In [50]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import OneHotEncoder

In [51]:
dataset = pd.read_csv('dataset2.csv')
dataset.head()

   Col1       Col2  Col3    Col4  Col5   Col6               Class
0     6  Chevrolet    31    Male   679  76960                Rich
1     8        BMW    51    Male   883  89304                Rich
2     7      Honda    45    Male   911  77018  Upper Middle Class
3     8        BMW    59  Female  1675  26160        Middle Class
4    10  Chevrolet    44    Male  1040  82055        Middle Class

In [52]:
X = dataset.iloc[:,:-1] 
y = dataset.iloc[:,-1:]
X

     Col1       Col2  Col3    Col4  Col5   Col6
0       6  Chevrolet    31    Male   679  76960
1       8        BMW    51    Male   883  89304
2       7      Honda    45    Male   911  77018
3       8        BMW    59  Female  1675  26160
4      10  Chevrolet    44    Male  1040  82055
..    ...        ...   ...     ...   ...    ...
995    10      Honda    77    Male   606  70132
996     3        BMW    74    Male  1850  83876
997     3  Chevrolet    86    Male   913  71429
998    10        BMW    58    Male  1828  69289
999     1     Toyota    49    Male  1746  96361

[1000 rows x 6 columns]

In [53]:
labelencoder_X=LabelEncoder()
z = X.iloc[:,1:2]  
X.iloc[:,1:2] = labelencoder_X.fit_transform(z.values.ravel())

C:\Users\User\AppData\Local\Temp\ipykernel_3592\1020965164.py:3: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  X.iloc[:,1:2] = labelencoder_X.fit_transform(z.values.ravel())

In [54]:
labelencoder_X=LabelEncoder()
z = X.iloc[:,3:4]  
X.iloc[:,3:4] = labelencoder_X.fit_transform(z.values.ravel())

C:\Users\User\AppData\Local\Temp\ipykernel_3592\2252864314.py:3: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  X.iloc[:,3:4] = labelencoder_X.fit_transform(z.values.ravel())

In [55]:
encoder = LabelEncoder()
encoder.fit(y)
y = encoder.transform(y)

C:\Users\User\AppData\Roaming\Python\Python310\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\User\AppData\Roaming\Python\Python310\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [57]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [58]:
regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.77575
Mean Squared Error: 0.7962375
Root Mean Squared Error: 0.8923214107035649