## Plzeňský kraj školy

In [46]:
import pandas
import xml.etree.ElementTree as ET
import re
xml_soubor = 'plzensky_puvodni.xml'

In [47]:

tree = ET.parse('plzensky_puvodni.xml')
root = tree.getroot()

skoly = []
for entry in root.findall('PravniSubjekt'):
    skola_group = entry.find('SkolyZarizeni')
    for skola in skola_group.findall('SkolaZarizeni'):
        izo = skola.find('IZO').text
        typ = skola.find('SkolaDruhTyp').text
        nazev = skola.find('SkolaPlnyNazev').text
        adresa = skola.find('SkolaMistaVykonuCinnosti')
        actual_ad = adresa.find('SkolaMistoVykonuCinnosti')
        adresa1 =  actual_ad.find('MistoAdresa1').text
        adresa2 =  actual_ad.find('MistoAdresa2').text
        adresa3 =  actual_ad.find('MistoAdresa3').text
        if adresa3 == None:
            adresa3 = adresa2
        #izoluji název obce regulárním výrazem a ukládám do sloupce obec
        pattern1 = r' \d\d '
        list_obec = re.split(pattern1, adresa3)
        obec = list_obec[-1]
        #izoluji psč
        pattern2 = r' [A-ZÁČĎŘŠŤÚŽ]'
        list_obec = re.split(pattern2, adresa3)
        PSC = list_obec[0]
        #přidávám sloupec kraj
        kraj = 'Plzeňský kraj'
        
        if typ == 'C00':  # číselník pro SŠ
            obor = skola.find('SkolaOboryVzdelani')
            actual_obor = obor.find('SkolaOborVzdelani')
            obor_kod = actual_obor.find('OborKod').text
            obor_nazev = actual_obor.find('OborNazev').text
            obor_forma = actual_obor.find('FormaVzdelavani').text
            obor_delka = actual_obor.find('DelkaVzdelavani').text
            obor_kapacita = actual_obor.find('OborKapacita').text
            
            skoly.append([izo, nazev, typ, adresa1, adresa2, adresa3, PSC, obec, kraj, obor_kod, obor_nazev, obor_forma, obor_delka, obor_kapacita])

sloupce = ['id', 'nazev', 'typ', 'adresa1', 'adresa2', 'adresa3', 'PSC', 'obec', 'kraj', 'obor_kod', 'obor_nazev', 'obor_forma', 'obor_delka', 'obor_kapacita']
df_skoly_plzensky = pandas.DataFrame(skoly, columns = sloupce)

pandas.set_option('display.max_rows', None)  # chci vidět všechny řádky
df_skoly_plzensky

,id,nazev,typ,adresa1,adresa2,adresa3,PSC,obec,kraj,obor_kod,obor_nazev,obor_forma,obor_delka,obor_kapacita
0,048342912,Střední škola,C00,Pivovarská 323,Týnské Předměstí,344 01 Domažlice,344 01,Domažlice,Plzeňský kraj,7941K41,Gymnázium,10,40,132
1,110026420,Střední škola,C00,Trnkova 125,Staňkov I,345 61 Staňkov,345 61,Staňkov,Plzeňský kraj,3656H01,Kominík,10,30,90
2,048342939,Střední škola,C00,Erbenova 184,Týnské Předměstí,344 01 Domažlice,344 01,Domažlice,Plzeňský kraj,1820M01,Informační technologie,10,40,110
3,018230083,Střední škola,C00,Prokopa Velikého 640,Týnské Předměstí,344 01 Domažlice,344 01,Domažlice,Plzeňský kraj,2345L01,Mechanik seřizovač,10,40,180
4,000076996,Střední škola,C00,Národních mučedníků 347,Klatovy IV,339 01 Klatovy,339 01,Klatovy,Plzeňský kraj,7941K41,Gymnázium,10,40,260
5,000077143,Střední škola,C00,nábř. Kpt. Nálepky 362,Klatovy III,339 01 Klatovy,339 01,Klatovy,Plzeňský kraj,2341M01,Strojírenství,10,40,120
6,000077003,Střední škola,C00,F. Procházky 324,Sušice II,342 01 Sušice,342 01,Sušice,Plzeňský kraj,7941K41,Gymnázium,10,40,150
7,000077232,Střední škola,C00,Plánická 196,Klatovy I,339 01 Klatovy,339 01,Klatovy,Plzeňský kraj,5341M01,Zdravotnický asistent,10,40,180
8,107840294,Střední škola,C00,Blatenská 313,341 01 Horažďovice,341 01 Horažďovice,341 01,Horažďovice,Plzeňský kraj,2954H01,Cukrář,10,30,72
9,107840308,Střední škola,C00,U Kapličky 761,Sušice II,342 01 Sušice,342 01,Sušice,Plzeňský kraj,2368H01,Mechanik opravář motorových vozidel,10,30,72
10,000077313,Střední škola,C00,Národních mučedníků 141,Klatovy IV,339 01 Klatovy,339 01,Klatovy,Plzeňský kraj,1601M01,Ekologie a životní prostředí,10,40,68
11,049778137,Střední škola,C00,Vejprnická 663/56,Skvrňany,318 00 Plzeň,318 00,Plzeň,Plzeňský kraj,7941K41,Gymnázium,10,40,136
12,000574406,Střední škola,C00,Klatovská třída 2778/200g,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,1820M01,Informační technologie,10,40,260
13,049774301,Střední škola,C00,Koterovská 828/85,Lobzy,326 00 Plzeň,326 00,Plzeň,Plzeňský kraj,1820M01,Informační technologie,10,40,600
14,049778099,Střední škola,C00,Petákova 2055/2,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,7941K41,Gymnázium,10,40,356
15,049778102,Střední škola,C00,Opavská 823/21,Doubravka,312 00 Plzeň,312 00,Plzeň,Plzeňský kraj,7941K41,Gymnázium,10,40,160
16,049778145,Střední škola,C00,Mikulášské náměstí 808/23,Východní Předměstí,326 00 Plzeň,326 00,Plzeň,Plzeňský kraj,7941K41,Gymnázium,10,40,358
17,064353389,Střední škola,C00,Tylova 988/18,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,6842L51,Bezpečnostní služby,24,30,90
18,049778161,Střední škola,C00,náměstí T. G. Masaryka 1530/13,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,6341M02,Obchodní akademie,10,40,544
19,000520152,Střední škola,C00,Nerudova 1214/33,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,6341M01,Ekonomika a podnikání,10,40,272
20,040527867,Střední škola,C00,Mikulášské náměstí 509/15,Východní Předměstí,326 00 Plzeň,326 00,Plzeň,Plzeňský kraj,7941K41,Gymnázium,22,40,100
21,049775961,Střední škola,C00,Sokolovská 1165/54,Bolevec,323 00 Plzeň,323 00,Plzeň,Plzeňský kraj,7941K41,Gymnázium,10,40,130
22,049776541,Střední škola,C00,Politických vězňů 2003/5,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,6341M02,Obchodní akademie,10,40,300
23,110037545,Střední škola,C00,Pod Vinicemi 889/82,Severní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,8241M01,Užitá malba,10,40,75
24,110034538,Střední škola,C00,Nade Mží 734/1,Skvrňany,318 00 Plzeň,318 00,Plzeň,Plzeňský kraj,6441L51,Podnikání,10,20,40
25,110100204,Střední škola,C00,U Borského parku 1213/3,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,2953H01,Pekař,10,30,90
26,000497061,Střední škola,C00,Borská 2718/55,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,2351H01,Strojní mechanik,10,30,60
27,049777149,Střední škola,C00,sady 5. května 2395/21,Východní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,6341M01,Ekonomika a podnikání,10,40,460
28,049778064,Střední škola,C00,Chodské náměstí 1585/2,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,3646M01,Geodézie a katastr nemovitostí,10,40,136
29,108005666,Střední škola,C00,Raisova 96,332 02 Starý Plzenec,332 02 Starý Plzenec,332 02,Starý Plzenec,Plzeňský kraj,6341M01,Ekonomika a podnikání,22,50,165
30,108005631,Střední škola,C00,Družstevní 650,336 13 Blovice,336 13 Blovice,336 13,Blovice,Plzeňský kraj,7941K41,Gymnázium,10,40,130
31,108005640,Střední škola,C00,č.p. 1,335 46 Oselce,335 46 Oselce,335 46,Oselce,Plzeňský kraj,2368H01,Mechanik opravář motorových vozidel,10,30,90
32,108005623,Střední škola,C00,Táborská 2081/28,Východní Předměstí,326 00 Plzeň,326 00,Plzeň,Plzeňský kraj,1601M01,Ekologie a životní prostředí,10,40,100
33,108032060,Střední škola,C00,Školní 280,331 01 Plasy,331 01 Plasy,331 01,Plasy,Plzeňský kraj,4141M01,Agropodnikání,10,40,120
34,107840359,Střední škola,C00,nám. Osvobození 32,331 41 Kralovice,331 41 Kralovice,331 41,Kralovice,Plzeňský kraj,2368H01,Mechanik opravář motorových vozidel,10,30,90
35,000479322,Střední škola,C00,Mládežníků 1115,Nové Město,337 01 Rokycany,337 01,Rokycany,Plzeňský kraj,1820M01,Informační technologie,10,40,120
36,018242171,Střední škola,C00,Jeřabinová 96,Plzeňské Předměstí,337 01 Rokycany,337 01,Rokycany,Plzeňský kraj,2343L51,Provozní technika,10,20,60
37,102100675,Střední škola,C00,Soběslavova 1426,349 01 Stříbro,349 01 Stříbro,349 01,Stříbro,Plzeňský kraj,6341M02,Obchodní akademie,10,40,132
38,000479021,Střední škola,C00,Pionýrská 1370,347 01 Tachov,347 01 Tachov,347 01,Tachov,Plzeňský kraj,7941K61,Gymnázium,10,60,360
39,110017501,Střední škola,C00,Plzeňská 231,348 02 Bor,348 02 Bor,348 02,Bor,Plzeňský kraj,2351E01,Strojírenské práce,10,30,36
40,048326437,Střední škola,C00,Kostelní 129,348 15 Planá,348 15 Planá,348 15,Planá,Plzeňský kraj,2659H01,Spojový mechanik,10,30,36
41,000077348,Střední škola,C00,Benešova 508,349 01 Stříbro,349 01 Stříbro,349 01,Stříbro,Plzeňský kraj,1820M01,Informační technologie,10,40,120
42,110030966,Střední škola,C00,Karlovarská 1210/99,Bolevec,323 00 Plzeň,323 00,Plzeň,Plzeňský kraj,5341H01,Ošetřovatel,10,30,120
43,000574961,Střední škola,C00,K terénu 64,Plzeňské Předměstí,346 01 Horšovský Týn,346 01,Horšovský Týn,Plzeňský kraj,2951E01,Potravinářská výroba,10,30,24
44,049774859,Střední škola,C00,Vejprnická 663/56,Skvrňany,318 00 Plzeň,318 00,Plzeň,Plzeňský kraj,2351E01,Strojírenské práce,10,30,72
45,181077639,Střední škola,C00,Husova 346,334 52 Merklín,334 52 Merklín,334 52,Merklín,Plzeňský kraj,7862C01,Praktická škola jednoletá,10,10,24
46,108032019,Střední škola,C00,Macháčkova 905/45,Skvrňany,318 00 Plzeň,318 00,Plzeň,Plzeňský kraj,4152E02,Zahradnická výroba,10,20,22
47,150069685,Střední škola,C00,Chodské náměstí 131,345 25 Hostouň,345 25 Hostouň,345 25,Hostouň,Plzeňský kraj,4151E01,Zemědělské práce,10,30,24
48,110034791,Střední škola,C00,č.p. 1,338 08 Terešov,338 08 Terešov,338 08,Terešov,Plzeňský kraj,2351E01,Strojírenské práce,10,30,32
49,000376469,Střední škola,C00,Jana Littrowa 122,Velké Předměstí,346 01 Horšovský Týn,346 01,Horšovský Týn,Plzeňský kraj,2368H01,Mechanik opravář motorových vozidel,10,30,96
50,000523925,Střední škola,C00,Škroupova 209/13,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,3143M01,Oděvnictví,10,40,220
51,000520110,Střední škola,C00,Světce 1,347 01 Tachov,347 01 Tachov,347 01,Tachov,Plzeňský kraj,1820M01,Informační technologie,10,40,132
52,110100549,Střední škola,C00,Karlovarská 1210/99,Bolevec,323 00 Plzeň,323 00,Plzeň,Plzeňský kraj,2345M01,Dopravní prostředky,10,40,264
53,110100590,Střední škola,C00,Vejprnická 663/56,Skvrňany,318 00 Plzeň,318 00,Plzeň,Plzeňský kraj,1820M01,Informační technologie,10,40,256
54,110100662,Střední škola,C00,Klatovská třída 1615/109,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,2153H01,Modelář,10,30,72
55,181121379,Střední škola,C00,Husova 1126/43,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,7842M06,Kombinované lyceum,10,40,130

In [48]:
df_skoly_plzensky['adresa3'].isna().sum()

0

In [49]:
df_skoly_plzensky['adresa3'].unique()

array(['344 01 Domažlice', '345 61 Staňkov', '339 01 Klatovy',
       '342 01 Sušice', '341 01 Horažďovice', '318 00 Plzeň',
       '301 00 Plzeň', '326 00 Plzeň', '312 00 Plzeň', '323 00 Plzeň',
       '332 02 Starý Plzenec', '336 13 Blovice', '335 46 Oselce',
       '331 01 Plasy', '331 41 Kralovice', '337 01 Rokycany',
       '349 01 Stříbro', '347 01 Tachov', '348 02 Bor', '348 15 Planá',
       '346 01 Horšovský Týn', '334 52 Merklín', '345 25 Hostouň',
       '338 08 Terešov'], dtype=object)

přidávám sloupec okres a PSC

In [50]:
vazba_obec_psc_okres = pandas.read_csv("vazba_obec_psc_okres.csv")

In [51]:
df_plzensky_kraj_final = pandas.merge(df_skoly_plzensky, vazba_obec_psc_okres, on=['PSC', 'obec'], how='left')

In [52]:
df_plzensky_kraj_final['okres'].isna().sum()

1

In [53]:
pandas.set_option('display.max_rows', None)
df_plzensky_kraj_final

,id,nazev,typ,adresa1,adresa2,adresa3,PSC,obec,kraj,obor_kod,obor_nazev,obor_forma,obor_delka,obor_kapacita,okres
0,048342912,Střední škola,C00,Pivovarská 323,Týnské Předměstí,344 01 Domažlice,344 01,Domažlice,Plzeňský kraj,7941K41,Gymnázium,10,40,132,Domažlice
1,110026420,Střední škola,C00,Trnkova 125,Staňkov I,345 61 Staňkov,345 61,Staňkov,Plzeňský kraj,3656H01,Kominík,10,30,90,Domažlice
2,048342939,Střední škola,C00,Erbenova 184,Týnské Předměstí,344 01 Domažlice,344 01,Domažlice,Plzeňský kraj,1820M01,Informační technologie,10,40,110,Domažlice
3,018230083,Střední škola,C00,Prokopa Velikého 640,Týnské Předměstí,344 01 Domažlice,344 01,Domažlice,Plzeňský kraj,2345L01,Mechanik seřizovač,10,40,180,Domažlice
4,000076996,Střední škola,C00,Národních mučedníků 347,Klatovy IV,339 01 Klatovy,339 01,Klatovy,Plzeňský kraj,7941K41,Gymnázium,10,40,260,Klatovy
5,000077143,Střední škola,C00,nábř. Kpt. Nálepky 362,Klatovy III,339 01 Klatovy,339 01,Klatovy,Plzeňský kraj,2341M01,Strojírenství,10,40,120,Klatovy
6,000077003,Střední škola,C00,F. Procházky 324,Sušice II,342 01 Sušice,342 01,Sušice,Plzeňský kraj,7941K41,Gymnázium,10,40,150,Klatovy
7,000077232,Střední škola,C00,Plánická 196,Klatovy I,339 01 Klatovy,339 01,Klatovy,Plzeňský kraj,5341M01,Zdravotnický asistent,10,40,180,Klatovy
8,107840294,Střední škola,C00,Blatenská 313,341 01 Horažďovice,341 01 Horažďovice,341 01,Horažďovice,Plzeňský kraj,2954H01,Cukrář,10,30,72,Klatovy
9,107840308,Střední škola,C00,U Kapličky 761,Sušice II,342 01 Sušice,342 01,Sušice,Plzeňský kraj,2368H01,Mechanik opravář motorových vozidel,10,30,72,Klatovy
10,000077313,Střední škola,C00,Národních mučedníků 141,Klatovy IV,339 01 Klatovy,339 01,Klatovy,Plzeňský kraj,1601M01,Ekologie a životní prostředí,10,40,68,Klatovy
11,049778137,Střední škola,C00,Vejprnická 663/56,Skvrňany,318 00 Plzeň,318 00,Plzeň,Plzeňský kraj,7941K41,Gymnázium,10,40,136,Plzeň-město
12,000574406,Střední škola,C00,Klatovská třída 2778/200g,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,1820M01,Informační technologie,10,40,260,Plzeň-město
13,049774301,Střední škola,C00,Koterovská 828/85,Lobzy,326 00 Plzeň,326 00,Plzeň,Plzeňský kraj,1820M01,Informační technologie,10,40,600,Plzeň-město
14,049778099,Střední škola,C00,Petákova 2055/2,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,7941K41,Gymnázium,10,40,356,Plzeň-město
15,049778102,Střední škola,C00,Opavská 823/21,Doubravka,312 00 Plzeň,312 00,Plzeň,Plzeňský kraj,7941K41,Gymnázium,10,40,160,Plzeň-město
16,049778145,Střední škola,C00,Mikulášské náměstí 808/23,Východní Předměstí,326 00 Plzeň,326 00,Plzeň,Plzeňský kraj,7941K41,Gymnázium,10,40,358,Plzeň-město
17,064353389,Střední škola,C00,Tylova 988/18,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,6842L51,Bezpečnostní služby,24,30,90,Plzeň-město
18,049778161,Střední škola,C00,náměstí T. G. Masaryka 1530/13,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,6341M02,Obchodní akademie,10,40,544,Plzeň-město
19,000520152,Střední škola,C00,Nerudova 1214/33,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,6341M01,Ekonomika a podnikání,10,40,272,Plzeň-město
20,040527867,Střední škola,C00,Mikulášské náměstí 509/15,Východní Předměstí,326 00 Plzeň,326 00,Plzeň,Plzeňský kraj,7941K41,Gymnázium,22,40,100,Plzeň-město
21,049775961,Střední škola,C00,Sokolovská 1165/54,Bolevec,323 00 Plzeň,323 00,Plzeň,Plzeňský kraj,7941K41,Gymnázium,10,40,130,Plzeň-město
22,049776541,Střední škola,C00,Politických vězňů 2003/5,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,6341M02,Obchodní akademie,10,40,300,Plzeň-město
23,110037545,Střední škola,C00,Pod Vinicemi 889/82,Severní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,8241M01,Užitá malba,10,40,75,Plzeň-město
24,110034538,Střední škola,C00,Nade Mží 734/1,Skvrňany,318 00 Plzeň,318 00,Plzeň,Plzeňský kraj,6441L51,Podnikání,10,20,40,Plzeň-město
25,110100204,Střední škola,C00,U Borského parku 1213/3,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,2953H01,Pekař,10,30,90,Plzeň-město
26,000497061,Střední škola,C00,Borská 2718/55,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,2351H01,Strojní mechanik,10,30,60,Plzeň-město
27,049777149,Střední škola,C00,sady 5. května 2395/21,Východní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,6341M01,Ekonomika a podnikání,10,40,460,Plzeň-město
28,049778064,Střední škola,C00,Chodské náměstí 1585/2,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,3646M01,Geodézie a katastr nemovitostí,10,40,136,Plzeň-město
29,108005666,Střední škola,C00,Raisova 96,332 02 Starý Plzenec,332 02 Starý Plzenec,332 02,Starý Plzenec,Plzeňský kraj,6341M01,Ekonomika a podnikání,22,50,165,Plzeň-město
30,108005631,Střední škola,C00,Družstevní 650,336 13 Blovice,336 13 Blovice,336 13,Blovice,Plzeňský kraj,7941K41,Gymnázium,10,40,130,NaN
31,108005640,Střední škola,C00,č.p. 1,335 46 Oselce,335 46 Oselce,335 46,Oselce,Plzeňský kraj,2368H01,Mechanik opravář motorových vozidel,10,30,90,Plzeň-jih
32,108005623,Střední škola,C00,Táborská 2081/28,Východní Předměstí,326 00 Plzeň,326 00,Plzeň,Plzeňský kraj,1601M01,Ekologie a životní prostředí,10,40,100,Plzeň-město
33,108032060,Střední škola,C00,Školní 280,331 01 Plasy,331 01 Plasy,331 01,Plasy,Plzeňský kraj,4141M01,Agropodnikání,10,40,120,Plzeň-sever
34,107840359,Střední škola,C00,nám. Osvobození 32,331 41 Kralovice,331 41 Kralovice,331 41,Kralovice,Plzeňský kraj,2368H01,Mechanik opravář motorových vozidel,10,30,90,Plzeň-sever
35,000479322,Střední škola,C00,Mládežníků 1115,Nové Město,337 01 Rokycany,337 01,Rokycany,Plzeňský kraj,1820M01,Informační technologie,10,40,120,Rokycany
36,018242171,Střední škola,C00,Jeřabinová 96,Plzeňské Předměstí,337 01 Rokycany,337 01,Rokycany,Plzeňský kraj,2343L51,Provozní technika,10,20,60,Rokycany
37,102100675,Střední škola,C00,Soběslavova 1426,349 01 Stříbro,349 01 Stříbro,349 01,Stříbro,Plzeňský kraj,6341M02,Obchodní akademie,10,40,132,Tachov
38,000479021,Střední škola,C00,Pionýrská 1370,347 01 Tachov,347 01 Tachov,347 01,Tachov,Plzeňský kraj,7941K61,Gymnázium,10,60,360,Tachov
39,110017501,Střední škola,C00,Plzeňská 231,348 02 Bor,348 02 Bor,348 02,Bor,Plzeňský kraj,2351E01,Strojírenské práce,10,30,36,Tachov
40,048326437,Střední škola,C00,Kostelní 129,348 15 Planá,348 15 Planá,348 15,Planá,Plzeňský kraj,2659H01,Spojový mechanik,10,30,36,Tachov
41,000077348,Střední škola,C00,Benešova 508,349 01 Stříbro,349 01 Stříbro,349 01,Stříbro,Plzeňský kraj,1820M01,Informační technologie,10,40,120,Tachov
42,110030966,Střední škola,C00,Karlovarská 1210/99,Bolevec,323 00 Plzeň,323 00,Plzeň,Plzeňský kraj,5341H01,Ošetřovatel,10,30,120,Plzeň-město
43,000574961,Střední škola,C00,K terénu 64,Plzeňské Předměstí,346 01 Horšovský Týn,346 01,Horšovský Týn,Plzeňský kraj,2951E01,Potravinářská výroba,10,30,24,Domažlice
44,049774859,Střední škola,C00,Vejprnická 663/56,Skvrňany,318 00 Plzeň,318 00,Plzeň,Plzeňský kraj,2351E01,Strojírenské práce,10,30,72,Plzeň-město
45,181077639,Střední škola,C00,Husova 346,334 52 Merklín,334 52 Merklín,334 52,Merklín,Plzeňský kraj,7862C01,Praktická škola jednoletá,10,10,24,Plzeň-jih
46,108032019,Střední škola,C00,Macháčkova 905/45,Skvrňany,318 00 Plzeň,318 00,Plzeň,Plzeňský kraj,4152E02,Zahradnická výroba,10,20,22,Plzeň-město
47,150069685,Střední škola,C00,Chodské náměstí 131,345 25 Hostouň,345 25 Hostouň,345 25,Hostouň,Plzeňský kraj,4151E01,Zemědělské práce,10,30,24,Domažlice
48,110034791,Střední škola,C00,č.p. 1,338 08 Terešov,338 08 Terešov,338 08,Terešov,Plzeňský kraj,2351E01,Strojírenské práce,10,30,32,Rokycany
49,000376469,Střední škola,C00,Jana Littrowa 122,Velké Předměstí,346 01 Horšovský Týn,346 01,Horšovský Týn,Plzeňský kraj,2368H01,Mechanik opravář motorových vozidel,10,30,96,Domažlice
50,000523925,Střední škola,C00,Škroupova 209/13,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,3143M01,Oděvnictví,10,40,220,Plzeň-město
51,000520110,Střední škola,C00,Světce 1,347 01 Tachov,347 01 Tachov,347 01,Tachov,Plzeňský kraj,1820M01,Informační technologie,10,40,132,Tachov
52,110100549,Střední škola,C00,Karlovarská 1210/99,Bolevec,323 00 Plzeň,323 00,Plzeň,Plzeňský kraj,2345M01,Dopravní prostředky,10,40,264,Plzeň-město
53,110100590,Střední škola,C00,Vejprnická 663/56,Skvrňany,318 00 Plzeň,318 00,Plzeň,Plzeňský kraj,1820M01,Informační technologie,10,40,256,Plzeň-město
54,110100662,Střední škola,C00,Klatovská třída 1615/109,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,2153H01,Modelář,10,30,72,Plzeň-město
55,181121379,Střední škola,C00,Husova 1126/43,Jižní Předměstí,301 00 Plzeň,301 00,Plzeň,Plzeňský kraj,7842M06,Kombinované lyceum,10,40,130,Plzeň-město

In [54]:
df_plzensky_kraj_final.loc[30, 'okres'] = 'Plzeň-jih'

In [55]:
df_plzensky_kraj_final['okres'].isna().sum()

0

In [56]:
#ukládám do csv
df_plzensky_kraj_final.to_csv('skoly_Plzensky_final.csv', index = None)