
# Assignment 1: Sci-Kit Learn machine learning preprocessing pipeline

This notebook contains a set of exercises that will guide you through the different steps of this assignment. Solutions must be code-based, _i.e._ hard-coded or manually computed results will not be accepted. Remember to write your solutions to each exercise in the dedicated cells and not modify or remove the test cells. When completing all the exercises submit this same notebook back to Moodle in **.ipynb** format.

<div class="alert alert-success">

<b>About the datasets used in this assignment</b>

<u>Context</u>

Superheroes have been in popular culture for a long time, and now more than ever. Since its creation, superheroes have not been diverse, but this is changing rapidly. The two datasets aim to provide an overview of heroes and their physical and power characteristics, helping curious people to identify trends and patterns. In this case, we want to understand how physical attributes and powers define superheroes' alignment (superhero, supervillain).

<u>Content</u>
    
The columns included in both datasets are: 
- **Dataset part 1**: Name, Gender, Eye color, Race, Hair color, Height, Publisher, Skin color, Alignment, Weight,Has Superpowers, Power Level, Intelligence Level
- **Dataset part 2**: Previous columns and, Agility, Accelerated Healing, Lantern Power Ring, Dimensional Awareness, Cold Resistance, Durability, Stealth, Energy Absorption, Flight, Danger Sense, Underwater breathing, Marksmanship, Weapons Master, Power Augmentation, Animal Attributes, Longevity, Intelligence, Super Strength, Cryokinesis, Telepathy, Energy Armor, Energy Blasts, Duplication, Size Changing, Density Control, Stamina, Astral Travel,Audio Control, Dexterity, Omnitrix, Super Speed, Possession, Animal Oriented Powers, Weapon-based Powers, Electrokinesis, Darkforce Manipulation, Death Touch, Teleportation, Enhanced Senses, Telekinesis, Energy Beams, Magic, Hyperkinesis, Jump, Clairvoyance, Dimensional Travel, Power Sense, Shapeshifting, Peak Human Condition, Immortality, Camouflage, Element Control, Phasing, Astral Projection, Electrical Transport, Fire Control,Projection, Summoning, Enhanced Memory, Reflexes, Invulnerability, Energy Constructs, Force Fields, Self-Sustenance ,Anti-Gravity, Empathy, Power Nullifier, Radiation Control, Psionic Powers, Elasticity, Substance Secretion, Elemental Transmogrification, Technopath/Cyberpath, Photographic Reflexes, Seismic Power, Animation, Precognition, Mind Control, Fire Resistance, Power Absorption, Enhanced Hearing, Nova Force, Insanity, Hypnokinesis, Animal Control, Natural Armor, Intangibility, Enhanced Sight, Molecular Manipulation, Heat Generation, Adaptation, Gliding, Power Suit, Mind Blast, Probability Manipulation, Gravity Control, Regeneration, Light Control, Echolocation, Levitation, Toxin and Disease Control, Banish, Energy Manipulation, Heat Resistance, Natural Weapons, Time Travel, Enhanced Smell, Illusions, Thirstokinesis, Hair Manipulation, Illumination, Omnipotent, Cloaking, Changing Armor, Power Cosmic, Biokinesis, Water Control, Radiation Immunity, Vision - Telescopic, Toxin and Disease Resistance, Spatial Awareness, Energy Resistance, Telepathy Resistance, Molecular Combustion, Omnilingualism, Portal Creation, Magnetism, Mind Control Resistance, Plant Control, Sonar, Sonic Scream, Time Manipulation, Enhanced Touch, Magic Resistance, Invisibility, Sub-Mariner, Radiation Absorption, Intuitive aptitude, Vision - Microscopic, Melting, Wind Control, Super Breath, Wallcrawling, Vision - Night, Vision - Infrared, Grim Reaping, Matter Absorption, The Force, Resurrection, Terrakinesis, Vision - Heat, Vitakinesis, Radar Sense, Qwardian Power Ring, Weather Control, Vision - X-Ray, Vision - Thermal, Web Creation, Reality Warping, Odin Force, Symbiote Costume, Speed Force, Phoenix Force, Molecular Dissipation, Vision - Cryo, Omnipresent, Omniscient.

Column names are self-explanatory. Physical attributes are numerical or categorical, while superpowers are dummy (Onehot) variables.
    
 <u>Inspiration</u>

What are the characteristics of your favorite superheroes? Are these characteristics affecting superheroes' alignment? Let's put some light on this important business question.

</div>

<div class="alert alert-danger"><b>Submission deadline:</b> Friday, October 18th, 23:55</div>

In [1]:
# DO NOT MODIFY NOR ADD CODE TO THIS CELL
import pandas as pd
from sklearn import set_config

set_config(transform_output="pandas")

df = pd.read_csv('https://raw.githubusercontent.com/jnin/information-systems/refs/heads/main/data/superheroes_%20physical_traits.csv')

<div class="alert alert-info"><b>Exercise 1: Creating the Feature Matrix and Target Array</b>

Write the code to create the feature matrix ```X``` and the target array ```y``` from the dataframe ```df```. When creating ```X```, make sure to drop or ignore the irrelevant columns: ```['Name', 'Publisher']```.

The target variable for this problem is ```Alignment```.

<br><i>[0.5 points]</i>
</div>
<div class="alert alert-warning">
    
Python is case-sensitive, so ensure your code matches the required capitalization.
Do **not** download the dataset manually. Instead, run the previous cell to load the data directly from the provided link.

</div>

In [2]:
X = df.drop(columns=['Name','Publisher','Alignment'])
X

,Gender,Eye color,Race,Hair color,Height,Skin color,Weight,Has Superpowers,Power Level,Intelligence Level
0,Male,yellow,Human,No Hair,203.0,NaN,441.0,False,Extremely Powerful,Super-Genius
1,Male,blue,Icthyo Sapien,No Hair,191.0,blue,65.0,True,Below Average,Average Intelligence
2,Male,blue,Ungaran,No Hair,185.0,red,90.0,True,Average,Low Intelligence
3,Male,green,Human / Radiation,No Hair,203.0,NaN,441.0,False,Extremely Powerful,Smart
4,Male,blue,Cosmic Entity,Black,-99.0,NaN,-99.0,False,Extremely Powerful,Genius
...,...,...,...,...,...,...,...,...,...,...
729,Female,blue,Human,Strawberry Blond,165.0,NaN,52.0,True,Below Average,Genius
730,Male,white,Frost Giant,No Hair,304.8,white,-99.0,True,Extremely Powerful,Smart
731,Male,brown,Yoda's species,White,66.0,green,17.0,False,Above Average,Super-Genius
732,Female,blue,Human,Black,170.0,NaN,57.0,True,Average,Smart
733,Male,red,NaN,Brown,185.0,NaN,81.0,True,Below Average,Genius

In [3]:
y = df[['Alignment']]
y

    Alignment
0        good
1        good
2        good
3         bad
4         bad
..        ...
729      good
730      good
731      good
732      good
733       bad

[734 rows x 1 columns]

In [4]:
# LEAVE BLANK

In [5]:
# LEAVE BLANK

<div class="alert alert-info"><b>Exercise 2: Imputing Missing Values </b> 

The first step in our preprocessing routine is to handle missing values in the feature matrix ```X```. Write the code to instantiate a ```SimpleImputer``` with a ```most_frequent``` strategy, naming it ```imputer```. Then, test the imputer transforming ```X```, and store the transformed data in a new DataFrame called ```X_imputed```.

<br><i>[0.5 points]</i>
</div>

In [6]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='most_frequent')
X_imputed = imputer.fit_transform(X)
X_imputed

#print(X.isna().sum())

#checking if the imputer worked.
X_imputed.isna().sum()

Gender                0
Eye color             0
Race                  0
Hair color            0
Height                0
Skin color            0
Weight                0
Has Superpowers       0
Power Level           0
Intelligence Level    0
dtype: int64

In [7]:
# LEAVE BLANK

In [8]:
# LEAVE BLANK

<div class="alert alert-info"><b>Exercise 3: Encoding Categorical Features</b> 

Now that our dataset is free of missing values, let's handle the categorical columns. Create a `OneHotEncoder` object named `one_hot_encoder`. Next, create a DataFrame called `X_categorical` containing the following columns from `X_imputed`: `['Gender', 'Eye color', 'Race', 'Hair color', 'Skin color']`. 

Test the encoder by transforming the features of `X_categorical`, and store the transformed data in a new DataFrame named `X_categorical_encoded`.

<br><i>[0.75 points]</i>
</div>

In [9]:
from sklearn.preprocessing import OneHotEncoder

one_hot_encoder = OneHotEncoder(sparse_output=False)
X_categorical = X_imputed[['Gender','Eye color','Race','Hair color','Skin color']]
X_categorical_encoded = one_hot_encoder.fit_transform(X_categorical)
X_categorical_encoded

,Gender_Female,Gender_Male,Eye color_amber,Eye color_black,Eye color_blue,Eye color_blue / white,Eye color_bown,Eye color_brown,Eye color_gold,Eye color_green,...,Skin color_grey,Skin color_orange,Skin color_orange / white,Skin color_pink,Skin color_purple,Skin color_red,Skin color_red / black,Skin color_silver,Skin color_white,Skin color_yellow
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
730,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
731,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
732,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
733,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
# LEAVE BLANK

In [11]:
# LEAVE BLANK

In [12]:
# LEAVE BLANK

<div class="alert alert-info"><b>Exercise 4: Encoding Ordinal Features </b> 

Next, repeat the process for the ordinal features `['Power Level', 'Intelligence Level']`. First, create a new DataFrame called `X_ordinal` containing these two columns. Then, instantiate an `OrdinalEncoder` and name it `ordinal_encoder`. 

Test the encoder by transforming the `X_ordinal` DataFrame, and store the transformed data in a new DataFrame called `X_ordinal_encoded`.

<br><i>[0.75 points]</i>
</div>

<div class="alert alert-warning">
    
Consider that the integer values assigned to each label should align with a meaningful interpretation of the label's significance.

</div>

In [13]:
from sklearn.preprocessing import OrdinalEncoder

X_ordinal=X_imputed[['Power Level','Intelligence Level']]

#finding out what the different categories are
unique_power=df['Power Level'].unique()
print(unique_power)
unique_intelligence=df['Intelligence Level'].unique()
print(unique_intelligence)

categories=[['Weak','Below Average','Average','Above Average','Extremely Powerful'],
            ['Low Intelligence','Average Intelligence','Smart','Genius','Super-Genius']]

ordinal_encoder = OrdinalEncoder(categories=categories)

X_ordinal_encoded = ordinal_encoder.fit_transform(X_ordinal)
X_ordinal_encoded

['Extremely Powerful' 'Below Average' 'Average' 'Above Average' 'Weak']
['Super-Genius' 'Average Intelligence' 'Low Intelligence' 'Smart' 'Genius']

     Power Level  Intelligence Level
0            4.0                 4.0
1            1.0                 1.0
2            2.0                 0.0
3            4.0                 2.0
4            4.0                 3.0
..           ...                 ...
729          1.0                 3.0
730          4.0                 2.0
731          3.0                 4.0
732          2.0                 2.0
733          1.0                 3.0

[734 rows x 2 columns]

In [14]:
# LEAVE BLANK

In [15]:
# LEAVE BLANK

<div class="alert alert-info"><b>Exercise 5: Combining Feature Transformations </b> 

Now that we have confirmed the transformations for categorical and ordinal columns, let's use a `ColumnTransformer` to apply them in parallel. Instantiate a `ColumnTransformer` named `transformer`, including both the `OneHotEncoder` and `OrdinalEncoder`. Be sure to specify the correct column names for each transformer.

Test your `transformer` by applying it to the `X_imputed` DataFrame, and store the transformed data in a new DataFrame called `X_encoded`.

<br><i>[1 points]</i>
</div>

In [16]:
from sklearn.compose import ColumnTransformer
categorical_columns=['Gender','Eye color','Race','Hair color','Skin color']
ordinal_columns=['Power Level','Intelligence Level']


transformer = ColumnTransformer(
    transformers=
        [('categorical', one_hot_encoder, categorical_columns),
        ('ordinal', ordinal_encoder , ordinal_columns)],
    remainder='passthrough')

X_encoded= transformer.fit_transform(X_imputed)

X_encoded

,categorical__Gender_Female,categorical__Gender_Male,categorical__Eye color_amber,categorical__Eye color_black,categorical__Eye color_blue,categorical__Eye color_blue / white,categorical__Eye color_bown,categorical__Eye color_brown,categorical__Eye color_gold,categorical__Eye color_green,...,categorical__Skin color_red,categorical__Skin color_red / black,categorical__Skin color_silver,categorical__Skin color_white,categorical__Skin color_yellow,ordinal__Power Level,ordinal__Intelligence Level,remainder__Height,remainder__Weight,remainder__Has Superpowers
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,4.0,203.0,441.0,False
1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,191.0,65.0,True
2,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,2.0,0.0,185.0,90.0,True
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,4.0,2.0,203.0,441.0,False
4,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,3.0,-99.0,-99.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,3.0,165.0,52.0,True
730,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,4.0,2.0,304.8,-99.0,True
731,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,4.0,66.0,17.0,False
732,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,2.0,170.0,57.0,True
733,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,3.0,185.0,81.0,True

In [17]:
# LEAVE BLANK

In [18]:
# LEAVE BLANK

In [19]:
# LEAVE BLANK

<div class="alert alert-info"><b>Exercise 6: Standardizing the Features </b> 

To prevent potential issues with feature scaling, we will standardize the features using a `StandardScaler`. First, instantiate a `StandardScaler` and assign it to the variable `scaler`. Then, test it by transforming the `X_encoded` DataFrame. Store the scaled data in a new DataFrame called `X_scaled`.

 <br><i>[0.5 points]</i>
</div>

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_encoded)
X_scaled

,categorical__Gender_Female,categorical__Gender_Male,categorical__Eye color_amber,categorical__Eye color_black,categorical__Eye color_blue,categorical__Eye color_blue / white,categorical__Eye color_bown,categorical__Eye color_brown,categorical__Eye color_gold,categorical__Eye color_green,...,categorical__Skin color_red,categorical__Skin color_red / black,categorical__Skin color_silver,categorical__Skin color_white,categorical__Skin color_yellow,ordinal__Power Level,ordinal__Intelligence Level,remainder__Height,remainder__Weight,remainder__Has Superpowers
0,-0.611990,0.611990,-0.052271,-0.179858,-1.085376,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,1.427113,1.445132,0.722041,3.039988,-0.983783
1,-0.611990,0.611990,-0.052271,-0.179858,0.921340,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,-0.725286,-0.686268,0.636037,0.164673,1.016485
2,-0.611990,0.611990,-0.052271,-0.179858,0.921340,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,8.975275,-0.036936,-0.082817,-0.098125,-0.052271,-0.007820,-1.396735,0.593036,0.355851,1.016485
3,-0.611990,0.611990,-0.052271,-0.179858,-1.085376,-0.036936,-0.036936,-0.455233,-0.064062,3.009119,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,1.427113,0.024198,0.722041,3.039988,-0.983783
4,-0.611990,0.611990,-0.052271,-0.179858,0.921340,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,1.427113,0.734665,-1.442378,-1.089453,-0.983783
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,1.634013,-1.634013,-0.052271,-0.179858,0.921340,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,-0.725286,0.734665,0.449697,0.065261,1.016485
730,-0.611990,0.611990,-0.052271,-0.179858,-1.085376,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,10.191032,-0.052271,1.427113,0.024198,1.451636,-1.089453,1.016485
731,-0.611990,0.611990,-0.052271,-0.179858,-1.085376,-0.036936,-0.036936,2.196679,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,0.709647,1.445132,-0.259831,-0.202388,-0.983783
732,1.634013,-1.634013,-0.052271,-0.179858,0.921340,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,-0.007820,0.024198,0.485531,0.103496,1.016485
733,-0.611990,0.611990,-0.052271,-0.179858,-1.085376,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,-0.725286,0.734665,0.593036,0.287027,1.016485

In [21]:
# LEAVE BLANK

In [22]:
# LEAVE BLANK

<div class="alert alert-info"><b>Exercise 7: Building the Preprocessing Pipeline </b> 

To complete this part of the assignment, create a `Pipeline` named `pipe` that includes the imputer, transformer, and scaler from the previous exercises. Test the pipeline by transforming the original feature matrix `X`, and store the preprocessed data in a new DataFrame called `X_pipe`.

<br><i>[1 points]</i>
</div>

<div class='alert alert-warning'>

Be sure you apply the data transformations in the correct order.

</div>

In [23]:
from sklearn.pipeline import Pipeline
pipe = Pipeline(steps=[
    ('Imputer', imputer),
    ('Transformer', transformer),
    ('Scaler',scaler)
])
X_pipe= pipe.fit_transform(X)
X_pipe

,categorical__Gender_Female,categorical__Gender_Male,categorical__Eye color_amber,categorical__Eye color_black,categorical__Eye color_blue,categorical__Eye color_blue / white,categorical__Eye color_bown,categorical__Eye color_brown,categorical__Eye color_gold,categorical__Eye color_green,...,categorical__Skin color_red,categorical__Skin color_red / black,categorical__Skin color_silver,categorical__Skin color_white,categorical__Skin color_yellow,ordinal__Power Level,ordinal__Intelligence Level,remainder__Height,remainder__Weight,remainder__Has Superpowers
0,-0.611990,0.611990,-0.052271,-0.179858,-1.085376,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,1.427113,1.445132,0.722041,3.039988,-0.983783
1,-0.611990,0.611990,-0.052271,-0.179858,0.921340,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,-0.725286,-0.686268,0.636037,0.164673,1.016485
2,-0.611990,0.611990,-0.052271,-0.179858,0.921340,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,8.975275,-0.036936,-0.082817,-0.098125,-0.052271,-0.007820,-1.396735,0.593036,0.355851,1.016485
3,-0.611990,0.611990,-0.052271,-0.179858,-1.085376,-0.036936,-0.036936,-0.455233,-0.064062,3.009119,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,1.427113,0.024198,0.722041,3.039988,-0.983783
4,-0.611990,0.611990,-0.052271,-0.179858,0.921340,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,1.427113,0.734665,-1.442378,-1.089453,-0.983783
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,1.634013,-1.634013,-0.052271,-0.179858,0.921340,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,-0.725286,0.734665,0.449697,0.065261,1.016485
730,-0.611990,0.611990,-0.052271,-0.179858,-1.085376,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,10.191032,-0.052271,1.427113,0.024198,1.451636,-1.089453,1.016485
731,-0.611990,0.611990,-0.052271,-0.179858,-1.085376,-0.036936,-0.036936,2.196679,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,0.709647,1.445132,-0.259831,-0.202388,-0.983783
732,1.634013,-1.634013,-0.052271,-0.179858,0.921340,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,-0.007820,0.024198,0.485531,0.103496,1.016485
733,-0.611990,0.611990,-0.052271,-0.179858,-1.085376,-0.036936,-0.036936,-0.455233,-0.064062,-0.332323,...,-0.111417,-0.036936,-0.082817,-0.098125,-0.052271,-0.725286,0.734665,0.593036,0.287027,1.016485

In [24]:
# LEAVE BLANK

In [25]:
# LEAVE BLANK

In [26]:
# LEAVE BLANK

In [27]:
# LEAVE BLANK

<div class="alert alert-info"><b>Exercise 8: End-to-End Preprocessing on a Complex Dataset </b> 

Now, apply everything you’ve learned to preprocess a more complex dataset. Execute the next cell to load a new dataset, `df`, which includes both numerical and categorical features, some of which are ordinal. This dataset also contains missing values and features that require scaling.

**Your tasks are:**

1. **Feature Selection and Engineering:**  
   Create a feature matrix `X` and a target array `y` (using the `Alignment` variable). Drop any irrelevant columns and explain your reasoning for each column you choose to exclude. If you find it relevant, consider combining existing columns or creating new ones based on the dataset's features.

2. **Encoding Categorical and Ordinal Features:**  
   Identify the categorical and ordinal columns, and encode them using a `ColumnTransformer` to apply the transformations in parallel.

3. **Handling Missing Data:**  
   If there are missing values in your feature matrix, decide on an appropriate method to handle them (e.g., imputation).

4. **Standardizing Features:**  
   Assess whether standardization is necessary for your numerical features, and apply it if needed.

5. **Building a Pipeline:**  
   Create a `Pipeline` that integrates all the preprocessing steps you have applied.

6. **Documentation:**
   Remember that thoroughly documenting your code and clearly explaining why certain decisions were made—while also considering and justifying why other options were not chosen—will be highly evaluated.
   



<br><i>[5 points]</i>
</div>

In [28]:
# DO NOT MODIFY NOR ADD CODE TO THIS CELL

df = pd.read_csv('https://raw.githubusercontent.com/jnin/information-systems/refs/heads/main/data/superheroes_complete.csv')
df

,Name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,NaN,good,441.0,...,False,False,False,False,False,False,False,False,False,False
1,Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0,...,False,False,False,False,False,False,False,False,False,False
2,Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0,...,False,False,False,False,False,False,False,False,False,False
3,Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,NaN,bad,441.0,...,False,False,False,False,False,False,False,False,False,False
4,Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,NaN,bad,-99.0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,Yellowjacket II,Female,blue,Human,Strawberry Blond,165.0,Marvel Comics,NaN,good,52.0,...,False,False,False,False,False,False,False,False,False,False
656,Ymir,Male,white,Frost Giant,No Hair,304.8,Marvel Comics,white,good,-99.0,...,False,False,False,False,False,False,False,False,False,False
657,Yoda,Male,brown,Yoda's species,White,66.0,George Lucas,green,good,17.0,...,False,False,False,False,False,False,False,False,False,False
658,Zatanna,Female,blue,Human,Black,170.0,DC Comics,NaN,good,57.0,...,False,False,False,False,False,False,False,False,False,False
659,Zoom,Male,red,NaN,Brown,185.0,DC Comics,NaN,bad,81.0,...,False,False,False,False,False,False,False,False,False,False

Feature Selection and Engineering: 
- The goal of feature selection is to retain the most relevant features for the machine learning model while removing irrelevant or redundant ones. In this case, the Name and Publisher columns were excluded because they are either identifiers (e.g., Name) or potentially non-predictive for alignment classification (e.g., Publisher).
- Alignment is used as the target variable (y), as this is what we aim to predict. It represents whether a character is good, bad, or neutral.
- Any column that does not provide a meaningful contribution to predicting the alignment (such as names or publisher information) is discarded to reduce noise and improve model efficiency.
- Upon reviewing the number of missing values across different columns, we found that 588 out of 659 values in the "Skin color" column were missing, representing approximately 90% of the data. We concluded that this column does not provide a meaningful contribution to predicting alignment and, therefore, removed it.

In [35]:
X = df.drop(columns=['Name','Publisher','Alignment','Skin color'])
y = df[['Alignment']]

missing_columns = X.isna().sum()  # Get the sum of NaNs per column
missing_columns = missing_columns[missing_columns > 0]  # Filter columns with NaNs
print(missing_columns)

Gender         18
Eye color     131
Race          247
Hair color    132
Weight          2
dtype: int64

#Encoding Categorical and Ordinal Features
- We use OneHotEncoder for categorical features like Gender, Eye color, Race, etc., because these variables do not have an inherent order. One-hot encoding converts these features into binary columns to represent their categories.
- For features like Power Level and Intelligence Level, we use OrdinalEncoder because these variables have a natural order. Encoding them as ordinal ensures that the model captures the relative ranking of these values.
- ColumnTransformer allows the application of different transformations to different subsets of features. This is necessary when dealing with mixed types of data (categorical vs. ordinal).

Alternative consideration
- We could use Target Encoding or Binary Encoding as an alternative to One-Hot Encoding, especially for high-cardinality categorical features (like Race). This would reduce the dimensionality but might introduce bias if not carefully handled.

In [31]:

from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder(sparse_output=False)

from sklearn.preprocessing import OrdinalEncoder
categories=[['Weak','Below Average','Average','Above Average','Extremely Powerful'],
            ['Low Intelligence','Average Intelligence','Smart','Genius','Super-Genius']]

ordinal_encoder = OrdinalEncoder(categories=categories)

from sklearn.compose import ColumnTransformer
categorical_columns=['Gender','Eye color','Race','Hair color']
ordinal_columns=['Power Level','Intelligence Level']


transformer = ColumnTransformer(
    transformers=
        [('categorical', one_hot_encoder, categorical_columns),
        ('ordinal', ordinal_encoder , ordinal_columns)],
    remainder='passthrough')

X_encoded= transformer.fit_transform(X)

X_encoded

,categorical__Gender_Female,categorical__Gender_Male,categorical__Gender_nan,categorical__Eye color_amber,categorical__Eye color_black,categorical__Eye color_blue,categorical__Eye color_blue / white,categorical__Eye color_bown,categorical__Eye color_brown,categorical__Eye color_gold,...,remainder__Web Creation,remainder__Reality Warping,remainder__Odin Force,remainder__Symbiote Costume,remainder__Speed Force,remainder__Phoenix Force,remainder__Molecular Dissipation,remainder__Vision - Cryo,remainder__Omnipresent,remainder__Omniscient
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
4,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
656,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
657,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,False,False,False,False,False,False,False,False,False,False
658,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
659,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False

#Handling missing Data TO UPDATE
- Although our code scales the data, handling missing data would typically involve using techniques such as mean, median, or mode imputation before scaling the data. The scaling step here uses StandardScaler, which assumes data is normally distributed.

Alternative consideration
- For non-normal data, alternatives like RobustScaler or MinMaxScaler could be considered.

In [36]:
missing_columns = X_encoded.isna().sum()  # Get the sum of NaNs per column
missing_columns = missing_columns[missing_columns > 0]  # Filter columns with NaNs
print(missing_columns)

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X_encoded)
X_imputed

remainder__Weight    2
dtype: int64

,categorical__Gender_Female,categorical__Gender_Male,categorical__Gender_nan,categorical__Eye color_amber,categorical__Eye color_black,categorical__Eye color_blue,categorical__Eye color_blue / white,categorical__Eye color_bown,categorical__Eye color_brown,categorical__Eye color_gold,...,remainder__Web Creation,remainder__Reality Warping,remainder__Odin Force,remainder__Symbiote Costume,remainder__Speed Force,remainder__Phoenix Force,remainder__Molecular Dissipation,remainder__Vision - Cryo,remainder__Omnipresent,remainder__Omniscient
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
656,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
657,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
658,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
659,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Standardizing Features 
- Many machine learning algorithms (e.g., linear regression or neural networks) implicitly assume that all features are equally important. Standardization ensures that each feature has a comparable range (typically mean 0 and standard deviation 1), so no single feature dominates the model just because of its magnitude.
- Features like weight and height have much larger ranges compared to binary features (which are 0 and 1). Without standardization, these larger values can dominate the learning process because many machine learning algorithms (e.g., distance-based ones like k-Nearest Neighbors (k-NN), SVMs, or gradient descent-based models like logistic regression) rely on measuring distances or gradients (source:'https://neptune.ai/blog/performance-metrics-in-machine-learning-complete-guide')
- Since we have many categorical binary values alongside continuous variables like for example weight and height, we decided to use a StandardScaler to standardize the our numerical features for more balanced feature scaling

In [33]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed)
X_scaled

,categorical__Gender_Female,categorical__Gender_Male,categorical__Gender_nan,categorical__Eye color_amber,categorical__Eye color_black,categorical__Eye color_blue,categorical__Eye color_blue / white,categorical__Eye color_bown,categorical__Eye color_brown,categorical__Eye color_gold,...,remainder__Web Creation,remainder__Reality Warping,remainder__Odin Force,remainder__Symbiote Costume,remainder__Speed Force,remainder__Phoenix Force,remainder__Molecular Dissipation,remainder__Vision - Cryo,remainder__Omnipresent,remainder__Omniscient
0,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,-0.678363,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
1,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,1.474136,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
2,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,1.474136,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
3,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,-0.678363,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
4,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,1.474136,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,1.645559,-1.538619,-0.167444,-0.055132,-0.181284,1.474136,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
656,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,-0.678363,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
657,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,-0.678363,-0.038954,-0.038954,2.132186,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
658,1.645559,-1.538619,-0.167444,-0.055132,-0.181284,1.474136,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
659,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,-0.678363,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132

Building a Pipeline
#documentation 
#documenation

In [34]:
from sklearn.pipeline import Pipeline
pipe = Pipeline(steps=[
    ('Transformer', transformer),
    ('Imputer', imputer),
    ('Scaler',scaler)
])
X_pipe= pipe.fit_transform(X)
X_pipe

,categorical__Gender_Female,categorical__Gender_Male,categorical__Gender_nan,categorical__Eye color_amber,categorical__Eye color_black,categorical__Eye color_blue,categorical__Eye color_blue / white,categorical__Eye color_bown,categorical__Eye color_brown,categorical__Eye color_gold,...,remainder__Web Creation,remainder__Reality Warping,remainder__Odin Force,remainder__Symbiote Costume,remainder__Speed Force,remainder__Phoenix Force,remainder__Molecular Dissipation,remainder__Vision - Cryo,remainder__Omnipresent,remainder__Omniscient
0,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,-0.678363,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
1,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,1.474136,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
2,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,1.474136,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
3,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,-0.678363,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
4,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,1.474136,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,1.645559,-1.538619,-0.167444,-0.055132,-0.181284,1.474136,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
656,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,-0.678363,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
657,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,-0.678363,-0.038954,-0.038954,2.132186,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
658,1.645559,-1.538619,-0.167444,-0.055132,-0.181284,1.474136,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132
659,-0.607696,0.649934,-0.167444,-0.055132,-0.181284,-0.678363,-0.038954,-0.038954,-0.469002,-0.067574,...,-0.157622,-0.147214,-0.055132,-0.124035,-0.038954,-0.038954,-0.038954,-0.038954,-0.055132,-0.055132