# Regression Application [Bengaluru House pricing]

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns

In [5]:
data = pd.read_csv("Bengaluru_House_Data.csv")

In [6]:
data.head(10)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4.0,NaN,204.00
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4.0,NaN,600.00
8,Super built-up Area,Ready To Move,Marathahalli,3 BHK,NaN,1310,3.0,1.0,63.25
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020,6.0,NaN,370.00

In [7]:
data.shape

(13320, 9)

In [8]:
data.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [9]:
for c in data.columns:
    print(data[c].value_counts())
    print("--------------------------")

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
--------------------------
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
--------------------------
location
Whitefield                 540
Sarjapur  Road             399
Electronic City            302
Kanakpura Road             273
Thanisandra                234
                          ...
Park View Layout             1
Xavier Layout                1
Air View Colony              1
akshaya nagar t c palya      1
mvj engineering college      1
Name: count, Length: 1305, dtype: int64
--------------------------
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
--------------------------
society
GrrvaGr    80
PrarePa    76
Prtates    59
Sryalan    59
GMown E    56
           ..
PronsAs     1
NantsGa     1
Vemit S     1
Shamzm      1
SJces R     1
Name: count, Length: 2688, dtype: int64
--------------------------
total_sqft
1200       843
1100       221
1500       205
2400       196
600        180
          ...
1369         1
5665.84      1
2920         1
6688         1
1331.95      1
Name: count, Length: 2117, dtype: int64
--------------------------
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
--------------------------
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
--------------------------
price
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
219.00      1
32.93       1
988.00      1
94.28       1
43.04       1
Name: count, Length: 1994, dtype: int64
--------------------------

## Data processing

In [10]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [12]:
# Not critical data
data.drop(columns=["area_type", "availability", "society", "balcony"], inplace=True)

In [13]:
data

                       location       size total_sqft  bath   price
0      Electronic City Phase II      2 BHK       1056   2.0   39.07
1              Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2                   Uttarahalli      3 BHK       1440   2.0   62.00
3            Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                      Kothanur      2 BHK       1200   2.0   51.00
...                         ...        ...        ...   ...     ...
13315                Whitefield  5 Bedroom       3453   4.0  231.00
13316             Richards Town      4 BHK       3600   5.0  400.00
13317     Raja Rajeshwari Nagar      2 BHK       1141   2.0   60.00
13318           Padmanabhanagar      4 BHK       4689   4.0  488.00
13319              Doddathoguru      1 BHK        550   1.0   17.00

[13320 rows x 5 columns]

In [14]:
data.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [15]:
data["total_sqft"].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [16]:
def uniformRange(x):
    temp = x.split("-")
    if len(temp) == 2:
        return (float(temp[0]) + float(temp[1])) / 2
    try:
        return float(x)
    except:
        return None

In [17]:
data["total_sqft"] = data["total_sqft"].apply(uniformRange)

In [18]:
data["total_sqft"].unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ])

In [19]:
data.head()

                   location       size  total_sqft  bath   price
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00
2               Uttarahalli      3 BHK      1440.0   2.0   62.00
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00
4                  Kothanur      2 BHK      1200.0   2.0   51.00

In [20]:
data["size"].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [21]:
data["size"] = data["size"].fillna("2 BHK")

In [22]:
data["location"].value_counts()

location
Whitefield                 540
Sarjapur  Road             399
Electronic City            302
Kanakpura Road             273
Thanisandra                234
                          ...
Park View Layout             1
Xavier Layout                1
Air View Colony              1
akshaya nagar t c palya      1
mvj engineering college      1
Name: count, Length: 1305, dtype: int64

In [23]:
data["location"] = data["location"].fillna("Sarjapur  Road")

In [24]:
data["total_sqft"].value_counts()

total_sqft
1200.0     843
1100.0     221
1500.0     206
2400.0     196
600.0      180
          ...
2485.0       1
30400.0      1
1701.0       1
1264.0       1
1557.0       1
Name: count, Length: 1999, dtype: int64

In [25]:
data["bath"] = data["bath"].fillna(data["bath"].median())

In [26]:
# Bedroom-Hall-Kitchen (BHK)
data["BHK"] = data["size"].str.split().str.get(0).astype(int)

In [27]:
data.head(10)

                   location       size  total_sqft  bath   price  BHK
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2
5                Whitefield      2 BHK      1170.0   2.0   38.00    2
6          Old Airport Road      4 BHK      2732.0   4.0  204.00    4
7              Rajaji Nagar      4 BHK      3300.0   4.0  600.00    4
8              Marathahalli      3 BHK      1310.0   3.0   63.25    3
9              Gandhi Bazar  6 Bedroom      1020.0   6.0  370.00    6

In [28]:
data[data["BHK"] > 20]

                       location        size  total_sqft  bath  price  BHK
1718  2Electronic City Phase II      27 BHK      8000.0  27.0  230.0   27
4684                Munnekollal  43 Bedroom      2400.0  40.0  660.0   43

In [29]:
data["Price_Per_sqft"] = data["price"] * 100000 / data["total_sqft"]

In [30]:
data["Price_Per_sqft"]

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: Price_Per_sqft, Length: 13320, dtype: float64

In [31]:
data.describe()

         total_sqft          bath         price           BHK  Price_Per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [32]:
data.isna().sum()

location           0
size               0
total_sqft        46
bath               0
price              0
BHK                0
Price_Per_sqft    46
dtype: int64

In [33]:
data["location"].value_counts()

location
Whitefield                 540
Sarjapur  Road             400
Electronic City            302
Kanakpura Road             273
Thanisandra                234
                          ...
Park View Layout             1
Xavier Layout                1
Air View Colony              1
akshaya nagar t c palya      1
mvj engineering college      1
Name: count, Length: 1305, dtype: int64

In [34]:
# Removing whitespace from location values
data["location"] = data["location"].apply(lambda x: x.strip())

In [35]:
loc_count = data["location"].value_counts()
loc_count

location
Whitefield            541
Sarjapur  Road        400
Electronic City       304
Kanakpura Road        273
Thanisandra           237
                     ...
Hsr layout sector3      1
Thyagraj Nagar          1
Banagirinagar           1
Medaralli               1
Chikkajala              1
Name: count, Length: 1294, dtype: int64

In [36]:
loc_count_less_10 = loc_count[loc_count <= 10]
len(loc_count_less_10)

1053

In [37]:
data["location"] = data["location"].apply(
    lambda x: "Other" if x in loc_count_less_10 else x
)

In [38]:
data["location"].value_counts()

location
Other                        2885
Whitefield                    541
Sarjapur  Road                400
Electronic City               304
Kanakpura Road                273
                             ...
Tindlu                         11
Marsur                         11
2nd Phase Judicial Layout      11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

## Outlier Detection and Removal

In [39]:
data.describe()

         total_sqft          bath         price           BHK  Price_Per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [40]:
(data["total_sqft"] / data["BHK"]).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [41]:
# remove the values under the accepted area for each room
data = data[(data["total_sqft"] / data["BHK"]) >= 300]

In [42]:
data.describe()

         total_sqft          bath         price           BHK  Price_Per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838     6303.979357
std     1261.271296      1.077938    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [43]:
data.shape

(12530, 7)

In [44]:
data.isna().sum()

location          0
size              0
total_sqft        0
bath              0
price             0
BHK               0
Price_Per_sqft    0
dtype: int64

In [45]:
data["Price_Per_sqft"].describe()

count     12530.000000
mean       6303.979357
std        4162.237981
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: Price_Per_sqft, dtype: float64

In [46]:
data.reset_index(inplace=True)

In [47]:
def remove_outliers_sqft(df):
    def filter_outliers(subdf):
        m = subdf["Price_Per_sqft"].mean()
        st = subdf["Price_Per_sqft"].std()
        return subdf[
            (subdf["Price_Per_sqft"] >= m - st) & (subdf["Price_Per_sqft"] <= m + st)
        ]
    return df.groupby("location").apply(filter_outliers).reset_index(drop=True)


data = remove_outliers_sqft(data)
data.describe()

C:\Users\acer\AppData\Local\Temp\ipykernel_2608\4039815339.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("location").apply(filter_outliers).reset_index(drop=True)

,index,total_sqft,bath,price,BHK,Price_Per_sqft
count,10350.000000,10350.000000,10350.000000,10350.000000,10350.000000,10350.000000
mean,6658.081063,1508.646058,2.472560,91.347418,2.575556,5660.751992
std,3852.264480,879.853598,0.980519,86.425645,0.898481,2271.111971
min,0.000000,300.000000,1.000000,10.000000,1.000000,1250.000000
25%,3329.250000,1110.000000,2.000000,49.000000,2.000000,4239.794174
50%,6641.500000,1286.000000,2.000000,67.000000,2.000000,5175.519668
75%,10019.500000,1650.000000,3.000000,100.000000,3.000000,6431.808627
max,13319.000000,30400.000000,16.000000,2200.000000,16.000000,24509.803922

In [48]:
def bhk_outlier_remover(df):
    group_cols = ['location', 'BHK']
    means = df.groupby(group_cols)['Price_Per_sqft'].transform('mean')
    stds = df.groupby(group_cols)['Price_Per_sqft'].transform('std')
    counts = df.groupby(group_cols)['Price_Per_sqft'].transform('count')
    
    mask_outliers = (counts > 5) & (df['Price_Per_sqft'] < (means - stds))
    return df[~mask_outliers]

In [49]:
data = bhk_outlier_remover(data)
data

,index,location,size,total_sqft,bath,price,BHK,Price_Per_sqft
0,210,1st Block Jayanagar,4 BHK,2850.0,4.0,428.00,4,15017.543860
1,848,1st Block Jayanagar,3 BHK,1630.0,3.0,194.00,3,11901.840491
2,2152,1st Block Jayanagar,3 BHK,1875.0,2.0,235.00,3,12533.333333
3,7138,1st Block Jayanagar,3 BHK,1200.0,2.0,130.00,3,10833.333333
4,7358,1st Block Jayanagar,2 BHK,1235.0,2.0,148.00,2,11983.805668
...,...,...,...,...,...,...,...,...
10345,12627,Yeshwanthpur,3 BHK,1676.0,3.0,92.13,3,5497.016706
10346,12850,Yeshwanthpur,3 BHK,2503.0,3.0,138.00,3,5513.383939
10347,13017,Yeshwanthpur,3 BHK,1855.0,3.0,135.00,3,7277.628032
10348,13124,Yeshwanthpur,3 BHK,1876.0,3.0,160.00,3,8528.784648
10349,13309,Yeshwanthpur,3 BHK,1675.0,3.0,92.13,3,5500.298507

In [50]:
data.describe()

,index,total_sqft,bath,price,BHK,Price_Per_sqft
count,9015.000000,9015.000000,9015.000000,9015.000000,9015.000000,9015.000000
mean,6645.110261,1518.767164,2.483860,95.879512,2.577926,5897.210291
std,3865.123510,903.762467,0.998968,90.249170,0.918163,2290.136061
min,0.000000,300.000000,1.000000,10.000000,1.000000,2439.024390
25%,3303.500000,1113.060000,2.000000,51.000000,2.000000,4484.304933
50%,6620.000000,1293.000000,2.000000,70.000000,2.000000,5397.236615
75%,10019.000000,1670.000000,3.000000,105.500000,3.000000,6629.773003
max,13319.000000,30400.000000,16.000000,2200.000000,16.000000,24509.803922

In [51]:
data.shape

(9015, 8)

In [52]:
data

,index,location,size,total_sqft,bath,price,BHK,Price_Per_sqft
0,210,1st Block Jayanagar,4 BHK,2850.0,4.0,428.00,4,15017.543860
1,848,1st Block Jayanagar,3 BHK,1630.0,3.0,194.00,3,11901.840491
2,2152,1st Block Jayanagar,3 BHK,1875.0,2.0,235.00,3,12533.333333
3,7138,1st Block Jayanagar,3 BHK,1200.0,2.0,130.00,3,10833.333333
4,7358,1st Block Jayanagar,2 BHK,1235.0,2.0,148.00,2,11983.805668
...,...,...,...,...,...,...,...,...
10345,12627,Yeshwanthpur,3 BHK,1676.0,3.0,92.13,3,5497.016706
10346,12850,Yeshwanthpur,3 BHK,2503.0,3.0,138.00,3,5513.383939
10347,13017,Yeshwanthpur,3 BHK,1855.0,3.0,135.00,3,7277.628032
10348,13124,Yeshwanthpur,3 BHK,1876.0,3.0,160.00,3,8528.784648
10349,13309,Yeshwanthpur,3 BHK,1675.0,3.0,92.13,3,5500.298507

In [53]:
data.drop(columns=["size",'Price_Per_sqft', 'index'], inplace=True)

### Cleaned Data

In [54]:
data.head()

              location  total_sqft  bath  price  BHK
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [55]:
data.to_csv('Cleaned_data.csv')

In [56]:
X = data.drop(columns = 'price')
y = data['price']

### Splitting data

In [57]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#Splitted Data
print('X_train shape is ' , X_train.shape)
print('X_test shape is ' , X_test.shape)
#print('y_train shape is ' , y_train.shape)
#print('y_test shape is ' , y_test.shape)

X_train shape is  (7212, 4)
X_test shape is  (1803, 4)

## Applying Linear Regression

In [58]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn. compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [59]:
column_trans = make_column_transformer((OneHotEncoder(sparse_output=False), ['location']),remainder='passthrough')

In [60]:
scaler = StandardScaler()

lr =  LinearRegression(fit_intercept=True,copy_X=True,n_jobs=-1)

pipe = make_pipeline(column_trans, scaler, lr)

In [61]:

pipe.fit(X_train,y_train)

c:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression(n_jobs=-1))])

In [62]:

y_pred_lr = pipe.predict(X_test)
LReg = r2_score(y_test, y_pred_lr)

In [63]:
lasso = Lasso()

In [64]:
pipe = make_pipeline(column_trans, scaler, lasso)

In [65]:
pipe.fit(X_train, y_train)

c:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [66]:
y_predect_lasso = pipe.predict(X_test)
l = r2_score(y_test,y_predect_lasso)

In [67]:
ridge = Ridge()

In [68]:
pipe = make_pipeline(column_trans, scaler, ridge)

In [69]:
pipe.fit(X_train, y_train)

c:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [70]:
y_predect_ridge = pipe.predict(X_test)
r = r2_score(y_test,y_predect_ridge)

In [71]:
print("Linear Regression ", LReg)
print("Lasso ", l)
print("Ridge ", r)

Linear Regression  0.8176912391604741
Lasso  0.8071013884666697
Ridge  0.8177290865154168

In [72]:
import pickle

In [73]:
pickle.dump(pipe, open('RigeModel.pkl','wb'))