In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
calorie = pd.read_csv('calories.csv')
exercise = pd.read_csv('exercise.csv')

In [3]:
calorie.head()

    User_ID  Calories
0  14733363     231.0
1  14861698      66.0
2  11179863      26.0
3  16180408      71.0
4  17771927      35.0

In [4]:
calorie.drop('User_ID', axis = 'columns', inplace = True)

In [5]:
calorie

       Calories
0         231.0
1          66.0
2          26.0
3          71.0
4          35.0
...         ...
14995      45.0
14996      23.0
14997      75.0
14998      11.0
14999      98.0

[15000 rows x 1 columns]

In [6]:
calorie.shape

(15000, 1)

In [7]:
exercise.head()

    User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0  14733363    male   68   190.0    94.0      29.0       105.0       40.8
1  14861698  female   20   166.0    60.0      14.0        94.0       40.3
2  11179863    male   69   179.0    79.0       5.0        88.0       38.7
3  16180408  female   34   179.0    71.0      13.0       100.0       40.5
4  17771927  female   27   154.0    58.0      10.0        81.0       39.8

In [8]:
exercise.shape

(15000, 8)

In [9]:
df = pd.concat([exercise,calorie], axis = 1)

In [10]:
df.head()

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
0,14733363,male,68,190.0,94.0,29.0,105.0,40.8,231.0
1,14861698,female,20,166.0,60.0,14.0,94.0,40.3,66.0
2,11179863,male,69,179.0,79.0,5.0,88.0,38.7,26.0
3,16180408,female,34,179.0,71.0,13.0,100.0,40.5,71.0
4,17771927,female,27,154.0,58.0,10.0,81.0,39.8,35.0

In [11]:
df.isnull().sum()

User_ID       0
Gender        0
Age           0
Height        0
Weight        0
Duration      0
Heart_Rate    0
Body_Temp     0
Calories      0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User_ID     15000 non-null  int64
 1   Gender      15000 non-null  object
 2   Age         15000 non-null  int64
 3   Height      15000 non-null  float64
 4   Weight      15000 non-null  float64
 5   Duration    15000 non-null  float64
 6   Heart_Rate  15000 non-null  float64
 7   Body_Temp   15000 non-null  float64
 8   Calories    15000 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 1.0+ MB

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
encoder = LabelEncoder()

In [15]:
df['Gender'] = encoder.fit_transform(df['Gender'])

In [16]:
df.head()

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
0,14733363,1,68,190.0,94.0,29.0,105.0,40.8,231.0
1,14861698,0,20,166.0,60.0,14.0,94.0,40.3,66.0
2,11179863,1,69,179.0,79.0,5.0,88.0,38.7,26.0
3,16180408,0,34,179.0,71.0,13.0,100.0,40.5,71.0
4,17771927,0,27,154.0,58.0,10.0,81.0,39.8,35.0

In [19]:
pip install xgboost

Requirement already satisfied: xgboost in c:\users\prachi singh\anaconda3\lib\site-packages (2.1.0)
Requirement already satisfied: numpy in c:\users\prachi singh\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\prachi singh\anaconda3\lib\site-packages (from xgboost) (1.11.4)
Note: you may need to restart the kernel to use updated packages.

In [20]:
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor

In [22]:
X = df.drop(['Calories','User_ID'],axis= 'columns')
X.head()

   Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0       1   68   190.0    94.0      29.0       105.0       40.8
1       0   20   166.0    60.0      14.0        94.0       40.3
2       1   69   179.0    79.0       5.0        88.0       38.7
3       0   34   179.0    71.0      13.0       100.0       40.5
4       0   27   154.0    58.0      10.0        81.0       39.8

In [23]:
Y = df.Calories
Y.head()

0    231.0
1     66.0
2     26.0
3     71.0
4     35.0
Name: Calories, dtype: float64

In [24]:
X_train,X_test,y_train,y_test  = train_test_split(X,Y,test_size = 0.2)

In [25]:
model = XGBRegressor()
model.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [26]:
model.score(X_test,y_test)

0.9988498034945414

In [27]:
model.predict([[1,60,190,90,29,105,40]])

array([216.11519], dtype=float32)

In [28]:
import pickle
pickle.dump(model,open('model.pkl','wb'))