In [4]:
pip install seaborn

Requirement already satisfied: seaborn in c:\users\hp\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\hp\anaconda3\lib\site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=1.2 in c:\users\hp\anaconda3\lib\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\hp\anaconda3\lib\site-packages (from seaborn) (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [6]:
df = pd.read_csv('Bengaluru_House_Data.csv')

In [7]:
df.head()
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [8]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [9]:
df.shape

(13320, 9)

In [10]:
df.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [11]:
for i in df.columns:
    print(df[i].value_counts())
    print("*"*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Amionce     1
JaghtDe     1
Jauraht     1
Brity U     1
RSntsAp     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200    843
1100    221
1500    205
2400    196
600     180
       ...
3580      1
2461      1
1437      1
2155      1
4689      1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
351.00      1
54.10       1
80.64       1
32.73       1
488.00      1
Name: count, Length: 1994, dtype: int64
********************

In [12]:
df.drop(columns=['area_type', 'society', 'balcony', 'availability'], inplace=True)

In [13]:
df.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [14]:
df.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [16]:
df['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64

In [17]:
df['location'] = df['location'].fillna('Whitefield')

In [18]:
df['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [19]:
df['size'] = df['size'].fillna('2 BHK')

In [20]:
df['bath'] = df['bath'].fillna(df['bath'].median())

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [22]:
df['bedroom'] = df['size'].str.split(' ').str.get(0).astype(int)

In [23]:
df.head()

                   location       size total_sqft  bath   price  bedroom
0  Electronic City Phase II      2 BHK       1056   2.0   39.07        2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00        4
2               Uttarahalli      3 BHK       1440   2.0   62.00        3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00        3
4                  Kothanur      2 BHK       1200   2.0   51.00        2

In [24]:
df.drop(columns=['size'], inplace=True)

In [25]:
df[df.bedroom >20]

                       location total_sqft  bath  price  bedroom
1718  2Electronic City Phase II       8000  27.0  230.0       27
4684                Munnekollal       2400  40.0  660.0       43

In [26]:
df.drop(df[df.bedroom >20].index, inplace=True)

In [27]:
df.info

<bound method DataFrame.info of                        location total_sqft  bath   price  bedroom
0      Electronic City Phase II       1056   2.0   39.07        2
1              Chikka Tirupathi       2600   5.0  120.00        4
2                   Uttarahalli       1440   2.0   62.00        3
3            Lingadheeranahalli       1521   3.0   95.00        3
4                      Kothanur       1200   2.0   51.00        2
...                         ...        ...   ...     ...      ...
13315                Whitefield       3453   4.0  231.00        5
13316             Richards Town       3600   5.0  400.00        4
13317     Raja Rajeshwari Nagar       1141   2.0   60.00        2
13318           Padmanabhanagar       4689   4.0  488.00        4
13319              Doddathoguru        550   1.0   17.00        1

[13318 rows x 5 columns]>

In [28]:
df.head()

                   location total_sqft  bath   price  bedroom
0  Electronic City Phase II       1056   2.0   39.07        2
1          Chikka Tirupathi       2600   5.0  120.00        4
2               Uttarahalli       1440   2.0   62.00        3
3        Lingadheeranahalli       1521   3.0   95.00        3
4                  Kothanur       1200   2.0   51.00        2

In [29]:
df

                       location total_sqft  bath   price  bedroom
0      Electronic City Phase II       1056   2.0   39.07        2
1              Chikka Tirupathi       2600   5.0  120.00        4
2                   Uttarahalli       1440   2.0   62.00        3
3            Lingadheeranahalli       1521   3.0   95.00        3
4                      Kothanur       1200   2.0   51.00        2
...                         ...        ...   ...     ...      ...
13315                Whitefield       3453   4.0  231.00        5
13316             Richards Town       3600   5.0  400.00        4
13317     Raja Rajeshwari Nagar       1141   2.0   60.00        2
13318           Padmanabhanagar       4689   4.0  488.00        4
13319              Doddathoguru        550   1.0   17.00        1

[13318 rows x 5 columns]

In [30]:
df['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [31]:
def convertrange(x):
    temp = x.split('-')
    if len(temp) == 2:
        return (float(temp[0]) + float(temp[1])) / 2
    try:
        return float(x)
    except:
        return None

In [32]:
df['total_sqft'] = df['total_sqft'].apply(convertrange)

In [33]:
df['total_sqft'].unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ])

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13318 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13318 non-null  object
 1   total_sqft  13272 non-null  float64
 2   bath        13318 non-null  float64
 3   price       13318 non-null  float64
 4   bedroom     13318 non-null  int32
dtypes: float64(3), int32(1), object(1)
memory usage: 572.3+ KB

In [35]:
df['total_sqft'] = df['total_sqft'].fillna(df['total_sqft'].median())

In [36]:
df['ppsqft'] = df['price'] * 100000 / df['total_sqft']
df.head()

                   location  total_sqft  bath   price  bedroom       ppsqft
0  Electronic City Phase II      1056.0   2.0   39.07        2  3699.810606
1          Chikka Tirupathi      2600.0   5.0  120.00        4  4615.384615
2               Uttarahalli      1440.0   2.0   62.00        3  4305.555556
3        Lingadheeranahalli      1521.0   3.0   95.00        3  6245.890861
4                  Kothanur      1200.0   2.0   51.00        2  4250.000000

In [37]:
df.describe()

         total_sqft          bath         price       bedroom        ppsqft
count  13318.000000  13318.000000  13318.000000  13318.000000  1.331800e+04
mean    1558.100371      2.684187    112.515704      2.797943  7.918312e+03
std     1235.187497      1.282026    148.903830      1.229083  1.062549e+05
min        1.000000      1.000000      8.000000      1.000000  2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000  4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000  5.440000e+03
75%     1677.750000      3.000000    120.000000      3.000000  7.327287e+03
max    52272.000000     18.000000   3600.000000     19.000000  1.200000e+07

In [38]:
df['location'].value_counts()

location
Whitefield                            541
Sarjapur  Road                        399
Electronic City                       302
Kanakpura Road                        273
Thanisandra                           234
                                     ...
 Whitefield                             1
Kengeri Satellite Town ( BDA SITE)      1
Indiranagar HAL 2nd Stage               1
K R C kothanur                          1
Abshot Layout                           1
Name: count, Length: 1304, dtype: int64

In [39]:
df['location'] = df['location'].str.strip()

In [40]:
df['location'].value_counts()

location
Whitefield                        542
Sarjapur  Road                    399
Electronic City                   304
Kanakpura Road                    273
Thanisandra                       237
                                 ...
Vasantapura main road               1
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
Abshot Layout                       1
Name: count, Length: 1293, dtype: int64

In [41]:

location_less_than_10 = df['location'].value_counts()[df['location'].value_counts() <= 10]
location_less_than_10

location
Dairy Circle                      10
Nagappa Reddy Layout              10
Basapura                          10
1st Block Koramangala             10
Sector 1 HSR Layout               10
                                  ..
Vasantapura main road              1
Bapuji Layout                      1
1st Stage Radha Krishna Layout     1
BEML Layout 5th stage              1
Abshot Layout                      1
Name: count, Length: 1052, dtype: int64

In [42]:
df['location'] = df['location'].replace(location_less_than_10.index, 'other')
df['location'].value_counts()

location
other                 2884
Whitefield             542
Sarjapur  Road         399
Electronic City        304
Kanakpura Road         273
                      ...
Nehru Nagar             11
Banjara Layout          11
LB Shastri Nagar        11
Pattandur Agrahara      11
Narayanapura            11
Name: count, Length: 242, dtype: int64

In [43]:
df = df[((df['total_sqft'] / df['bedroom']) >= 300)]
df.describe()

         total_sqft          bath         price       bedroom         ppsqft
count  12568.000000  12568.000000  12568.000000  12568.000000   12568.000000
mean    1593.601347      2.559039    111.409518      2.650064    6313.436790
std     1259.484400      1.077715    151.916676      0.976813    4174.854291
min      300.000000      1.000000      8.440000      1.000000     267.829813
25%     1117.750000      2.000000     49.000000      2.000000    4209.344773
50%     1300.000000      2.000000     70.000000      3.000000    5295.544522
75%     1700.000000      3.000000    115.000000      3.000000    6927.325006
max    52272.000000     16.000000   3600.000000     16.000000  176470.588235

In [44]:
df.shape

(12568, 6)

In [45]:
def remove_outliers_sqrt(df):
    df_output = pd.DataFrame()
    for key,subdf in df.groupby('location'):
        mean = subdf['ppsqft'].mean()
        std = subdf['ppsqft'].std()
        reduced_df = subdf[(subdf['ppsqft'] > (mean - std)) & (subdf['ppsqft'] < (mean + std))]
        df_output = pd.concat([df_output, reduced_df], ignore_index=True)
    return df_output
df = remove_outliers_sqrt(df)
df.describe()

         total_sqft          bath         price       bedroom        ppsqft
count  10399.000000  10399.000000  10399.000000  10399.000000  10399.000000
mean    1508.682153      2.472257     91.416869      2.574959   5666.500918
std      879.288582      0.980663     86.376160      0.899088   2279.104864
min      300.000000      1.000000     10.000000      1.000000   1250.000000
25%     1110.000000      2.000000     49.000000      2.000000   4239.329087
50%     1285.000000      2.000000     67.000000      2.000000   5177.304965
75%     1650.000000      3.000000    100.000000      3.000000   6448.042347
max    30400.000000     16.000000   2200.000000     16.000000  24509.803922

In [46]:
def remove_bhkoutliers(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby('bedroom'):
            bhk_stats[bhk] = {
                'mean': bhk_df['ppsqft'].mean(),
                'std': bhk_df['ppsqft'].std(),
                'count': bhk_df.shape[0]
            }
        for bhk, bhk_df in location_df.groupby('bedroom'):
            stats = bhk_stats.get(bhk - 1)
            if stats and stats['count'] > 5:
                exclude_indices = np.append(
                    exclude_indices,
                    bhk_df[bhk_df['ppsqft'] < (stats['mean'])].index.values
                )
    return df.drop(exclude_indices, axis='index')  # Correctly indented

In [47]:
df = remove_bhkoutliers(df)

In [48]:
df.shape

(7430, 6)

In [49]:
df = df.drop(columns=['ppsqft'])

In [50]:
df.head()

              location  total_sqft  bath  price  bedroom
0  1st Block Jayanagar      2850.0   4.0  428.0        4
1  1st Block Jayanagar      1630.0   3.0  194.0        3
2  1st Block Jayanagar      1875.0   2.0  235.0        3
3  1st Block Jayanagar      1200.0   2.0  130.0        3
4  1st Block Jayanagar      1235.0   2.0  148.0        2

In [51]:
df.to_csv('cleaned_bengaluru_house_data.csv')

ml

In [52]:
x = df.drop(columns=['price'])
y = df['price']
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [53]:
X_tarin,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [54]:
print(X_tarin.shape, x_test.shape, y_train.shape, y_test.shape)

(5944, 4) (1486, 4) (5944,) (1486,)

In [55]:


columntrans = make_column_transformer((OneHotEncoder(sparse_output=False), ['location']),
    remainder='passthrough'
)

In [56]:
scaler = StandardScaler()

In [57]:
lr = LinearRegression()

In [58]:
model = make_pipeline(columntrans, scaler, lr)

In [59]:
model.fit(X_tarin, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [60]:
y_pred = model.predict(x_test)

In [61]:
r2 = r2_score(y_test, y_pred)
r2

0.8439792437469305

In [62]:
lasso = Lasso()

In [63]:
model = make_pipeline(columntrans, scaler,lasso)
model.fit(X_tarin, y_train)
y_pred_lasso = model.predict(x_test)

In [64]:
r2_score(y_test, y_pred_lasso)

0.8340323650321564

In [65]:
ridge = Ridge()
model = make_pipeline(columntrans, scaler, ridge)
model.fit(X_tarin, y_train)
y_pred_ridge = model.predict(x_test)
r2_score(y_test, y_pred_ridge)

0.8440280302186544

In [66]:
import pickle
pickle.dump(model,open('ridgemodel.pkl', 'wb'))

In [68]:
with open('column_transformer.pkl', 'wb') as f:
    pickle.dump(columntrans, f)