Perform the following operations using Python on Iris data set.
1. Load the Dataset into pandas data frame.
2. Display information about missing values in the data
3. Display initial statistics.
4. Check the dimensions of the data frame.
5. Display data type of the variable.
6. Apply proper data type conversion
7. Convert categorical variables into quantitative variables using one hot
encoding and label encoder

In [1]:
# Import necessary libraries
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import load_iris

In [14]:
# Load the Iris dataset
# iris = load_iris()

iris=pd.read_csv("Iris.csv")
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [32]:
# 1. Load the Dataset into pandas data frame.
# iris_df = pd.DataFrame(data=iris, columns=iris.columns)

iris_df=pd.DataFrame(iris)
iris_df

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [20]:
# 2. Display information about missing values in the data
missing_values = iris_df.isnull().sum()
print("Missing Values:\n", missing_values)

Missing Values:
 Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [23]:
# 4. Check the dimensions of the data frame
dimensions = iris_df.shape
print("\nDimensions of the Data Frame:", dimensions)

Dimensions of the Data Frame: (150, 6)

In [6]:
# 5. Display data type of the variable
data_types = iris_df.dtypes
print("\nData Types of Variables:\n", data_types)

Data Types of Variables:
 sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                 int32
dtype: object

In [7]:
# 6. Apply proper data type conversion (if needed)
# (Since iris dataset is already numeric, we don't need to convert data types)
# Here is a demo example
# Create a demo DataFrame
demo_data = {
    'A': ['1', '2', '3', '4', '5'],
    'B': [1.1, 2.2, 3.3, 4.4, 5.5],
    'C': ['True', 'False', 'True', 'False', 'True']
}

demo_df = pd.DataFrame(demo_data)

# Display the demo DataFrame
print("Demo DataFrame:")
print(demo_df)

# Check data types of variables in the demo DataFrame
print("\nData Types of Variables in Demo DataFrame:")
print(demo_df.dtypes)

Demo DataFrame:
   A    B      C
0  1  1.1   True
1  2  2.2  False
2  3  3.3   True
3  4  4.4  False
4  5  5.5   True

Data Types of Variables in Demo DataFrame:
A     object
B    float64
C     object
dtype: object

In [8]:
# 6. Apply proper data type conversion (if needed)
demo_df['A'] = demo_df['A'].astype(int)
demo_df['C'] = demo_df['C'].map({'True': True, 'False': False})

# Display the modified demo DataFrame after data type conversion
print("\nModified Demo DataFrame after Data Type Conversion:")
print(demo_df)
print("\nData Types of Variables after Conversion:")
print(demo_df.dtypes)

Modified Demo DataFrame after Data Type Conversion:
   A    B      C
0  1  1.1   True
1  2  2.2  False
2  3  3.3   True
3  4  4.4  False
4  5  5.5   True

Data Types of Variables after Conversion:
A      int32
B    float64
C       bool
dtype: object

In [31]:
# 7. Convert categorical variables into quantitative variables using one hot encoding and label encoder
# Apply label encoding to target variable
label_encoder = LabelEncoder()
iris_df['Species'] = label_encoder.fit_transform(iris_df['Species'])

# Apply one-hot encoding to categorical variables if any (In Iris dataset, there are no categorical variables)

# Display the modified DataFrame
print("\nModified DataFrame after Label Encoding:\n", iris_df.head())
#iris_df.tail(7)
#iris_df.iloc[:3]

Modified DataFrame after Label Encoding:
    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [33]:
# Example of One-hot encoding with sample dataset

# Add a new categorical variable "Species_Type"
# iris_df['Species_Type'] = ['Setosa', 'Versicolor', 'Virginica'] * 50

# Display the first few rows of the modified dataset
# print("Original Iris dataset with new categorical variable:")
# print(iris_df.head())

# Apply one-hot encoding to the categorical variable
iris_encoded = pd.get_dummies(iris_df, columns=['Species'])

# Display the first few rows of the dataset after one-hot encoding
print("\nIris dataset after one-hot encoding:")
print(iris_encoded.head())

Iris dataset after one-hot encoding:
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species_0  \
0   1            5.1           3.5            1.4           0.2          1
1   2            4.9           3.0            1.4           0.2          1
2   3            4.7           3.2            1.3           0.2          1
3   4            4.6           3.1            1.5           0.2          1
4   5            5.0           3.6            1.4           0.2          1

   Species_1  Species_2
0          0          0
1          0          0
2          0          0
3          0          0
4          0          0