In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [3]:
kidney = pd.read_csv("kidney_disease - kidney_disease.csv")
liver = pd.read_csv("indian_liver_patient - indian_liver_patient.csv")
parkinson = pd.read_csv("parkinsons - parkinsons.csv")

In [4]:
kidney.columns

Index(['Unnamed: 0', 'id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc',
       'ba', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn',
       'dm', 'cad', 'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [6]:
kidney.drop(columns="Unnamed: 0",inplace=True)

In [7]:
kidney.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [8]:
cols = ['rbc','pc','pcc','ba','htn','dm','cad','appet','pe','ane','classification']
le=LabelEncoder()
kidney[cols] = kidney[cols].apply(le.fit_transform)

In [9]:
kidney

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,1,1,0,0,...,44.0,7800.0,5.2,1,1,0,0,0,0,0
1,1,7.0,50.0,1.020,4.0,0.0,1,1,0,0,...,38.0,6000.0,4.1,0,0,0,0,0,0,0
2,2,62.0,80.0,1.010,2.0,3.0,1,1,0,0,...,31.0,7500.0,3.2,0,1,0,1,0,1,0
3,3,48.0,70.0,1.005,4.0,0.0,1,0,1,0,...,32.0,6700.0,3.9,1,0,0,1,1,1,0
4,4,51.0,80.0,1.010,2.0,0.0,1,1,0,0,...,35.0,7300.0,4.6,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,1,1,0,0,...,47.0,6700.0,4.9,0,0,0,0,0,0,1
396,396,42.0,70.0,1.025,0.0,0.0,1,1,0,0,...,54.0,7800.0,6.2,0,0,0,0,0,0,1
397,397,12.0,80.0,1.020,0.0,0.0,1,1,0,0,...,49.0,6600.0,5.4,0,0,0,0,0,0,1
398,398,17.0,60.0,1.025,0.0,0.0,1,1,0,0,...,51.0,7200.0,5.9,0,0,0,0,0,0,1
399,399,58.0,80.0,1.025,0.0,0.0,1,1,0,0,...,53.0,6800.0,6.1,0,0,0,0,0,0,1

In [10]:
x = kidney.drop(columns=['classification','id'])
y = kidney['classification']
model = LogisticRegression()
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8875
              precision    recall  f1-score   support

           0       0.91      0.92      0.91        52
           1       0.85      0.82      0.84        28

    accuracy                           0.89        80
   macro avg       0.88      0.87      0.88        80
weighted avg       0.89      0.89      0.89        80

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [11]:
model = RandomForestClassifier()
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        52
           1       1.00      1.00      1.00        28

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80

In [12]:
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler()
x_rus,y_rus = rus.fit_resample(x_train,y_train)
x_rus_train,x_rus_test,y_rus_train,y_rus_test = train_test_split(x_rus,y_rus,test_size=0.2,random_state=42)
model.fit(x_rus_train,y_rus_train)
y_rus_pred = model.predict(x_rus_test)
print(accuracy_score(y_rus_test,y_rus_pred))
print(classification_report(y_rus_test,y_rus_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        27
           1       1.00      1.00      1.00        22

    accuracy                           1.00        49
   macro avg       1.00      1.00      1.00        49
weighted avg       1.00      1.00      1.00        49

In [13]:
from sklearn.model_selection import GridSearchCV
model = RandomForestClassifier()
# Define hyperparameter grid for tuning
param_grid = {
   'criterion': ['gini', 'entropy','log_loss'],
   'max_depth': [5, 10, 15, None],
   'min_samples_split': [2, 5, 10],
   'min_samples_leaf': [1, 2, 4]
}
# 1. **Grid Search CV** (Exhaustive Search for Best Hyperparameters)
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(x_rus_train, y_rus_train)
# Get the best parameters
print("Best parameters from Grid Search CV:", grid_search.best_params_)
print("Best accuracy from Grid Search CV:", grid_search.best_score_)
# Train with best parameters
best_model_grid = grid_search.best_estimator_
y_pred_grid = best_model_grid.predict(x_rus_test)
# Performance Metrics
print("\nGrid Search CV Classification Report:\n", classification_report(y_rus_test, y_pred_grid))

Best parameters from Grid Search CV: {'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best accuracy from Grid Search CV: 1.0

Grid Search CV Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        27
           1       1.00      1.00      1.00        22

    accuracy                           1.00        49
   macro avg       1.00      1.00      1.00        49
weighted avg       1.00      1.00      1.00        49

In [14]:
import pickle

with open("kidney.pkl",'wb') as file:
    pickle.dump(grid_search,file)
print("Model saved as kidney_disease.pkl")

Model saved as kidney_disease.pkl

In [22]:
with open('kidney.pkl','rb') as file:
    loaded_dump = pickle.load(file)

In [23]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
model = xgb.XGBClassifier(objective='binary:logistic',random_state=42)
# x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model.fit(x_rus_train,y_rus_train)
y_rus_pred = model.predict(x_rus_test)
print(accuracy_score(y_rus_test,y_rus_pred))
print(classification_report(y_rus_test,y_rus_pred))

0.9795918367346939
              precision    recall  f1-score   support

           0       1.00      0.96      0.98        27
           1       0.96      1.00      0.98        22

    accuracy                           0.98        49
   macro avg       0.98      0.98      0.98        49
weighted avg       0.98      0.98      0.98        49

In [5]:
kidney

,Unnamed: 0,id,age,bp,sg,al,su,rbc,pc,pcc,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,0,48.0,80.0,1.020,1.0,0.0,normal,normal,notpresent,...,44.0,7800.0,5.2,yes,yes,no,good,no,no,ckd
1,1,1,7.0,50.0,1.020,4.0,0.0,normal,normal,notpresent,...,38.0,6000.0,4.1,no,no,no,good,no,no,ckd
2,2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,...,31.0,7500.0,3.2,no,yes,no,poor,no,yes,ckd
3,3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
4,4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,...,47.0,6700.0,4.9,no,no,no,good,no,no,notckd
396,396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,...,54.0,7800.0,6.2,no,no,no,good,no,no,notckd
397,397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,...,49.0,6600.0,5.4,no,no,no,good,no,no,notckd
398,398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,...,51.0,7200.0,5.9,no,no,no,good,no,no,notckd
399,399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,...,53.0,6800.0,6.1,no,no,no,good,no,no,notckd

In [8]:
kidney.loc[0]

Unnamed: 0                 0
id                         0
age                     48.0
bp                      80.0
sg                      1.02
al                       1.0
su                       0.0
rbc                   normal
pc                    normal
pcc               notpresent
ba                notpresent
bgr                    121.0
bu                      36.0
sc                       1.2
sod                    139.0
pot                      4.4
hemo                    15.4
pcv                     44.0
wc                    7800.0
rc                       5.2
htn                      yes
dm                       yes
cad                       no
appet                   good
pe                        no
ane                       no
classification           ckd
Name: 0, dtype: object