# Exercise 2
## Authors: E. Vercesi; A. Dei Rossi, S. Huber*, L. Scarciglia.

In this exercise session you are going to learn the basics of PyTorch and pandas. We will start with PyTorch.

[PyTorch](https://pytorch.org/) is a Python library for scientific computing (as much as NumPy), but which can additionally run on GPUs. 
Hence, this is the computing library of choice for Deep Learning applications. 
PyTorch is developed by Meta. You might have also heard of its main competitor TensorFlow (Google). Although both have basically the same functionalities, in this course we would like you to stick to PyTorch (assignments made using TensorFlow won't be evaluated).

If you haven't done Exercise 1 on NumPy yet, we highly encourage to do it first: NumPy and PyTorch offer a vast overlap of functionalities, so understanding NumPy first is going to boost greatly your understanding of PyTorch.
To begin with, make sure you have installed it. If not, please do so (by typing `conda/pip install torch` from your environment, or using the GUI of your IDE). Also make sure that the version installed is 2.8.

In addition to that, also install [pandas](https://pandas.pydata.org/docs/getting_started/install.html). We will use it at the end of the notebook.

In [2]:
import torch  # If you see errors, use conda or pip to install torch in your virtual environment.
import numpy as np

torch.manual_seed(42)  # manual seed is to ensure repeatability of random numbers.

## Create tensors

Tensors are like NumPy arrays, but they can live in GPUs.

1. Create a tensor out of a Python list [1, 2, 3].
2. Create a tensor out of a NumPy array [[2, 3, 4], [4, 3, 2]] (see method [`.from_numpy()`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html)).
3. Convert the tensor of point 2 back to a NumPy array. (see method [`.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html)).

In [3]:
## 1: create a tensor out of a Python list
py_t = torch.tensor([1,2,3])
print(py_t)
## 2: create a tensor out of a NumPy array
np_t = torch.from_numpy(np.array([[2,3,4],[4,3,2]]))
print(np_t)
## 3: Convert the tensor back to NumPy.
np_l = np_t.numpy()
print(np_l)

tensor([1, 2, 3])
tensor([[2, 3, 4],
        [4, 3, 2]])
[[2 3 4]
 [4 3 2]]

1. Check the `.dtype` attribute of the above created tensors. 
2. Create a tensor of size 3 with values [1, 2, 3] but forcing the dtype to be float64.

In [4]:
## 1: check the dtype attribute
print("py_t:", py_t.dtype, "np_t:", np_t.dtype, "np_l:", np_l.dtype)
## 2: create [1, 2, 3] with dtype float64
t_float = torch.tensor([1,2,3], dtype=torch.float64)
print(t_float)

py_t: torch.int64 np_t: torch.int64 np_l: int64
tensor([1., 2., 3.], dtype=torch.float64)

PyTorch also offers some more advanced functions that can be used to create well-known matrices:

1. Create an identity matrix of size (5, 5) (see [`torch.eye()`](https://pytorch.org/docs/stable/generated/torch.eye.html)).
2. Create a matrix of all zeros of size (3, 4) (see [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html).
3. Create a matrix of all ones of size (2, 3) (see [`torch.ones()`](https://pytorch.org/docs/stable/generated/torch.ones.html).
4. Given a tensor of size (3, 2) of your choice, create a matrix of the same size (3, 2) filled with ones (equivalently zeros) (see [`torch.zeros_like()`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html).
5. Create a matrix of size (3, 4) filled with numbers from 0 to 11 inclusive (same as in NumPy). Try both [`torch.arange()`](https://pytorch.org/docs/stable/generated/torch.arange.html) and [`torch.linspace()`](https://pytorch.org/docs/stable/generated/torch.linspace.html).

In [5]:
## 1: torch.eye()
id_m = torch.eye(5)
print(id_m.shape)
## 2: torch.zeros()
m_zeros = torch.zeros((3,4))
print(m_zeros.shape)
## 3: torch.ones()
m_ones = torch.ones((2,3))
print(m_ones.shape)
## 4: torch.zeros_like()
m_rand = torch.randint(0,10,(3,2))
print(m_rand)
print(torch.zeros_like(m_rand))
print(torch.ones_like(m_rand))
## 5:
## torch.arange()
print(torch.arange(0, 12).reshape((3,4)))
## torch.linspace()
print(torch.linspace(0,11,12).reshape(3,4))

torch.Size([5, 5])
torch.Size([3, 4])
torch.Size([2, 3])
tensor([[2, 7],
        [6, 4],
        [6, 5]])
tensor([[0, 0],
        [0, 0],
        [0, 0]])
tensor([[1, 1],
        [1, 1],
        [1, 1]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

### Random tensors

As in NumPy, you have a big choice of random distributions to sample you arrays from.
Create the same random arrays you did in NumPy in Exercise 1:
1) Create a random tensor of size 4 of uniform floating point numbers in the interval [0, 1). (see [`torch.rand`](https://pytorch.org/docs/stable/generated/torch.rand.html)).
2) Create a random tensor of size (3, 2) of uniform floating point numbers in the interval [0, 5). (hint: generate numbers in the interval [0, 1) and scale them up by 5).
3) Create a random tensor of size (2, 1, 2) of integers in the interval [10, 20]. (see [`torch.randint`](https://pytorch.org/docs/stable/generated/torch.randint.html), caraful with border conditions).
4) Create a random tensor of size 10 over the normal distribution, mean 3 and std dev 2. (see [`torch.normal`](https://pytorch.org/docs/stable/generated/torch.normal.html)).

In [6]:
## 1: torch.rand()
print(torch.rand(4))
## 2: torch.rand() scaled up to [0, 5)
print(torch.rand(5)*5)
## 3: torch.randint()
print(torch.randint(10,21,(2,1,2)))
## 4: torch.normal()
print(torch.normal(3, 2, size=(1,10)))

tensor([0.2566, 0.7936, 0.9408, 0.1332])
tensor([4.6730, 2.9679, 4.3470, 2.8386, 3.7055])
tensor([[[10, 14]],

        [[13, 16]]])
tensor([[5.4422, 3.3022, 2.3362, 2.0430, 2.4739, 2.6429, 0.6283, 1.2279, 1.5701,
         3.2560]])

## Working with tensors' dimensions

In this section we will learn how to manipulate tensor's dimensions. Notice that they are extremely similar to NumPy methods: hence, if you have done exercise 1, this section should be quite straightforward.

### Access elements and slicing 

Create an identity matrix of size (4, 4) and access 
1. The element in position [0, 0].
2. The last element.
3. Element in position [2, 3].
Check that the returned elements are what you expect.

In [7]:
# Create the identity matrix
id_m = torch.eye(4)
print(id_m)
## 1: access element in [0, 0]
print(id_m[0,0])
## 2: access element in [3, 3]
print(id_m[3,3])
## 3: access element in [2, 3]
print(id_m[3,2])

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor(1.)
tensor(1.)
tensor(0.)

### Slicing

1. Create a random tensor of size (3, 4) of integers in the interval [5, 10].
2. Print the second row.
3. Print the third column.
4. Print the sub-matrix spanning from the second to the third row, from the second to the third column.

In [8]:
## 1: create a random tensor of size [3, 4].
rand_m = torch.randint(5,11,(3,4))
print(rand_m)
## 2: print the second row.
print(rand_m[1])
## 3: print the third column.
print(rand_m[:,2])
## 4: sub-matrix
print(rand_m[1:,1:3])

tensor([[ 5,  7,  5,  6],
        [ 8,  8, 10, 10],
        [ 9,  8, 10,  5]])
tensor([ 8,  8, 10, 10])
tensor([ 5, 10, 10])
tensor([[ 8, 10],
        [ 8, 10]])

### Access tensors' dimensions

1. Create a tensor $v$ of size (3, 4, 2, 4, 1) of random floats in [0, 1).
2. Print its shape. You can use both `.shape` and [`.size()`](https://docs.pytorch.org/docs/stable/generated/torch.Tensor.size.html), try them both.
3. Print its third dimension's size (2 in our example). Check [`.size()`](https://docs.pytorch.org/docs/stable/generated/torch.Tensor.size.html) function.
4. Print the number of dimensions of our vector (5 in our example). Check [`.dim()`](https://docs.pytorch.org/docs/stable/generated/torch.Tensor.dim.html#torch.Tensor.dim) or [`.ndim`](https://docs.pytorch.org/docs/stable/generated/torch.Tensor.dim.html#torch.Tensor.ndim).

In [9]:
## 1: create a random tensor v of size (3, 4, 2, 4, 1).
v = torch.rand(3,4,2,4,1)
print(v)
## 2: print v's shape using .shape and .size().
print("v shape:", v.shape, "v size():", v.size())
## 3: print the size of the third dimension of v.
print(v.size(2))
## 4: print the number of dimensions of v.
print(v.ndim)

tensor([[[[[0.3068],
           [0.1165],
           [0.9103],
           [0.6440]],

          [[0.7071],
           [0.6581],
           [0.4913],
           [0.8913]]],


         [[[0.1447],
           [0.5315],
           [0.1587],
           [0.6542]],

          [[0.3278],
           [0.6532],
           [0.3958],
           [0.9147]]],


         [[[0.2036],
           [0.2018],
           [0.2018],
           [0.9497]],

          [[0.6666],
           [0.9811],
           [0.0874],
           [0.0041]]],


         [[[0.1088],
           [0.1637],
           [0.7025],
           [0.6790]],

          [[0.9155],
           [0.2418],
           [0.1591],
           [0.7653]]]],



        [[[[0.2979],
           [0.8035],
           [0.3813],
           [0.7860]],

          [[0.1115],
           [0.2477],
           [0.6524],
           [0.6057]]],


         [[[0.3725],
           [0.7980],
           [0.8399],
           [0.1374]],

          [[0.2331],
           [0.9578],
           [0.3313],
           [0.3227]]],


         [[[0.0162],
           [0.2137],
           [0.6249],
           [0.4340]],

          [[0.1371],
           [0.5117],
           [0.1585],
           [0.0758]]],


         [[[0.2247],
           [0.0624],
           [0.1816],
           [0.9998]],

          [[0.5944],
           [0.6541],
           [0.0337],
           [0.1716]]]],



        [[[[0.3336],
           [0.5782],
           [0.0600],
           [0.2846]],

          [[0.2007],
           [0.5014],
           [0.3139],
           [0.4654]]],


         [[[0.1612],
           [0.1568],
           [0.2083],
           [0.3289]],

          [[0.1054],
           [0.9192],
           [0.4008],
           [0.9302]]],


         [[[0.6558],
           [0.0766],
           [0.8460],
           [0.3624]],

          [[0.3083],
           [0.0850],
           [0.0029],
           [0.6431]]],


         [[[0.3908],
           [0.6947],
           [0.0897],
           [0.8712]],

          [[0.1330],
           [0.4137],
           [0.6044],
           [0.7581]]]]])
v shape: torch.Size([3, 4, 2, 4, 1]) v size(): torch.Size([3, 4, 2, 4, 1])
2
5

## Permute dimensions

You can invert the order of the dimensions of a tensor. Create a random tensor of integers in the interval [0, 10) of size (2, 3, 4) and permute its dimensions so that the final size is (4, 2, 3). See [`torch.permute`](https://pytorch.org/docs/stable/generated/torch.permute.html).

In [10]:
## 1: Create a random tensor. Check its shape (2, 3, 4)
rand_int = torch.randint(0,10,(2,3,4))
print(rand_int.shape)
## 2: Permute its dimensions. Check its shape (4, 2, 3)
perm_t = torch.permute(rand_int, (2,0,1))
print(perm_t.shape)

torch.Size([2, 3, 4])
torch.Size([4, 2, 3])

## Squeeze/unsqueeze

If you want increase the number of dimensions of your vector (similar to `np.newaxis`, this might turn useful in the context of broadcasting), you can use [`torch.unsqueeze`](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html). If you want to reduce the number of dimensions of your vector by dropping dimensions of size 1 you can use [`torch.squeeze`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) instead.

1. Create a random tensor uniform in [0, 1) of size (2, 2). Insert a new dimension so that the final shape is (2, 1, 2).
2. Add a dimension to the tensor of point 1, so that the final shape is (2, 1, 2, 1). Try to use negative indices as the argument of `torch.unsqueeze()`.
3. Turn the tensor back to its original shape (2, 2) by using `torch.squeeze()`.

In [11]:
## 1: Create a tensor of size (2, 2). Unsqueeze it so that its final shape is (2, 1, 2)
rand_t = torch.rand((2,2))
rand_t = rand_t.unsqueeze(1)
print(rand_t.shape)
## 2: Add an additional dimension to the tensor so that its shape is (2, 1, 2, 1). Use negative indices
rand_t = rand_t.unsqueeze(3)
print(rand_t.shape)
## 3: Turn the tensor back to shape (2, 2)
rand_t = rand_t.squeeze()
print(rand_t.shape)

torch.Size([2, 1, 2])
torch.Size([2, 1, 2, 1])
torch.Size([2, 2])

## Concatenate and stack

If you have two tensors of compatible sizes, you can merge them into a unique tensor along one of their axes.
In order to get some intuition, think about having 2 2-dimensional tensors of size (3, 4). You can merge them along the first axis and get the final shape be (6, 4), or you can merge them along the second axis and get the final shape to be (3, 8), or you can go in 3D stacking one over the other (along the z-axis) and get a shape of (2, 3, 4). 

This is precisely what [`torch.concat`](https://pytorch.org/docs/stable/generated/torch.cat.html#torch.cat) (also called `.cat`) and [`torch.stack`](https://pytorch.org/docs/stable/generated/torch.stack) do. 
You should already be familiar with NumPy `axis` attribute. In PyTorch it is called `dim`. If you try using `axis` instead of `dim`, PyTorch allows you to do so. Though it is not recommended, since it is not written in the official documentation.

1. Concat $v$ and $w$ along the first dimension. Check that the final shape is (6, 4).
2. Concat $v$ and $w$ along the second dimension. Check that the final shape is (3, 8).
3. Concat $v$ and $w$ along a new dimension. Check that the final shape is (2, 3, 4).

In [12]:
v = torch.randint(0, 10, (3,4))
w = torch.randint(0, 10, (3,4))
print(v)
print(w)
## 1: concat along first dimension.
print(torch.concat([v,w]))
## 2: concat along second dimension.
print(torch.concat([v,w], dim=1))
## 3: concat along new dimension.
print(torch.stack([v,w]))

tensor([[9, 2, 6, 8],
        [2, 8, 2, 1],
        [0, 0, 6, 5]])
tensor([[0, 6, 9, 2],
        [4, 2, 0, 2],
        [3, 3, 1, 6]])
tensor([[9, 2, 6, 8],
        [2, 8, 2, 1],
        [0, 0, 6, 5],
        [0, 6, 9, 2],
        [4, 2, 0, 2],
        [3, 3, 1, 6]])
tensor([[9, 2, 6, 8, 0, 6, 9, 2],
        [2, 8, 2, 1, 4, 2, 0, 2],
        [0, 0, 6, 5, 3, 3, 1, 6]])
tensor([[[9, 2, 6, 8],
         [2, 8, 2, 1],
         [0, 0, 6, 5]],

        [[0, 6, 9, 2],
         [4, 2, 0, 2],
         [3, 3, 1, 6]]])

### Reshape and View

PyTorch lets you reshape your tensors, by keeping the same data, but re-arranging its dimensions.

Create a random vector of size (2, 3, 4), and make a new vector of size (6, 4) using [``torch.reshape``](https://docs.pytorch.org/docs/stable/generated/torch.Tensor.reshape.html) and [``torch.view``](https://www.geeksforgeeks.org/python/how-does-the-view-method-work-in-python-pytorch/).

- `torch.reshape` works on all vectors, but it might be less efficient when working on contiguous data.
- `torch.view` only works on contiguous data (see [``torch.is_contiguous``](https://docs.pytorch.org/docs/stable/generated/torch.Tensor.is_contiguous.html)), but it is more efficient.

In general, ``torch.reshape`` is the safest option to use.

In [13]:
## 1: create a random tensor of size (2, 3, 4)
v = torch.randint(0,11,(2,3,4))
print(v)
## 2: reshape it so that its size is (6, 4) using torch.reshape
# Is v altered by reshape?
print(v.reshape(6,4))
## 3: reshape v so that its size is (6, 4) using torch.view
# Is v altered by view?
print(v.view(6,4))
## 4: as a final step, try to make a tensor not contiguous: e.g., permuting its dimensions
v = torch.rand(2, 3, 4)
# Permute v's dimensions by using torch.permute, so that the final shape is (3, 2, 4). Do it inplace.
v = v.permute((1,0,2))
# Make sure that v is not contiguous anymore.
print(v.is_contiguous())
# print(v.view(6, 4)) would yield an error.

tensor([[[ 3,  1,  4, 10],
         [ 7,  2,  9,  9],
         [ 2,  0,  1,  1]],

        [[ 5,  1,  0,  4],
         [ 4,  0,  0, 10],
         [ 8,  8,  8,  5]]])
tensor([[ 3,  1,  4, 10],
        [ 7,  2,  9,  9],
        [ 2,  0,  1,  1],
        [ 5,  1,  0,  4],
        [ 4,  0,  0, 10],
        [ 8,  8,  8,  5]])
tensor([[ 3,  1,  4, 10],
        [ 7,  2,  9,  9],
        [ 2,  0,  1,  1],
        [ 5,  1,  0,  4],
        [ 4,  0,  0, 10],
        [ 8,  8,  8,  5]])
False

## Broadcasting

Same as in NumPy, also PyTorch tensors allow [broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html).
When performing element-wise operations (like sums) on two tensors of mismatching sizes, the smaller tensor can adapt to the size of the larger tensor in case these simple rules apply:

- Each tensor has at least one dimension.
- When iterating over the dimension sizes, starting at the trailing (right-most) dimension, the dimension sizes must be
    -  equal
    -  one of them is 1
    -  one of them does not exist.

Let us see an example:

Assume you have $v = [[1, 2, 3], [4, 5, 6]]$ shape (2, 3) and $w=[3, 2, 1]$ shape (3). If we want to perform $v + w$ (element by element sum), it is clear that the dimensions don't match, but with the help of broadcasting we can still do it: $w$ is simply enlarged to reach size (2, 3) by copying itself twice on the first axis. Then, it is possible to perform element by element sum $v+w$.

Let's put broadcasting in practice:

1. Perform the above described example $v+w$ using tensors, check that the result size is (2, 3) and that numbers add up.
2. $r = [[1, 2], [3, 4], [5, 6]]$ and $l=[1, 2, 3]$. Compute $r + l$. It should raise errors. Why?
3. Adjust the size of $l$ in example 2 so that the sum works. What size should $l$ have in order for broadcasting to work on $r + l$?
4. Create random integers tensors $s$ of size (2, 1, 3, 1) and $t$ of size (1, 3, 1, 3). Does broadcasting work here in order to compute $s+t$? In case it does, predict the final shape of the result.

In [14]:
v = torch.arange(1,7).reshape(2,3)
r = torch.arange(1,7).reshape(3,2)
l = torch.arange(1,4)
w = torch.arange(3,0,-1)
## 1: compute v + w
print(v+w)
## 2: compute r + l. It doesn't work, why?
#r+l
## 3: adjust the size of l, and compute r + l
l = l.reshape(3,1)
print(l)
print(r+l)
## 4: compute s + t
s = torch.randint(0,11,(2,1,3,1))
t = torch.randint(0,11,(1,3,1,3))
# shape (2,3,3,3)
print((s+t).shape)

tensor([[4, 4, 4],
        [7, 7, 7]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [5, 6],
        [8, 9]])
torch.Size([2, 3, 3, 3])

## PyTorch functions

In this section we are going to learn the basic functions of PyTorch.

### Mean, min, max, sum ...

These functions are quite self-explanatory, and they work the same way as in NumPy. The only detail we ought to pay attention to is the axis we want to perform the function along (in NumPy it was called `axis`, in PyTorch `dim`).

Create a random tensor $v$ of ints of size (3, 2, 4) and print it.

In order to be sure you have understood what is going on, try to predict the result and then check that your prediction is wrong/correct.

1. Compute the min value in the entire tensor.
2. Compute the max value along axis 0.
3. Compute the min along axis 1.
4. Multi-dimensional axes: take the sum over axes (0, 1).

In [15]:
# Create v of shape (3, 2, 4)
v = torch.randint(0,11,(3,2,4))
print(v)

tensor([[[ 2,  5,  0,  2],
         [ 9,  4,  3,  5]],

        [[ 3,  9,  2,  3],
         [ 5,  7,  3,  8]],

        [[10,  1,  7,  2],
         [10,  3,  0,  1]]])

In [16]:
## 1: Compute the min value of v.
print(v.min())
## 2: Compute the max along axis 0.
print(v.max(0))
print(v.max(0)[0].shape)
## 3: Compute the min along axis 1.
print(v.min(1)) # 6,9,8,1 | 2,6,8,3 | 5,10,3,8
## 4: Compute the sum over axes (0, 1)
print(v.sum((0,1)))  # [19,34,20,22] (4,)

tensor(0)
torch.return_types.max(
values=tensor([[10,  9,  7,  3],
        [10,  7,  3,  8]]),
indices=tensor([[2, 1, 2, 1],
        [2, 1, 0, 1]]))
torch.Size([2, 4])
torch.return_types.min(
values=tensor([[ 2,  4,  0,  2],
        [ 3,  7,  2,  3],
        [10,  1,  0,  1]]),
indices=tensor([[0, 1, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 1]]))
tensor([39, 29, 15, 21])

### [`torch.dot`](https://docs.pytorch.org/docs/stable/generated/torch.dot.html#torch.dot), [`torch.matmul`](https://docs.pytorch.org/docs/stable/generated/torch.matmul), *

Unlike NumPy, Torch has a stricter policy on these operands:

- `*`: is the Hadamard product. I.e., element-wise product.
- [`torch.dot`](https://docs.pytorch.org/docs/stable/generated/torch.dot.html#torch.dot): only used to compute the dot product of two 1-dimensional tensors. Remember how confusing the dot product between multi-dimension NumPy vectors is (see Exercise 1)? PyTorch avoids this issue by simply forbidding the dimension of the input tensors to be greater than 1.
- [`torch.matmul`](https://docs.pytorch.org/docs/stable/generated/torch.matmul): or its alias `@` computes the matrix product. Can be used for larger than 2-dimensional tensors (it applies broadcasting, as much as in NumPy). Notice that the complexity of multiplying two $n\times n$ matrices is $O(n^3)$. We will take advantage of its relatively high time-complexity in order to show how much faster are GPUs with respect to CPUs later on in the notebook.

1. Create two random integer tensors $A$ and $B$ of compatible sizes and perform their Hadamard product (element by element product). Try these sizes (predict whether they work or not):
    - $A$ size (3, 4), $B$ size (3, 4).
    - $A$ size (3, 4), $B$ size (4, 4).
    - $A$ size (3, 4), $B$ size (1, 4).
2. Create two random 1-dimensional tensors $v, w$ and compute their dot product. If you can use multiple ways to compute it, check that indeed they return the same value.
3. Create $C$ of size (3, 4) and $D$ of size (4, 3). Compute the matrix product. Are the sizes compatible?
4. Create $E$ of size (3, 3) and $F$ of size (4, 3). Compute the matrix product. Are the sizes compatible? If not, use the transpose operator [`torch.t()`](https://docs.pytorch.org/docs/stable/generated/torch.t.html#torch.t) to adjust the dimensions of one of the two matrices and compute the matrix product.

In [17]:
## 1: Create A, B and perform hadamard product
# A (3,4), B (3,4) should work
a = torch.randint(0,11,(3,4))
b = torch.randint(0,11,(3,4))
print(a*b)
# A (3,4), B (4,4) does not work
a = torch.randint(0,11,(3,4))
b = torch.randint(0,11,(4,4))
#print(a*b)
# A (3,4), B (1,4) should work
a = torch.randint(0,11,(3,4))
b = torch.randint(0,11,(1,4))
print(a*b)
## 2: Create 1-dimensional tensors v, w and compute their dot product.
v = torch.tensor([1,2,3])
w = torch.tensor([3,2,1])
print(torch.dot(v,w))
## 3: Compute matrix product of C and D.
c = torch.randint(1,11,(3,4))
d = torch.randint(1,11,(4,3))
print(c @ d)
## 4: adjust dimensions using .T, and compute the matrix product E @ F
e = torch.randint(1,11,(3,3))
f = torch.randint(1,11,(4,3))
print(e @ f.t())

tensor([[10, 12, 25,  6],
        [18,  1,  6, 24],
        [60,  5, 18, 72]])
tensor([[24, 12,  2, 18],
        [20, 20,  7, 12],
        [ 8, 18,  0, 21]])
tensor(10)
tensor([[189,  70, 126],
        [235,  78, 158],
        [ 88,  30,  71]])
tensor([[101, 101, 141, 128],
        [ 19,  16,  24,  22],
        [ 90,  65, 100, 100]])

## Gradients

One of the useful features of PyTorch (that NumPy doesn't have) is that it is possible to compute automatically the gradient of functions. 
As you will see, the gradient of a function is one of the key ingredients of the backpropagation algorithm, used to train neural nets.
This is also one of the reason why PyTorch is so ubiquitous to neural nets applications.

Assume we have tensor $x = [2], y = [2]$. We have $z = 2x^2 + 3y = [14]$.

We know that $\frac{\delta z}{\delta x} = 4x$, $\frac{\delta z}{\delta y} = 3$. Since we are evaluating the point $x=2, y=2$, we get that the gradient is (8, 3). The gradients are going to be stored in `x.grad` and `y.grad` if we specify the option `requires_grad=True`. We can let PyTorch compute the gradients by invoking `z.backward()`. Check that indeed `x.grad` and `y.grad` hold the desired values.

In [18]:
x = torch.tensor([2], dtype=torch.float64, requires_grad=True)
y = torch.tensor([2], dtype=torch.float64, requires_grad=True)
z = 2 * x*x + 3 * y
z.backward()
print(x.grad)
print(y.grad)

tensor([8.], dtype=torch.float64)
tensor([3.], dtype=torch.float64)

1. Create tensors $s = [1]$ and $t = [1]$, define a new tensor $w = 5s + 6$ and compute its gradient. What is the gradient associated to $t$? (Notice that $w$ does not depend on $t$). 
2. What happens if we try to define an integer tensor with `requires_grad=True`?
3. What happens if we call `numpy()` on a tensor that has `requires_grad=True`?

In [19]:
s = torch.tensor([1], dtype=torch.float64, requires_grad=True)
t = torch.tensor([1], dtype=torch.float64, requires_grad=True)
## 1: gradient of t for w = 5s + 6.
w = 5 * s + 6
w.backward()
print(s.grad)
print(t.grad)
## 2: integer tensor with requires_grad.
#l = torch.tensor([1], dtype=torch.int64, requires_grad=True)
## 3: compute .numpy() of a tensor with requires_grad.
# s.numpy()

tensor([5.], dtype=torch.float64)
None

In this section we point out a very important feature of gradients, namely that they are *cumulative*! In order to see what does that mean, let's see in practice the example that was given in class:

1. Create tensors $x=[2], y=[3]$ (with flag `requires_grad=True`).
2. Compute $z = x * x + y$ and perform the backward pass.
3. Check that the gradients are as expected: $\frac{\delta z}{\delta x}=2x=4$, $\frac{\delta z}{\delta y} = 1$.
4. Compute $g = xy + 3x$ and perform che backward pass.
5. Check out the gradients: $\frac{\delta g}{\delta x}=y + 3=6$, $\frac{\delta g}{\delta y} = x = 2$.
6. Do you see the expected value? Can you explain why? (hint: gradients are *cumulative*).
7. In order to fix this potential issue, use [`torch.zero_grad()`](https://docs.pytorch.org/docs/stable/generated/torch.optim.Optimizer.zero_grad.html) in between the computation of $z$ and $g$. Do you observe the expected gradient now?

In [ ]:
## 1: create x, y.
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)
## 2: compute z.
z = x * x + y
z.backward()
## 3: check out gradients of x, y.
print(x.grad)
print(y.grad)
## 4: compute g.
g = x*y + 3*x
g.backward()
## 5: check out gradients of x, y
print(x.grad)
print(y.grad)
## 7: Repeat 1-5 using torch.zero_grad()
## 1: create x, y.
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)
## 2: compute z.
z = x * x + y
z.backward()
## 3: check out gradients of x, y.
print(x.grad)
print(y.grad)
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)
## 4: compute g.
g = x*y + 3*x
g.backward()
## 5: check out gradients of x, y
print(x.grad)
print(y.grad)

tensor(4.)
tensor(1.)
tensor(10.)
tensor(3.)

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

## Device (GPU vs CPU)

In this section we will learn how do computation using the GPU instead of the CPU: notice that this is the main reason why, in Deep Learning applications, PyTorch is used over NumPy.

By default, tensors are accessed by the CPU. You can check it easily using the [`.device()`](https://pytorch.org/docs/stable/tensor_attributes.html#torch.device) method.
1) Create an identity matrix of size (4, 4) and access its device attribute.

In [26]:
## 1: see .device of a matrix

v = torch.eye(4)  # create a tensor
print(v.device)

cpu

Hence, every time we want to use the GPU, we need to explicitly move the tensors to the desired device. Careful here: your laptop doesn't necessarily have a dedicated GPU. And, even if it has one, it might not be compatible with CUDA (the NVIDIA interface that allows computations to be performed on the GPU).

You can check if CUDA is available on your machine by simply using [`cuda.is_available()`](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html).

In [27]:
torch.cuda.is_available()

False

If the above returns False, it could be either because you didn't install correctly CUDA, or because you laptop doesn't have a GPU compatible with it. 
If you have a MacBook with Apple Silicon processors, you can still use the device `mps`:

In [28]:
# For mac M1/2/3/* users
torch.backends.mps.is_available()

False

We can set the device to one of these three options:
- `cuda` (if you have a NVIDIA graphics card). Might be `cuda:0` etc if you have more than one.
- `mps` (if you have a MacBook with M1/2/3/* processor)
- `cpu` otherwise

If your laptop doesn't have any of the above-mentioned devices apart from the CPU, you can use Kaggle's notebooks: they offer free hours of GPU per week (they count the hours the kernel is running, not if you are actually using the notebook. Hence, remember to shut the kernel down when you don't use it!!!)

If you are using Kaggle platform for your projects (we recommend you to do that), you have at your disposal 30h/week of free GPUs: in order to activate it, you need to open a notebook, go to settings -> accelerator and you can select a GPU from there. If the GPU options are non-clickable, it is because you have to verify you account using your phone number. Go to home -> your picture (top right border) -> settings -> phone verification. Before the options become actually clickable you will need to wait a few minutes (<5').

In [29]:
device = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu')
device

device(type='cpu')

Finally, move the tensor `v` you created earlier to the most convenient device. Use function [`.to`](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html). Careful: is it an in-place method? Check that the device is indeed correct.

In [31]:
# Move vector v to the correct device. Check it is indeed on the desired device.
v = v.to(device)
print(v.device)

cpu

You can also create a tensor and send it directly to the correct device. 
1. Create a tensor of ones of size (3, 3) and specify in its constructor the `device` attribute. Check that, indeed, the tensor has been initialized with the correct device.

In [32]:
## 1: Create a tensor and initialize it to the correct device.
x = torch.ones((3,3), device=device)
x.device

device(type='cpu')

### GPUs vs CPUs

Now, we prove empirically that GPUs are much faster than CPUs at doing large calculations.

Create large tensors $G, H$ both of size (15000, 15000). Take their matrix product and measure how long it takes (use [`%%time`](https://ipython.readthedocs.io/en/9.2.0/interactive/magics.html) cell magic notebook function).

In [26]:
device = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu')
device

device(type='mps')

In [27]:
# Create E and F
G = torch.rand(15000, 15000)
H = torch.rand(15000, 15000)

In [28]:
%%time
G @ H

CPU times: user 7.42 s, sys: 460 ms, total: 7.88 s
Wall time: 4.22 s

tensor([[3726.7639, 3756.2234, 3699.6274,  ..., 3721.4380, 3738.4131,
         3754.0791],
        [3755.6550, 3777.7593, 3741.3372,  ..., 3755.9939, 3770.7937,
         3747.3943],
        [3767.4851, 3801.6426, 3752.6885,  ..., 3770.9099, 3765.2354,
         3759.9216],
        ...,
        [3761.4927, 3790.4978, 3766.2434,  ..., 3771.4724, 3783.7256,
         3779.7422],
        [3765.3115, 3799.5425, 3747.0039,  ..., 3755.6519, 3781.7246,
         3793.4346],
        [3757.9209, 3775.9148, 3742.3926,  ..., 3752.0540, 3760.3030,
         3760.2754]])

Move $E$ and $F$ to the most convenient device at your disposal (different from CPU, if possible), and compute the same matrix product.

In [29]:
# Move the tensors to GPU in another cell, so that the time is not counted.
G = G.to(device)
H = H.to(device)

In [30]:
%%time
G @ H

CPU times: user 21 ms, sys: 26.7 ms, total: 47.7 ms
Wall time: 163 ms

tensor([[3726.7639, 3756.2234, 3699.6274,  ..., 3721.4304, 3738.4143,
         3754.0664],
        [3755.6550, 3777.7593, 3741.3372,  ..., 3755.9897, 3770.8015,
         3747.3979],
        [3767.4851, 3801.6426, 3752.6885,  ..., 3770.9121, 3765.2329,
         3759.9214],
        ...,
        [3761.4927, 3790.4978, 3766.2434,  ..., 3771.4734, 3783.7253,
         3779.7429],
        [3765.3115, 3799.5425, 3747.0039,  ..., 3755.6516, 3781.7271,
         3793.4272],
        [3757.9209, 3775.9148, 3742.3926,  ..., 3752.0532, 3760.2930,
         3760.2812]], device='mps:0')

Side note: on my laptop (MacBook) I noticed a performance improvement by $\approx\times 10$. On Kaggle the performance improvement is much larger (from >20'' to <<1').

At the end of this task, if you are using Kaggle, remember to shut down your kernel (or Kaggle will continue charging you GPU time).

# A super quick introduction to pandas

[Pandas](https://pandas.pydata.org/) is the equivalent of a Python database (but it is also a "data analysis and manipulation tool"). Or Python's version of Excel, if you prefer.

Install it in your environment (using your IDE's GUI, or by typing in your command line `conda install pandas`).

Next, we will see the most basic usage of pandas: making queries and modifying your data. Keep in mind that pandas does much more than that: see this simple [cheatsheet](https://pandas.pydata.org/docs/user_guide/10min.html) for reference.

It is best practice, in pandas, to use the shortcut `pd` on import.

In [31]:
import pandas as pd

A table in pandas is called `pd.DataFrame`. Single columns, instead, are called `pd.Series` (a `pd.Series` is the pandas equivalent of a `torch.tensor` or `np.array`).
You can create a table using some data in a dictionary, or importing it from any well-formatted file (see, e.g., [`pd.read_csv`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv)).

In [32]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Ethan"],
    "Department": ["HR", "IT", "Finance", "IT", "HR"],
    "Salary": [50000, 60000, 55000, 65000, 52000],
    "Years_at_Company": [2, 5, 3, 7, 1],
}

# Create a DataFrame
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])
df

      Name Department  Salary  Years_at_Company
a    Alice         HR   50000                 2
b      Bob         IT   60000                 5
c  Charlie    Finance   55000                 3
d    Diana         IT   65000                 7
e    Ethan         HR   52000                 1

As you see, the data is nicely displayed in a table. The additional column (without a title) is the index: namely, the name of every row. By default it is an increasing number, but you can change it to be anything (in our case, we used letters).

## Queries

You can select columns using the usual `[]` notation (this returns a `pd.Series`):

In [33]:
df['Department']

a         HR
b         IT
c    Finance
d         IT
e         HR
Name: Department, dtype: object

Or, multiple columns with the ``[[]]`` notation (this returns a `pd.DataFrame`):

In [34]:
df[['Department','Salary']]

  Department  Salary
a         HR   50000
b         IT   60000
c    Finance   55000
d         IT   65000
e         HR   52000

You can select rows (as much as in SQL) according to any condition: it is enough to create a boolean vector with the rows to select, and use the following syntax:

In [35]:
df[[True, True, False, False, True]]

    Name Department  Salary  Years_at_Company
a  Alice         HR   50000                 2
b    Bob         IT   60000                 5
e  Ethan         HR   52000                 1

You can create boolean vectors according to any condition using element-wise boolean operators:

In [36]:
df['Salary'] > 53000

a    False
b     True
c     True
d     True
e    False
Name: Salary, dtype: bool

Putting everything together, write a query to select the names of the people that earn more than 53000.

In [37]:
# Write a query to select the names of the people that earn more than 53000.
df

      Name Department  Salary  Years_at_Company
a    Alice         HR   50000                 2
b      Bob         IT   60000                 5
c  Charlie    Finance   55000                 3
d    Diana         IT   65000                 7
e    Ethan         HR   52000                 1

# [`pd.loc`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [`pd.iloc`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html) functions

Pandas offers additional ways to select rows and columns:

- [`pd.loc`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html): allows you to select rows and columns by the index value.
- [`pd.iloc`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html): allows you to select rows and columns by the integer position. It is actually deprecated.

You can access the second row by either using the index value `'b'` (and function `.loc`) or by integer position 1 (and function `.iloc`) as in the following example.

In [38]:
df.loc['b']

Name                  Bob
Department             IT
Salary              60000
Years_at_Company        5
Name: b, dtype: object

In [39]:
df.iloc[1]

Name                  Bob
Department             IT
Salary              60000
Years_at_Company        5
Name: b, dtype: object

If you read more carefully the documentation of the two functions, you will see that, indeed, both [`pd.loc`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [`pd.iloc`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html) allow more flexibility like selecting intervals, arrays of booleans and so on.

## Apply functions

Anothe common feature of pandas, is applying functions element-wise to columns: see below for an example.

In [40]:
# Double every salary:
df['Salary'].apply(lambda x: x * 2)

a    100000
b    120000
c    110000
d    130000
e    104000
Name: Salary, dtype: int64

What is [`lambda`](https://www.w3schools.com/python/python_lambda.asp) above?

As a final exercise, write a query for the names of the employees with a salary above 51000 and below 56000 using the `.apply` operator.

In [41]:
# Write a query to select the names of the people that earn a salary between 51000 and 56000. Use the .apply() operator.
df

      Name Department  Salary  Years_at_Company
a    Alice         HR   50000                 2
b      Bob         IT   60000                 5
c  Charlie    Finance   55000                 3
d    Diana         IT   65000                 7
e    Ethan         HR   52000                 1