<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-A01793817/blob/main/Modulo%204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nombre: Javier Antonio Rodríguez Rudas


Matrícula: A01793817

Módulo 4


4.1 Leer archivos en Python
Sentencia para abrir un archivo: file1 = open(parametro 1, parametro 2)

parámetro 1 =  ruta del archivo
parámetro 2 =  es el modo, los valores pueden ser:

r -> lectura
w -> escritura
a -> agregar

ejemplo file1 = open("\escritorio\prueba.cvs","w")

ejemplo#1:
with open("ejemplo.txt","r") as file1
    file_stuff = file1.read()
    print(file_stuff)
print(file1.closed)
print(file_stuff)


ejemplo#2:
with open("ejemplo.txt", "r") as File2
    file_stuff = File2.readlines()
    print(file_stuff)

ejemplo#3:
with open("Ejemplo3.txt","r") as File3
    for line in File3
    print(line)

ejemplo#4 - Leer por cantidad de posiciones:
with open("ejemplo4.txt","r") as File4
    file_stuff = File4.readlines(4) 
    print(file_stuff)   #Imprime las primeras cuatros posiciones

In [ ]:
# Read the Example1.txt
example1 = "Example1.txt"
file1 = open(example1, "r")

In [ ]:
# Print the path of file

file1.name

In [ ]:
# Print the mode of file, either 'r' or 'w'

file1.mode

In [ ]:
# Read the file

FileContent = file1.read()
FileContent

In [ ]:
# Print the file with '\n' as a new line

print(FileContent)

In [ ]:
# Type of file content

type(FileContent)

In [ ]:
# Close file after finish

file1.close()

In [ ]:
# Open file using with

with open(example1, "r") as file1:
    FileContent = file1.read()
    print(FileContent)

In [ ]:
# Verify if the file is closed

file1.closed

In [ ]:
# See the content of file

print(FileContent)

In [ ]:
# Read first four characters

with open(example1, "r") as file1:
    print(file1.read(4))

In [ ]:
# Read certain amount of characters

with open(example1, "r") as file1:
    print(file1.read(4))
    print(file1.read(4))
    print(file1.read(7))
    print(file1.read(15))

In [ ]:
with open(example1, "r") as file1:
    print(file1.read(16))
    print(file1.read(5))
    print(file1.read(9))

In [ ]:
# Read one line

with open(example1, "r") as file1:
    print("first line: " + file1.readline())

In [ ]:
with open(example1, "r") as file1:
    print(file1.readline(20)) # does not read past the end of line
    print(file1.read(20)) # Returns the next 20 chars

In [ ]:
# Iterate through the lines

with open(example1,"r") as file1:
        i = 0;
        for line in file1:
            print("Iteration", str(i), ": ", line)
            i = i + 1

In [ ]:
# Read all lines and save as a list

with open(example1, "r") as file1:
    FileasList = file1.readlines()

In [ ]:
# Print the first line

FileasList[0]

In [ ]:
# Print the third line

FileasList[2]

4.2 Escribir archivos en Python

sentencia: File1 = open("/resources/data/Tema4.txt","r")

directorio: /resources/data/
mode: r
objeto: File1

Escribir en un archivo ejem -> File1.write("Estas es una linea")
Escribir en un archivo ejem -> File1.write("Esta es la linea 1\n")
                               File1.write("Esta es la linea 2\n")
Escribir en un archivo a través de un ciclo for:

Ejem ->

Lines=["Esta es la linea A\n","Esta es la linea B\n"]
with open("/resource/data/prueba1.txt","w") as File1:
    for line in Lines
      File1.write(line)
Adjuntar una línea en un archivo:

Ejem ->

with open("/resource/data/prueba1.txt","a") as File1
    File1.write("Esto es la línea C")

Ejem Copiar lineas de un archivo a otro ->

with open("/resource/data/prueba1.txt","r") as readFile
    with open("/resource/data/prueba2.txt","w") as writeFile
        for line in readFile
          writeFile.write(line)

In [ ]:
# Write line to file
exmp2 = 'Example2.txt'
with open(exmp2, 'w') as writefile:
    writefile.write("This is line A")

In [ ]:
# Read file
with open(exmp2,'r') as readfile:
 print(readfile.read())

This is line A1
This is line B2
This is line C3

In [ ]:
# Write line to file
with open(exmp2,'w') as writefile:
  writefile.write("Esta es la línea A\n")
  writefile.write("Esta es la línea B\n")

In [ ]:
# Sample list of text

Lines = ["This is line Javier\n", "This is line Pedro\n", "This is line Juan\n"]
Lines

['This is line Javier\n', 'This is line Pedro\n', 'This is line Juan\n']

In [ ]:
# Write the strings in the list to text file

with open('Example2.txt', 'w') as writefile:
    for line in Lines:
        writefile.write(line)

In [ ]:
with open('Example2.txt','r') as readfile:
  print(readfile.read())

Overwrite

In [ ]:
with open('Example2.txt', 'w') as writefile:
    writefile.write("Overwrite\n")
with open('Example2.txt', 'r') as testwritefile:
    print(testwritefile.read())

Overwrite

In [ ]:
# Write a new line to text file
with open('Example2.txt','a') as attfile:
  attfile.write("Linea 1\n")
  attfile.write("Linea 2\n")
  attfile.write("linea 3\n")
with open('Example2.txt','r') as readfile:
  print(readfile.read())

Overwrite
Linea 1
Linea 2
linea 3
This is line E
This is line E
Linea 1
Linea 2
linea 3

In [ ]:
with open('Example2.txt', 'a+') as testwritefile:
    testwritefile.write("This is line E\n")
    print(testwritefile.read())

In [ ]:
with open('Example2.txt', 'a+') as testwritefile:
    print("Initial Location: {}".format(testwritefile.tell()))
    
    data = testwritefile.read()
    if (not data):  #empty strings return false in python
            print('Read nothing') 
    else: 
            print(testwritefile.read())
            
    testwritefile.seek(0,0) # move 0 bytes from beginning.
    
    print("\nNew Location : {}".format(testwritefile.tell()))
    data = testwritefile.read()
    if (not data): 
            print('Read nothing') 
    else: 
            print(data)
    
    print("Location after read: {}".format(testwritefile.tell()) )

Initial Location: 103
Read nothing

New Location : 0
Overwrite
Linea 1
Linea 2
linea 3
This is line E
This is line E
Linea 1
Linea 2
linea 3
This is line E

Location after read: 103

In [ ]:
with open('Example2.txt', 'r+') as testwritefile:
    data = testwritefile.readlines()
    testwritefile.seek(0,0) #write at beginning of file
   
    testwritefile.write("Line 1" + "\n")
    testwritefile.write("Line 2" + "\n")
    testwritefile.write("Line 3" + "\n")
    testwritefile.write("finished\n")
    #Uncomment the line below
    #testwritefile.truncate()
    testwritefile.seek(0,0)
    print(testwritefile.read())

Line 1
Line 2
Line 3
finished
a 3
This is line E
This is line E
Linea 1
Linea 2
linea 3
This is line E

In [ ]:
# Copy file to another

with open('Example2.txt','r') as readfile:
    with open('Example3.txt','w') as writefile:
          for line in readfile:
                writefile.write(line)

In [ ]:
# Verify if the copy is successfully executed

with open('Example3.txt','r') as testwritefile:
    print(testwritefile.read())

Line 1
Line 2
Line 3
finished
a 3
This is line E
This is line E
Linea 1
Linea 2
linea 3
This is line E

In [ ]:
def cleanFiles(currentMem,exMem):
    with open(currentMem,'r+') as writeFile: 
        with open(exMem,'a+') as appendFile:
            #get the data
            writeFile.seek(0)
            members = writeFile.readlines()
            #remove header
            header = members[0]
            members.pop(0)
                
            inactive = [member for member in members if ('no' in member)]
            '''
            The above is the same as 

            for member in members:
            if 'no' in member:
                inactive.append(member)
            '''
            #go to the beginning of the write file
            writeFile.seek(0) 
            writeFile.write(header)
            for member in members:
                if (member in inactive):
                    appendFile.write(member)
                else:
                    writeFile.write(member)      
            writeFile.truncate()
                
memReg = 'members.txt'
exReg = 'inactive.txt'
cleanFiles(memReg,exReg)

# code to help you see the files

headers = "Membership No  Date Joined  Active  \n"

with open(memReg,'r') as readFile:
    print("Active Members: \n\n")
    print(readFile.read())
    
with open(exReg,'r') as readFile:
    print("Inactive Members: \n\n")
    print(readFile.read())

4.3 Liberia Panda

Ejem -> import pandas

Cargar un archivo csv

Ejem ->
import pandas

csv_path="file.csv"
df=pandas.read_csv(csv_path)

Agregar alias al importa la libreria

Ejem ->
import pandas as pd

csv_path="file.csv"
df=pd.read_csv(csv_path)

Pasar un archivo csv a un Dataframes

Ejem ->

import pandas

csv_path="file.csv"
df=pd.read_csv(csv_path)
df.head()

Ejemplo

songs={'ALBUM':['Black in Black', 'Fear in dark'],'AÑO':[2000,1999],'TAMAÑO':['01:00:00','02:00,00']}

songs_frame = pd.DataFrame(songs)

Para obtener una columna
Ejem ->
x=df[['TAMAÑO']]

Ejemplos par acceder a los valores:

i: fila
x: columna
Nota arrancan en la posición 0

df.ix[0,0]:'Black in Black'
df.ix[1,0]:'Fear in dark'
df.ix[0,'AÑO']
z=df.ix[0:2,0:3]
z=df.ix[0:2,'ALBUM':'TAMAÑO']

In [ ]:
import pandas as pd

df=pd.DataFrame({'a':[11,21,31],'b':[21,22,23]})
df.head(3)

    a   b
0  11  21
1  21  22
2  31  23

In [ ]:
df['a']

0    11
1    21
2    31
Name: a, dtype: int64

QUESTION 1

Consider the dataframe df. How would you find the element in the second row and first column?
resp. df.ix[1,0] or df.iloc[1,0]

QUESTION 2

Will the following code run?

import pandas as banana

df=banana.DataFrame({'a':[11,21,31],'b':[21,22,23]})

df.head()
resp. Yes

Trabajar y guardar datos en Panda

Sentencia unique -> Sirve para eliminar todos los elementos duplicados en un DataFrame.

Ejem -> df['TAMAÑO'].unique()

Utiliar operadores de desigualdad

Al utilizar operadores de desigualdad el resultado es un booleam
Ejem -> df['TAMAÑO']>= 1980

Nuevo dataframe apartir de un dataframe origen
Ejem -> df1=df[df['TAMAÑA']> 1999]

Guardar un dataframe
Ejem ->df1.to_csv('new_songes.csv')

QUESTION 1

Consider the dataframe: df=pd.DataFrame({'a':[1,2,1],'b':[1,1,1]})

What type does the following return: df['a']==1 ?
resp. bool

QUESTION 2

What task does the following method perform: df.to_csv("file.csv")?
resp. Save a dataframe to a csv file.

In [ ]:
#LABORATORIO
df=pd.DataFrame({'a':[1,2,1],'b':[1,1,1]})

In [ ]:
# 1.Find the unique values in column  'a' :
df['a'].unique()

array([1, 2])

In [ ]:
# 2.Return a dataframe with only the rows where column  a  is less than two:
df[df['a']<2]

   a  b
0  1  1
2  1  1

Ejercicio de DataFrame

In [ ]:
# Use a variable q to store the column Rating as a dataframe
# Write your code below and press Shift+Enter to execute

q=df[['Rating']]

q

In [ ]:
#Assign the variable q to the dataframe that is made up of the column Released and Artist:
q = df[['Released', 'Artist']]
q

In [ ]:
#Access the 2nd row and the 3rd column of df:
df.iloc[1, 2]

In [ ]:
#Use the following list to convert the dataframe index df to characters and assign it to df_new; find the element corresponding to the row index a and column 'Artist'. Then select the rows a through d for the column 'Artist'
df_new=df
df_new.index=new_index
df_new.loc['a', 'Artist']
df_new.loc['a':'d', 'Artist']

Review Questions

Question 1

What do the following lines of code do?

with open("Example1.txt","r") as file1:

FileContent=file1.readlines()

print(FileContent)

resp. Read the file "Example1.txt".

Question 2

What do the following lines of code do?

with open("Example2.txt","w") as writefile:

writefile.write("This is line A\n")

writefile.write("This is line B\n")

resp. Write to the file "Example2.txt".

Question 3

What do the following lines of code do?

with open("Example3.txt","a") as file1:

file1.write("This is line C\n")

resp. Append the file "Example3.txt".

Question 4

What is the result of applying the following method df.head() to the dataframe "df"?

resp. Prints out the entire dataframe.