<a href="https://colab.research.google.com/github/pragatii-sharmaa/Deep-Learning-codes/blob/main/PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.6.0+cu124

# Creating Tensors

Using empty

In [ ]:
a= torch.empty(3,3)
a

tensor([[ 0.0000e+00,  0.0000e+00, -9.2361e-03],
        [ 4.4745e-41, -9.2361e-03,  4.4745e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [ ]:
type(a)

torch.Tensor

Using zeros

In [ ]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Using Ones

In [ ]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

Using rand without reproducibility

In [ ]:
torch.rand(2,3)

tensor([[0.2863, 0.8412, 0.2359],
        [0.3053, 0.5671, 0.6648]])

Using rand with reproducibility

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

Using arange

In [ ]:
torch.arange(1,20,2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

Using linspace

In [ ]:
torch.linspace(1,100,10)

tensor([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

Using eye

In [ ]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Using Full

In [ ]:
torch.full((4,4),2)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])

**Generating _like tensors**

In [ ]:
x= torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[3617347299805510178, 3775199757219161398, 7305460056833798245],
        [7305182065089603125, 3616776658674004025, 7454421801564381749]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

**Data Types in Tensors**

In [ ]:
x.dtype

torch.int64

In [ ]:
d= torch.tensor([1.0,2.0,3.0],dtype= torch.int32)
d.dtype

torch.int32

In [ ]:
f= torch.tensor([10,20,30],dtype= torch.float16)
f.dtype

torch.float16

# Mathematical Operations

**Scalar operations**

In [ ]:
p= torch.rand(2,3)
p= p*100
p

tensor([[71.1765, 78.7581, 41.8305],
        [90.1415, 99.6886, 75.6515]])

In [ ]:
p+2   #add

tensor([[ 73.1765,  80.7581,  43.8305],
        [ 92.1415, 101.6886,  77.6515]])

In [ ]:
p-2      #sub

tensor([[69.1765, 76.7581, 39.8305],
        [88.1415, 97.6886, 73.6515]])

In [ ]:
p*2.2      #multiplication

tensor([[156.5884, 173.2677,  92.0272],
        [198.3113, 219.3150, 166.4332]])

In [ ]:
p/3       #division

tensor([[23.7255, 26.2527, 13.9435],
        [30.0472, 33.2295, 25.2172]])

In [ ]:
p%2         #modulo

tensor([[1.1765, 0.7581, 1.8305],
        [0.1415, 1.6886, 1.6515]])

In [ ]:
p//2      #int divison

tensor([[35., 39., 20.],
        [45., 49., 37.]])

In [ ]:
p**2       #power

tensor([[5066.1006, 6202.8325, 1749.7931],
        [8125.4902, 9937.8232, 5723.1431]])

**Tensor Operations**

In [ ]:
q= torch.rand(2,3)
r= torch.rand(2,3)
q=  q*100
r= r*100

In [ ]:
p

tensor([[71.1765, 78.7581, 41.8305],
        [90.1415, 99.6886, 75.6515]])

In [ ]:
q

tensor([[22.3894, 30.2346, 17.8419],
        [82.3844, 55.5744, 97.7024]])

In [ ]:
p+q

tensor([[ 93.5659, 108.9927,  59.6725],
        [172.5259, 155.2630, 173.3538]])

In [ ]:
p-q

tensor([[ 48.7872,  48.5234,  23.9886],
        [  7.7571,  44.1142, -22.0509]])

In [ ]:
p*q

tensor([[1593.5975, 2381.2200,  746.3375],
        [7426.2510, 5540.1353, 7391.3267]])

In [ ]:
p/q

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [ ]:
p//q

tensor([[3., 2., 2.],
        [1., 1., 0.]])

In [ ]:
p**q

tensor([[       inf,        inf, 8.5227e+28],
        [       inf,        inf,        inf]])

In [ ]:
p%q

tensor([[ 4.0085, 18.2888,  6.1467],
        [ 7.7571, 44.1142, 75.6515]])

**Operations on a single tensor**

In [ ]:
z= torch.tensor([1.12,2.2,4.4,-5,-3.2])

In [ ]:
torch.abs(z)

tensor([1.1200, 2.2000, 4.4000, 5.0000, 3.2000])

In [ ]:
torch.ceil(z)

tensor([ 2.,  3.,  5., -5., -3.])

In [ ]:
torch.floor(z)

tensor([ 1.,  2.,  4., -5., -4.])

In [ ]:
torch.neg(z)

tensor([-1.1200, -2.2000, -4.4000,  5.0000,  3.2000])

In [ ]:
torch.round(z)

tensor([ 1.,  2.,  4., -5., -3.])

In [ ]:
torch.clamp(z,min=2,max=3)

tensor([2.0000, 2.2000, 3.0000, 2.0000, 2.0000])

Reduction Operation

In [ ]:
x= torch.tensor([[1, 2, 3],
        [4, 5, 6]],dtype=torch.float32)

In [ ]:
torch.sum(x)  #sum of all the elements

tensor(21.)

In [ ]:
torch.sum(x,dim=0) #sum along col. dim=0

tensor([5., 7., 9.])

In [ ]:
torch.sum(x,dim=1) #sum along rows. dim=1

tensor([ 6., 15.])

In [ ]:
torch.mean(x)

tensor(3.5000)

In [ ]:
torch.median(x)

tensor(3.)

In [ ]:
torch.std(x)

tensor(1.8708)

In [ ]:
torch.var(x)

tensor(3.5000)

In [ ]:
torch.argmax(x)

tensor(5)

In [ ]:
torch.argmin(x)

tensor(0)

In [ ]:
torch.max(x)

tensor(6.)

In [ ]:
torch.min(x)

tensor(1.)

**Matrix Operations**

In [ ]:
m1= torch.randint(size=(2,3),low=0,high=10)
m1

tensor([[7, 0, 0],
        [9, 5, 7]])

In [ ]:
m2=torch.randint(size=(3,2),low=0,high=10)
m2

tensor([[3, 9],
        [4, 0],
        [5, 7]])

In [ ]:
torch.matmul(m1,m2)

tensor([[ 21,  63],
        [ 82, 130]])

In [ ]:
torch.transpose(m1,0,1)

tensor([[7, 9],
        [0, 5],
        [0, 7]])

In [ ]:
m3= torch.randint(size=(3,3),low=0,high=10,dtype= torch.float32)
m3

tensor([[5., 9., 9.],
        [7., 5., 9.],
        [8., 9., 7.]])

In [ ]:
torch.det(m3)

tensor(184.0000)

In [ ]:
torch.inverse(m3)

tensor([[-0.2500,  0.0978,  0.1957],
        [ 0.1250, -0.2011,  0.0978],
        [ 0.1250,  0.1467, -0.2065]])

In [ ]:
vector1= torch.tensor([1,2,3,4])
vector2= torch.tensor([9,8,7,6])

In [ ]:
torch.dot(vector1,vector2)

tensor(70)

**Comparison Operations**

In [ ]:
i= torch.randint(size= (2,3),low=15,high=30)
i

tensor([[24, 27, 26],
        [17, 17, 18]])

In [ ]:
j= torch.randint(size= (2,3),low=15,high=30)
j

tensor([[18, 21, 26],
        [15, 25, 25]])

In [ ]:
i>j

tensor([[ True,  True, False],
        [ True, False, False]])

In [ ]:
i<j

tensor([[False, False, False],
        [False,  True,  True]])

In [ ]:
i==j

tensor([[False, False,  True],
        [False, False, False]])

In [ ]:
i!=j

tensor([[ True,  True, False],
        [ True,  True,  True]])

**Special Functions**

In [ ]:
k= torch.randint(size=(3,3),low=5,high=50)
k

tensor([[39,  8, 23],
        [23, 28, 18],
        [ 5,  5, 16]])

In [ ]:
torch.log(k)

tensor([[3.6636, 2.0794, 3.1355],
        [3.1355, 3.3322, 2.8904],
        [1.6094, 1.6094, 2.7726]])

In [ ]:
torch.exp(k)

tensor([[8.6593e+16, 2.9810e+03, 9.7448e+09],
        [9.7448e+09, 1.4463e+12, 6.5660e+07],
        [1.4841e+02, 1.4841e+02, 8.8861e+06]])

In [ ]:
torch.sqrt(k)

tensor([[6.2450, 2.8284, 4.7958],
        [4.7958, 5.2915, 4.2426],
        [2.2361, 2.2361, 4.0000]])

In [ ]:
torch.sigmoid(k)

tensor([[1.0000, 0.9997, 1.0000],
        [1.0000, 1.0000, 1.0000],
        [0.9933, 0.9933, 1.0000]])

In [ ]:
torch.relu(k)

tensor([[39,  8, 23],
        [23, 28, 18],
        [ 5,  5, 16]])

In [ ]:
k= torch.randint(size=(3,3),low=5,high=50,dtype=torch.float32)
k

tensor([[14.,  5., 23.],
        [24., 47., 17.],
        [43., 28., 25.]])

In [ ]:
torch.softmax(k, dim=0) # Specify dim=0 for column-wise softmax

tensor([[2.5437e-13, 5.7495e-19, 1.1917e-01],
        [5.6028e-09, 1.0000e+00, 2.9539e-04],
        [1.0000e+00, 5.6028e-09, 8.8054e-01]])

In [ ]:
torch.softmax(k, dim=1) # Specify dim=1 for row-wise softmax

tensor([[1.2339e-04, 1.5228e-08, 9.9988e-01],
        [1.0262e-10, 1.0000e+00, 9.3576e-14],
        [1.0000e+00, 3.0590e-07, 1.5230e-08]])

**Inplace Operations**

In [ ]:
a= torch.tensor([1,23,4,44])
b= torch.tensor([5,6,21,54])

In [ ]:
a.add_(b)

tensor([ 6, 29, 25, 98])

In [ ]:
a.mul_(b)

tensor([   5,  138,   84, 2376])

Copying a Tensor

In [ ]:
a= torch.tensor([12,3,44,5,6,77])
b=a.clone()   #----------> using the clone operation

In [ ]:
b

tensor([12,  3, 44,  5,  6, 77])

In [ ]:
a[0]= 43

In [ ]:
a

tensor([43,  3, 44,  5,  6, 77])

In [ ]:
b

tensor([12,  3, 44,  5,  6, 77])

**Tensors operations on GPU**

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device= torch.device('cuda')

Creating a new tensor on GPU

In [ ]:
torch.rand((2,3),device=device)

tensor([[0.4803, 0.2770, 0.6081],
        [0.5818, 0.2763, 0.2903]], device='cuda:0')

In [ ]:
a= torch.rand(2,3)

In [ ]:
b= a.to(device)

In [ ]:
a

tensor([[0.2657, 0.4418, 0.5676],
        [0.0746, 0.1374, 0.0649]])

In [ ]:
b

tensor([[0.2657, 0.4418, 0.5676],
        [0.0746, 0.1374, 0.0649]], device='cuda:0')

In [ ]:
b+5

tensor([[5.2657, 5.4418, 5.5676],
        [5.0746, 5.1374, 5.0649]], device='cuda:0')

# AutoGrad

In [ ]:
# Create a tensor with gradient tracking
x = torch.tensor([2.0], requires_grad=True)  #scalar with value 2.0
x

tensor([2.], requires_grad=True)

In [ ]:
# Perform an operation -------------> mathematical function
y = x**2 + 3*x + 5
y

tensor([15.], grad_fn=<AddBackward0>)

In [ ]:
# Backward pass
y.backward()

In [ ]:
# Gradient (dy/dx) = 2x + 3 at x=2
print(x.grad)

None

In [ ]:
#Example 2
x= torch.tensor(7.0, requires_grad=True)
x

tensor(7., requires_grad=True)

In [ ]:
y= x**2
y

tensor(49., grad_fn=<PowBackward0>)

In [ ]:
z= torch.sin(y)
z

tensor(-0.9538, grad_fn=<SinBackward0>)

In [ ]:
z.backward()

In [ ]:
x.grad

tensor(4.2083)

# Pipeine PyTorch

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

Loading the breast cancer dataset

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

Extracting info from the dataset

In [ ]:
df.shape

(569, 33)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

Data Preprocessing

In [ ]:
df= df.drop(columns=['id', 'Unnamed: 32'])

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
X= df.iloc[:,1:]
X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
y= df.iloc[:,0]
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

Performing train test split

In [ ]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2)

In [ ]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
331,12.980,19.35,84.52,514.0,0.09579,0.11250,0.071070,0.029500,0.1761,0.06540,...,14.420,21.95,99.21,634.3,0.12880,0.32530,0.343900,0.09858,0.3596,0.09166
319,12.430,17.00,78.60,477.3,0.07557,0.03454,0.013420,0.016990,0.1472,0.05561,...,12.900,20.21,81.76,515.9,0.08409,0.04712,0.022370,0.02832,0.1901,0.05932
239,17.460,39.28,113.40,920.6,0.09812,0.12980,0.141700,0.088110,0.1809,0.05966,...,22.510,44.87,141.20,1408.0,0.13650,0.37350,0.324100,0.20660,0.2853,0.08496
360,12.540,18.07,79.42,491.9,0.07436,0.02650,0.001194,0.005449,0.1528,0.05185,...,13.720,20.98,86.82,585.7,0.09293,0.04327,0.003581,0.01635,0.2233,0.05521
259,15.530,33.56,103.70,744.9,0.10630,0.16390,0.175100,0.083990,0.2091,0.06650,...,18.490,49.54,126.30,1035.0,0.18830,0.55640,0.570300,0.20140,0.3512,0.12040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332,11.220,19.86,71.94,387.3,0.10540,0.06779,0.005006,0.007583,0.1940,0.06028,...,11.980,25.78,76.91,436.1,0.14240,0.09669,0.013350,0.02022,0.3292,0.06522
46,8.196,16.84,51.71,201.9,0.08600,0.05943,0.015880,0.005917,0.1769,0.06503,...,8.964,21.96,57.26,242.2,0.12970,0.13570,0.068800,0.02564,0.3105,0.07409
407,12.850,21.37,82.63,514.5,0.07551,0.08316,0.061260,0.018670,0.1580,0.06114,...,14.400,27.01,91.63,645.8,0.09402,0.19360,0.183800,0.05601,0.2488,0.08151
23,21.160,23.04,137.20,1404.0,0.09428,0.10220,0.109700,0.086320,0.1769,0.05278,...,29.170,35.59,188.00,2615.0,0.14010,0.26000,0.315500,0.20090,0.2822,0.07526
564,21.560,22.39,142.00,1479.0,0.11100,0.11590,0.243900,0.138900,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.410700,0.22160,0.2060,0.07115

Scaling the X_train,X_test using StandardScaler

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-3.43253360e-01, -3.78628468e-03, -3.25417809e-01, ...,
        -2.63567387e-01,  1.06713130e+00,  3.88995952e-01],
       [-5.01452257e-01, -5.52361473e-01, -5.72814956e-01, ...,
        -1.33213030e+00, -1.59488950e+00, -1.36961397e+00],
       [ 9.45348563e-01,  4.64859819e+00,  8.81479084e-01, ...,
         1.37927585e+00, -9.97604138e-02,  2.46580901e-02],
       ...,
       [-3.80645827e-01,  4.67754941e-01, -4.04401019e-01, ...,
        -9.11001534e-01, -6.72997931e-01, -1.62948720e-01],
       [ 2.00959569e+00,  8.57593480e-01,  1.87608248e+00, ...,
         1.29258629e+00, -1.48446340e-01, -5.02816128e-01],
       [ 2.12464943e+00,  7.05859917e-01,  2.07667476e+00, ...,
         1.60740628e+00, -1.34517781e+00, -7.26312937e-01]])

In [ ]:
y_train

331    B
319    B
239    M
360    B
259    M
      ..
332    B
46     B
407    B
23     M
564    M
Name: diagnosis, Length: 455, dtype: object

Label Encoding to transform y into binary values

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1])

To convert numpy arrays to pytorch tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 2.9304910900815213
Epoch: 2, Loss: 2.7718109117609626
Epoch: 3, Loss: 2.6117707620821813
Epoch: 4, Loss: 2.4436067832474806
Epoch: 5, Loss: 2.2674187418327723
Epoch: 6, Loss: 2.0932301048418624
Epoch: 7, Loss: 1.9221851782280737
Epoch: 8, Loss: 1.7596624231365414
Epoch: 9, Loss: 1.6072819788047161
Epoch: 10, Loss: 1.4647123286958814
Epoch: 11, Loss: 1.3330409975512356
Epoch: 12, Loss: 1.214835320056978
Epoch: 13, Loss: 1.1139094644929686
Epoch: 14, Loss: 1.0307410349083137
Epoch: 15, Loss: 0.9646064781785699
Epoch: 16, Loss: 0.9135628127209322
Epoch: 17, Loss: 0.8748471459258381
Epoch: 18, Loss: 0.8455122117826281
Epoch: 19, Loss: 0.8229683612101686
Epoch: 20, Loss: 0.8052306491980397
Epoch: 21, Loss: 0.7909047671117564
Epoch: 22, Loss: 0.7790539217773348
Epoch: 23, Loss: 0.7690555352734199
Epoch: 24, Loss: 0.760490206468213
Epoch: 25, Loss: 0.7530668184170686

In [ ]:
model.bias

tensor([-0.1785], dtype=torch.float64, requires_grad=True)

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6551246643066406