<a href="https://colab.research.google.com/github/Sizanur-siam/Machine-Learning-projects-/blob/main/All_in_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('/content/teen_e_safety_dataset.csv')

In [4]:
df.head()

,Timestamp,Device_Type,Malware_Detection,Phishing_Attempts,Social_Media_Usage,VPN_Usage,Cyberbullying_Reports,Parental_Control_Alerts,Firewall_Logs,Login_Attempts,...,Website_Visits,Peer_Interactions,Risky_Website_Visits,Cloud_Service_Usage,Unencrypted_Traffic,Ad_Clicks,Insecure_Login_Attempts,E_Safety_Awareness_Score,Malware_Exposure_Risk,Cybersecurity_Behavior_Category
0,2017-01-01 00:00:00,Mobile,0,0,Low,0,0,0,4,2,...,2,Low,0,0,0,0,0,Moderate,1,Safe
1,2017-01-01 01:00:00,Desktop,0,0,Low,0,0,0,4,2,...,4,Low,0,0,0,0,0,Moderate,0,Neutral
2,2017-01-01 02:00:00,Laptop,0,0,Low,0,0,0,0,1,...,2,Low,0,0,0,0,0,Moderate,0,Neutral
3,2017-01-01 03:00:00,Mobile,0,0,Low,0,0,1,2,3,...,3,Low,0,0,0,1,1,Moderate,0,Safe
4,2017-01-01 04:00:00,Mobile,0,1,Medium,0,0,0,2,3,...,3,Low,0,0,0,0,0,Moderate,0,Risky

In [5]:
df.shape

(67921, 30)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67921 entries, 0 to 67920
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Timestamp                        67921 non-null  object
 1   Device_Type                      67921 non-null  object
 2   Malware_Detection                67921 non-null  int64
 3   Phishing_Attempts                67921 non-null  int64
 4   Social_Media_Usage               67921 non-null  object
 5   VPN_Usage                        67921 non-null  int64
 6   Cyberbullying_Reports            67921 non-null  int64
 7   Parental_Control_Alerts          67921 non-null  int64
 8   Firewall_Logs                    67921 non-null  int64
 9   Login_Attempts                   67921 non-null  int64
 10  Download_Risk                    67921 non-null  int64
 11  Password_Strength                67921 non-null  object
 12  Data_Breach_Notifications        67921 non-null  int64
 13  Online_Purchase_Risk             67921 non-null  int64
 14  Education_Content_Usage          20326 non-null  object
 15  Age_Group                        67921 non-null  object
 16  Geolocation                      67921 non-null  object
 17  Public_Network_Usage             67921 non-null  int64
 18  Network_Type                     67921 non-null  object
 19  Hours_Online                     67921 non-null  float64
 20  Website_Visits                   67921 non-null  int64
 21  Peer_Interactions                67921 non-null  object
 22  Risky_Website_Visits             67921 non-null  int64
 23  Cloud_Service_Usage              67921 non-null  int64
 24  Unencrypted_Traffic              67921 non-null  int64
 25  Ad_Clicks                        67921 non-null  int64
 26  Insecure_Login_Attempts          67921 non-null  int64
 27  E_Safety_Awareness_Score         67921 non-null  object
 28  Malware_Exposure_Risk            67921 non-null  int64
 29  Cybersecurity_Behavior_Category  67921 non-null  object
dtypes: float64(1), int64(18), object(11)
memory usage: 15.5+ MB

In [7]:
df.describe()

,Malware_Detection,Phishing_Attempts,VPN_Usage,Cyberbullying_Reports,Parental_Control_Alerts,Firewall_Logs,Login_Attempts,Download_Risk,Data_Breach_Notifications,Online_Purchase_Risk,Public_Network_Usage,Hours_Online,Website_Visits,Risky_Website_Visits,Cloud_Service_Usage,Unencrypted_Traffic,Ad_Clicks,Insecure_Login_Attempts,Malware_Exposure_Risk
count,67921.000000,67921.000000,67921.000000,67921.000000,67921.000000,67921.00000,67921.000000,67921.000000,67921.000000,67921.000000,67921.000000,67921.000000,67921.000000,67921.000000,67921.000000,67921.000000,67921.000000,67921.000000,67921.000000
mean,0.048468,0.302057,0.148849,0.019582,0.099086,2.00265,1.749753,0.101014,0.010232,0.051604,0.199894,1.990720,2.996054,0.099454,0.098673,0.050735,0.199217,0.100278,0.299657
std,0.214755,0.551460,0.355943,0.138558,0.298779,1.40747,1.134658,0.301350,0.100638,0.221228,0.399923,2.004330,1.734960,0.299273,0.298225,0.219459,0.399414,0.300373,0.458111
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000021,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,0.000000,0.000000,0.000000,0.000000,0.572169,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,2.00000,1.000000,0.000000,0.000000,0.000000,0.000000,1.383695,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,0.000000,0.000000,0.000000,3.00000,2.000000,0.000000,0.000000,0.000000,0.000000,2.752655,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,1.000000,5.000000,1.000000,1.000000,1.000000,11.00000,5.000000,1.000000,1.000000,1.000000,1.000000,22.659108,13.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [9]:
df.isnull().sum()

Timestamp                              0
Device_Type                            0
Malware_Detection                      0
Phishing_Attempts                      0
Social_Media_Usage                     0
VPN_Usage                              0
Cyberbullying_Reports                  0
Parental_Control_Alerts                0
Firewall_Logs                          0
Login_Attempts                         0
Download_Risk                          0
Password_Strength                      0
Data_Breach_Notifications              0
Online_Purchase_Risk                   0
Education_Content_Usage            47595
Age_Group                              0
Geolocation                            0
Public_Network_Usage                   0
Network_Type                           0
Hours_Online                           0
Website_Visits                         0
Peer_Interactions                      0
Risky_Website_Visits                   0
Cloud_Service_Usage                    0
Unencrypted_Traffic                    0
Ad_Clicks                              0
Insecure_Login_Attempts                0
E_Safety_Awareness_Score               0
Malware_Exposure_Risk                  0
Cybersecurity_Behavior_Category        0
dtype: int64

In [10]:
df["Education_Content_Usage"]=df['Education_Content_Usage'].fillna('None')

Feature Engineeringt

In [11]:
df.drop('Timestamp', axis=1, inplace=True)

data scalying

In [12]:
df.shape

(67921, 29)

In [13]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [15]:
numerical_columns = [col for col in df.columns if df[col].dtype in ['int64', 'float64']]
scaler = StandardScaler()
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

In [14]:
df

,Device_Type,Malware_Detection,Phishing_Attempts,Social_Media_Usage,VPN_Usage,Cyberbullying_Reports,Parental_Control_Alerts,Firewall_Logs,Login_Attempts,Download_Risk,...,Website_Visits,Peer_Interactions,Risky_Website_Visits,Cloud_Service_Usage,Unencrypted_Traffic,Ad_Clicks,Insecure_Login_Attempts,E_Safety_Awareness_Score,Malware_Exposure_Risk,Cybersecurity_Behavior_Category
0,Mobile,0,0,Low,0,0,0,4,2,0,...,2,Low,0,0,0,0,0,Moderate,1,Safe
1,Desktop,0,0,Low,0,0,0,4,2,0,...,4,Low,0,0,0,0,0,Moderate,0,Neutral
2,Laptop,0,0,Low,0,0,0,0,1,0,...,2,Low,0,0,0,0,0,Moderate,0,Neutral
3,Mobile,0,0,Low,0,0,1,2,3,0,...,3,Low,0,0,0,1,1,Moderate,0,Safe
4,Mobile,0,1,Medium,0,0,0,2,3,0,...,3,Low,0,0,0,0,0,Moderate,0,Risky
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67916,Tablet,0,0,Low,0,0,0,5,1,1,...,4,Low,0,0,0,0,0,Moderate,0,Neutral
67917,Mobile,0,0,Low,0,0,1,2,1,1,...,5,Low,0,0,0,0,0,High,0,Safe
67918,Mobile,0,0,Low,0,0,0,0,1,0,...,1,Low,0,0,0,0,0,Low,0,Safe
67919,Laptop,0,0,Low,0,0,1,0,1,0,...,3,Low,0,0,0,0,0,Low,0,Safe
67920,Desktop,1,1,Medium,0,0,0,2,2,0,...,5,Low,0,0,0,0,1,Low,0,Safe

One-Hot-Encoder

  Use scikit-learn

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
X=df.drop("Cybersecurity_Behavior_Category",axis=1)
y=df['Cybersecurity_Behavior_Category']
X.shape,y.shape

((67921, 28), (67921,))

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train.shape,X_test.shape,y_test.shape,y_test.shape

((54336, 28), (13585, 28), (13585,), (13585,))

In [19]:
import numpy as np
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder,FunctionTransformer

In [20]:
from sklearn.compose import ColumnTransformer

In [21]:
col_transformer=ColumnTransformer(transformers=[('ordtr',OrdinalEncoder(categories=[['Low', 'Medium', 'High'],['Weak', 'Moderate', 'Strong'],['Low', 'None', 'High'],['Low', 'Medium', 'High'],['Low', 'Moderate', 'High'],]),['Social_Media_Usage','Password_Strength',
       'Education_Content_Usage','Peer_Interactions', 'E_Safety_Awareness_Score',]),
('onetr',OneHotEncoder(drop='first'),['Device_Type','Geolocation', 'Age_Group', 'Network_Type']),
  ],remainder='passthrough')

In [22]:
X_train_new=col_transformer.fit_transform(X_train)

In [23]:
col_transformer.transform(X_test)

array([[ 0.        ,  0.        ,  1.        , ..., -0.49877585,
        -0.3338484 , -0.65411901],
       [ 1.        ,  0.        ,  1.        , ..., -0.49877585,
        -0.3338484 , -0.65411901],
       [ 0.        ,  1.        ,  1.        , ..., -0.49877585,
        -0.3338484 ,  1.52877379],
       ...,
       [ 1.        ,  2.        ,  1.        , ..., -0.49877585,
        -0.3338484 , -0.65411901],
       [ 0.        ,  0.        ,  1.        , ..., -0.49877585,
        -0.3338484 , -0.65411901],
       [ 2.        ,  0.        ,  1.        , ..., -0.49877585,
        -0.3338484 ,  1.52877379]])

In [24]:
col_transformer.get_feature_names_out()

array(['ordtr__Social_Media_Usage', 'ordtr__Password_Strength',
       'ordtr__Education_Content_Usage', 'ordtr__Peer_Interactions',
       'ordtr__E_Safety_Awareness_Score', 'onetr__Device_Type_Laptop',
       'onetr__Device_Type_Mobile', 'onetr__Device_Type_Tablet',
       'onetr__Geolocation_EU', 'onetr__Geolocation_OTHER',
       'onetr__Geolocation_US', 'onetr__Age_Group_17-19',
       'onetr__Age_Group_<13', 'onetr__Network_Type_Ethernet',
       'onetr__Network_Type_Other', 'onetr__Network_Type_WiFi',
       'remainder__Malware_Detection', 'remainder__Phishing_Attempts',
       'remainder__VPN_Usage', 'remainder__Cyberbullying_Reports',
       'remainder__Parental_Control_Alerts', 'remainder__Firewall_Logs',
       'remainder__Login_Attempts', 'remainder__Download_Risk',
       'remainder__Data_Breach_Notifications',
       'remainder__Online_Purchase_Risk',
       'remainder__Public_Network_Usage', 'remainder__Hours_Online',
       'remainder__Website_Visits', 'remainder__Risky_Website_Visits',
       'remainder__Cloud_Service_Usage', 'remainder__Unencrypted_Traffic',
       'remainder__Ad_Clicks', 'remainder__Insecure_Login_Attempts',
       'remainder__Malware_Exposure_Risk'], dtype=object)

In [25]:
from sklearn.preprocessing import LabelEncoder
target=LabelEncoder()
y_train=target.fit_transform(y_train)
y_test=target.transform(y_test)

In [26]:
target.classes_

array(['Neutral', 'Risky', 'Safe'], dtype=object)

In [45]:
y_train.shape

(54336,)

In [28]:
X_train_new

array([[ 0.        ,  0.        ,  2.        , ..., -0.49877585,
        -0.3338484 ,  1.52877379],
       [ 0.        ,  0.        ,  1.        , ..., -0.49877585,
        -0.3338484 , -0.65411901],
       [ 0.        ,  1.        ,  1.        , ...,  2.00490862,
        -0.3338484 ,  1.52877379],
       ...,
       [ 1.        ,  2.        ,  1.        , ..., -0.49877585,
        -0.3338484 , -0.65411901],
       [ 2.        ,  0.        ,  0.        , ..., -0.49877585,
         2.99537156,  1.52877379],
       [ 0.        ,  2.        ,  1.        , ..., -0.49877585,
        -0.3338484 , -0.65411901]])

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import r2_score

In [30]:
lr=LogisticRegression()
lr.fit(X_train_new,y_train)

LogisticRegression()

In [31]:
y_pred=lr.predict(col_transformer.transform(X_test))

In [32]:
accuracy_score(y_test,y_pred)

0.6072138387927861

In [34]:
y_pred.shape

(13585,)

In [35]:
dtcol_transformer=ColumnTransformer(transformers=[('ordtr',OrdinalEncoder(categories=[['Low', 'Medium', 'High'],['Weak', 'Moderate', 'Strong'],['Low', 'None', 'High'],['Low', 'Medium', 'High'],['Low', 'Moderate', 'High'],]),['Social_Media_Usage','Password_Strength',
       'Education_Content_Usage','Peer_Interactions', 'E_Safety_Awareness_Score',]),
('onetr',OneHotEncoder(),['Device_Type','Geolocation', 'Age_Group', 'Network_Type']),
  ],remainder='passthrough')

In [37]:
dtcol_transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('ordtr',
                                 OrdinalEncoder(categories=[['Low', 'Medium',
                                                             'High'],
                                                            ['Weak', 'Moderate',
                                                             'Strong'],
                                                            ['Low', 'None',
                                                             'High'],
                                                            ['Low', 'Medium',
                                                             'High'],
                                                            ['Low', 'Moderate',
                                                             'High']]),
                                 ['Social_Media_Usage', 'Password_Strength',
                                  'Education_Content_Usage',
                                  'Peer_Interactions',
                                  'E_Safety_Awareness_Score']),
                                ('onetr', OneHotEncoder(),
                                 ['Device_Type', 'Geolocation', 'Age_Group',
                                  'Network_Type'])])

In [38]:
X_train_dt=dtcol_transformer.fit_transform(X_train)

In [40]:
X_train_dt.shape

(54336, 39)

In [42]:
X_test_dt=dtcol_transformer.transform(X_test)
X_test_dt.shape

(13585, 39)

In [43]:
from sklearn.tree import DecisionTreeClassifier

In [46]:
dtc=DecisionTreeClassifier()
dtc.fit(X_train_dt,y_train)

DecisionTreeClassifier()

In [49]:
y_pred_dt=dtc.predict(X_test_dt)
y_pred_dt.shape

(13585,)

In [50]:
accuracy_score(y_test,y_pred_dt)

0.45609127714390874

Pipleline