## Week 8 - 8.1

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
df = pd.read_csv("cricket_for_naive_bayes.csv")

In [18]:
df.head()

    OUTLOOK TEMPERATURE HUMIDITY  WINDY PLAY CRICKET
0     Rainy         Hot     High  False           No
1     Rainy         Hot     High   True           No
2  Overcast         Hot     High  False          Yes
3     Sunny        Mild     High  False          Yes
4     Sunny        Cool   Normal  False          Yes

convert the data into numberic by writing our own functions

In [19]:
def outlook(x):
    if x=='Rainy':
        return 0
    if x=='Overcast':
        return 1
    if x=='Sunny':
        return 2
    

def temperature(x):
    if x=='Hot':
        return 0
    if x=='Mild':
        return 1
    if x=='Cool':
        return 2
    

def humid(x):
    if x=='High':
        return 0
    if x=='Normal':
        return 1
    

def windy(x):
    if x==False:
        return 0
    if x==True:
        return 1
    

def target(x):
    if x=='No':
        return 0
    if x=='Yes':
        return 1

#### apply the above functions on the cols and store them into df

In [20]:
df['OUTLOOK'] = df['OUTLOOK'].apply(outlook)
df['TEMPERATURE'] = df['TEMPERATURE'].apply(temperature)
df['HUMIDITY'] = df['HUMIDITY'].apply(humid)
df['WINDY'] = df['WINDY'].apply(windy)
df['PLAY CRICKET'] = df['PLAY CRICKET'].apply(target)

In [22]:
df.head()

   OUTLOOK  TEMPERATURE  HUMIDITY  WINDY  PLAY CRICKET
0        0            0         0      0             0
1        0            0         0      1             0
2        1            0         0      0             1
3        2            1         0      0             1
4        2            2         1      0             1

In [25]:
x = df[['OUTLOOK','TEMPERATURE','HUMIDITY','WINDY']]
y = df['PLAY CRICKET']

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=10)

In [28]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [29]:
gnb.fit(x_train,y_train)

GaussianNB()

In [30]:
y_pred = gnb.predict(x_test)
y_pred

array([1, 1, 1, 1, 1], dtype=int64)

comparing actual response values (y_test) with predicted reponse values (y_pred)

In [33]:
from sklearn import metrics

score = metrics.accuracy_score(y_test,y_pred)
print("accuracy : ",score)

accuracy :  0.8

In [34]:
gnb.score(x_test,y_test)

0.8

#### Prediction on:
    Outlook -> Sunny
    Temperature -> Cool
    Humidity -> Normal
    Wind -> No

In [36]:
gnb.predict([[2,2,1,0]]) # 1 ---> play

C:\Users\MRUH\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

In [37]:
gnb.predict([[2,1,0,1]]) # 1 ---> play

C:\Users\MRUH\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

array([0], dtype=int64)