# Import Libraries

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Read the dataset

In [135]:
df = pd.read_csv("youTubeSearchListChattishgarh.csv",index_col=[0])

/home/shivshaurya/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3331: DtypeWarning: Columns (0,3,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [136]:
df.head()

,ContentId,title,viewCount,likeCount,dislikeCount,commentCount,favoriteCount,publishedAt,description,duration,tags
0,lBvknjH3MF0,Akash Chopra Hindi Commentary,1092,83,0,0,0,2021-05-05T10:04:48Z,Follow for more on Insta \n\nhttps://www.insta...,PT30S,"['Cricket', 'India', 'Commentary', 'Hindijokes..."
1,qlReo1HxJpE,THE LAUGH CLUB OPEN MIC VLOG 2,14702,749,3,19,0,2021-02-13T06:19:39Z,#STANDUPCOMEDY #COMEDY #LAUGHCLUB\n\nTHIS VIDE...,PT6M42S,[]
2,b0SnJGhuSFQ,FUNNY ROAST OF APPLE 🔥,10370,388,3,19,0,2021-02-04T01:34:45Z,#ROAST #APPLE #IPHONE #AIRPOD\n\nITS A MICRO -...,PT3M5S,"['Roast', 'Apple', 'iPhone', 'Airpod', 'Jokes'..."
3,nfBqb5ZEPys,Stand Up Comedy Homey B,1211,21,0,9,0,2020-12-12T10:35:18Z,Crowd work stand up comedy by HomeyB\n\nhttps:...,PT29S,"['Standupcomedy', 'Standup', 'Jokes', 'Haha', ..."
4,ZbOQhsNS87s,TIKTOK ZINDA HAI | NEW CLEAR FAMILY | FAMILY C...,32404,6003,23,344,0,2020-07-19T23:35:01Z,Link first episode EK THA TIKTOK -https://yout...,PT8M18S,"['TIKTOKROAST', 'TIKTOK', 'TIKTOKZINDAHAI', 'E..."

In [137]:
df.shape

(145233, 11)

# Check for null value count

In [138]:
df.isnull().sum()

ContentId            0
title                0
viewCount        36052
likeCount        36052
dislikeCount     36052
commentCount     36052
favoriteCount    36052
publishedAt      36052
description      39628
duration         36053
tags             36053
dtype: int64

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 145233 entries, 0 to 109180
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ContentId      145233 non-null  object
 1   title          145233 non-null  object
 2   viewCount      109181 non-null  object
 3   likeCount      109181 non-null  object
 4   dislikeCount   109181 non-null  object
 5   commentCount   109181 non-null  object
 6   favoriteCount  109181 non-null  object
 7   publishedAt    109181 non-null  object
 8   description    105605 non-null  object
 9   duration       109180 non-null  object
 10  tags           109180 non-null  object
dtypes: object(11)
memory usage: 13.3+ MB

# Converting Object dtype to strings

In [140]:
df['title'] = df['title'].convert_dtypes()
df['description'] = df['description'].convert_dtypes()
df['tags'] = df['tags'].convert_dtypes()

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 145233 entries, 0 to 109180
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ContentId      145233 non-null  object
 1   title          145233 non-null  string
 2   viewCount      109181 non-null  object
 3   likeCount      109181 non-null  object
 4   dislikeCount   109181 non-null  object
 5   commentCount   109181 non-null  object
 6   favoriteCount  109181 non-null  object
 7   publishedAt    109181 non-null  object
 8   description    105605 non-null  string
 9   duration       109180 non-null  object
 10  tags           109180 non-null  string
dtypes: object(8), string(3)
memory usage: 13.3+ MB

# Dropping Null Values

In [142]:
df = df.dropna()
df = df.reset_index(drop=True)

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105604 entries, 0 to 105603
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ContentId      105604 non-null  object
 1   title          105604 non-null  string
 2   viewCount      105604 non-null  object
 3   likeCount      105604 non-null  object
 4   dislikeCount   105604 non-null  object
 5   commentCount   105604 non-null  object
 6   favoriteCount  105604 non-null  object
 7   publishedAt    105604 non-null  object
 8   description    105604 non-null  string
 9   duration       105604 non-null  object
 10  tags           105604 non-null  string
dtypes: object(8), string(3)
memory usage: 8.9+ MB

In [144]:
df.isnull().sum()

ContentId        0
title            0
viewCount        0
likeCount        0
dislikeCount     0
commentCount     0
favoriteCount    0
publishedAt      0
description      0
duration         0
tags             0
dtype: int64

# Removing tags, special characters and digits, convert to lower case

In [145]:
import re
def pre_process(text):
    
    # lowercase
    text=text.lower()
    
    #remove tags
    text=re.sub("","",text)
    
    # remove special characters and digits
    text=re.sub("(\\d|\\W)+"," ",text)
    
    return text

df['text'] = df['title'] + df['description'] + df['tags']
df['text'] = df['text'].apply(lambda x:pre_process(x))

#show the second 'text' just for fun
df['text'][2]

'funny roast of apple roast apple iphone airpod its a micro roast this video was made for pure entertainment purpose follow me here instagram https www instagram com homeybvibe fb https www facebook com homeybvibe twitter https twitter com homeybvibe roast apple iphone airpod jokes funny indian comedy roasting roastvideoindia standup comedy '

In [146]:
df.head()

,ContentId,title,viewCount,likeCount,dislikeCount,commentCount,favoriteCount,publishedAt,description,duration,tags,text
0,lBvknjH3MF0,Akash Chopra Hindi Commentary,1092,83,0,0,0,2021-05-05T10:04:48Z,Follow for more on Insta https://www.instagr...,PT30S,"['Cricket', 'India', 'Commentary', 'Hindijokes...",akash chopra hindi commentaryfollow for more o...
1,qlReo1HxJpE,THE LAUGH CLUB OPEN MIC VLOG 2,14702,749,3,19,0,2021-02-13T06:19:39Z,#STANDUPCOMEDY #COMEDY #LAUGHCLUB THIS VIDEO ...,PT6M42S,[],the laugh club open mic vlog standupcomedy com...
2,b0SnJGhuSFQ,FUNNY ROAST OF APPLE 🔥,10370,388,3,19,0,2021-02-04T01:34:45Z,#ROAST #APPLE #IPHONE #AIRPOD ITS A MICRO - R...,PT3M5S,"['Roast', 'Apple', 'iPhone', 'Airpod', 'Jokes'...",funny roast of apple roast apple iphone airpod...
3,nfBqb5ZEPys,Stand Up Comedy Homey B,1211,21,0,9,0,2020-12-12T10:35:18Z,Crowd work stand up comedy by HomeyB https://...,PT29S,"['Standupcomedy', 'Standup', 'Jokes', 'Haha', ...",stand up comedy homey bcrowd work stand up com...
4,ZbOQhsNS87s,TIKTOK ZINDA HAI | NEW CLEAR FAMILY | FAMILY C...,32404,6003,23,344,0,2020-07-19T23:35:01Z,Link first episode EK THA TIKTOK -https://yout...,PT8M18S,"['TIKTOKROAST', 'TIKTOK', 'TIKTOKZINDAHAI', 'E...",tiktok zinda hai new clear family family comed...

# Lemmatization and Removal of Stopwords

In [147]:
import re
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
import string
from nltk.tokenize import word_tokenize
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
processed_all_documents = list()

for desc in df['text']:
    word_tokens = word_tokenize(desc) 
    
    filtered_sentence = [] 

    # Removing Stopwords
    for w in word_tokens: 
        if w not in stop_words: 
            filtered_sentence.append(w) 
    
    # Lemmetization
    lemma_word = []
    wordnet_lemmatizer = WordNetLemmatizer()
    for w in filtered_sentence:
        word1 = wordnet_lemmatizer.lemmatize(w, pos = "n")
        word2 = wordnet_lemmatizer.lemmatize(word1, pos = "v")
        word3 = wordnet_lemmatizer.lemmatize(word2, pos = ("a"))
        lemma_word.append(word3)
    words = ' '.join(lemma_word)
    processed_all_documents.append(words)
df['Processed_text'] = processed_all_documents
df['Word_Count'] = [len(desc.split(' ')) for desc in df['Processed_text']]

wordCount_after = df['Word_Count'].sum()
print("Total Words after processing: ", wordCount_after)
print("Max word count of a Document: ", df['Word_Count'].max())
print("Mean word count of Documents: ", df['Word_Count'].mean())

[nltk_data] Downloading package punkt to
[nltk_data]     /home/shivshaurya/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/shivshaurya/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/shivshaurya/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Total Words after processing:  21876070
Max word count of a Document:  1921
Mean word count of Documents:  207.15190712473012

In [148]:
df.head()

,ContentId,title,viewCount,likeCount,dislikeCount,commentCount,favoriteCount,publishedAt,description,duration,tags,text,Processed_text,Word_Count
0,lBvknjH3MF0,Akash Chopra Hindi Commentary,1092,83,0,0,0,2021-05-05T10:04:48Z,Follow for more on Insta https://www.instagr...,PT30S,"['Cricket', 'India', 'Commentary', 'Hindijokes...",akash chopra hindi commentaryfollow for more o...,akash chopra hindi commentaryfollow insta http...,16
1,qlReo1HxJpE,THE LAUGH CLUB OPEN MIC VLOG 2,14702,749,3,19,0,2021-02-13T06:19:39Z,#STANDUPCOMEDY #COMEDY #LAUGHCLUB THIS VIDEO ...,PT6M42S,[],the laugh club open mic vlog standupcomedy com...,laugh club open mic vlog standupcomedy comedy ...,67
2,b0SnJGhuSFQ,FUNNY ROAST OF APPLE 🔥,10370,388,3,19,0,2021-02-04T01:34:45Z,#ROAST #APPLE #IPHONE #AIRPOD ITS A MICRO - R...,PT3M5S,"['Roast', 'Apple', 'iPhone', 'Airpod', 'Jokes'...",funny roast of apple roast apple iphone airpod...,funny roast apple roast apple iphone airpod mi...,44
3,nfBqb5ZEPys,Stand Up Comedy Homey B,1211,21,0,9,0,2020-12-12T10:35:18Z,Crowd work stand up comedy by HomeyB https://...,PT29S,"['Standupcomedy', 'Standup', 'Jokes', 'Haha', ...",stand up comedy homey bcrowd work stand up com...,stand comedy homey bcrowd work stand comedy ho...,33
4,ZbOQhsNS87s,TIKTOK ZINDA HAI | NEW CLEAR FAMILY | FAMILY C...,32404,6003,23,344,0,2020-07-19T23:35:01Z,Link first episode EK THA TIKTOK -https://yout...,PT8M18S,"['TIKTOKROAST', 'TIKTOK', 'TIKTOKZINDAHAI', 'E...",tiktok zinda hai new clear family family comed...,tiktok zinda hai new clear family family comed...,198

# Create a vocabulary of words, 
Ignore words that appear in 85% of documents, 
Eliminate stop words

In [149]:
from sklearn.feature_extraction.text import CountVectorizer
import re

def get_stop_words(stop_file_path):
    """load stop words """
    
    with open(stop_file_path, 'r', encoding="utf-8") as f:
        stopwords = f.readlines()
        stop_set = set(m.strip() for m in stopwords)
        return frozenset(stop_set)

#load a set of stop words
stopwords=get_stop_words("stopwords.txt")

#get the text column 
docs=df['Processed_text'].tolist()

#create a vocabulary of words, 
#ignore words that appear in 85% of documents, 
#eliminate stop words
cv=CountVectorizer(max_df=0.85,stop_words=stopwords)
word_count_vector=cv.fit_transform(docs)

/home/shivshaurya/anaconda3/lib/python3.8/site-packages/sklearn/feature_extraction/text.py:382: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['come', 'vis', 'viser', 'visest'] not in stop_words.
  warnings.warn('Your stop_words may be inconsistent with '

In [150]:
word_count_vector.shape

(105604, 233158)

In [151]:
list(cv.vocabulary_.keys())[:10]

['akash',
 'chopra',
 'hindi',
 'commentaryfollow',
 'insta',
 'www',
 'instagram',
 'homeybvibe',
 'cricket',
 'india']

In [152]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True)
tfidf_transformer.fit(word_count_vector)

TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)

In [153]:
# you only needs to do this once, this is a mapping of index to 
feature_names=cv.get_feature_names()

In [154]:
feature_names

['__',
 '___',
 '____',
 '_____',
 '______',
 '_______',
 '________',
 '_________',
 '__________',
 '___________',
 '____________',
 '_____________',
 '______________',
 '_______________',
 '________________',
 '_________________',
 '__________________',
 '___________________',
 '____________________',
 '_____________________',
 '______________________',
 '_______________________',
 '________________________',
 '_________________________',
 '__________________________',
 '___________________________',
 '____________________________',
 '_____________________________',
 '______________________________',
 '_______________________________',
 '________________________________',
 '_________________________________',
 '__________________________________',
 '___________________________________',
 '____________________________________',
 '_____________________________________',
 '______________________________________',
 '_______________________________________',
 '________________________________________',
 '_________________________________________',
 '__________________________________________',
 '___________________________________________',
 '____________________________________________',
 '_____________________________________________',
 '______________________________________________',
 '_______________________________________________',
 '________________________________________________',
 '_________________________________________________',
 '__________________________________________________',
 '___________________________________________________',
 '____________________________________________________',
 '_____________________________________________________',
 '______________________________________________________',
 '_______________________________________________________',
 '________________________________________________________',
 '_________________________________________________________',
 '__________________________________________________________',
 '___________________________________________________________',
 '____________________________________________________________',
 '_____________________________________________________________',
 '______________________________________________________________',
 '_______________________________________________________________',
 '________________________________________________________________',
 '_________________________________________________________________',
 '__________________________________________________________________',
 '___________________________________________________________________',
 '____________________________________________________________________',
 '_____________________________________________________________________',
 '______________________________________________________________________',
 '_______________________________________________________________________',
 '________________________________________________________________________',
 '__________________________________________________________________________',
 '___________________________________________________________________________',
 '_____________________________________________________________________________',
 '______________________________________________________________________________',
 '____________________________________________________________________________________',
 '_____________________________________________________________________________________',
 '_______________________________________________________________________________________',
 '________________________________________________________________________________________',
 '_________________________________________________________________________________________',
 '____________________________________________________________________________________________',
 '_____________________________________________________________________________________________',
 '______________________________________________________________________________________________',
 '_______________________________________________________________________________________________',
 '___________________________________________________________________________________________________________________________________________',
 '_________________________________________________________________________________________________________________________________________________________________________________________________',
 '_____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________',
 '_________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________',
 '________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________',
 '_________________________________________________disclaimer_______________',
 '________________________________________________original',
 '______________________________________________l',
 '______________________________________________p',
 '__________________________________________keywords',
 '__________________________________________please',
 '______________________keep',
 '______________________surendra____nagvanshi',
 '_____________________keep',
 '____________keep_____supporting__',
 '__________like',
 '__________thanks',
 '_________love',
 '_________thanks',
 '________thanks',
 '_______pm',
 '_______thank__you__so___much_',
 '______by',
 '______guru',
 '______no',
 '______share',
 '______subscribe',
 '_____aam',
 '_____comment',
 '_____share',
 '_____stutas',
 '_____tag____',
 '____djvicky_belgaum_video',
 '____full',
 '___https',
 '___keep',
 '___kg_productions___',
 '___vfx',
 '__abhi',
 '__aman',
 '__arabic',
 '__b',
 '__blob',
 '__debolinaa',
 '__dhaval',
 '__eg_wapj',
 '__extract_me___',
 '__guri',
 '__how_to_use_green_screen_editing_tik_tok_video_ma_editing_kara',
 '__https',
 '__i',
 '__lets_do_it___',
 '__lover',
 '__manish',
 '__mitchikichi',
 '__mujtaba',
 '__new_haryanvi_l_song',
 '__official',
 '__oo',
 '__oxvm',
 '__prateekhh__',
 '__prateekhh___',
 '__priyanka',
 '__remix',
 '__shub',
 '__shubhamhere__',
 '__stunts',
 '__sty',
 '__supporting',
 '__supporting___',
 '__video',
 '__water',
 '__whatsapp',
 '__ya',
 '__ye_ham_hamare_car_hai_ringtone',
 '_a',
 '_a_to_z_aadiwasi_gaane',
 '_aagman_sohala_',
 '_aberration',
 '_above_us_',
 '_ace',
 '_adyogi_brand',
 '_adysq_eq',
 '_aesthetic_video_',
 '_aixq',
 '_akhilesh_unni',
 '_alaya_',
 '_alaya_f',
 '_album_',
 '_aledwq',
 '_alesia',
 '_alight_motion',
 '_all',
 '_alone',
 '_aman_jaji',
 '_aman_jaji_',
 '_ani',
 '_apna',
 '_apr',
 '_aqj',
 '_archana_padhi_',
 '_ards_gaming',
 '_arijit_singh_',
 '_article',
 '_aseema_panda_',
 '_aspire',
 '_audio',
 '_august',
 '_august_full_screen_status',
 '_august_independence_status',
 '_august_remix_song',
 '_august_status',
 '_august_status_song',
 '_august_status_video',
 '_august_whatsapp_status',
 '_augustindependence',
 '_augustvideo',
 '_auto_mall',
 '_av_',
 '_awnbr',
 '_b',
 '_back_to_the_grind',
 '_baja_re_baja_tamoko_baja',
 '_bamcef_adhiveshanbahujan',
 '_bamcef_अध',
 '_ban_apps_list',
 '_barati',
 '_bass_boosted_i_dj_parasar_netam',
 '_batla',
 '_bc',
 '_beautiful_girl_dance_green_screen_effects_vfx_effects_green_background_danc',
 '_beauty',
 '_before',
 '_best_',
 '_best_bangla_funny_video',
 '_best_status',
 '_best_whatsapp_status',
 '_beta_v',
 '_bhavin',
 '_bird_machine_',
 '_biswajit_',
 '_bk',
 '_black_screen',
 '_black_screen_',
 '_black_screen_status',
 '_black_screen_status_alone',
 '_black_screen_status_avee_player',
 '_black_screen_status_english',
 '_black_screen_status_kaise_banaye',
 '_black_screen_whatsapp_status_arijjit_singh',
 '_black_screen_whatsapp_status_editing',
 '_black_screen_whatsapp_status_english',
 '_bollywood_movies_list_',
 '_bollywood_upcoming_movies_list_',
 '_boney',
 '_boys',
 '_bra',
 '_brycqjtifw',
 '_build',
 '_bus_mod_',
 '_button_probelm',
 '_bwbuky',
 '_by',
 '_c',
 '_carol',
 '_cegac_',
 '_cene',
 '_cf',
 '_cg',
 '_cg_bhakti_mix_',
 '_cg_dance_mix_',
 '_cg_dance_remix_',
 '_cg_style_remix_',
 '_cg_tapori_mix_',
 '_channel_',
 '_chidiya',
 '_chinmayanand',
 '_chjmv',
 '_chroma_key',
 '_ck',
 '_ckz',
 '_cmte',
 '_coca',
 '_colourful_lights',
 '_coming',
 '_coming_soon',
 '_coolpro',
 '_corona',
 '_couple',
 '_cphiwpqbqo',
 '_creen',
 '_crunch',
 '_crush_black_screen_status',
 '_cut_off_',
 '_cxosygfnog',
 '_d',
 '_da',
 '_darpan_shah',
 '_days',
 '_deep',
 '_deepika_padukone',
 '_dekh_lena',
 '_dekha_teri_photo',
 '_developer',
 '_dexkplqaowlaohnrryv',
 '_di',
 '_dil_banjara_',
 '_dj',
 '_dj_gulshan_in_the_mix__marathi_dance_mix__',
 '_dj_mahesh_and_shaile',
 '_dj_nesh',
 '_dj_parasar_netam',
 '_dj_remix',
 '_dj_samarth',
 '_dj_sandesh_',
 '_djad',
 '_dl',
 '_documentary',
 '_dog',
 '_dogs_farm_rescue',
 '_dsp',
 '_e',
 '_e_g',
 '_edm_version_',
 '_ef',
 '_elg',
 '_elxnauneec',
 '_emoji_whatsapp_status_',
 '_emote',
 '_encoding',
 '_enigmatic_vivacity_',
 '_eso',
 '_euro',
 '_fat_loss_workouts',
 '_fe',
 '_feather',
 '_feb_',
 '_fewl',
 '_ffktpjc',
 '_filhaal',
 '_first',
 '_fish_hunter',
 '_fix',
 '_fmwebp_ql',
 '_follow',
 '_fom',
 '_football_team',
 '_fot',
 '_free_download',
 '_free_like_on_tiktok',
 '_free_stock_footage_',
 '_ftej',
 '_full_hd_',
 '_full_music_video_',
 '_full_screen',
 '_full_screen_status_video_',
 '_full_screen_status_video_song_',
 '_full_screen_whatsapp_status',
 '_full_screen_whatsapp_status_',
 '_funky',
 '_funny_photo',
 '_funny_video',
 '_fuzby',
 '_g',
 '_g_',
 '_gaj',
 '_gaj_ka_daman_',
 '_game',
 '_gaming',
 '_gcvwlf',
 '_gdh',
 '_gh',
 '_girl_green_screen_vfx_video',
 '_girl_vlogs',
 '_git',
 '_gmc_pla',
 '_go_down_after_spirited_display_against_uruguay_under_',
 '_godfather_',
 '_good_newwz_',
 '_green',
 '_green_screen_',
 '_green_screen_imovie_green_screen_',
 '_green_screen_status_',
 '_guru_randhawa_',
 '_guru_randhawa_f_jay_sean__larissa_bonesi',
 '_gzgq',
 '_h',
 '_hacker_playz',
 '_hand_pump',
 '_haryanvi_apna_system',
 '_hbkecg',
 '_hd',
 '_hd_',
 '_headlight_modication',
 '_headlights',
 '_headshot',
 '_headshot_tips_and_tricks_for_headshot',
 '_heartbreaker',
 '_hell',
 '_hello_koun_',
 '_here',
 '_himesh_reshamya',
 '_hindi_',
 '_hits_black_screen_status_video',
 '_homerevise_',
 '_horror_movie_soundtrack',
 '_horror_song_status',
 '_horses',
 '_hr',
 '_https',
 '_human_sagar_',
 '_humane_sagar_',
 '_hv',
 '_i',
 '_iadllwjmic',
 '_ibci',
 '_idea',
 '_idv',
 '_iekacyro',
 '_iggz',
 '_ij',
 '_ildhtqgxxg',
 '_imovie',
 '_imun',
 '_inches_ring_light_unboxing',
 '_inkprint_solutions',
 '_inkprint_solutions_',
 '_int',
 '_investigations',
 '_iqjee',
 '_isha_sharma_',
 '_ishq',
 '_itz',
 '_ix',
 '_ixbzy',
 '_ja',
 '_janapada_dj_song_dj_samarth',
 '_janmashtami',
 '_jawaani_jaaneman_',
 '_jbl',
 '_jcb_ashoka_leyland_आयशर',
 '_jex',
 '_jkimlzm',
 '_jrdw',
 '_jrs',
 '_jswi',
 '_jul',
 '_jy',
 '_jyhk_d',
 '_jyotica',
 '_k',
 '_k_p_t_song_tv_app',
 '_ka',
 '_kaabil_song_download',
 '_kala_dulha_ban_gya_',
 '_kamini',
 '_kareena_k',
 '_kashish_',
 '_keep',
 '_khqt',
 '_kills',
 '_kinemaster_color_background_video_',
 '_kishore',
 '_kiss',
 '_kitten',
 '_ko_karaar_aaya_status_full_screen',
 '_kop',
 '_kr',
 '_krishna_janmastami_special',
 '_krity',
 '_krqmzc',
 '_kumaar',
 '_kumaarrula_ke_gaya_ishq_',
 '_l',
 '_ladha_swadhyay',
 '_latest_',
 '_latest_today_news',
 '_legend__abhi',
 '_li',
 '_life',
 '_lighsun',
 '_like',
 '_lkfy',
 '_lkfyfcrvku',
 '_lockdown',
 '_lover',
 '_lrkd',
 '_lsrxnrps',
 '_lt_tripod',
 '_lucknow',
 '_luke',
 '_luxury_premium_car_holi_offer',
 '_lxfbpqkb',
 '_ly',
 '_lycmnh',
 '_lymvyduh',
 '_lyyhttps',
 '_m',
 '_manish',
 '_manj_m',
 '_mantu_chhuria_',
 '_masti',
 '_mc_stan',
 '_md_group_magarkund',
 '_md_gruop_magarkund',
 '_md_grup',
 '_mdsl',
 '_me',
 '_mere',
 '_mgg',
 '_mixsingh_',
 '_mkglirvae',
 '_mkglirvberp',
 '_mkglirvbhiceljcicjqvjqpmiefly',
 '_mkglirvza',
 '_mkglirvzsuey',
 '_mkglirvzxkbnfeul',
 '_mod',
 '_mod_apkdone',
 '_modification',
 '_months_old',
 '_monudhanushshruthilovebgmringtone',
 '_movies',
 '_mr',
 '_mr_',
 '_mrlytsn',
 '_mt_creation',
 '_mukesh_jaji_',
 '_mulbhut_kartavya_swadhyay',
 '_mumzy',
 '_must',
 '_mw',
 '_n',
 '_naach_with_rach',
 '_naach_with_rach_',
 '_nafrox_',
 '_nagada_mix_',
 '_nazuk',
 '_neha_k',
 '_new',
 '_new_',
 '_new_bhojpuri_song_',
 '_new_black_screen_status_',
 '_new_black_screen_status_punjabi_song',
 '_new_black_screen_whatsapp_status_dj',
 '_new_breakup_whatsapp_status_video_',
 '_new_gujarati_black_screen_status',
 '_new_haryanvi_song_',
 '_new_love_black_screen_status_',
 '_new_notification_ringtonetones',
 '_new_sambalpuri_song_',
 '_new_trending_lyrical_status',
 '_new_year_status',
 '_nhkumwoy',
 '_nl',
 '_no',
 '_nonstop',
 '_nurm',
 '_nushrat___whatsapp_status__',
 '_nwh',
 '_nxnptxk',
 '_o',
 '_o_xzig',
 '_oamnjg',
 '_odia_',
 '_odia_black_screen_status_',
 '_odia_black_screen_status_video',
 '_odia_sad_song_',
 '_odia_song_',
 '_odianews',
 '_official',
 '_official_full_video_',
 '_ohayo',
 '_on_tranding',
 '_on_trending',
 '_on_trending_for_status',
 '_oq',
 '_oqueewu',
 '_others_status_viseo',
 '_ouhkstqfre',
 '_ouktefrc',
 '_ouyjsnmoc',
 '_overthinking',
 '_p',
 '_pade_hathiyaro_ki',
 '_page_',
 '_painful',
 '_parry_sidhu_',
 '_pav',
 '_pcieg',
 '_pe',
 '_peelwedcem',
 '_pendi_ki_heli',
 '_pgmb',
 '_picturebook',
 '_ping_pong_mix_',
 '_pjys',
 '_pkpc',
 '_places_to_visit_in_gorakhpur',
 '_places_to_visit_in_shahranpur',
 '_plan',
 '_pogp',
 '_pradeep',
 '_pranjal_dahiya_',
 '_preeti_raina_',
 '_prem',
 '_prem_darshan_',
 '_priyambada_swain',
 '_pro',
 '_pro_camera_photography',
 '_pro_max',
 '_pro_pubg',
 '_pro_upcoming_smartphones_in_tamil',
 '_pro_vs_iphone_',
 '_pubg',
 '_pubgml',
 '_punjabi',
 '_pvfcg',
 '_pwpig',
 '_q',
 '_qe',
 '_qi',
 '_ql',
 '_qq',
 '_qqmrmii',
 '_qwjgewzc',
 '_rab_hasta_hua_rakhe_tumko_',
 '_race_full',
 '_rahul',
 '_raj_singh_kashyap_',
 '_raja_d',
 '_ranu',
 '_rare_groove',
 '_ratanpur_',
 '_ravi',
 '_rcittiulq',
 '_re_',
 '_realme',
 '_remix_',
 '_review',
 '_ringtone',
 '_ritesh',
 '_rm',
 '_rme',
 '_roast',
 '_roda_sher_re',
 '_roda_श',
 '_rohit_',
 '_royalcustoms_',
 '_rpi',
 '_rprqpbcjzta',
 '_rqmxxrezq',
 '_ruchika_jangid_',
 '_running',
 '_rznnyjheye',
 '_s',
 '_s_h_o_a_i_b__k_h_a_n_',
 '_saal',
 '_sad_shayari_mood_off_status',
 '_sad_song_hindi_',
 '_sad_status_video',
 '_saidpur',
 '_saif_ali_khan',
 '_sajaoongi',
 '_sambalpuri',
 '_sambalpuri_rock_song_',
 '_sameeksha',
 '_sars_control_and_psychological_effects_of_quarantine_toronto_canada',
 '_satisfy',
 '_satisfya',
 '_savage',
 '_sb_tech_',
 '_sec_best_sad_whatsapp_status',
 '_sec_status',
 '_sec_status_video',
 '_sec_whatsapp_status',
 '_secnd_whatsapp_status',
 '_second_evergreen',
 '_second_sad_status_video',
 '_second_status',
 '_second_video_video',
 '_second_whatsapp_status',
 '_second_whatsappstatus',
 '_sep_',
 '_sep_status',
 '_series',
 '_sh_zpqzbnu',
 '_shaadi_special_',
 '_shailesh',
 '_shikshak_bharti',
 '_shivam_grover_ft',
 '_shorts',
 '_singh',
 '_sittin',
 '_six',
 '_sk',
 '_smiling_cars',
 '_smoke_atmosphere_hd_',
 '_something',
 '_song',
 '_song_par_photo_lagaye',
 '_song_status',
 '_song_status_for_whatsapp',
 '_song_status_full_screen',
 '_song_status_sad',
 '_sound_fix',
 '_sound_horn_fix',
 '_sourav_',
 '_sourav_dash_',
 '_sourav_thanks',
 '_south_',
 '_special_whatsapp_status',
 '_sspa',
 '_status',
 '_stebin_ben__',
 '_story',
 '_studio_version_',
 '_stutas',
 '_subscribe_कर_द',
 '_sunny_inder',
 '_super_',
 '_supporting',
 '_surendra_nagvanshi_editing_ki_dukanhello',
 '_suyyash_rai',
 '_svg_',
 '_swadhyay',
 '_swag_gameplay',
 '_swagger_',
 '_sy',
 '_szl',
 '_t',
 '_tabu',
 '_tamil_mass_bgm_ringtone',
 '_tatve',
 '_tbs',
 '_team_profile_atletico_de_kolkata',
 '_team_profile_chennaiyin_fc',
 '_team_profile_delhi_dynamos_fc',
 '_team_profile_fc_goa',
 '_team_profile_fc_pune_city',
 '_team_profile_kerala_blasters',
 '_team_profile_mumbai_city_fc',
 '_telugu',
 '_tfgb',
 '_tfgbwydrcc',
 '_th_august_',
 '_the',
 '_the_fading',
 '_the_nightingale_and_the_nobleman_pointers',
 '_the_rahul_singh',
 '_there',
 '_this_channel',
 '_throughout_the_city_',
 '_thug',
 '_thw',
 '_tik_tok',
 '_tiktok',
 '_tin',
 '_title_song_',
 '_tk',
 '_to_',
 '_to_crown_historic_night_in_mumbai',
 '_tomafo',
 '_top',
 '_toxic_op_yt',
 '_toxic_yt',
 '_tpfzas',
 '_trading',
 '_trend',
 '_trending',
 '_trending_status',
 '_trendingstatus',
 '_try',
 '_twpx',
 '_u',
 '_ucfnm',
 '_ud',
 '_ueygwfw',
 '_uhdz',
 '_uhwpfxoymk',
 '_ujrd',
 '_uma_old_song_',
 '_umrao_jaan_',
 '_update',
 '_upga',
 '_urfrnog',
 '_uttar_pradesh',
 '_uudjalmaf',
 '_uvr',
 '_uxjbhsc',
 '_uxyua',
 '_v_v_p_',
 '_vam',
 '_vassundhara_pandita',
 '_vdu',
 '_vee',
 '_verma',
 '_very_sad_whatsapp_status_video_',
 '_vfx',
 '_vi',
 '_vi_annajal_kavita_swadhyay',
 '_video',
 '_video_in_josh_app',
 '_villian_mass_ringtone',
 '_virtual',
 '_vishal_',
 '_vlogs',
 '_vlpkuu',
 '_vrz',
 '_vs_india_u_',
 '_vs_ktmrc',
 '_vvn_vvn_',
 '_vzximskvj',
 '_waiting_list_latest_news',
 '_we',
 '_wegonr',
 '_whatsapp_status',
 '_whatsapp_status_',
 '_when',
 '_wholesome_',
 '_wi',
 '_with_cast_and_release',
 '_world_cup',
 '_wstatus',
 '_wzl',
 '_x',
 '_x_',
 '_xbclsnlrdm',
 '_xboxlive',
 '_xlndjiaee',
 '_xnmju',
 '_xo',
 '_xtaofes',
 '_xtrnfw',
 '_xws',
 '_xxy',
 '_y',
 '_yamraj_',
 '_years_in_human_years',
 '_yiccdfwq',
 '_ynxhhmn',
 '_young',
 '_yrone',
 '_yuliusremby',
 '_ywb',
 '_yxenyq',
 '_yxxibcfia',
 '_zack',
 '_zcquqqmkla',
 '_zdaroidrl',
 '_zjrnpo',
 '_zln',
 '_zmpumg',
 '_znoyq',
 '_zo',
 '_zunqdm',
 '_zxegq',
 '_zzlu',
 '_اا',
 '_अध',
 '_अन',
 '_अब',
 '_अम',
 '_अय',
 '_अवस',
 '_आ',
 '_आईन',
 '_आगमन',
 '_आठव',
 '_आण',
 '_आपल',
 '_आरक',
 '_आह',
 '_इज',
 '_इत',

# Generate tf-idf for the given document

In [155]:
i = 0
tex_list = df['Processed_text'].tolist()
tf_idf_vector_list = []
for i in range(len(tex_list)):
    tf_idf_vector=tfidf_transformer.transform(cv.transform([tex_list[i]]))
    i = i+1
    tf_idf_vector_list.append(tf_idf_vector)
    # added to list  
    if ((i%10000) == 0):
        print ('Collecting tf-idf',i)
print(len(tf_idf_vector_list))

Collecting tf-idf 10000
Collecting tf-idf 20000
Collecting tf-idf 30000
Collecting tf-idf 40000
Collecting tf-idf 50000
Collecting tf-idf 60000
Collecting tf-idf 70000
Collecting tf-idf 80000
Collecting tf-idf 90000
Collecting tf-idf 100000
105604

In [156]:
tf_idf_vector_list[0].todense()

matrix([[0., 0., 0., ..., 0., 0., 0.]])

In [157]:
tf_idf_vector_list[0].todense().shape

(1, 233158)

# Label Generation for Supervised Learning
K-Means Clustering is done based on Processed text

In [158]:
#Clustering
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

In [159]:
document = df['Processed_text'].values.astype('U')
vectorizer = TfidfVectorizer(stop_words='english')
features = vectorizer.fit_transform(document)

In [160]:
k=20 #Obtained from Silhouette_score
model = KMeans(n_clusters=k,init='k-means++',max_iter=100,n_init=1)
label = model.fit(features)

# Calculation of optimal value of K

In [161]:
# from sklearn.metrics import silhouette_score

# sil = []
# kmax = 20
# sil
# # dissimilarity would not be defined for a single cluster, thus, minimum number of clusters should be 2
# for k in range(2, kmax+1):
#     kmeans = KMeans(n_clusters = k).fit(features)
#     labels = kmeans.labels_
#     sil.append(silhouette_score(features, labels, metric = 'euclidean'))
#     print("Done for k =",k)

In [162]:
df['cluster'] = model.labels_

In [163]:
print(model.labels_)

[18 18 18 ... 18 18 18]

In [164]:
print(model.labels_)

[18 18 18 ... 18 18 18]

In [165]:
df.head()

,ContentId,title,viewCount,likeCount,dislikeCount,commentCount,favoriteCount,publishedAt,description,duration,tags,text,Processed_text,Word_Count,cluster
0,lBvknjH3MF0,Akash Chopra Hindi Commentary,1092,83,0,0,0,2021-05-05T10:04:48Z,Follow for more on Insta https://www.instagr...,PT30S,"['Cricket', 'India', 'Commentary', 'Hindijokes...",akash chopra hindi commentaryfollow for more o...,akash chopra hindi commentaryfollow insta http...,16,18
1,qlReo1HxJpE,THE LAUGH CLUB OPEN MIC VLOG 2,14702,749,3,19,0,2021-02-13T06:19:39Z,#STANDUPCOMEDY #COMEDY #LAUGHCLUB THIS VIDEO ...,PT6M42S,[],the laugh club open mic vlog standupcomedy com...,laugh club open mic vlog standupcomedy comedy ...,67,18
2,b0SnJGhuSFQ,FUNNY ROAST OF APPLE 🔥,10370,388,3,19,0,2021-02-04T01:34:45Z,#ROAST #APPLE #IPHONE #AIRPOD ITS A MICRO - R...,PT3M5S,"['Roast', 'Apple', 'iPhone', 'Airpod', 'Jokes'...",funny roast of apple roast apple iphone airpod...,funny roast apple roast apple iphone airpod mi...,44,18
3,nfBqb5ZEPys,Stand Up Comedy Homey B,1211,21,0,9,0,2020-12-12T10:35:18Z,Crowd work stand up comedy by HomeyB https://...,PT29S,"['Standupcomedy', 'Standup', 'Jokes', 'Haha', ...",stand up comedy homey bcrowd work stand up com...,stand comedy homey bcrowd work stand comedy ho...,33,17
4,ZbOQhsNS87s,TIKTOK ZINDA HAI | NEW CLEAR FAMILY | FAMILY C...,32404,6003,23,344,0,2020-07-19T23:35:01Z,Link first episode EK THA TIKTOK -https://yout...,PT8M18S,"['TIKTOKROAST', 'TIKTOK', 'TIKTOKZINDAHAI', 'E...",tiktok zinda hai new clear family family comed...,tiktok zinda hai new clear family family comed...,198,18

# Checking number of items in each cluster

In [166]:
i = 0
for i in range(len(df['cluster'].unique())):
    count = (df.cluster == i).sum()
    print(f"Total count of cluster {i} is {count}")

Total count of cluster 0 is 1575
Total count of cluster 1 is 1304
Total count of cluster 2 is 2293
Total count of cluster 3 is 3334
Total count of cluster 4 is 2224
Total count of cluster 5 is 2786
Total count of cluster 6 is 4664
Total count of cluster 7 is 822
Total count of cluster 8 is 914
Total count of cluster 9 is 10269
Total count of cluster 10 is 12367
Total count of cluster 11 is 1567
Total count of cluster 12 is 1090
Total count of cluster 13 is 4874
Total count of cluster 14 is 1932
Total count of cluster 15 is 933
Total count of cluster 16 is 1904
Total count of cluster 17 is 2779
Total count of cluster 18 is 46922
Total count of cluster 19 is 1051

# Sort the tf-idf vectors by descending order of scores

In [167]:
def sort_coo(coo_matrix):
    tuples = zip(coo_matrix.col, coo_matrix.data)
    return sorted(tuples, key=lambda x: (x[1], x[0]), reverse=True)

In [168]:
sorted_items_list=[]
i=0
for i in range(len(tf_idf_vector_list)):
    sorted_items=sort_coo(tf_idf_vector_list[i].tocoo())
    i = i+1
    sorted_items_list.append(sorted_items)
    # added to list  
    if ((i%10000) == 0):
        print ('Sorting Done for',i)

Sorting Done for 10000
Sorting Done for 20000
Sorting Done for 30000
Sorting Done for 40000
Sorting Done for 50000
Sorting Done for 60000
Sorting Done for 70000
Sorting Done for 80000
Sorting Done for 90000
Sorting Done for 100000

In [169]:
len(sorted_items_list)

105604

# Extract only the top n; n here is 5

In [170]:
def extract_topn_from_vector(feature_names, sorted_items, topn=5):
    """get the feature names and tf-idf score of top n items"""
    
    #use only topn items from vector
    sorted_items = sorted_items[:topn]

    score_vals = []
    feature_vals = []
    
    # word index and corresponding tf-idf score
    for idx, score in sorted_items:
        
        #keep track of feature name and its corresponding score
        score_vals.append(round(score, 3))
        feature_vals.append(feature_names[idx])

    #create a tuples of feature,score
    #results = zip(feature_vals,score_vals)
    results= {}
    for idx in range(len(feature_vals)):
        results[feature_vals[idx]]=score_vals[idx]
    
    return results

In [171]:
keyword_list = []
i=0
for i in range(len(sorted_items_list)):
    keywords=extract_topn_from_vector(feature_names,sorted_items_list[i],5)
    i = i+1
    keyword_list.append(keywords)
    # added to list  
    if ((i%10000) == 0):
        print ('Keywords added for',i)

Keywords added for 10000
Keywords added for 20000
Keywords added for 30000
Keywords added for 40000
Keywords added for 50000
Keywords added for 60000
Keywords added for 70000
Keywords added for 80000
Keywords added for 90000
Keywords added for 100000

In [172]:
len(keyword_list)

105604

In [173]:
def getList(dict):
    return list(dict.keys())
key_list = []
i = 0
for i in range(len(keyword_list)):
    keys = getList(keyword_list[i])
    key_list.append(keys)
    
len(key_list)

105604

In [174]:
key_list[0]

['commentary', 'commentaryfollow', 'homeybvibe', 'hindijokes', 'akash']

In [175]:
df['keywords'] = key_list

In [176]:
df.head()

,ContentId,title,viewCount,likeCount,dislikeCount,commentCount,favoriteCount,publishedAt,description,duration,tags,text,Processed_text,Word_Count,cluster,keywords
0,lBvknjH3MF0,Akash Chopra Hindi Commentary,1092,83,0,0,0,2021-05-05T10:04:48Z,Follow for more on Insta https://www.instagr...,PT30S,"['Cricket', 'India', 'Commentary', 'Hindijokes...",akash chopra hindi commentaryfollow for more o...,akash chopra hindi commentaryfollow insta http...,16,18,"[commentary, commentaryfollow, homeybvibe, hin..."
1,qlReo1HxJpE,THE LAUGH CLUB OPEN MIC VLOG 2,14702,749,3,19,0,2021-02-13T06:19:39Z,#STANDUPCOMEDY #COMEDY #LAUGHCLUB THIS VIDEO ...,PT6M42S,[],the laugh club open mic vlog standupcomedy com...,laugh club open mic vlog standupcomedy comedy ...,67,18,"[homeybvibe, club, laugh, open, thelaughclubof..."
2,b0SnJGhuSFQ,FUNNY ROAST OF APPLE 🔥,10370,388,3,19,0,2021-02-04T01:34:45Z,#ROAST #APPLE #IPHONE #AIRPOD ITS A MICRO - R...,PT3M5S,"['Roast', 'Apple', 'iPhone', 'Airpod', 'Jokes'...",funny roast of apple roast apple iphone airpod...,funny roast apple roast apple iphone airpod mi...,44,18,"[homeybvibe, roast, airpod, apple, roastvideoi..."
3,nfBqb5ZEPys,Stand Up Comedy Homey B,1211,21,0,9,0,2020-12-12T10:35:18Z,Crowd work stand up comedy by HomeyB https://...,PT29S,"['Standupcomedy', 'Standup', 'Jokes', 'Haha', ...",stand up comedy homey bcrowd work stand up com...,stand comedy homey bcrowd work stand comedy ho...,33,17,"[homeyb, comedy, iteration, funjokes, bcrowd]"
4,ZbOQhsNS87s,TIKTOK ZINDA HAI | NEW CLEAR FAMILY | FAMILY C...,32404,6003,23,344,0,2020-07-19T23:35:01Z,Link first episode EK THA TIKTOK -https://yout...,PT8M18S,"['TIKTOKROAST', 'TIKTOK', 'TIKTOKZINDAHAI', 'E...",tiktok zinda hai new clear family family comed...,tiktok zinda hai new clear family family comed...,198,18,"[geeta, homey, god, dr, family]"

In [177]:
count_list = []
key_words=''
keyword_list = df['keywords']
combine_keyword = [[' '.join(i)] for i in keyword_list]
df['combine_keywords'] = combine_keyword

In [178]:
df.head()

,ContentId,title,viewCount,likeCount,dislikeCount,commentCount,favoriteCount,publishedAt,description,duration,tags,text,Processed_text,Word_Count,cluster,keywords,combine_keywords
0,lBvknjH3MF0,Akash Chopra Hindi Commentary,1092,83,0,0,0,2021-05-05T10:04:48Z,Follow for more on Insta https://www.instagr...,PT30S,"['Cricket', 'India', 'Commentary', 'Hindijokes...",akash chopra hindi commentaryfollow for more o...,akash chopra hindi commentaryfollow insta http...,16,18,"[commentary, commentaryfollow, homeybvibe, hin...",[commentary commentaryfollow homeybvibe hindij...
1,qlReo1HxJpE,THE LAUGH CLUB OPEN MIC VLOG 2,14702,749,3,19,0,2021-02-13T06:19:39Z,#STANDUPCOMEDY #COMEDY #LAUGHCLUB THIS VIDEO ...,PT6M42S,[],the laugh club open mic vlog standupcomedy com...,laugh club open mic vlog standupcomedy comedy ...,67,18,"[homeybvibe, club, laugh, open, thelaughclubof...",[homeybvibe club laugh open thelaughclubofficial]
2,b0SnJGhuSFQ,FUNNY ROAST OF APPLE 🔥,10370,388,3,19,0,2021-02-04T01:34:45Z,#ROAST #APPLE #IPHONE #AIRPOD ITS A MICRO - R...,PT3M5S,"['Roast', 'Apple', 'iPhone', 'Airpod', 'Jokes'...",funny roast of apple roast apple iphone airpod...,funny roast apple roast apple iphone airpod mi...,44,18,"[homeybvibe, roast, airpod, apple, roastvideoi...",[homeybvibe roast airpod apple roastvideoindia]
3,nfBqb5ZEPys,Stand Up Comedy Homey B,1211,21,0,9,0,2020-12-12T10:35:18Z,Crowd work stand up comedy by HomeyB https://...,PT29S,"['Standupcomedy', 'Standup', 'Jokes', 'Haha', ...",stand up comedy homey bcrowd work stand up com...,stand comedy homey bcrowd work stand comedy ho...,33,17,"[homeyb, comedy, iteration, funjokes, bcrowd]",[homeyb comedy iteration funjokes bcrowd]
4,ZbOQhsNS87s,TIKTOK ZINDA HAI | NEW CLEAR FAMILY | FAMILY C...,32404,6003,23,344,0,2020-07-19T23:35:01Z,Link first episode EK THA TIKTOK -https://yout...,PT8M18S,"['TIKTOKROAST', 'TIKTOK', 'TIKTOKZINDAHAI', 'E...",tiktok zinda hai new clear family family comed...,tiktok zinda hai new clear family family comed...,198,18,"[geeta, homey, god, dr, family]",[geeta homey god dr family]

In [179]:
data = df['combine_keywords']
result = []
for sublist in data:
    for item in sublist:
        result.append(item)

df['combine_keywords'] = result
df.head()

,ContentId,title,viewCount,likeCount,dislikeCount,commentCount,favoriteCount,publishedAt,description,duration,tags,text,Processed_text,Word_Count,cluster,keywords,combine_keywords
0,lBvknjH3MF0,Akash Chopra Hindi Commentary,1092,83,0,0,0,2021-05-05T10:04:48Z,Follow for more on Insta https://www.instagr...,PT30S,"['Cricket', 'India', 'Commentary', 'Hindijokes...",akash chopra hindi commentaryfollow for more o...,akash chopra hindi commentaryfollow insta http...,16,18,"[commentary, commentaryfollow, homeybvibe, hin...",commentary commentaryfollow homeybvibe hindijo...
1,qlReo1HxJpE,THE LAUGH CLUB OPEN MIC VLOG 2,14702,749,3,19,0,2021-02-13T06:19:39Z,#STANDUPCOMEDY #COMEDY #LAUGHCLUB THIS VIDEO ...,PT6M42S,[],the laugh club open mic vlog standupcomedy com...,laugh club open mic vlog standupcomedy comedy ...,67,18,"[homeybvibe, club, laugh, open, thelaughclubof...",homeybvibe club laugh open thelaughclubofficial
2,b0SnJGhuSFQ,FUNNY ROAST OF APPLE 🔥,10370,388,3,19,0,2021-02-04T01:34:45Z,#ROAST #APPLE #IPHONE #AIRPOD ITS A MICRO - R...,PT3M5S,"['Roast', 'Apple', 'iPhone', 'Airpod', 'Jokes'...",funny roast of apple roast apple iphone airpod...,funny roast apple roast apple iphone airpod mi...,44,18,"[homeybvibe, roast, airpod, apple, roastvideoi...",homeybvibe roast airpod apple roastvideoindia
3,nfBqb5ZEPys,Stand Up Comedy Homey B,1211,21,0,9,0,2020-12-12T10:35:18Z,Crowd work stand up comedy by HomeyB https://...,PT29S,"['Standupcomedy', 'Standup', 'Jokes', 'Haha', ...",stand up comedy homey bcrowd work stand up com...,stand comedy homey bcrowd work stand comedy ho...,33,17,"[homeyb, comedy, iteration, funjokes, bcrowd]",homeyb comedy iteration funjokes bcrowd
4,ZbOQhsNS87s,TIKTOK ZINDA HAI | NEW CLEAR FAMILY | FAMILY C...,32404,6003,23,344,0,2020-07-19T23:35:01Z,Link first episode EK THA TIKTOK -https://yout...,PT8M18S,"['TIKTOKROAST', 'TIKTOK', 'TIKTOKZINDAHAI', 'E...",tiktok zinda hai new clear family family comed...,tiktok zinda hai new clear family family comed...,198,18,"[geeta, homey, god, dr, family]",geeta homey god dr family

# Input Data

In [180]:
import numpy as np
input_data = np.array(df['combine_keywords'])
input_data = input_data.flatten()

In [181]:
input_data.shape

(105604,)

# Output Data

In [182]:
output_data = df['cluster']

In [183]:
output_data.shape

(105604,)

# Train test split

In [184]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split (input_data,output_data,test_size=0.20,random_state=1,stratify=output_data)
y_train.shape

(84483,)

# Text to numerical conversion

In [185]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
train_data=vectorizer.fit_transform(x_train)
test_data=vectorizer.transform(x_test)
train_data

<84483x55400 sparse matrix of type '<class 'numpy.float64'>'
	with 422101 stored elements in Compressed Sparse Row format>

In [186]:
train_data.shape

(84483, 55400)

In [187]:
from sklearn.decomposition import TruncatedSVD
def svd_tfidf_matrix(matrix):
    svd = TruncatedSVD(n_components=3)
    return svd.fit_transform(matrix)

In [188]:
train_data = svd_tfidf_matrix(matrix=train_data)

In [189]:
test_data = svd_tfidf_matrix(matrix=test_data)

In [190]:
train_data.shape

(84483, 3)

In [191]:
test_data.shape

(21121, 3)

# XGB Classifier

In [192]:
#!pip install xgboost --upgrade
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

# fit model no training data
model = XGBClassifier()
model.fit(train_data, y_train)
print(model)

/home/shivshaurya/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[14:48:50] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=16,
              num_parallel_tree=1, objective='multi:softprob', predictor='auto',
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
              subsample=1, tree_method='exact', use_label_encoder=True,
              validate_parameters=1, verbosity=None)

In [193]:
import xgboost 
print(xgboost.__version__)

1.5.0

In [194]:
print(model.score(train_data, y_train))
print(model.score(test_data,y_test))

0.7788075707538795
0.578949860328583

In [195]:
test_data[0]

array([ 4.34599316e-05, -1.91566098e-06,  3.36047687e-05])

In [196]:
from sklearn.metrics import auc, accuracy_score, confusion_matrix, mean_squared_error
y_pred = model.predict(test_data)

mse=mean_squared_error(y_test, y_pred)

print(np.sqrt(mse))

5.769411871838058

# Save the model

In [197]:
# save the model to disk
import pickle
filename = 'xgboost.pb'
pickle.dump(model, open(filename, 'wb'))

# Test Input Keyword

In [198]:
keyword = "standup comedy videos"

In [199]:
keyword_data=np.array(keyword)
keyword_data = keyword_data.flatten()
keyword_vect=vectorizer.fit_transform(keyword_data)
keyword_vect

<1x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

# Load the saved ML Model

In [200]:
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(keyword_vect)
print(result)

[2]

In [201]:
result_cluster = df.loc[df['cluster'] == result[0]]
result_cluster

,ContentId,title,viewCount,likeCount,dislikeCount,commentCount,favoriteCount,publishedAt,description,duration,tags,text,Processed_text,Word_Count,cluster,keywords,combine_keywords
3180,PF03ZVlsLU4,एक्स गर्लफ्रेंड की एमएमएस Teaser | MMS Returns...,561,39,1,2,0,2021-10-10T07:00:24Z,This video is just a teaser for एक्स गर्लफ्रें...,PT44S,"['deeperinto horror stories', 'hindi animated ...",एक स गर लफ र ड क एमएमएस teaser mms returns hor...,एक स गर लफ र ड क एमएमएस teaser mm return horro...,389,2,"[mm, horror, story, deeperinto, college]",mm horror story deeperinto college
3181,0PrDhUlbvhs,College mms horror story cartoon | एमएमएस | एम...,37528,692,63,20,0,2021-09-26T06:37:00Z,College MMS ( एमएमएस ) is a horror story about...,PT24M10S,"['deeperinto horror stories', 'mms', 'college ...",college mms horror story cartoon एमएमएस एमएमएस...,college mm horror story cartoon एमएमएस एमएमएस ...,427,2,"[mm, horror, story, college, एमएमएस]",mm horror story college एमएमएस
3182,4qyLWrY5Im4,Kabristan Ki Chudail | Hindi Horror Stories |...,23782,551,28,25,0,2021-09-19T06:07:07Z,Kabristan Ki Chudai or चुड़ैल कब्रिस्तान की is...,PT15M,"['deeperinto horror stories', 'chudail kabrist...",kabristan ki chudail hindi horror stories च ड ...,kabristan ki chudail hindi horror story च ड ल ...,437,2,"[kabristan, chudail, horror, story, ki]",kabristan chudail horror story ki
3183,9VD1joZ49GM,Kabristan Ki Chudail Teaser | Hindi Horror Sto...,564,43,4,6,0,2021-09-12T10:56:38Z,Title : Kabristan Ki Chudail Teaser | Hindi Ho...,PT32S,"['deeperinto horror stories', 'kabristan ki ch...",kabristan ki chudail teaser hindi horror stori...,kabristan ki chudail teaser hindi horror story...,247,2,"[chudail, kabristan, horror, story, deeperinto]",chudail kabristan horror story deeperinto
3184,1y3oAfUT1R4,Chudail Ki Pyar Ki Kahani | चुड़ैल | Chudail k...,23328,468,37,20,0,2021-08-29T09:14:11Z,Chudail Ki Pyar Ki Kahani (चुड़ैल) is an old f...,PT14M56S,"['chudail ki pyar ki kahani', 'chudail ek prem...",chudail ki pyar ki kahani च ड ल chudail ki kah...,chudail ki pyar ki kahani च ड ल chudail ki kah...,570,2,"[chudail, story, horror, kahaniya, hindi]",chudail story horror kahaniya hindi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103443,eo_Eyik2Pp8,मजबूर व्यापारी | Helpless merchant | Hindi kah...,1140,3,0,0,0,2015-09-14T04:33:19Z,Our content consists of the entire 9th standar...,PT3M30S,"['hindi kahaniya for kids', 'hindi kahani', 'h...",मजब र व य प र helpless merchant hindi kahaniya...,मजब र व य प र helpless merchant hindi kahaniya...,101,2,"[story, moral, kid, hindi, kahaniya]",story moral kid hindi kahaniya
103444,pCl02hxT1m8,भिकारी से भगवान | Bhikari Se Bhagvan | Hindi k...,6237,21,4,0,0,2015-09-14T04:33:19Z,Our content consists of the entire 10th standa...,PT2M29S,"['hindi kahaniya for kids', 'hindi kahani', 'h...",भ क र स भगव न bhikari se bhagvan hindi kahaniy...,भ क र स भगव न bhikari se bhagvan hindi kahaniy...,150,2,"[story, moral, kid, hindi, kahaniya]",story moral kid hindi kahaniya
103445,zZbGzq5Twcs,नकल | Nakal | Hindi kahaniya for kids | Moral ...,62929,228,77,0,0,2015-09-14T04:33:19Z,Our content consists of the entire 8th standar...,PT3M34S,"['hindi kahaniya for kids', 'hindi kahani', 'h...",नकल nakal hindi kahaniya for kids moral story ...,नकल nakal hindi kahaniya kid moral story hindi...,144,2,"[story, moral, kid, hindi, kahaniya]",story moral kid hindi kahaniya
103463,tXFA-SpXbnA,गौरा | Gaura | Animal Story | Hindi cartoon | ...,47909,277,49,0,0,2015-07-29T11:46:54Z,Our content consists of the entire syllabus in...,PT1M50S,"['hindi kahaniya for kids', 'hindi moral stori...",ग र gaura animal story hindi cartoon kahaniya ...,ग र gaura animal story hindi cartoon kahaniya ...,145,2,"[gaura, story, moral, kid, hindi]",gaura story moral kid hindi
103502,JFR5NK61c6o,पंडित जी की कर्तव्यनिष्ठा | Panditji ki Kartav...,1773,6,1,0,0,2015-02-09T06:21:07Z,Our content consists of the entire syllabus in...,PT1M40S,"['hindi kahaniya for kids', 'hindi kahani', 'h...",प ड त ज क कर तव यन ष ठ panditji ki kartavyanis...,प ड त ज क कर तव यन ष ठ panditji ki kartavyanis...,149,2,"[story, moral, kid, hindi, kahaniya]",story moral kid hindi kahaniya

In [202]:
result_cluster['viewCount'] = result_cluster['viewCount'].astype('int32')

<ipython-input-202-2fa0e82fe5af>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_cluster['viewCount'] = result_cluster['viewCount'].astype('int32')

In [203]:
result_cluster['viewCount'].dtype

dtype('int32')

In [204]:
#Ten largest values in view Count column
recommended_data = result_cluster.nlargest(10,['viewCount'])
recommended_data

,ContentId,title,viewCount,likeCount,dislikeCount,commentCount,favoriteCount,publishedAt,description,duration,tags,text,Processed_text,Word_Count,cluster,keywords,combine_keywords
100754,iN-5t9-KmkQ,चुड़ैल कल आना | ज़ालिम सास | Hindi Stories | Hor...,126341227,[],[],4995,0,2019-05-28T06:03:15Z,चुड़ैल कल आना | ज़ालिम सास | Hindi Stories | Hor...,PT10M6S,"['चुड़ैल कल आना', 'Hindi Stories', 'Latest kaha...",च ड़ ल कल आन ज़ ल म स स hindi stories horror sto...,च ड़ ल कल आन ज़ ल म स स hindi story horror story...,145,2,"[story, kahaniya, horror, hindi, bhootiya]",story kahaniya horror hindi bhootiya
4549,1W-tzuxQMvc,चोटी काटने वाली चुड़ैल | Horror Stories | Engli...,124534359,381814,165920,5388,0,2019-09-08T05:53:40Z,चोटी काटने वाली चुड़ैल | Horror Stories | Engli...,PT10M6S,"['चोटी काटने वाली चुड़ैल', 'Hindi Stories', 'La...",च ट क टन व ल च ड़ ल horror stories english subt...,च ट क टन व ल च ड़ ल horror story english subtit...,157,2,"[story, kahaniya, horror, chudail, टन]",story kahaniya horror chudail टन
19870,ckekwXelUSY,भूतिया Hand Pump। Possessed Village Water Hand...,116145996,357967,173141,4430,0,2020-05-21T02:15:02Z,You can listen to our stories now on Gaana.com...,PT10M2S,"['Hindi Stories', 'Latest kahaniya', 'Kahani',...",भ त य hand pump possessed village water hand p...,भ त य hand pump possess village water hand pum...,249,2,"[story, kahaniya, pump, hindi, horror]",story kahaniya pump hindi horror
19871,1eqreKRwhg0,चुड़ैल पेट्रोल चोर | Female Petrol Thief | Hind...,99648693,356682,164718,4539,0,2020-05-19T02:30:00Z,You can listen to our stories now on Gaana.com...,PT10M2S,"['Hindi Stories', 'Latest kahaniya', 'Kahani',...",च ड़ ल प ट र ल च र female petrol thief hindi ka...,च ड़ ल प ट र ल च र female petrol thief hindi ka...,247,2,"[story, kahaniya, hindi, horror, petrol]",story kahaniya hindi horror petrol
21503,LKouFx2OkDI,स्वर्ण नगरी || New Hindi Kahaniya || SSOFTOONS...,98803156,298887,145979,3095,0,2020-04-11T04:00:04Z,"Svarn nagri, SONE KI NAGRI, The city of gold, ...",PT17M35S,"['ssoftoons hindi', 'ssoftoons hindi video', '...",स वर ण नगर new hindi kahaniya ssoftoons hindi ...,स वर ण नगर new hindi kahaniya ssoftoons hindi ...,106,2,"[hindi, jadui, nagri, story, kahaniya]",hindi jadui nagri story kahaniya
19877,q33HjI-IQWU,चुड़ैल माँ | बच्चा चुराने वाली चुड़ैल | Hindi S...,91530955,292963,129138,4098,0,2020-05-07T02:15:01Z,Please Subscribe Our Channel: https://bit.ly/2...,PT8M58S,"['Hindi Stories', 'Latest kahaniya', 'Kahani',...",च ड ल म बच च च र न व ल च ड़ ल hindi stories hor...,च ड ल म बच च च र न व ल च ड़ ल hindi story horro...,234,2,"[story, kahaniya, horror, hindi, haunt]",story kahaniya horror hindi haunt
14339,0PM3RW1zBx8,चुड़ैल की बेटी | Witch's Daughter | Loyal Dog |...,86848270,321677,143263,4211,0,2020-08-14T04:45:45Z,Please Subscribe Our Channel: https://bit.ly/2...,PT10M,"['Hindi Stories', 'Latest kahaniya', 'Kahani',...",च ड़ ल क ब ट witch s daughter loyal dog hindi h...,च ड़ ल क ब ट witch daughter loyal dog hindi hor...,215,2,"[story, kahaniya, hindi, horror, bhootiya]",story kahaniya hindi horror bhootiya
19873,wQagT6MCFZY,भूतिया झूला । झूले पर बैठना मना है । Haunted S...,78388206,268725,127091,3771,0,2020-05-15T02:15:00Z,Please Subscribe Our Channel: https://bit.ly/2...,PT10M3S,"['Hindi Stories', 'Latest kahaniya', 'Kahani',...",भ त य झ ल झ ल पर ब ठन मन ह haunted swing stori...,भ त य झ ल झ ल पर ब ठन मन ह haunt swing story h...,236,2,"[story, kahaniya, horror, haunt, hindi]",story kahaniya horror haunt hindi
19942,dzqBAmXjJLM,पत्नी निकली चुड़ैल | Wife Became Witch | Hindi ...,75835479,271175,89583,5760,0,2019-10-04T07:36:29Z,Please Subscribe Our Channel: https://bit.ly/2...,PT10M24S,"['पत्नी निकली चुड़ैल', 'Chudail ki kahaniya', '...",पत न न कल च ड़ ल wife became witch hindi storie...,पत न न कल च ड़ ल wife become witch hindi story ...,169,2,"[story, kahaniya, moral, hindi, subtitle]",story kahaniya moral hindi subtitle
4561,lM5rs0gNBqA,जय बजरंग बली | Hindi Stories For Adults | Horr...,72107100,[],[],3232,0,2019-07-29T07:22:51Z,जय बजरंग बली | Hindi Stories For Adults | Horr...,PT10M15S,"['जय बजरंग बली', 'Hindi Stories', 'Latest kaha...",जय बजर ग बल hindi stories for adults horror st...,जय बजर ग बल hindi story adult horror story chu...,145,2,"[story, kahaniya, बजर, horror, ki]",story kahaniya बजर horror ki

In [205]:
recommendation_videos = recommended_data[['ContentId','title']]
recommendation_videos

          ContentId                                              title
100754  iN-5t9-KmkQ  चुड़ैल कल आना | ज़ालिम सास | Hindi Stories | Hor...
4549    1W-tzuxQMvc  चोटी काटने वाली चुड़ैल | Horror Stories | Engli...
19870   ckekwXelUSY  भूतिया Hand Pump। Possessed Village Water Hand...
19871   1eqreKRwhg0  चुड़ैल पेट्रोल चोर | Female Petrol Thief | Hind...
21503   LKouFx2OkDI  स्वर्ण नगरी || New Hindi Kahaniya || SSOFTOONS...
19877   q33HjI-IQWU  चुड़ैल माँ | बच्चा चुराने वाली चुड़ैल | Hindi S...
14339   0PM3RW1zBx8  चुड़ैल की बेटी | Witch's Daughter | Loyal Dog |...
19873   wQagT6MCFZY  भूतिया झूला । झूले पर बैठना मना है । Haunted S...
19942   dzqBAmXjJLM  पत्नी निकली चुड़ैल | Wife Became Witch | Hindi ...
4561    lM5rs0gNBqA  जय बजरंग बली | Hindi Stories For Adults | Horr...

In [ ]:
keyword