In [1]:
# import necessary libraries 
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
#Loading the dataset and displaying the first few rows.
iris_data = pd.read_csv('/kaggle/input/iris/Iris.csv')
iris_data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
# Split the data into features (X) and labels (Y).
X=iris_data.drop(columns=['Id','Species'])
Y=iris_data['Species']
X.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [4]:
# Split the data into training and testing sets.
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
# Standardize the features.
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [5]:
# Create a ML model.
model = LogisticRegression()
#Train the model.
model.fit(X_train_scaled,Y_train)

LogisticRegression()

In [6]:
# Evaluate the model on the testing set.
Y_pred=model.predict(X_test_scaled)
accuracy = accuracy_score(Y_test,Y_pred)
print('Acuracy: ',accuracy)

Acuracy:  1.0

In [7]:
#Predict using the trained model.
prediction = model.predict([[4.6,3.5,1.5,0.2]])
# Print the prediction.
print(prediction)

['Iris-versicolor']

In [8]:
# Sample new data for prediction.
new_data =np.array([[5.6,3.5,1.4,0.2],
                   [6.3,2.9,5.6,1.8],
                   [4.9,3.0,1.4,0.2]])
# Standardize the data.
new_data_scaled =scaler.fit_transform(new_data)
# Make predictions.
predictions = model.predict(new_data_scaled)
# Display the predicted classes.
print('Predictions: ', predictions)

Predictions:  ['Iris-setosa' 'Iris-virginica' 'Iris-setosa']