In [1]:
import sys
sys.path.append("/aloy/home/ddalton/projects/scGPT_playground")
from src.preprocessing import pipeline as pp
from src.utils import utils, utils as ut
import scanpy as sc

manual_parameters = { 
    "dataset_exercise":"umls_clean",                 
    "diseases_of_interest_set": None,
    "library_strategies_of_interest_set": ["RNA-Seq"],
    "normalize": "log2CPM",  # options: "log2CPM", "CPM", None
}

# get dsaids of interest
dsaids_interest = ut.get_doids_with_umls(manual_parameters.get("library_strategies_of_interest_set"))

# get data info
df_info = ut.load_dsa_info()
print(f"Loaded DSAIDs info: {len(df_info)}")

df_filtered = df_info[df_info["dsaid"].isin(dsaids_interest)]
print(f"Filtered DSAIDs info: {len(df_filtered)}")

/aloy/home/ddalton/miniconda3/envs/scgpt/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
INFO:root:Loading signatures from file /aloy/home/ddalton/projects/disease_signatures/data/DiSignAtlas/signatures.pkl

Loaded Nº DSAIDs: 10306
Filter Human Species Nº DSAIDs: 7194
Filter ['RNA-Seq'] Nº DSAIDs: 2536
Filter DSAIDs with info Nº DSAIDs: 2534
Loaded signatures Nº DSAIDs: 2534

INFO:root:Nº of Human protein coding genes: 20608

Loaded human protein coding genes: 20608
Filter to enough Human protein coding genes Nº DSAIDs: 2533
Filter by clean DSAIDs Nº DSAIDs: 2533
Filter by presence of UMLS codes Nº DSAIDs: 2421
Filter by mapping from UMLS to DOID Nº DSAIDs: 1607
Loaded DSAIDs info: 10306
Filtered DSAIDs info: 1607

In [2]:
df_filtered["dsaid"].to_list()

['DSA00004',
 'DSA00006',
 'DSA00015',
 'DSA00016',
 'DSA00030',
 'DSA00045',
 'DSA00046',
 'DSA00047',
 'DSA00048',
 'DSA00068',
 'DSA00069',
 'DSA00071',
 'DSA00072',
 'DSA00073',
 'DSA00074',
 'DSA00104',
 'DSA00105',
 'DSA00111',
 'DSA00112',
 'DSA00113',
 'DSA00115',
 'DSA00116',
 'DSA00117',
 'DSA00118',
 'DSA00131',
 'DSA00132',
 'DSA00135',
 'DSA00147',
 'DSA00148',
 'DSA00151',
 'DSA00175',
 'DSA00176',
 'DSA00180',
 'DSA00181',
 'DSA00187',
 'DSA00188',
 'DSA00197',
 'DSA00205',
 'DSA00215',
 'DSA00216',
 'DSA00217',
 'DSA00219',
 'DSA00220',
 'DSA00221',
 'DSA00244',
 'DSA00247',
 'DSA00248',
 'DSA00249',
 'DSA00250',
 'DSA00252',
 'DSA00253',
 'DSA00275',
 'DSA00276',
 'DSA00277',
 'DSA00278',
 'DSA00279',
 'DSA00282',
 'DSA00283',
 'DSA00288',
 'DSA00295',
 'DSA00312',
 'DSA00313',
 'DSA00342',
 'DSA00343',
 'DSA00353',
 'DSA00360',
 'DSA00365',
 'DSA00366',
 'DSA00367',
 'DSA00368',
 'DSA00395',
 'DSA00413',
 'DSA00414',
 'DSA00415',
 'DSA00416',
 'DSA00417',
 'DSA00418',
 'DSA00423',
 'DSA00424',
 'DSA00443',
 'DSA00452',
 'DSA00459',
 'DSA00460',
 'DSA00461',
 'DSA00462',
 'DSA00468',
 'DSA00469',
 'DSA00481',
 'DSA00482',
 'DSA00487',
 'DSA00496',
 'DSA00499',
 'DSA00500',
 'DSA00501',
 'DSA00508',
 'DSA00513',
 'DSA00514',
 'DSA00515',
 'DSA00516',
 'DSA00517',
 'DSA00518',
 'DSA00519',
 'DSA00520',
 'DSA00521',
 'DSA00522',
 'DSA00523',
 'DSA00524',
 'DSA00525',
 'DSA00529',
 'DSA00551',
 'DSA00552',
 'DSA00553',
 'DSA00555',
 'DSA00556',
 'DSA00557',
 'DSA00573',
 'DSA00584',
 'DSA00585',
 'DSA00599',
 'DSA00602',
 'DSA00603',
 'DSA00604',
 'DSA00605',
 'DSA00631',
 'DSA00632',
 'DSA00633',
 'DSA00634',
 'DSA00636',
 'DSA00638',
 'DSA00639',
 'DSA00640',
 'DSA00641',
 'DSA00646',
 'DSA00647',
 'DSA00652',
 'DSA00654',
 'DSA00655',
 'DSA00656',
 'DSA00657',
 'DSA00658',
 'DSA00659',
 'DSA00664',
 'DSA00679',
 'DSA00680',
 'DSA00688',
 'DSA00691',
 'DSA00692',
 'DSA00694',
 'DSA00695',
 'DSA00696',
 'DSA00701',
 'DSA00702',
 'DSA00703',
 'DSA00708',
 'DSA00710',
 'DSA00713',
 'DSA00714',
 'DSA00719',
 'DSA00720',
 'DSA00721',
 'DSA00722',
 'DSA00735',
 'DSA00740',
 'DSA00745',
 'DSA00748',
 'DSA00749',
 'DSA00752',
 'DSA00759',
 'DSA00765',
 'DSA00770',
 'DSA00771',
 'DSA00772',
 'DSA00773',
 'DSA00782',
 'DSA00785',
 'DSA00800',
 'DSA00816',
 'DSA00817',
 'DSA00818',
 'DSA00819',
 'DSA00820',
 'DSA00822',
 'DSA00823',
 'DSA00825',
 'DSA00826',
 'DSA00827',
 'DSA00839',
 'DSA00859',
 'DSA00860',
 'DSA00863',
 'DSA00864',
 'DSA00874',
 'DSA00875',
 'DSA00879',
 'DSA00886',
 'DSA00887',
 'DSA00893',
 'DSA00894',
 'DSA00895',
 'DSA00905',
 'DSA00906',
 'DSA00915',
 'DSA00916',
 'DSA00927',
 'DSA00928',
 'DSA00929',
 'DSA00932',
 'DSA00933',
 'DSA00934',
 'DSA00935',
 'DSA00936',
 'DSA00937',
 'DSA00938',
 'DSA00939',
 'DSA00958',
 'DSA00961',
 'DSA00978',
 'DSA00984',
 'DSA00992',
 'DSA00993',
 'DSA00994',
 'DSA01014',
 'DSA01015',
 'DSA01016',
 'DSA01017',
 'DSA01021',
 'DSA01023',
 'DSA01024',
 'DSA01025',
 'DSA01029',
 'DSA01030',
 'DSA01035',
 'DSA01046',
 'DSA01055',
 'DSA01058',
 'DSA01064',
 'DSA01075',
 'DSA01076',
 'DSA01078',
 'DSA01093',
 'DSA01097',
 'DSA01098',
 'DSA01099',
 'DSA01100',
 'DSA01104',
 'DSA01108',
 'DSA01113',
 'DSA01131',
 'DSA01132',
 'DSA01139',
 'DSA01140',
 'DSA01154',
 'DSA01173',
 'DSA01175',
 'DSA01176',
 'DSA01177',
 'DSA01178',
 'DSA01180',
 'DSA01181',
 'DSA01182',
 'DSA01183',
 'DSA01184',
 'DSA01194',
 'DSA01195',
 'DSA01224',
 'DSA01225',
 'DSA01226',
 'DSA01247',
 'DSA01249',
 'DSA01250',
 'DSA01251',
 'DSA01252',
 'DSA01253',
 'DSA01254',
 'DSA01255',
 'DSA01258',
 'DSA01267',
 'DSA01288',
 'DSA01289',
 'DSA01290',
 'DSA01291',
 'DSA01292',
 'DSA01293',
 'DSA01294',
 'DSA01301',
 'DSA01302',
 'DSA01315',
 'DSA01316',
 'DSA01325',
 'DSA01326',
 'DSA01327',
 'DSA01331',
 'DSA01332',
 'DSA01333',
 'DSA01334',
 'DSA01335',
 'DSA01336',
 'DSA01337',
 'DSA01339',
 'DSA01344',
 'DSA01353',
 'DSA01354',
 'DSA01361',
 'DSA01365',
 'DSA01366',
 'DSA01369',
 'DSA01377',
 'DSA01378',
 'DSA01384',
 'DSA01385',
 'DSA01395',
 'DSA01396',
 'DSA01397',
 'DSA01401',
 'DSA01407',
 'DSA01409',
 'DSA01417',
 'DSA01424',
 'DSA01439',
 'DSA01440',
 'DSA01441',
 'DSA01447',
 'DSA01448',
 'DSA01449',
 'DSA01450',
 'DSA01465',
 'DSA01466',
 'DSA01469',
 'DSA01470',
 'DSA01471',
 'DSA01472',
 'DSA01473',
 'DSA01475',
 'DSA01476',
 'DSA01477',
 'DSA01482',
 'DSA01486',
 'DSA01487',
 'DSA01488',
 'DSA01501',
 'DSA01513',
 'DSA01521',
 'DSA01522',
 'DSA01529',
 'DSA01530',
 'DSA01536',
 'DSA01537',
 'DSA01538',
 'DSA01539',
 'DSA01540',
 'DSA01541',
 'DSA01542',
 'DSA01545',
 'DSA01546',
 'DSA01561',
 'DSA01569',
 'DSA01572',
 'DSA01575',
 'DSA01590',
 'DSA01593',
 'DSA01594',
 'DSA01595',
 'DSA01596',
 'DSA01597',
 'DSA01598',
 'DSA01599',
 'DSA01600',
 'DSA01601',
 'DSA01602',
 'DSA01604',
 'DSA01605',
 'DSA01615',
 'DSA01618',
 'DSA01620',
 'DSA01632',
 'DSA01633',
 'DSA01635',
 'DSA01640',
 'DSA01641',
 'DSA01642',
 'DSA01653',
 'DSA01654',
 'DSA01655',
 'DSA01664',
 'DSA01665',
 'DSA01668',
 'DSA01669',
 'DSA01670',
 'DSA01671',
 'DSA01672',
 'DSA01674',
 'DSA01675',
 'DSA01676',
 'DSA01677',
 'DSA01681',
 'DSA01691',
 'DSA01695',
 'DSA01696',
 'DSA01697',
 'DSA01698',
 'DSA01699',
 'DSA01703',
 'DSA01704',
 'DSA01706',
 'DSA01707',
 'DSA01708',
 'DSA01709',
 'DSA01710',
 'DSA01717',
 'DSA01720',
 'DSA01721',
 'DSA01724',
 'DSA01732',
 'DSA01733',
 'DSA01734',
 'DSA01735',
 'DSA01736',
 'DSA01737',
 'DSA01738',
 'DSA01739',
 'DSA01740',
 'DSA01744',
 'DSA01745',
 'DSA01750',
 'DSA01754',
 'DSA01770',
 'DSA01772',
 'DSA01773',
 'DSA01774',
 'DSA01775',
 'DSA01776',
 'DSA01779',
 'DSA01783',
 'DSA01795',
 'DSA01796',
 'DSA01797',
 'DSA01799',
 'DSA01817',
 'DSA01818',
 'DSA01819',
 'DSA01820',
 'DSA01821',
 'DSA01822',
 'DSA01826',
 'DSA01828',
 'DSA01830',
 'DSA01840',
 'DSA01841',
 'DSA01842',
 'DSA01843',
 'DSA01844',
 'DSA01845',
 'DSA01846',
 'DSA01850',
 'DSA01851',
 'DSA01852',
 'DSA01853',
 'DSA01855',
 'DSA01856',
 'DSA01857',
 'DSA01985',
 'DSA02173',
 'DSA02253',
 'DSA02284',
 'DSA02330',
 'DSA02404',
 'DSA02588',
 'DSA02624',
 'DSA02627',
 'DSA02630',
 'DSA02631',
 'DSA02632',
 'DSA02635',
 'DSA02638',
 'DSA02639',
 'DSA02640',
 'DSA02641',
 'DSA02644',
 'DSA02647',
 'DSA02648',
 'DSA02649',
 'DSA02650',
 'DSA02651',
 'DSA02657',
 'DSA02658',
 'DSA02659',
 'DSA02664',
 'DSA02665',
 'DSA02666',
 'DSA02667',
 'DSA02668',
 'DSA02669',
 'DSA02673',
 'DSA02694',
 'DSA02708',
 'DSA02715',
 'DSA02716',
 'DSA02718',
 'DSA02719',
 'DSA02730',
 'DSA02731',
 'DSA02732',
 'DSA02733',
 'DSA02734',
 'DSA02755',
 'DSA02757',
 'DSA02758',
 'DSA02759',
 'DSA02764',
 'DSA02765',
 'DSA02766',
 'DSA02771',
 'DSA02772',
 'DSA02773',
 'DSA02774',
 'DSA02780',
 'DSA02781',
 'DSA02782',
 'DSA02783',
 'DSA02784',
 'DSA02787',
 'DSA02790',
 'DSA02793',
 'DSA02799',
 'DSA02805',
 'DSA02817',
 'DSA02818',
 'DSA02821',
 'DSA02822',
 'DSA02823',
 'DSA02824',
 'DSA02825',
 'DSA02826',
 'DSA02827',
 'DSA02828',
 'DSA02829',
 'DSA02832',
 'DSA02833',
 'DSA02834',
 'DSA02835',
 'DSA02839',
 'DSA02840',
 'DSA02849',
 'DSA02850',
 'DSA02851',
 'DSA02852',
 'DSA02853',
 'DSA02854',
 'DSA02860',
 'DSA02867',
 'DSA02868',
 'DSA02874',
 'DSA02875',
 'DSA02876',
 'DSA02877',
 'DSA02878',
 'DSA02886',
 'DSA02887',
 'DSA02891',
 'DSA02893',
 'DSA02894',
 'DSA02898',
 'DSA02914',
 'DSA02915',
 'DSA02916',
 'DSA02921',
 'DSA02924',
 'DSA02925',
 'DSA02938',
 'DSA02939',
 'DSA02943',
 'DSA02944',
 'DSA02945',
 'DSA02950',
 'DSA02951',
 'DSA02952',
 'DSA02953',
 'DSA02954',
 'DSA02955',
 'DSA02977',
 'DSA02978',
 'DSA02984',
 'DSA02985',
 'DSA02986',
 'DSA02990',
 'DSA02994',
 'DSA02996',
 'DSA02997',
 'DSA02998',
 'DSA02999',
 'DSA03000',
 'DSA03001',
 'DSA03006',
 'DSA03008',
 'DSA03009',
 'DSA03010',
 'DSA03011',
 'DSA03015',
 'DSA03020',
 'DSA03022',
 'DSA03023',
 'DSA03024',
 'DSA03025',
 'DSA03026',
 'DSA03027',
 'DSA03028',
 'DSA03029',
 'DSA03033',
 'DSA03034',
 'DSA03042',
 'DSA03046',
 'DSA03047',
 'DSA03048',
 'DSA03054',
 'DSA03065',
 'DSA03084',
 'DSA03085',
 'DSA03104',
 'DSA03114',
 'DSA03115',
 'DSA03116',
 'DSA03117',
 'DSA03118',
 'DSA03119',
 'DSA03122',
 'DSA03123',
 'DSA03124',
 'DSA03128',
 'DSA03129',
 'DSA03133',
 'DSA03134',
 'DSA03135',
 'DSA03136',
 'DSA03137',
 'DSA03138',
 'DSA03139',
 'DSA03140',
 'DSA03141',
 'DSA03144',
 'DSA03147',
 'DSA03148',
 'DSA03149',
 'DSA03150',
 'DSA03162',
 'DSA03163',
 'DSA03167',
 'DSA03168',
 'DSA03186',
 'DSA03187',
 'DSA03191',
 'DSA03192',
 'DSA03193',
 'DSA03194',
 'DSA03196',
 'DSA03197',
 'DSA03198',
 'DSA03200',
 'DSA03206',
 'DSA03211',
 'DSA03212',
 'DSA03213',
 'DSA03214',
 'DSA03215',
 'DSA03217',
 'DSA03218',
 'DSA03229',
 'DSA03230',
 'DSA03231',
 'DSA03237',
 'DSA03544',
 'DSA03624',
 'DSA03668',
 'DSA03767',
 'DSA03769',
 'DSA03770',
 'DSA03775',
 'DSA03776',
 'DSA03783',
 'DSA03786',
 'DSA03788',
 'DSA03789',
 'DSA03791',
 'DSA03792',
 'DSA03794',
 'DSA03795',
 'DSA03797',
 'DSA03798',
 'DSA03800',
 'DSA03802',
 'DSA03806',
 'DSA03807',
 'DSA03808',
 'DSA03809',
 'DSA03810',
 'DSA03811',
 'DSA03812',
 'DSA03813',
 'DSA03829',
 'DSA03831',
 'DSA03832',
 'DSA03838',
 'DSA03839',
 'DSA03840',
 'DSA03841',
 'DSA03853',
 'DSA03857',
 'DSA03874',
 'DSA03878',
 'DSA03883',
 'DSA03884',
 'DSA03885',
 'DSA03886',
 'DSA03893',
 'DSA03894',
 'DSA03895',
 'DSA03896',
 'DSA03897',
 'DSA03902',
 'DSA03903',
 'DSA03904',
 'DSA03923',
 'DSA03924',
 'DSA03925',
 'DSA03940',
 'DSA03945',
 'DSA03946',
 'DSA03947',
 'DSA03948',
 'DSA03949',
 'DSA03950',
 'DSA03955',
 'DSA03959',
 'DSA03961',
 'DSA03975',
 'DSA03986',
 'DSA03987',
 'DSA04017',
 'DSA04031',
 'DSA04032',
 'DSA04033',
 'DSA04034',
 'DSA04035',
 'DSA04036',
 'DSA04037',
 'DSA04038',
 'DSA04039',
 'DSA04052',
 'DSA04060',
 'DSA04061',
 'DSA04062',
 'DSA04071',
 'DSA04076',
 'DSA04077',
 'DSA04078',
 'DSA04079',
 'DSA04080',
 'DSA04082',
 'DSA04083',
 'DSA04085',
 'DSA04098',
 'DSA04099',
 'DSA04102',
 'DSA04103',
 'DSA04104',
 'DSA04105',
 'DSA04106',
 'DSA04107',
 'DSA04108',
 'DSA04134',
 'DSA04139',
 'DSA04148',
 'DSA04149',
 'DSA04158',
 'DSA04196',
 'DSA04197',
 'DSA04198',
 'DSA04199',
 'DSA04202',
 'DSA04204',
 'DSA04234',
 'DSA04235',
 'DSA04251',
 'DSA04254',
 'DSA04255',
 'DSA04256',
 'DSA04257',
 'DSA04258',
 'DSA04276',
 'DSA04277',
 'DSA04278',
 'DSA04279',
 'DSA04280',
 'DSA04299',
 'DSA04300',
 'DSA04301',
 'DSA04304',
 'DSA04305',
 'DSA04306',
 'DSA04308',
 'DSA04309',
 'DSA04310',
 'DSA04311',
 'DSA04312',
 'DSA04313',
 'DSA04314',
 'DSA04317',
 'DSA04318',
 'DSA04319',
 'DSA04322',
 'DSA04324',
 'DSA04343',
 'DSA04346',
 'DSA04351',
 'DSA04352',
 'DSA04356',
 'DSA04364',
 'DSA04369',
 'DSA04373',
 'DSA04376',
 'DSA04384',
 'DSA04385',
 'DSA04386',
 'DSA04387',
 'DSA04398',
 'DSA04399',
 'DSA04400',
 'DSA04401',
 'DSA04402',
 'DSA04403',
 'DSA04404',
 'DSA04405',
 'DSA04420',
 'DSA04421',
 'DSA04428',
 'DSA04449',
 'DSA04450',
 'DSA04475',
 'DSA04476',
 'DSA04480',
 'DSA04500',
 'DSA04503',
 'DSA04527',
 'DSA04574',
 'DSA04592',
 'DSA04593',
 'DSA04627',
 'DSA04632',
 'DSA04656',
 'DSA04673',
 'DSA04678',
 'DSA04679',
 'DSA04680',
 'DSA04683',
 'DSA04805',
 'DSA04811',
 'DSA04812',
 'DSA04837',
 'DSA04838',
 'DSA04840',
 'DSA04843',
 'DSA04844',
 'DSA04848',
 'DSA04849',
 'DSA04854',
 'DSA04855',
 'DSA04863',
 'DSA04870',
 'DSA04871',
 'DSA04873',
 'DSA04894',
 'DSA04895',
 'DSA04896',
 'DSA04915',
 'DSA04916',
 'DSA04917',
 'DSA04930',
 'DSA04931',
 'DSA04932',
 'DSA04933',
 'DSA05025',
 'DSA05042',
 'DSA05043',
 'DSA05045',
 'DSA05046',
 'DSA05047',
 'DSA05049',
 'DSA05050',
 'DSA05051',
 'DSA05052',
 'DSA05053',
 'DSA05054',
 'DSA05058',
 'DSA05059',
 'DSA05060',
 'DSA05061',
 'DSA05062',
 'DSA05063',
 'DSA05064',
 'DSA05065',
 'DSA05070',
 'DSA05072',
 'DSA05073',
 'DSA05074',
 'DSA05075',
 'DSA05076',
 'DSA05094',
 'DSA05095',
 'DSA05096',
 'DSA05111',
 'DSA05137',
 'DSA05138',
 'DSA05139',
 'DSA05140',
 'DSA05145',
 'DSA05146',
 'DSA05147',
 'DSA05149',
 'DSA05151',
 'DSA05162',
 'DSA05164',
 'DSA05165',
 'DSA05172',
 'DSA05173',
 'DSA05176',
 'DSA05181',
 'DSA05182',
 'DSA05183',
 'DSA05185',
 'DSA05186',
 'DSA05187',
 'DSA05191',
 'DSA05197',
 'DSA05199',
 'DSA05200',
 'DSA05201',
 'DSA05205',
 'DSA05206',
 'DSA05208',
 'DSA05209',
 'DSA05210',
 'DSA05211',
 'DSA05212',
 'DSA05213',
 'DSA05214',
 'DSA05215',
 'DSA05216',
 'DSA05217',
 'DSA05220',
 'DSA05221',
 'DSA05222',
 'DSA05225',
 'DSA05226',
 'DSA05249',
 'DSA05250',
 'DSA05276',
 'DSA05281',
 'DSA05282',
 'DSA05283',
 'DSA05292',
 'DSA05295',
 'DSA05296',
 'DSA05297',
 'DSA05301',
 'DSA05308',
 'DSA05309',
 'DSA05310',
 'DSA05313',
 'DSA05314',
 'DSA05315',
 'DSA05322',
 'DSA05323',
 'DSA05324',
 'DSA05326',
 'DSA05327',
 'DSA05330',
 'DSA05331',
 'DSA05332',
 'DSA05349',
 'DSA05354',
 'DSA05360',
 'DSA05361',
 'DSA05368',
 'DSA05369',
 'DSA05370',
 'DSA05377',
 'DSA05378',
 'DSA05385',
 'DSA05392',
 'DSA05393',
 'DSA05394',
 'DSA05395',
 'DSA05396',
 'DSA05397',
 'DSA05406',
 'DSA05407',
 'DSA05408',
 'DSA05410',
 'DSA05411',
 'DSA05412',
 'DSA05414',
 ...]

In [3]:
import scanpy as sc
adata = sc.read_h5ad("/aloy/home/ddalton/projects/scGPT_playground/data/pp_data-25-08-13-01/data.h5ad")

FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/aloy/home/ddalton/projects/scGPT_playground/data/pp_data-25-08-13-01/data.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [ ]:
adata.shape

(0, 20608)

In [ ]:
import importlib
importlib.reload(pp)

In [ ]:
df_filtered = df_filtered.copy()
df_filtered["celltype"] = df_filtered["diseaseid"]
df_filtered["ids"] = df_filtered["dsaid"]
df_filtered["dataset_id"] = df_filtered["accession"]

In [ ]:
# quality control
# dsaids >= n_samples
counts_cond = df_filtered["control_case_sample_count"].to_list()
df_filtered = df_filtered.copy()
df_filtered["n_control"] = [int(x.split("|")[0]) for x in counts_cond]
df_filtered["n_cases"] = [int(x.split("|")[1]) for x in counts_cond]
df_filtered["celltype"] = df_filtered["diseaseid"]

for i in [1,2, 5, 10]:
    print(f"Nº DSAIDs with +{i} cases: {len(df_filtered[df_filtered['n_cases'] >= i])}")

for i in [1,2, 5, 10]:
    print(f"Nº DSAIDs with +{i} controls: {len(df_filtered[df_filtered['n_control'] >= i])}")

for i in [1,2, 5, 10]:
    print(f"Nº DSAIDs with +{i} controls & conditions: {len(df_filtered[(df_filtered['n_cases']>= i) & (df_filtered['n_control'] >= i)])}")


df_filtered_2 = df_filtered[(df_filtered['n_cases']>= 2) & (df_filtered['n_control'] >= 2)]
print(f"Filtered DSAIDs info with +2 cases & controls: {len(df_filtered_2)}")

Nº DSAIDs with +1 cases: 1607
Nº DSAIDs with +2 cases: 1506
Nº DSAIDs with +5 cases: 870
Nº DSAIDs with +10 cases: 462
Nº DSAIDs with +1 controls: 1607
Nº DSAIDs with +2 controls: 1511
Nº DSAIDs with +5 controls: 872
Nº DSAIDs with +10 controls: 434
Nº DSAIDs with +1 controls & conditions: 1607
Nº DSAIDs with +2 controls & conditions: 1467
Nº DSAIDs with +5 controls & conditions: 731
Nº DSAIDs with +10 controls & conditions: 326
Filtered DSAIDs info with +2 cases & controls: 1467

In [ ]:
# diseases >= n_datasets
for i in [1,2,3, 5, 10]:
    _n_diseases = sum(df_filtered.groupby('diseaseid')['accession'].nunique()>=i)
    print(f"Nº diseases with +{i} datasets: {_n_diseases}")
v

for i in [1,2,3, 5, 10]:
    _n_diseases = sum(df_filtered_2.groupby('diseaseid')['accession'].nunique()>=i)
    print(f"Nº diseases - pre-filtered -  with +{i} datasets: {_n_diseases}")


disease_ids_interest = [k for k, v in dict(df_filtered_2.groupby('diseaseid')['accession'].nunique()).items() if v>=3 ]

df_filtered_3 = df_filtered_2[df_filtered_2["diseaseid"].isin(disease_ids_interest)]
print(f"Nº DSAIDs with +3 datasets: {len(df_filtered_3)}")

Nº diseases with +1 datasets: 340
Nº diseases with +2 datasets: 141
Nº diseases with +3 datasets: 87
Nº diseases with +5 datasets: 46
Nº diseases with +10 datasets: 17
Nº diseases - pre-filtered -  with +1 datasets: 324
Nº diseases - pre-filtered -  with +2 datasets: 133
Nº diseases - pre-filtered -  with +3 datasets: 82
Nº diseases - pre-filtered -  with +5 datasets: 44
Nº diseases - pre-filtered -  with +10 datasets: 15
Nº DSAIDs with +3 datasets: 999

In [ ]:

def do_you_fuck():
    print(fuck)


fuck = "Yes"
do_you_fuck()

Yes

In [ ]:
import importlib
importlib.reload(pp)

fuck="YES"
pp.do_you_fuck()

NameError: name 'fuck' is not defined

In [ ]:
from src.training import train as tr

In [ ]:
df_filtered = pp.clean_dsaids_qc(df_filtered)

Nº dsaids: 1181	Nº unique diseases: 133
Filter Datasets w/ Samples +2	Nº dsaids: 1181	Nº unique diseases: 133
Filter Diseases w/ Datasets +2	Nº dsaids: 1181	Nº unique diseases: 133

In [ ]:
df_split_2 = tr.split_stratified(df_filtered)

tr.is_test_good(df_split_2)

True

In [ ]:
import pandas as pd

In [ ]:
report_split(df_split_2)

Nº of diseases in train split 1:	133
Nº of diseases in test split 1:	133
Nº of datasets in train split 1:	533
Nº of datasets in test split 1:	135
Nº of samples in train split 1:	942
Nº of samples in test split 1:	239

In [ ]:
df_split_2[df_split_2["accession"] == "GSE174302"]

In [ ]:
df_split_2

,dsaid,accession,platform,deg_count,disease,diseaseid,tissue,data_source,library_strategy,organism,control_case_sample_count,definition,n_control,n_cases,celltype,ids,dataset_id,test_split_1
3,DSA00004,GSE224022,GPL16791,1000,Retinoblastoma,C0035335,Retina,GEO,RNA-Seq,Homo sapiens,4|5,DO:A retinal cell cancer and malignant neoplas...,4,5,C0035335,DSA00004,GSE224022,0
5,DSA00006,GSE126342,GPL11154,1000,Myotonic Dystrophy Type 1,C0027126,Skeletal muscle,GEO,RNA-Seq,Homo sapiens,6|16,DO:A myotonic disease that is characterized by...,6,16,C0027126,DSA00006,GSE126342,1
14,DSA00015,GSE224056,GPL24676,1000,Gastric Cancer,C0699791,Stomach,GEO,RNA-Seq,Homo sapiens,4|5,DO:A gastrointestinal system cancer that is lo...,4,5,C0699791,DSA00015,GSE224056,1
15,DSA00016,GSE224056,GPL24676,112,Gastric Cancer,C0699791,Stomach,GEO,RNA-Seq,Homo sapiens,5|5,DO:A gastrointestinal system cancer that is lo...,5,5,C0699791,DSA00016,GSE224056,1
29,DSA00030,GSE215424,GPL24676,1000,Amyotrophic Lateral Sclerosis,C0002736,Muscle,GEO,RNA-Seq,Homo sapiens,5|5,DO:A motor neuron disease that is characterize...,5,5,C0002736,DSA00030,GSE215424,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10101,DSA10102,GSE163908,GPL24676,935,Idiopathic Pulmonary Fibrosis,C1800706,NaN,GEO,RNA-Seq,Homo sapiens,3|3,DO:A pulmonary fibrosis that is characterized ...,3,3,C1800706,DSA10102,GSE163908,0
10120,DSA10121,GSE29006,GPL10999,0,Lung Cancer,C0684249,Lung,GEO,RNA-Seq,Homo sapiens,2|2,DO:A respiratory system cancer that is located...,2,2,C0684249,DSA10121,GSE29006,0
10130,DSA10131,GSE164264,GPL23227,1000,Acquired Immunodeficiency Syndrome,C0001175,Blood,GEO,RNA-Seq,Homo sapiens,2|2,DO:A viral infectious disease that results in ...,2,2,C0001175,DSA10131,GSE164264,0
10131,DSA10132,GSE164264,GPL23227,1000,Acquired Immunodeficiency Syndrome,C0001175,Blood,GEO,RNA-Seq,Homo sapiens,2|2,DO:A viral infectious disease that results in ...,2,2,C0001175,DSA10132,GSE164264,0
10148,DSA10149,GSE164376,GPL24676,95,Schizophrenia,C0036341,NaN,GEO,RNA-Seq,Homo sapiens,9|7,DO:A psychotic disorder that is characterized ...,9,7,C0036341,DSA10149,GSE164376,0

In [ ]:
group_label = "dataset_id"

test_dt = df_split_2[df_split_2[f"test_split_{1}"]==1][group_label].unique()
train_dt = df_split_2[df_split_2[f"test_split_{1}"]==0][group_label].unique()

set(test_dt) & set(train_dt)

set()

In [ ]:
from typing import *
import pandas as pd
import logging
from sklearn.model_selection import StratifiedGroupKFold, GroupShuffleSplit

import random
population = [1,2,3,4,5]
s_size = (len(population) //10)



def get_stratified_test_split(obs: pd.DataFrame, n_splits=3) -> List[str]:
    """Get Test Split
    We will perform a split for those diseases which have more than one dataset.

    There MUST not be any data-leakage between the train and test set - no shared datasets between the two sets.

    Strategy:
        1. Check diseases w/ n_splits+ datasets
        2. Divide dataset into train and test w/ 10:1 ratio
        3. Assign train and test to the respective datasets

    """

    obs_copy = obs.copy(deep=True)

    # pre-process data
    obs_copy["combination"] = (
        obs_copy["celltype"].astype(str) + "_" + obs_copy["dataset_id"].astype(str)
    )

    logging.info(f"Columns in obs_copy {obs_copy.columns}")

    assert "combination" in obs_copy.columns, "combination column not created in obs"

    diseases_f1 = set()  # diseases filter 1

    # 1. Check diseases w/ n_splits+ datasets
    all_diseases = obs_copy["celltype"].unique()
    for diseases in all_diseases:
        QUERY = f'celltype == "{diseases}"'
        _df_query = obs_copy.query(QUERY)
        if len(_df_query["dataset_id"].unique()) >= n_splits:
            diseases_f1.add(diseases)

    logging.info(f"Number of diseases with {n_splits}+ datasets: {len(diseases_f1)}")

    # 2. Divide dataset into train and test to n_splits
    QUERY = "celltype in @diseases_f1"
    df_diseases_f1 = obs_copy.query(QUERY)

    sgkf = StratifiedGroupKFold(n_splits=10, shuffle=True, random_state=42)
    for i, (train_idx, test_idx) in enumerate(
        sgkf.split(
            X=df_diseases_f1["ids"],
            y=df_diseases_f1["celltype"],
            groups=df_diseases_f1["dataset_id"],
        )
    ):

        # get which disease & datasets are in the test
        df_diseases_f1_test = df_diseases_f1.iloc[test_idx]
        df_diseases_f1_train = df_diseases_f1.iloc[train_idx]

        assert "combination" in obs_copy.columns, "combination column not found in obs"
        assert (
            "combination" in df_diseases_f1_test.columns
        ), "combination column not found in df_diseases_f1_test"

        # 3. Assign train and test labels
        obs_copy[f"test_split_{i+1}"] = (
            obs_copy["combination"].isin(df_diseases_f1_test["combination"]).astype(int)
        )

        logging.info(
            f"Nº of diseases in train split {i+1}: {obs_copy.iloc[train_idx]['celltype'].nunique()}"
        )

        logging.info(
            f"Nº of diseases in test split {i+1}: {obs_copy.iloc[test_idx]['celltype'].nunique()}"
        )

        logging.info(
            f"Nº of datasets in train split {i+1}: {obs_copy.iloc[train_idx]['dataset_id'].nunique()}"
        )

        logging.info(
            f"Nº of datasets in test split {i+1}: {obs_copy.iloc[test_idx]['dataset_id'].nunique()}"
        )

        logging.info(
            f"Nº of samples in train split {i+1}: {obs_copy.iloc[train_idx]['ids'].nunique()}"
        )

        logging.info(
            f"Nº of samples in test split {i+1}: {obs_copy.iloc[test_idx]['ids'].nunique()}"
        )

        # assert there is no overlap
        train_dataset_ids = set(df_diseases_f1_train["dataset_id"])
        test_dataset_ids = set(df_diseases_f1_test["dataset_id"])

        overlap = train_dataset_ids.intersection(test_dataset_ids)
 

        assert len(overlap) == 0, f"Overlap found in dataset_ids between train and test in split {i+1}: {overlap}"


    obs_copy.drop(columns=["combination"], inplace=True)

    return obs_copy

df_split = get_stratified_test_split(df_filtered_3, n_splits=3)

INFO:root:Columns in obs_copy Index(['dsaid', 'accession', 'platform', 'deg_count', 'disease', 'diseaseid',
       'tissue', 'data_source', 'library_strategy', 'organism',
       'control_case_sample_count', 'definition', 'n_control', 'n_cases',
       'celltype', 'ids', 'dataset_id', 'combination'],
      dtype='object')
INFO:root:Number of diseases with 3+ datasets: 82
/home/ddalton/Data/old_home/miniconda3/envs/scgpt_2/lib/python3.12/site-packages/sklearn/model_selection/_split.py:994: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  warnings.warn(
INFO:root:Nº of diseases in train split 1: 82
INFO:root:Nº of diseases in test split 1: 38
INFO:root:Nº of datasets in train split 1: 523
INFO:root:Nº of datasets in test split 1: 58
INFO:root:Nº of samples in train split 1: 897
INFO:root:Nº of samples in test split 1: 102
INFO:root:Nº of diseases in train split 2: 82
INFO:root:Nº of diseases in test split 2: 40
INFO:root:Nº of datasets in train split 2: 523
INFO:root:Nº of datasets in test split 2: 58
INFO:root:Nº of samples in train split 2: 903
INFO:root:Nº of samples in test split 2: 96
INFO:root:Nº of diseases in train split 3: 82
INFO:root:Nº of diseases in test split 3: 38
INFO:root:Nº of datasets in train split 3: 522
INFO:root:Nº of datasets in test split 3: 59
INFO:root:Nº of samples in train split 3: 890
INFO:root:Nº of samples in test split 3: 109
INFO:root:Nº of diseases in train split 4: 82
INFO:root:Nº of diseases in test split 4: 35
INFO:root:Nº of datasets in train split 4: 522
INFO:root:Nº of datasets in test split 4: 59
INFO:root:Nº of samples in train split 4: 907
INFO:root:Nº of samples in test split 4: 92
INFO:root:Nº of diseases in train split 5: 82
INFO:root:Nº of diseases in test split 5: 38
INFO:root:Nº of datasets in train split 5: 523
INFO:root:Nº of datasets in test split 5: 58
INFO:root:Nº of samples in train split 5: 912
INFO:root:Nº of samples in test split 5: 87
INFO:root:Nº of diseases in train split 6: 82
INFO:root:Nº of diseases in test split 6: 34
INFO:root:Nº of datasets in train split 6: 524
INFO:root:Nº of datasets in test split 6: 57
INFO:root:Nº of samples in train split 6: 906
INFO:root:Nº of samples in test split 6: 93
INFO:root:Nº of diseases in train split 7: 82
INFO:root:Nº of diseases in test split 7: 38
INFO:root:Nº of datasets in train split 7: 523
INFO:root:Nº of datasets in test split 7: 58
INFO:root:Nº of samples in train split 7: 899
INFO:root:Nº of samples in test split 7: 100
INFO:root:Nº of diseases in train split 8: 82
INFO:root:Nº of diseases in test split 8: 36
INFO:root:Nº of datasets in train split 8: 522
INFO:root:Nº of datasets in test split 8: 59
INFO:root:Nº of samples in train split 8: 880
INFO:root:Nº of samples in test split 8: 119
INFO:root:Nº of diseases in train split 9: 82
INFO:root:Nº of diseases in test split 9: 39
INFO:root:Nº of datasets in train split 9: 523
INFO:root:Nº of datasets in test split 9: 58
INFO:root:Nº of samples in train split 9: 894
INFO:root:Nº of samples in test split 9: 105
INFO:root:Nº of diseases in train split 10: 82
INFO:root:Nº of diseases in test split 10: 42
INFO:root:Nº of datasets in train split 10: 524
INFO:root:Nº of datasets in test split 10: 57
INFO:root:Nº of samples in train split 10: 903
INFO:root:Nº of samples in test split 10: 96

In [ ]:
df_split

,dsaid,accession,platform,deg_count,disease,diseaseid,tissue,data_source,library_strategy,organism,...,test_split_1,test_split_2,test_split_3,test_split_4,test_split_5,test_split_6,test_split_7,test_split_8,test_split_9,test_split_10
5,DSA00006,GSE126342,GPL11154,1000,Myotonic Dystrophy Type 1,C0027126,Skeletal muscle,GEO,RNA-Seq,Homo sapiens,...,0,0,0,0,0,0,1,0,0,0
14,DSA00015,GSE224056,GPL24676,1000,Gastric Cancer,C0699791,Stomach,GEO,RNA-Seq,Homo sapiens,...,0,0,0,0,0,0,0,0,1,0
15,DSA00016,GSE224056,GPL24676,112,Gastric Cancer,C0699791,Stomach,GEO,RNA-Seq,Homo sapiens,...,0,0,0,0,0,0,0,0,1,0
29,DSA00030,GSE215424,GPL24676,1000,Amyotrophic Lateral Sclerosis,C0002736,Muscle,GEO,RNA-Seq,Homo sapiens,...,0,0,0,0,0,1,0,0,0,0
44,DSA00045,GSE223405,GPL16791,1000,Prostate Cancer,C0600139,NaN,GEO,RNA-Seq,Homo sapiens,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10101,DSA10102,GSE163908,GPL24676,935,Idiopathic Pulmonary Fibrosis,C1800706,NaN,GEO,RNA-Seq,Homo sapiens,...,0,0,0,0,0,0,0,0,0,1
10120,DSA10121,GSE29006,GPL10999,0,Lung Cancer,C0684249,Lung,GEO,RNA-Seq,Homo sapiens,...,0,0,0,0,0,0,1,0,0,0
10130,DSA10131,GSE164264,GPL23227,1000,Acquired Immunodeficiency Syndrome,C0001175,Blood,GEO,RNA-Seq,Homo sapiens,...,0,0,0,0,0,1,0,0,0,0
10131,DSA10132,GSE164264,GPL23227,1000,Acquired Immunodeficiency Syndrome,C0001175,Blood,GEO,RNA-Seq,Homo sapiens,...,0,0,0,0,0,1,0,0,0,0
10148,DSA10149,GSE164376,GPL24676,95,Schizophrenia,C0036341,NaN,GEO,RNA-Seq,Homo sapiens,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
df_split_2

,dsaid,accession,platform,deg_count,disease,diseaseid,tissue,data_source,library_strategy,organism,control_case_sample_count,definition,n_control,n_cases,celltype,ids,dataset_id,test_split
5,DSA00006,GSE126342,GPL11154,1000,Myotonic Dystrophy Type 1,C0027126,Skeletal muscle,GEO,RNA-Seq,Homo sapiens,6|16,DO:A myotonic disease that is characterized by...,6,16,C0027126,DSA00006,GSE126342,0
14,DSA00015,GSE224056,GPL24676,1000,Gastric Cancer,C0699791,Stomach,GEO,RNA-Seq,Homo sapiens,4|5,DO:A gastrointestinal system cancer that is lo...,4,5,C0699791,DSA00015,GSE224056,0
15,DSA00016,GSE224056,GPL24676,112,Gastric Cancer,C0699791,Stomach,GEO,RNA-Seq,Homo sapiens,5|5,DO:A gastrointestinal system cancer that is lo...,5,5,C0699791,DSA00016,GSE224056,0
29,DSA00030,GSE215424,GPL24676,1000,Amyotrophic Lateral Sclerosis,C0002736,Muscle,GEO,RNA-Seq,Homo sapiens,5|5,DO:A motor neuron disease that is characterize...,5,5,C0002736,DSA00030,GSE215424,0
44,DSA00045,GSE223405,GPL16791,1000,Prostate Cancer,C0600139,NaN,GEO,RNA-Seq,Homo sapiens,3|3,DO:A prostate cancer that has_material_basis_i...,3,3,C0600139,DSA00045,GSE223405,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10101,DSA10102,GSE163908,GPL24676,935,Idiopathic Pulmonary Fibrosis,C1800706,NaN,GEO,RNA-Seq,Homo sapiens,3|3,DO:A pulmonary fibrosis that is characterized ...,3,3,C1800706,DSA10102,GSE163908,0
10120,DSA10121,GSE29006,GPL10999,0,Lung Cancer,C0684249,Lung,GEO,RNA-Seq,Homo sapiens,2|2,DO:A respiratory system cancer that is located...,2,2,C0684249,DSA10121,GSE29006,0
10130,DSA10131,GSE164264,GPL23227,1000,Acquired Immunodeficiency Syndrome,C0001175,Blood,GEO,RNA-Seq,Homo sapiens,2|2,DO:A viral infectious disease that results in ...,2,2,C0001175,DSA10131,GSE164264,0
10131,DSA10132,GSE164264,GPL23227,1000,Acquired Immunodeficiency Syndrome,C0001175,Blood,GEO,RNA-Seq,Homo sapiens,2|2,DO:A viral infectious disease that results in ...,2,2,C0001175,DSA10132,GSE164264,0
10148,DSA10149,GSE164376,GPL24676,95,Schizophrenia,C0036341,NaN,GEO,RNA-Seq,Homo sapiens,9|7,DO:A psychotic disorder that is characterized ...,9,7,C0036341,DSA10149,GSE164376,0

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "A": [1, 2, 1, 3],
    "B": [1, 1, 3, 4],
    "value": [10, 20, 30, 40]
})

# combinations to mask
combos = [(1, 1), (2, 1), (1, 3)]

mask = df[["A", "B"]].apply(tuple, axis=1).isin(combos)

print(mask)
print(df[mask])

0     True
1     True
2     True
3    False
dtype: bool
   A  B  value
0  1  1     10
1  2  1     20
2  1  3     30

In [ ]:
list(zip(df["A"],df["B"]))

[(1, 1), (2, 1), (1, 3), (3, 4)]

In [ ]:
for i in range(10):
    print(f"Nº of diseasses in train split {i+1}: {df_split[df_split[f'test_split_{i+1}'] == 1]['celltype'].nunique()}")
    print(f"Nº of diseasses in train split {i+1}: {df_split[df_split[f'test_split_{i+1}'] == 1]['accession'].nunique()}")

Nº of diseasses in train split 1: 38
Nº of diseasses in train split 1: 58
Nº of diseasses in train split 2: 40
Nº of diseasses in train split 2: 58
Nº of diseasses in train split 3: 38
Nº of diseasses in train split 3: 59
Nº of diseasses in train split 4: 35
Nº of diseasses in train split 4: 59
Nº of diseasses in train split 5: 38
Nº of diseasses in train split 5: 58
Nº of diseasses in train split 6: 34
Nº of diseasses in train split 6: 57
Nº of diseasses in train split 7: 38
Nº of diseasses in train split 7: 58
Nº of diseasses in train split 8: 36
Nº of diseasses in train split 8: 59
Nº of diseasses in train split 9: 39
Nº of diseasses in train split 9: 58
Nº of diseasses in train split 10: 42
Nº of diseasses in train split 10: 57

In [ ]:
df_split_2

In [ ]:
print(f"Nº of diseasses in train split {i+1}: {df_split_2[df_split_2[f'test_split'] == 1]['celltype'].nunique()}")
print(f"Nº of datasets in train split {i+1}: {df_split_2[df_split_2[f'test_split'] == 0]['accession'].nunique()}")

Nº of diseasses in train split 10: 82
Nº of datasets in train split 10: 496

In [ ]:
df_split[df_split["diseaseid"]=="C0002874"]

,dsaid,accession,platform,deg_count,disease,diseaseid,tissue,data_source,library_strategy,organism,...,test_split_1,test_split_2,test_split_3,test_split_4,test_split_5,test_split_6,test_split_7,test_split_8,test_split_9,test_split_10
2634,DSA02635,GSE165870,GPL24676,129,Aplastic Anemia,C0002874,Bone marrow,GEO,RNA-Seq,Homo sapiens,...,0,1,0,0,0,0,0,0,0,0
3216,DSA03217,GSE140844,GPL11154,93,Aplastic Anemia,C0002874,NaN,GEO,RNA-Seq,Homo sapiens,...,0,0,0,0,0,0,0,0,1,0
9330,DSA09331,GSE145531,GPL20301,1000,Aplastic Anemia,C0002874,Bone marrow,GEO,RNA-Seq,Homo sapiens,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
df_filtered_3.groupby('diseaseid')['accession'].nunique()

diseaseid
C0001175     3
C0002395    29
C0002736    17
C0002874     3
C0003864     3
            ..
C1800706    18
C1839259     3
C1879321     7
C2239176     4
C2936739     3
Name: accession, Length: 82, dtype: int64

In [ ]:
importlib.reload(pp)

In [ ]:
dsaids_interest = ['DSA00004',
 'DSA00006',
 'DSA00015',
 'DSA00016',
 'DSA00030',
 'DSA00045',
 'DSA00046',
 'DSA00047',
 'DSA00048',
 'DSA00071',
 'DSA00072',
 'DSA00073',
 'DSA00074',
 'DSA00105',
 'DSA00111',
 'DSA00112',
 'DSA00113',]
df_1 = pp.get_processed_exp_prof_2(dsaids_interest, normalize="log2CPM")

100%|██████████| 17/17 [00:00<00:00, 48.64it/s]

In [ ]:
df_1

In [5]:
df_2 = pp.get_processed_exp_prof(dsaids_interest[:4], normalize="log2CPM")

Processing: 100%|██████████| 4/4 [00:00<00:00, 16.36it/s]

In [4]:
dsaids_interest

['DSA00004',
 'DSA00006',
 'DSA00015',
 'DSA00016',
 'DSA00030',
 'DSA00045',
 'DSA00046',
 'DSA00047',
 'DSA00048',
 'DSA00068',
 'DSA00069',
 'DSA00071',
 'DSA00072',
 'DSA00073',
 'DSA00074',
 'DSA00104',
 'DSA00105',
 'DSA00111',
 'DSA00112',
 'DSA00113',
 'DSA00115',
 'DSA00116',
 'DSA00117',
 'DSA00118',
 'DSA00131',
 'DSA00132',
 'DSA00135',
 'DSA00147',
 'DSA00148',
 'DSA00151',
 'DSA00175',
 'DSA00176',
 'DSA00180',
 'DSA00181',
 'DSA00187',
 'DSA00188',
 'DSA00197',
 'DSA00205',
 'DSA00215',
 'DSA00216',
 'DSA00217',
 'DSA00219',
 'DSA00220',
 'DSA00221',
 'DSA00244',
 'DSA00247',
 'DSA00248',
 'DSA00249',
 'DSA00250',
 'DSA00252',
 'DSA00253',
 'DSA00275',
 'DSA00276',
 'DSA00277',
 'DSA00278',
 'DSA00279',
 'DSA00282',
 'DSA00283',
 'DSA00288',
 'DSA00295',
 'DSA00312',
 'DSA00313',
 'DSA00342',
 'DSA00343',
 'DSA00353',
 'DSA00360',
 'DSA00365',
 'DSA00366',
 'DSA00367',
 'DSA00368',
 'DSA00395',
 'DSA00413',
 'DSA00414',
 'DSA00415',
 'DSA00416',
 'DSA00417',
 'DSA00418',
 'DSA00423',
 'DSA00424',
 'DSA00443',
 'DSA00452',
 'DSA00459',
 'DSA00460',
 'DSA00461',
 'DSA00462',
 'DSA00468',
 'DSA00469',
 'DSA00481',
 'DSA00482',
 'DSA00487',
 'DSA00496',
 'DSA00499',
 'DSA00500',
 'DSA00501',
 'DSA00508',
 'DSA00513',
 'DSA00514',
 'DSA00515',
 'DSA00516',
 'DSA00517',
 'DSA00518',
 'DSA00519',
 'DSA00520',
 'DSA00521',
 'DSA00522',
 'DSA00523',
 'DSA00524',
 'DSA00525',
 'DSA00529',
 'DSA00551',
 'DSA00552',
 'DSA00553',
 'DSA00555',
 'DSA00556',
 'DSA00557',
 'DSA00573',
 'DSA00584',
 'DSA00585',
 'DSA00599',
 'DSA00602',
 'DSA00603',
 'DSA00604',
 'DSA00605',
 'DSA00631',
 'DSA00632',
 'DSA00633',
 'DSA00634',
 'DSA00636',
 'DSA00638',
 'DSA00639',
 'DSA00640',
 'DSA00641',
 'DSA00646',
 'DSA00647',
 'DSA00652',
 'DSA00654',
 'DSA00655',
 'DSA00656',
 'DSA00657',
 'DSA00658',
 'DSA00659',
 'DSA00664',
 'DSA00679',
 'DSA00680',
 'DSA00688',
 'DSA00691',
 'DSA00692',
 'DSA00694',
 'DSA00695',
 'DSA00696',
 'DSA00701',
 'DSA00702',
 'DSA00703',
 'DSA00708',
 'DSA00710',
 'DSA00713',
 'DSA00714',
 'DSA00719',
 'DSA00720',
 'DSA00721',
 'DSA00722',
 'DSA00735',
 'DSA00740',
 'DSA00745',
 'DSA00748',
 'DSA00749',
 'DSA00752',
 'DSA00759',
 'DSA00765',
 'DSA00770',
 'DSA00771',
 'DSA00772',
 'DSA00773',
 'DSA00782',
 'DSA00785',
 'DSA00800',
 'DSA00816',
 'DSA00817',
 'DSA00818',
 'DSA00819',
 'DSA00820',
 'DSA00822',
 'DSA00823',
 'DSA00825',
 'DSA00826',
 'DSA00827',
 'DSA00839',
 'DSA00859',
 'DSA00860',
 'DSA00863',
 'DSA00864',
 'DSA00874',
 'DSA00875',
 'DSA00879',
 'DSA00886',
 'DSA00887',
 'DSA00893',
 'DSA00894',
 'DSA00895',
 'DSA00905',
 'DSA00906',
 'DSA00915',
 'DSA00916',
 'DSA00927',
 'DSA00928',
 'DSA00929',
 'DSA00932',
 'DSA00933',
 'DSA00934',
 'DSA00935',
 'DSA00936',
 'DSA00937',
 'DSA00938',
 'DSA00939',
 'DSA00958',
 'DSA00961',
 'DSA00978',
 'DSA00984',
 'DSA00992',
 'DSA00993',
 'DSA00994',
 'DSA01014',
 'DSA01015',
 'DSA01016',
 'DSA01017',
 'DSA01021',
 'DSA01023',
 'DSA01024',
 'DSA01025',
 'DSA01029',
 'DSA01030',
 'DSA01035',
 'DSA01046',
 'DSA01055',
 'DSA01058',
 'DSA01064',
 'DSA01075',
 'DSA01076',
 'DSA01078',
 'DSA01093',
 'DSA01097',
 'DSA01098',
 'DSA01099',
 'DSA01100',
 'DSA01104',
 'DSA01108',
 'DSA01113',
 'DSA01131',
 'DSA01132',
 'DSA01139',
 'DSA01140',
 'DSA01154',
 'DSA01173',
 'DSA01175',
 'DSA01176',
 'DSA01177',
 'DSA01178',
 'DSA01180',
 'DSA01181',
 'DSA01182',
 'DSA01183',
 'DSA01184',
 'DSA01194',
 'DSA01195',
 'DSA01224',
 'DSA01225',
 'DSA01226',
 'DSA01247',
 'DSA01249',
 'DSA01250',
 'DSA01251',
 'DSA01252',
 'DSA01253',
 'DSA01254',
 'DSA01255',
 'DSA01258',
 'DSA01267',
 'DSA01288',
 'DSA01289',
 'DSA01290',
 'DSA01291',
 'DSA01292',
 'DSA01293',
 'DSA01294',
 'DSA01301',
 'DSA01302',
 'DSA01315',
 'DSA01316',
 'DSA01325',
 'DSA01326',
 'DSA01327',
 'DSA01331',
 'DSA01332',
 'DSA01333',
 'DSA01334',
 'DSA01335',
 'DSA01336',
 'DSA01337',
 'DSA01339',
 'DSA01344',
 'DSA01353',
 'DSA01354',
 'DSA01361',
 'DSA01365',
 'DSA01366',
 'DSA01369',
 'DSA01377',
 'DSA01378',
 'DSA01384',
 'DSA01385',
 'DSA01395',
 'DSA01396',
 'DSA01397',
 'DSA01401',
 'DSA01407',
 'DSA01409',
 'DSA01417',
 'DSA01424',
 'DSA01439',
 'DSA01440',
 'DSA01441',
 'DSA01447',
 'DSA01448',
 'DSA01449',
 'DSA01450',
 'DSA01465',
 'DSA01466',
 'DSA01469',
 'DSA01470',
 'DSA01471',
 'DSA01472',
 'DSA01473',
 'DSA01475',
 'DSA01476',
 'DSA01477',
 'DSA01482',
 'DSA01486',
 'DSA01487',
 'DSA01488',
 'DSA01501',
 'DSA01513',
 'DSA01521',
 'DSA01522',
 'DSA01529',
 'DSA01530',
 'DSA01536',
 'DSA01537',
 'DSA01538',
 'DSA01539',
 'DSA01540',
 'DSA01541',
 'DSA01542',
 'DSA01545',
 'DSA01546',
 'DSA01561',
 'DSA01569',
 'DSA01572',
 'DSA01575',
 'DSA01590',
 'DSA01593',
 'DSA01594',
 'DSA01595',
 'DSA01596',
 'DSA01597',
 'DSA01598',
 'DSA01599',
 'DSA01600',
 'DSA01601',
 'DSA01602',
 'DSA01604',
 'DSA01605',
 'DSA01615',
 'DSA01618',
 'DSA01620',
 'DSA01632',
 'DSA01633',
 'DSA01635',
 'DSA01640',
 'DSA01641',
 'DSA01642',
 'DSA01653',
 'DSA01654',
 'DSA01655',
 'DSA01664',
 'DSA01665',
 'DSA01668',
 'DSA01669',
 'DSA01670',
 'DSA01671',
 'DSA01672',
 'DSA01674',
 'DSA01675',
 'DSA01676',
 'DSA01677',
 'DSA01681',
 'DSA01691',
 'DSA01695',
 'DSA01696',
 'DSA01697',
 'DSA01698',
 'DSA01699',
 'DSA01703',
 'DSA01704',
 'DSA01706',
 'DSA01707',
 'DSA01708',
 'DSA01709',
 'DSA01710',
 'DSA01717',
 'DSA01720',
 'DSA01721',
 'DSA01724',
 'DSA01732',
 'DSA01733',
 'DSA01734',
 'DSA01735',
 'DSA01736',
 'DSA01737',
 'DSA01738',
 'DSA01739',
 'DSA01740',
 'DSA01744',
 'DSA01745',
 'DSA01750',
 'DSA01754',
 'DSA01770',
 'DSA01772',
 'DSA01773',
 'DSA01774',
 'DSA01775',
 'DSA01776',
 'DSA01779',
 'DSA01783',
 'DSA01795',
 'DSA01796',
 'DSA01797',
 'DSA01799',
 'DSA01817',
 'DSA01818',
 'DSA01819',
 'DSA01820',
 'DSA01821',
 'DSA01822',
 'DSA01826',
 'DSA01828',
 'DSA01830',
 'DSA01840',
 'DSA01841',
 'DSA01842',
 'DSA01843',
 'DSA01844',
 'DSA01845',
 'DSA01846',
 'DSA01850',
 'DSA01851',
 'DSA01852',
 'DSA01853',
 'DSA01855',
 'DSA01856',
 'DSA01857',
 'DSA01985',
 'DSA02173',
 'DSA02253',
 'DSA02284',
 'DSA02330',
 'DSA02404',
 'DSA02588',
 'DSA02624',
 'DSA02627',
 'DSA02630',
 'DSA02631',
 'DSA02632',
 'DSA02635',
 'DSA02638',
 'DSA02639',
 'DSA02640',
 'DSA02641',
 'DSA02644',
 'DSA02647',
 'DSA02648',
 'DSA02649',
 'DSA02650',
 'DSA02651',
 'DSA02657',
 'DSA02658',
 'DSA02659',
 'DSA02664',
 'DSA02665',
 'DSA02666',
 'DSA02667',
 'DSA02668',
 'DSA02669',
 'DSA02673',
 'DSA02694',
 'DSA02708',
 'DSA02715',
 'DSA02716',
 'DSA02718',
 'DSA02719',
 'DSA02730',
 'DSA02731',
 'DSA02732',
 'DSA02733',
 'DSA02734',
 'DSA02755',
 'DSA02757',
 'DSA02758',
 'DSA02759',
 'DSA02764',
 'DSA02765',
 'DSA02766',
 'DSA02771',
 'DSA02772',
 'DSA02773',
 'DSA02774',
 'DSA02780',
 'DSA02781',
 'DSA02782',
 'DSA02783',
 'DSA02784',
 'DSA02787',
 'DSA02790',
 'DSA02793',
 'DSA02799',
 'DSA02805',
 'DSA02817',
 'DSA02818',
 'DSA02821',
 'DSA02822',
 'DSA02823',
 'DSA02824',
 'DSA02825',
 'DSA02826',
 'DSA02827',
 'DSA02828',
 'DSA02829',
 'DSA02832',
 'DSA02833',
 'DSA02834',
 'DSA02835',
 'DSA02839',
 'DSA02840',
 'DSA02849',
 'DSA02850',
 'DSA02851',
 'DSA02852',
 'DSA02853',
 'DSA02854',
 'DSA02860',
 'DSA02867',
 'DSA02868',
 'DSA02874',
 'DSA02875',
 'DSA02876',
 'DSA02877',
 'DSA02878',
 'DSA02886',
 'DSA02887',
 'DSA02891',
 'DSA02893',
 'DSA02894',
 'DSA02898',
 'DSA02914',
 'DSA02915',
 'DSA02916',
 'DSA02921',
 'DSA02924',
 'DSA02925',
 'DSA02938',
 'DSA02939',
 'DSA02943',
 'DSA02944',
 'DSA02945',
 'DSA02950',
 'DSA02951',
 'DSA02952',
 'DSA02953',
 'DSA02954',
 'DSA02955',
 'DSA02977',
 'DSA02978',
 'DSA02984',
 'DSA02985',
 'DSA02986',
 'DSA02990',
 'DSA02994',
 'DSA02996',
 'DSA02997',
 'DSA02998',
 'DSA02999',
 'DSA03000',
 'DSA03001',
 'DSA03006',
 'DSA03008',
 'DSA03009',
 'DSA03010',
 'DSA03011',
 'DSA03015',
 'DSA03020',
 'DSA03022',
 'DSA03023',
 'DSA03024',
 'DSA03025',
 'DSA03026',
 'DSA03027',
 'DSA03028',
 'DSA03029',
 'DSA03033',
 'DSA03034',
 'DSA03042',
 'DSA03046',
 'DSA03047',
 'DSA03048',
 'DSA03054',
 'DSA03065',
 'DSA03084',
 'DSA03085',
 'DSA03104',
 'DSA03114',
 'DSA03115',
 'DSA03116',
 'DSA03117',
 'DSA03118',
 'DSA03119',
 'DSA03122',
 'DSA03123',
 'DSA03124',
 'DSA03128',
 'DSA03129',
 'DSA03133',
 'DSA03134',
 'DSA03135',
 'DSA03136',
 'DSA03137',
 'DSA03138',
 'DSA03139',
 'DSA03140',
 'DSA03141',
 'DSA03144',
 'DSA03147',
 'DSA03148',
 'DSA03149',
 'DSA03150',
 'DSA03162',
 'DSA03163',
 'DSA03167',
 'DSA03168',
 'DSA03186',
 'DSA03187',
 'DSA03191',
 'DSA03192',
 'DSA03193',
 'DSA03194',
 'DSA03196',
 'DSA03197',
 'DSA03198',
 'DSA03200',
 'DSA03206',
 'DSA03211',
 'DSA03212',
 'DSA03213',
 'DSA03214',
 'DSA03215',
 'DSA03217',
 'DSA03218',
 'DSA03229',
 'DSA03230',
 'DSA03231',
 'DSA03237',
 'DSA03544',
 'DSA03624',
 'DSA03668',
 'DSA03767',
 'DSA03769',
 'DSA03770',
 'DSA03775',
 'DSA03776',
 'DSA03783',
 'DSA03786',
 'DSA03788',
 'DSA03789',
 'DSA03791',
 'DSA03792',
 'DSA03794',
 'DSA03795',
 'DSA03797',
 'DSA03798',
 'DSA03800',
 'DSA03802',
 'DSA03806',
 'DSA03807',
 'DSA03808',
 'DSA03809',
 'DSA03810',
 'DSA03811',
 'DSA03812',
 'DSA03813',
 'DSA03829',
 'DSA03831',
 'DSA03832',
 'DSA03838',
 'DSA03839',
 'DSA03840',
 'DSA03841',
 'DSA03853',
 'DSA03857',
 'DSA03874',
 'DSA03878',
 'DSA03883',
 'DSA03884',
 'DSA03885',
 'DSA03886',
 'DSA03893',
 'DSA03894',
 'DSA03895',
 'DSA03896',
 'DSA03897',
 'DSA03902',
 'DSA03903',
 'DSA03904',
 'DSA03923',
 'DSA03924',
 'DSA03925',
 'DSA03940',
 'DSA03945',
 'DSA03946',
 'DSA03947',
 'DSA03948',
 'DSA03949',
 'DSA03950',
 'DSA03955',
 'DSA03959',
 'DSA03961',
 'DSA03975',
 'DSA03986',
 'DSA03987',
 'DSA04017',
 'DSA04031',
 'DSA04032',
 'DSA04033',
 'DSA04034',
 'DSA04035',
 'DSA04036',
 'DSA04037',
 'DSA04038',
 'DSA04039',
 'DSA04052',
 'DSA04060',
 'DSA04061',
 'DSA04062',
 'DSA04071',
 'DSA04076',
 'DSA04077',
 'DSA04078',
 'DSA04079',
 'DSA04080',
 'DSA04082',
 'DSA04083',
 'DSA04085',
 'DSA04098',
 'DSA04099',
 'DSA04102',
 'DSA04103',
 'DSA04104',
 'DSA04105',
 'DSA04106',
 'DSA04107',
 'DSA04108',
 'DSA04134',
 'DSA04139',
 'DSA04148',
 'DSA04149',
 'DSA04158',
 'DSA04196',
 'DSA04197',
 'DSA04198',
 'DSA04199',
 'DSA04202',
 'DSA04204',
 'DSA04234',
 'DSA04235',
 'DSA04251',
 'DSA04254',
 'DSA04255',
 'DSA04256',
 'DSA04257',
 'DSA04258',
 'DSA04276',
 'DSA04277',
 'DSA04278',
 'DSA04279',
 'DSA04280',
 'DSA04299',
 'DSA04300',
 'DSA04301',
 'DSA04304',
 'DSA04305',
 'DSA04306',
 'DSA04308',
 'DSA04309',
 'DSA04310',
 'DSA04311',
 'DSA04312',
 'DSA04313',
 'DSA04314',
 'DSA04317',
 'DSA04318',
 'DSA04319',
 'DSA04322',
 'DSA04324',
 'DSA04343',
 'DSA04346',
 'DSA04351',
 'DSA04352',
 'DSA04356',
 'DSA04364',
 'DSA04369',
 'DSA04373',
 'DSA04376',
 'DSA04384',
 'DSA04385',
 'DSA04386',
 'DSA04387',
 'DSA04398',
 'DSA04399',
 'DSA04400',
 'DSA04401',
 'DSA04402',
 'DSA04403',
 'DSA04404',
 'DSA04405',
 'DSA04420',
 'DSA04421',
 'DSA04428',
 'DSA04449',
 'DSA04450',
 'DSA04475',
 'DSA04476',
 'DSA04480',
 'DSA04500',
 'DSA04503',
 'DSA04527',
 'DSA04574',
 'DSA04592',
 'DSA04593',
 'DSA04627',
 'DSA04632',
 'DSA04656',
 'DSA04673',
 'DSA04678',
 'DSA04679',
 'DSA04680',
 'DSA04683',
 'DSA04805',
 'DSA04811',
 'DSA04812',
 'DSA04837',
 'DSA04838',
 'DSA04840',
 'DSA04843',
 'DSA04844',
 'DSA04848',
 'DSA04849',
 'DSA04854',
 'DSA04855',
 'DSA04863',
 'DSA04870',
 'DSA04871',
 'DSA04873',
 'DSA04894',
 'DSA04895',
 'DSA04896',
 'DSA04915',
 'DSA04916',
 'DSA04917',
 'DSA04930',
 'DSA04931',
 'DSA04932',
 'DSA04933',
 'DSA05025',
 'DSA05042',
 'DSA05043',
 'DSA05045',
 'DSA05046',
 'DSA05047',
 'DSA05049',
 'DSA05050',
 'DSA05051',
 'DSA05052',
 'DSA05053',
 'DSA05054',
 'DSA05058',
 'DSA05059',
 'DSA05060',
 'DSA05061',
 'DSA05062',
 'DSA05063',
 'DSA05064',
 'DSA05065',
 'DSA05070',
 'DSA05072',
 'DSA05073',
 'DSA05074',
 'DSA05075',
 'DSA05076',
 'DSA05094',
 'DSA05095',
 'DSA05096',
 'DSA05111',
 'DSA05137',
 'DSA05138',
 'DSA05139',
 'DSA05140',
 'DSA05145',
 'DSA05146',
 'DSA05147',
 'DSA05149',
 'DSA05151',
 'DSA05162',
 'DSA05164',
 'DSA05165',
 'DSA05172',
 'DSA05173',
 'DSA05176',
 'DSA05181',
 'DSA05182',
 'DSA05183',
 'DSA05185',
 'DSA05186',
 'DSA05187',
 'DSA05191',
 'DSA05197',
 'DSA05199',
 'DSA05200',
 'DSA05201',
 'DSA05205',
 'DSA05206',
 'DSA05208',
 'DSA05209',
 'DSA05210',
 'DSA05211',
 'DSA05212',
 'DSA05213',
 'DSA05214',
 'DSA05215',
 'DSA05216',
 'DSA05217',
 'DSA05220',
 'DSA05221',
 'DSA05222',
 'DSA05225',
 'DSA05226',
 'DSA05249',
 'DSA05250',
 'DSA05276',
 'DSA05281',
 'DSA05282',
 'DSA05283',
 'DSA05292',
 'DSA05295',
 'DSA05296',
 'DSA05297',
 'DSA05301',
 'DSA05308',
 'DSA05309',
 'DSA05310',
 'DSA05313',
 'DSA05314',
 'DSA05315',
 'DSA05322',
 'DSA05323',
 'DSA05324',
 'DSA05326',
 'DSA05327',
 'DSA05330',
 'DSA05331',
 'DSA05332',
 'DSA05349',
 'DSA05354',
 'DSA05360',
 'DSA05361',
 'DSA05368',
 'DSA05369',
 'DSA05370',
 'DSA05377',
 'DSA05378',
 'DSA05385',
 'DSA05392',
 'DSA05393',
 'DSA05394',
 'DSA05395',
 'DSA05396',
 'DSA05397',
 'DSA05406',
 'DSA05407',
 'DSA05408',
 'DSA05410',
 'DSA05411',
 'DSA05412',
 'DSA05414',
 ...]

In [ ]:
df_2