## HAMBURGUER RESTAURANTS WEB SCRAPPING EXERCISES

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import geopandas as gpd
#--- The followinf packages are used for geospatial analysis
from utils import * #We import our geocoding function-get_coord-from utils.py
from cred_google_Template import MY_API_KEY #The file in which we have our API key
import requests 
from tqdm import tqdm  
from bs4 import BeautifulSoup 
import json
import ast
import time 
import random

## 1. Create the dataFrames:

## Data Cleansing 1rst step: GoogleMapsScrapper

In [2]:
#Firs we create the dataframes associated with googleMapsScrapper
bucaramanga_googleMapsScrapper = read_GoogleMapsScrapper('resultados_googleMapsScrapper/bucaramanga_hamburguesas.xlsx')
floridablanca_googleMapsScrapper = read_GoogleMapsScrapper('resultados_googleMapsScrapper/floridablanca_hamburguesas.xlsx')
giron_googleMapsScrapper = read_GoogleMapsScrapper('resultados_googleMapsScrapper/giron_hamburguesas.xlsx')
piedecuesta_googleMapsScrapper = read_GoogleMapsScrapper('resultados_googleMapsScrapper/Piedecuesta_hamburguesas.xlsx')

In [3]:
#Let's visualize the content for every dataFrame
bucaramanga_googleMapsScrapper.tail()

,Name (20),Category,Rating,Nº Reviews,User,Stars,User Comment,Hours,Description,Plus Code,...,Longitude,Url in Maps,Iframe,Image Url,ORIGINAL KW,CID,id,Day N.,Saved,hash
91,Alquimia Burgeria,Hamburguesería,"4,6",156.000,Gui Occam (XanaX),5.0,Simplemente ¡Delicioso!\n\nLas salsas son espe...,"domingo, 12a2:30 PM, 5:45a10 PM; lunes, 5:30a1...",NaN,"4V2P+VG Bucaramanga, Santander",...,-73.113665,https://maps.app.goo.gl/JBhfQ87RbJf6cna99,"<iframe src=""https://www.google.com/maps/embed...",https://lh5.googleusercontent.com/p/AF1QipMomL...,"hamburgueserias en Bucaramanga, Santander,Colo...",17735122329442247169,91,0,0,NaN
92,Comidas Rapidas The Gordo,Restaurante de comida rápida,"4,2",79.000,Angel Ardila,2.0,La calidad del producto bajo mucho la comida s...,"domingo, 4:30 AMa12 PM; lunes, 4:30 AMa12 PM; ...",NaN,"4VPC+7X Bucaramanga, Santander",...,-73.127527,https://maps.app.goo.gl/xZQ8Z2yfsnCTs6Yz8,"<iframe src=""https://www.google.com/maps/embed...",https://lh5.googleusercontent.com/p/AF1QipMNC6...,"hamburgueserias en Bucaramanga, Santander,Colo...",18030534595666215964,92,0,0,NaN
93,CHOPE&apos;S,Restaurante,"4,5",2.039,Andres D García,3.0,"Empezando por lo bueno, fui con un grupo grand...","domingo, 12a10 PM; lunes, 12a10 PM; martes, 12...",NaN,"4V7R+74 Bucaramanga, Santander",...,-73.109717,https://maps.app.goo.gl/c8r11ciPyzwgigVNA,"<iframe src=""https://www.google.com/maps/embed...",https://lh5.googleusercontent.com/p/AF1QipOvyz...,"hamburgueserias en Bucaramanga, Santander,Colo...",14727530354292560980,93,0,0,NaN
94,Donde Nahún,Restaurante de comida rápida,"4,4",289.000,KEDWIN MAURICIO JIMENEZ,4.0,"Un sitio agradable, se ve que está recién remo...","domingo, 4:30a11:15 PM; lunes, 4:30a11:15 PM; ...",NaN,"4V9H+6P Bucaramanga, Santander",...,-73.120653,https://maps.app.goo.gl/utpPXDKBzk3d12zn9,"<iframe src=""https://www.google.com/maps/embed...",https://lh5.googleusercontent.com/p/AF1QipOMgC...,"hamburgueserias en Bucaramanga, Santander,Colo...",17501424792840023590,94,0,0,NaN
95,Búnker la salle,Hamburguesería,"4,3",35.000,Fabio Andrey Sanchez Quintero,5.0,Muy deliciosa la comida y la atención al clien...,"domingo, 5 PMa12 AM; lunes, 5 PMa12 AM; martes...",NaN,"4V2P+WM Bucaramanga, Santander",...,-73.113300,https://maps.app.goo.gl/WJuT7BsqY2Gdu9WS6,"<iframe src=""https://www.google.com/maps/embed...",https://lh5.googleusercontent.com/p/AF1QipNAB2...,"hamburgueserias en Bucaramanga, Santander,Colo...",18029364851116086947,95,0,0,NaN

In [4]:
bucaramanga_googleMapsScrapper.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 28 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name (20)     96 non-null     object
 1   Category      94 non-null     object
 2   Rating        91 non-null     object
 3   Nº Reviews    91 non-null     float64
 4   User          90 non-null     object
 5   Stars         90 non-null     float64
 6   User Comment  90 non-null     object
 7   Hours         88 non-null     object
 8   Description   0 non-null      float64
 9   Plus Code     93 non-null     object
 10  Address       96 non-null     object
 11  City          96 non-null     object
 12  Province      96 non-null     object
 13  Url           40 non-null     object
 14  Telephone     92 non-null     object
 15  email         0 non-null      float64
 16  Claim         96 non-null     object
 17  Latitude      96 non-null     float64
 18  Longitude     96 non-null     float64
 19  Url in Maps   94 non-null     object
 20  Iframe        94 non-null     object
 21  Image Url     96 non-null     object
 22  ORIGINAL KW   96 non-null     object
 23  CID           96 non-null     uint64
 24  id            96 non-null     int64
 25  Day N.        96 non-null     int64
 26  Saved         96 non-null     int64
 27  hash          0 non-null      float64
dtypes: float64(7), int64(3), object(17), uint64(1)
memory usage: 21.1+ KB

In [5]:
floridablanca_googleMapsScrapper.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 28 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name (2)      185 non-null    object
 1   Category      180 non-null    object
 2   Rating        179 non-null    object
 3   Nº Reviews    179 non-null    float64
 4   User          181 non-null    object
 5   Stars         181 non-null    float64
 6   User Comment  181 non-null    object
 7   Hours         155 non-null    object
 8   Description   0 non-null      float64
 9   Plus Code     180 non-null    object
 10  Address       185 non-null    object
 11  City          185 non-null    object
 12  Province      185 non-null    object
 13  Url           52 non-null     object
 14  Telephone     172 non-null    object
 15  email         0 non-null      float64
 16  Claim         185 non-null    object
 17  Latitude      185 non-null    float64
 18  Longitude     185 non-null    float64
 19  Url in Maps   180 non-null    object
 20  Iframe        180 non-null    object
 21  Image Url     185 non-null    object
 22  ORIGINAL KW   185 non-null    object
 23  CID           185 non-null    uint64
 24  id            185 non-null    int64
 25  Day N.        185 non-null    int64
 26  Saved         185 non-null    int64
 27  hash          0 non-null      float64
dtypes: float64(7), int64(3), object(17), uint64(1)
memory usage: 40.6+ KB

In [6]:
giron_googleMapsScrapper.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 28 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name (97)     170 non-null    object
 1   Category      163 non-null    object
 2   Rating        159 non-null    object
 3   Nº Reviews    159 non-null    float64
 4   User          162 non-null    object
 5   Stars         162 non-null    float64
 6   User Comment  162 non-null    object
 7   Hours         154 non-null    object
 8   Description   0 non-null      float64
 9   Plus Code     163 non-null    object
 10  Address       170 non-null    object
 11  City          170 non-null    object
 12  Province      170 non-null    object
 13  Url           32 non-null     object
 14  Telephone     160 non-null    object
 15  email         0 non-null      float64
 16  Claim         170 non-null    object
 17  Latitude      170 non-null    float64
 18  Longitude     170 non-null    float64
 19  Url in Maps   163 non-null    object
 20  Iframe        163 non-null    object
 21  Image Url     169 non-null    object
 22  ORIGINAL KW   170 non-null    object
 23  CID           170 non-null    uint64
 24  id            170 non-null    int64
 25  Day N.        170 non-null    int64
 26  Saved         170 non-null    int64
 27  hash          0 non-null      float64
dtypes: float64(7), int64(3), object(17), uint64(1)
memory usage: 37.3+ KB

In [7]:
piedecuesta_googleMapsScrapper.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 28 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          177 non-null    object
 1   Category      177 non-null    object
 2   Rating        173 non-null    object
 3   Nº Reviews    0 non-null      float64
 4   User          171 non-null    object
 5   Stars         171 non-null    float64
 6   User Comment  171 non-null    object
 7   Hours         161 non-null    object
 8   Description   0 non-null      float64
 9   Plus Code     173 non-null    object
 10  Address       175 non-null    object
 11  City          177 non-null    object
 12  Province      175 non-null    object
 13  Url           62 non-null     object
 14  Telephone     161 non-null    object
 15  email         0 non-null      float64
 16  Claim         177 non-null    object
 17  Latitude      177 non-null    float64
 18  Longitude     177 non-null    float64
 19  Url in Maps   177 non-null    object
 20  Iframe        177 non-null    object
 21  Image Url     176 non-null    object
 22  ORIGINAL KW   177 non-null    object
 23  CID           177 non-null    uint64
 24  id            177 non-null    int64
 25  Day N.        177 non-null    int64
 26  Saved         177 non-null    int64
 27  hash          0 non-null      float64
dtypes: float64(7), int64(3), object(17), uint64(1)
memory usage: 38.8+ KB

See what is whappening? each one of the googleMapsScrapper's dataFrames has a differente name for the 'Name' column: if we don't change this, the concatenation process will result in a wrong value

In [8]:
#for every single one of the previous dataframes, change the name of the column with 'NAME' to 'NAME'
bucaramanga_googleMapsScrapper.rename(columns={'Name (20)':'name'}, inplace=True)
floridablanca_googleMapsScrapper.rename(columns={'Name (2)':'name'}, inplace=True)
giron_googleMapsScrapper.rename(columns={'Name (97)':'name'}, inplace=True)
piedecuesta_googleMapsScrapper.rename(columns={'Name':'name'}, inplace=True)

In [9]:
#The 4 dataFrames have exactly the same structure: let's merge them into a single dataFrame called amb_googleMapsScrapper:
amb_googleMapsScrapper = pd.concat([bucaramanga_googleMapsScrapper, floridablanca_googleMapsScrapper, giron_googleMapsScrapper, piedecuesta_googleMapsScrapper], ignore_index=True)

In [10]:
#Let's visualize this resulting dataFrame:
amb_googleMapsScrapper.tail()

,name,Category,Rating,Nº Reviews,User,Stars,User Comment,Hours,Description,Plus Code,...,Longitude,Url in Maps,Iframe,Image Url,ORIGINAL KW,CID,id,Day N.,Saved,hash
623,Aoki Sushi Rolls Piedecuesta,Restaurante japonés,"4,6",NaN,Miguel Gallardo,5.0,"Excelente Sabor y Variedad de productos, muy b...","jueves, 5a11 PM; viernes, 5a11 PM; sábado, 12a...",NaN,"2W2W+Q8 Piedecuesta, Santander",...,-73.054164,https://maps.app.goo.gl/pM9gkH39ccCBoXHA6,"<iframe src=""https://www.google.com/maps/embed...",https://lh5.googleusercontent.com/p/AF1QipPqxQ...,"hamburgueserias en Piedecuesta, Santander,Colo...",10521077328624489584,93,4,0,NaN
624,Aoki Sushi Rolls Piedecuesta,Restaurante japonés,"4,6",NaN,Ygdabel Martínez,5.0,"Ambiente calido, buena musica y una super aten...","jueves, 5a11 PM; viernes, 5a11 PM; sábado, 12a...",NaN,"2W2W+Q8 Piedecuesta, Santander",...,-73.054164,https://maps.app.goo.gl/pM9gkH39ccCBoXHA6,"<iframe src=""https://www.google.com/maps/embed...",https://lh5.googleusercontent.com/p/AF1QipPqxQ...,"hamburgueserias en Piedecuesta, Santander,Colo...",10521077328624489584,93,4,0,NaN
625,Asadero Super Kali,Restaurante,"4,2",NaN,Williams Moreno,5.0,El pollo siempre fresco y jugoso. La sopa muy ...,"jueves, 10:30 AMa9:30 PM; viernes, 10:30 AMa9:...",NaN,"XWXW+VJ Piedecuesta, Santander",...,-73.053459,https://maps.app.goo.gl/MJaP4WYgkKr45L7m6,"<iframe src=""https://www.google.com/maps/embed...",https://lh5.googleusercontent.com/p/AF1QipMheu...,"hamburgueserias en Piedecuesta, Santander,Colo...",17376116562636499163,94,4,0,NaN
626,Asadero Super Kali,Restaurante,"4,2",NaN,ANDREA CAROLINA RUIZ BADILLO,5.0,En este excelente restaurante podemos disfruta...,"jueves, 10:30 AMa9:30 PM; viernes, 10:30 AMa9:...",NaN,"XWXW+VJ Piedecuesta, Santander",...,-73.053459,https://maps.app.goo.gl/MJaP4WYgkKr45L7m6,"<iframe src=""https://www.google.com/maps/embed...",https://lh5.googleusercontent.com/p/AF1QipMheu...,"hamburgueserias en Piedecuesta, Santander,Colo...",17376116562636499163,94,4,0,NaN
627,La hamburguesería,Hamburguesería,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"WXX4+6M Piedecuesta, Santander",...,-73.043300,https://maps.app.goo.gl/QH4bnLony1puWDWq7,"<iframe src=""https://www.google.com/maps/embed...",NaN,"hamburgueserias en Piedecuesta, Santander,Colo...",16806474301662761919,95,4,0,NaN

In [11]:
#let's delete the columns: 'User', 'Description', 'Telephone', 'email', 'Claim', 'Iframe', 'Image Url', 'ORIGINAL KW', 'CID', 'id', 'Day N.', 'Saved', 'hash' for amb_googleMapsScrapper
amb_googleMapsScrapper.drop(['User', 'Description', 'Telephone', 'email', 'Claim', 'Iframe', 'Image Url', 'ORIGINAL KW', 'CID', 'id', 'Day N.', 'Saved', 'hash'], axis=1, inplace=True)

In [12]:
#Do not forget to reset_index on the resulting dataFrame:
amb_googleMapsScrapper.reset_index(drop=True, inplace=True)
#Now let's visualize the 5 last rows:
amb_googleMapsScrapper.tail()

,name,Category,Rating,Nº Reviews,Stars,User Comment,Hours,Plus Code,Address,City,Province,Url,Latitude,Longitude,Url in Maps
623,Aoki Sushi Rolls Piedecuesta,Restaurante japonés,"4,6",NaN,5.0,"Excelente Sabor y Variedad de productos, muy b...","jueves, 5a11 PM; viernes, 5a11 PM; sábado, 12a...","2W2W+Q8 Piedecuesta, Santander","Cra 15, Av. 10ª N #7BN-15, Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,7.001967,-73.054164,https://maps.app.goo.gl/pM9gkH39ccCBoXHA6
624,Aoki Sushi Rolls Piedecuesta,Restaurante japonés,"4,6",NaN,5.0,"Ambiente calido, buena musica y una super aten...","jueves, 5a11 PM; viernes, 5a11 PM; sábado, 12a...","2W2W+Q8 Piedecuesta, Santander","Cra 15, Av. 10ª N #7BN-15, Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,7.001967,-73.054164,https://maps.app.goo.gl/pM9gkH39ccCBoXHA6
625,Asadero Super Kali,Restaurante,"4,2",NaN,5.0,El pollo siempre fresco y jugoso. La sopa muy ...,"jueves, 10:30 AMa9:30 PM; viernes, 10:30 AMa9:...","XWXW+VJ Piedecuesta, Santander","Cra 15 #2N-02, Piedecuesta, Santander","Piedecuesta, Santander",Santander,https://www.gurugo.co/empresas/asadero-super-k...,6.999699,-73.053459,https://maps.app.goo.gl/MJaP4WYgkKr45L7m6
626,Asadero Super Kali,Restaurante,"4,2",NaN,5.0,En este excelente restaurante podemos disfruta...,"jueves, 10:30 AMa9:30 PM; viernes, 10:30 AMa9:...","XWXW+VJ Piedecuesta, Santander","Cra 15 #2N-02, Piedecuesta, Santander","Piedecuesta, Santander",Santander,https://www.gurugo.co/empresas/asadero-super-k...,6.999699,-73.053459,https://maps.app.goo.gl/MJaP4WYgkKr45L7m6
627,La hamburguesería,Hamburguesería,NaN,NaN,NaN,NaN,NaN,"WXX4+6M Piedecuesta, Santander","Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,6.948116,-73.043300,https://maps.app.goo.gl/QH4bnLony1puWDWq7

In [13]:
#Let's see what columns are left in a variable called columns_left
columns_left = amb_googleMapsScrapper.columns
print(columns_left)
#Now let's visualize the 5 last rows:
amb_googleMapsScrapper.tail()

Index(['name', 'Category', 'Rating', 'Nº Reviews', 'Stars', 'User Comment',
       'Hours', 'Plus Code', 'Address', 'City', 'Province', 'Url', 'Latitude',
       'Longitude', 'Url in Maps'],
      dtype='object')

,name,Category,Rating,Nº Reviews,Stars,User Comment,Hours,Plus Code,Address,City,Province,Url,Latitude,Longitude,Url in Maps
623,Aoki Sushi Rolls Piedecuesta,Restaurante japonés,"4,6",NaN,5.0,"Excelente Sabor y Variedad de productos, muy b...","jueves, 5a11 PM; viernes, 5a11 PM; sábado, 12a...","2W2W+Q8 Piedecuesta, Santander","Cra 15, Av. 10ª N #7BN-15, Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,7.001967,-73.054164,https://maps.app.goo.gl/pM9gkH39ccCBoXHA6
624,Aoki Sushi Rolls Piedecuesta,Restaurante japonés,"4,6",NaN,5.0,"Ambiente calido, buena musica y una super aten...","jueves, 5a11 PM; viernes, 5a11 PM; sábado, 12a...","2W2W+Q8 Piedecuesta, Santander","Cra 15, Av. 10ª N #7BN-15, Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,7.001967,-73.054164,https://maps.app.goo.gl/pM9gkH39ccCBoXHA6
625,Asadero Super Kali,Restaurante,"4,2",NaN,5.0,El pollo siempre fresco y jugoso. La sopa muy ...,"jueves, 10:30 AMa9:30 PM; viernes, 10:30 AMa9:...","XWXW+VJ Piedecuesta, Santander","Cra 15 #2N-02, Piedecuesta, Santander","Piedecuesta, Santander",Santander,https://www.gurugo.co/empresas/asadero-super-k...,6.999699,-73.053459,https://maps.app.goo.gl/MJaP4WYgkKr45L7m6
626,Asadero Super Kali,Restaurante,"4,2",NaN,5.0,En este excelente restaurante podemos disfruta...,"jueves, 10:30 AMa9:30 PM; viernes, 10:30 AMa9:...","XWXW+VJ Piedecuesta, Santander","Cra 15 #2N-02, Piedecuesta, Santander","Piedecuesta, Santander",Santander,https://www.gurugo.co/empresas/asadero-super-k...,6.999699,-73.053459,https://maps.app.goo.gl/MJaP4WYgkKr45L7m6
627,La hamburguesería,Hamburguesería,NaN,NaN,NaN,NaN,NaN,"WXX4+6M Piedecuesta, Santander","Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,6.948116,-73.043300,https://maps.app.goo.gl/QH4bnLony1puWDWq7

In [14]:
#Now let's visualize the 5 last rows:
amb_googleMapsScrapper.tail()

,name,Category,Rating,Nº Reviews,Stars,User Comment,Hours,Plus Code,Address,City,Province,Url,Latitude,Longitude,Url in Maps
623,Aoki Sushi Rolls Piedecuesta,Restaurante japonés,"4,6",NaN,5.0,"Excelente Sabor y Variedad de productos, muy b...","jueves, 5a11 PM; viernes, 5a11 PM; sábado, 12a...","2W2W+Q8 Piedecuesta, Santander","Cra 15, Av. 10ª N #7BN-15, Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,7.001967,-73.054164,https://maps.app.goo.gl/pM9gkH39ccCBoXHA6
624,Aoki Sushi Rolls Piedecuesta,Restaurante japonés,"4,6",NaN,5.0,"Ambiente calido, buena musica y una super aten...","jueves, 5a11 PM; viernes, 5a11 PM; sábado, 12a...","2W2W+Q8 Piedecuesta, Santander","Cra 15, Av. 10ª N #7BN-15, Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,7.001967,-73.054164,https://maps.app.goo.gl/pM9gkH39ccCBoXHA6
625,Asadero Super Kali,Restaurante,"4,2",NaN,5.0,El pollo siempre fresco y jugoso. La sopa muy ...,"jueves, 10:30 AMa9:30 PM; viernes, 10:30 AMa9:...","XWXW+VJ Piedecuesta, Santander","Cra 15 #2N-02, Piedecuesta, Santander","Piedecuesta, Santander",Santander,https://www.gurugo.co/empresas/asadero-super-k...,6.999699,-73.053459,https://maps.app.goo.gl/MJaP4WYgkKr45L7m6
626,Asadero Super Kali,Restaurante,"4,2",NaN,5.0,En este excelente restaurante podemos disfruta...,"jueves, 10:30 AMa9:30 PM; viernes, 10:30 AMa9:...","XWXW+VJ Piedecuesta, Santander","Cra 15 #2N-02, Piedecuesta, Santander","Piedecuesta, Santander",Santander,https://www.gurugo.co/empresas/asadero-super-k...,6.999699,-73.053459,https://maps.app.goo.gl/MJaP4WYgkKr45L7m6
627,La hamburguesería,Hamburguesería,NaN,NaN,NaN,NaN,NaN,"WXX4+6M Piedecuesta, Santander","Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,6.948116,-73.043300,https://maps.app.goo.gl/QH4bnLony1puWDWq7

In [15]:
#Now let's drop duplicates based on these 3 columns: latitude, longitude and Address
amb_googleMapsScrapper.drop_duplicates(subset=['Latitude', 'Longitude', 'Address'], inplace=True)
#let's reset the index
amb_googleMapsScrapper.reset_index(drop=True, inplace=True)
#Now let's visualize the 5 last wors
amb_googleMapsScrapper.tail()

,name,Category,Rating,Nº Reviews,Stars,User Comment,Hours,Plus Code,Address,City,Province,Url,Latitude,Longitude,Url in Maps
372,Restaurante Bar la Playa,Restaurante,"4,0",NaN,1.0,Definitivamente no volvería ni aunque me vuelv...,"jueves, 6 AMa10 PM; viernes, 6 AMa10 PM; sábad...","XXC5+79 Piedecuesta, Santander","6.969098,-73.041713, Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,6.970722,-73.041509,https://maps.app.goo.gl/xjaWmCSCy7SU8utv6
373,Pizza Cartoon y Panzerotti,Restaurante,"4,3",NaN,1.0,pedi una pizza mediana que se supone traia 5 p...,"jueves, 4 PMa12 AM; viernes, 4 PMa12 AM; sábad...","XWWV+QG Piedecuesta, Santander","Transversal 1D # 7a-14, La Argentina, Piedecue...","Piedecuesta, Santander",Santander,NaN,6.996958,-73.056191,https://maps.app.goo.gl/NM7KozQ1AyVwmXZh8
374,Aoki Sushi Rolls Piedecuesta,Restaurante japonés,"4,6",NaN,5.0,"Excelente Sabor y Variedad de productos, muy b...","jueves, 5a11 PM; viernes, 5a11 PM; sábado, 12a...","2W2W+Q8 Piedecuesta, Santander","Cra 15, Av. 10ª N #7BN-15, Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,7.001967,-73.054164,https://maps.app.goo.gl/pM9gkH39ccCBoXHA6
375,Asadero Super Kali,Restaurante,"4,2",NaN,5.0,El pollo siempre fresco y jugoso. La sopa muy ...,"jueves, 10:30 AMa9:30 PM; viernes, 10:30 AMa9:...","XWXW+VJ Piedecuesta, Santander","Cra 15 #2N-02, Piedecuesta, Santander","Piedecuesta, Santander",Santander,https://www.gurugo.co/empresas/asadero-super-k...,6.999699,-73.053459,https://maps.app.goo.gl/MJaP4WYgkKr45L7m6
376,La hamburguesería,Hamburguesería,NaN,NaN,NaN,NaN,NaN,"WXX4+6M Piedecuesta, Santander","Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,6.948116,-73.043300,https://maps.app.goo.gl/QH4bnLony1puWDWq7

In [16]:
amb_googleMapsScrapper.columns

Index(['name', 'Category', 'Rating', 'Nº Reviews', 'Stars', 'User Comment',
       'Hours', 'Plus Code', 'Address', 'City', 'Province', 'Url', 'Latitude',
       'Longitude', 'Url in Maps'],
      dtype='object')

In [17]:
#let's remove rows based on Nan values: if there is at least a Nan values in one of these columns, the row will be removed: ['Rating', 'Nº Reviews', 'Stars']
amb_googleMapsScrapper.dropna(how='all', inplace=True) #We'd like to keep the majority of restaurants: only rows with all NaN values will be removed
#do not forget to reset the index
amb_googleMapsScrapper.reset_index(drop=True, inplace=True)
#Now let's visualize the 5 last rows
amb_googleMapsScrapper.tail()

,name,Category,Rating,Nº Reviews,Stars,User Comment,Hours,Plus Code,Address,City,Province,Url,Latitude,Longitude,Url in Maps
372,Restaurante Bar la Playa,Restaurante,"4,0",NaN,1.0,Definitivamente no volvería ni aunque me vuelv...,"jueves, 6 AMa10 PM; viernes, 6 AMa10 PM; sábad...","XXC5+79 Piedecuesta, Santander","6.969098,-73.041713, Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,6.970722,-73.041509,https://maps.app.goo.gl/xjaWmCSCy7SU8utv6
373,Pizza Cartoon y Panzerotti,Restaurante,"4,3",NaN,1.0,pedi una pizza mediana que se supone traia 5 p...,"jueves, 4 PMa12 AM; viernes, 4 PMa12 AM; sábad...","XWWV+QG Piedecuesta, Santander","Transversal 1D # 7a-14, La Argentina, Piedecue...","Piedecuesta, Santander",Santander,NaN,6.996958,-73.056191,https://maps.app.goo.gl/NM7KozQ1AyVwmXZh8
374,Aoki Sushi Rolls Piedecuesta,Restaurante japonés,"4,6",NaN,5.0,"Excelente Sabor y Variedad de productos, muy b...","jueves, 5a11 PM; viernes, 5a11 PM; sábado, 12a...","2W2W+Q8 Piedecuesta, Santander","Cra 15, Av. 10ª N #7BN-15, Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,7.001967,-73.054164,https://maps.app.goo.gl/pM9gkH39ccCBoXHA6
375,Asadero Super Kali,Restaurante,"4,2",NaN,5.0,El pollo siempre fresco y jugoso. La sopa muy ...,"jueves, 10:30 AMa9:30 PM; viernes, 10:30 AMa9:...","XWXW+VJ Piedecuesta, Santander","Cra 15 #2N-02, Piedecuesta, Santander","Piedecuesta, Santander",Santander,https://www.gurugo.co/empresas/asadero-super-k...,6.999699,-73.053459,https://maps.app.goo.gl/MJaP4WYgkKr45L7m6
376,La hamburguesería,Hamburguesería,NaN,NaN,NaN,NaN,NaN,"WXX4+6M Piedecuesta, Santander","Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,6.948116,-73.043300,https://maps.app.goo.gl/QH4bnLony1puWDWq7

In [18]:
#Finally, we will create a column named: 'categoria_puntuacion'. We will apply the function get_score_range() from utils on the column 'Rating'
#First, we see that 'Rating' is a string: we will convert it to a float: But we'll have to replace the ',' by '.' first
amb_googleMapsScrapper['Rating'] = amb_googleMapsScrapper['Rating'].str.replace(',', '.')
#Now we convert it to a float
amb_googleMapsScrapper['Rating'] = amb_googleMapsScrapper['Rating'].astype(float)
#Now we create the column 'categoria_puntuacion'
amb_googleMapsScrapper['categoria_puntuacion'] = amb_googleMapsScrapper['Rating'].apply(get_score_range)
#Now let's visualize the 5 last rows
amb_googleMapsScrapper.tail()

,name,Category,Rating,Nº Reviews,Stars,User Comment,Hours,Plus Code,Address,City,Province,Url,Latitude,Longitude,Url in Maps,categoria_puntuacion
372,Restaurante Bar la Playa,Restaurante,4.0,NaN,1.0,Definitivamente no volvería ni aunque me vuelv...,"jueves, 6 AMa10 PM; viernes, 6 AMa10 PM; sábad...","XXC5+79 Piedecuesta, Santander","6.969098,-73.041713, Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,6.970722,-73.041509,https://maps.app.goo.gl/xjaWmCSCy7SU8utv6,4.0-4.5
373,Pizza Cartoon y Panzerotti,Restaurante,4.3,NaN,1.0,pedi una pizza mediana que se supone traia 5 p...,"jueves, 4 PMa12 AM; viernes, 4 PMa12 AM; sábad...","XWWV+QG Piedecuesta, Santander","Transversal 1D # 7a-14, La Argentina, Piedecue...","Piedecuesta, Santander",Santander,NaN,6.996958,-73.056191,https://maps.app.goo.gl/NM7KozQ1AyVwmXZh8,4.0-4.5
374,Aoki Sushi Rolls Piedecuesta,Restaurante japonés,4.6,NaN,5.0,"Excelente Sabor y Variedad de productos, muy b...","jueves, 5a11 PM; viernes, 5a11 PM; sábado, 12a...","2W2W+Q8 Piedecuesta, Santander","Cra 15, Av. 10ª N #7BN-15, Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,7.001967,-73.054164,https://maps.app.goo.gl/pM9gkH39ccCBoXHA6,4.5-5.0
375,Asadero Super Kali,Restaurante,4.2,NaN,5.0,El pollo siempre fresco y jugoso. La sopa muy ...,"jueves, 10:30 AMa9:30 PM; viernes, 10:30 AMa9:...","XWXW+VJ Piedecuesta, Santander","Cra 15 #2N-02, Piedecuesta, Santander","Piedecuesta, Santander",Santander,https://www.gurugo.co/empresas/asadero-super-k...,6.999699,-73.053459,https://maps.app.goo.gl/MJaP4WYgkKr45L7m6,4.0-4.5
376,La hamburguesería,Hamburguesería,NaN,NaN,NaN,NaN,NaN,"WXX4+6M Piedecuesta, Santander","Piedecuesta, Santander","Piedecuesta, Santander",Santander,NaN,6.948116,-73.043300,https://maps.app.goo.gl/QH4bnLony1puWDWq7,< 4.0

In [19]:
#Let's export these three dataFrames to csf files: they will be exported in a new folder called 'resultados_finales':
amb_googleMapsScrapper.to_csv('resultados_finales/amb_googleMapsScrapper.csv', index=False)

## Data Cleansing 2nd step: InstantDataScrapper

In [20]:
#Firs we create the dataframes associated with googleMapsScrapper
bucaramanga_instantDataScrapper = read_instantDataScrapper('resultadosInstantDataScrapper/bucaramanga_instantDataScrapper.csv')
floridablanca_instantDataScrapper = read_instantDataScrapper('resultadosInstantDataScrapper/floridablanca_instantDataScrapper.csv')
giron_instantDataScrapper =  read_instantDataScrapper('resultadosInstantDataScrapper/giron_instantDataScrapper.csv')
piedecuesta_instantDataScrapper = read_instantDataScrapper('resultadosInstantDataScrapper/piedecuesta_instantDataScrapper.csv')

In [21]:
#Let's visualizethe content for floridablanca_instanDataScrapper
floridablanca_instantDataScrapper.tail()

,nombre_restaurante,tipo_restaurante,puntuacion,cantidad_comentarios,precio_por_persona,direccion_comercial,tipo_consumo,if66xd,opciones,if66xd 2,entrega,enlace,uDyWh,uDyWh 2,YQ4gaf src 2
137,Asados Malu,· Restaurante,5.0,(10),⋅ Abre a las 5 p.m.,"frente a los conjuntos de paragüitas, Cra. 8",NaN,NaN,NaN,NaN,NaN,https://ssl.gstatic.com/local/servicebusiness/...,"""Excelentes , carne fresca con la sazón correc...",hamburguesas,https://lh5.googleusercontent.com/p/AF1QipN0mP...
138,ALEX BURGER,· · Comida rápida,4.4,(31),"$20,000-30,000",Villa San Marcos,Consumo en el lugar,·,Pedidos desde el automóvil,·,Entrega sin contacto,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipO2_v...
139,Villa Barbacoa,· · Restaurante,4.4,(392),"$10,000-20,000","225, Cl. 157 #154",NaN,NaN,NaN,NaN,NaN,https://ssl.gstatic.com/local/servicebusiness/...,"""Excelentes """,hamburguesas,https://lh5.googleusercontent.com/p/AF1QipOlO8...
140,Choppers Burger Dog,· · Hamburguesa,4.4,(523),"$10,000-20,000",Santander,Consumo en el lugar,·,Pedidos desde el automóvil,·,Entrega sin contacto,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMizP...
141,George Burger,· Hamburguesa,4.9,(17),NaN,Santander,NaN,NaN,NaN,NaN,NaN,https://ssl.gstatic.com/local/servicebusiness/...,"""Tienen diferentes tipos de hamburguesas.""",NaN,https://lh5.googleusercontent.com/p/AF1QipPM1E...

In [22]:
#let's see the info for bucaramanga_instantDataScrapper:
bucaramanga_instantDataScrapper.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   nombre_restaurante    180 non-null    object
 1   tipo_restaurante      179 non-null    object
 2   puntuacion            170 non-null    float64
 3   cantidad_comentarios  170 non-null    object
 4   precio_por_persona    144 non-null    object
 5   direccion_comercial   180 non-null    object
 6   tipo_consumo          100 non-null    object
 7   if66xd                100 non-null    object
 8   opciones              100 non-null    object
 9   if66xd 2              98 non-null     object
 10  entrega               98 non-null     object
 11  enlace                180 non-null    object
dtypes: float64(1), object(11)
memory usage: 17.2+ KB

In [23]:
#let's see its info, so we can find relevant information about the columns and data tyes:
floridablanca_instantDataScrapper.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   nombre_restaurante    140 non-null    object
 1   tipo_restaurante      140 non-null    object
 2   puntuacion            138 non-null    float64
 3   cantidad_comentarios  138 non-null    object
 4   precio_por_persona    105 non-null    object
 5   direccion_comercial   140 non-null    object
 6   tipo_consumo          73 non-null     object
 7   if66xd                73 non-null     object
 8   opciones              73 non-null     object
 9   if66xd 2              70 non-null     object
 10  entrega               70 non-null     object
 11  enlace                67 non-null     object
 12  uDyWh                 67 non-null     object
 13  uDyWh 2               66 non-null     object
 14  YQ4gaf src 2          135 non-null    object
dtypes: float64(1), object(14)
memory usage: 16.8+ KB

In [24]:
#let's see it too for giron_instantDataScrapper:
giron_instantDataScrapper.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   nombre_restaurante    96 non-null     object
 1   tipo_restaurante      96 non-null     object
 2   puntuacion            92 non-null     float64
 3   cantidad_comentarios  92 non-null     object
 4   precio_por_persona    75 non-null     object
 5   tipo_consumo          54 non-null     object
 6   if66xd                53 non-null     object
 7   opciones              53 non-null     object
 8   if66xd 2              51 non-null     object
 9   entrega               51 non-null     object
 10  enlace                40 non-null     object
 11  direccion_comercial   93 non-null     object
 12  uDyWh                 41 non-null     object
 13  uDyWh 2               41 non-null     object
 14  YQ4gaf src 2          91 non-null     object
 15  rllt__details 4       26 non-null     object
 16  rllt__details 5       51 non-null     object
dtypes: float64(1), object(16)
memory usage: 13.1+ KB

In [25]:
piedecuesta_instantDataScrapper.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   nombre_restaurante    129 non-null    object
 1   tipo_restaurante      129 non-null    object
 2   puntuacion            123 non-null    float64
 3   cantidad_comentarios  123 non-null    object
 4   precio_por_persona    93 non-null     object
 5   direccion_comercial   127 non-null    object
 6   tipo_consumo          63 non-null     object
 7   if66xd                62 non-null     object
 8   opciones              62 non-null     object
 9   if66xd 2              61 non-null     object
 10  entrega               61 non-null     object
 11  enlace                129 non-null    object
 12  uDyWh                 64 non-null     object
 13  uDyWh 2               64 non-null     object
dtypes: float64(1), object(13)
memory usage: 14.5+ KB

There's also a similar problem here with the instantDataScrapper dataFrames: there are 'thrash' columns that we need to get ripped off. If we concat the dataFrames how they are right now, we're going to get a wrong result!

In [26]:
#let's create a list with the columns that are in common between the 4 of them, and the ones that we will need!
columns2 = ['nombre_restaurante', 'tipo_restaurante', 'puntuacion',
       'cantidad_comentarios', 'precio_por_persona', 'direccion_comercial',
       'tipo_consumo', 'opciones', 'entrega', 'enlace']
#now, for every single one of the previous 4 dataFrames, use this list to fix the columns names:

bucaramanga_instantDataScrapper = bucaramanga_instantDataScrapper[columns2]
floridablanca_instantDataScrapper = floridablanca_instantDataScrapper[columns2]
giron_instantDataScrapper = giron_instantDataScrapper[columns2]
piedecuesta_instantDataScrapper = piedecuesta_instantDataScrapper[columns2]
#NOW we are erady to concatenate!

In [27]:
#The 4 dataFrames have exactly the same structure: let's merge them into a single dataFrame called amb_instantDataScrapper:
amb_instantDataScrapper = pd.concat([bucaramanga_instantDataScrapper, floridablanca_instantDataScrapper, giron_instantDataScrapper, piedecuesta_instantDataScrapper], ignore_index=True)
#Now let's visualize the resulting dataFrame:
amb_instantDataScrapper.tail()

,nombre_restaurante,tipo_restaurante,puntuacion,cantidad_comentarios,precio_por_persona,direccion_comercial,tipo_consumo,opciones,entrega,enlace
548,Ulala Pizza,· Pizza,4.8,(6),⋅ 4:45 p.m.,Cra. 1C #21-05,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMRPE...
549,Aoki Sushi Rolls Piedecuesta,· Japonesa,4.6,(77),⋅ Abre a las 5 p.m.,"Cra 15, Av. 10ª N #7BN-15",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOtCt...
550,Restaurante San Martin,· · Restaurante,4.2,(884),$$,"Barrio San Rafael, Cra 15 #13a - 35",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMUo0...
551,Pancha comida tradicional,· Ideal para familias,4.7,(132),⋅ Abre a las 5 p.m.,Cl 7 #6-55,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOYh8...
552,MAMBAS,· Hamburguesa,4.8,(12),⋅ Abre a las 5:30 p.m.,"Ruitoque condominio, Aldea comercial local 18",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipN_Yd...

In [28]:
#Let's use the info() method again to see if there's relevant infno:
amb_instantDataScrapper.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 553 entries, 0 to 552
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   nombre_restaurante    545 non-null    object
 1   tipo_restaurante      544 non-null    object
 2   puntuacion            523 non-null    float64
 3   cantidad_comentarios  523 non-null    object
 4   precio_por_persona    417 non-null    object
 5   direccion_comercial   540 non-null    object
 6   tipo_consumo          290 non-null    object
 7   opciones              288 non-null    object
 8   entrega               280 non-null    object
 9   enlace                416 non-null    object
dtypes: float64(1), object(9)
memory usage: 43.3+ KB

In [29]:
amb_instantDataScrapper.columns

Index(['nombre_restaurante', 'tipo_restaurante', 'puntuacion',
       'cantidad_comentarios', 'precio_por_persona', 'direccion_comercial',
       'tipo_consumo', 'opciones', 'entrega', 'enlace'],
      dtype='object')

In [30]:
#Let's see the info method again: there might be some data type issues:
amb_instantDataScrapper.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 553 entries, 0 to 552
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   nombre_restaurante    545 non-null    object
 1   tipo_restaurante      544 non-null    object
 2   puntuacion            523 non-null    float64
 3   cantidad_comentarios  523 non-null    object
 4   precio_por_persona    417 non-null    object
 5   direccion_comercial   540 non-null    object
 6   tipo_consumo          290 non-null    object
 7   opciones              288 non-null    object
 8   entrega               280 non-null    object
 9   enlace                416 non-null    object
dtypes: float64(1), object(9)
memory usage: 43.3+ KB

Ojo con esto:
- precio_por_persona
- cantidad_comentarios

son columnas que representan variables continuas. Por tanto, debemos transformarlas a un valor numérico

In [31]:
#Transform the columns 'precio_por_persona' and 'cantidad_comentarios' to integer type:
#amb_instantDataScrapper['precio_por_persona'] = amb_instantDataScrapper['precio_por_persona'].str.replace('$', '').str.replace(',', '').astype(int)

We can see the following error: ValueError: invalid literal for int() with base 10: '30000-50000'.Let's check which the unique values are:

In [32]:
#Let's visualize 'precio_por_persona' unique values in a variable:
amb_instantDataScrapper['precio_por_persona'].unique()

array(['$30,000-50,000', '$20,000-30,000', '$30,000-40,000', '$',
       '$10,000-20,000', '$20,000-40,000', nan, '$$', '$10,000-30,000',
       '$40,000-50,000', '⋅ Abre a las 6:15\u202fp.m.',
       '⋅ Abre a las 5\u202fp.m.', '⋅ Abre a las 6\u202fp.m.',
       '⋅ Abre a las 5:30\u202fp.m.', '⋅ Abre a las 6:30\u202fp.m.',
       '⋅ 4:30\u202fp.m.', '⋅ Abre a las 5:50\u202fp.m.',
       '⋅ Abre a las 6:50\u202fp.m.', '⋅ Abre a las 6\u202fp.m. del sáb',
       '⋅ Abre a las 4:30\u202fp.m. del vie', 'Santander', '$1-10,000',
       '⋅ Abre a las 10\u202fa.m. del vie', '⋅ Abre a las 5:45\u202fp.m.',
       '⋅ 4:25\u202fp.m.', '⋅ Abre a las 11\u202fa.m. del vie',
       '⋅ Abre a las 7\u202fa.m. del vie', '⋅ 4:45\u202fp.m.'],
      dtype=object)

In [33]:
#Let's drop the column 'precio_por_persona':
amb_instantDataScrapper.drop('precio_por_persona', axis=1, inplace=True)
#Do not fotget to reset index
amb_instantDataScrapper.reset_index(drop=True, inplace=True)
#Now let's visualize the 5 last rows:
amb_instantDataScrapper.tail()

,nombre_restaurante,tipo_restaurante,puntuacion,cantidad_comentarios,direccion_comercial,tipo_consumo,opciones,entrega,enlace
548,Ulala Pizza,· Pizza,4.8,(6),Cra. 1C #21-05,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMRPE...
549,Aoki Sushi Rolls Piedecuesta,· Japonesa,4.6,(77),"Cra 15, Av. 10ª N #7BN-15",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOtCt...
550,Restaurante San Martin,· · Restaurante,4.2,(884),"Barrio San Rafael, Cra 15 #13a - 35",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMUo0...
551,Pancha comida tradicional,· Ideal para familias,4.7,(132),Cl 7 #6-55,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOYh8...
552,MAMBAS,· Hamburguesa,4.8,(12),"Ruitoque condominio, Aldea comercial local 18",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipN_Yd...

In [34]:
#Now let's transform the column cantidad_comentarios to a numeric type: but first, we will need to eliminate any string literal that is not a number, using regular expressions:
amb_instantDataScrapper['cantidad_comentarios'] = amb_instantDataScrapper['cantidad_comentarios'].str.extract('(\d+)').astype(float)

In [35]:
#Now let's visualize the unique values of the column 'cantidad_comentarios':
amb_instantDataScrapper['cantidad_comentarios'].unique()
#Let's visualize the 5 last rows:
amb_instantDataScrapper.tail()

,nombre_restaurante,tipo_restaurante,puntuacion,cantidad_comentarios,direccion_comercial,tipo_consumo,opciones,entrega,enlace
548,Ulala Pizza,· Pizza,4.8,6.0,Cra. 1C #21-05,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMRPE...
549,Aoki Sushi Rolls Piedecuesta,· Japonesa,4.6,77.0,"Cra 15, Av. 10ª N #7BN-15",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOtCt...
550,Restaurante San Martin,· · Restaurante,4.2,884.0,"Barrio San Rafael, Cra 15 #13a - 35",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMUo0...
551,Pancha comida tradicional,· Ideal para familias,4.7,132.0,Cl 7 #6-55,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOYh8...
552,MAMBAS,· Hamburguesa,4.8,12.0,"Ruitoque condominio, Aldea comercial local 18",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipN_Yd...

In [36]:
#And finally, we will delete rows in which at least one of this columns has a Nan value: [puntuacion, cantidad_comentarios, direccion_comercial]
#amb_instantDataScrapper.dropna(subset=['puntuacion', 'cantidad_comentarios', 'direccion_comercial'], inplace=True)
amb_instantDataScrapper.dropna(how='all', inplace=True)#Remember: we will only remove those rows with all NaN values
amb_instantDataScrapper.drop_duplicates(inplace=True)#And we'll remove duplicates based on all of the rows
#Doo not forget to reset index:
amb_instantDataScrapper.reset_index(drop=True, inplace=True)
#Now let's visualize the 5 last rows:
amb_instantDataScrapper.tail()

,nombre_restaurante,tipo_restaurante,puntuacion,cantidad_comentarios,direccion_comercial,tipo_consumo,opciones,entrega,enlace
540,Ulala Pizza,· Pizza,4.8,6.0,Cra. 1C #21-05,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMRPE...
541,Aoki Sushi Rolls Piedecuesta,· Japonesa,4.6,77.0,"Cra 15, Av. 10ª N #7BN-15",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOtCt...
542,Restaurante San Martin,· · Restaurante,4.2,884.0,"Barrio San Rafael, Cra 15 #13a - 35",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMUo0...
543,Pancha comida tradicional,· Ideal para familias,4.7,132.0,Cl 7 #6-55,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOYh8...
544,MAMBAS,· Hamburguesa,4.8,12.0,"Ruitoque condominio, Aldea comercial local 18",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipN_Yd...

In [37]:
#Additionally, we will create a new column called 'categoria_puntuacion' by applying the function get_score_range() to the column 'puntuacion':
amb_instantDataScrapper['categoria_puntuacion'] = amb_instantDataScrapper['puntuacion'].apply(get_score_range)
#Now let's visualize the 5 last rows:
amb_instantDataScrapper.tail()

,nombre_restaurante,tipo_restaurante,puntuacion,cantidad_comentarios,direccion_comercial,tipo_consumo,opciones,entrega,enlace,categoria_puntuacion
540,Ulala Pizza,· Pizza,4.8,6.0,Cra. 1C #21-05,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMRPE...,4.5-5.0
541,Aoki Sushi Rolls Piedecuesta,· Japonesa,4.6,77.0,"Cra 15, Av. 10ª N #7BN-15",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOtCt...,4.5-5.0
542,Restaurante San Martin,· · Restaurante,4.2,884.0,"Barrio San Rafael, Cra 15 #13a - 35",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMUo0...,4.0-4.5
543,Pancha comida tradicional,· Ideal para familias,4.7,132.0,Cl 7 #6-55,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOYh8...,4.5-5.0
544,MAMBAS,· Hamburguesa,4.8,12.0,"Ruitoque condominio, Aldea comercial local 18",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipN_Yd...,4.5-5.0

Now we're at the last stage of the cleansing process: let's extract the geographic coordinates based on the address column: 'direccion_comercial'

In [38]:
#First, we will look for the unique values of 'direccion_comercial':
amb_instantDataScrapper['direccion_comercial'].unique()

array(['Cra. 34 #48 - 93', 'Cl. 50 #16-59', 'Cl. 52 #22-60',
       'Cra. 45 #56 - 14', 'Cra. 36 #38-44 Piso 2', 'Cl. 105 #2693',
       'Cra. 30 #40-13', 'Cra. 26a #50-72', 'Cra. 32a #17-31',
       'Cra. 36 #38-52', 'Cra. 30 #19-37', 'Cl. 35 #20-47',
       'Cacicque Centro Comercial, Cl 93 #34-99', 'Santander',
       'Calle 44 #33-22', 'Av. 89', 'Cra. 26 #17-53',
       'Conjunto Marsella Real, Avenida los búcaros # oste 3 - 155, Local 12',
       'Cl. 32 #38-24', 'Calle 44 #31a-74 #31a-2 a', 'Cra. 26a #No 50 66',
       'Cl. 49 #32 07', 'Cl. 67 #16 - 30', 'Cl. 36 #24-32',
       'Cl. 10 #21-28 Casa -local', 'Cra. 36 #54-34', 'Cl. 41 #34-13',
       '680003, Cra 23 #53 03', 'Cl. 36 #1430', 'Cra. 21 #19-31',
       'Cra 23 #559', 'Cl. 56 #18-29',
       'Tv. 93 # 34-99 Centro Comercial Cacique - Plazoleta de Comidas, Local 318',
       'Cl. 34 #32-58', 'Cra 29#40-54',
       'Centro Comercial Cacique, Tv. 93 #34 - 99 Local 402',
       'Cl. 52 #34-12', 'Cl. 67 #26-29',
       'La Quinta, Cra. 38 #49-12 Local 416', 'Calle 56 #2AW-17',
       'Calle 34 N #34-45', 'Cl. 38 #33 45',
       'carrera 35A # 49-55 plaza de comidas quinto piso, local 507',
       'cra: 27A#45A16', 'Cra29#40-90', 'Cra 23 #53 - 03',
       'Cra. 35a #46-31', 'Cl. 34 #30 26', 'Cl. 105 #24-59',
       'Cl. 105 #No. 15-69', 'Cl. 32 #29 -66',
       'El Verguero col, Cl. 100 #35-95', 'Calle 48 #Nº 35 - 23',
       'Ave Eduardo Santos #28-32', 'Cra. 36 #42-85',
       'Carrera 29 A # 44 - 21 Parque Las Palmas', 'Cl. 34 #30-33',
       'Calle 45 # 1 Occidente 29', 'Cl. 65 #13 - 16', 'Cra. 28',
       'Cl. 38 #33-44', 'Cra. 26 #90-30', 'Cra. 26 #20-06', 'Cra. 2w #63',
       'Cra. 30 #18-65', 'Cra 29 # 41', 'Cl. 18 #24-06', 'Cl. 47 #29-74',
       'Cra 29 #41-20', 'Cra. 35 #37- 46', 'Cl. 55 #22-23',
       'Cra. 27 #14-3', 'Cl. 111 #22-08', '25 - 110 Calle 86', 'Cra 17',
       'Centro Comercial Cacique, Tv. 93 #34-99', 'Cra. 39 #51-66',
       'Cra. 26 #20-05', 'Cra. 24 #31-11', 'Cra. 35 #34',
       'Cra. 36 #52-96', 'Cl. 32 #30a-11', 'Cl. 22 #24-34',
       'Cra 29 #47-82', 'Cra. 28 #14-83', 'Cra. 35 #53-12',
       'Cra. 32a #20 - 26',
       'frente al parque san Francisco, Blvr. Santander #local 20-72',
       'Cra. 37 #35-49', 'Cra. 47 #32-106', 'Cl. 32 #40-25',
       'Cra. 27 #13-59', 'Cl. 105 #24-87', 'Cra. 33 #44- 49',
       'Cra. 30 #16-4', 'Cra. 24 #21-23', 'Cra. 1 #65b - 38',
       'Cl. 106 #23a-98', 'Cl. 37 #4A-10', 'Cl. 31a #33 bis - 51',
       'Cra 23 #52-88', 'Local 17 Av los Bucaros, Marsella Real #3-135',
       'González #25-29', 'Cra 29 #21-9', 'Cra 29#94-52',
       'Cl. 65c #5A-07', 'a 49-62, Cra. 35a #49-2', 'Cl. 10 #26-45',
       'Cra. 36 #48-88', '680006 Carrera 34 # 35 - 46', 'Cra. 17C #60-63',
       'Cra. 24 #33a - 39', 'Cl. 39 #2159', 'Cra. 33 #4449',
       'Cra. 35 #34-02', 'Cra. 13 #13-70', 'Cra. 30 #· 32 - 58',
       'Cra. 18 #11- 34 Esquina', 'Cl. 67 # 24-29', 'Cl. 56 #16-17',
       'Cl 88 #17b',
       'Cacique - Bucaramanga, Transversal Oriental #No. 90-182 Local 412',
       'Cra. 2w #62-31', 'Cra. 36 #42-36', 'Cra. 34 #37-33',
       'Cl. 22 #21-10', 'Cl. 32 # 29-49', 'Cl. 51 #31 18',
       'Cl. 48 #34 esquina', 'Carrera 29#13a-05', 'Cra. 36 #41-22',
       'Cra. 21 #37-21', 'Cl. 39 # 21-19', 'Carrera 17#8-52',
       'Cra. 36 #48 - 58', 'Av. La Rosita #17-26', 'Cl. 75 #31-2', '+57',
       'DIAGONAL EDIFICIO LAS NIEVES, Calle 21 25 22 San Francisco',
       'Cl. 65 #18-39', 'Blvr. Santander #22-92', 'Cl. 14 #26-03',
       'Cra. 28 #50 - 40', 'Cra. 20 #8-5', 'Cl. 57 # 17a - 08', 'Cra. 2w',
       'Cl. 43 #9 - 38', 'Av. 89 #23-65', 'Cra 23 #22-32', 'Cl. 12 #1923',
       'Cl. 52 #35-06', 'Cra. 19 # 11-07', 'Cra. 34 #44-84',
       'Cl. 36 #13-08', 'Cra. 26 #17-18', 'Cl. 52 #20-53',
       'Cl. 33 # 32 - 72', 'Cl. 17 #26-12', 'Cl. 59 #1w-64',
       'Cra. 9 #42-44', 'Cra. 20 #14-25', 'CC Megamall, Cl. 20 #29-15',
       'Cl. 48 #34-26', 'Cl. 34 #25 - 66', 'Cra. 36 #42 -31',
       'Tv. 93 #34', 'Cl 52A #31-15', 'Cra 29 #41-30', 'Cl. 9 #22-15',
       'Carrera 33a # 29 - 15 Centro Comercial Megamall - Plazoleta de Comidas - Local 50',
       'Calle 32, Parque #21-05', 'Cra. 36 #38-41', 'Cra. 38 #32-88',
       'Cra. 31 #50 - 19 Local 1', 'Samanes #28-70', '68001',
       'Cl. 50 #27-17', 'Cra. 28 #11a-2 a 11a-48', 'Cl. 204 #204 A-06',
       'Cl. 32 #26-26', 'Centro Comercial La Florida, Terraza 360',
       'Cl. 32 #26-13', 'Cra. 28 #22-70', 'Circunvalar 29 #8-68',
       'Av. 60 #144 21', 'Cl. 198 #33 - 112', 'Cl. 147 #22-63',
       'lagos , cañaveral, Cl 29 #10-42', 'Cl. 28 #6e-32',
       'piso 2 interior 6, Cra. 25 #25-71 local 249', 'Cl. 32 #1179',
       'Cra. 8 #3-02', 'Cl. 126a # 45 - 02', 'Cl. 20 #12-03',
       'Cl. 201a #22-27', 'Sector B Torre 10, Local 102',
       'El dorado, Cl 111A #32-40', 'Av. Floridablanca # 147-38 Local 7',
       'Cl. 17 #18-83', 'Cra. 7 #6-21', 'Cl. 5 #5-06', 'Cra. 9 #33-05',
       'Cl. 5 # 14-49', 'Calle 32 # 26-40 Cañaveral', 'Cl. 8 #610',
       'Cl. 200 #20-04', 'Cra. 3 #240', 'a 29-240, Cra. 12 #29-2',
       'Cra. 23 #200A - 27', 'Cl. 29 #20 # 9', 'Cra. 10 #2-48',
       'Cra. 5 Este # 30-30', 'Cra. 9 Este # 32-22', 'Cra. 11 # 27-22',
       'Cl. 200 #19-58', 'Cra. 12 #9-23',
       'Parque Caracoli, Carrera 27 No. 29-145 Local No. FC-409',
       'Cra 26 #30-59', 'Floridablanca, Santander', 'Cl. 10 #7-42',
       'Cra. 8ª #12-113 L3', 'Cra. 8', 'Circunvalar 29', 'Cra. 10 #256',
       'Cra. 6 #6-59', 'Cra. 3 #48-6', 'Cl. 31 #23-75',
       'Cl 203 #40-22 Local 1-B', 'Cra. 13 #7-37', 'Cra. 3 Este #27-04',
       'Carrera 11 · 15 - 06',
       'Centro Comercial La Florida, Cl. 31a #20-42', 'Cra. 10a #46',
       'Cra. 20 #59-64', 'Carrera 39 B # 149 - 09 Escoflor',
       'Cl 104B #42A-22', 'Cl. 33 #26-64', 'Cra. 32a #112-26',
       'Cl. 16a #39', 'Cl. 5 #18a-27', 'Circunvalar 29 #8-12',
       'Cra. 11 #26 24', 'Carrera 43 #105A-86 Campanazo', 'Cl. 56 #1505',
       '681002 Calle 31 No.23-75, Local 2', 'Transversal 149 #56-03',
       'Cl. 5 #15-08', 'Cl. 32 #26-17',
       'CC Parque Caracoli, Tv. El Bosque #29-145 Local 402',
       'Cl. 19 #10a-27', 'zapamaga V, Cl. 123 #47-40', 'Cra. 8 #26-22',
       'Carrera 33 # 112 13 caldas Telefono 3163331788 6366581',
       'Cra. 40 #203-40', '681003, Av. Bucarica',
       'Calle 151 Sector c torre 14 local 3-4', 'Cra. 12 #18-16',
       'Cra. 7 E #33-24', 'Cra 5 #41-20, Sumergido de Lagos #2',
       'Barrio La Paz, Cl. 200 #18-88', 'Cra. 7 #38-03',
       'Av. Floridablanca #149-04', 'Cl. 31 # 23-29', 'Cra. 13 #9-12',
       'a 149a-23, Cra. 23 #1491', 'Cl. 16 #12-02', 'Av. Bucarica',
       'Cl. 118 #32-61', 'Tv. El Bosque #29-145',
       'Centro Comercial Caracoli, Tv. El Bosque #29-145 Local 404',
       'Av Bucarica Bucarica Bloque 16-8, Local 101B', 'Cl. 15 #28-66',
       'Cl. 32 #26-28', 'Cra 26 #30-43',
       'Calle 31 No. 26A-19, Local 225 C.C. La Florida -(Floridablanca Santader)',
       'Ruitoque Plaza, Ruitoque Alto via tres esquinas Km 7, Local 2',
       'Cl 111A #45-03', 'Cra. 7 E #27c-2 a, Cl. 27c #32',
       'Cl. 147d #44-47', 'Circunvalar 29 #8 -78', 'Cl. 148 #44-64',
       'Cra. 12 #10-03', 'Cra. 3 #2-150', 'Cra. 7 #6 23', 'Cra. 8 #4-20',
       'Bucaramanga, Santander', 'Cl. 56 #1602', 'Cl. 157 #154',
       'Centro Comercial Cañaveral Calle 30, Cañaveral #25-71 Piso 2, Local 249, interior 3',
       'Cl. 200 #26-16', 'Cra. 11b #12-27', 'Cl. 7 #5-59',
       'Cra. 11 #5 10 Local 4',
       'frente a los conjuntos de paragüitas, Cra. 8', 'Villa San Marcos',
       '225, Cl. 157 #154', nan, 'Cl. 17 #26-05', 'Girón, Santander',
       '$20,000-30,000', '⋅ Abre a las 5\u202fp.m.',
       'norte giron, Cl. 20 #24-74', 'Cra. 9 #8-56',
       'Campo verde, Cra. 5 #1b-08', 'Calle 6N numero 4-330',
       'paseo del puente 1, Cra. 5B #19 63', 'Cra. 4 #1a-24',
       'Argentina antigua, Carrera 13 #940, Dg. 6 #2-29',
       'Manzana Acasa 2 Santelmo 2', 'Unnamed Road',
       'La Tachuela, Cl. 3 #4b - 04', 'Cra 15 #2B-18', 'Cra. 7 #6-98',
       'paso del puente 2', 'Cra. 4 #1-304', 'Cra 15 #7bn-21 #',
       'Cra. 7b', 'Cra. 7 #5-00', 'Mz. S #354', 'Cra. 7 #7-11',
       'calle 7an, Av. 10ª N #15-35', 'Cl. 3 AN',
       'Barrio La presentación, Cl 4 #6a 03', 'Cl. 5 #745',
       'Cra 8, Vía Antigua a Piedecuesta #1-50',
       'Calle 4 n#6-185 Junín 2', 'Carrera 15 # 6N-21 Barrio, Av. 10ª N',
       'Cll 15a 17-114 Barroblanco', 'Cl. 1AN #7D-08',
       'Manzana n casa 197 #574', 'Calle 4N # 9-03, Junin IV Etapa',
       'Cra. 5B #21-24',
       'Carrera 15 No 7an-41 Barrio, Quinta Granada, Piedrcuesta',
       'Diagonal 6b 1gnorte - 09', 'Diagonal 6 #1in-09', 'Cl. 1a',
       'Cl. 1ª Nte.', '981011', 'Cl. 6 #250', 'Cra. 8 #3-96',
       'Paseo del, Cl 21 #4 12', 'Cl. 10 Nte. # 16 - 26',
       'Cl. 1ª Nte. #0w-99', 'Cl 7', 'Cra 15 #1n-03', 'Calle6N #9-94',
       'Cra. 17 #1446', 'Cra. 4 #1b-9 1b-9', 'Junin ll, Calle 6N #3A-177',
       'Tv. 2 #4e 24', 'Calle 21b 1w 05 a 50', 'Cra. 4 #1A-34',
       'Carrera 15, Av. 10ª N #7BN-15', 'Cra 15 # 10 N 65',
       'la castellana', 'Manzana E San Telmo 1 Etapa, Casa 1',
       'Cl. 6 #11-70', 'Cl. 14 #6a-06', 'Cl 10 #981',
       'Cra 6#1D-Bis-05, Piedecuesta-Paseo Alcalá #Casa 792',
       'calle 6n # 3a 131 junin 2', 'Cl. 1ª D Bis #532', 'Cl. 18 #7-22',
       'Calle6N #1w-04 local 2', 'Diagonal 6 1iN - 03 por la principal',
       'Cl. 17', 'Paseo del puente 1, Cra. 5 #18a - 47', 'Cra. 4',
       'Calle 3 & Carrera 12', 'Calle 6 norte #4 138', 'Cl 7 #7-51',
       'Cra. 15C #7', 'Barrio Paseo del Puente 2, Cl 21 #4B 04',
       'Paseo del Puente, Cl. 23 #5A-17',
       'Cl. 10 # 5 - 44 Interior 1. Sanandresito 1 piso 681012',
       'Cl. 5 #9-75', 'Cra. 13 #3-93', 'Carrera 15 ## 10 N 65',
       'Cl 4 #4-25', 'Cra. 9 #7-55', 'Cl 7a #1510',
       'Ecocentro, Carrera 15 # 10N -65', 'Cra. 7 #10-76',
       'Cl 21 # 5 - 04', 'carrera 15, Av. 10ª N #7bn-21', 'Kr 2, Cl 4',
       'Santelmo 2 manzana a casa 5', 'Piedecuesta-El Molino',
       'Calle 6 número 15 23', 'Cl 7 #8-41', '2X62+26',
       'Piedecuesta, Santander', 'Cra. 8 #4-44',
       'Paseo del puente 2 calle 23, Cra. 2C #22-56',
       'Junin 1 calle 6n 3a 131', 'Dg. 6 #1B-34', 'Cra. 4 #7N-29',
       'Paseo del, Cl 21 #4-12', '681011', 'Cra 15 #4 -36',
       'La Tachuela,Comuna del Trapiche, Cl 4 # 5 05',
       'Transversal 1AN # 7D-14', 'Parque tematico', 'Cra. 8 #4-94',
       'Cra. 5 #4b-12', 'Cra 15 #2N-02',
       'Barrio Palermo 1 Calle 1A # 3_63', 'San Telmo, Manzana C #casa 3',
       '6.969098,-73.041713', 'Cra 15 # 3 - 40', 'Cra 15 # 3-46',
       'Transversal 1D # 7a-14', 'Kr 4, Cl. 0', 'Cra 15 #3-90',
       'Manzana D casa 1 Santelmo 1',
       'Barrio El Trapiche II Etapa, Calle 2A, Tv Comuna del Trapiche #3-111',
       'Vía', 'Cra. 1C #21-05', 'Cra 15, Av. 10ª N #7BN-15',
       'Barrio San Rafael, Cra 15 #13a - 35', 'Cl 7 #6-55',
       'Ruitoque condominio, Aldea comercial local 18'], dtype=object)

In [40]:
# We can see that the majority of this values corresponds to authentic addresses:
# Sp, we will need to create a new columns starting from 'direccion_comercial' column, which will contain the address in a format that can be used by the geocoding function:
#First, is there are float values, we will convert them to string:
amb_instantDataScrapper['direccion_comercial'] = amb_instantDataScrapper['direccion_comercial'].astype(str)
#Second STEP WILL BE REPLACING '#' for 'No'
amb_instantDataScrapper['direccion_comercial'] = amb_instantDataScrapper['direccion_comercial'].apply(lambda x : x.replace('#', 'No'))
#now  let's replace the rows with 'Cra' and 'Kr' for 'Carrera'
amb_instantDataScrapper['direccion_comercial'] = amb_instantDataScrapper['direccion_comercial'].apply(lambda x : x.replace('Cra', 'Carrera'))
amb_instantDataScrapper['direccion_comercial'] = amb_instantDataScrapper['direccion_comercial'].apply(lambda x : x.replace('Kr', 'Carrera'))
#and we will do the same for 'Cl' and 'Cll': they will be replaced by 'Calle'
amb_instantDataScrapper['direccion_comercial'] = amb_instantDataScrapper['direccion_comercial'].apply(lambda x : x.replace('Cl', 'Calle'))
#if 'Calle' or 'Carrera' are present, they should be the first word in the address:
#amb_instantDataScrapper['direccion_comercial'] = amb_instantDataScrapper['direccion_comercial'].apply(lambda x : ' '.join([x.split()[0], x.split()[1].capitalize(), ' '.join(x.split()[2:])]))
#Now let's visualize t THE LAST 5 ROWS:
amb_instantDataScrapper.tail()

,nombre_restaurante,tipo_restaurante,puntuacion,cantidad_comentarios,direccion_comercial,tipo_consumo,opciones,entrega,enlace,categoria_puntuacion
540,Ulala Pizza,· Pizza,4.8,6.0,Carrera. 1C No21-05,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMRPE...,4.5-5.0
541,Aoki Sushi Rolls Piedecuesta,· Japonesa,4.6,77.0,"Carrera 15, Av. 10ª N No7BN-15",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOtCt...,4.5-5.0
542,Restaurante San Martin,· · Restaurante,4.2,884.0,"Barrio San Rafael, Carrera 15 No13a - 35",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMUo0...,4.0-4.5
543,Pancha comida tradicional,· Ideal para familias,4.7,132.0,Calle 7 No6-55,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOYh8...,4.5-5.0
544,MAMBAS,· Hamburguesa,4.8,12.0,"Ruitoque condominio, Aldea comercial local 18",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipN_Yd...,4.5-5.0

In [41]:
#Third Step: we will create a new column called 'geocoding_address' that will contain the address in a format that can be used by the geocoding function:
amb_instantDataScrapper['geocoding_address'] = amb_instantDataScrapper.apply(lambda x : x['direccion_comercial'] + ', Bucaramanga, Santander, Colombia', axis=1)
#Now let's visualize the last 5 rows:
amb_instantDataScrapper.tail()

,nombre_restaurante,tipo_restaurante,puntuacion,cantidad_comentarios,direccion_comercial,tipo_consumo,opciones,entrega,enlace,categoria_puntuacion,geocoding_address
540,Ulala Pizza,· Pizza,4.8,6.0,Carrera. 1C No21-05,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMRPE...,4.5-5.0,"Carrera. 1C No21-05, Bucaramanga, Santander, C..."
541,Aoki Sushi Rolls Piedecuesta,· Japonesa,4.6,77.0,"Carrera 15, Av. 10ª N No7BN-15",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOtCt...,4.5-5.0,"Carrera 15, Av. 10ª N No7BN-15, Bucaramanga, S..."
542,Restaurante San Martin,· · Restaurante,4.2,884.0,"Barrio San Rafael, Carrera 15 No13a - 35",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMUo0...,4.0-4.5,"Barrio San Rafael, Carrera 15 No13a - 35, Buca..."
543,Pancha comida tradicional,· Ideal para familias,4.7,132.0,Calle 7 No6-55,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOYh8...,4.5-5.0,"Calle 7 No6-55, Bucaramanga, Santander, Colombia"
544,MAMBAS,· Hamburguesa,4.8,12.0,"Ruitoque condominio, Aldea comercial local 18",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipN_Yd...,4.5-5.0,"Ruitoque condominio, Aldea comercial local 18,..."

In [42]:
#Fourth STEP: we will use the geocoding function to get the latitude and longitude of every address in the column 'geocoding_address':
# we will call our api_key from the cred_google_Template file
MY_API_KEY = MY_API_KEY
#lets try to get the coordinates of the first address in the column 'geocoding_address':
get_coord(amb_instantDataScrapper['geocoding_address'][0], MY_API_KEY)

['CRA. 34, BUCARAMANGA, SANTANDER, COLOMBIA', 7.122748, -73.1113997]

In [43]:
#Now let's implement the following interation in order to extract out coordinates: let's call our get_coor function from utils.py
coordenadas_amb = []
tiempo = [1,2,2.5]

for i in tqdm(range(len(amb_instantDataScrapper['geocoding_address'])),colour = 'green'):

    try :
    
        R = get_coord(amb_instantDataScrapper['geocoding_address'][i],MY_API_KEY)
        geo_source = R[1],R[2]
        coordenadas_amb.append(geo_source)
    
    except :
    
        coordenadas_amb.append('Error')
    

    time.sleep(random.choices(tiempo)[0])

100%|██████████| 545/545 [19:40<00:00,  2.17s/it]

In [44]:
#We have to visualize the list coordenadas_amb to see if there are any errors:
coordenadas_amb

[(7.122748, -73.1113997),
 (7.1116432, -73.1225771),
 (7.1122031, -73.1165542),
 (7.1128333, -73.1060708),
 (7.1155403, -73.1085182),
 (7.0854502, -73.1179727),
 (7.1263811, -73.1088893),
 (7.1150365, -73.1158184),
 (7.1120746, -73.1125005),
 (7.1155403, -73.1085182),
 (7.1381453, -73.1178097),
 (7.1206415, -73.1209489),
 (7.0996939, -73.1073169),
 (7.119349, -73.1227416),
 (7.1198706, -73.1112937),
 (7.0920447, -73.1136107),
 (7.1312188, -73.1206358),
 (7.1041, -73.12706),
 (7.12282, -73.1223),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.1151407, -73.1158051),
 (7.1159001, -73.1142681),
 (7.0967753, -73.119901),
 (7.1174107, -73.1280109),
 (7.121089, -73.1141971),
 (7.1155403, -73.1085182),
 (7.1169172, -73.1215558),
 (7.1179729, -73.1184002),
 (7.1174107, -73.1280109),
 (7.11931, -73.1214239),
 (7.127253, -73.1224623),
 (7.1089841, -73.1141976),
 (7.0996939, -73.1073169),
 (7.1218513, -73.1201512),
 (7.1294776, -73.1273738),
 (7.1000528, -73.107414),
 (7.1131674, -73.1097173),
 (7.0967753, -73.119901),
 (7.119349, -73.1227416),
 (7.1089841, -73.1141976),
 (7.1613607, -73.1409075),
 (7.1227572, -73.1115988),
 (7.1149816, -73.1087979),
 (7.1294776, -73.1273738),
 (7.119349, -73.1227416),
 (7.127253, -73.1224623),
 (7.1179568, -73.1094546),
 (7.1243545, -73.1143572),
 (7.0857094, -73.1114467),
 (7.076583, -73.1273423),
 (7.119349, -73.1227416),
 (7.0880352, -73.1157031),
 (7.1128288, -73.1215922),
 (7.1338909, -73.1187045),
 (7.1155403, -73.1085182),
 (7.1195282, -73.1125025),
 (7.1218513, -73.1201512),
 (7.104183, -73.1404311),
 (7.0984696, -73.1194277),
 (7.0995113, -73.1107805),
 (7.1225911, -73.1115355),
 (7.1312188, -73.1206358),
 (7.1312188, -73.1206358),
 (7.1003835, -73.129592),
 (7.1313187, -73.1172276),
 (7.1205697, -73.113385),
 (7.1318061, -73.1174394),
 (7.1127453, -73.1250035),
 (7.1206858, -73.113592),
 (7.1191128, -73.1098445),
 (7.1082648, -73.1199169),
 (7.1278914, -73.1193136),
 (7.0819904, -73.1158704),
 (7.0912516, -73.1100936),
 (7.1156682, -73.1232217),
 (7.0996939, -73.1073169),
 (7.1151575, -73.1064918),
 (7.1312188, -73.1206358),
 (7.1165119, -73.1176301),
 (7.1191128, -73.1098445),
 (7.1155403, -73.1085182),
 (7.12282, -73.1223),
 (7.119349, -73.1227416),
 (7.1166353, -73.1123913),
 (7.0995113, -73.1107805),
 (7.1191128, -73.1098445),
 (7.1323159, -73.1150944),
 (7.131142, -73.124989),
 (7.1193008, -73.108614),
 (7.0915539, -73.107369),
 (7.1263811, -73.1088893),
 (7.1278914, -73.1193136),
 (7.0856831, -73.1112641),
 (7.1175894, -73.1112649),
 (7.1381453, -73.1178097),
 (7.1165119, -73.1176301),
 (7.107558, -73.13487),
 (7.0915539, -73.107369),
 (7.1171847, -73.126635),
 (7.1282289, -73.1119437),
 (7.127253, -73.1224623),
 (7.1031382, -73.1216715),
 (7.1022774, -73.1022175),
 (7.1203067, -73.1132305),
 (7.1294776, -73.1273738),
 (7.0978275, -73.1222877),
 (7.1149094, -73.1089996),
 (7.1376098, -73.1177836),
 (7.115309, -73.1083822),
 (7.1243473, -73.111764),
 (7.1063835, -73.1171857),
 (7.1165119, -73.1176301),
 (7.1173183, -73.1223649),
 (7.1175894, -73.1112649),
 (7.1191128, -73.1098445),
 (7.1145012, -73.127362),
 (7.1254614, -73.1154441),
 (7.1266093, -73.1267515),
 (7.1019194, -73.1141117),
 (7.1089841, -73.1141976),
 (7.0902744, -73.1102459),
 (7.0756385, -73.0830541),
 (7.1003835, -73.129592),
 (7.1155403, -73.1085182),
 (7.122748, -73.1113997),
 (7.1263233, -73.1275391),
 (7.119349, -73.1227416),
 (7.1138962, -73.1121864),
 (7.1165872, -73.1100881),
 (7.1294776, -73.1273738),
 (7.1218694, -73.1097696),
 (7.11931, -73.1214239),
 (7.1180306, -73.1206376),
 (7.1294776, -73.1273738),
 (7.1155403, -73.1085182),
 (7.119349, -73.1227416),
 (7.1179363, -73.1180672),
 (7.0995294, -73.1096366),
 (7.119349, -73.1227416),
 (7.0619338, -73.1694591),
 (7.0984696, -73.1194277),
 (7.1297252, -73.1261045),
 (7.1343714, -73.1155094),
 (7.1145341, -73.1140356),
 (7.1315636, -73.1254086),
 (7.1068621, -73.1185252),
 (7.1003835, -73.129592),
 (7.1207423, -73.1103015),
 (7.0920447, -73.1136107),
 (7.127253, -73.1224623),
 (7.1510642, -73.1310025),
 (7.110472, -73.1194085),
 (7.1356589, -73.1274991),
 (7.122748, -73.1113997),
 (7.1174107, -73.1280109),
 (7.1318189, -73.1208229),
 (7.1113977, -73.1177529),
 (7.1262395, -73.113171),
 (7.1535145, -73.1317271),
 (7.1012612, -73.1288676),
 (7.1080179, -73.1299477),
 (7.1315636, -73.1254086),
 (7.110472, -73.1194085),
 (7.1166391, -73.1101532),
 (7.122407, -73.1183802),
 (7.1155403, -73.1085182),
 (7.1001272, -73.1076525),
 (7.1123212, -73.1120523),
 (7.1205357, -73.1135192),
 (7.110472, -73.1194085),
 (7.1308004, -73.1126667),
 (7.12282, -73.1223),
 (7.1155403, -73.1085182),
 (7.1273892, -73.1104249),
 (7.1137937, -73.112255),
 (7.1084848, -73.1170321),
 (7.119349, -73.1227416),
 (7.1120669, -73.1209617),
 (7.1407768, -73.1345802),
 (7.1402291, -73.1156091),
 (7.12282, -73.1223),
 (7.0702043, -73.1051509),
 (7.12282, -73.1223),
 (7.1071214, -73.1128329),
 (7.0724115, -73.1024019),
 (7.0838979, -73.0852029),
 (7.0651753, -73.0845174),
 (7.078638, -73.0952086),
 (7.0692066, -73.1096089),
 (7.119349, -73.1227416),
 (7.1261188, -73.1217516),
 (7.1178498, -73.1168055),
 (7.12282, -73.1223),
 (7.0854707, -73.1306983),
 (7.0872793, -73.0980092),
 (7.119349, -73.1227416),
 (7.1282929, -73.1264151),
 (7.0603938, -73.0960722),
 (7.121089, -73.1141971),
 (7.121089, -73.1141971),
 (7.0900657, -73.1012816),
 (7.0787735, -73.1082953),
 (7.1535145, -73.1317271),
 (7.0730743, -73.1651355),
 (7.140411, -73.1298794),
 (7.1080179, -73.1299477),
 (7.119349, -73.1227416),
 (7.1240219, -73.1189368),
 (7.1390974, -73.1230588),
 (7.0614363, -73.1006211),
 (7.1137821, -73.1358882),
 (7.0709182, -73.1045348),
 (7.127253, -73.1224623),
 (7.114743, -73.141803),
 (7.1128288, -73.1215922),
 (7.076286, -73.0897763),
 (7.0787738, -73.0882319),
 (7.1221832, -73.131865),
 (7.119349, -73.1227416),
 (7.0614363, -73.1006211),
 (7.1499711, -73.133389),
 (7.1258323, -73.1185152),
 (7.1312188, -73.1206358),
 (7.0720568, -73.1068227),
 (7.1376098, -73.1177836),
 (7.0810579, -73.1148186),
 (7.0854707, -73.1306983),
 (7.0724115, -73.1024019),
 (7.119349, -73.1227416),
 (7.1038758, -73.1260593),
 (7.1137821, -73.1358882),
 (7.1208293, -73.1283874),
 (7.119349, -73.1227416),
 (7.1145012, -73.127362),
 (7.0739441, -73.0896447),
 (7.1314325, -73.1338591),
 (7.0705384, -73.105538),
 (7.076126, -73.1008663),
 (7.1315636, -73.1254086),
 (7.0755795, -73.0971225),
 (7.0831386, -73.1246859),
 (7.123349, -73.11903),
 (7.1323159, -73.1150944),
 (7.1299271, -73.1371061),
 (7.140411, -73.1298794),
 (7.0724115, -73.1024019),
 (7.1315318, -73.1337332),
 (7.1272269, -73.1082609),
 (7.1089841, -73.1141976),
 (7.1243151, -73.1209765),
 (7.119349, -73.1227416),
 (7.140411, -73.1298794),
 (7.12282, -73.1223),
 (7.0752244, -73.1087164),
 (7.1293895, -73.125361),
 (7.0878738, -73.0963694),
 (7.0854707, -73.1306983),
 (7.0879357, -73.103445),
 (7.1230599, -73.107246),
 (7.119349, -73.1227416),
 (7.0679349, -73.0861708),
 (7.0754079, -73.0983759),
 (7.1499711, -73.133389),
 (7.0762759, -73.0882995),
 (7.0660316, -73.0991382),
 (7.0614363, -73.1006211),
 (7.1384341, -73.1359418),
 (7.119349, -73.1227416),
 (7.0894801, -73.1084689),
 (7.1242468, -73.1213559),
 (7.1145012, -73.127362),
 (7.0768395, -73.1108191),
 (7.1334936, -73.1178058),
 (7.0679349, -73.0861708),
 (7.0874191, -73.1008657),
 (7.0752244, -73.1087164),
 (7.0752244, -73.1087164),
 (7.119349, -73.1227416),
 (7.0679349, -73.0861708),
 (7.1487717, -73.1400304),
 (7.12282, -73.1223),
 (7.1312188, -73.1206358),
 (7.0709709, -73.1047513),
 (7.0288723, -73.0942599),
 (7.0900657, -73.1012816),
 (7.1568012, -73.1365006),
 (7.119349, -73.1227416),
 (7.0777422, -73.0945139),
 (7.119349, -73.1227416),
 (7.0724115, -73.1024019),
 (7.0769398, -73.0982988),
 (7.1499711, -73.133389),
 (7.119349, -73.1227416),
 (7.1137821, -73.1358882),
 (7.1038185, -73.1256474),
 (7.0854707, -73.1306983),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.1089841, -73.1141976),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.0702592, -73.111329),
 (7.070812, -73.1070105),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.0614363, -73.1006211),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.0834371, -73.1254528),
 (7.1391178, -73.1277873),
 (7.119349, -73.1227416),
 (7.1315318, -73.1337332),
 (7.0657381, -73.0889407),
 (7.119349, -73.1227416),
 (7.0702592, -73.111329),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.1535145, -73.1317271),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.0803339, -73.171039),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.1116848, -73.106932),
 (7.1188628, -73.1349619),
 (7.1473665, -73.1287468),
 (6.9778994, -73.0494109),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.0845177, -73.0994462),
 (7.119349, -73.1227416),
 (7.1435385, -73.134864),
 (7.1290655, -73.1298292),
 (7.1038185, -73.1256474),
 (7.0845177, -73.0994462),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.1290655, -73.1298292),
 (7.0843496, -73.0998047),
 (7.1384341, -73.1359418),
 (7.119349, -73.1227416),
 (7.0783096, -73.1740717),
 (7.1038185, -73.1256474),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.1449188, -73.1355881),
 (7.1091337, -73.1093561),
 (7.140411, -73.1298794),
 (6.991539, -73.053998),
 (7.1448262, -73.1294356),
 (7.119349, -73.1227416),
 (7.12809, -73.1297),
 (7.1524925, -73.1247661),
 (6.9917116, -73.0573924),
 (7.0631201, -73.0995099),
 (7.119349, -73.1227416),
 (7.0814957, -73.1334435),
 (7.1487272, -73.1400784),
 (7.0515367, -73.1667893),
 (7.119349, -73.1227416),
 (7.1436578, -73.1305548),
 (7.1436578, -73.1305548),
 (7.119349, -73.1227416),
 (7.1397937, -73.1284526),
 (7.0854707, -73.1306983),
 (7.1273297, -73.126868),
 (7.1468591, -73.127204),
 (7.1436578, -73.1305548),
 (7.1391178, -73.1277873),
 (7.1290655, -73.1298292),
 (7.1473665, -73.1287468),
 (7.1156682, -73.1232217),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.1473665, -73.1287468),
 (7.0845177, -73.0994462),
 (7.0784386, -73.1169114),
 (7.119349, -73.1227416),
 (7.1290655, -73.1298292),
 (7.1355731, -73.1313531),
 (7.1050539, -73.1396012),
 (7.1011954, -73.1097772),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.1376098, -73.1177836),
 (6.991539, -73.053998),
 (7.1449188, -73.1355881),
 (7.1473665, -73.1287468),
 (7.119349, -73.1227416),
 (6.9919514, -73.0541104),
 (7.1318061, -73.1174394),
 (7.1473665, -73.1287468),
 (7.1197614, -73.1289138),
 (7.1535145, -73.1317271),
 (6.9778994, -73.0494109),
 (7.122368, -73.1362179),
 ('NA', 'NA'),
 (7.1473665, -73.1287468),
 (7.119349, -73.1227416),
 (7.1391178, -73.1277873),
 (7.0806068, -73.1220556),
 (7.1273297, -73.126868),
 (7.1248485, -73.1302424),
 (7.1170564, -73.1263649),
 (7.140411, -73.1298794),
 (7.1145012, -73.127362),
 (7.1290655, -73.1298292),
 (7.141272, -73.129602),
 (7.1011052, -73.0968493),
 (7.1394532, -73.1235731),
 (7.1351034, -73.131138),
 (7.1384341, -73.1359418),
 (7.0619338, -73.1694591),
 (7.1290655, -73.1298292),
 (7.141272, -73.129602),
 (7.0774535, -73.1727917),
 (6.9852388, -73.0439643),
 (7.110472, -73.1194085),
 (7.1391178, -73.1277873),
 (7.119349, -73.1227416),
 (7.108134, -73.111379),
 (7.0854707, -73.1306983),
 (7.1248485, -73.1302424),
 (7.1473665, -73.1287468),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.1273297, -73.126868),
 (6.9969693, -73.0552854),
 (7.1290655, -73.1298292),
 (7.119349, -73.1227416),
 (7.0811361, -73.1176626),
 (7.1018539, -73.1095351),
 (7.0854707, -73.1306983),
 (7.119349, -73.1227416),
 (7.1290655, -73.1298292),
 (7.1436578, -73.1305548),
 (7.119349, -73.1227416),
 (7.119349, -73.1227416),
 (7.1406362, -73.1333996),
 (7.1405956, -73.133391),
 (7.1073449, -73.1234933),
 (7.086249, -73.139124),
 (7.1290655, -73.1298292),
 (7.1011954, -73.1097772),
 (6.9904765, -73.0552549),
 (7.1304318, -73.4761147),
 (7.1445627, -73.1330469),
 (7.1290655, -73.1298292),
 (7.1439242, -73.129992),
 (7.1011052, -73.0968493),
 (7.119349, -73.1227416)]

In [45]:
#Now let's visualize the dataframe
amb_instantDataScrapper['coordenadas'] = coordenadas_amb
#lets see the last 5 rows
amb_instantDataScrapper.tail()

,nombre_restaurante,tipo_restaurante,puntuacion,cantidad_comentarios,direccion_comercial,tipo_consumo,opciones,entrega,enlace,categoria_puntuacion,geocoding_address,coordenadas
540,Ulala Pizza,· Pizza,4.8,6.0,Carrera. 1C No21-05,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMRPE...,4.5-5.0,"Carrera. 1C No21-05, Bucaramanga, Santander, C...","(7.1445627, -73.1330469)"
541,Aoki Sushi Rolls Piedecuesta,· Japonesa,4.6,77.0,"Carrera 15, Av. 10ª N No7BN-15",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOtCt...,4.5-5.0,"Carrera 15, Av. 10ª N No7BN-15, Bucaramanga, S...","(7.1290655, -73.1298292)"
542,Restaurante San Martin,· · Restaurante,4.2,884.0,"Barrio San Rafael, Carrera 15 No13a - 35",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMUo0...,4.0-4.5,"Barrio San Rafael, Carrera 15 No13a - 35, Buca...","(7.1439242, -73.129992)"
543,Pancha comida tradicional,· Ideal para familias,4.7,132.0,Calle 7 No6-55,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOYh8...,4.5-5.0,"Calle 7 No6-55, Bucaramanga, Santander, Colombia","(7.1011052, -73.0968493)"
544,MAMBAS,· Hamburguesa,4.8,12.0,"Ruitoque condominio, Aldea comercial local 18",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipN_Yd...,4.5-5.0,"Ruitoque condominio, Aldea comercial local 18,...","(7.119349, -73.1227416)"

In [46]:
#Let's extract the geographic coordinates into two separate columns: coordenadas[0] will be the latitude and coordenadas[1] will be the longitude:
amb_instantDataScrapper['latitude'] = amb_instantDataScrapper['coordenadas'].apply(lambda x : x[0])
amb_instantDataScrapper['longitude'] = amb_instantDataScrapper['coordenadas'].apply(lambda x : x[1])
#Let's visualize it
amb_instantDataScrapper.tail()

,nombre_restaurante,tipo_restaurante,puntuacion,cantidad_comentarios,direccion_comercial,tipo_consumo,opciones,entrega,enlace,categoria_puntuacion,geocoding_address,coordenadas,latitude,longitude
540,Ulala Pizza,· Pizza,4.8,6.0,Carrera. 1C No21-05,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMRPE...,4.5-5.0,"Carrera. 1C No21-05, Bucaramanga, Santander, C...","(7.1445627, -73.1330469)",7.144563,-73.133047
541,Aoki Sushi Rolls Piedecuesta,· Japonesa,4.6,77.0,"Carrera 15, Av. 10ª N No7BN-15",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOtCt...,4.5-5.0,"Carrera 15, Av. 10ª N No7BN-15, Bucaramanga, S...","(7.1290655, -73.1298292)",7.129066,-73.129829
542,Restaurante San Martin,· · Restaurante,4.2,884.0,"Barrio San Rafael, Carrera 15 No13a - 35",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipMUo0...,4.0-4.5,"Barrio San Rafael, Carrera 15 No13a - 35, Buca...","(7.1439242, -73.129992)",7.143924,-73.129992
543,Pancha comida tradicional,· Ideal para familias,4.7,132.0,Calle 7 No6-55,NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipOYh8...,4.5-5.0,"Calle 7 No6-55, Bucaramanga, Santander, Colombia","(7.1011052, -73.0968493)",7.101105,-73.096849
544,MAMBAS,· Hamburguesa,4.8,12.0,"Ruitoque condominio, Aldea comercial local 18",NaN,NaN,NaN,https://lh5.googleusercontent.com/p/AF1QipN_Yd...,4.5-5.0,"Ruitoque condominio, Aldea comercial local 18,...","(7.119349, -73.1227416)",7.119349,-73.122742

In [47]:
#Export this CSV to the folder '/resultados_finales'
amb_instantDataScrapper.to_csv('resultados_finales/amb_instantDataScrapper.csv', index=False)