In [1]:
# Data Cleansing Notes
# Data cleansing is mainly done by using pandas.
# In simple terms, Data cleaning/cleansing means fixing bad data in your data set.
# Bad Data could be:
# a) Empty Cells
# b) Data in wrong format
# c) Wrong Data
# d) Duplicates

# Programs:
# 1. Remove all rows with NULL values
# 2. Replace each NAN value with "Not Declared"
# 3. Replace NULL values of "Esalary" column with any other value
# 4. Calculate the mean of Esalary and replace the NAN with mean
# 5. Replace only first occurance for salary by 22000 when it is NAN/NULL
# 6. Cleaning / Correcting the wrong data, changing the Eno from 1005 to 105
# 7. Find Duplicates

In [41]:
# 1. Remove all rows with NULL values

#importing pandas library
import pandas as pd

#Open file in read mode
f1=pd.read_csv('bad_data.csv')

#Remove the rows with NAN (Not A Number) value, and store in 'data' variable
# Note: By default, the dropna() method returns a new DataFrame, and will not change the original.
# in dropna 'na' means Not Applicable
data = f1.dropna()

# If you want to change the original DataFrame, use the inplace = True argument:
# data = f1.dropna(inplace=True)

#Display the CSV file data
data

     Eno   Ename  Esalary
0  101.0  Ename1  10000.0
3  104.0  Ename4  40000.0
5  106.0  Ename6  60000.0
6  106.0  Ename6  60000.0

In [42]:
# 2. Replace each NAN value with "Not Declared"

#import pandas
import pandas as pd

#Read csv file
fo = pd.read_csv("bad_data.csv")

new_data = fo.fillna("Not Declared")

print(new_data.to_string())

            Eno         Ename       Esalary
0         101.0        Ename1       10000.0
1         102.0  Not Declared       20000.0
2  Not Declared        Ename3       30000.0
3         104.0        Ename4       40000.0
4        1005.0        Ename5  Not Declared
5         106.0        Ename6       60000.0
6         106.0        Ename6       60000.0

In [43]:
# 3. Replace NULL values of "Esalary" column with any other value

import pandas as pd

csvFile = pd.read_csv("bad_data.csv")

csvFile['Esalary'].fillna("Not Declared", inplace=True)

print(csvFile.to_string())

      Eno   Ename       Esalary
0   101.0  Ename1       10000.0
1   102.0     NaN       20000.0
2     NaN  Ename3       30000.0
3   104.0  Ename4       40000.0
4  1005.0  Ename5  Not Declared
5   106.0  Ename6       60000.0
6   106.0  Ename6       60000.0

In [44]:
# 4. Calculate the mean of Esalary and replace the NAN with mean

import pandas as pd

fo = pd.read_csv("bad_data.csv")

# Mean = the average value (the sum of all values divided by number of values).
mean = fo['Esalary'].mean()

fo['Esalary'].fillna(mean, inplace=True)

print(fo.to_string())

      Eno   Ename       Esalary
0   101.0  Ename1  10000.000000
1   102.0     NaN  20000.000000
2     NaN  Ename3  30000.000000
3   104.0  Ename4  40000.000000
4  1005.0  Ename5  36666.666667
5   106.0  Ename6  60000.000000
6   106.0  Ename6  60000.000000

In [74]:
# 5. Replace only first occurance for salary by 22000 when it is NAN/NULL

import pandas as pd

fo = pd.read_csv("product.csv")
fo['pprice'].fillna(22000, limit=1, inplace=True)

print(fo.to_string())

#Note: In the output for pno=102 the pprice is 22000, but at last row for pno=102 the pprice is NAN

   pno   pname   pprice  qty
0  101  pname1    100.0   10
1  102  pname2  22000.0   20
2  103     NaN    300.0   30
3  104  pname4    400.0   40
4  102  pname2      NaN   20

In [46]:
# 6. Cleaning / Correcting the wrong data, changing the Eno from 1005 to 105

import pandas as pd

fo = pd.read_csv("bad_data.csv")

#Note: the loc is given based on index value
# syntax of loc is loc[row_no, col_no/name]
fo.loc[4, 'Eno'] = 105

fo

     Eno   Ename  Esalary
0  101.0  Ename1  10000.0
1  102.0     NaN  20000.0
2    NaN  Ename3  30000.0
3  104.0  Ename4  40000.0
4  105.0  Ename5      NaN
5  106.0  Ename6  60000.0
6  106.0  Ename6  60000.0

In [2]:
# 7. Find and remove duplicates

import pandas as pd

fo = pd.read_csv("bad_data.csv")

#print(fo.duplicated())

print(fo.to_string())

      Eno   Ename  Esalary
0   101.0  Ename1  10000.0
1   102.0     NaN  20000.0
2     NaN  Ename3  30000.0
3   104.0  Ename4  40000.0
4  1005.0  Ename5      NaN
5   106.0  Ename6  60000.0
6   106.0  Ename6  60000.0

In [ ]:
#Practical Program on CSV file and data cleansing

# Q. Prepare a file product.csv
# pno, pname, price, qty
# 1. Display all records
# 2. Display records which do not have any null values
# 3. Display record status false/true duplicated.
# 4. Enter price in place where price is NULL
# 5. Skip rows 1 and 3 and print the records
# 6. Wherever price is not there replace with 555 and wherever pname is not there replace it with xyz
# 7. Replace null value for salary column by mean of available salary values.
# 8. Replace null value for salary column by medium of available salary values.

In [53]:
# 1. Displaying all records
import pandas as pd

fo = pd.read_csv("product.csv")

fo

   pno   pname  pprice  qty
0  101  pname1   100.0   10
1  102  pname2     NaN   20
2  103     NaN   300.0   30
3  104  pname4   400.0   40

In [54]:
#2. Display all records from product.csv which do not have null value

import pandas as pd

fo = pd.read_csv("product.csv")

data = fo.dropna()

data

   pno   pname  pprice  qty
0  101  pname1   100.0   10
3  104  pname4   400.0   40

In [56]:
# 3. Display whther records is duplicated (true) or not (false)

import pandas as pd
fo = pd.read_csv("product.csv")

fo.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [58]:
# 4. Enter price in place where price is NULL

import pandas as pd
fo = pd.read_csv("product.csv")
fo['pprice'].fillna("90000", inplace=True)

print(fo.to_string())

   pno   pname pprice  qty
0  101  pname1  100.0   10
1  102  pname2  90000   20
2  103     NaN  300.0   30
3  104  pname4  400.0   40
4  102  pname2  90000   20

In [65]:
# 5. Skip rows 1 and 3 and print the records

import pandas as pd

fo = pd.read_csv("product.csv", skiprows=[1,3])

fo

   pno   pname  pprice  qty
0  102  pname2     NaN   20
1  104  pname4   400.0   40
2  102  pname2     NaN   20

In [69]:
# 6. Wherever price is not there replace with 555 and wherever pname is not there replace it with xyz

import pandas as pd
fo = pd.read_csv("product.csv")

#Wherever price is NAN fill with 555
fo['pprice'].fillna(555, inplace=True)

#Wherever pname is NAN fill with XYZ
fo['pname'].fillna("XYZ", inplace=True)

print(fo.to_string())

   pno   pname  pprice  qty
0  101  pname1   100.0   10
1  102  pname2   555.0   20
2  103     XYZ   300.0   30
3  104  pname4   400.0   40
4  102  pname2   555.0   20

In [70]:
# 7. Replace null value for salary column by mean of available salary values.

import pandas as pd

fo = pd.read_csv("product.csv")

#calculate and Store the mean value of entire pprice column
mean = fo['pprice'].mean()

#Replace pprice NAN value with mean
fo['pprice'].fillna(mean, inplace=True)

print(fo.to_string())

   pno   pname      pprice  qty
0  101  pname1  100.000000   10
1  102  pname2  266.666667   20
2  103     NaN  300.000000   30
3  104  pname4  400.000000   40
4  102  pname2  266.666667   20

In [71]:
# 8. Replace null value for salary column by medium of available salary values.

import pandas as pd
fo = pd.read_csv("product.csv")
median = fo['pprice'].median()
fo['pprice'].fillna(median, inplace=True)

print(fo.to_string())

   pno   pname  pprice  qty
0  101  pname1   100.0   10
1  102  pname2   300.0   20
2  103     NaN   300.0   30
3  104  pname4   400.0   40
4  102  pname2   300.0   20