# KUIS 2 Pembelajaran Mesin

## Tentang dataset

Pada sebuah lembaga kemanusiaan berbasis teknologi informasi, dibentuk beberapa tim kemanusiaan yang bertugas untuk terjun ke masyarakat memberikan bantuan dalam bentuk aplikasi komputer atau layanan pelatihan IT.  Kegiatn tersebut dilaksanakan setiap tahun dengan ketentuan anggota organisasi tersebut dapat bergabung ke beberapa tim sebagai ketua atau anggota. Terdapat pula anggota yang sudah tidak aktif di organisasi tersebut (terhapus di database mereka —> label N/A).  Organisasi tersebut juga melakukan rekrutmen volunteer, namun tidak semua tim menggunakan bantuan volunteer. Hasil kegiatan dari setiap tim dapat diwujudkan ke dalam sebuah pengakuan hak cipta atau publikasi karya ilmiah atau publikasi berita di media massa.

## Ketentuan
1. Pengerjaan secara individu alias setiap mahasiswa!
2. Terdapat data dengan nilai #N/A, pertimbangkan cara terbaik untuk mengatasi nilai tersebut.
3. Tidak boleh ada duplikasi pekerjaan antar mahasiswa
4. Berikan penjelasan untuk setiap tahapan. Jangan hanya kode!

## Soal
1. Lakukan pemilahan data training dan testing yang sesuai dan proporsional dari data tersebut! (10 poin)
2. Tentukan data validasi! (10 poin)
3. Tentukan secara tepat kolom yang menjadi "label" (20 poin)
4. Terapkan dua jenis metode klasifikasi dan lakukan perbandingan akurasi  dengan wajib melibatkan variabel keterlibatan volunteer sampai variabel luaran-luaran yang dihasilkan! (20 poin)
5. Lakukan tunning hyperparameter berdasarkan hasil klasifikasi pada nomor 3 menggunakan metode Grid Search dan Random Search! Simpulkan parameter apa yang paling baik digunakan berdasarkan metode klasifikasi yang dipilih, dan berapa akurasinya. (40 poin)

In [82]:
import pandas as pd

df = pd.read_excel('data/dataset_quiz.xlsx')

df.head(100)

,id_ketua,id_anggota1,id_anggota2,id_anggota3,id_anggota4,id_anggota5,keterlibatan_vltr,jml_vltr_terlibat,tahun,skema,luaran_hki,jenis_luaran_hki,potensi_hki,luaran_lain,jenis_luaran_lain,status_luaran_lain
0,7206.0,7214.0,6211.0,8602.0,7801.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
1,7214.0,7109.0,8402.0,7903.0,9202.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
2,5911.0,8201.0,8701.0,9101.0,9003.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
3,8402.0,7702.0,8602.0,8903.0,8903.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
4,8201.0,8305.0,5911.0,5903.0,8402.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,8803.0,8804.0,9102.0,8005.0,9303.0,NaN,YA,3,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
81,6211.0,8901.0,9003.0,9303.0,9007.0,NaN,YA,3,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
82,8601.0,8903.0,8703.0,NaN,NaN,NaN,YA,3,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
83,8703.0,8601.0,9202.0,9102.0,6204.0,NaN,YA,3,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
84,8102.0,7109.0,5903.0,7206.0,8903.0,NaN,TIDAK,0,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA

In [83]:
df.isna().sum()

id_ketua               3
id_anggota1            5
id_anggota2            4
id_anggota3            3
id_anggota4           13
id_anggota5           84
keterlibatan_vltr      0
jml_vltr_terlibat      0
tahun                  0
skema                  0
luaran_hki             0
jenis_luaran_hki       0
potensi_hki            0
luaran_lain            0
jenis_luaran_lain      0
status_luaran_lain     0
dtype: int64

In [84]:
# Menghilangkan data null
df.drop('id_anggota5', axis=1, inplace=True)

modus_ketua = df['id_ketua'].mode()[0]
df['id_ketua'] = df['id_ketua'].fillna(modus_ketua)

modus_anggota1 = df['id_anggota1'].mode()[0]
df['id_anggota1'] = df['id_anggota1'].fillna(modus_anggota1)

modus_anggota2 = df['id_anggota2'].mode()[0]
df['id_anggota2'] = df['id_anggota2'].fillna(modus_anggota2)

modus_anggota3 = df['id_anggota3'].mode()[0]
df['id_anggota3'] = df['id_anggota3'].fillna(modus_anggota3)

modus_anggota4 = df['id_anggota4'].mode()[0]
df['id_anggota4'] = df['id_anggota4'].fillna(modus_anggota4)
# Cek Data
df.head()

,id_ketua,id_anggota1,id_anggota2,id_anggota3,id_anggota4,keterlibatan_vltr,jml_vltr_terlibat,tahun,skema,luaran_hki,jenis_luaran_hki,potensi_hki,luaran_lain,jenis_luaran_lain,status_luaran_lain
0,7206.0,7214.0,6211.0,8602.0,7801.0,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
1,7214.0,7109.0,8402.0,7903.0,9202.0,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
2,5911.0,8201.0,8701.0,9101.0,9003.0,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
3,8402.0,7702.0,8602.0,8903.0,8903.0,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
4,8201.0,8305.0,5911.0,5903.0,8402.0,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA

1. Lakukan pemilahan data training dan testing yang sesuai dan proporsional dari data tersebut! (10 poin)

In [85]:
# Melakukan Pemilahan data Training dan Testing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

df['skema']=encoder.fit_transform(df['skema'])
df['luaran_hki']=encoder.fit_transform(df['luaran_hki'])
df['jenis_luaran_hki']=encoder.fit_transform(df['jenis_luaran_hki'])
df['potensi_hki']=encoder.fit_transform(df['potensi_hki'])
df['luaran_lain']=encoder.fit_transform(df['luaran_lain'])
df['jenis_luaran_lain']=encoder.fit_transform(df['jenis_luaran_lain'])
df['status_luaran_lain']=encoder.fit_transform(df['status_luaran_lain'])
df['keterlibatan_vltr']=encoder.fit_transform(df['keterlibatan_vltr'])

X = df.drop(['keterlibatan_vltr'], axis=1)
y = df['keterlibatan_vltr']

X = pd.get_dummies(X)

2. Tentukan data validasi! (10 poin)

In [86]:
from sklearn.model_selection import train_test_split
df_train, df_unseen = train_test_split(df, test_size=0.2, random_state=3, stratify=df['keterlibatan_vltr'])

# validasi data
df_val, df_test = train_test_split(df_unseen, test_size=0.5,random_state =0, stratify=df_unseen['keterlibatan_vltr'])

3. Tentukan secara tepat kolom yang menjadi "label" (20 poin)

In [87]:
# mengimport label encoder
from sklearn import preprocessing
# mendefinisikan label encoder
le = preprocessing.LabelEncoder()
# encode label yang ada dalam kolom 'keterkibatann_vltr'
df['keterlibatan_vltr']= le.fit_transform(df['keterlibatan_vltr'])
df['jenis_luaran_lain']= le.fit_transform(df['jenis_luaran_lain'])
df['status_luaran_lain']= le.fit_transform(df['status_luaran_lain'])
df['jenis_luaran_hki']= le.fit_transform(df['jenis_luaran_hki'])
df['luaran_hki']= le.fit_transform(df['luaran_hki'])
df['potensi_hki']= le.fit_transform(df['potensi_hki'])
df['luaran_lain']= le.fit_transform(df['luaran_lain'])
df['skema']= le.fit_transform(df['skema'])
# menggunakan Decision Tree
# dengan variabel keterlibatan volunter sampai hasil keluaran yang didapatkan
x = df.iloc[:,6:16]
y = df['tahun']
x.head()

,jml_vltr_terlibat,tahun,skema,luaran_hki,jenis_luaran_hki,potensi_hki,luaran_lain,jenis_luaran_lain,status_luaran_lain
0,0,2019,1,1,1,2,0,3,1
1,0,2019,1,1,1,2,0,3,1
2,0,2019,1,1,1,2,0,3,1
3,0,2019,1,1,1,2,0,3,1
4,0,2019,1,1,1,2,0,3,1

4. Terapkan dua jenis metode klasifikasi dan lakukan perbandingan akurasi  dengan wajib melibatkan variabel keterlibatan volunteer sampai variabel luaran-luaran yang dihasilkan! (20 poin)

Menggunakan Decision Tree

In [88]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

params = {
    'criterion': ['entropy','gini'], 
    'max_depth': [2,4,6,8,10,12]
}

dt = DecisionTreeClassifier()
grid_random = GridSearchCV(dt, param_grid=params, cv=cv, n_jobs=-1)
result= grid_random.fit(X,y)

best_accuracy = grid_random.best_score_
best_parameters = grid_random.best_params_

print('Best Accuracy: {:.2f} %'.format(best_accuracy*100))

Best Accuracy: 100.00 %

Menggunkan SVC

In [89]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

svc = SVC()

params = {
    'kernel' : ['linear', 'poly', 'rbf'],
    'degree' :[1,2,3,4,5,6,7,8,9,10] ,
    'C':[1,5,10,50],
}

grid_search = GridSearchCV(svc, param_grid=params, cv=cv, n_jobs=-1)
result= grid_search.fit(X,y)

best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

print('Best Accuracy: {:.2f} %'.format(best_accuracy*100))

Best Accuracy: 47.40 %

5. Lakukan tunning hyperparameter berdasarkan hasil klasifikasi pada nomor 3 menggunakan metode Grid Search dan Random Search! Simpulkan parameter apa yang paling baik digunakan berdasarkan metode klasifikasi yang dipilih, dan berapa akurasinya. (40 poin)

In [90]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import RandomizedSearchCV

params = {
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': list(range(5,11))
}

dt = DecisionTreeClassifier()
grid_random = RandomizedSearchCV(dt, param_distributions=params, n_iter=5 , cv=cv, n_jobs=-1, random_state=1)
result= grid_random.fit(X,y)

print('Hasil evaluasi: %s' % result.best_score_)
print('Konfigurasi hyperparameter: %s' % result.best_params_)

Hasil evaluasi: 1.0
Konfigurasi hyperparameter: {'max_depth': 5, 'criterion': 'entropy'}

In [91]:
from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV

svc = SVC()

params = {
    'kernel' : ['linear', 'poly', 'rbf'],
    'degree' :[1,2,3,4,5,6,7,8,9,10] ,
    'C':[1,5,10,50],
}

grid_random = RandomizedSearchCV(svc, n_iter=5, param_distributions=params, cv=cv, n_jobs=-1)
result= grid_random.fit(X,y)

print('Hasil evaluasi: %s' % result.best_score_)
print('Konfigurasi hyperparameter: %s' % result.best_params_)

Hasil evaluasi: 0.4740259740259741
Konfigurasi hyperparameter: {'kernel': 'linear', 'degree': 5, 'C': 10}

Hasil yang terbaik menurut hasil saya adalah menggunkan Decision Tree