# Partition Cell Types Deepclean

Perform deepcleaning removal of doublet clusters based on manual annotation

Relabel L3 AIFI cell type labels based on deepcleaning manual annotations

## Load libraries

In [17]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=RuntimeWarning)

import concurrent.futures
from concurrent.futures import ThreadPoolExecutor
from datetime import date
import hisepy
import os
import pandas as pd
import re
import scanpy as sc
import scanpy.external as sce
import glob

In [2]:
out_dir = 'output'
if not os.path.isdir(out_dir):
    os.makedirs(out_dir)

## Helper functions

These make it a bit simpler to cache and read in files from HISE

In [3]:
def cache_uuid_path(uuid):
    cache_path = '/home/jupyter/cache/{u}'.format(u = uuid)
    if not os.path.isdir(cache_path):
        hise_res = hisepy.reader.cache_files([uuid])
    filename = os.listdir(cache_path)[0]
    cache_file = '{p}/{f}'.format(p = cache_path, f = filename)
    return cache_file

In [4]:
def read_parquet_uuid(uuid):
    cache_file = cache_uuid_path(uuid)
    res = pd.read_parquet(cache_file)
    return res

In [5]:
def sort_adata_uuid(uuid, sort_cols = ['AIFI_L2', 'sample.sampleKitGuid']):
    cache_file = cache_uuid_path(uuid)
    adata = sc.read_h5ad(cache_file)
    obs = adata.obs
    obs = obs.sort_values(sort_cols)
    adata = adata[obs.index]
    adata.write_h5ad(cache_file)

This function will enable us to connect to our .h5ad files without loading the entire thing into memory. We'll then load only the cells that we want for each cell class to assemble them for writing. This should save us some overhead as we do our subsetting.

In [6]:
def read_adata_backed_uuid(uuid):
    cache_file = cache_uuid_path(uuid)
    res = sc.read_h5ad(cache_file, backed = 'r')
    return res

This function will remove Ig-related genes, which is recommended by Marla Glass for analysis of B cell subtypes

In [7]:
def remove_ig_genes(adata):
    igl_genes = [gene for gene in adata.var_names if gene.startswith("IGL")]
    igk_genes = [gene for gene in adata.var_names if gene.startswith("IGK")]
    ighc_genes = [gene for gene in adata.var_names if gene.startswith("IGH")]
    exl_genes = igl_genes + igk_genes + ighc_genes

    filtered_genes = [gene for gene in adata.var_names if gene not in exl_genes]
    adata = adata[:, filtered_genes]

    return adata

This function will apply a standard normalization, nearest neighbors, clustering, and UMAP process to our cell subsets:

In [8]:
def process_adata(adata, resolution = 2):
    
    # Keep a copy of the raw data
    adata = adata.raw.to_adata()
    adata.raw = adata

    print('Normalizing', end = "; ")
    # Normalize and log transform
    sc.pp.normalize_total(adata)
    sc.pp.log1p(adata)

    print('Finding HVGs', end = "; ")
    # Restrict downstream steps to variable genes
    sc.pp.highly_variable_genes(adata)
    adata = adata[:, adata.var_names[adata.var['highly_variable']]].copy()

    print('Scaling', end = "; ")
    # Scale variable genes
    sc.pp.scale(adata)

    print('PCA', end = "; ")
    # Run PCA
    sc.tl.pca(adata, svd_solver = 'arpack')
    
    print('Neighbors', end = "; ")
    # Find nearest neighbors
    sc.pp.neighbors(
        adata, 
        n_neighbors = 50,
        n_pcs = 30
    )

    print('Leiden', end = "; ")
    # Find clusters
    sc.tl.leiden(
        adata, 
        resolution = resolution, 
        key_added = 'leiden_{r}'.format(r = resolution),
        n_iterations = 2
    )

    print('UMAP', end = "; ")
    # Run UMAP
    sc.tl.umap(adata, min_dist = 0.05)
    
    print('Renormalizing')
    adata = adata.raw.to_adata()
    adata.raw = adata

    # Normalize and log transform
    sc.pp.normalize_total(adata)
    sc.pp.log1p(adata)
    
    return adata

In [9]:
def format_cell_type(cell_type):
    cell_type = re.sub('\\+', 'pos', cell_type)
    cell_type = re.sub('-', 'neg', cell_type)
    cell_type = re.sub(' ', '_', cell_type)
    return cell_type

In [10]:
def element_id(n = 3):
    import periodictable
    from random import randrange
    rand_el = []
    for i in range(n):
        el = randrange(0,118)
        rand_el.append(periodictable.elements[el].name)
    rand_str = '-'.join(rand_el)
    return rand_str

In [11]:
# make a function to find files
def get_filepaths_with_glob(root_path: str, file_regex: str):
    return glob.glob(os.path.join(root_path, file_regex))

In [177]:
# Define a function to extract the desired substring using regex
def extract_substring(path, pattern = r'preRA_cluster_harmonize_(.*?)_\d{4}-\d{2}-\d{2}\.h5ad'):
    #pattern = r'preRA_cluster_harmonize_(.*?)_\d{4}-\d{2}-\d{2}\.h5ad'
    match = re.search(pattern, path)
    if match:
        return match.group(1)
    return None

In [13]:
def read_anndata_files(file_tuples):
    """
    Read Anndata objects from H5AD files and store them in a dictionary with custom names.

    Parameters:
        file_tuples (list of tuples): List of tuples where each tuple contains filename and desired name.

    Returns:
        dict: Dictionary containing Anndata objects with custom names.
    """
    anndata_dict = {}
    for filename, name in file_tuples:
        anndata_obj = anndata.read_h5ad(filename)
        anndata_dict[name] = anndata_obj
    return anndata_dict

In [14]:
def reformat_cell_type(cell_type):
    '''convert cell type names read in from file back to original L3 labels'''
    cell_type = re.sub('pos', '+', cell_type)
    cell_type = re.sub('neg', '-', cell_type)
    cell_type = re.sub('_',' ', cell_type)
    return cell_type

## Identify files for use in HISE

In [15]:
search_id = 'polonium-strontium-zirconium'

Retrieve files stored in our HISE project store

In [18]:
ps_df = hisepy.list_files_in_project_store('UCSDCU_Y4')
ps_df = ps_df[['id', 'name']]

Filter for files from the previous notebook using our search_id

In [19]:
search_df = ps_df[ps_df['name'].str.contains(search_id)]
search_df = search_df.sort_values('name')

In [20]:
h5ad_df = search_df[search_df['name'].str.contains('.h5ad')]

In [21]:
h5ad_df

,id,name
410,704874eb-d661-4ca3-bb4c-a0f4c20c5fe9,polonium-strontium-zirconium/preRA_cluster_har...
411,3ccbd155-2b80-4fd7-8988-ef4462198ccf,polonium-strontium-zirconium/preRA_cluster_har...
412,2db8c682-b9da-4be7-87ce-4449618222e8,polonium-strontium-zirconium/preRA_cluster_har...
413,3d754896-d258-449e-9739-f6d921607201,polonium-strontium-zirconium/preRA_cluster_har...
414,00a560a8-499c-4cc3-98fc-b4f93f6f0d91,polonium-strontium-zirconium/preRA_cluster_har...
...,...,...
476,e7ae8e4e-c9f5-4798-9a7a-7fbd7f6593e2,polonium-strontium-zirconium/preRA_cluster_har...
477,40e4d947-9308-4ada-8681-e62f66a37077,polonium-strontium-zirconium/preRA_cluster_har...
478,b01b7837-cb0b-4c57-ba62-e133943e9852,polonium-strontium-zirconium/preRA_cluster_har...
479,b75ca414-cb11-402f-aea5-8d1e000a2dad,polonium-strontium-zirconium/preRA_cluster_har...
480,9aa7bc6c-306e-41ab-be7a-5776708e41e3,polonium-strontium-zirconium/preRA_cluster_har...

In [22]:
h5ad_uuids = {}
for i in range(h5ad_df.shape[0]):
    fn = h5ad_df['name'].tolist()[i]
    group_name = re.sub('.+pbmc_', '', fn)
    group_name = re.sub('_init.+', '', group_name)
    h5ad_uuids[group_name] = h5ad_df['id'].tolist()[i]

In [23]:
h5ad_uuids

{'polonium-strontium-zirconium/preRA_cluster_harmonize_ASDC_2024-05-25.h5ad': '704874eb-d661-4ca3-bb4c-a0f4c20c5fe9',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Activated_memory_B_cell_2024-05-25.h5ad': '3ccbd155-2b80-4fd7-8988-ef4462198ccf',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Adaptive_NK_cell_2024-05-25.h5ad': '2db8c682-b9da-4be7-87ce-4449618222e8',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_BaEoMaP_cell_2024-05-25.h5ad': '3d754896-d258-449e-9739-f6d921607201',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_C1Qpos_CD16_monocyte_2024-05-25.h5ad': '00a560a8-499c-4cc3-98fc-b4f93f6f0d91',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_CD14pos_cDC2_2024-05-25.h5ad': '63217d12-5f51-4668-9ad8-dea66b394581',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_CD27neg_effector_B_cell_2024-05-25.h5ad': 'f9d59339-9182-48e0-abf2-8a4d48cee5f6',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_CD27pos_effector_B_cell_2024-05-25.h5ad': 'abd08fae-e2ed-4a09-8c2e-38c2531c56eb',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_CD4_MAIT_2024-05-25.h5ad': '6edd318c-5481-4b7c-99a6-f4cdcd44daba',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_CD56bright_NK_cell_2024-05-25.h5ad': '68a4eda0-8312-4f07-a661-c834dcc403f7',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_CD8_MAIT_2024-05-25.h5ad': 'fe28ae5f-8f35-49ec-a1d8-6a5723c1d80f',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_CD8aa_2024-05-25.h5ad': '38d11eaf-6f15-4908-8b23-90990b55ec98',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_CD95_memory_B_cell_2024-05-25.h5ad': '5a22953e-96a2-4b38-b79f-edddaf98ad39',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_CLP_cell_2024-05-25.h5ad': '8c9ccdaa-30c5-4afa-ae8a-9d88e008ef18',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_CMP_cell_2024-05-26.h5ad': '920734fd-943d-42b2-8216-7fc458e30c77',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_CM_CD4_T_cell_2024-05-26.h5ad': '23088aa5-7ec2-4e2a-a117-a83c2c0485d7',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_CM_CD8_T_cell_2024-05-26.h5ad': '69fd7a3a-b26e-4cb3-b3cd-76584c7f25ea',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Core_CD14_monocyte_2024-05-26.h5ad': '2d91757a-efcb-4428-b396-0d82abebbbfa',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Core_CD16_monocyte_2024-05-26.h5ad': '8083ad79-29cb-4838-81b6-9481b348b8b7',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Core_memory_B_cell_2024-05-26.h5ad': '2e5e1d81-855d-4fc7-ba30-d5a69904ba4d',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Core_naive_B_cell_2024-05-25.h5ad': '80d25082-5f70-4f4e-9ef1-c9d0373c7061',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Core_naive_CD4_T_cell_2024-05-26.h5ad': '6a34dd0b-d984-4397-a049-92b3782fb327',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Core_naive_CD8_T_cell_2024-05-26.h5ad': '8d68c740-389d-4e68-bda8-aad6dde3ee10',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_DN_T_cell_2024-05-26.h5ad': '0eeb81ba-3caa-4d76-95b8-05346f4a405b',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Early_memory_B_cell_2024-05-26.h5ad': 'e8439aa9-7a54-4630-a461-a5959cd06ee9',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Erythrocyte_2024-05-26.h5ad': '8c10e2e8-f3e7-4161-9f6d-730e26867137',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_GZMBneg_CD27neg_EM_CD4_T_cell_2024-05-26.h5ad': 'c93c7614-3d3f-4b36-a6f3-c94808dc754c',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_GZMBneg_CD27pos_EM_CD4_T_cell_2024-05-26.h5ad': '82601892-b723-4e00-8e10-dd42dd2bab07',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_GZMBpos_Vd2_gdT_2024-05-26.h5ad': '08214f7b-7e51-4675-a08c-aa89d69e5c38',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_GZMKneg_CD27pos_EM_CD8_T_cell_2024-05-26.h5ad': '2c909fb5-59ab-4ac1-914e-c5cb85d887e2',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_GZMKneg_CD56dim_NK_cell_2024-05-26.h5ad': 'e192cec7-80da-48d9-92da-637dd882545d',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_GZMKpos_CD27pos_EM_CD8_T_cell_2024-05-26.h5ad': '3fbf1be4-1bdb-4527-a057-49f78e994ffe',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_GZMKpos_CD56dim_NK_cell_2024-05-26.h5ad': '4e6c035a-01f9-40c0-a4b6-35ef1d85f851',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_GZMKpos_Vd2_gdT_2024-05-26.h5ad': 'ddb00ae9-f991-42c3-90e1-58e32472ee8a',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_GZMKpos_memory_CD4_Treg_2024-05-26.h5ad': 'f917166f-82be-4a15-91c0-d2be939d8120',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_HLAnegDRhi_cDC2_2024-05-26.h5ad': '5c3e9fba-478f-4696-9236-38029a809bbd',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_IL1Bpos_CD14_monocyte_2024-05-26.h5ad': '0780fec0-7794-4afa-ab0a-c538cc31a672',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_ILC_2024-05-26.h5ad': 'a1171673-91fc-48ba-955d-cc45fbee344d',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_ISGpos_CD14_monocyte_2024-05-26.h5ad': '1e89c310-6a42-4224-b547-0b8f086ebfaf',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_ISGpos_CD16_monocyte_2024-05-26.h5ad': 'db05eef8-d40c-4e3d-9365-b7984ea62065',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_ISGpos_CD56dim_NK_cell_2024-05-26.h5ad': 'b17bf7c1-5435-4d92-b479-cb462a57c93c',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_ISGpos_MAIT_2024-05-26.h5ad': '7b73ff6f-2e2b-468c-be5b-811f5bb15f96',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_ISGpos_cDC2_2024-05-26.h5ad': '2112e53e-f357-4d95-9831-6cfff886c954',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_ISGpos_memory_CD4_T_cell_2024-05-26.h5ad': 'c259f7c6-23cd-442c-90a1-56c4b153af18',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_ISGpos_memory_CD8_T_cell_2024-05-26.h5ad': '19a2a355-4d96-4952-9b84-eedef5660405',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_ISGpos_naive_B_cell_2024-05-26.h5ad': '18479084-1a31-444d-aca1-73421a2aa520',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_ISGpos_naive_CD4_T_cell_2024-05-26.h5ad': 'e31f44b4-72e6-4ed8-8c6a-3e7b426fe160',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_ISGpos_naive_CD8_T_cell_2024-05-26.h5ad': '45dff235-37ec-4223-8ae8-f3d3c9f929cb',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Intermediate_monocyte_2024-05-26.h5ad': 'd2173f6f-ac47-4137-a571-006dc1b3ddb5',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_KLRB1pos_memory_CD4_Treg_2024-05-26.h5ad': '4b75bb8e-8872-4f3a-a143-00892d04ccb3',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_KLRB1pos_memory_CD8_Treg_2024-05-26.h5ad': 'd9616844-52df-4e63-b620-f4aec42f6f5a',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-05-26.h5ad': 'c8f1d77e-b7f4-4754-b52f-2b854dc4b687',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell_2024-05-26.h5ad': '66035192-6ac4-4ee0-8054-8ab1cf8021da',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_KLRF1neg_effector_Vd1_gdT_2024-05-26.h5ad': 'baacbafe-11f7-4efb-b024-38780aa5e3df',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-05-26.h5ad': 'a03e9b68-9ad4-43e1-99e0-fd9f13bf9683',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_KLRF1pos_effector_Vd1_gdT_2024-05-26.h5ad': 'e7cf9937-2ec9-45ef-9483-965022d5721c',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Memory_CD4_Treg_2024-05-26.h5ad': '2076d543-5e12-4b9c-bfee-24f9b4ae8bc0',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Memory_CD8_Treg_2024-05-26.h5ad': 'a0e9d362-1b63-4ad5-b372-732978c17910',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Naive_CD4_Treg_2024-05-26.h5ad': 'd64015a7-ba44-40f0-b880-ad15d75da56d',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Naive_Vd1_gdT_2024-05-26.h5ad': '122a79ae-7c62-4152-a0cc-7416e8b88e97',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Plasma_cell_2024-05-26.h5ad': '67fba28c-48b2-4d5c-b909-ebda0c75933e',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Platelet_2024-05-26.h5ad': '4ddfd9c7-7de0-491b-9054-8781f0608380',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Proliferating_NK_cell_2024-05-26.h5ad': '700213a0-42c9-4e2b-a659-beeb275f0b17',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Proliferating_T_cell_2024-05-26.h5ad': '687a4f2c-c12b-4275-bcd4-a15ef20839d1',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_SOX4pos_Vd1_gdT_2024-05-26.h5ad': '21c1c91e-c055-4cb4-a0d7-23476271f0af',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_SOX4pos_naive_CD4_T_cell_2024-05-26.h5ad': '6731b94c-44b4-4646-a024-11da840fadca',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_SOX4pos_naive_CD8_T_cell_2024-05-26.h5ad': 'e7ae8e4e-c9f5-4798-9a7a-7fbd7f6593e2',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Transitional_B_cell_2024-05-26.h5ad': '40e4d947-9308-4ada-8681-e62f66a37077',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_Type_2_polarized_memory_B_cell_2024-05-26.h5ad': 'b01b7837-cb0b-4c57-ba62-e133943e9852',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_cDC1_2024-05-26.h5ad': 'b75ca414-cb11-402f-aea5-8d1e000a2dad',
 'polonium-strontium-zirconium/preRA_cluster_harmonize_pDC_2024-05-26.h5ad': '9aa7bc6c-306e-41ab-be7a-5776708e41e3'}

In [24]:
len(h5ad_uuids)

71

## Download and sort .h5ad files

Sorting the .h5ad files by AIFI_L2 will make reading each cell type much faster by placing cells of the same type next to each other in the sparse matrix.

In [ ]:

# run once
for uuid in h5ad_uuids.values():
    sort_adata_uuid(uuid, sort_cols = ['AIFI_L3'])

downloading fileID: 704874eb-d661-4ca3-bb4c-a0f4c20c5fe9
Files have been successfully downloaded!
downloading fileID: 3ccbd155-2b80-4fd7-8988-ef4462198ccf
Files have been successfully downloaded!
downloading fileID: 2db8c682-b9da-4be7-87ce-4449618222e8
Files have been successfully downloaded!
downloading fileID: 3d754896-d258-449e-9739-f6d921607201
Files have been successfully downloaded!
downloading fileID: 00a560a8-499c-4cc3-98fc-b4f93f6f0d91
Files have been successfully downloaded!
downloading fileID: 63217d12-5f51-4668-9ad8-dea66b394581
Files have been successfully downloaded!
downloading fileID: f9d59339-9182-48e0-abf2-8a4d48cee5f6
Files have been successfully downloaded!
downloading fileID: abd08fae-e2ed-4a09-8c2e-38c2531c56eb
Files have been successfully downloaded!
downloading fileID: 6edd318c-5481-4b7c-99a6-f4cdcd44daba
Files have been successfully downloaded!
downloading fileID: 68a4eda0-8312-4f07-a661-c834dcc403f7
Files have been successfully downloaded!
downloading fileID: fe28ae5f-8f35-49ec-a1d8-6a5723c1d80f
Files have been successfully downloaded!
downloading fileID: 38d11eaf-6f15-4908-8b23-90990b55ec98
Files have been successfully downloaded!
downloading fileID: 5a22953e-96a2-4b38-b79f-edddaf98ad39
Files have been successfully downloaded!
downloading fileID: 8c9ccdaa-30c5-4afa-ae8a-9d88e008ef18
Files have been successfully downloaded!
downloading fileID: 920734fd-943d-42b2-8216-7fc458e30c77
Files have been successfully downloaded!
downloading fileID: 23088aa5-7ec2-4e2a-a117-a83c2c0485d7
Files have been successfully downloaded!
downloading fileID: 69fd7a3a-b26e-4cb3-b3cd-76584c7f25ea
Files have been successfully downloaded!
downloading fileID: 2d91757a-efcb-4428-b396-0d82abebbbfa
Files have been successfully downloaded!
downloading fileID: 8083ad79-29cb-4838-81b6-9481b348b8b7
Files have been successfully downloaded!
downloading fileID: 2e5e1d81-855d-4fc7-ba30-d5a69904ba4d
Files have been successfully downloaded!
downloading fileID: 80d25082-5f70-4f4e-9ef1-c9d0373c7061
Files have been successfully downloaded!
downloading fileID: 6a34dd0b-d984-4397-a049-92b3782fb327
Files have been successfully downloaded!
downloading fileID: 8d68c740-389d-4e68-bda8-aad6dde3ee10
Files have been successfully downloaded!
downloading fileID: 0eeb81ba-3caa-4d76-95b8-05346f4a405b
Files have been successfully downloaded!
downloading fileID: e8439aa9-7a54-4630-a461-a5959cd06ee9
Files have been successfully downloaded!
downloading fileID: 8c10e2e8-f3e7-4161-9f6d-730e26867137
Files have been successfully downloaded!
downloading fileID: c93c7614-3d3f-4b36-a6f3-c94808dc754c
Files have been successfully downloaded!
downloading fileID: 82601892-b723-4e00-8e10-dd42dd2bab07
Files have been successfully downloaded!
downloading fileID: 08214f7b-7e51-4675-a08c-aa89d69e5c38
Files have been successfully downloaded!
downloading fileID: 2c909fb5-59ab-4ac1-914e-c5cb85d887e2
Files have been successfully downloaded!
downloading fileID: e192cec7-80da-48d9-92da-637dd882545d
Files have been successfully downloaded!
downloading fileID: 3fbf1be4-1bdb-4527-a057-49f78e994ffe
Files have been successfully downloaded!
downloading fileID: 4e6c035a-01f9-40c0-a4b6-35ef1d85f851
Files have been successfully downloaded!
downloading fileID: ddb00ae9-f991-42c3-90e1-58e32472ee8a
Files have been successfully downloaded!
downloading fileID: f917166f-82be-4a15-91c0-d2be939d8120
Files have been successfully downloaded!
downloading fileID: 5c3e9fba-478f-4696-9236-38029a809bbd
Files have been successfully downloaded!
downloading fileID: 0780fec0-7794-4afa-ab0a-c538cc31a672
Files have been successfully downloaded!
downloading fileID: a1171673-91fc-48ba-955d-cc45fbee344d
Files have been successfully downloaded!
downloading fileID: 1e89c310-6a42-4224-b547-0b8f086ebfaf
Files have been successfully downloaded!
downloading fileID: db05eef8-d40c-4e3d-9365-b7984ea62065
Files have been successfully downloaded!
downloading fileID: b17bf7c1-5435-4d92-b479-cb462a57c93c
Files have been successfully downloaded!
downloading fileID: 7b73ff6f-2e2b-468c-be5b-811f5bb15f96
Files have been successfully downloaded!
downloading fileID: 2112e53e-f357-4d95-9831-6cfff886c954
Files have been successfully downloaded!
downloading fileID: c259f7c6-23cd-442c-90a1-56c4b153af18
Files have been successfully downloaded!
downloading fileID: 19a2a355-4d96-4952-9b84-eedef5660405
Files have been successfully downloaded!
downloading fileID: 18479084-1a31-444d-aca1-73421a2aa520
Files have been successfully downloaded!
downloading fileID: e31f44b4-72e6-4ed8-8c6a-3e7b426fe160
Files have been successfully downloaded!
downloading fileID: 45dff235-37ec-4223-8ae8-f3d3c9f929cb
Files have been successfully downloaded!
downloading fileID: d2173f6f-ac47-4137-a571-006dc1b3ddb5
Files have been successfully downloaded!
downloading fileID: 4b75bb8e-8872-4f3a-a143-00892d04ccb3
Files have been successfully downloaded!
downloading fileID: d9616844-52df-4e63-b620-f4aec42f6f5a

## Open connections to .h5ad files

Now that they're sorted, we can open these files with on-disk backing so we don't have to read the entire file at once.

## Process files

In [25]:
input_path = "../../05-clustering/scripts/output/"

In [26]:
### read in processed leiden adata
filenames = get_filepaths_with_glob(input_path, "preRA_cluster_harmonize_*.h5ad")  
filenames[:5]

['../../05-clustering/scripts/output/preRA_cluster_harmonize_CD4_MAIT_2024-05-25.h5ad',
 '../../05-clustering/scripts/output/preRA_cluster_harmonize_ISGpos_naive_CD8_T_cell_2024-05-26.h5ad',
 '../../05-clustering/scripts/output/preRA_cluster_harmonize_Adaptive_NK_cell_2024-05-25.h5ad',
 '../../05-clustering/scripts/output/preRA_cluster_harmonize_Early_memory_B_cell_2024-05-26.h5ad',
 '../../05-clustering/scripts/output/preRA_cluster_harmonize_CD56bright_NK_cell_2024-05-25.h5ad']

In [27]:
### extract cell types
# Apply the function to each filename in the list using list comprehension
cell_types = [extract_substring(path) for path in filenames]
cell_types[:5]

['CD4_MAIT',
 'ISGpos_naive_CD8_T_cell',
 'Adaptive_NK_cell',
 'Early_memory_B_cell',
 'CD56bright_NK_cell']

In [28]:
file_dict = dict(zip(cell_types, filenames))
list(file_dict.items())[:10]

[('CD4_MAIT',
  '../../05-clustering/scripts/output/preRA_cluster_harmonize_CD4_MAIT_2024-05-25.h5ad'),
 ('ISGpos_naive_CD8_T_cell',
  '../../05-clustering/scripts/output/preRA_cluster_harmonize_ISGpos_naive_CD8_T_cell_2024-05-26.h5ad'),
 ('Adaptive_NK_cell',
  '../../05-clustering/scripts/output/preRA_cluster_harmonize_Adaptive_NK_cell_2024-05-25.h5ad'),
 ('Early_memory_B_cell',
  '../../05-clustering/scripts/output/preRA_cluster_harmonize_Early_memory_B_cell_2024-05-26.h5ad'),
 ('CD56bright_NK_cell',
  '../../05-clustering/scripts/output/preRA_cluster_harmonize_CD56bright_NK_cell_2024-05-25.h5ad'),
 ('Intermediate_monocyte',
  '../../05-clustering/scripts/output/preRA_cluster_harmonize_Intermediate_monocyte_2024-05-26.h5ad'),
 ('Core_naive_CD8_T_cell',
  '../../05-clustering/scripts/output/preRA_cluster_harmonize_Core_naive_CD8_T_cell_2024-05-26.h5ad'),
 ('Transitional_B_cell',
  '../../05-clustering/scripts/output/preRA_cluster_harmonize_Transitional_B_cell_2024-05-26.h5ad'),
 ('pDC',
  '../../05-clustering/scripts/output/preRA_cluster_harmonize_pDC_2024-05-26.h5ad'),
 ('KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell',
  '../../05-clustering/scripts/output/preRA_cluster_harmonize_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-05-26.h5ad')]

In [86]:
#### read in doublet csv
doublet_df = pd.read_csv("../data/consensus_doublet_removal_sheet_06_12_24.csv")
### select only cell type and doublet leiden
doublet_df = doublet_df[["AIFI_L3", "leiden (doublet clusters to be removed)"]]
# reformat cell types
doublet_df['AIFI_L3'] = [format_cell_type(cell_type) for cell_type in doublet_df['AIFI_L3']]
doublet_df

                           AIFI_L3 leiden (doublet clusters to be removed)
0                             ASDC                                 2,11,16
1          Activated_memory_B_cell                                    2,12
2                 Adaptive_NK_cell                              9,18,22,24
3                     BaEoMaP_cell                                       7
4             C1Qpos_CD16_monocyte                    16,17,18,19,21,24,25
..                             ...                                     ...
66        SOX4pos_naive_CD8_T_cell                                   10,21
67             Transitional_B_cell                                14,15,18
68  Type_2_polarized_memory_B_cell                                11,18,20
69                            cDC1                           5,18,19,20,23
70                             pDC                 10,11,12,14,16,17,19,20

[71 rows x 2 columns]

In [87]:
doublet_df['AIFI_L3']

0                               ASDC
1            Activated_memory_B_cell
2                   Adaptive_NK_cell
3                       BaEoMaP_cell
4               C1Qpos_CD16_monocyte
                   ...
66          SOX4pos_naive_CD8_T_cell
67               Transitional_B_cell
68    Type_2_polarized_memory_B_cell
69                              cDC1
70                               pDC
Name: AIFI_L3, Length: 71, dtype: object

## Store doublet clusters

In [88]:
# Convert the DataFrame to a dictionary
doublet_cluster_dict = {}

for index, row in doublet_df.iterrows():
    key = row['AIFI_L3']
    # Check if the value is not NaN or None
    if pd.notna(row['leiden (doublet clusters to be removed)']):
        values = row['leiden (doublet clusters to be removed)'].split(',')
    else:
        values = []
    doublet_cluster_dict[key] = values

#print(doublet_cluster_dict)

In [89]:
doublet_cluster_dict

{'ASDC': ['2', '11', '16'],
 'Activated_memory_B_cell': ['2', '12'],
 'Adaptive_NK_cell': ['9', '18', '22', '24'],
 'BaEoMaP_cell': ['7'],
 'C1Qpos_CD16_monocyte': ['16', '17', '18', '19', '21', '24', '25'],
 'CD14pos_cDC2': ['4', '16', '18', '19', '21', '22'],
 'CD27pos_effector_B_cell': ['15', ' 20', '19', '22'],
 'CD27neg_effector_B_cell': ['13', '18', '21'],
 'CD4_MAIT': ['14'],
 'CD56bright_NK_cell': ['10', '21', '22', '19'],
 'CD8_MAIT': ['14', '15', '18', '19', '22', '23'],
 'CD8aa': ['18'],
 'CD95_memory_B_cell': ['7', '8', '16'],
 'CLP_cell': ['11'],
 'CM_CD4_T_cell': [],
 'CM_CD8_T_cell': ['18', '19'],
 'CMP_cell': ['15', '16', '20', '21'],
 'Core_CD14_monocyte': ['16', '17', '22', '24', '28'],
 'Core_CD16_monocyte': ['13', '16', '18', '20', '21'],
 'Core_memory_B_cell': ['14', '16', '18', '19', '20'],
 'Core_naive_B_cell': ['8', '11', '13', '18', '19', '20'],
 'Core_naive_CD4_T_cell': ['15', '17', '19', '20', ' 21'],
 'Core_naive_CD8_T_cell': ['13'],
 'DN_T_cell': ['22', '23', '24'],
 'Early_memory_B_cell': ['9', '17', '19', '21'],
 'Erythrocyte': ['2',
  '3',
  '6',
  '7',
  '9',
  '12',
  '13',
  '15',
  '16',
  '17',
  '18',
  '19'],
 'GZMBpos_Vd2_gdT': ['18', '21'],
 'GZMBneg_CD27pos_EM_CD4_T_cell': ['21'],
 'GZMBneg_CD27neg_EM_CD4_T_cell': ['3', '13', '14', '20', '21', '23', '24'],
 'GZMKpos_CD27pos_EM_CD8_T_cell': ['18', '23', '24', '26'],
 'GZMKpos_CD56dim_NK_cell': ['14', '20', '18', '17'],
 'GZMKpos_Vd2_gdT': ['21', '23'],
 'GZMKpos_memory_CD4_Treg': ['15'],
 'GZMKneg_CD27pos_EM_CD8_T_cell': ['18', '20', '15'],
 'GZMKneg_CD56dim_NK_cell': ['13', '15', '16', '17', '18', '12', '19'],
 'HLAnegDRhi_cDC2': ['8', '19', '21', '25', '26', '27'],
 'IL1Bpos_CD14_monocyte': ['0', '4', '7', '12', '17', '19', '20'],
 'ILC': ['12', '15', '16'],
 'ISGpos_CD14_monocyte': ['5', '18', '25', '28', '22', '29'],
 'ISGpos_CD16_monocyte': ['2', '9', '12', '16', '19', '22', '23'],
 'ISGpos_CD56dim_NK_cell': ['6', '11', '17', '18', '19', '20', '21', '23'],
 'ISGpos_MAIT': ['9', '21'],
 'ISGpos_cDC2': ['2', '14', '16'],
 'ISGpos_memory_CD4_T_cell': ['20', '21'],
 'ISGpos_memory_CD8_T_cell': ['17'],
 'ISGpos_naive_B_cell': ['18', '19'],
 'ISGpos_naive_CD4_T_cell': ['17'],
 'ISGpos_naive_CD8_T_cell': ['15'],
 'Intermediate_monocyte': ['5', '12', '15', '20', '21', '22'],
 'KLRB1pos_memory_CD4_Treg': ['17', '21'],
 'KLRB1pos_memory_CD8_Treg': ['10', '17'],
 'KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell': ['26', '28', '29'],
 'KLRF1pos_effector_Vd1_gdT': ['17', '20', '21', '23', '24'],
 'KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell': ['17', '25', '30'],
 'KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell': ['19', '23'],
 'KLRF1neg_effector_Vd1_gdT': ['0', '6', '18', '19', '20'],
 'Memory_CD4_Treg': ['20', '22', '23'],
 'Memory_CD8_Treg': ['13'],
 'Naive_CD4_Treg': ['17', '19'],
 'Naive_Vd1_gdT': ['19'],
 'Plasma_cell': ['9', '14', '21'],
 'Platelet': ['5', '9', '12', '14', '15', '16', '17', '19', '20', '22'],
 'Proliferating_NK_cell': ['12', '14', '17', '18', '19'],
 'Proliferating_T_cell': ['12', '24', '25'],
 'SOX4pos_Vd1_gdT': ['18'],
 'SOX4pos_naive_CD4_T_cell': ['14', '19', '20', '22'],
 'SOX4pos_naive_CD8_T_cell': ['10', '21'],
 'Transitional_B_cell': ['14', '15', '18'],
 'Type_2_polarized_memory_B_cell': ['11', '18', '20'],
 'cDC1': ['5', '18', '19', '20', '23'],
 'pDC': ['10', '11', '12', '14', '16', '17', '19', '20']}

## Store Relabel Cell Type Clusters

Store list of leiden clusters to relabel to L3 cell types

In [162]:
relabel_df = pd.read_csv("../data/relabel_deepclean_sheet_06_11_24.csv")
relabel_df = relabel_df[['AIFI_L3', 'relabel_name','clusters']]
# reformat cell types
relabel_df['AIFI_L3'] = [format_cell_type(cell_type) for cell_type in relabel_df['AIFI_L3']]
# filter by cell types that need to be relabeled and clusters only
relabel_df = relabel_df.dropna(thresh= 2)
relabel_df

,AIFI_L3,relabel_name,clusters
0,ASDC,ASDC_uk1_B,"0,1,7"
1,Activated_memory_B_cell,Activated memory B cell_uk1,1
2,Adaptive_NK_cell,Adaptive NK cell_uk1_T,"7,11,20,21"
14,CM_CD4_T_cell,"CM CD4 T cell_uk1_CD8,CM CD4 T cell_uk2","12,17"
24,Early_memory_B_cell,Early memory B cell_uk1,"12,13"
27,GZMBneg_CD27pos_EM_CD4_T_cell,GZMB- CD27+ EM CD4 T cell_uk1_CD8,15
28,GZMBneg_CD27neg_EM_CD4_T_cell,GZMB- CD27- EM CD4 T cell_uk1_CD8,6
29,GZMKpos_CD27pos_EM_CD8_T_cell,GZMK+ CD27+ EM CD8 T cell_uk1_gdt,"10,15,17"
37,ILC,ILC_uk1,2
43,ISGpos_memory_CD4_T_cell,ISG+ memory CD4 T cell_uk1_CD8,15
51,KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell,"[KLRF1+_GZMB+_CD27-_EM_CD8_uk1],[KLRF1+_GZMB+_...","[30],[23],[1,4,15,16]"
53,KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell,KLRF1-_GZMB+_CD27-_EM_CD8_uk1,20
54,KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell,KLRF1-_GZMB+_CD27-_mem_CD4_uk1,"5,6"
63,Proliferating_T_cell,Prolif_T_uk1,16
68,Type_2_polarized_memory_B_cell,T2MBC_uk1,19

In [98]:
### remove cell types with more than one names to be relabeled
multiple_relabel_cond = relabel_df['AIFI_L3'].str.contains('|'.join(['CM_CD4_T_cell', 'KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell']))
relabel_df_single = relabel_df[~multiple_relabel_cond]
relabel_df_multi = relabel_df[multiple_relabel_cond]

In [99]:
relabel_df_single

,AIFI_L3,relabel_name,clusters
0,ASDC,ASDC_uk1_B,"0,1,7"
1,Activated_memory_B_cell,Activated memory B cell_uk1,1
2,Adaptive_NK_cell,Adaptive NK cell_uk1_T,"7,11,20,21"
24,Early_memory_B_cell,Early memory B cell_uk1,"12,13"
27,GZMBneg_CD27pos_EM_CD4_T_cell,GZMB- CD27+ EM CD4 T cell_uk1_CD8,15
28,GZMBneg_CD27neg_EM_CD4_T_cell,GZMB- CD27- EM CD4 T cell_uk1_CD8,6
29,GZMKpos_CD27pos_EM_CD8_T_cell,GZMK+ CD27+ EM CD8 T cell_uk1_gdt,"10,15,17"
37,ILC,ILC_uk1,2
43,ISGpos_memory_CD4_T_cell,ISG+ memory CD4 T cell_uk1_CD8,15
53,KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell,KLRF1-_GZMB+_CD27-_EM_CD8_uk1,20
54,KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell,KLRF1-_GZMB+_CD27-_mem_CD4_uk1,"5,6"
63,Proliferating_T_cell,Prolif_T_uk1,16
68,Type_2_polarized_memory_B_cell,T2MBC_uk1,19

In [100]:
relabel_df_multi

,AIFI_L3,relabel_name,clusters
14,CM_CD4_T_cell,"CM CD4 T cell_uk1_CD8,CM CD4 T cell_uk2","12,17"
51,KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell,"[KLRF1+_GZMB+_CD27-_EM_CD8_uk1],[KLRF1+_GZMB+_...","[30],[23],[1,4,15,16]"

In [83]:
# Create the dictionary
relabel_cluster_dict = {}

for index, row in relabel_df_single.iterrows():
    key = row['AIFI_L3']
    # parse clusters that have multiple relabel name within same cell types
    cl = row['clusters'].split(',')
    parsed_cl =  [cluster.strip('[]').split(',') for cluster in cl]
    value = (row['relabel_name'].split(','), cl)
    relabel_cluster_dict[key] = value

In [84]:
print(relabel_cluster_dict)

{'ASDC': (['ASDC_uk1_B'], ['0', '1', '7']), 'Activated_memory_B_cell': (['Activated memory B cell_uk1'], ['1']), 'Adaptive_NK_cell': (['Adaptive NK cell_uk1_T'], ['7', '11', '20', '21']), 'Early_memory_B_cell': (['Early memory B cell_uk1'], ['12', '13']), 'GZMBneg_CD27pos_EM_CD4_T_cell': (['GZMB- CD27+ EM CD4 T cell_uk1_CD8'], ['15']), 'GZMBneg_CD27neg_EM_CD4_T_cell': (['GZMB- CD27- EM CD4 T cell_uk1_CD8'], ['6']), 'GZMKpos_CD27pos_EM_CD8_T_cell': (['GZMK+ CD27+ EM CD8 T cell_uk1_gdt'], ['10', '15', '17']), 'ILC': (['ILC_uk1'], ['2']), 'ISGpos_memory_CD4_T_cell': (['ISG+ memory CD4 T cell_uk1_CD8'], ['15']), 'KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell': (['KLRF1-_GZMB+_CD27-_EM_CD8_uk1'], ['20']), 'KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell': (['KLRF1-_GZMB+_CD27-_mem_CD4_uk1'], ['5', '6']), 'Proliferating_T_cell': (['Prolif_T_uk1'], ['16']), 'Type_2_polarized_memory_B_cell': (['T2MBC_uk1'], ['19'])}

In [150]:
### manually add cell types with multiple renaming labels to dictionary
multi_relabel_dict = {
    'KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell': (
        ['KLRF1+_GZMB+_CD27-_EM_CD8_uk1', 'KLRF1+_GZMB+_CD27-_EM_CD8_uk2', 'KLRF1+GZMB+_CD27-_EM_CD8_uk3'],
        [['30'], ['23'], ['1','4','15','16']]),
    'CM_CD4_T_cell': (
        ['CM CD4 T cell_uk1_CD8', 'CM CD4 T cell_uk2'], 
        [['12'],['17']])}
multi_relabel_dict

{'KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell': (['KLRF1+_GZMB+_CD27-_EM_CD8_uk1',
   'KLRF1+_GZMB+_CD27-_EM_CD8_uk2',
   'KLRF1+GZMB+_CD27-_EM_CD8_uk3'],
  [['30'], ['23'], ['1', '4', '15', '16']]),
 'CM_CD4_T_cell': (['CM CD4 T cell_uk1_CD8', 'CM CD4 T cell_uk2'],
  [['12'], ['17']])}

## Process Each Cell Types

In [122]:
### create unit test: cell type with no renaming, cell type with 1 rename and cell type with multiple rename
#subfile_dict = dict((k, file_dict[k]) for k in ('CD4_MAIT', 'ASDC', 'CM_CD4_T_cell'))
subfile_dict = dict((k, file_dict[k]) for k in ('CD4_MAIT', 'ASDC', 'CM_CD4_T_cell'))

subfile_dict

{'CD4_MAIT': '../../05-clustering/scripts/output/preRA_cluster_harmonize_CD4_MAIT_2024-05-25.h5ad',
 'ASDC': '../../05-clustering/scripts/output/preRA_cluster_harmonize_ASDC_2024-05-25.h5ad',
 'CM_CD4_T_cell': '../../05-clustering/scripts/output/preRA_cluster_harmonize_CM_CD4_T_cell_2024-05-26.h5ad'}

In [163]:
out_files = []
out_files

[]

In [164]:
for label, file in file_dict.items():
    print("Key:", label)
    print("Value:", file)

    adata = sc.read_h5ad(file)
    print(adata)

    # subset doublet dictionary by current cell types
    doublet_clust = doublet_cluster_dict[label]
    print('Doublet clusters: ' + str(doublet_clust))

    #### label doublets on metadata
    #### create new column in metadata that labels doublets based on target leiden from manual analysis 
    if len(doublet_clust) == 0:
        print("The list is empty")
        adata.obs['doublets_manual'] = 'no'
    else:
        adata.obs['doublets_manual'] = ['yes' if leiden in doublet_clust else 'no' for leiden in adata.obs['leiden_harmony_2']]
    ## check
    print(pd.crosstab(adata.obs['doublets_manual'], adata.obs['leiden_harmony_2']))


    #### label renamed cell types
    # if current cell type needs to be relabeled and the current cell type does not have multiple relabel names    
    if label in relabel_df_single['AIFI_L3'].values and label not in relabel_df_multi['AIFI_L3'].values:
        relabel_clust = relabel_cluster_dict[label]

        print('Clusters to relabel: '+ str(relabel_clust))
        to_rename = relabel_clust[0][0]
        rename_cl = relabel_clust[1]
        # modify metadata
        adata.obs['AIFI_L3_new'] = [
            to_rename if leiden in rename_cl else adata.obs['AIFI_L3'][idx] 
            for idx, leiden in enumerate(adata.obs['leiden_harmony_2'])
        ]
        # check
        print(pd.crosstab(adata.obs['AIFI_L3_new'], adata.obs['leiden_harmony_2']))
    
    # if curr cell type contains multiple cell types to relabel
    if label in relabel_df_multi['AIFI_L3'].values:
        relabel_clust = multi_relabel_dict[label]
    
        print('Clusters to relabel: '+ str(relabel_clust))
    
        # Create a dictionary from the relabel_clust for easier lookup
        rename_dict = {}
        for cell_type, clusters in zip(relabel_clust[0], relabel_clust[1]):
            for cluster in clusters:
                rename_dict[cluster] = cell_type
    
        # Apply the renaming logic
        adata.obs['AIFI_L3_new'] = [
            rename_dict.get(leiden, adata.obs['AIFI_L3'][idx]) 
            for idx, leiden in enumerate(adata.obs['leiden_harmony_2'])
        ]
        print(pd.crosstab(adata.obs['AIFI_L3_new'], adata.obs['leiden_harmony_2']))

    # if curr cell type does not need to be relabeled, create new column, inherit old L3 annotations
    if label not in  relabel_df_single['AIFI_L3'].values and label not in relabel_df_multi['AIFI_L3'].values:
        adata.obs['AIFI_L3_new'] = adata.obs['AIFI_L3']

    ### export doublet metadata, do not append to out-files for certpro
    meta = adata.obs[['barcodes','batch_id', 'cell_name', 'sample.sampleKitGuid','subject.subjectGuid','AIFI_L3_new','leiden_harmony_2','doublets_manual']]
    meta.head()
    ### export
    meta.to_csv('../data/preRA_doublet_meta_{c}_{d}.csv'.format(
        c = label,
        d = date.today()
    ))

    # subset anndata by singlets only
    adata_subset = adata[adata.obs['doublets_manual'] == 'no']

    print("subsetted cells to: " + str(adata.shape))

    # export deep cleaned anndata
    print('Saving processed data')
    out_file = 'output/preRA_deepcleaned_{c}_{d}.h5ad'.format(
        c = label,
        d = date.today()
    )
    adata_subset.write_h5ad(out_file)

    # append to outfile list
    out_files.append(out_file)

Key: CD4_MAIT
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_CD4_MAIT_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 4270 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['14']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no                445  436  410  348  299  296  232  206  202  190  177  163
yes                 0    0    0    0    0    0    0    0    0    0    0    0

leiden_harmony_2   12   13   14   15   16   17  18
doublets_manual
no                160  143    0  130  114  101  81
yes                 0    0  137    0    0    0   0
subsetted cells to: (4270, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_naive_CD8_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_ISGpos_naive_CD8_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 2299 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['15']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9   10  11  \
doublets_manual
no                241  182  174  171  164  162  158  149  139  129  110  99
yes                 0    0    0    0    0    0    0    0    0    0    0   0

leiden_harmony_2  12  13  14  15  16  17
doublets_manual
no                98  84  83   0  59  22
yes                0   0   0  75   0   0
subsetted cells to: (2299, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Adaptive_NK_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Adaptive_NK_cell_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 73124 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['9', '18', '22', '24']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                5749  5548  4875  4254  4240  4187  3998  3826  3744     0
yes                  0     0     0     0     0     0     0     0     0  3665

leiden_harmony_2  ...    17    18    19    20    21   22   23   24   25   26
doublets_manual   ...
no                ...  1891     0  1090  1078  1061    0  820    0  493  303
yes               ...     0  1578     0     0     0  896    0  561    0    0

[2 rows x 27 columns]
Clusters to relabel: (['Adaptive NK cell_uk1_T'], ['7', '11', '20', '21'])
leiden_harmony_2           0     1     2     3     4     5     6     7     8  \
AIFI_L3_new
Adaptive NK cell        5749  5548  4875  4254  4240  4187  3998     0  3744
Adaptive NK cell_uk1_T     0     0     0     0     0     0     0  3826     0

leiden_harmony_2           9  ...    17    18    19    20    21   22   23  \
AIFI_L3_new                   ...
Adaptive NK cell        3665  ...  1891  1578  1090     0     0  896  820
Adaptive NK cell_uk1_T     0  ...     0     0     0  1078  1061    0    0

leiden_harmony_2         24   25   26
AIFI_L3_new
Adaptive NK cell        561  493  303
Adaptive NK cell_uk1_T    0    0    0

[2 rows x 27 columns]
subsetted cells to: (73124, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Early_memory_B_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Early_memory_B_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 5693 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['9', '17', '19', '21']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9  ...   12  \
doublets_manual                                                     ...
no                519  509  474  407  378  376  341  306  281    0  ...  227
yes                 0    0    0    0    0    0    0    0    0  267  ...    0

leiden_harmony_2   13   14   15   16   17   18  19  20  21
doublets_manual
no                193  192  169  139    0  116   0  61   0
yes                 0    0    0    0  116    0  78   0  54

[2 rows x 22 columns]
Clusters to relabel: (['Early memory B cell_uk1'], ['12', '13'])
leiden_harmony_2           0    1    2    3    4    5    6    7    8    9  \
AIFI_L3_new
Early memory B cell      519  509  474  407  378  376  341  306  281  267
Early memory B cell_uk1    0    0    0    0    0    0    0    0    0    0

leiden_harmony_2         ...   12   13   14   15   16   17   18  19  20  21
AIFI_L3_new              ...
Early memory B cell      ...    0    0  192  169  139  116  116  78  61  54
Early memory B cell_uk1  ...  227  193    0    0    0    0    0   0   0   0

[2 rows x 22 columns]
subsetted cells to: (5693, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD56bright_NK_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_CD56bright_NK_cell_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 40284 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['10', '21', '22', '19']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                3533  3517  3174  2998  2765  2750  2504  2485  2299  2213
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...   15   16   17   18   19   20   21   22  23  24
doublets_manual   ...
no                ...  854  672  565  541    0  443    0    0  76  25
yes               ...    0    0    0    0  526    0  407  230   0   0

[2 rows x 25 columns]
subsetted cells to: (40284, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Intermediate_monocyte
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Intermediate_monocyte_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 49124 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['5', '12', '15', '20', '21', '22']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                3654  3501  3428  3393  3230     0  2656  2640  2614  2487
yes                  0     0     0     0     0  2756     0     0     0     0

leiden_harmony_2  ...    13    14    15    16    17    18   19   20   21   22
doublets_manual   ...
no                ...  2069  2027     0  1499  1335  1263  756    0    0    0
yes               ...     0     0  1833     0     0     0    0  743  408  107

[2 rows x 23 columns]
subsetted cells to: (49124, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Core_naive_CD8_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Core_naive_CD8_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 326580 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['13']
leiden_harmony_2      0      1      2      3      4      5      6      7  \
doublets_manual
no                39302  36300  32388  30299  25822  25406  24206  23849
yes                   0      0      0      0      0      0      0      0

leiden_harmony_2      8      9  ...     11    12    13    14  15  16  17  18  \
doublets_manual                 ...
no                23352  22531  ...  12041  9524     0  2091  49  28   9   4
yes                   0      0  ...      0     0  2656     0   0   0   0   0

leiden_harmony_2  19  20
doublets_manual
no                 2   2
yes                0   0

[2 rows x 21 columns]
subsetted cells to: (326580, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Transitional_B_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Transitional_B_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 47103 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['14', '15', '18']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                5077  4533  4229  4042  3883  3445  3383  3251  2600  2443
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...    11    12    13   14   15   16   17   18  19  20
doublets_manual   ...
no                ...  2104  1328  1053    0    0  672  654    0  80   6
yes               ...     0     0     0  983  970    0    0  131   0   0

[2 rows x 21 columns]
subsetted cells to: (47103, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: pDC
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_pDC_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 26277 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['10', '11', '12', '14', '16', '17', '19', '20']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                2597  2415  2385  2357  2292  2039  1763  1701  1493  1215
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...    11   12   13   14   15   16   17   18  19  20
doublets_manual   ...
no                ...     0    0  912    0  462    0    0  133   0   0
yes               ...  1040  931    0  666    0  333  321    0  77  66

[2 rows x 21 columns]
subsetted cells to: (26277, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 110784 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['26', '28', '29']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                8674  6680  6667  6051  5921  5481  5180  5114  5108  5052
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...    23    24    25    26   27   28   29   30   31   32
doublets_manual   ...
no                ...  1768  1498  1250     0  829    0    0  685  558  552
yes               ...     0     0     0  1209    0  725  692    0    0    0

[2 rows x 33 columns]
Clusters to relabel: (['KLRF1+_GZMB+_CD27-_EM_CD8_uk1', 'KLRF1+_GZMB+_CD27-_EM_CD8_uk2', 'KLRF1+GZMB+_CD27-_EM_CD8_uk3'], [['30'], ['23'], ['1', '4', '15', '16']])
leiden_harmony_2                     0     1     2     3     4     5     6  \
AIFI_L3_new
KLRF1+ GZMB+ CD27- EM CD8 T cell  8674     0  6667  6051     0  5481  5180
KLRF1+GZMB+_CD27-_EM_CD8_uk3         0  6680     0     0  5921     0     0
KLRF1+_GZMB+_CD27-_EM_CD8_uk1        0     0     0     0     0     0     0
KLRF1+_GZMB+_CD27-_EM_CD8_uk2        0     0     0     0     0     0     0

leiden_harmony_2                     7     8     9  ...    23    24    25  \
AIFI_L3_new                                         ...
KLRF1+ GZMB+ CD27- EM CD8 T cell  5114  5108  5052  ...     0  1498  1250
KLRF1+GZMB+_CD27-_EM_CD8_uk3         0     0     0  ...     0     0     0
KLRF1+_GZMB+_CD27-_EM_CD8_uk1        0     0     0  ...     0     0     0
KLRF1+_GZMB+_CD27-_EM_CD8_uk2        0     0     0  ...  1768     0     0

leiden_harmony_2                    26   27   28   29   30   31   32
AIFI_L3_new
KLRF1+ GZMB+ CD27- EM CD8 T cell  1209  829  725  692    0  558  552
KLRF1+GZMB+_CD27-_EM_CD8_uk3         0    0    0    0    0    0    0
KLRF1+_GZMB+_CD27-_EM_CD8_uk1        0    0    0    0  685    0    0
KLRF1+_GZMB+_CD27-_EM_CD8_uk2        0    0    0    0    0    0    0

[4 rows x 33 columns]
subsetted cells to: (110784, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CM_CD4_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_CM_CD4_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 830036 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: []
The list is empty
leiden_harmony_2      0      1      2      3      4      5      6      7  \
doublets_manual
no                75198  73173  61144  58355  55414  53910  52898  50125

leiden_harmony_2      8      9  ...     11     12     13     14     15    16  \
doublets_manual                 ...
no                50049  47643  ...  41671  41645  41036  35332  29269  7624

leiden_harmony_2    17    18    19  20
doublets_manual
no                7623  4577  1232   9

[1 rows x 21 columns]
Clusters to relabel: (['CM CD4 T cell_uk1_CD8', 'CM CD4 T cell_uk2'], [['12'], ['17']])
leiden_harmony_2           0      1      2      3      4      5      6      7  \
AIFI_L3_new
CM CD4 T cell          75198  73173  61144  58355  55414  53910  52898  50125
CM CD4 T cell_uk1_CD8      0      0      0      0      0      0      0      0
CM CD4 T cell_uk2          0      0      0      0      0      0      0      0

leiden_harmony_2           8      9  ...     11     12     13     14     15  \
AIFI_L3_new                          ...
CM CD4 T cell          50049  47643  ...  41671      0  41036  35332  29269
CM CD4 T cell_uk1_CD8      0      0  ...      0  41645      0      0      0
CM CD4 T cell_uk2          0      0  ...      0      0      0      0      0

leiden_harmony_2         16    17    18    19  20
AIFI_L3_new
CM CD4 T cell          7624     0  4577  1232   9
CM CD4 T cell_uk1_CD8     0     0     0     0   0
CM CD4 T cell_uk2         0  7623     0     0   0

[3 rows x 21 columns]
subsetted cells to: (830036, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Core_naive_B_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Core_naive_B_cell_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 391130 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['8', '11', '13', '18', '19', '20']
leiden_harmony_2      0      1      2      3      4      5      6      7  \
doublets_manual
no                42334  42029  34695  33944  33662  29442  28560  28529
yes                   0      0      0      0      0      0      0      0

leiden_harmony_2      8      9  ...    18    19    20    21   22  23  24  25  \
doublets_manual                 ...
no                    0  18051  ...     0     0     0  1181  126  79   5   3
yes               21058      0  ...  3427  1666  1212     0    0   0   0   0

leiden_harmony_2  26  27
doublets_manual
no                 3   3
yes                0   0

[2 rows x 28 columns]
subsetted cells to: (391130, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Memory_CD8_Treg
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Memory_CD8_Treg_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 1607 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['13']
leiden_harmony_2    0    1    2    3    4    5   6   7   8   9  10  11  12  \
doublets_manual
no                147  138  134  134  131  113  98  98  91  81  80  72  71
yes                 0    0    0    0    0    0   0   0   0   0   0   0   0

leiden_harmony_2  13  14  15  16
doublets_manual
no                 0  60  57  39
yes               63   0   0   0
subsetted cells to: (1607, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD8aa
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_CD8aa_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 5258 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['18']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9  ...   11  \
doublets_manual                                                     ...
no                450  438  409  359  347  346  299  295  293  280  ...  233
yes                 0    0    0    0    0    0    0    0    0    0  ...    0

leiden_harmony_2   12   13   14   15   16   17  18  19  20
doublets_manual
no                209  207  188  187  160  122   0  65  64
yes                 0    0    0    0    0    0  72   0   0

[2 rows x 21 columns]
subsetted cells to: (5258, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_MAIT
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_ISGpos_MAIT_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 1612 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['9', '21']
leiden_harmony_2    0    1    2    3    4   5   6   7   8   9  ...  12  13  \
doublets_manual                                                ...
no                214  144  131  123  112  98  84  72  71   0  ...  51  47
yes                 0    0    0    0    0   0   0   0   0  69  ...   0   0

leiden_harmony_2  14  15  16  17  18  19  20  21
doublets_manual
no                47  46  43  36  35  29  18   0
yes                0   0   0   0   0   0   0  18

[2 rows x 22 columns]
subsetted cells to: (1612, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ILC
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_ILC_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 2945 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['12', '15', '16']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no                299  245  238  232  225  200  179  169  156  155  145  142
yes                 0    0    0    0    0    0    0    0    0    0    0    0

leiden_harmony_2   12   13   14  15  16  17
doublets_manual
no                  0  133  119   0   0  37
yes               140    0    0  70  61   0
Clusters to relabel: (['ILC_uk1'], ['2'])
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9   10   11  \
AIFI_L3_new
ILC               299  245    0  232  225  200  179  169  156  155  145  142
ILC_uk1             0    0  238    0    0    0    0    0    0    0    0    0

leiden_harmony_2   12   13   14  15  16  17
AIFI_L3_new
ILC               140  133  119  70  61  37
ILC_uk1             0    0    0   0   0   0
subsetted cells to: (2945, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD27neg_effector_B_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_CD27neg_effector_B_cell_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 24356 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['13', '18', '21']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                2399  1871  1748  1739  1674  1628  1568  1500  1392  1352
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...   13   14   15   16   17   18   19   20  21  22
doublets_manual   ...
no                ...    0  769  744  673  512    0  323  261   0  53
yes               ...  830    0    0    0    0  376    0    0  80   0

[2 rows x 23 columns]
subsetted cells to: (24356, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: cDC1
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_cDC1_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 3816 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['5', '18', '19', '20', '23']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9  ...   14  \
doublets_manual                                                     ...
no                352  246  242  234  227    0  219  214  211  190  ...  151
yes                 0    0    0    0    0  221    0    0    0    0  ...    0

leiden_harmony_2   15   16  17  18  19  20  21  22  23
doublets_manual
no                131  113  89   0   0   0  43  26   0
yes                 0    0   0  80  76  51   0   0  16

[2 rows x 24 columns]
subsetted cells to: (3816, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD27pos_effector_B_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_CD27pos_effector_B_cell_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 22959 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['15', ' 20', '19', '22']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                1944  1597  1570  1514  1505  1476  1342  1237  1158  1092
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...   14   15   16   17   18   19   20   21   22   23
doublets_manual   ...
no                ...  729    0  638  607  591    0  358  330    0  224
yes               ...    0  661    0    0    0  454    0    0  254    0

[2 rows x 24 columns]
subsetted cells to: (22959, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMKpos_CD27pos_EM_CD8_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_GZMKpos_CD27pos_EM_CD8_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 297188 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['18', '23', '24', '26']
leiden_harmony_2      0      1      2      3      4      5      6      7  \
doublets_manual
no                24647  22160  20121  20121  18902  18250  17771  16198
yes                   0      0      0      0      0      0      0      0

leiden_harmony_2      8      9  ...    17    18    19    20    21    22    23  \
doublets_manual                 ...
no                15461  14594  ...  7514     0  6130  5721  4973  3608     0
yes                   0      0  ...     0  6844     0     0     0     0  2977

leiden_harmony_2    24    25   26
doublets_manual
no                   0  2194    0
yes               2658     0  429

[2 rows x 27 columns]
Clusters to relabel: (['GZMK+ CD27+ EM CD8 T cell_uk1_gdt'], ['10', '15', '17'])
leiden_harmony_2                       0      1      2      3      4      5  \
AIFI_L3_new
GZMK+ CD27+ EM CD8 T cell          24647  22160  20121  20121  18902  18250
GZMK+ CD27+ EM CD8 T cell_uk1_gdt      0      0      0      0      0      0

leiden_harmony_2                       6      7      8      9  ...    17  \
AIFI_L3_new                                                    ...
GZMK+ CD27+ EM CD8 T cell          17771  16198  15461  14594  ...     0
GZMK+ CD27+ EM CD8 T cell_uk1_gdt      0      0      0      0  ...  7514

leiden_harmony_2                     18    19    20    21    22    23    24  \
AIFI_L3_new
GZMK+ CD27+ EM CD8 T cell          6844  6130  5721  4973  3608  2977  2658
GZMK+ CD27+ EM CD8 T cell_uk1_gdt     0     0     0     0     0     0     0

leiden_harmony_2                     25   26
AIFI_L3_new
GZMK+ CD27+ EM CD8 T cell          2194  429
GZMK+ CD27+ EM CD8 T cell_uk1_gdt     0    0

[2 rows x 27 columns]
subsetted cells to: (297188, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Platelet
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Platelet_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 29861 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['5', '9', '12', '14', '15', '16', '17', '19', '20', '22']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                2521  2415  2207  2034  1970     0  1812  1713  1680     0
yes                  0     0     0     0     0  1902     0     0     0  1614

leiden_harmony_2  ...    13    14   15   16   17   18   19   20  21  22
doublets_manual   ...
no                ...  1288     0    0    0    0  373    0    0  55   0
yes               ...     0  1161  825  823  694    0  292  236   0  21

[2 rows x 23 columns]
subsetted cells to: (29861, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Naive_CD4_Treg
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Naive_CD4_Treg_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 87974 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17', '19']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                8862  8110  7704  6462  6411  6364  5310  4697  4637  4220
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2    10    11    12    13    14    15    16    17    18   19
doublets_manual
no                3914  3283  3248  2918  2842  2620  2351     0  1240    0
yes                  0     0     0     0     0     0     0  2091     0  690
subsetted cells to: (87974, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: IL1Bpos_CD14_monocyte
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_IL1Bpos_CD14_monocyte_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 32996 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['0', '4', '7', '12', '17', '19', '20']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                   0  3103  2730  2505     0  1993  1953     0  1735  1668
yes               3709     0     0     0  2043     0     0  1777     0     0

leiden_harmony_2  ...    11    12    13    14   15   16   17   18   19  20
doublets_manual   ...
no                ...  1558     0  1278  1237  869  813    0  298    0   0
yes               ...     0  1360     0     0    0    0  467    0  141  94

[2 rows x 21 columns]
subsetted cells to: (32996, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: KLRF1pos_effector_Vd1_gdT
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_KLRF1pos_effector_Vd1_gdT_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 17915 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17', '20', '21', '23', '24']
leiden_harmony_2     0     1     2     3     4     5    6    7    8    9  ...  \
doublets_manual                                                           ...
no                2055  1639  1473  1252  1157  1140  980  872  843  823  ...
yes                  0     0     0     0     0     0    0    0    0    0  ...

leiden_harmony_2   15   16   17   18   19   20   21   22   23  24
doublets_manual
no                415  407    0  370  302    0    0  132    0   0
yes                 0    0  385    0    0  187  173    0  130  87

[2 rows x 25 columns]
subsetted cells to: (17915, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Core_memory_B_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Core_memory_B_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 148466 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['14', '16', '18', '19', '20']
leiden_harmony_2      0      1      2      3      4      5     6     7     8  \
doublets_manual
no                13713  11195  11182  10653  10481  10300  9568  9311  8934
yes                   0      0      0      0      0      0     0     0     0

leiden_harmony_2     9  ...    14    15    16    17    18   19   20   21   22  \
doublets_manual         ...
no                8925  ...     0  4056     0  1738     0    0    0  428  424
yes                  0  ...  5452     0  2311     0  1215  861  697    0    0

leiden_harmony_2   23
doublets_manual
no                183
yes                 0

[2 rows x 24 columns]
subsetted cells to: (148466, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMKpos_memory_CD4_Treg
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_GZMKpos_memory_CD4_Treg_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 1099 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['15']
leiden_harmony_2    0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  \
doublets_manual
no                100  98  89  83  81  70  69  67  62  56  56  49  48  42  38
yes                 0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

leiden_harmony_2  15  16  17  18
doublets_manual
no                 0  27  26   8
yes               30   0   0   0
subsetted cells to: (1099, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Core_CD14_monocyte
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Core_CD14_monocyte_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 979131 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['16', '17', '22', '24', '28']
leiden_harmony_2      0      1      2      3      4      5      6      7  \
doublets_manual
no                84308  71206  70245  67840  62946  62313  60680  54469
yes                   0      0      0      0      0      0      0      0

leiden_harmony_2      8      9  ...     19    20    21    22    23    24  \
doublets_manual                 ...
no                51240  46693  ...  13404  9490  6495     0  4995     0
yes                   0      0  ...      0     0     0  5258     0  4939

leiden_harmony_2    25    26    27   28
doublets_manual
no                2562  2255  1128    0
yes                  0     0     0  472

[2 rows x 29 columns]
subsetted cells to: (979131, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMBpos_Vd2_gdT
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_GZMBpos_Vd2_gdT_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 29411 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['18', '21']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                2838  2580  2508  2446  2168  2019  1853  1578  1425  1417
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...    12    13   14   15   16   17   18   19   20   21
doublets_manual   ...
no                ...  1084  1077  913  746  492  447    0  348  346    0
yes               ...     0     0    0    0    0    0  386    0    0  154

[2 rows x 22 columns]
subsetted cells to: (29411, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: SOX4pos_naive_CD4_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_SOX4pos_naive_CD4_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 31683 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['14', '19', '20', '22']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                3396  2613  2577  2257  2162  2157  2083  2032  1965  1356
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...   14   15   16   17   18   19   20   21   22  23
doublets_manual   ...
no                ...    0  720  662  567  532    0    0  363    0  47
yes               ...  802    0    0    0    0  503  445    0  236   0

[2 rows x 24 columns]
subsetted cells to: (31683, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: KLRB1pos_memory_CD8_Treg
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_KLRB1pos_memory_CD8_Treg_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 2224 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['10', '17']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no                199  181  177  165  159  153  152  135  129  119    0  108
yes                 0    0    0    0    0    0    0    0    0    0  109    0

leiden_harmony_2  12  13  14  15  16  17  18
doublets_manual
no                98  90  73  71  60   0  20
yes                0   0   0   0   0  26   0
subsetted cells to: (2224, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD8_MAIT
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_CD8_MAIT_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 106766 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['14', '15', '18', '19', '22', '23']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                9556  9084  8889  8856  8413  7208  7132  6524  6027  5550
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...    14    15    16    17    18   19   20   21   22  23
doublets_manual   ...
no                ...     0     0  1773  1536     0    0  407  354    0   0
yes               ...  2857  1795     0     0  1266  803    0    0  141  32

[2 rows x 24 columns]
subsetted cells to: (106766, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: BaEoMaP_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_BaEoMaP_cell_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 258 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['7']
leiden_harmony_2   0   1   2   3   4   5   6   7   8   9  10  11  12
doublets_manual
no                31  31  26  24  23  23  16   0  15  14  14  14  11
yes                0   0   0   0   0   0   0  16   0   0   0   0   0
subsetted cells to: (258, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_naive_B_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_ISGpos_naive_B_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 18140 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['18', '19']
leiden_harmony_2     0     1     2     3     4     5    6    7    8    9  ...  \
doublets_manual                                                           ...
no                1434  1153  1129  1105  1081  1030  979  971  966  966  ...
yes                  0     0     0     0     0     0    0    0    0    0  ...

leiden_harmony_2   12   13   14   15   16   17   18   19   20  21
doublets_manual
no                857  834  755  647  623  564    0    0  210  66
yes                 0    0    0    0    0    0  492  404    0   0

[2 rows x 22 columns]
subsetted cells to: (18140, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: C1Qpos_CD16_monocyte
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_C1Qpos_CD16_monocyte_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 22215 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['16', '17', '18', '19', '21', '24', '25']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                1643  1615  1556  1436  1420  1351  1337  1315  1019  1006
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...   16   17   18   19   20   21   22   23   24  25
doublets_manual   ...
no                ...    0    0    0    0  440    0  288  207    0   0
yes               ...  637  523  456  443    0  393    0    0  179  35

[2 rows x 26 columns]
subsetted cells to: (22215, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CMP_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_CMP_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 4219 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['15', '16', '20', '21']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9  ...   13  \
doublets_manual                                                     ...
no                357  299  264  263  257  245  238  234  229  220  ...  185
yes                 0    0    0    0    0    0    0    0    0    0  ...    0

leiden_harmony_2   14   15   16   17   18  19  20  21  22
doublets_manual
no                176    0    0  148  127  28   0   0  10
yes                 0  163  149    0    0   0  25  14   0

[2 rows x 23 columns]
subsetted cells to: (4219, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_naive_CD4_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_ISGpos_naive_CD4_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 24988 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                2188  2115  1966  1898  1837  1462  1336  1267  1234  1182
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...   12   13   14   15   16   17   18   19   20   21
doublets_manual   ...
no                ...  917  873  824  705  679    0  607  460  401  204
yes               ...    0    0    0    0    0  630    0    0    0    0

[2 rows x 22 columns]
subsetted cells to: (24988, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMKpos_Vd2_gdT
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_GZMKpos_Vd2_gdT_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 36951 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['21', '23']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                3195  3074  2715  2581  2555  2553  2412  2207  2092  1919
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...    14    15   16   17   18   19   20   21   22  23
doublets_manual   ...
no                ...  1293  1064  746  642  602  391  372    0  164   0
yes               ...     0     0    0    0    0    0    0  266    0  72

[2 rows x 24 columns]
subsetted cells to: (36951, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: SOX4pos_Vd1_gdT
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_SOX4pos_Vd1_gdT_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 1884 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['18']
leiden_harmony_2    0    1    2    3    4    5    6    7   8   9  10  11  12  \
doublets_manual
no                230  223  163  139  134  130  115  100  96  90  84  66  61
yes                 0    0    0    0    0    0    0    0   0   0   0   0   0

leiden_harmony_2  13  14  15  16  17  18
doublets_manual
no                58  51  47  43  32   0
yes                0   0   0   0   0  22
subsetted cells to: (1884, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Core_CD16_monocyte
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Core_CD16_monocyte_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 176734 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['13', '16', '18', '20', '21']
leiden_harmony_2      0      1      2      3      4      5      6      7  \
doublets_manual
no                15927  15687  15544  13942  12875  12136  10787  10305
yes                   0      0      0      0      0      0      0      0

leiden_harmony_2     8     9  ...    12    13    14    15    16    17    18  \
doublets_manual               ...
no                8768  8587  ...  5408     0  4530  4418     0  4255     0
yes                  0     0  ...     0  5386     0     0  4261     0  3002

leiden_harmony_2    19    20    21
doublets_manual
no                2579     0     0
yes                  0  1716  1547

[2 rows x 22 columns]
subsetted cells to: (176734, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 94133 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['19', '23']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                8217  7442  6669  6184  6149  5733  5693  5538  5484  5270
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...    17    18    19   20   21   22   23   24   25   26
doublets_manual   ...
no                ...  2380  1648     0  777  656  623    0  421  361  202
yes               ...     0     0  1408    0    0    0  510    0    0    0

[2 rows x 27 columns]
Clusters to relabel: (['KLRF1-_GZMB+_CD27-_mem_CD4_uk1'], ['5', '6'])
leiden_harmony_2                         0     1     2     3     4     5  \
AIFI_L3_new
KLRF1- GZMB+ CD27- memory CD4 T cell  8217  7442  6669  6184  6149     0
KLRF1-_GZMB+_CD27-_mem_CD4_uk1           0     0     0     0     0  5733

leiden_harmony_2                         6     7     8     9  ...    17    18  \
AIFI_L3_new                                                   ...
KLRF1- GZMB+ CD27- memory CD4 T cell     0  5538  5484  5270  ...  2380  1648
KLRF1-_GZMB+_CD27-_mem_CD4_uk1        5693     0     0     0  ...     0     0

leiden_harmony_2                        19   20   21   22   23   24   25   26
AIFI_L3_new
KLRF1- GZMB+ CD27- memory CD4 T cell  1408  777  656  623  510  421  361  202
KLRF1-_GZMB+_CD27-_mem_CD4_uk1           0    0    0    0    0    0    0    0

[2 rows x 27 columns]
subsetted cells to: (94133, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_CD56dim_NK_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_ISGpos_CD56dim_NK_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 14470 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['6', '11', '17', '18', '19', '20', '21', '23']
leiden_harmony_2     0     1     2    3    4    5    6    7    8    9  ...  \
doublets_manual                                                        ...
no                1353  1056  1042  939  927  840    0  727  676  647  ...
yes                  0     0     0    0    0    0  836    0    0    0  ...

leiden_harmony_2   14   15   16   17   18   19   20   21   22   23
doublets_manual
no                499  451  421    0    0    0    0    0  152    0
yes                 0    0    0  361  353  286  261  226    0  144

[2 rows x 24 columns]
subsetted cells to: (14470, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMKneg_CD56dim_NK_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_GZMKneg_CD56dim_NK_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 487628 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['13', '15', '16', '17', '18', '12', '19']
leiden_harmony_2      0      1      2      3      4      5      6      7  \
doublets_manual
no                51821  43509  42182  41736  37345  34158  33846  33500
yes                   0      0      0      0      0      0      0      0

leiden_harmony_2      8      9  ...    16    17   18   19  20  21  22  23  24  \
doublets_manual                 ...
no                31026  27255  ...     0     0    0    0  15   8   7   4   3
yes                   0      0  ...  7509  7464  863  401   0   0   0   0   0

leiden_harmony_2  25
doublets_manual
no                 2
yes                0

[2 rows x 26 columns]
subsetted cells to: (487628, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CLP_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_CLP_cell_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 1215 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['11']
leiden_harmony_2    0    1    2    3   4   5   6   7   8   9  10  11  12  13  \
doublets_manual
no                130  114  106  102  99  90  84  83  79  70  65   0  62  61
yes                 0    0    0    0   0   0   0   0   0   0   0  63   0   0

leiden_harmony_2  14
doublets_manual
no                 7
yes                0
subsetted cells to: (1215, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_memory_CD4_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_ISGpos_memory_CD4_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 21910 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['20', '21']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                1747  1523  1360  1335  1269  1228  1227  1134  1124  1107
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...   13   14   15   16   17   18   19   20  21  22
doublets_manual   ...
no                ...  901  890  819  812  786  697  540    0   0  20
yes               ...    0    0    0    0    0    0    0  447  71   0

[2 rows x 23 columns]
Clusters to relabel: (['ISG+ memory CD4 T cell_uk1_CD8'], ['15'])
leiden_harmony_2                   0     1     2     3     4     5     6  \
AIFI_L3_new
ISG+ memory CD4 T cell          1747  1523  1360  1335  1269  1228  1227
ISG+ memory CD4 T cell_uk1_CD8     0     0     0     0     0     0     0

leiden_harmony_2                   7     8     9  ...   13   14   15   16  \
AIFI_L3_new                                       ...
ISG+ memory CD4 T cell          1134  1124  1107  ...  901  890    0  812
ISG+ memory CD4 T cell_uk1_CD8     0     0     0  ...    0    0  819    0

leiden_harmony_2                 17   18   19   20  21  22
AIFI_L3_new
ISG+ memory CD4 T cell          786  697  540  447  71  20
ISG+ memory CD4 T cell_uk1_CD8    0    0    0    0   0   0

[2 rows x 23 columns]
subsetted cells to: (21910, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ASDC
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_ASDC_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 2107 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['2', '11', '16']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no                224  215    0  160  158  148  147  115  111  109  106    0
yes                 0    0  211    0    0    0    0    0    0    0    0  103

leiden_harmony_2  12  13  14  15  16  17
doublets_manual
no                85  84  63  47   0   7
yes                0   0   0   0  14   0
Clusters to relabel: (['ASDC_uk1_B'], ['0', '1', '7'])
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9   10   11  \
AIFI_L3_new
ASDC                0    0  211  160  158  148  147    0  111  109  106  103
ASDC_uk1_B        224  215    0    0    0    0    0  115    0    0    0    0

leiden_harmony_2  12  13  14  15  16  17
AIFI_L3_new
ASDC              85  84  63  47  14   7
ASDC_uk1_B         0   0   0   0   0   0
subsetted cells to: (2107, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Erythrocyte
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Erythrocyte_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 16648 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['2', '3', '6', '7', '9', '12', '13', '15', '16', '17', '18', '19']
leiden_harmony_2     0     1     2     3     4     5     6     7    8    9  \
doublets_manual
no                1705  1441     0     0  1175  1134     0     0  988    0
yes                  0     0  1374  1181     0     0  1115  1011    0  964

leiden_harmony_2   10   11   12   13   14   15   16   17   18   19
doublets_manual
no                782  719    0    0  545    0    0    0    0    0
yes                 0    0  639  601    0  418  246  240  217  153
subsetted cells to: (16648, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: DN_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_DN_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 11697 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['22', '23', '24']
leiden_harmony_2     0    1    2    3    4    5    6    7    8    9  ...   15  \
doublets_manual                                                      ...
no                1156  985  966  842  705  622  586  584  565  507  ...  363
yes                  0    0    0    0    0    0    0    0    0    0  ...    0

leiden_harmony_2   16   17   18   19   20   21  22  23  24
doublets_manual
no                282  276  256  240  205  103   0   0   0
yes                 0    0    0    0    0    0  89  37  12

[2 rows x 25 columns]
subsetted cells to: (11697, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: KLRF1neg_effector_Vd1_gdT
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_KLRF1neg_effector_Vd1_gdT_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 7290 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['0', '6', '18', '19', '20']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9  ...   12  \
doublets_manual                                                     ...
no                  0  592  589  555  547  540    0  490  387  364  ...  291
yes               787    0    0    0    0    0  501    0    0    0  ...    0

leiden_harmony_2   13   14   15   16   17  18  19  20  21
doublets_manual
no                268  168  156  122  100   0   0   0  30
yes                 0    0    0    0    0  71  57  45   0

[2 rows x 22 columns]
subsetted cells to: (7290, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_cDC2
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_ISGpos_cDC2_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 5266 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['2', '14', '16']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no                479  436    0  385  357  353  331  304  292  288  284  262
yes                 0    0  406    0    0    0    0    0    0    0    0    0

leiden_harmony_2   12   13   14   15  16  17
doublets_manual
no                251  248    0  241   0  50
yes                 0    0  244    0  55   0
subsetted cells to: (5266, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Core_naive_CD4_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Core_naive_CD4_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 1619213 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['15', '17', '19', '20', ' 21']
leiden_harmony_2       0       1       2       3       4       5      6  \
doublets_manual
no                147615  130896  107698  106274  106271  101064  98055
yes                    0       0       0       0       0       0      0

leiden_harmony_2      7      8      9  ...     14     15     16     17     18  \
doublets_manual                        ...
no                95585  95478  89204  ...  63103      0  31843      0  23643
yes                   0      0      0  ...      0  43440      0  25890      0

leiden_harmony_2     19    20    21    22   23
doublets_manual
no                    0     0  5029  2436  824
yes               21114  9872     0     0    0

[2 rows x 24 columns]
subsetted cells to: (1619213, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_memory_CD8_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_ISGpos_memory_CD8_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 4329 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9  ...   11  \
doublets_manual                                                     ...
no                381  338  314  277  259  252  251  239  233  222  ...  203
yes                 0    0    0    0    0    0    0    0    0    0  ...    0

leiden_harmony_2   12   13   14   15   16   17  18  19  20
doublets_manual
no                198  193  171  163  138    0  89  70  30
yes                 0    0    0    0    0  101   0   0   0

[2 rows x 21 columns]
subsetted cells to: (4329, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Type_2_polarized_memory_B_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Type_2_polarized_memory_B_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 10419 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['11', '18', '20']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9  ...   11  \
doublets_manual                                                     ...
no                985  937  870  795  717  706  697  604  511  498  ...    0
yes                 0    0    0    0    0    0    0    0    0    0  ...  467

leiden_harmony_2   12   13   14   15   16   17   18   19  20
doublets_manual
no                457  390  353  251  228  165    0  106   0
yes                 0    0    0    0    0    0  109    0  98

[2 rows x 21 columns]
Clusters to relabel: (['T2MBC_uk1'], ['19'])
leiden_harmony_2                  0    1    2    3    4    5    6    7    8  \
AIFI_L3_new
T2MBC_uk1                         0    0    0    0    0    0    0    0    0
Type 2 polarized memory B cell  985  937  870  795  717  706  697  604  511

leiden_harmony_2                  9  ...   11   12   13   14   15   16   17  \
AIFI_L3_new                          ...
T2MBC_uk1                         0  ...    0    0    0    0    0    0    0
Type 2 polarized memory B cell  498  ...  467  457  390  353  251  228  165

leiden_harmony_2                 18   19  20
AIFI_L3_new
T2MBC_uk1                         0  106   0
Type 2 polarized memory B cell  109    0  98

[2 rows x 21 columns]
subsetted cells to: (10419, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 267555 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17', '25', '30']
leiden_harmony_2      0      1      2      3      4      5      6      7  \
doublets_manual
no                25804  18700  18003  17166  16945  16615  13348  12355
yes                   0      0      0      0      0      0      0      0

leiden_harmony_2      8      9  ...    21    22    23    24    25    26    27  \
doublets_manual                 ...
no                11775  10470  ...  4910  3946  3729  2486     0  1715  1465
yes                   0      0  ...     0     0     0     0  2201     0     0

leiden_harmony_2   28   29   30
doublets_manual
no                645  455    0
yes                 0    0  322

[2 rows x 31 columns]
Clusters to relabel: (['KLRF1-_GZMB+_CD27-_EM_CD8_uk1'], ['20'])
leiden_harmony_2                      0      1      2      3      4      5  \
AIFI_L3_new
KLRF1- GZMB+ CD27- EM CD8 T cell  25804  18700  18003  17166  16945  16615
KLRF1-_GZMB+_CD27-_EM_CD8_uk1         0      0      0      0      0      0

leiden_harmony_2                      6      7      8      9  ...    21    22  \
AIFI_L3_new                                                   ...
KLRF1- GZMB+ CD27- EM CD8 T cell  13348  12355  11775  10470  ...  4910  3946
KLRF1-_GZMB+_CD27-_EM_CD8_uk1         0      0      0      0  ...     0     0

leiden_harmony_2                    23    24    25    26    27   28   29   30
AIFI_L3_new
KLRF1- GZMB+ CD27- EM CD8 T cell  3729  2486  2201  1715  1465  645  455  322
KLRF1-_GZMB+_CD27-_EM_CD8_uk1        0     0     0     0     0    0    0    0

[2 rows x 31 columns]
subsetted cells to: (267555, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: HLAnegDRhi_cDC2
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_HLAnegDRhi_cDC2_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 35682 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['8', '19', '21', '25', '26', '27']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                2397  2092  1852  1843  1774  1755  1754  1704     0  1632
yes                  0     0     0     0     0     0     0     0  1635     0

leiden_harmony_2  ...    18    19   20   21   22   23   24   25   26  27
doublets_manual   ...
no                ...  1123     0  704    0  632  482  421    0    0   0
yes               ...     0  1041    0  684    0    0    0  310  146  78

[2 rows x 28 columns]
subsetted cells to: (35682, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMKpos_CD56dim_NK_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_GZMKpos_CD56dim_NK_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 46350 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['14', '20', '18', '17']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                3692  3415  3159  3090  3054  2929  2914  2815  2696  2662
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...    13    14    15    16   17   18   19   20   21   22
doublets_manual   ...
no                ...  1875     0  1446  1410    0    0  272    0  202  155
yes               ...     0  1801     0     0  575  564    0  233    0    0

[2 rows x 23 columns]
subsetted cells to: (46350, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Proliferating_NK_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Proliferating_NK_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 12257 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['12', '14', '17', '18', '19']
leiden_harmony_2     0    1    2    3    4    5    6    7    8    9  ...   11  \
doublets_manual                                                      ...
no                1312  996  988  973  903  875  857  844  741  711  ...  539
yes                  0    0    0    0    0    0    0    0    0    0  ...    0

leiden_harmony_2   12   13   14   15   16  17  18  19  20
doublets_manual
no                  0  331    0  316  202   0   0   0  52
yes               408    0  317    0    0  74  66  56   0

[2 rows x 21 columns]
subsetted cells to: (12257, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_CD14_monocyte
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_ISGpos_CD14_monocyte_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 185237 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['5', '18', '25', '28', '22', '29']
leiden_harmony_2      0      1      2      3      4      5      6     7     8  \
doublets_manual
no                12196  11700  11151  10532  10395      0  10049  9680  9292
yes                   0      0      0      0      0  10177      0     0     0

leiden_harmony_2     9  ...    20    21    22    23    24    25   26   27  \
doublets_manual         ...
no                9105  ...  5088  4012     0  2136  1921     0  752  531
yes                  0  ...     0     0  3077     0     0  1428    0    0

leiden_harmony_2   28   29
doublets_manual
no                  0    0
yes               444  318

[2 rows x 30 columns]
subsetted cells to: (185237, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMBneg_CD27neg_EM_CD4_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_GZMBneg_CD27neg_EM_CD4_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 292580 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['3', '13', '14', '20', '21', '23', '24']
leiden_harmony_2      0      1      2      3      4      5      6      7  \
doublets_manual
no                25350  24167  19555      0  17953  16455  15041  14877
yes                   0      0      0  19298      0      0      0      0

leiden_harmony_2      8      9  ...    15    16    17    18    19    20    21  \
doublets_manual                 ...
no                14759  14326  ...  9607  9304  9005  8916  6098     0     0
yes                   0      0  ...     0     0     0     0     0  2322  1151

leiden_harmony_2    22    23   24
doublets_manual
no                1068     0    0
yes                  0  1063  595

[2 rows x 25 columns]
Clusters to relabel: (['GZMB- CD27- EM CD4 T cell_uk1_CD8'], ['6'])
leiden_harmony_2                       0      1      2      3      4      5  \
AIFI_L3_new
GZMB- CD27- EM CD4 T cell          25350  24167  19555  19298  17953  16455
GZMB- CD27- EM CD4 T cell_uk1_CD8      0      0      0      0      0      0

leiden_harmony_2                       6      7      8      9  ...    15  \
AIFI_L3_new                                                    ...
GZMB- CD27- EM CD4 T cell              0  14877  14759  14326  ...  9607
GZMB- CD27- EM CD4 T cell_uk1_CD8  15041      0      0      0  ...     0

leiden_harmony_2                     16    17    18    19    20    21    22  \
AIFI_L3_new
GZMB- CD27- EM CD4 T cell          9304  9005  8916  6098  2322  1151  1068
GZMB- CD27- EM CD4 T cell_uk1_CD8     0     0     0     0     0     0     0

leiden_harmony_2                     23   24
AIFI_L3_new
GZMB- CD27- EM CD4 T cell          1063  595
GZMB- CD27- EM CD4 T cell_uk1_CD8     0    0

[2 rows x 25 columns]
subsetted cells to: (292580, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CM_CD8_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_CM_CD8_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 131620 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['18', '19']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                9796  9460  9324  8979  8675  8552  8028  7200  7123  7025
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...    11    12    13    14    15    16    17    18   19  \
doublets_manual   ...
no                ...  6608  6548  5830  5225  4479  4308  3797     0    0
yes               ...     0     0     0     0     0     0     0  2312  831

leiden_harmony_2   20
doublets_manual
no                629
yes                 0

[2 rows x 21 columns]
subsetted cells to: (131620, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Activated_memory_B_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Activated_memory_B_cell_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 1633 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['2', '12']
leiden_harmony_2    0    1    2    3    4    5    6    7    8   9  10  11  12
doublets_manual
no                226  199    0  145  138  121  118  115  106  99  95  81   0
yes                 0    0  169    0    0    0    0    0    0   0   0   0  21
Clusters to relabel: (['Activated memory B cell_uk1'], ['1'])
leiden_harmony_2               0    1    2    3    4    5    6    7    8   9  \
AIFI_L3_new
Activated memory B cell      226    0  169  145  138  121  118  115  106  99
Activated memory B cell_uk1    0  199    0    0    0    0    0    0    0   0

leiden_harmony_2             10  11  12
AIFI_L3_new
Activated memory B cell      95  81  21
Activated memory B cell_uk1   0   0   0
subsetted cells to: (1633, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Memory_CD4_Treg
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Memory_CD4_Treg_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 102998 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['20', '22', '23']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                8813  7952  7741  7676  7622  7218  6192  6004  5706  5573
yes                  0     0     0     0     0     0     0     0     0     0

leiden_harmony_2  ...    14    15    16    17    18    19    20    21   22  \
doublets_manual   ...
no                ...  2633  2604  2564  2473  2177  1931     0  1006    0
yes               ...     0     0     0     0     0     0  1432     0  835

leiden_harmony_2   23
doublets_manual
no                  0
yes               251

[2 rows x 24 columns]
subsetted cells to: (102998, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMKneg_CD27pos_EM_CD8_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_GZMKneg_CD27pos_EM_CD8_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 18404 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['18', '20', '15']
leiden_harmony_2     0     1     2     3     4     5     6     7     8    9  \
doublets_manual
no                1789  1531  1473  1432  1427  1314  1295  1100  1078  944
yes                  0     0     0     0     0     0     0     0     0    0

leiden_harmony_2  ...   11   12   13   14   15   16   17   18  19  20
doublets_manual   ...
no                ...  745  716  657  555    0  452  265    0  58   0
yes               ...    0    0    0    0  461    0    0  210   0  31

[2 rows x 21 columns]
subsetted cells to: (18404, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Plasma_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Plasma_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 7746 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['9', '14', '21']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9  ...   12  \
doublets_manual                                                     ...
no                603  557  553  540  491  477  453  434  404    0  ...  290
yes                 0    0    0    0    0    0    0    0    0  396  ...    0

leiden_harmony_2   13   14   15   16   17   18   19   20  21
doublets_manual
no                273    0  257  236  224  209  190  166   0
yes                 0  267    0    0    0    0    0    0  16

[2 rows x 22 columns]
subsetted cells to: (7746, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Proliferating_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Proliferating_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 9838 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['12', '24', '25']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9  ...   16  \
doublets_manual                                                     ...
no                799  714  621  589  588  576  571  553  470  455  ...  285
yes                 0    0    0    0    0    0    0    0    0    0  ...    0

leiden_harmony_2   17   18   19   20   21   22  23  24  25
doublets_manual
no                257  242  216  200  196  126  82   0   0
yes                 0    0    0    0    0    0   0  66  46

[2 rows x 26 columns]
Clusters to relabel: (['Prolif_T_uk1'], ['16'])
leiden_harmony_2        0    1    2    3    4    5    6    7    8    9  ...  \
AIFI_L3_new                                                             ...
Prolif_T_uk1            0    0    0    0    0    0    0    0    0    0  ...
Proliferating T cell  799  714  621  589  588  576  571  553  470  455  ...

leiden_harmony_2       16   17   18   19   20   21   22  23  24  25
AIFI_L3_new
Prolif_T_uk1          285    0    0    0    0    0    0   0   0   0
Proliferating T cell    0  257  242  216  200  196  126  82  66  46

[2 rows x 26 columns]
subsetted cells to: (9838, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD14pos_cDC2
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_CD14pos_cDC2_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 26816 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['4', '16', '18', '19', '21', '22']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                2443  1994  1850  1697     0  1494  1465  1454  1370  1322
yes                  0     0     0     0  1686     0     0     0     0     0

leiden_harmony_2  ...    14    15   16   17   18   19   20   21  22  23
doublets_manual   ...
no                ...  1172  1134    0  583    0    0  165    0   0  40
yes               ...     0     0  977    0  569  332    0  108  42   0

[2 rows x 24 columns]
subsetted cells to: (26816, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Naive_Vd1_gdT
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_Naive_Vd1_gdT_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 7830 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['19']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9  ...   13  \
doublets_manual                                                     ...
no                766  746  635  484  477  474  441  433  418  402  ...  246
yes                 0    0    0    0    0    0    0    0    0    0  ...    0

leiden_harmony_2   14   15   16   17   18   19   20  21  22
doublets_manual
no                222  175  165  151  143    0  102  75  38
yes                 0    0    0    0    0  111    0   0   0

[2 rows x 23 columns]
subsetted cells to: (7830, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: SOX4pos_naive_CD8_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_SOX4pos_naive_CD8_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 7017 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['10', '21']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9  ...   13  \
doublets_manual                                                     ...
no                702  462  454  440  419  406  403  401  387  362  ...  256
yes                 0    0    0    0    0    0    0    0    0    0  ...    0

leiden_harmony_2   14   15   16   17   18   19   20  21  22
doublets_manual
no                240  237  192  192  190  183  111   0  15
yes                 0    0    0    0    0    0    0  66   0

[2 rows x 23 columns]
subsetted cells to: (7017, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: KLRB1pos_memory_CD4_Treg
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_KLRB1pos_memory_CD4_Treg_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 10439 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17', '21']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9  ...   12  \
doublets_manual                                                     ...
no                846  798  791  757  653  624  616  609  566  558  ...  403
yes                 0    0    0    0    0    0    0    0    0    0  ...    0

leiden_harmony_2   13   14   15   16   17   18   19   20  21
doublets_manual
no                402  401  377  310    0  213  167  145   0
yes                 0    0    0    0  226    0    0    0  31

[2 rows x 22 columns]
subsetted cells to: (10439, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_CD16_monocyte
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_ISGpos_CD16_monocyte_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 32609 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['2', '9', '12', '16', '19', '22', '23']
leiden_harmony_2     0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no                3530  2476     0  2336  2057  1958  1919  1674  1552     0
yes                  0     0  2423     0     0     0     0     0     0  1541

leiden_harmony_2  ...   15   16   17   18   19   20   21   22   23   24
doublets_manual   ...
no                ...  890    0  705  611    0  440  327    0    0  234
yes               ...    0  795    0    0  611    0    0  304  266    0

[2 rows x 25 columns]
subsetted cells to: (32609, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD95_memory_B_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_CD95_memory_B_cell_2024-05-25.h5ad
AnnData object with n_obs × n_vars = 7540 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['7', '8', '16']
leiden_harmony_2    0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no                634  576  550  515  510  501  481    0    0  452  400  397
yes                 0    0    0    0    0    0    0  468  457    0    0    0

leiden_harmony_2   12   13   14   15   16   17   18
doublets_manual
no                310  289  261  222    0  159  138
yes                 0    0    0    0  220    0    0
subsetted cells to: (7540, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMBneg_CD27pos_EM_CD4_T_cell
Value: ../../05-clustering/scripts/output/preRA_cluster_harmonize_GZMBneg_CD27pos_EM_CD4_T_cell_2024-05-26.h5ad
AnnData object with n_obs × n_vars = 326393 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit', 'file.id', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_harmony_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['21']
leiden_harmony_2      0      1      2      3      4      5      6      7  \
doublets_manual
no                27724  24361  23181  22194  22006  20925  20624  19585
yes                   0      0      0      0      0      0      0      0

leiden_harmony_2      8      9  ...    15    16    17    18    19    20    21  \
doublets_manual                 ...
no                18987  18131  ...  9085  7388  6134  5290  4688  4607     0
yes                   0      0  ...     0     0     0     0     0     0  1658

leiden_harmony_2    22    23   24
doublets_manual
no                1291  1119  280
yes                  0     0    0

[2 rows x 25 columns]
Clusters to relabel: (['GZMB- CD27+ EM CD4 T cell_uk1_CD8'], ['15'])
leiden_harmony_2                       0      1      2      3      4      5  \
AIFI_L3_new
GZMB- CD27+ EM CD4 T cell          27724  24361  23181  22194  22006  20925
GZMB- CD27+ EM CD4 T cell_uk1_CD8      0      0      0      0      0      0

leiden_harmony_2                       6      7      8      9  ...    15  \
AIFI_L3_new                                                    ...
GZMB- CD27+ EM CD4 T cell          20624  19585  18987  18131  ...     0
GZMB- CD27+ EM CD4 T cell_uk1_CD8      0      0      0      0  ...  9085

leiden_harmony_2                     16    17    18    19    20    21    22  \
AIFI_L3_new
GZMB- CD27+ EM CD4 T cell          7388  6134  5290  4688  4607  1658  1291
GZMB- CD27+ EM CD4 T cell_uk1_CD8     0     0     0     0     0     0     0

leiden_harmony_2                     23   24
AIFI_L3_new
GZMB- CD27+ EM CD4 T cell          1119  280
GZMB- CD27+ EM CD4 T cell_uk1_CD8     0    0

[2 rows x 25 columns]
subsetted cells to: (326393, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c
/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

In [165]:
out_files

['output/preRA_deepcleaned_CD4_MAIT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_naive_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Adaptive_NK_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Early_memory_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CD56bright_NK_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Intermediate_monocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Core_naive_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Transitional_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_pDC_2024-06-13.h5ad',
 'output/preRA_deepcleaned_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CM_CD4_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Core_naive_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Memory_CD8_Treg_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CD8aa_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_MAIT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ILC_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CD27neg_effector_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_cDC1_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CD27pos_effector_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMKpos_CD27pos_EM_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Platelet_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Naive_CD4_Treg_2024-06-13.h5ad',
 'output/preRA_deepcleaned_IL1Bpos_CD14_monocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_KLRF1pos_effector_Vd1_gdT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Core_memory_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMKpos_memory_CD4_Treg_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Core_CD14_monocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMBpos_Vd2_gdT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_SOX4pos_naive_CD4_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_KLRB1pos_memory_CD8_Treg_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CD8_MAIT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_BaEoMaP_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_naive_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_C1Qpos_CD16_monocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CMP_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_naive_CD4_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMKpos_Vd2_gdT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_SOX4pos_Vd1_gdT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Core_CD16_monocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_CD56dim_NK_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMKneg_CD56dim_NK_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CLP_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_memory_CD4_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ASDC_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Erythrocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_DN_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_KLRF1neg_effector_Vd1_gdT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_cDC2_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Core_naive_CD4_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_memory_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Type_2_polarized_memory_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_HLAnegDRhi_cDC2_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMKpos_CD56dim_NK_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Proliferating_NK_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_CD14_monocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMBneg_CD27neg_EM_CD4_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CM_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Activated_memory_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Memory_CD4_Treg_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMKneg_CD27pos_EM_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Plasma_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Proliferating_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CD14pos_cDC2_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Naive_Vd1_gdT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_SOX4pos_naive_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_KLRB1pos_memory_CD4_Treg_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_CD16_monocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CD95_memory_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMBneg_CD27pos_EM_CD4_T_cell_2024-06-13.h5ad']

In [166]:
len(out_files)

71

## Export Doublet Metadata

In [39]:
doublet_meta_comb = pd.concat(doublet_meta)

In [42]:
### check metadata
len(doublet_meta_comb['AIFI_L3'].unique())

71

In [43]:
### export
doublet_meta_comb.to_csv("../data/preRA_scRNA_512_samples_doublet_metadata_all_types.csv")

## Upload Cell Type data to HISE

Finally, we'll use `hisepy.upload.upload_files()` to send a copy of our output to HISE to use for downstream analysis steps.

In [173]:
study_space_uuid = '223de760-9624-45bd-aefe-ca24c75b1800'
title = 'IDE for 06 PBMC L3 Deepclean {d}'.format(d = date.today())
title

'IDE for 06 PBMC L3 Deepclean 2024-06-13'

In [168]:
search_id = element_id()
search_id

'molybdenum-niobium-krypton'

In [169]:
in_files = list(h5ad_uuids.values())
in_files

['704874eb-d661-4ca3-bb4c-a0f4c20c5fe9',
 '3ccbd155-2b80-4fd7-8988-ef4462198ccf',
 '2db8c682-b9da-4be7-87ce-4449618222e8',
 '3d754896-d258-449e-9739-f6d921607201',
 '00a560a8-499c-4cc3-98fc-b4f93f6f0d91',
 '63217d12-5f51-4668-9ad8-dea66b394581',
 'f9d59339-9182-48e0-abf2-8a4d48cee5f6',
 'abd08fae-e2ed-4a09-8c2e-38c2531c56eb',
 '6edd318c-5481-4b7c-99a6-f4cdcd44daba',
 '68a4eda0-8312-4f07-a661-c834dcc403f7',
 'fe28ae5f-8f35-49ec-a1d8-6a5723c1d80f',
 '38d11eaf-6f15-4908-8b23-90990b55ec98',
 '5a22953e-96a2-4b38-b79f-edddaf98ad39',
 '8c9ccdaa-30c5-4afa-ae8a-9d88e008ef18',
 '920734fd-943d-42b2-8216-7fc458e30c77',
 '23088aa5-7ec2-4e2a-a117-a83c2c0485d7',
 '69fd7a3a-b26e-4cb3-b3cd-76584c7f25ea',
 '2d91757a-efcb-4428-b396-0d82abebbbfa',
 '8083ad79-29cb-4838-81b6-9481b348b8b7',
 '2e5e1d81-855d-4fc7-ba30-d5a69904ba4d',
 '80d25082-5f70-4f4e-9ef1-c9d0373c7061',
 '6a34dd0b-d984-4397-a049-92b3782fb327',
 '8d68c740-389d-4e68-bda8-aad6dde3ee10',
 '0eeb81ba-3caa-4d76-95b8-05346f4a405b',
 'e8439aa9-7a54-4630-a461-a5959cd06ee9',
 '8c10e2e8-f3e7-4161-9f6d-730e26867137',
 'c93c7614-3d3f-4b36-a6f3-c94808dc754c',
 '82601892-b723-4e00-8e10-dd42dd2bab07',
 '08214f7b-7e51-4675-a08c-aa89d69e5c38',
 '2c909fb5-59ab-4ac1-914e-c5cb85d887e2',
 'e192cec7-80da-48d9-92da-637dd882545d',
 '3fbf1be4-1bdb-4527-a057-49f78e994ffe',
 '4e6c035a-01f9-40c0-a4b6-35ef1d85f851',
 'ddb00ae9-f991-42c3-90e1-58e32472ee8a',
 'f917166f-82be-4a15-91c0-d2be939d8120',
 '5c3e9fba-478f-4696-9236-38029a809bbd',
 '0780fec0-7794-4afa-ab0a-c538cc31a672',
 'a1171673-91fc-48ba-955d-cc45fbee344d',
 '1e89c310-6a42-4224-b547-0b8f086ebfaf',
 'db05eef8-d40c-4e3d-9365-b7984ea62065',
 'b17bf7c1-5435-4d92-b479-cb462a57c93c',
 '7b73ff6f-2e2b-468c-be5b-811f5bb15f96',
 '2112e53e-f357-4d95-9831-6cfff886c954',
 'c259f7c6-23cd-442c-90a1-56c4b153af18',
 '19a2a355-4d96-4952-9b84-eedef5660405',
 '18479084-1a31-444d-aca1-73421a2aa520',
 'e31f44b4-72e6-4ed8-8c6a-3e7b426fe160',
 '45dff235-37ec-4223-8ae8-f3d3c9f929cb',
 'd2173f6f-ac47-4137-a571-006dc1b3ddb5',
 '4b75bb8e-8872-4f3a-a143-00892d04ccb3',
 'd9616844-52df-4e63-b620-f4aec42f6f5a',
 'c8f1d77e-b7f4-4754-b52f-2b854dc4b687',
 '66035192-6ac4-4ee0-8054-8ab1cf8021da',
 'baacbafe-11f7-4efb-b024-38780aa5e3df',
 'a03e9b68-9ad4-43e1-99e0-fd9f13bf9683',
 'e7cf9937-2ec9-45ef-9483-965022d5721c',
 '2076d543-5e12-4b9c-bfee-24f9b4ae8bc0',
 'a0e9d362-1b63-4ad5-b372-732978c17910',
 'd64015a7-ba44-40f0-b880-ad15d75da56d',
 '122a79ae-7c62-4152-a0cc-7416e8b88e97',
 '67fba28c-48b2-4d5c-b909-ebda0c75933e',
 '4ddfd9c7-7de0-491b-9054-8781f0608380',
 '700213a0-42c9-4e2b-a659-beeb275f0b17',
 '687a4f2c-c12b-4275-bcd4-a15ef20839d1',
 '21c1c91e-c055-4cb4-a0d7-23476271f0af',
 '6731b94c-44b4-4646-a024-11da840fadca',
 'e7ae8e4e-c9f5-4798-9a7a-7fbd7f6593e2',
 '40e4d947-9308-4ada-8681-e62f66a37077',
 'b01b7837-cb0b-4c57-ba62-e133943e9852',
 'b75ca414-cb11-402f-aea5-8d1e000a2dad',
 '9aa7bc6c-306e-41ab-be7a-5776708e41e3']

In [170]:
out_files

['output/preRA_deepcleaned_CD4_MAIT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_naive_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Adaptive_NK_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Early_memory_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CD56bright_NK_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Intermediate_monocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Core_naive_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Transitional_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_pDC_2024-06-13.h5ad',
 'output/preRA_deepcleaned_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CM_CD4_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Core_naive_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Memory_CD8_Treg_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CD8aa_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_MAIT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ILC_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CD27neg_effector_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_cDC1_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CD27pos_effector_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMKpos_CD27pos_EM_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Platelet_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Naive_CD4_Treg_2024-06-13.h5ad',
 'output/preRA_deepcleaned_IL1Bpos_CD14_monocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_KLRF1pos_effector_Vd1_gdT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Core_memory_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMKpos_memory_CD4_Treg_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Core_CD14_monocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMBpos_Vd2_gdT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_SOX4pos_naive_CD4_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_KLRB1pos_memory_CD8_Treg_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CD8_MAIT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_BaEoMaP_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_naive_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_C1Qpos_CD16_monocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CMP_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_naive_CD4_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMKpos_Vd2_gdT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_SOX4pos_Vd1_gdT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Core_CD16_monocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_CD56dim_NK_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMKneg_CD56dim_NK_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CLP_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_memory_CD4_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ASDC_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Erythrocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_DN_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_KLRF1neg_effector_Vd1_gdT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_cDC2_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Core_naive_CD4_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_memory_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Type_2_polarized_memory_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_HLAnegDRhi_cDC2_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMKpos_CD56dim_NK_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Proliferating_NK_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_CD14_monocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMBneg_CD27neg_EM_CD4_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CM_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Activated_memory_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Memory_CD4_Treg_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMKneg_CD27pos_EM_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Plasma_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Proliferating_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CD14pos_cDC2_2024-06-13.h5ad',
 'output/preRA_deepcleaned_Naive_Vd1_gdT_2024-06-13.h5ad',
 'output/preRA_deepcleaned_SOX4pos_naive_CD8_T_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_KLRB1pos_memory_CD4_Treg_2024-06-13.h5ad',
 'output/preRA_deepcleaned_ISGpos_CD16_monocyte_2024-06-13.h5ad',
 'output/preRA_deepcleaned_CD95_memory_B_cell_2024-06-13.h5ad',
 'output/preRA_deepcleaned_GZMBneg_CD27pos_EM_CD4_T_cell_2024-06-13.h5ad']

In [171]:
hisepy.upload.upload_files(
    files = out_files,
    study_space_id = study_space_uuid,
    title = title,
    input_file_ids = in_files,
    destination = search_id
)

you are trying to upload file_ids... ['output/preRA_deepcleaned_CD4_MAIT_2024-06-13.h5ad', 'output/preRA_deepcleaned_ISGpos_naive_CD8_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_Adaptive_NK_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_Early_memory_B_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_CD56bright_NK_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_Intermediate_monocyte_2024-06-13.h5ad', 'output/preRA_deepcleaned_Core_naive_CD8_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_Transitional_B_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_pDC_2024-06-13.h5ad', 'output/preRA_deepcleaned_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_CM_CD4_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_Core_naive_B_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_Memory_CD8_Treg_2024-06-13.h5ad', 'output/preRA_deepcleaned_CD8aa_2024-06-13.h5ad', 'output/preRA_deepcleaned_ISGpos_MAIT_2024-06-13.h5ad', 'output/preRA_deepcleaned_ILC_2024-06-13.h5ad', 'output/preRA_deepcleaned_CD27neg_effector_B_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_cDC1_2024-06-13.h5ad', 'output/preRA_deepcleaned_CD27pos_effector_B_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_GZMKpos_CD27pos_EM_CD8_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_Platelet_2024-06-13.h5ad', 'output/preRA_deepcleaned_Naive_CD4_Treg_2024-06-13.h5ad', 'output/preRA_deepcleaned_IL1Bpos_CD14_monocyte_2024-06-13.h5ad', 'output/preRA_deepcleaned_KLRF1pos_effector_Vd1_gdT_2024-06-13.h5ad', 'output/preRA_deepcleaned_Core_memory_B_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_GZMKpos_memory_CD4_Treg_2024-06-13.h5ad', 'output/preRA_deepcleaned_Core_CD14_monocyte_2024-06-13.h5ad', 'output/preRA_deepcleaned_GZMBpos_Vd2_gdT_2024-06-13.h5ad', 'output/preRA_deepcleaned_SOX4pos_naive_CD4_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_KLRB1pos_memory_CD8_Treg_2024-06-13.h5ad', 'output/preRA_deepcleaned_CD8_MAIT_2024-06-13.h5ad', 'output/preRA_deepcleaned_BaEoMaP_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_ISGpos_naive_B_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_C1Qpos_CD16_monocyte_2024-06-13.h5ad', 'output/preRA_deepcleaned_CMP_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_ISGpos_naive_CD4_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_GZMKpos_Vd2_gdT_2024-06-13.h5ad', 'output/preRA_deepcleaned_SOX4pos_Vd1_gdT_2024-06-13.h5ad', 'output/preRA_deepcleaned_Core_CD16_monocyte_2024-06-13.h5ad', 'output/preRA_deepcleaned_KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_ISGpos_CD56dim_NK_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_GZMKneg_CD56dim_NK_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_CLP_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_ISGpos_memory_CD4_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_ASDC_2024-06-13.h5ad', 'output/preRA_deepcleaned_Erythrocyte_2024-06-13.h5ad', 'output/preRA_deepcleaned_DN_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_KLRF1neg_effector_Vd1_gdT_2024-06-13.h5ad', 'output/preRA_deepcleaned_ISGpos_cDC2_2024-06-13.h5ad', 'output/preRA_deepcleaned_Core_naive_CD4_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_ISGpos_memory_CD8_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_Type_2_polarized_memory_B_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_HLAnegDRhi_cDC2_2024-06-13.h5ad', 'output/preRA_deepcleaned_GZMKpos_CD56dim_NK_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_Proliferating_NK_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_ISGpos_CD14_monocyte_2024-06-13.h5ad', 'output/preRA_deepcleaned_GZMBneg_CD27neg_EM_CD4_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_CM_CD8_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_Activated_memory_B_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_Memory_CD4_Treg_2024-06-13.h5ad', 'output/preRA_deepcleaned_GZMKneg_CD27pos_EM_CD8_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_Plasma_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_Proliferating_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_CD14pos_cDC2_2024-06-13.h5ad', 'output/preRA_deepcleaned_Naive_Vd1_gdT_2024-06-13.h5ad', 'output/preRA_deepcleaned_SOX4pos_naive_CD8_T_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_KLRB1pos_memory_CD4_Treg_2024-06-13.h5ad', 'output/preRA_deepcleaned_ISGpos_CD16_monocyte_2024-06-13.h5ad', 'output/preRA_deepcleaned_CD95_memory_B_cell_2024-06-13.h5ad', 'output/preRA_deepcleaned_GZMBneg_CD27pos_EM_CD4_T_cell_2024-06-13.h5ad']. Do you truly want to proceed?

(y/n) y

{'trace_id': 'eed482fd-9d4e-4752-8d90-b908296eff6f',
 'files': ['output/preRA_deepcleaned_CD4_MAIT_2024-06-13.h5ad',
  'output/preRA_deepcleaned_ISGpos_naive_CD8_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Adaptive_NK_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Early_memory_B_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_CD56bright_NK_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Intermediate_monocyte_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Core_naive_CD8_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Transitional_B_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_pDC_2024-06-13.h5ad',
  'output/preRA_deepcleaned_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_CM_CD4_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Core_naive_B_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Memory_CD8_Treg_2024-06-13.h5ad',
  'output/preRA_deepcleaned_CD8aa_2024-06-13.h5ad',
  'output/preRA_deepcleaned_ISGpos_MAIT_2024-06-13.h5ad',
  'output/preRA_deepcleaned_ILC_2024-06-13.h5ad',
  'output/preRA_deepcleaned_CD27neg_effector_B_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_cDC1_2024-06-13.h5ad',
  'output/preRA_deepcleaned_CD27pos_effector_B_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_GZMKpos_CD27pos_EM_CD8_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Platelet_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Naive_CD4_Treg_2024-06-13.h5ad',
  'output/preRA_deepcleaned_IL1Bpos_CD14_monocyte_2024-06-13.h5ad',
  'output/preRA_deepcleaned_KLRF1pos_effector_Vd1_gdT_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Core_memory_B_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_GZMKpos_memory_CD4_Treg_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Core_CD14_monocyte_2024-06-13.h5ad',
  'output/preRA_deepcleaned_GZMBpos_Vd2_gdT_2024-06-13.h5ad',
  'output/preRA_deepcleaned_SOX4pos_naive_CD4_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_KLRB1pos_memory_CD8_Treg_2024-06-13.h5ad',
  'output/preRA_deepcleaned_CD8_MAIT_2024-06-13.h5ad',
  'output/preRA_deepcleaned_BaEoMaP_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_ISGpos_naive_B_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_C1Qpos_CD16_monocyte_2024-06-13.h5ad',
  'output/preRA_deepcleaned_CMP_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_ISGpos_naive_CD4_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_GZMKpos_Vd2_gdT_2024-06-13.h5ad',
  'output/preRA_deepcleaned_SOX4pos_Vd1_gdT_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Core_CD16_monocyte_2024-06-13.h5ad',
  'output/preRA_deepcleaned_KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_ISGpos_CD56dim_NK_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_GZMKneg_CD56dim_NK_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_CLP_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_ISGpos_memory_CD4_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_ASDC_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Erythrocyte_2024-06-13.h5ad',
  'output/preRA_deepcleaned_DN_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_KLRF1neg_effector_Vd1_gdT_2024-06-13.h5ad',
  'output/preRA_deepcleaned_ISGpos_cDC2_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Core_naive_CD4_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_ISGpos_memory_CD8_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Type_2_polarized_memory_B_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_HLAnegDRhi_cDC2_2024-06-13.h5ad',
  'output/preRA_deepcleaned_GZMKpos_CD56dim_NK_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Proliferating_NK_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_ISGpos_CD14_monocyte_2024-06-13.h5ad',
  'output/preRA_deepcleaned_GZMBneg_CD27neg_EM_CD4_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_CM_CD8_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Activated_memory_B_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Memory_CD4_Treg_2024-06-13.h5ad',
  'output/preRA_deepcleaned_GZMKneg_CD27pos_EM_CD8_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Plasma_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Proliferating_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_CD14pos_cDC2_2024-06-13.h5ad',
  'output/preRA_deepcleaned_Naive_Vd1_gdT_2024-06-13.h5ad',
  'output/preRA_deepcleaned_SOX4pos_naive_CD8_T_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_KLRB1pos_memory_CD4_Treg_2024-06-13.h5ad',
  'output/preRA_deepcleaned_ISGpos_CD16_monocyte_2024-06-13.h5ad',
  'output/preRA_deepcleaned_CD95_memory_B_cell_2024-06-13.h5ad',
  'output/preRA_deepcleaned_GZMBneg_CD27pos_EM_CD4_T_cell_2024-06-13.h5ad']}

In [172]:
import session_info
session_info.show()