# TP1

Dans ce premier TP, vous allez découvrir la bibliothèque Pandas de Python. Ce premier Notebook vous permettra de vous famliariser avec les principales fonctions de pandas.

Quelques ressources :
- [site officiel de la bibliothèque pandas](http://pandas.pydata.org/)
- [comment utiliser IPython/Jupyter notebook](https://youtu.be/IsXXlYVBt1M?t=5m17s)

In [1]:
import pandas as pd

## Découverte des fonctions principales

1. Téléchargez le fichier `imdb_sample.csv` puis chargez le dans une variable `df` via la fonction [read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html). Prenez le temps de lire la documentation de la fonction `read_csv` et de découvrir les différents arguments qui existent.

In [2]:
df = pd.read_csv("imdb_sample.csv")

2. Utilisez la fonction [head](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html) pour afficher les 10 premières lignes de votre jeu de données `df`.

In [3]:
df.head(10)

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
6,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
8,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
9,8.9,Fight Club,R,Drama,139,"[u'Brad Pitt', u'Edward Norton', u'Helena Bonh..."

3. Utilisez la fonction [tail](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html) pour afficher les 5 dernières lignes de votre jeu de données `df`.

In [4]:
df.tail(5)

,star_rating,title,content_rating,genre,duration,actors_list
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

4. Quel est le nombre d'observations et de variables dans ce jeu de données (c'est-à-dire le nombre de lignes et colonnes). Vous pouvez utiliser l'attribut `shape`

In [5]:
print(f"ligne : {df.shape[0]}, col : {df.shape[1]}")

ligne : 979, col : 6

5. Donnez la liste des colonnes qui composent votre jeu de données en utilisant l'attribut `columns`. Renseignez vous ensuite sur le type `Index` de pandas.

In [25]:
for column in df.columns:
    print(column)

note
title
content_rating
genre
duration
note_over_20

Index(['note', 'title', 'content_rating', 'genre', 'duration', 'note_over_20'], dtype='object')

6. Renommez la colonne `star_rating` en `note` (allez voir la documentation de la fonction [rename](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html)).

In [7]:
df = df.rename(columns={"star_rating": "note"})

for column in df.columns:
    print(column)

note
title
content_rating
genre
duration
actors_list

7. La colonne `actors_list` ne nous servira pas pour ce TP. Utilisez la fonction [drop](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html) pour la supprimer.

In [27]:
df = df.drop(columns=['actors_list'])

for column in df.columns:
    print(column)

KeyError: "['actors_list'] not found in axis"

8. Afficher le type de chaque variable/colonne en utilisant l'attribut `dtypes`. Comment interprétez vous le résultat ?

In [9]:

df.dtypes

note              float64
title              object
content_rating     object
genre              object
duration            int64
dtype: object

## Trier le jeu données

9. Affichez le jeu de données trié par note croissante (voir la fonction [sort_values](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html)).

In [10]:
df = df.sort_values(by='note', ascending=False)
df.head(10)

,note,title,content_rating,genre,duration
0,9.3,The Shawshank Redemption,R,Crime,142
1,9.2,The Godfather,R,Crime,175
2,9.1,The Godfather: Part II,R,Crime,200
3,9.0,The Dark Knight,PG-13,Action,152
4,8.9,Pulp Fiction,R,Crime,154
5,8.9,12 Angry Men,NOT RATED,Drama,96
6,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201
8,8.9,Schindler's List,R,Biography,195
9,8.9,Fight Club,R,Drama,139

10. Affichez le jeu de données trié par note décroissante.

In [11]:
df = df.sort_values(by='note', ascending=False)
df.head(10)

,note,title,content_rating,genre,duration
0,9.3,The Shawshank Redemption,R,Crime,142
1,9.2,The Godfather,R,Crime,175
2,9.1,The Godfather: Part II,R,Crime,200
3,9.0,The Dark Knight,PG-13,Action,152
4,8.9,Pulp Fiction,R,Crime,154
5,8.9,12 Angry Men,NOT RATED,Drama,96
6,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201
8,8.9,Schindler's List,R,Biography,195
9,8.9,Fight Club,R,Drama,139

11. Affichez le jeu de données trié par note croissante puis par durée croissante en cas d'égalité.

In [12]:
df = df.sort_values(by=['note', 'duration'], ascending=[False, False])
df.head(10)

,note,title,content_rating,genre,duration
0,9.3,The Shawshank Redemption,R,Crime,142
1,9.2,The Godfather,R,Crime,175
2,9.1,The Godfather: Part II,R,Crime,200
3,9.0,The Dark Knight,PG-13,Action,152
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201
8,8.9,Schindler's List,R,Biography,195
6,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161
4,8.9,Pulp Fiction,R,Crime,154
9,8.9,Fight Club,R,Drama,139
5,8.9,12 Angry Men,NOT RATED,Drama,96

## Travailler avec les colonnes

12. Retournez le contenu de la colonne `title` (utilisez la notation à base de crochets).

In [13]:
df.head(10)['title']

0                         The Shawshank Redemption
1                                    The Godfather
2                           The Godfather: Part II
3                                  The Dark Knight
7    The Lord of the Rings: The Return of the King
8                                 Schindler's List
6                   The Good, the Bad and the Ugly
4                                     Pulp Fiction
9                                       Fight Club
5                                     12 Angry Men
Name: title, dtype: object

13. Appliquez les fonctions `min`, `max`, `mean` sur la colonne `note` pour récupérer la note minimale, moyenne et maxime pour les films du jeu de données.

In [14]:
df['note'].min()

np.float64(7.4)

In [15]:
df['note'].max()

np.float64(9.3)

In [16]:
df['note'].mean()

np.float64(7.889785495403474)

14. Créez votre propre fonction `min_max_mean` retournant la valeur minimale, maximale et moyenne d'une liste numérique.

In [17]:
def min_max_mean(arr: list) -> (float, float, float):
    return (arr.min(), arr.max(), arr.mean())

15. Appliquez votre fonction sur la colonne `note` du jeu de données et comparez votre résultat à celui de la question 13.

In [18]:
print(min_max_mean(df['note']))

(np.float64(7.4), np.float64(9.3), np.float64(7.889785495403474))

16. Créez une nouvelle colonne `note_over_20` qui correspond à la note passée à une échelle sur 20 (actuellement sur une échelle de 10). Puis affichez les 5 premières lignes du jeu de données.

In [28]:
def mult2(x):
    return 2*x

df['note_over_20'] = df['note']*2

df.head(10)

,note,title,content_rating,genre,duration,note_over_20
0,9.3,The Shawshank Redemption,R,Crime,142,18.6
1,9.2,The Godfather,R,Crime,175,18.4
2,9.1,The Godfather: Part II,R,Crime,200,18.2
3,9.0,The Dark Knight,PG-13,Action,152,18.0
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,17.8
8,8.9,Schindler's List,R,Biography,195,17.8
6,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161,17.8
4,8.9,Pulp Fiction,R,Crime,154,17.8
9,8.9,Fight Club,R,Drama,139,17.8
5,8.9,12 Angry Men,NOT RATED,Drama,96,17.8

17. Explorez la page de documentation de la fonction `value_counts` puis utiliser cette fonction sur la colonne `genre`. Faites une synthèse du résultat affiché.

In [20]:
df['genre'].value_counts()

genre
Drama        278
Comedy       156
Action       136
Crime        124
Biography     77
Adventure     75
Animation     62
Horror        29
Mystery       16
Western        9
Sci-Fi         5
Thriller       5
Film-Noir      3
Family         2
History        1
Fantasy        1
Name: count, dtype: int64

18. Ecrivez votre propre fonction `value_counts` permettant de compter le nombre d'éléments dans une liste.

In [21]:
def value_counts(arr: list)-> dict:
    for el in arr:

19. Appliquez votre fonction `value_countz` sur la colonne `genre` et comparez votre résultat avec celui de la question 17.

In [22]:
value_counts(df['genre'])

genre
Drama        278
Comedy       156
Action       136
Crime        124
Biography     77
Adventure     75
Animation     62
Horror        29
Mystery       16
Western        9
Sci-Fi         5
Thriller       5
Film-Noir      3
Family         2
History        1
Fantasy        1
Name: count, dtype: int64

20. Utilisez la méthode `describe` pour afficher un certain nombre d'indications statistiques sur une variable numérique. Vous pouvez l'appliquer sur la colonne `note` par exemple.

In [23]:
df['note'].describe()

count    979.000000
mean       7.889785
std        0.336069
min        7.400000
25%        7.600000
50%        7.800000
75%        8.100000
max        9.300000
Name: note, dtype: float64

## Filtrer la donnée

21. Créer une liste `mask` ayant la même taille que le nombre de lignes dans le jeu données (question 4). Cette liste de booélens alternera les valeurs `True` et `False`

In [ ]:
df['mask'] =

22. Executez le bloc d'instruction suivant. Qu'observez-vous ?

In [24]:
df[mask].shape

NameError: name 'mask' is not defined

23. Mettez à jour la liste `mask` pour commencer par 3 fois `True` et mettre à `False` toutes les autres valeurs.

24. Executez le bloc d'instruction suivant. Qu'observez-vous ?

In [ ]:
df[mask]

25. Créez un mask qui vaut `True` pour les films de plus de 2h30 et `False` sinon. Utilisez ensuite ce filtre pour afficher tous les films de plus de 2h30.

26. Trouvez l'instruction en une seule ligne permettant de voir tous les films de genre `Crime`.

27. Combien de films de genre `Crime` sont présents dans le jeu données ?

28. Filtre multiconditions. En pandas, utilisez **`&`** et **`|`** pour respectivement réaliser des conjonctions (**`and`**) et disjonctions (**`or`**). L'utilisation de parenthèses est nécessaire pour encadrer chaque condition.

Afficher la liste des films de genre `Crime` et de moins de 2h.

29. Afficher la liste des films de genre Crime et Drama de plus de 3h.