# Eat Safe, Love

## Notebook Set Up

In [42]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint

In [43]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [44]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [45]:
# review the collections in our database
db.list_collection_names()

['establishments']

In [46]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [47]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': 20}
# Use count_documents to display the number of documents in the result
establishments.count_documents(query)
# Display the first document in the results using pprint
pprint(establishments.find_one(query))

{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0.0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('648aa7b942fca62f46054a9b'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [49]:
# Convert the result to a Pandas DataFrame
import pandas as pd
# Display the number of rows in the DataFrame
establishments_df = pd.DataFrame(list(establishments.find()))
# Display the first 10 rows of the DataFrame
establishments_df.head(10)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,648aa7b742fca62f46052f69,1043695.0,0.0,PI/000073616,The Pavilion,Restaurant/Cafe/Canteen,1,East Cliff Pavilion,Wear Bay Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.195625, 'latitude': 51.083812}",,4591.765489,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,648aa7b742fca62f46052f6a,647177.0,0.0,PI/000041489,Wear Bay Bowls Club,Pub/bar/nightclub,7843,Wear Bay Road,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.196408, 'latitude': 51.086058}",,4591.821311,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,648aa7b742fca62f46052f6b,289353.0,0.0,PI/000002468,St Marys COE (aided) Primary School,School/college/university,7845,St Marys Church Of England Primary School,Warren Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 1.194762, 'latitude': 51.085797}",,4591.871474,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,648aa7b742fca62f46052f6e,289352.0,0.0,PI/000002460,The Ship,Pub/bar/nightclub,7843,23 The Stade,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.188537, 'latitude': 51.08084}",,4591.912145,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,648aa7b742fca62f46052f6f,289560.0,0.0,PI/000039927,Mariner,Pub/bar/nightclub,7843,16 The Stade,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.188537, 'latitude': 51.08084}",,4591.912145,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
5,648aa7b742fca62f46052f70,987206.0,0.0,PI/000075655,The Ships Galley,Pub/bar/nightclub,7843,The Ship,23 The Stade,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 1.188537, 'latitude': 51.08084}",,4591.912145,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
6,648aa7b742fca62f46052f71,344689.0,0.0,PI/000002095,Folkestone Trawlers Shop,Retailers - other,4613,1 The Stade,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.188537, 'latitude': 51.08084}",,4591.912145,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
7,648aa7b742fca62f46052f72,894592.0,0.0,PI/000074396,Docker,Retailers - other,4613,Folkestone Harbour,Harbour Approach Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 1.18590330311705, 'latitude': 51...",,4591.914705,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
8,648aa7b742fca62f46052f73,1043701.0,0.0,PI/000076360,Pick Up Pintxos,Takeaway/sandwich shop,7844,Folkestone Harbour,Harbour Approach Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.18590330311705, 'latitude': 51...",,4591.914705,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
9,648aa7b742fca62f46052f74,805702.0,0.0,PI/000073219,Dr Legumes - Harbour Arm,Restaurant/Cafe/Canteen,1,Folkestone Harbour,Harbour Approach Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 10, 'ConfidenceIn...",FHRS,"{'longitude': 1.18590330311705, 'latitude': 51...",,4591.914705,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [53]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query2 = {'LocalAuthorityName': {'$regex': 'London'},
          'RatingValue': {'$gte': 4}}

# Use count_documents to display the number of documents in the result
count2 = establishments.count_documents(query2)
print(count2)
# Display the first document in the results using pprint
pprint(establishments.find_one(query2))

33
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4.0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('648aa7ba42fca62f460564b6'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [56]:
# Convert the result to a Pandas DataFrame
establishments_df2 = pd.DataFrame(establishments.find(query2))
# Display the number of rows in the DataFrame
len(establishments_df2)
# Display the first 10 rows of the DataFrame
establishments_df2.head(10)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,648aa7ba42fca62f460564b6,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...",FHRS,"{'longitude': 0.508551, 'latitude': 51.369321}",,4627.439468,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,648aa7bb42fca62f460567dc,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.249255999922752, 'latitude': 5...",,4627.873179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
2,648aa7bb42fca62f46057329,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.561954, 'latitude': 51.543831}",,4631.968418,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
3,648aa7bc42fca62f46058129,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.346336990594864, 'latitude': 5...",,4636.846754,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
4,648aa7bc42fca62f4605812a,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.346325, 'latitude': 51.464078}",,4636.847650,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
5,648aa7bc42fca62f46058832,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.287555, 'latitude': 51.504071}",,4640.460834,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
6,648aa7be42fca62f4605a940,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.069286, 'latitude': 51.501121}",,4648.301822,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
7,648aa7bf42fca62f4605ad07,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.048006, 'latitude': 51.503733}",,4649.173485,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,648aa7bf42fca62f4605ad21,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.047966, 'latitude': 51.504112}",,4649.188826,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,648aa7bf42fca62f4605ad22,294606,0,PI/000016185,WH Smith,Retailers - other,4613,London City Airport,Silvertown London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0479655750095844, 'latitude': ...",,4649.188850,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [58]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.490142
longitude = 0.08384

query3 = {'RatingValue': 5, 
         'geocode.latitude': {'$lte': 51.500142, '$gte': 51.480142},
         'geocode.longitude': {'$lte': 0.09384, '$gte': 0.07384}}
sort = [('scores.Hygiene', 1)]



# Print the results
for result in db.establishments.find(query3).sort(sort).limit(5):
    print(result)

{'_id': ObjectId('648aa7be42fca62f4605a2fa'), 'FHRSID': 694609, 'ChangesByServerID': 0, 'LocalAuthorityBusinessID': 'PI/000116619', 'BusinessName': 'Volunteer', 'BusinessType': 'Pub/bar/nightclub', 'BusinessTypeID': 7843, 'AddressLine1': '130 - 132 Plumstead High Street', 'AddressLine2': '', 'AddressLine3': 'Plumstead', 'AddressLine4': 'Greenwich', 'PostCode': 'SE18 1JQ', 'Phone': '', 'RatingValue': 5.0, 'RatingKey': 'fhrs_5_en-gb', 'RatingDate': '2019-08-05T00:00:00', 'LocalAuthorityCode': '511', 'LocalAuthorityName': 'Greenwich', 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk', 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk', 'scores': {'Hygiene': 0, 'Structural': 0, 'ConfidenceInManagement': 0}, 'SchemeType': 'FHRS', 'geocode': {'longitude': 0.09208, 'latitude': 51.4873437}, 'RightToReply': '', 'Distance': 4646.965634598608, 'NewRatingPending': False, 'meta': {'dataSource': None, 'extractDate': '0001-01-01T00:00:00', 'itemCount': 0, 'returncode': None, 'totalCount': 0, 'totalPages': 0, 'pageSize': 0, 'pageNumber': 0}, 'links': [{'rel': 'self', 'href': 'http://api.ratings.food.gov.uk/establishments/694609'}]}
{'_id': ObjectId('648aa7be42fca62f4605a312'), 'FHRSID': 695241, 'ChangesByServerID': 0, 'LocalAuthorityBusinessID': 'PI/000179088', 'BusinessName': 'Plumstead Manor Nursery', 'BusinessType': 'Caring Premises', 'BusinessTypeID': 5, 'AddressLine1': 'Plumstead Manor School Old Mill Road', 'AddressLine2': '', 'AddressLine3': 'Plumstead', 'AddressLine4': 'Greenwich', 'PostCode': 'SE18 1QG', 'Phone': '', 'RatingValue': 5.0, 'RatingKey': 'fhrs_5_en-gb', 'RatingDate': '2021-06-16T00:00:00', 'LocalAuthorityCode': '511', 'LocalAuthorityName': 'Greenwich', 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk', 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk', 'scores': {'Hygiene': 0, 'Structural': 0, 'ConfidenceInManagement': 5}, 'SchemeType': 'FHRS', 'geocode': {'longitude': 0.0859939977526665, 'latitude': 51.481517791748}, 'RightToReply': '', 'Distance': 4646.9740101340385, 'NewRatingPending': False, 'meta': {'dataSource': None, 'extractDate': '0001-01-01T00:00:00', 'itemCount': 0, 'returncode': None, 'totalCount': 0, 'totalPages': 0, 'pageSize': 0, 'pageNumber': 0}, 'links': [{'rel': 'self', 'href': 'http://api.ratings.food.gov.uk/establishments/695241'}]}
{'_id': ObjectId('648aa7be42fca62f4605a315'), 'FHRSID': 694478, 'ChangesByServerID': 0, 'LocalAuthorityBusinessID': 'PI/000086506', 'BusinessName': 'Atlantic Fish Bar', 'BusinessType': 'Takeaway/sandwich shop', 'BusinessTypeID': 7844, 'AddressLine1': '35 Lakedale Road', 'AddressLine2': '', 'AddressLine3': 'Plumstead', 'AddressLine4': 'Greenwich', 'PostCode': 'SE18 1PR', 'Phone': '', 'RatingValue': 5.0, 'RatingKey': 'fhrs_5_en-gb', 'RatingDate': '2021-06-16T00:00:00', 'LocalAuthorityCode': '511', 'LocalAuthorityName': 'Greenwich', 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk', 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk', 'scores': {'Hygiene': 0, 'Structural': 0, 'ConfidenceInManagement': 5}, 'SchemeType': 'FHRS', 'geocode': {'longitude': 0.0912164, 'latitude': 51.4867296}, 'RightToReply': '', 'Distance': 4646.974611855838, 'NewRatingPending': False, 'meta': {'dataSource': None, 'extractDate': '0001-01-01T00:00:00', 'itemCount': 0, 'returncode': None, 'totalCount': 0, 'totalPages': 0, 'pageSize': 0, 'pageNumber': 0}, 'links': [{'rel': 'self', 'href': 'http://api.ratings.food.gov.uk/establishments/694478'}]}
{'_id': ObjectId('648aa7be42fca62f4605a2cd'), 'FHRSID': 695223, 'ChangesByServerID': 0, 'LocalAuthorityBusinessID': 'PI/000178842', 'BusinessName': 'Iceland', 'BusinessType': 'Retailers - supermarkets/hypermarkets', 'BusinessTypeID': 7840, 'AddressLine1': '144 - 146 Plumstead High Street', 'AddressLine2': '', 'AddressLine3': 'Plumstead', 'AddressLine4': 'Greenwich', 'PostCode': 'SE18 1JQ', 'Phone': '', 'RatingValue': 5.0, 'RatingKey': 'fhrs_5_en-gb', 'RatingDate': '2019-11-13T00:00:00', 'LocalAuthorityCode': '511', 'LocalAuthorityName': 'Greenwich', 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk', 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk', 'scores': {'Hygiene': 0, 'Structural': 5, 'ConfidenceInManagement': 5}, 'SchemeType': 'FHRS', 'geocode': {'longitude': 0.0924199968576431, 'latitude': 51.4871482849121}, 'RightToReply': '', 'Distance': 4646.946071297699, 'NewRatingPending': False, 'meta': {'dataSource': None, 'extractDate': '0001-01-01T00:00:00', 'itemCount': 0, 'returncode': None, 'totalCount': 0, 'totalPages': 0, 'pageSize': 0, 'pageNumber': 0}, 'links': [{'rel': 'self', 'href': 'http://api.ratings.food.gov.uk/establishments/695223'}]}
{'_id': ObjectId('648aa7be42fca62f4605a2dd'), 'FHRSID': 1380578, 'ChangesByServerID': 0, 'LocalAuthorityBusinessID': '14425', 'BusinessName': 'Howe and Co Fish and Chips - Van 17', 'BusinessType': 'Mobile caterer', 'BusinessTypeID': 7846, 'AddressLine1': 'Restaurant And Premises 107A Plumstead High Street', 'AddressLine2': '', 'AddressLine3': 'Plumstead', 'AddressLine4': 'Greenwich', 'PostCode': 'SE18 1SE', 'Phone': '', 'RatingValue': 5.0, 'RatingKey': 'fhrs_5_en-gb', 'RatingDate': '2021-11-11T00:00:00', 'LocalAuthorityCode': '511', 'LocalAuthorityName': 'Greenwich', 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk', 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk', 'scores': {'Hygiene': 0, 'Structural': 0, 'ConfidenceInManagement': 0}, 'SchemeType': 'FHRS', 'geocode': {'longitude': 0.0925370007753372, 'latitude': 51.4875335693359}, 'RightToReply': '', 'Distance': 4646.95593107927, 'NewRatingPending': False, 'meta': {'dataSource': None, 'extractDate': '0001-01-01T00:00:00', 'itemCount': 0, 'returncode': None, 'totalCount': 0, 'totalPages': 0, 'pageSize': 0, 'pageNumber': 0}, 'links': [{'rel': 'self', 'href': 'http://api.ratings.food.gov.uk/establishments/1380578'}]}

In [59]:
# Convert result to Pandas DataFrame
import pandas as pd
# Display the number of rows in the DataFrame
establishments_df3 = pd.DataFrame(list(establishments.find()))
# Display the first 10 rows of the DataFrame
establishments_df3.head(10)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,648aa7b742fca62f46052f69,1043695.0,0.0,PI/000073616,The Pavilion,Restaurant/Cafe/Canteen,1,East Cliff Pavilion,Wear Bay Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.195625, 'latitude': 51.083812}",,4591.765489,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,648aa7b742fca62f46052f6a,647177.0,0.0,PI/000041489,Wear Bay Bowls Club,Pub/bar/nightclub,7843,Wear Bay Road,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.196408, 'latitude': 51.086058}",,4591.821311,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,648aa7b742fca62f46052f6b,289353.0,0.0,PI/000002468,St Marys COE (aided) Primary School,School/college/university,7845,St Marys Church Of England Primary School,Warren Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 1.194762, 'latitude': 51.085797}",,4591.871474,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,648aa7b742fca62f46052f6e,289352.0,0.0,PI/000002460,The Ship,Pub/bar/nightclub,7843,23 The Stade,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.188537, 'latitude': 51.08084}",,4591.912145,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,648aa7b742fca62f46052f6f,289560.0,0.0,PI/000039927,Mariner,Pub/bar/nightclub,7843,16 The Stade,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.188537, 'latitude': 51.08084}",,4591.912145,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
5,648aa7b742fca62f46052f70,987206.0,0.0,PI/000075655,The Ships Galley,Pub/bar/nightclub,7843,The Ship,23 The Stade,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 1.188537, 'latitude': 51.08084}",,4591.912145,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
6,648aa7b742fca62f46052f71,344689.0,0.0,PI/000002095,Folkestone Trawlers Shop,Retailers - other,4613,1 The Stade,Folkestone,Kent,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.188537, 'latitude': 51.08084}",,4591.912145,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
7,648aa7b742fca62f46052f72,894592.0,0.0,PI/000074396,Docker,Retailers - other,4613,Folkestone Harbour,Harbour Approach Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 1.18590330311705, 'latitude': 51...",,4591.914705,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
8,648aa7b742fca62f46052f73,1043701.0,0.0,PI/000076360,Pick Up Pintxos,Takeaway/sandwich shop,7844,Folkestone Harbour,Harbour Approach Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 1.18590330311705, 'latitude': 51...",,4591.914705,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
9,648aa7b742fca62f46052f74,805702.0,0.0,PI/000073219,Dr Legumes - Harbour Arm,Restaurant/Cafe/Canteen,1,Folkestone Harbour,Harbour Approach Road,Folkestone,...,http://www.folkestone-hythe.gov.uk,foodteam@folkestone-hythe.gov.uk,"{'Hygiene': 0, 'Structural': 10, 'ConfidenceIn...",FHRS,"{'longitude': 1.18590330311705, 'latitude': 51...",,4591.914705,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [71]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match = {'$match': {'scores.Hygiene': 0}}
# 2. Groups the matches by Local Authority
group = {'$group': {'_id': '$LocalAuthorityName', 'count': {'$sum': 1}}}
# 3. Sorts the matches from highest to lowest
sort = {'$sort': {'count': -1}}
# Print the number of documents in the result
pipeline = [match, group, sort]
result = list(establishments.aggregate(pipeline))
print(len(result))
# Print the first 10 results
pprint(result[:10])

55
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [72]:
# Convert the result to a Pandas DataFrame
establishments_df4 = pd.DataFrame(list(establishments.aggregate(pipeline)))
# Display the number of rows in the DataFrame
print(len(establishments_df4))
# Display the first 10 rows of the DataFrame
establishments_df4.head(10)

55

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542