<a href="https://colab.research.google.com/github/CabellPasco/CabellPasco/blob/main/Copy_of_pandas1_student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas DataFrames I


### Programming for Data Science
---  

### PREREQUISITES
- variables
- data types
- operators
- list comprehensions (not essential)
- numpy arrays (not essential)


### SOURCES
- ten minutes to pandas  
https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html


- sort_values()  
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html


- value_counts()  
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html


- to_csv() : saving to CSV file  
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html


- read_csv() : load CSV file into DataFrame  
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html


- dropna() : drop missing data  
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html


- fillna() : impute missing data  
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html




### OBJECTIVES
- Introduce pandas dataframes and the essential operations

# Pandas DataFrames

The **Series**: a 1-dimensional labeled array capable of holding any data type.

The **DataFrame**: a 2-dimensional labeled data structure with columns of potentially different types.

> Note: Pandas used to have a 3-dimensional structure called a **panel**, but it has been removed from the library.\
Ironically, the name "pandas" was partly derived the word "panel": $pan(el)-da(ta)-s$.\
To handle higher dimensional data, the Pandas team suggests using [XArray](https://xarray.pydata.org/en/stable/), which also build on NumPy arrays.

By far, the most important data structure in Pandas is the dataframe, with the series playing a supporting role.

In fact, dataframe objects are built out of series objects.

So, **to understand what a dataframe is and how it behaves, you need to understand what is series is and how it is constructed.**

Before going into that, here are two quick observations about dataframes:

First, dataframes are **inspired by the R structure** of the same name. They have many similarities, but there are fundamental differences between the two that go beyond mere language differences. Most important is the Pandas dataframes have **indexes**, whereas R dataframes do not.

Second, it is helpful to think of Pandas as wrapper around NumPy and Matplotlib that makes it much easier to perform common operations, like select data by column name or visualizing plots. But this comes at a cost -- Pandas is slower than NumPy. The represents the classic trade-off between **ease-of-use** for humans and machine **performance**.

For shorthand, `df` will refer to pandas DataFrames.  

DataFrames can be created with pandas.    
Various formats (`csv`,`json`,...) can be loaded into DataFrames.   

The [ten minutes to pandas link](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html) above gives a good, brief overview of pandas. Be sure to review.

Import pandas like this, where the alias `pd` is convention:

In [2]:
import pandas as pd

# Series Objects

## Axis Labels (Indexes)

A series is at heart a one-dimensional array with **labels** along its axis.
* Its data must be of a single type, like NumPy arrays (which they are internally).
* Think of a series as being oriented *vertically*.

The axis labels are collectively referred to as the **index**.

Think of **the index as a separate data structure** that is attached to the array.
* The array holds the data.
* The index holds the names of the observations or things that the data are about.

Why have an index?
* Provides a way to access elements of the array by name
* Allows series objects that share index labels to be combined

In fact, **a dataframe is a collection of series** with a common index.

To this collection of series the dataframe adds a set of labels along the horizontal axis.
* The index is **axis 0**
* The columns are labeled by a different set of labels along **axis 1**

Note that both index and column labels can be **multidimensional**.
* The are called Hierarchical Indexes and go the technical name of `MultiIndexes`.
* As an example, consider that a table of text data might have a two-column index: `(book_id, chap_id)`
* See [the Pandas documentation](https://pandas.pydata.org/docs/user_guide/advanced.html).

It is **crucial** to understand the difference between the index of a dataframe and its data in order to understand how dataframes work.

Many a headache is caused by not understanding this difference :-)

**Indexes are powerful and controversial.**
* They allow for all kinds of magic to take place when combining and accessing data.
* But they are expensive and sometimes hard to work with (especially multiindexes).
* They are especially difficult if you are coming from R and expecting dataframes to behave a certain way.

## A visual

<img src="https://pynative.com/wp-content/uploads/2021/02/dataframe.png" width="50%" height="100%"/>

# DataFrames Constructors

Several ways to create pandas dataframes

**Passing a dictionary of objects:**

In [19]:
# x, y, z, are lists in the dict

df = pd.DataFrame({
    'x': [0, 2, 1, 5],  #each of these is a COLUMN in the data frame, must ALL BE SAME LENGTH
    'y': [1, 1, 0, 0],
    'z': [True, False, False, False]
})

In [6]:
df

   x  y      z
0  0  1   True
1  2  1  False
2  1  0  False
3  5  0  False

**`.index`**  
https://pandas.pydata.org/docs/reference/api/pandas.Index.html

In [7]:
df.index

RangeIndex(start=0, stop=4, step=1)

You can change the index by assigning a list of values:

In [8]:
df.index = ['first','second','third','fourth']

In [9]:
df

        x  y      z
first   0  1   True
second  2  1  False
third   1  0  False
fourth  5  0  False

**`list()`**  
casts object to list  
here will give you the df index as a list

In [10]:
list(df.index)

['first', 'second', 'third', 'fourth']

**`.columns`**  
gives you the column labels

In [22]:
df.columns #gives you column names, can be MADE INTO LIST and modified from there

Index(['x', 'y', 'z'], dtype='object')

In [21]:
# can also cast as a list (from above)
list(df.columns)

['x', 'y', 'z']

**`.values`**  
gives a Numpy representation of the dataframe (more on numpy later)  
can also use `.to_numpy()`

In [20]:
df.values #given in rows instead of columnsm - hard to keep track, numpy array of lists

array([[0, 1, True],
       [2, 1, False],
       [1, 0, False],
       [5, 0, False]], dtype=object)

In [14]:
type(df.values)

numpy.ndarray

**Passing the three required pieces:**
- columns as list
- index as list
- data as list of lists

In [15]:
df2 = pd.DataFrame(
    columns=['x','y'],
    index=['row1','row2','row3'],
    data=[[9,3],[1,2],[4,6]])

In [16]:
df2

      x  y
row1  9  3
row2  1  2
row3  4  6

**Passing a nested list (or list-like):**

In [17]:
my_data = [
    ('a', 1, True),
    ('b', 2, False)
]
df3 = pd.DataFrame(my_data, columns=['f1', 'f2', 'f3'])

In [23]:
df3

  f1  f2     f3
0  a   1   True
1  b   2  False

# Naming indexes

In [24]:
df3.index.name = 'obs_id'

In [25]:
df3

       f1  f2     f3
obs_id
0       a   1   True
1       b   2  False

# Copying DataFrames with `copy()`

Use `copy()` to give the new df a clean break from the original.  

Otherwise, the copied df will point to the same object as the original.

In [26]:
df = pd.DataFrame({'x':[0,2,1,5], 'y':[1,1,0,0], 'z':[True,False,False,False]})

In [27]:
df_deep    = df.copy()  # deep copy; changes to df will not pass through
df_shallow = df         # shallow copy; changes to df will pass through

In [29]:
print('--df')
print(df)

# update values in df.x - df.x accesses the "x" column
df.x = 1

print('--Updated df')
print(df)
print('--df_shallow')
print(df_shallow)
print('--df_deep')
print(df_deep)

# rebuild df
df = pd.DataFrame({'x':[0,2,1,5], 'y':[1,1,0,0], 'z':[True,False,False,False]})

--df
   x  y      z
0  0  1   True
1  2  1  False
2  1  0  False
3  5  0  False
--Updated df
   x  y      z
0  1  1   True
1  1  1  False
2  1  0  False
3  1  0  False
--df_shallow
   x  y      z
0  1  1   True
1  1  1  False
2  1  0  False
3  1  0  False
--df_deep
   x  y      z
0  0  1   True
1  2  1  False
2  1  0  False
3  5  0  False

Notice `df_shallow` mirrors changes to `df`, since it references its indices and data.  
`df_deep` does not reference `df`, and so changes `to` df do not impact `df_deep`.

# Column Data Types

**`With `.types`**

In [30]:
df.dtypes

x    int64
y    int64
z     bool
dtype: object

**With `.info()`**

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x       4 non-null      int64
 1   y       4 non-null      int64
 2   z       4 non-null      bool
dtypes: bool(1), int64(2)
memory usage: 196.0 bytes

**Column Renaming with `.rename()`**

Can rename one or more fields at once using a dict.  

Rename the field `z` to `is_label`:

In [32]:
df = df.rename(columns={'z': 'is_label'})

In [33]:
df

   x  y  is_label
0  0  1      True
1  2  1     False
2  1  0     False
3  5  0     False

# Column Referencing

Use bracket notation or dot notation.  
- bracket notation: variable name must be a string

**Bracket**

In [34]:
df['y']

0    1
1    1
2    0
3    0
Name: y, dtype: int64

**Dot** (i.e. as object attribute)

In [35]:
df.y

0    1
1    1
2    0
3    0
Name: y, dtype: int64

Dot notation is very convenient, since as object attributes they can be tab-completed in various editing environments.

But:
- It only works if the column names are not reserved words
- It can't be used when created a new column (see below)

Column attributes and methods work with both:
 - example: `.values`

In [36]:
df.y.values, df['y'].values

(array([1, 1, 0, 0]), array([1, 1, 0, 0]))

show only the first value, by indexing:

In [37]:
df.y.values[0]

1

# Column Selection

You select columns from a dataframe by passing a value or list (or any expression that evaluates to a list).

In [38]:
# single bracket
df['x']

0    0
1    2
2    1
3    5
Name: x, dtype: int64

In [39]:
# double bracket
df[['x']]

   x
0  0
1  2
2  1
3  5

In [40]:
df[['y', 'x']]

   y  x
0  1  0
1  1  2
2  0  1
3  0  5

### TRY FOR YOURSELF (UNGRADED EXERCISES)

1) Create a dataframe called `dat` by passing a dictionary of inputs. Here are the requirements:
- has a column named `features` containing floats
- has a column named `labels` containing integers 0, 1, 2  

Print the df.

In [44]:
dat = pd.DataFrame({
    'features': [1.1, 2.2, 3.3],
    'labels': [0, 1, 2],
})
dat

   features  labels
0       1.1       0
1       2.2       1
2       3.3       2

2) Rename the `labels` column in `dat` to `label`.  
[Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html)

In [46]:
dat = dat.rename(columns={'labels': 'label'})
dat

   features  label
0       1.1      0
1       2.2      1
2       3.3      2

# Adding New Columns

It is typical to create a new column from existing columns.  

In this example, a new column (or field) is created by summing `x` and `y`:

In [47]:
df['x_plus_y'] = df.x + df.y

In [48]:
df

   x  y  is_label  x_plus_y
0  0  1      True         1
1  2  1     False         3
2  1  0     False         1
3  5  0     False         5

Notice the components:

- the left side has form: DataFrame name, bracket notation, new column name
- the assignment operator `=` is used
- the right side contains an expression; here, two df columns are summed

Bracket notation also works on the fields, but it's more typing:

In [49]:
df['x_plus_y'] = df['x'] + df['y']
df

   x  y  is_label  x_plus_y
0  0  1      True         1
1  2  1     False         3
2  1  0     False         1
3  5  0     False         5

The bracket notation must be used when assigning to a new column. This will break:

In [52]:
df['x_plus_y'] = df.x + df.y

# Removing Columns with `del` and `.drop()`

## `del`

`del` can drop a DataFrame or single columns from the frame

In [ ]:
df_drop = df.copy()

In [ ]:
df_drop.head(2)

In [ ]:
# delete the column 'x'
del df_drop['x']

In [ ]:
df_drop

## `.drop()`

Can drop one or more columns.

takes `axis` parameter:
- axis=0 refers to rows  
- axis=1 refers to columns

In [ ]:
df_drop = df_drop.drop(['x_plus_y', 'is_label'], axis=1)

In [ ]:
df_drop