<a href="https://colab.research.google.com/github/Chalhotra/Hands-on-ML/blob/main/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import urllib.request
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
URL = "https://raw.githubusercontent.com/codebasics/py/refs/heads/master/ML/5_one_hot_encoding/Exercise/carprices.csv"
def fetch_and_load_data(URL):
    urllib.request.urlretrieve(URL, "carprices.csv")
    df = pd.read_csv("carprices.csv")
    return df
df = fetch_and_load_data(URL)
print(df)

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [67]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dfle = le.fit_transform(df['Car Model'])
dfle

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2])

In [68]:
df['Car Model']= dfle

In [69]:
df

    Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [70]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
car_cats= df[['Car Model', 'Mileage', 'Age(yrs)']]
y = df[['Sell Price($)']]

car_cats

    Car Model  Mileage  Age(yrs)
0           1    69000         6
1           1    35000         3
2           1    57000         5
3           1    22500         2
4           1    46000         4
5           0    59000         5
6           0    52000         5
7           0    72000         6
8           0    91000         8
9           2    67000         6
10          2    83000         7
11          2    79000         7
12          2    59000         5

In [71]:
fitted = ohe.fit_transform(car_cats[['Car Model']])

fitted= fitted.toarray()

In [72]:
fitted

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [73]:
encoded_df = pd.DataFrame(fitted, columns=ohe.get_feature_names_out(['Car Model']), index=car_cats.index)

In [74]:
encoded_df

    Car Model_0  Car Model_1  Car Model_2
0           0.0          1.0          0.0
1           0.0          1.0          0.0
2           0.0          1.0          0.0
3           0.0          1.0          0.0
4           0.0          1.0          0.0
5           1.0          0.0          0.0
6           1.0          0.0          0.0
7           1.0          0.0          0.0
8           1.0          0.0          0.0
9           0.0          0.0          1.0
10          0.0          0.0          1.0
11          0.0          0.0          1.0
12          0.0          0.0          1.0

In [76]:
df

    Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [78]:
cols = pd.concat([df, encoded_df], axis="columns")

In [79]:
cols

,Car Model,Mileage,Sell Price($),Age(yrs),Car Model_0,Car Model_1,Car Model_2
0,1,69000,18000,6,0.0,1.0,0.0
1,1,35000,34000,3,0.0,1.0,0.0
2,1,57000,26100,5,0.0,1.0,0.0
3,1,22500,40000,2,0.0,1.0,0.0
4,1,46000,31500,4,0.0,1.0,0.0
5,0,59000,29400,5,1.0,0.0,0.0
6,0,52000,32000,5,1.0,0.0,0.0
7,0,72000,19300,6,1.0,0.0,0.0
8,0,91000,12000,8,1.0,0.0,0.0
9,2,67000,22000,6,0.0,0.0,1.0
10,2,83000,20000,7,0.0,0.0,1.0
11,2,79000,21000,7,0.0,0.0,1.0
12,2,59000,33000,5,0.0,0.0,1.0

In [80]:
df= cols.drop(['Sell Price($)', 'Car Model_2', 'Car Model'], axis=1)

In [81]:
df

    Mileage  Age(yrs)  Car Model_0  Car Model_1
0     69000         6          0.0          1.0
1     35000         3          0.0          1.0
2     57000         5          0.0          1.0
3     22500         2          0.0          1.0
4     46000         4          0.0          1.0
5     59000         5          1.0          0.0
6     52000         5          1.0          0.0
7     72000         6          1.0          0.0
8     91000         8          1.0          0.0
9     67000         6          0.0          0.0
10    83000         7          0.0          0.0
11    79000         7          0.0          0.0
12    59000         5          0.0          0.0

In [82]:
from sklearn.linear_model import LinearRegression
lin_reg= LinearRegression()

lin_reg.fit(df, cols[['Sell Price($)']])

LinearRegression()

In [84]:
# lin_reg.predict([])
lin_reg.score(df, cols[['Sell Price($)']])

0.9417050937281082

In [86]:
lin_reg.predict([[45000,4,0,0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[36991.31721061]])

In [88]:
lin_reg.predict([[86000,7,0,1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[11080.74313219]])