In [54]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
from nltk.probability import FreqDist
from nltk.stem import PorterStemmer
import csv
import pandas as pd

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nasii\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [89]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [56]:
df = pd.read_csv('place_i.tsv', sep='\t')

In [57]:
df.head()

,placeName,placeTags,numPeopleVisited,numPeopleWant,placeDesc,placeShortDesc,placeNearby,placeAddress,placeAlt,placeLong,placeEditors,placePubDate,placeRelatedLists,placeRelatedPlaces,placeURL
0,45th Parallel Marker,"['location markers', 'marvelous maps and meas...",207,430,"Along Highway 41 between Oconto and Peshtigo,...",Almost half-way between the Equator and North...,"['Chateau Hutter', 'Peshtigo Fire Museum', 'W...","Peshtigo, Wisconsin, 54157 United States",44.9989,-87.8535,none,2010-03-15 00:00:00,"['Peshtigo Fire Museum', 'Chateau Hutter', 'W...",none,https://www.atlasobscura.com/places/45th-para...
1,Bise Village,"['villages', 'flora', 'roads', 'roadside attr...",67,429,Respect the local’s privacy as they go about ...,A network of sandy streets lined with verdant...,"['Okinawa Churaumi Aquarium', 'Izena Island',...",639-26 Bise Motobu Japan,26.7090,127.8800,none,2017-11-17 00:00:00,"['Okinawa Churaumi Aquarium', 'Izena Island',...",none,https://www.atlasobscura.com/places/bise-village
2,Carillon Berlin-Tiergarten,"['towers', 'music]",337,430,There are live concerts every Sunday at 3 p.m...,One of the world's heaviest musical instrumen...,"['Soviet Graffiti in the Reichstag', 'Memoria...",John-Foster-Dulles-Allee Berlin Germany,52.5177,13.3670,none,2018-08-06 00:00:00,"['Soviet Graffiti in the Reichstag', 'Memoria...",none,https://www.atlasobscura.com/places/carillon-...
3,Coney Island Mermaid Parade,"['mermaids', 'parades', 'tradition', 'festiva...",269,430,Check the parade's website for information on...,The famed amusement district marks the beginn...,"['Childs Restaurant Building', 'Coney Art Wal...","West 21st Street and Surf Avenue Brooklyn, Ne...",40.5746,-73.9876,none,2019-06-04 00:00:00,"['Childs Restaurant Building', 'Coney Art Wal...",none,https://www.atlasobscura.com/places/coney-isl...
4,Glasgow City Chambers' Staircase,"['marble', 'stairs', 'government', 'architect...",168,430,The City Chambers is a functioning government...,The ornate structure is part of a building bo...,['Unmarked Grave of Pierre Emile L'Angelier '...,"45 John St Glasgow, Scotland, G1 1LY United K...",55.8609,-4.2483,none,2019-10-01 00:00:00,"['Unmarked Grave of Pierre Emile L'Angelier',...",none,https://www.atlasobscura.com/places/glasgow-c...

In [58]:
df.columns

Index(['placeName ', ' placeTags ', ' numPeopleVisited ', ' numPeopleWant ',
       ' placeDesc ', ' placeShortDesc ', ' placeNearby ', ' placeAddress ',
       ' placeAlt ', ' placeLong ', ' placeEditors ', ' placePubDate ',
       ' placeRelatedLists ', ' placeRelatedPlaces ', ' placeURL'],
      dtype='object')

In [59]:
placeName = df['placeName '].isna().any()
placeDesc = df[' placeDesc '].isna().any()

In [60]:
print(placeName)
print(placeDesc)

False
False

In [61]:
df['placeName ']              = df['placeName '].astype(str).str.lower()
df[' placeDesc ']             = df[' placeDesc '].astype(str).str.lower()
df[' placeURL']               = df[' placeURL'].astype(str).str.lower()  
df.head(3)

,placeName,placeTags,numPeopleVisited,numPeopleWant,placeDesc,placeShortDesc,placeNearby,placeAddress,placeAlt,placeLong,placeEditors,placePubDate,placeRelatedLists,placeRelatedPlaces,placeURL
0,45th parallel marker,"['location markers', 'marvelous maps and meas...",207,430,"along highway 41 between oconto and peshtigo,...",Almost half-way between the Equator and North...,"['Chateau Hutter', 'Peshtigo Fire Museum', 'W...","Peshtigo, Wisconsin, 54157 United States",44.9989,-87.8535,none,2010-03-15 00:00:00,"['Peshtigo Fire Museum', 'Chateau Hutter', 'W...",none,https://www.atlasobscura.com/places/45th-para...
1,bise village,"['villages', 'flora', 'roads', 'roadside attr...",67,429,respect the local’s privacy as they go about ...,A network of sandy streets lined with verdant...,"['Okinawa Churaumi Aquarium', 'Izena Island',...",639-26 Bise Motobu Japan,26.7090,127.8800,none,2017-11-17 00:00:00,"['Okinawa Churaumi Aquarium', 'Izena Island',...",none,https://www.atlasobscura.com/places/bise-village
2,carillon berlin-tiergarten,"['towers', 'music]",337,430,there are live concerts every sunday at 3 p.m...,One of the world's heaviest musical instrumen...,"['Soviet Graffiti in the Reichstag', 'Memoria...",John-Foster-Dulles-Allee Berlin Germany,52.5177,13.3670,none,2018-08-06 00:00:00,"['Soviet Graffiti in the Reichstag', 'Memoria...",none,https://www.atlasobscura.com/places/carillon-...

In [62]:
regexp = RegexpTokenizer('\w+')
df['placeName ']           = df['placeName '].apply(regexp.tokenize)
df[' placeDesc ']          = df[' placeDesc '].apply(regexp.tokenize)
df.head(3)

,placeName,placeTags,numPeopleVisited,numPeopleWant,placeDesc,placeShortDesc,placeNearby,placeAddress,placeAlt,placeLong,placeEditors,placePubDate,placeRelatedLists,placeRelatedPlaces,placeURL
0,"[45th, parallel, marker]","['location markers', 'marvelous maps and meas...",207,430,"[along, highway, 41, between, oconto, and, pes...",Almost half-way between the Equator and North...,"['Chateau Hutter', 'Peshtigo Fire Museum', 'W...","Peshtigo, Wisconsin, 54157 United States",44.9989,-87.8535,none,2010-03-15 00:00:00,"['Peshtigo Fire Museum', 'Chateau Hutter', 'W...",none,https://www.atlasobscura.com/places/45th-para...
1,"[bise, village]","['villages', 'flora', 'roads', 'roadside attr...",67,429,"[respect, the, local, s, privacy, as, they, go...",A network of sandy streets lined with verdant...,"['Okinawa Churaumi Aquarium', 'Izena Island',...",639-26 Bise Motobu Japan,26.7090,127.8800,none,2017-11-17 00:00:00,"['Okinawa Churaumi Aquarium', 'Izena Island',...",none,https://www.atlasobscura.com/places/bise-village
2,"[carillon, berlin, tiergarten]","['towers', 'music]",337,430,"[there, are, live, concerts, every, sunday, at...",One of the world's heaviest musical instrumen...,"['Soviet Graffiti in the Reichstag', 'Memoria...",John-Foster-Dulles-Allee Berlin Germany,52.5177,13.3670,none,2018-08-06 00:00:00,"['Soviet Graffiti in the Reichstag', 'Memoria...",none,https://www.atlasobscura.com/places/carillon-...

In [63]:
# Make a list of english stopwords
stopwords = nltk.corpus.stopwords.words("english")

In [64]:
df['placeName ']           = df['placeName '].apply(lambda x: [item for item in x if item not in stopwords])
df[' placeDesc ']          = df[' placeDesc '].apply(lambda x: [item for item in x if item not in stopwords])
df.head(3)

,placeName,placeTags,numPeopleVisited,numPeopleWant,placeDesc,placeShortDesc,placeNearby,placeAddress,placeAlt,placeLong,placeEditors,placePubDate,placeRelatedLists,placeRelatedPlaces,placeURL
0,"[45th, parallel, marker]","['location markers', 'marvelous maps and meas...",207,430,"[along, highway, 41, oconto, peshtigo, wiscons...",Almost half-way between the Equator and North...,"['Chateau Hutter', 'Peshtigo Fire Museum', 'W...","Peshtigo, Wisconsin, 54157 United States",44.9989,-87.8535,none,2010-03-15 00:00:00,"['Peshtigo Fire Museum', 'Chateau Hutter', 'W...",none,https://www.atlasobscura.com/places/45th-para...
1,"[bise, village]","['villages', 'flora', 'roads', 'roadside attr...",67,429,"[respect, local, privacy, go, daily, life, pla...",A network of sandy streets lined with verdant...,"['Okinawa Churaumi Aquarium', 'Izena Island',...",639-26 Bise Motobu Japan,26.7090,127.8800,none,2017-11-17 00:00:00,"['Okinawa Churaumi Aquarium', 'Izena Island',...",none,https://www.atlasobscura.com/places/bise-village
2,"[carillon, berlin, tiergarten]","['towers', 'music]",337,430,"[live, concerts, every, sunday, 3, p, may, sep...",One of the world's heaviest musical instrumen...,"['Soviet Graffiti in the Reichstag', 'Memoria...",John-Foster-Dulles-Allee Berlin Germany,52.5177,13.3670,none,2018-08-06 00:00:00,"['Soviet Graffiti in the Reichstag', 'Memoria...",none,https://www.atlasobscura.com/places/carillon-...

In [66]:
#keep only words which are longer than 2 letters and join the tokenized string
df['placeName_new ']           = df['placeName '].apply(lambda x: ' '.join([item for item in x if len(item)>2]))
df[' placeDesc_new ']          = df[' placeDesc '].apply(lambda x: ' '.join([item for item in x if len(item)>2]))

In [67]:
df[['placeName ','placeName_new ',' placeDesc ',' placeDesc_new ',' placeURL']].head()

,placeName,placeName_new,placeDesc,placeDesc_new,placeURL
0,"[45th, parallel, marker]",45th parallel marker,"[along, highway, 41, oconto, peshtigo, wiscons...",along highway oconto peshtigo wisconsin look h...,https://www.atlasobscura.com/places/45th-para...
1,"[bise, village]",bise village,"[respect, local, privacy, go, daily, life, pla...",respect local privacy daily life places okinaw...,https://www.atlasobscura.com/places/bise-village
2,"[carillon, berlin, tiergarten]",carillon berlin tiergarten,"[live, concerts, every, sunday, 3, p, may, sep...",live concerts every sunday may september featu...,https://www.atlasobscura.com/places/carillon-...
3,"[coney, island, mermaid, parade]",coney island mermaid parade,"[check, parade, website, information, year, da...",check parade website information year date reg...,https://www.atlasobscura.com/places/coney-isl...
4,"[glasgow, city, chambers, staircase]",glasgow city chambers staircase,"[city, chambers, functioning, governmental, bu...",city chambers functioning governmental buildin...,https://www.atlasobscura.com/places/glasgow-c...

In [69]:
#create list of all words in these columns
all_name   = ' '.join([word for word in df['placeName_new ']])
all_desc   = ' '.join([word for word in df[' placeDesc_new ']])

In [51]:
#all_name

In [70]:
all_desc

'along highway oconto peshtigo wisconsin look historical sign marker might miss respect local privacy daily life places okinawa best accessed car live concerts every sunday may september featuring blend popular music classic works typical carillon music check website changes schedule special holiday performances automated music plays daily noon check parade website information year date register since streets closed parade best take public transportation take train stillwell avenue city chambers functioning governmental building inform security information desk interested viewing staircases two sets staircase either side access though free limited able roam around leisure take photos examine display cases containing various objects pertaining building history gain entry upper levels suggested take one tours offered free minute tour twice day monday friday tours filled first come first served basis fit groups people tours located main entrance located george square side building free pamphlets available give history building visit exit 101 soto ave north rancho drive turn right old trapper lodge statues left past horses red barn parking lot note pierce college whose land statues reside trying evict statues historical landmark campus result statues fenced able visited although one peek rips fencing material get small glimpse raeford fayetteville hwy 401 cahuachi ceremonial center nazca river valley town name many tours available various tour companies actually nice places discover linkeroever side scheldt keep river right follow trail half mile toward small beach called sint annastrand might even lose grimness summery days also hilarious cinema located old quarter augustine models located entryway mathematics building university arizona campus lamp burns day night striking effect visit dark pop nearby savoy hotel check little museum features photos old liquors 1969 thank note neil armstrong nasa stationery thanking staff sending champagne cocktail glasses toast moon landing tours church currently available 2nd 4th fridays worship services person online via church facebook page sunday accessibility questions prior visit please contact church office 615 254 7584 email info dpchurch com abandoned village open public bridge entrance chained location longer open public may reopen future check heading publicly visible bit old treasury shelter tunnel opening dry moat catch glimpse fence line pennsylvania avenue lat long marks spot want purchase frozen pie volunteer sell one parish house drop weekday business hours mass sundays midway currently artists compound rooms rent overnight long term stays expect show see murals completely closed public week one text hotel directly 310 827 1748 weekend stays gets fully booked october plan going around halloween perfect time visit place plan ahead book room advance every halloween midway throws massive halloween event open public called draculacon ball easily walked central shopping district located praça figueira square easily accessed busses 12e 15e 208 714 736 737 760 short walk metro rossio lark hill place accessed salford museum free enter museum occasionally changes street temporarily represent eras history located lexington ice center sports complex take lexington turn right man war right beaver creek right eureka springs drive seasonal museum open weekends april november seven days week may october want visit outside seasonal hours give call make special arrangements admission park free wary many steep cliffs visiting small children spot east head north butte see lady time distance big bring binoculars plan see roadside plus lit night well worth wait june october scheduled tours directly site including lady chapel wall women monument get close private vehicles permitted taking tour bus traveling gift shop butte plaza mall 3100 harrison ave round trip takes two half hours weather permitting make reservations call 406 782 1221 check website admission fees details currently open public however congressional staffer including interns take guests staff heard bathtubs uncertain location prepared crazy looks ask take senate bathtubs ampelparchen seen pedestrian crossings throughout vienna city center check hours visiting bring camera visit gallery purchase tickets museum saw mill river parkway north take exit executive boulevard make left turn onto broadway grounds left admission esperanto museum also includes admission globe museum world largest collection globes upper level building town paradise follow whitefish point north miles free museum open tuesday friday saturdays architect james dakin designed prominent gothic style building reason must visit see gorgeous dome charge tour building use audio guide even children room minions spare per person worth see immersive theatrical presentation located east side laurel canyon blvd south chandler look plain white office car rear end window open monday friday free admission closest metro drassanes also include wine tasting visit column farm offers tours restaurant plenty delicious options including raspberry cream parfait made moose feta cheese best places view caves city caves attraction broadmarsh centre brewhouse yard tours mortimer hole conducted throughout year virtual cave fly throughs available nottingham caves survey website island near hostel riverside drive bridge walkway island must use non powered watercraft get swimming lake illegal many kayak sup canoe rentals lady bird lake writing closest epicsup rentals signs california highway earlimart direct park minutes earlimart sculpture storage right restored original artist metro latour maubourg varenne invalides francois xavier right stavropoleos lipscani streets good place start explore styx valley field national park office one hour drive hobart via new norfolk check website open hours make appointment kid friendly fair vermont border new york miles west rutland miles south burlington allen house directly across center village green park place adams house southern end corner park place adams street 257 stroudsmoor stroudsburg 18360 accessible car madrid according vermont quarries corporation tours danby quarry available public tours might available special circumstances case try contacting website site part alcatel lucent research lab specified address antenna top hill accessible road going hill typically open general work hours site open year round access inside buildings winter trail mile easy walking starts miles north grand lake entrance rocky mountain national park visitors museum worth noting 2nd 3rd floors wheelchair accessible admission per person families six members open mid april october hours thurs 10am 4pm friday 10am 4pm sat 10am sun 10am september museum hosts pow wow proves great place family picnics guided tours better access available two boat services hour train ride berlin easy take ice regional trains get also option taking bus flixbus located mile south warm springs highway head main doors near neighboring basilica staircase right take museum charge five euros houston memorial park easily reached taking interstate south 1764 fm1764 lowry expressway main road texas city park reached making left 29th street bayview may reach park directly taking 146 southbound 197 loop 25th avenue memorial park closes 7pm mid way along glen osmond road minutes drive adelaide hills city near bar wooden staircase leads second floor dining room prefer get meal walk bicycle north bike path mile burlington boathouse foot main street come lakeview cemetery right see steep footpath following edge ravine right follow footpath top bluff continue another 100 yards past open field left located falmouth jamaica north shore island minutes east montego bay minutes west ocho rios enter bronx community college gates hall fame terrace college offers free tours sure call best time visit summer fall warned town may resembled muddy mess wet seasons north 34th street 250 feet east intersection fremont avenue north fremont section seattle site located slopes mushera musherabeg mountain outside millstreet country park eleven kilometers millstreet county cork follow signs millstreet toward millstreet country park past park entrance turn right 300 meters road entrance site left ali buried section cemetery follow green path directly grave take city bus marked las momias ask bus driver point street leads museum walk uphill see big stone wall without windows straight museum turn right follow wall end see lot souvenir stands turn left walk find ticket window want visit cemetery first turn big stone wall instead walk uphill little see entrance right graveyard worth look like kind thing cannot get museum cemetery must walk around side museum actually underneath graveyard take short tour trip part general tour city enough time appreciate ghastly cadavers instead make sure least hour two walk around cave open april september weekends bank holidays tours must booked online admission free exhibit open please call ahead 731 855 2013 large groups outhouse located town 575 south north pere marquette rail trail located approximately miles south entrance belgrade crow visible left side highway 4442 0091 members annual dues give access programming anyone free visit library paid parking available nearby parking garages street attend silent film screening authentic classic movie experience mighty wurlitzer pipe organ providing musical accompaniment walk statue time though aware crowds tend gather around shiny toe advised rub statue causes damage wear sure take peek behind statue get glimpse sandy stoddart depiction greek god helios illustrating concept enlightenment head surrounded nest snakes representing anti intellectualism view reproduction paintings listen pre recorded tour need pay front desk staff per person depending timing could wait conference room could use consider calling ahead pull curtain free live entertainment weekends kids get free firehat nys thruway exit route 219 route 219 south end approx miles left miles right onto continuation 219 south approx miles 219 ashford hollow speed limit right onto ahrens road carsons ashford house park sign corner stay straight approx miles county road mill valley turn left miles park entrance left two distinct sections park directions main site plaques information admission fees trail maps site mill valley closer ashton hollow smaller parking lot bathrooms port potties take photos trail maps consult trail website set trail maps posted sparingly names many sculptors also shared sparingly bring water long climbs hot days closes year 31st october gps coordinates lead train station upon arriving fairhaven may park near amtrak station walk main part town along harris avenue may park 12th harris walk toward amtrak station markers ground sure keep eye short walk ōsaki station yamanote rinkai lines less mile gotanda station asakusa yamanote tokyu ikegami lines less mile takanawa dai station asakusa line locate spot google maps searching museum package culture free entry open monday friday nine mile run trail south braddock avenue regent square neighborhood pittsburgh turn west hutchinson street north lancaster avenue follow road parking lot park walk past soccer field trail accessible canal street station plum brook station located eight miles sandusky ohio station typically open public although open house events run past allowing visitors tour various facilities potential visits would arranged contacting glenn research center plum brook directly public transit take district line central london reach richmond park station walk outside get bus 371 pedestrian gate found petersham stop best get near stags autumn months breeding season sometimes behave aggressively toward people better idea watch stags clash antlers distance binoculars check website evening special performances concerts always free sundays rain shine plane fly girona barcelona perpignan ap7 motorway barcelona jonquera take girona north exit towards palamós village bordils take road pera púbol nacional road take barcelona france towards palamós drive figueres turn right parlavà drive reach road turn right towards girona driving turn left follow road pera púbol train take renfe train line barcelona portbou stop flaçà station flaçà púbol away bus take sarfa regular line stopping flaçà pera free car park entrance púbol village traveling site please treat respect dignity site great spiritual import resting place many native people well final resting place many people coming downtown boulder want take pearl street becomes pearl parkway follow road make right koa lake follow valmont road bend mill bend road located rise center blois cemeteries remain publicly accessible despite runways dedicated access road leads hart cemetery sullivan road small signs indicate location entrance sites illinois exit 3rd turn right broadway riverpark drive left front street left onto trendley avenue parking lot left three miles south east kidderminster a450 museum second floor chamberlin hall university wisconsin madison building admission free hours monday friday museum open physics department also classes session celebratory experience head nisshodo mochiya march girls day japanese holiday widely celebrated hawaiʻi girls mark occasion arranging doll collections eating special diamond shaped tri colored mochi called hishi mochi beware however according hawai magazine sweet popular preorders plentiful girls day may hishi mochi left tower directly one flight paths msp international airport hill close high among best spots view coming planes road 2km llanallgo a5025 private residence easily view house street would like take closer look steve gladly show work set appointment writing steve hartbauer 1415 syracuse denver 80220 contact info residential street parking hard get around alaska probably need guide boat helicopter help get close wild bears matter color see schedule events find information tickets online aware research places china many gps coordinated mentioned editors wrong sad see lack research adding locations edit 2021 new member brodheadsville halfway allentown wilke barre western pocono community library pilgrim way 115 rte 209 gallery inside library opens every day 9am mondays wednesdays thursdays open 8pm tuesdays fridays 5pm saturdays 4pm closed sundays major holidays minute drive bodø short walk along shoreline viewed road visitors allowed property open 60th anniversary november 2017 located minutes ferry terminal bainbridge highly recommend taking car unless experienced biker skinny house located east side gladys avenue immediately north 7th street rose park neighborhood long beach mile gentle uphill hike golf cart shuttle taken entrance base sky trail gondola trees mystery open every day due precarious nature wink sinks people officially allowed visit close people nonetheless various cuts visible surrounding fences empty beer cans often spotted vicinity advisable however trespassers arrested least problems happen visit whole thing collapses biking moon hill yangshuo county popular western street cycle along head towards main road hotel path lead large weir cross river small path take fen lou village jin bao river cross river take concrete road turning right meets main road bike min moon hill takes minutes scenic taking two villages located north end beach subway line stop pauli bus 112 stop hamburgmuseum take bus runs end cosme velho rodoviaria continue walk hill right couple blocks come large intimidating tunnel gone far stretcher railing society campaigns promotion protection preservation london stretcher railings found website twitter society website provides map stretcher railing locations map coordinates point tabard gardens estate one example railings found location three minute walk away hanky place railings also visits arranged appointment nas open weekdays closed weekends holidays entrance fee photo required entrances located 2101 constitution ave 2100 closest metro station foggy bottom come check cafeteria cheap eats downstairs favorite among state department employees work nearby sound museum captures info also stop maritime underground railroad historical markers area follow work done harriet jacobs also quaker group helped free 600 slaves also garden open daily dawn dusk admission free little britain far pauls cathedral tower open visitors climb due condition free parking available harris hill ski jump parking lot cedar street cross cedar street enter hiking trails cemetery trail retreat tower trailhead reservations made website order sky bars store website although due high demand quantities shipment currently limited shop closed mondays take highway strong road pass strong cemetery turn right onto edgewater road tree visible road twenty minutes bowling green kentucky one hour outside nashville tennessee dumbarton easy reach train bus glasgow sometimes castle closed due adverse weather conditions check website visiting ensure open entrance fee must climb stairs reach castle really suitable anyone mobility issues connects fisgard pandora ave government store park one visitor lots campus walk installation take underground either museumsquartier volktheather station accessible also bus car use feet walking west street passage leads interesting stiftgasse district walk mariahilfer strasse main shopping street coordinates perfectly hexagonal square center town piazza grande also several 16th century fortress buildings around city worth seeing three monumental gates allowed entrance city porta udine porta cividale porta aquileia stop tourist office information first weekend september year city puts historical reenactment beginning war ottoman habsburg wars 1615 actual location accessible via paved roads powder hill dinosaur park small site size large backyard easily seen half hour park located along powder hill south long hill adjacent gravel road leads dinosaur less powder ridge mountain park resort today hike woods around bluff available everyone though bluffs rock formations steep easily climbed viewed base bluff prophet rock road stone marker placed site 1929 general lafayette chapter trails meander woods sign posts provide direction historical information stick trails take directly prophet rock visits require tour guide least knowledgeable taxi driver round trip local guide costs including price entry tower joan arc tour jeanne arc also known donjon rouen dungeon rouen easy find due large size prominent location train station museum arts best view tower street although museum tower also worth visiting despite overshadowed unfortunate escape room game tower interior closed season reopen spring 2019 also fine museum city dedicated memory history joan arc addition wilbur collection museum also hosts art shows traveling exhibitions throughout year check calendar see currently display bernardo waterfowl area part ladd gordon waterfowl complex located miles south albuquerque new mexico interstate take exit 175 turn left 116 miles area right open public daily one half hour sunrise one half hour sunset admission fee waterfowl present mid november mid february best arrive sunrise head one blinds around pond see birds blasting fields temperatures early morning typically teens lower dress accordingly nowata northeast oklahoma miles northeast tulsa center town head north 169 mile turn right heading east onto e021 road past intersection n4150 road look bowling ball lane left farnams encourage passersby photograph examine mosaics 131 grand rapids take leonard street exit drive east leonard front avenue turn right south continue end street turn left east parking lot next fish ladder see kilns briefly drive past rock creek parkway want get closer easiest access intersects 26th dead ends directly behind kilns musée grevin10 boulevard montmartre75009 parisnote street montmartre neighborhood opéra area far galeties lafayette 3rd ave side building northwest corner 3rd 65th prior first phase restoration million job aimed se

In [71]:
#Tokenize all_words
nltk.download('punkt')
tokenized_name = nltk.tokenize.word_tokenize(all_name)
tokenized_desc = nltk.tokenize.word_tokenize(all_desc)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\nasii\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [72]:
#Create a frequency distribution which records the number of times each word has occurred:
name_list = FreqDist(tokenized_name)
desc_list = FreqDist(tokenized_desc)

In [73]:
name_list

FreqDist({'museum': 17, 'park': 11, 'island': 6, 'house': 5, 'rock': 5, 'city': 4, 'hill': 4, 'monument': 4, 'historic': 4, 'tower': 4, ...})

In [74]:
desc_list

FreqDist({'take': 46, 'road': 45, 'open': 40, 'park': 38, 'street': 36, 'right': 35, 'walk': 31, 'located': 30, 'free': 29, 'parking': 28, ...})

In [22]:
type(name_list)

nltk.probability.FreqDist

In [75]:
ps = PorterStemmer()
  
# choose some words to be stemmed
#words = ["program", "programs", "programmer", "programming", "programmers"]
  
for w in desc_list:
    print(w, " : ", ps.stem(w))

take  :  take
road  :  road
open  :  open
park  :  park
street  :  street
right  :  right
walk  :  walk
located  :  locat
free  :  free
parking  :  park
miles  :  mile
museum  :  museum
station  :  station
turn  :  turn
left  :  left
get  :  get
also  :  also
north  :  north
one  :  one
available  :  avail
see  :  see
south  :  south
visit  :  visit
follow  :  follow
site  :  site
bus  :  bu
entrance  :  entranc
may  :  may
city  :  citi
side  :  side
tours  :  tour
trail  :  trail
place  :  place
check  :  check
lot  :  lot
hours  :  hour
website  :  websit
drive  :  drive
admission  :  admiss
public  :  public
tour  :  tour
main  :  main
center  :  center
river  :  river
town  :  town
mile  :  mile
accessible  :  access
along  :  along
best  :  best
building  :  build
around  :  around
east  :  east
area  :  area
closed  :  close
small  :  small
hill  :  hill
end  :  end
look  :  look
car  :  car
train  :  train
avenue  :  avenu
access  :  access
day  :  day
exit  :  exit
easily  :  easili
near  :  near
minutes  :  minut
visitors  :  visitor
church  :  church
location  :  locat
house  :  hous
directly  :  directli
way  :  way
find  :  find
friday  :  friday
first  :  first
people  :  peopl
line  :  line
time  :  time
head  :  head
hour  :  hour
easy  :  easi
cemetery  :  cemeteri
highway  :  highway
every  :  everi
sunday  :  sunday
year  :  year
two  :  two
minute  :  minut
ave  :  ave
past  :  past
many  :  mani
long  :  long
metro  :  metro
make  :  make
visiting  :  visit
use  :  use
view  :  view
west  :  west
stop  :  stop
tower  :  tower
hike  :  hike
sign  :  sign
information  :  inform
old  :  old
valley  :  valley
keep  :  keep
little  :  littl
village  :  villag
want  :  want
advance  :  advanc
children  :  children
worth  :  worth
close  :  close
signs  :  sign
mid  :  mid
sure  :  sure
fee  :  fee
trailhead  :  trailhead
places  :  place
though  :  though
various  :  variou
monday  :  monday
square  :  squar
toward  :  toward
hotel  :  hotel
currently  :  current
online  :  onlin
october  :  octob
ahead  :  ahead
enter  :  enter
call  :  call
bring  :  bring
taking  :  take
takes  :  take
however  :  howev
mill  :  mill
onto  :  onto
must  :  must
closest  :  closest
cave  :  cave
island  :  island
lake  :  lake
new  :  new
appointment  :  appoint
work  :  work
inside  :  insid
reached  :  reach
reach  :  reach
path  :  path
another  :  anoth
large  :  larg
route  :  rout
maps  :  map
due  :  due
scenic  :  scenic
far  :  far
visitor  :  visitor
rock  :  rock
historical  :  histor
daily  :  daili
september  :  septemb
special  :  special
either  :  either
limited  :  limit
history  :  histori
statues  :  statu
half  :  half
beach  :  beach
nearby  :  nearbi
please  :  pleas
fence  :  fenc
room  :  room
district  :  district
short  :  short
november  :  novemb
outside  :  outsid
well  :  well
including  :  includ
wall  :  wall
weather  :  weather
good  :  good
across  :  across
green  :  green
corner  :  corner
part  :  part
walking  :  walk
10am  :  10am
great  :  great
boat  :  boat
leads  :  lead
kilometers  :  kilomet
stone  :  stone
library  :  librari
closer  :  closer
water  :  water
coordinates  :  coordin
away  :  away
three  :  three
high  :  high
allowed  :  allow
climb  :  climb
taxi  :  taxi
next  :  next
buses  :  buse
back  :  back
might  :  might
accessed  :  access
popular  :  popular
viewing  :  view
able  :  abl
photos  :  photo
entry  :  entri
come  :  come
note  :  note
although  :  although
called  :  call
even  :  even
person  :  person
via  :  via
contact  :  contact
office  :  offic
visible  :  visibl
tunnel  :  tunnel
spot  :  spot
purchase  :  purchas
going  :  go
halloween  :  halloween
central  :  central
weekends  :  weekend
april  :  april
steep  :  steep
private  :  privat
permitted  :  permit
round  :  round
trip  :  trip
ask  :  ask
seen  :  seen
throughout  :  throughout
tickets  :  ticket
point  :  point
guide  :  guid
canyon  :  canyon
national  :  nation
research  :  research
typically  :  typic
grand  :  grand
mountain  :  mountain
3rd  :  3rd
4pm  :  4pm
bike  :  bike
feet  :  feet
millstreet  :  millstreet
county  :  counti
grave  :  grave
uphill  :  uphil
straight  :  straight
holidays  :  holiday
anyone  :  anyon
statue  :  statu
need  :  need
pay  :  pay
front  :  front
depending  :  depend
219  :  219
lead  :  lead
nine  :  nine
events  :  event
gate  :  gate
found  :  found
barcelona  :  barcelona
towards  :  toward
púbol  :  púbol
runs  :  run
ski  :  ski
cedar  :  cedar
trails  :  trail
store  :  store
pass  :  pass
roads  :  road
resort  :  resort
northeast  :  northeast
permit  :  permit
paz  :  paz
nearest  :  nearest
summit  :  summit
fountain  :  fountain
abbey  :  abbey
scavenger  :  scaveng
hunt  :  hunt
marker  :  marker
miss  :  miss
respect  :  respect
local  :  local
music  :  music
changes  :  chang
staircase  :  staircas
filled  :  fill
give  :  give
college  :  colleg
campus  :  campu
glimpse  :  glimps
actually  :  actual
days  :  day
university  :  univers
night  :  night
staff  :  staff
moon  :  moon
2nd  :  2nd
prior  :  prior
info  :  info
com  :  com
bridge  :  bridg
heading  :  head
bit  :  bit
business  :  busi
sundays  :  sunday
rooms  :  room
week  :  week
weekend  :  weekend
booked  :  book
plan  :  plan
book  :  book
ice  :  ice
seasonal  :  season
lady  :  ladi
big  :  big
wait  :  wait
vehicles  :  vehicl
traveling  :  travel
shop  :  shop
reservations  :  reserv
pedestrian  :  pedestrian
gallery  :  galleri
parkway  :  parkway
collection  :  collect
saturdays  :  saturday
per  :  per
window  :  window
farm  :  farm
made  :  made
caves  :  cave
start  :  start
field  :  field
general  :  gener
guided  :  guid
better  :  better
ride  :  ride
interstate  :  interst
bluff  :  bluff
continue  :  continu
yards  :  yard
hall  :  hall
34th  :  34th
driver  :  driver
ticket  :  ticket
instead  :  instead
least  :  least
paid  :  paid
experience  :  experi
aware  :  awar
advised  :  advis
wear  :  wear
behind  :  behind
thruway  :  thruway
approx  :  approx
set  :  set
gps  :  gp
harris  :  harri
markers  :  marker
lines  :  line
less  :  less
google  :  googl
run  :  run
neighborhood  :  neighborhood
canal  :  canal
visits  :  visit
arranged  :  arrang
season  :  season
sometimes  :  sometim
watch  :  watch
girona  :  girona
pera  :  pera
flaçà  :  flaçà
girls  :  girl
mochi  :  mochi
paths  :  path
mondays  :  monday
property  :  properti
shuttle  :  shuttl
nature  :  natur
often  :  often
cross  :  cross
couple  :  coupl
gone  :  gone
stretcher  :  stretcher
railings  :  rail
gardens  :  garden
state  :  state
underground  :  underground
dawn  :  dawn
dusk  :  dusk
castle  :  castl
suitable  :  suitabl
several  :  sever
porta  :  porta
powder  :  powder
size  :  size
woods  :  wood
costs  :  cost
arc  :  arc
interior  :  interior
art  :  art
waterfowl  :  waterfowl
arrive  :  arriv
early  :  earli
levee  :  leve
vehicle  :  vehicl
quite  :  quit
recommended  :  recommend
bellagio  :  bellagio
stops  :  stop
spaces  :  space
lad  :  lad
phrao  :  phrao
alternatively  :  altern
usually  :  usual
savota  :  savota
wanxianshan  :  wanxianshan
shoes  :  shoe
sek  :  sek
wisconsin  :  wisconsin
live  :  live
concerts  :  concert
classic  :  classic
schedule  :  schedul
holiday  :  holiday
performances  :  perform
parade  :  parad
since  :  sinc
streets  :  street
desk  :  desk
interested  :  interest
examine  :  examin
display  :  display
containing  :  contain
objects  :  object
pertaining  :  pertain
gain  :  gain
upper  :  upper
groups  :  group
red  :  red
land  :  land
visited  :  visit
peek  :  peek
companies  :  compani
dark  :  dark
fridays  :  friday
services  :  servic
email  :  email
longer  :  longer
reopen  :  reopen
publicly  :  publicli
lat  :  lat
midway  :  midway
overnight  :  overnight
stays  :  stay
show  :  show
massive  :  massiv
ball  :  ball
shopping  :  shop
occasionally  :  occasion
lexington  :  lexington
complex  :  complex
war  :  war
creek  :  creek
springs  :  spring
cliffs  :  cliff
butte  :  butt
distance  :  distanc
binoculars  :  binocular
june  :  june
monument  :  monument
fees  :  fee
bathtubs  :  bathtub
prepared  :  prepar
camera  :  camera
saw  :  saw
boulevard  :  boulevard
broadway  :  broadway
grounds  :  ground
world  :  world
tuesday  :  tuesday
prominent  :  promin
charge  :  charg
audio  :  audio
blvd  :  blvd
white  :  white
include  :  includ
offers  :  offer
restaurant  :  restaur
plenty  :  plenti
cream  :  cream
centre  :  centr
yard  :  yard
fly  :  fli
walkway  :  walkway
swimming  :  swim
illegal  :  illeg
kayak  :  kayak
rentals  :  rental
writing  :  write
earlimart  :  earlimart
direct  :  direct
original  :  origin
vermont  :  vermont
border  :  border
burlington  :  burlington
adams  :  adam
southern  :  southern
according  :  accord
try  :  tri
contacting  :  contact
address  :  address
antenna  :  antenna
top  :  top
buildings  :  build
starts  :  start
wheelchair  :  wheelchair
six  :  six
members  :  member
hosts  :  host
regional  :  region
memorial  :  memori
texas  :  texa
closes  :  close
glen  :  glen
second  :  second
floor  :  floor
footpath  :  footpath
following  :  follow
shore  :  shore
community  :  commun
gates  :  gate
summer  :  summer
wet  :  wet
intersection  :  intersect
fremont  :  fremont
section  :  section
country  :  countri
buried  :  buri
graveyard  :  graveyard
like  :  like
thing  :  thing
855  :  855
rail  :  rail
approximately  :  approxim
paintings  :  paint
could  :  could
ashford  :  ashford
hollow  :  hollow
limit  :  limit
stay  :  stay
directions  :  direct
smaller  :  smaller
sparingly  :  sparingli
hot  :  hot
31st  :  31st
upon  :  upon
amtrak  :  amtrak
ground  :  ground
yamanote  :  yamanot
asakusa  :  asakusa
plum  :  plum
brook  :  brook
eight  :  eight
would  :  would
london  :  london
stags  :  stag
months  :  month
idea  :  idea
always  :  alway
palamós  :  palamó
driving  :  drive
resting  :  rest
coming  :  come
downtown  :  downtown
pearl  :  pearl
bend  :  bend
remain  :  remain
despite  :  despit
dedicated  :  dedic
sites  :  site
department  :  depart
march  :  march
hishi  :  hishi
among  :  among
2km  :  2km
steve  :  steve
probably  :  probabl
locations  :  locat
halfway  :  halfway
western  :  western
thursdays  :  thursday
tuesdays  :  tuesday
5pm  :  5pm
major  :  major
viewed  :  view
ferry  :  ferri
terminal  :  termin
recommend  :  recommend
immediately  :  immedi
7th  :  7th
base  :  base
sky  :  sky
cycle  :  cycl
blocks  :  block
railing  :  rail
society  :  societi
map  :  map
required  :  requir
group  :  group
garden  :  garden
cathedral  :  cathedr
hiking  :  hike
bars  :  bar
demand  :  demand
strong  :  strong
tree  :  tree
twenty  :  twenti
bowling  :  bowl
conditions  :  condit
ensure  :  ensur
connects  :  connect
perfectly  :  perfectli
seeing  :  see
tourist  :  tourist
actual  :  actual
paved  :  pave
dinosaur  :  dinosaur
adjacent  :  adjac
gravel  :  gravel
prophet  :  prophet
lafayette  :  lafayett
meander  :  meander
provide  :  provid
require  :  requir
price  :  price
joan  :  joan
known  :  known
rouen  :  rouen
arts  :  art
fine  :  fine
addition  :  addit
sunrise  :  sunris
lane  :  lane
leonard  :  leonard
kilns  :  kiln
pueblo  :  pueblo
wark  :  wark
capture  :  captur
photographs  :  photograph
block  :  block
service  :  servic
manitou  :  manit
smiljan  :  smiljan
mount  :  mount
chacaltaya  :  chacaltaya
cost  :  cost
150  :  150
usd  :  usd
200  :  200
english  :  english
mornings  :  morn
seibu  :  seibu
alley  :  alley
docent  :  docent
kilometer  :  kilomet
wednesday  :  wednesday
painted  :  paint
2018  :  2018
plaque  :  plaqu
königswinter  :  königswint
transport  :  transport
passenger  :  passeng
still  :  still
athenry  :  athenri
detour  :  detour
makes  :  make
within  :  within
sides  :  side
times  :  time
lets  :  let
school  :  school
pinturas  :  pintura
ruta  :  ruta
looking  :  look
b047  :  b047
gives  :  give
leg  :  leg
rmb  :  rmb
maze  :  maze
tram  :  tram
completed  :  complet
reward  :  reward
sconondoa  :  sconondoa
cable  :  cabl
arild  :  arild
saturday  :  saturday
adults  :  adult
students  :  student
winthrop  :  winthrop
oconto  :  oconto
peshtigo  :  peshtigo
privacy  :  privaci
life  :  life
okinawa  :  okinawa
featuring  :  featur
blend  :  blend
works  :  work
typical  :  typic
carillon  :  carillon
automated  :  autom
plays  :  play
noon  :  noon
date  :  date
register  :  regist
transportation  :  transport
stillwell  :  stillwel
chambers  :  chamber
functioning  :  function
governmental  :  government
inform  :  inform
security  :  secur
staircases  :  staircas
sets  :  set
roam  :  roam
leisure  :  leisur
cases  :  case
levels  :  level
suggested  :  suggest
offered  :  offer
twice  :  twice
served  :  serv
basis  :  basi
fit  :  fit
george  :  georg
pamphlets  :  pamphlet
101  :  101
soto  :  soto
rancho  :  rancho
trapper  :  trapper
lodge  :  lodg
horses  :  hors
barn  :  barn
pierce  :  pierc
whose  :  whose
reside  :  resid
trying  :  tri
evict  :  evict
landmark  :  landmark
result  :  result
fenced  :  fenc
rips  :  rip
fencing  :  fenc
material  :  materi
raeford  :  raeford
fayetteville  :  fayettevil
hwy  :  hwi
401  :  401
cahuachi  :  cahuachi
ceremonial  :  ceremoni
nazca  :  nazca
name  :  name
nice  :  nice
discover  :  discov
linkeroever  :  linkeroev
scheldt  :  scheldt
sint  :  sint
annastrand  :  annastrand
lose  :  lose
grimness  :  grim
summery  :  summeri
hilarious  :  hilari
cinema  :  cinema
quarter  :  quarter
augustine  :  augustin
models  :  model
entryway  :  entryway
mathematics  :  mathemat
arizona  :  arizona
lamp  :  lamp
burns  :  burn
striking  :  strike
effect  :  effect
pop  :  pop
savoy  :  savoy
features  :  featur
liquors  :  liquor
1969  :  1969
thank  :  thank
neil  :  neil
armstrong  :  armstrong
nasa  :  nasa
stationery  :  stationeri
thanking  :  thank
sending  :  send
champagne  :  champagn
cocktail  :  cocktail
glasses  :  glass
toast  :  toast
landing  :  land
4th  :  4th
worship  :  worship
facebook  :  facebook
page  :  page
accessibility  :  access
questions  :  question
615  :  615
254  :  254
7584  :  7584
dpchurch  :  dpchurch
abandoned  :  abandon
chained  :  chain
future  :  futur
treasury  :  treasuri
shelter  :  shelter
opening  :  open
dry  :  dri
moat  :  moat
catch  :  catch
pennsylvania  :  pennsylvania
marks  :  mark
frozen  :  frozen
pie  :  pie
volunteer  :  volunt
sell  :  sell
parish  :  parish
drop  :  drop
weekday  :  weekday
mass  :  mass
artists  :  artist
compound  :  compound
rent  :  rent
term  :  term
expect  :  expect
murals  :  mural
completely  :  complet
text  :  text
310  :  310
827  :  827
1748  :  1748
gets  :  get
fully  :  fulli
perfect  :  perfect
throws  :  throw
event  :  event
draculacon  :  draculacon
walked  :  walk
praça  :  praça
figueira  :  figueira
busses  :  buss
12e  :  12e
15e  :  15e
208  :  208
714  :  714
736  :  736
737  :  737
760  :  760
rossio  :  rossio
lark  :  lark
salford  :  salford
temporarily  :  temporarili
represent  :  repres
eras  :  era
sports  :  sport
man  :  man
beaver  :  beaver
eureka  :  eureka
seven  :  seven
arrangements  :  arrang
wary  :  wari
roadside  :  roadsid
plus  :  plu
lit  :  lit
scheduled  :  schedul
chapel  :  chapel
women  :  women
gift  :  gift
plaza  :  plaza
mall  :  mall
3100  :  3100
harrison  :  harrison
permitting  :  permit
406  :  406
782  :  782
1221  :  1221
details  :  detail
congressional  :  congression
staffer  :  staffer
interns  :  intern
guests  :  guest
heard  :  heard
uncertain  :  uncertain
crazy  :  crazi
looks  :  look
senate  :  senat
ampelparchen  :  ampelparchen
crossings  :  cross
vienna  :  vienna
executive  :  execut
esperanto  :  esperanto
includes  :  includ
globe  :  globe
largest  :  largest
globes  :  globe
level  :  level
paradise  :  paradis
whitefish  :  whitefish
architect  :  architect
james  :  jame
dakin  :  dakin
designed  :  design
gothic  :  gothic
style  :  style
reason  :  reason
gorgeous  :  gorgeou
dome  :  dome
minions  :  minion
spare  :  spare
immersive  :  immers
theatrical  :  theatric
presentation  :  present
laurel  :  laurel
chandler  :  chandler
plain  :  plain
rear  :  rear
drassanes  :  drassan
wine  :  wine
tasting  :  tast
column  :  column
delicious  :  delici
options  :  option
raspberry  :  raspberri
parfait  :  parfait
moose  :  moos
feta  :  feta
cheese  :  chees
attraction  :  attract
broadmarsh  :  broadmarsh
brewhouse  :  brewhous
mortimer  :  mortim
hole  :  hole
conducted  :  conduct
virtual  :  virtual
throughs  :  through
nottingham  :  nottingham
survey  :  survey
hostel  :  hostel
riverside  :  riversid
non  :  non
powered  :  power
watercraft  :  watercraft
sup  :  sup
canoe  :  cano
bird  :  bird
epicsup  :  epicsup
california  :  california
sculpture  :  sculptur
storage  :  storag
restored  :  restor
artist  :  artist
latour  :  latour
maubourg  :  maubourg
varenne  :  varenn
invalides  :  invalid
francois  :  francoi
xavier  :  xavier
stavropoleos  :  stavropoleo
lipscani  :  lipscani
explore  :  explor
styx  :  styx
hobart  :  hobart
norfolk  :  norfolk
kid  :  kid
friendly  :  friendli
fair  :  fair
york  :  york
rutland  :  rutland
allen  :  allen
257  :  257
stroudsmoor  :  stroudsmoor
stroudsburg  :  stroudsburg
18360  :  18360
madrid  :  madrid
quarries  :  quarri
corporation  :  corpor
danby  :  danbi
quarry  :  quarri
circumstances  :  circumst
case  :  case
alcatel  :  alcatel
lucent  :  lucent
lab  :  lab
specified  :  specifi
winter  :  winter
rocky  :  rocki
noting  :  note
floors  :  floor
families  :  famili
thurs  :  thur
sat  :  sat
sun  :  sun
pow  :  pow
wow  :  wow
proves  :  prove
family  :  famili
picnics  :  picnic
berlin  :  berlin
trains  :  train
option  :  option
flixbus  :  flixbu
warm  :  warm
doors  :  door
neighboring  :  neighbor
basilica  :  basilica
five  :  five
euros  :  euro
houston  :  houston
1764  :  1764
fm1764  :  fm1764
lowry  :  lowri
expressway  :  expressway
making  :  make
29th  :  29th
bayview  :  bayview
146  :  146
southbound  :  southbound
197  :  197
loop  :  loop
25th  :  25th
7pm  :  7pm
osmond  :  osmond
adelaide  :  adelaid
hills  :  hill
bar  :  bar
wooden  :  wooden
dining  :  dine
prefer  :  prefer
meal  :  meal
bicycle  :  bicycl
boathouse  :  boathous
foot  :  foot
lakeview  :  lakeview
edge  :  edg
ravine  :  ravin
100  :  100
falmouth  :  falmouth
jamaica  :  jamaica
montego  :  montego
bay  :  bay
ocho  :  ocho
rios  :  rio
bronx  :  bronx
fame  :  fame
terrace  :  terrac
fall  :  fall
warned  :  warn
resembled  :  resembl
muddy  :  muddi
mess  :  mess
seasons  :  season
250  :  250
seattle  :  seattl
slopes  :  slope
mushera  :  mushera
musherabeg  :  musherabeg
eleven  :  eleven
cork  :  cork
300  :  300
meters  :  meter
ali  :  ali
marked  :  mark
las  :  la
momias  :  momia
without  :  without
windows  :  window
souvenir  :  souvenir
stands  :  stand
kind  :  kind
can  :  can
not  :  not
underneath  :  underneath
enough  :  enough
appreciate  :  appreci
ghastly  :  ghastli
cadavers  :  cadav
bank  :  bank
exhibit  :  exhibit
731  :  731
2013  :  2013
outhouse  :  outhous
575  :  575
pere  :  pere
marquette  :  marquett
belgrade  :  belgrad
crow  :  crow
4442  :  4442
0091  :  0091
annual  :  annual
dues  :  due
programming  :  program
garages  :  garag
attend  :  attend
silent  :  silent
film  :  film
screening  :  screen
authentic  :  authent
movie  :  movi
mighty  :  mighti
wurlitzer  :  wurlitz
pipe  :  pipe
organ  :  organ
providing  :  provid
musical  :  music
accompaniment  :  accompani
crowds  :  crowd
tend  :  tend
gather  :  gather
shiny  :  shini
toe  :  toe
rub  :  rub
causes  :  caus
damage  :  damag
sandy  :  sandi
stoddart  :  stoddart
depiction  :  depict
greek  :  greek
god  :  god
helios  :  helio
illustrating  :  illustr
concept  :  concept
enlightenment  :  enlighten
surrounded  :  surround
nest  :  nest
snakes  :  snake

In [76]:
Stem_dict = dict([(y,x+1) for x,y in enumerate(sorted(set(desc_list)))])

In [77]:
print(Stem_dict)

{'0091': 1, '100': 2, '101': 3, '10am': 4, '112': 5, '115': 6, '116': 7, '120': 8, '1221': 9, '124': 10, '12e': 11, '12th': 12, '131': 13, '1415': 14, '145': 15, '146': 16, '150': 17, '15e': 18, '1615': 19, '169': 20, '16th': 21, '1748': 22, '175': 23, '1764': 24, '178': 25, '18360': 26, '185': 27, '18km': 28, '1929': 29, '1969': 30, '197': 31, '1st': 32, '200': 33, '2013': 34, '2014': 35, '2017': 36, '2018': 37, '2019': 38, '2021': 39, '208': 40, '209': 41, '20th': 42, '2100': 43, '2101': 44, '219': 45, '240': 46, '250': 47, '254': 48, '257': 49, '25th': 50, '26th': 51, '29th': 52, '2km': 53, '2nd': 54, '300': 55, '30th': 56, '310': 57, '3100': 58, '31st': 59, '3200': 60, '333': 61, '334': 62, '34th': 63, '371': 64, '3rd': 65, '401': 66, '406': 67, '4442': 68, '4pm': 69, '4th': 70, '502': 71, '5099': 72, '545': 73, '575': 74, '5pm': 75, '600': 76, '60th': 77, '615': 78, '65th': 79, '714': 80, '727': 81, '731': 82, '736': 83, '737': 84, '742': 85, '7584': 86, '760': 87, '782': 88, '7pm': 89, '7th': 90, '80220': 91, '827': 92, '845': 93, '855': 94, '8am': 95, '8pm': 96, '8th': 97, '9am': 98, 'a450': 99, 'a5025': 100, 'a965': 101, 'abandoned': 102, 'abbey': 103, 'able': 104, 'access': 105, 'accessed': 106, 'accessibility': 107, 'accessible': 108, 'accompaniment': 109, 'according': 110, 'accordingly': 111, 'across': 112, 'activity': 113, 'actual': 114, 'actually': 115, 'adams': 116, 'adding': 117, 'addition': 118, 'address': 119, 'adelaide': 120, 'adjacent': 121, 'admission': 122, 'admissions': 123, 'admitted': 124, 'adult': 125, 'adults': 126, 'advance': 127, 'advantage': 128, 'adventure': 129, 'adverse': 130, 'advisable': 131, 'advised': 132, 'aerial': 133, 'afar': 134, 'aftermarket': 135, 'aged': 136, 'aggressively': 137, 'ahead': 138, 'ahrens': 139, 'aimed': 140, 'air': 141, 'airport': 142, 'akinfreelibrary': 143, 'alameda': 144, 'alaska': 145, 'alberta': 146, 'albuquerque': 147, 'alcatel': 148, 'ali': 149, 'allen': 150, 'allentown': 151, 'alley': 152, 'alleyway': 153, 'allowed': 154, 'allowing': 155, 'allows': 156, 'almost': 157, 'alone': 158, 'along': 159, 'already': 160, 'also': 161, 'alternatively': 162, 'although': 163, 'alto': 164, 'always': 165, 'among': 166, 'ampelparchen': 167, 'ample': 168, 'amtrak': 169, 'annastrand': 170, 'anniversary': 171, 'annual': 172, 'another': 173, 'antenna': 174, 'anti': 175, 'antlers': 176, 'anyone': 177, 'ap7': 178, 'apple': 179, 'appointment': 180, 'appreciate': 181, 'approx': 182, 'approximately': 183, 'april': 184, 'aquileia': 185, 'arc': 186, 'arcade': 187, 'architect': 188, 'area': 189, 'arild': 190, 'arizona': 191, 'armstrong': 192, 'around': 193, 'arrange': 194, 'arranged': 195, 'arrangements': 196, 'arranging': 197, 'arrested': 198, 'arrive': 199, 'arriving': 200, 'art': 201, 'artifacts': 202, 'artist': 203, 'artists': 204, 'arts': 205, 'artwork': 206, 'asakusa': 207, 'ashford': 208, 'ashton': 209, 'ask': 210, 'athenry': 211, 'attend': 212, 'attention': 213, 'attraction': 214, 'audio': 215, 'augustine': 216, 'authentic': 217, 'automated': 218, 'autumn': 219, 'available': 220, 'ave': 221, 'avenue': 222, 'avoid': 223, 'aware': 224, 'away': 225, 'axle': 226, 'b047': 227, 'back': 228, 'backyard': 229, 'bainbridge': 230, 'bajo': 231, 'ball': 232, 'bangkok': 233, 'bank': 234, 'banks': 235, 'bao': 236, 'bar': 237, 'barbed': 238, 'barcelona': 239, 'barn': 240, 'barre': 241, 'bars': 242, 'base': 243, 'basilica': 244, 'basis': 245, 'basking': 246, 'bathrooms': 247, 'bathtubs': 248, 'bay': 249, 'bayview': 250, 'beach': 251, 'bears': 252, 'beaver': 253, 'becomes': 254, 'beer': 255, 'began': 256, 'beginning': 257, 'behave': 258, 'behind': 259, 'belgrade': 260, 'bellagio': 261, 'bellesguard': 262, 'belongings': 263, 'bend': 264, 'bends': 265, 'bennett': 266, 'berlin': 267, 'bernard': 268, 'bernardo': 269, 'beside': 270, 'best': 271, 'bet': 272, 'better': 273, 'beware': 274, 'bicycle': 275, 'big': 276, 'bigger': 277, 'bike': 278, 'biker': 279, 'biking': 280, 'binoculars': 281, 'bird': 282, 'birds': 283, 'bit': 284, 'blasting': 285, 'blend': 286, 'blinds': 287, 'blink': 288, 'block': 289, 'blocks': 290, 'blois': 291, 'bluff': 292, 'bluffs': 293, 'blvd': 294, 'boat': 295, 'boathouse': 296, 'bodø': 297, 'bolivia': 298, 'bonn': 299, 'book': 300, 'booked': 301, 'booking': 302, 'bookshop': 303, 'border': 304, 'bordils': 305, 'bottom': 306, 'bouchers': 307, 'boulder': 308, 'boulevard': 309, 'bounded': 310, 'bourbon': 311, 'bowling': 312, 'braddock': 313, 'breaking': 314, 'breeding': 315, 'brewhouse': 316, 'brick': 317, 'bridge': 318, 'briefly': 319, 'bring': 320, 'britain': 321, 'broadmarsh': 322, 'broadway': 323, 'brodheadsville': 324, 'broken': 325, 'bronx': 326, 'brook': 327, 'brussels': 328, 'bts': 329, 'building': 330, 'buildings': 331, 'bull': 332, 'buried': 333, 'burlington': 334, 'burns': 335, 'bus': 336, 'buses': 337, 'business': 338, 'busses': 339, 'butte': 340, 'buy': 341, 'cable': 342, 'cadavers': 343, 'cafeteria': 344, 'café': 345, 'cahuachi': 346, 'calendar': 347, 'calgary': 348, 'california': 349, 'call': 350, 'called': 351, 'calling': 352, 'camera': 353, 'cameras': 354, 'campaigns': 355, 'camping': 356, 'campus': 357, 'can': 358, 'canal': 359, 'canoe': 360, 'cans': 361, 'canyon': 362, 'capture': 363, 'captures': 364, 'car': 365, 'caracoles': 366, 'care': 367, 'career': 368, 'carillon': 369, 'cars': 370, 'carsons': 371, 'cart': 372, 'carving': 373, 'casagoofyintl': 374, 'case': 375, 'cases': 376, 'casino': 377, 'castle': 378, 'catacombs': 379, 'catch': 380, 'cathedral': 381, 'causes': 382, 'cave': 383, 'caves': 384, 'cedar': 385, 'celebrated': 386, 'celebratory': 387, 'cell': 388, 'cemeteries': 389, 'cemetery': 390, 'center': 391, 'central': 392, 'centre': 393, 'century': 394, 'cerchi': 395, 'ceremonial': 396, 'chacaltaya': 397, 'chained': 398, 'chamberlin': 399, 'chambers': 400, 'champagne': 401, 'chandler': 402, 'chang': 403, 'change': 404, 'changes': 405, 'chapel': 406, 'chapter': 407, 'characteristics': 408, 'charge': 409, 'chartered': 410, 'chartering': 411, 'cheap': 412, 'check': 413, 'cheese': 414, 'child': 415, 'children': 416, 'china': 417, 'chinese': 418, 'chocolate': 419, 'christmas': 420, 'church': 421, 'cinema': 422, 'circumstances': 423, 'city': 424, 'cividale': 425, 'clash': 426, 'classes': 427, 'classic': 428, 'clearly': 429, 'cliffs': 430, 'climb': 431, 'climbed': 432, 'climbing': 433, 'climbs': 434, 'close': 435, 'closed': 436, 'closer': 437, 'closes': 438, 'closest': 439, 'cocktail': 440, 'collapses': 441, 'collection': 442, 'collections': 443, 'college': 444, 'cologne': 445, 'color': 446, 'colored': 447, 'column': 448, 'com': 449, 'come': 450, 'coming': 451, 'commendator': 452, 'commercial': 453, 'commune': 454, 'communications': 455, 'community': 456, 'companies': 457, 'completed': 458, 'completely': 459, 'complex': 460, 'compound': 461, 'comstock': 462, 'concept': 463, 'concerts': 464, 'concrete': 465, 'condition': 466, 'conditions': 467, 'conducted': 468, 'cone': 469, 'conference': 470, 'confirmation': 471, 'congressional': 472, 'conimbra': 473, 'conimbraga': 474, 'connects': 475, 'consciously': 476, 'conservancy': 477, 'conservation': 478, 'conservatory': 479, 'consider': 480, 'constitution': 481, 'consult': 482, 'contact': 483, 'contacting': 484, 'containing': 485, 'continuation': 486, 'continue': 487, 'cool': 488, 'coordinated': 489, 'coordinates': 490, 'cork': 491, 'corner': 492, 'corona': 493, 'corporation': 494, 'correct': 495, 'cosme': 496, 'cost': 497, 'costs': 498, 'could': 499, 'country': 500, 'county': 501, 'couple': 502, 'course': 503, 'coventry': 504, 'cows': 505, 'cramlington': 506, 'crazy': 507, 'cream': 508, 'creek': 509, 'cross': 510, 'crossing': 511, 'crossings': 512, 'crouch': 513, 'crow': 514, 'crowds': 515, 'cube': 516, 'culture': 517, 'currently': 518, 'curtain': 519, 'cuts': 520, 'cycle': 521, 'dai': 522, 'daily': 523, 'dakin': 524, 'damage': 525, 'damaged': 526, 'danby': 527, 'dangerous': 528, 'dark': 529, 'date': 530, 'dates': 531, 'dawn': 532, 'day': 533, 'days': 534, 'dead': 535, 'decent': 536, 'decision': 537, 'dedicated': 538, 'dei': 539, 'delicious': 540, 'demand': 541, 'demolition': 542, 'denver': 543, 'department': 544, 'depending': 545, 'depicted': 546, 'depiction': 547, 'depth': 548, 'describe': 549, 'designed': 550, 'desk': 551, 'despite': 552, 'destruction': 553, 'detail': 554, 'details': 555, 'detour': 556, 'developed': 557, 'diamond': 558, 'different': 559, 'difficulties': 560, 'dignity': 561, 'dining': 562, 'dinosaur': 563, 'direct': 564, 'direction': 565, 'directions': 566, 'directly': 567, 'director': 568, 'dirt': 569, 'disabled': 570, 'disappointment': 571, 'discover': 572, 'discovery': 573, 'dishes': 574, 'display': 575, 'distance': 576, 'distinct': 577, 'district': 578, 'docent': 579, 'doll': 580, 'doloris': 581, 'dome': 582, 'domingo': 583, 'donations': 584, 'done': 585, 'donjon': 586, 'doorbell': 587, 'doors': 588, 'dot': 589, 'dotted': 590, 'downstairs': 591, 'downtown': 592, 'dpchurch': 593, 'drachenfels': 594, 'draculacon': 595, 'dragon': 596, 'dragons': 597, 'drassanes': 598, 'drawings': 599, 'dress': 600, 'drive': 601, 'driver': 602, 'drivers': 603, 'driving': 604, 'drone': 605, 'drop': 606, 'droppings': 607, 'dry': 608, 'due': 609, 'dues': 610, 'dumbarton': 611, 'dungeon': 612, 'dusk': 613, 'duval': 614, 'e021': 615, 'earlimart': 616, 'early': 617, 'easiest': 618, 'easily': 619, 'east': 620, 'easy': 621, 'eating': 622, 'eats': 623, 'edge': 624, 'edgewater': 625, 'edit': 626, 'editors': 627, 'effect': 628, 'eight': 629, 'either': 630, 'electric': 631, 'elevator': 632, 'eleven': 633, 'email': 634, 'employees': 635, 'empty': 636, 'encourage': 637, 'encouraged': 638, 'end': 639, 'ends': 640, 'english': 641, 'enjoy': 642, 'enlightenment': 643, 'enough': 644, 'ensure': 645, 'enter': 646, 'entering': 647, 'entertainment': 648, 'entrance': 649, 'entrances': 650, 'entry': 651, 'entryway': 652, 'epicsup': 653, 'eras': 654, 'erawan': 655, 'escape': 656, 'esperanto': 657, 'estate': 658, 'eureka': 659, 'euros': 660, 'even': 661, 'evening': 662, 'event': 663, 'events': 664, 'every': 665, 'everyone': 666, 'evict': 667, 'exact': 668, 'examine': 669, 'example': 670, 'exceptionally': 671, 'excursion': 672, 'executive': 673, 'exercise': 674, 'exhibit': 675, 'exhibitions': 676, 'exit': 677, 'expect': 678, 'experience': 679, 'experienced': 680, 'explain': 681, 'explore': 682, 'expressway': 683, 'eye': 684, 'facebook': 685, 'facilities': 686, 'fair': 687, 'fairhaven': 688, 'fall': 689, 'falls': 690, 'falmouth': 691, 'fame': 692, 'families': 693, 'family': 694, 'far': 695, 'farm': 696, 'farmstead': 697, 'farnams': 698, 'favorite': 699, 'fayetteville': 700, 'features': 701, 'featuring': 702, 'february': 703, 'fee': 704, 'fees': 705, 'feet': 706, 'female': 707, 'fen': 708, 'fence': 709, 'fenced': 710, 'fenceline': 711, 'fences': 712, 'fencing': 713, 'ferguson': 714, 'ferry': 715, 'feta': 716, 'fidélité': 717, 'field': 718, 'fields': 719, 'figueira': 720, 'figueres': 721, 'filled': 722, 'film': 723, 'final': 724, 'find': 725, 'finding': 726, 'fine': 727, 'firehat': 728, 'first': 729, 'fisgard': 730, 'fish': 731, 'fit': 732, 'five': 733, 'flaçà': 734, 'flight': 735, 'flixbus': 736, 'floor': 737, 'floors': 738, 'fly': 739, 'fm1764': 740, 'foggy': 741, 'follow': 742, 'following': 743, 'foot': 744, 'footpath': 745, 'formation': 746, 'formations': 747, 'formerly': 748, 'fortress': 749, 'fortresses': 750, 'found': 751, 'fountain': 752, 'france': 753, 'francois': 754, 'free': 755, 'fremont': 756, 'friday': 757, 'fridays': 758, 'friendly': 759, 'front': 760, 'frozen': 761, 'fulfilled': 762, 'fulfilling': 763, 'fully': 764, 'functioning': 765, 'future': 766, 'förstadsgatan': 767, 'gain': 768, 'galeties': 769, 'gallery': 770, 'galway': 771, 'game': 772, 'gamla': 773, 'garages': 774, 'garden': 775, 'gardens': 776, 'gate': 777, 'gates': 778, 'gather': 779, 'gaviota': 780, 'general': 781, 'gentle': 782, 'george': 783, 'get': 784, 'gets': 785, 'getting': 786, 'ghastly': 787, 'gift': 788, 'girl': 789, 'girls': 790, 'girona': 791, 'give': 792, 'gives': 793, 'gladly': 794, 'gladys': 795, 'glasgow': 796, 'glasses': 797, 'glen': 798, 'glenn': 799, 'glimpse': 800, 'globe': 801, 'globes': 802, 'glyphs': 803, 'gmx': 804, 'god': 805, 'going': 806, 'golf': 807, 'gondola': 808, 'gone': 809, 'gong': 810, 'good': 811, 'google': 812, 'gopher': 813, 'gordon': 814, 'gorgeous': 815, 'gospic': 816, 'gotanda': 817, 'gothic': 818, 'government': 819, 'governmental': 820, 'gps': 821, 'grand': 822, 'grande': 823, 'grate': 824, 'grave': 825, 'gravel': 826, 'graveyard': 827, 'great': 828, 'greek': 829, 'green': 830, 'greenhouse': 831, 'grevin10': 832, 'grill': 833, 'grimness': 834, 'ground': 835, 'grounds': 836, 'group': 837, 'groups': 838, 'guardians': 839, 'guests': 840, 'guide': 841, 'guided': 842, 'guides': 843, 'guoliang': 844, 'guoliangcun': 845, 'habsburg': 846, 'haena': 847, 'haggle': 848, 'hail': 849, 'half': 850, 'halfway': 851, 'hall': 852, 'halloween': 853, 'hamburgmuseum': 854, 'hampshire': 855, 'hanakoa': 856, 'handle': 857, 'hanging': 858, 'hanky': 859, 'hanychov': 860, 'happen': 861, 'happening': 862, 'hard': 863, 'harriet': 864, 'harris': 865, 'harrison': 866, 'hart': 867, 'hartbauer': 868, 'hawai': 869, 'hawaiʻi': 870, 'head': 871, 'heading': 872, 'heard': 873, 'heart': 874, 'height': 875, 'helicopter': 876, 'helios': 877, 'help': 878, 'helped': 879, 'herald': 880, 'hermine': 881, 'hexagonal': 882, 'hidden': 883, 'high': 884, 'highly': 885, 'highway': 886, 'hike': 887, 'hikers': 888, 'hiking': 889, 'hilarious': 890, 'hill': 891, 'hills': 892, 'himmelstorp': 893, 'hire': 894, 'hired': 895, 'hishi': 896, 'historical': 897, 'history': 898, 'hobart': 899, 'hogan': 900, 'hole': 901, 'holiday': 902, 'holidays': 903, 'hollow': 904, 'home': 905, 'homes': 906, 'horses': 907, 'hostel': 908, 'hosts': 909, 'hot': 910, 'hotel': 911, 'hour': 912, 'hours': 913, 'house': 914, 'houston': 915, 'however': 916, 'hubert': 917, 'huge': 918, 'huixian': 919, 'hundred': 920, 'hunt': 921, 'hutchinson': 922, 'huxian': 923, 'hwy': 924, 'höganäs': 925, 'ice': 926, 'idea': 927, 'ikebukuro': 928, 'ikegami': 929, 'illegal': 930, 'illinois': 931, 'illustrating': 932, 'images': 933, 'immediately': 934, 'immersive': 935, 'impasse': 936, 'imperial': 937, 'import': 938, 'imposed': 939, 'inclement': 940, 'include': 941, 'included': 942, 'includes': 943, 'including': 944, 'indian': 945, 'indicate': 946, 'info': 947, 'inform': 948, 'information': 949, 'infrastructure': 950, 'initially': 951, 'inside': 952, 'installation': 953, 'instead': 954, 'instructed': 955, 'intellectualism': 956, 'interested': 957, 'interesting': 958, 'interior': 959, 'international': 960, 'interns': 961, 'intersection': 962, 'intersects': 963, 'interstate': 964, 'intimidating': 965, 'invalides': 966, 'involves': 967, 'island': 968, 'isolated': 969, 'issues': 970, 'jack': 971, 'jacobs': 972, 'jaffrey': 973, 'jamaica': 974, 'james': 975, 'japanese': 976, 'jeanne': 977, 'jin': 978, 'joan': 979, 'job': 980, 'john': 981, 'jonquera': 982, 'jump': 983, 'june': 984, 'kalalau': 985, 'kayak': 986, 'kayakers': 987, 'keep': 988, 'kentucky': 989, 'kept': 990, 'kew': 991, 'key': 992, 'kid': 993, 'kidderminster': 994, 'kids': 995, 'kilns': 996, 'kilometer': 997, 'kilometers': 998, 'kind': 999, 'king': 1000, 'knowledge': 1001, 'knowledgeable': 1002, 'known': 1003, 'koa': 1004, 'königswinter': 1005, 'lab': 1006, 'lack': 1007, 'lad': 1008, 'ladd': 1009, 'ladder': 1010, 'lady': 1011, 'lafayette': 1012, 'lake': 1013, 'lakeview': 1014, 'lamp': 1015, 'lancaster': 1016, 'land': 1017, 'landing': 1018, 'landmark': 1019, 'landscape': 1020, 'lane': 1021, 'languages': 1022, 'large': 1023, 'larger': 1024, 'largest': 1025, 'lark': 1026, 'las': 1027, 'last': 1028, 'lat': 1029, 'later': 1030, 'latour': 1031, 'laurel': 1032, 'lead': 1033, 'leads': 1034, 'least': 1035, 'leave': 1036, 'leaves': 1037, 'led': 1038, 'left': 1039, 'leg': 1040, 'leisure': 1041, 'leland': 1042, 'leonard': 1043, 'less': 1044, 'lesser': 1045, 'lets': 1046, 'levee': 1047, 'level': 1048, 'levels': 1049, 'lexington': 1050, 'library': 1051, 'liceu': 1052, 'lies': 1053, 'life': 1054, 'lighthouse': 1055, 'like': 1056, 'lily': 1057, 'limit': 1058, 'limited': 1059, 'limits': 1060, 'line': 1061, 'lines': 1062, 'link': 1063, 'linkeroever': 1064, 'lipscani': 1065, 'liquors': 1066, 'listed': 1067, 'listen': 1068, 'listing': 1069, 'lit': 1070, 'little': 1071, 'live': 1072, 'lives': 1073, 'llanallgo': 1074, 'local': 1075, 'locals': 1076, 'locate': 1077, 'located': 1078, 'location': 1079, 'locations': 1080, 'lockable': 1081, 'locked': 1082, 'locker': 1083, 'lodge': 1084, 'london': 1085, 'long': 1086, 'longer': 1087, 'look': 1088, 'looking': 1089, 'looks': 1090, 'loop': 1091, 'lose': 1092, 'lost': 1093, 'lot': 1094, 'lots': 1095, 'lou': 1096, 'low': 1097, 'lower': 1098, 'lowry': 1099, 'ltd': 1100, 'lucent': 1101, 'lyon': 1102, 'made': 1103, 'madison': 1104, 'madrid': 1105, 'magazine': 1106, 'main': 1107, 'major': 1108, 'make': 1109, 'makes': 1110, 'making': 1111, 'mall': 1112, 'malmö': 1113, 'man': 1114, 'manitou': 1115, 'mansion': 1116, 'many': 1117, 'map': 1118, 'maps': 1119, 'march': 1120, 'mariahilfer': 1121, 'maritime': 1122, 'mark': 1123, 'marked': 1124, 'marker': 1125, 'markers': 1126, 'marks': 1127, 'marquette': 1128, 'mason': 1129, 'mass': 1130, 'massive': 1131, 'mast': 1132, 'masterpiece': 1133, 'masts': 1134, 'material': 1135, 'mathematics': 1136, 'matter': 1137, 'matthew': 1138, 'maubourg': 1139, 'may': 1140, 'maybe': 1141, 'maybeck': 1142, 'mayo': 1143, 'maze': 1144, 'meal': 1145, 'meander': 1146, 'meaning': 1147, 'measures': 1148, 'medical': 1149, 'medicine': 1150, 'meeting': 1151, 'meets': 1152, 'member': 1153, 'members': 1154, 'memorial': 1155, 'memory': 1156, 'mentioned': 1157, 'menu': 1158, 'mess': 1159, 'meta': 1160, 'metal': 1161, 'meters': 1162, 'metler': 1163, 'metro': 1164, 'mexico': 1165, 'michigan': 1166, 'mid': 1167, 'midway': 1168, 'might': 1169, 'mighty': 1170, 'mile': 1171, 'miles': 1172, 'mill': 1173, 'million': 1174, 'millstreet': 1175, 'min': 1176, 'mindful': 1177, 'minions': 1178, 'minute': 1179, 'minutes': 1180, 'miss': 1181, 'missing': 1182, 'moat': 1183, 'mobility': 1184, 'mochi': 1185, 'mochiya': 1186, 'models': 1187, 'modern': 1188, 'moher': 1189, 'momias': 1190, 'monday': 1191, 'mondays': 1192, 'montego': 1193, 'months': 1194, 'montmartre': 1195, 'montmartre75009': 1196, 'monument': 1197, 'monumental': 1198, 'moon': 1199, 'moonraker': 1200, 'moose': 1201, 'morning': 1202, 'mornings': 1203, 'mortimer': 1204, 'mosaics': 1205, 'motor': 1206, 'motorway': 1207, 'mount': 1208, 'mountain': 1209, 'mounted': 1210, 'mouth': 1211, 'movie': 1212, 'mrt': 1213, 'msp': 1214, 'much': 1215, 'mud': 1216, 'muddy': 1217, 'mural': 1218, 'murals': 1219, 'museum': 1220, 'museumsquartier': 1221, 'mushera': 1222, 'musherabeg': 1223, 'music': 1224, 'musical': 1225, 'must': 1226, 'musée': 1227, 'mystery': 1228, 'n4150': 1229, 'nacional': 1230, 'nails': 1231, 'name': 1232, 'named': 1233, 'names': 1234, 'nanping': 1235, 'narrow': 1236, 'nas': 1237, 'nasa': 1238, 'nashville': 1239, 'national': 1240, 'native': 1241, 'natural': 1242, 'nature': 1243, 'nazca': 1244, 'near': 1245, 'nearby': 1246, 'nearest': 1247, 'nearly': 1248, 'necessary': 1249, 'need': 1250, 'neighborhood': 1251, 'neighboring': 1252, 'neil': 1253, 'nest': 1254, 'netherlands': 1255, 'never': 1256, 'new': 1257, 'newcastle': 1258, 'next': 1259, 'niagara': 1260, 'nice': 1261, 'night': 1262, 'nimis': 1263, 'nine': 1264, 'nisshodo': 1265, 'non': 1266, 'nonetheless': 1267, 'noon': 1268, 'norfolk': 1269, 'normally': 1270, 'north': 1271, 'northeast': 1272, 'northumberland': 1273, 'northumberlandia': 1274, 'northwest': 1275, 'not': 1276, 'note': 1277, 'noting': 1278, 'nottingham': 1279, 'november': 1280, 'nowata': 1281, 'numbers': 1282, 'nys': 1283, 'objects': 1284, 'obtain': 1285, 'occasion': 1286, 'occasionally': 1287, 'occupants': 1288, 'ocho': 1289, 'oconto': 1290, 'october': 1291, 'offer': 1292, 'offered': 1293, 'offe

In [79]:
term = {'term': []}
term_id = {'term_id' : []}

In [80]:
print(term)
print(term_id)

{'term': []}
{'term_id': []}

In [81]:
for k in Stem_dict.keys():
    term['term'].append(k)

In [82]:
print(term)

{'term': ['0091', '100', '101', '10am', '112', '115', '116', '120', '1221', '124', '12e', '12th', '131', '1415', '145', '146', '150', '15e', '1615', '169', '16th', '1748', '175', '1764', '178', '18360', '185', '18km', '1929', '1969', '197', '1st', '200', '2013', '2014', '2017', '2018', '2019', '2021', '208', '209', '20th', '2100', '2101', '219', '240', '250', '254', '257', '25th', '26th', '29th', '2km', '2nd', '300', '30th', '310', '3100', '31st', '3200', '333', '334', '34th', '371', '3rd', '401', '406', '4442', '4pm', '4th', '502', '5099', '545', '575', '5pm', '600', '60th', '615', '65th', '714', '727', '731', '736', '737', '742', '7584', '760', '782', '7pm', '7th', '80220', '827', '845', '855', '8am', '8pm', '8th', '9am', 'a450', 'a5025', 'a965', 'abandoned', 'abbey', 'able', 'access', 'accessed', 'accessibility', 'accessible', 'accompaniment', 'according', 'accordingly', 'across', 'activity', 'actual', 'actually', 'adams', 'adding', 'addition', 'address', 'adelaide', 'adjacent', 'admission', 'admissions', 'admitted', 'adult', 'adults', 'advance', 'advantage', 'adventure', 'adverse', 'advisable', 'advised', 'aerial', 'afar', 'aftermarket', 'aged', 'aggressively', 'ahead', 'ahrens', 'aimed', 'air', 'airport', 'akinfreelibrary', 'alameda', 'alaska', 'alberta', 'albuquerque', 'alcatel', 'ali', 'allen', 'allentown', 'alley', 'alleyway', 'allowed', 'allowing', 'allows', 'almost', 'alone', 'along', 'already', 'also', 'alternatively', 'although', 'alto', 'always', 'among', 'ampelparchen', 'ample', 'amtrak', 'annastrand', 'anniversary', 'annual', 'another', 'antenna', 'anti', 'antlers', 'anyone', 'ap7', 'apple', 'appointment', 'appreciate', 'approx', 'approximately', 'april', 'aquileia', 'arc', 'arcade', 'architect', 'area', 'arild', 'arizona', 'armstrong', 'around', 'arrange', 'arranged', 'arrangements', 'arranging', 'arrested', 'arrive', 'arriving', 'art', 'artifacts', 'artist', 'artists', 'arts', 'artwork', 'asakusa', 'ashford', 'ashton', 'ask', 'athenry', 'attend', 'attention', 'attraction', 'audio', 'augustine', 'authentic', 'automated', 'autumn', 'available', 'ave', 'avenue', 'avoid', 'aware', 'away', 'axle', 'b047', 'back', 'backyard', 'bainbridge', 'bajo', 'ball', 'bangkok', 'bank', 'banks', 'bao', 'bar', 'barbed', 'barcelona', 'barn', 'barre', 'bars', 'base', 'basilica', 'basis', 'basking', 'bathrooms', 'bathtubs', 'bay', 'bayview', 'beach', 'bears', 'beaver', 'becomes', 'beer', 'began', 'beginning', 'behave', 'behind', 'belgrade', 'bellagio', 'bellesguard', 'belongings', 'bend', 'bends', 'bennett', 'berlin', 'bernard', 'bernardo', 'beside', 'best', 'bet', 'better', 'beware', 'bicycle', 'big', 'bigger', 'bike', 'biker', 'biking', 'binoculars', 'bird', 'birds', 'bit', 'blasting', 'blend', 'blinds', 'blink', 'block', 'blocks', 'blois', 'bluff', 'bluffs', 'blvd', 'boat', 'boathouse', 'bodø', 'bolivia', 'bonn', 'book', 'booked', 'booking', 'bookshop', 'border', 'bordils', 'bottom', 'bouchers', 'boulder', 'boulevard', 'bounded', 'bourbon', 'bowling', 'braddock', 'breaking', 'breeding', 'brewhouse', 'brick', 'bridge', 'briefly', 'bring', 'britain', 'broadmarsh', 'broadway', 'brodheadsville', 'broken', 'bronx', 'brook', 'brussels', 'bts', 'building', 'buildings', 'bull', 'buried', 'burlington', 'burns', 'bus', 'buses', 'business', 'busses', 'butte', 'buy', 'cable', 'cadavers', 'cafeteria', 'café', 'cahuachi', 'calendar', 'calgary', 'california', 'call', 'called', 'calling', 'camera', 'cameras', 'campaigns', 'camping', 'campus', 'can', 'canal', 'canoe', 'cans', 'canyon', 'capture', 'captures', 'car', 'caracoles', 'care', 'career', 'carillon', 'cars', 'carsons', 'cart', 'carving', 'casagoofyintl', 'case', 'cases', 'casino', 'castle', 'catacombs', 'catch', 'cathedral', 'causes', 'cave', 'caves', 'cedar', 'celebrated', 'celebratory', 'cell', 'cemeteries', 'cemetery', 'center', 'central', 'centre', 'century', 'cerchi', 'ceremonial', 'chacaltaya', 'chained', 'chamberlin', 'chambers', 'champagne', 'chandler', 'chang', 'change', 'changes', 'chapel', 'chapter', 'characteristics', 'charge', 'chartered', 'chartering', 'cheap', 'check', 'cheese', 'child', 'children', 'china', 'chinese', 'chocolate', 'christmas', 'church', 'cinema', 'circumstances', 'city', 'cividale', 'clash', 'classes', 'classic', 'clearly', 'cliffs', 'climb', 'climbed', 'climbing', 'climbs', 'close', 'closed', 'closer', 'closes', 'closest', 'cocktail', 'collapses', 'collection', 'collections', 'college', 'cologne', 'color', 'colored', 'column', 'com', 'come', 'coming', 'commendator', 'commercial', 'commune', 'communications', 'community', 'companies', 'completed', 'completely', 'complex', 'compound', 'comstock', 'concept', 'concerts', 'concrete', 'condition', 'conditions', 'conducted', 'cone', 'conference', 'confirmation', 'congressional', 'conimbra', 'conimbraga', 'connects', 'consciously', 'conservancy', 'conservation', 'conservatory', 'consider', 'constitution', 'consult', 'contact', 'contacting', 'containing', 'continuation', 'continue', 'cool', 'coordinated', 'coordinates', 'cork', 'corner', 'corona', 'corporation', 'correct', 'cosme', 'cost', 'costs', 'could', 'country', 'county', 'couple', 'course', 'coventry', 'cows', 'cramlington', 'crazy', 'cream', 'creek', 'cross', 'crossing', 'crossings', 'crouch', 'crow', 'crowds', 'cube', 'culture', 'currently', 'curtain', 'cuts', 'cycle', 'dai', 'daily', 'dakin', 'damage', 'damaged', 'danby', 'dangerous', 'dark', 'date', 'dates', 'dawn', 'day', 'days', 'dead', 'decent', 'decision', 'dedicated', 'dei', 'delicious', 'demand', 'demolition', 'denver', 'department', 'depending', 'depicted', 'depiction', 'depth', 'describe', 'designed', 'desk', 'despite', 'destruction', 'detail', 'details', 'detour', 'developed', 'diamond', 'different', 'difficulties', 'dignity', 'dining', 'dinosaur', 'direct', 'direction', 'directions', 'directly', 'director', 'dirt', 'disabled', 'disappointment', 'discover', 'discovery', 'dishes', 'display', 'distance', 'distinct', 'district', 'docent', 'doll', 'doloris', 'dome', 'domingo', 'donations', 'done', 'donjon', 'doorbell', 'doors', 'dot', 'dotted', 'downstairs', 'downtown', 'dpchurch', 'drachenfels', 'draculacon', 'dragon', 'dragons', 'drassanes', 'drawings', 'dress', 'drive', 'driver', 'drivers', 'driving', 'drone', 'drop', 'droppings', 'dry', 'due', 'dues', 'dumbarton', 'dungeon', 'dusk', 'duval', 'e021', 'earlimart', 'early', 'easiest', 'easily', 'east', 'easy', 'eating', 'eats', 'edge', 'edgewater', 'edit', 'editors', 'effect', 'eight', 'either', 'electric', 'elevator', 'eleven', 'email', 'employees', 'empty', 'encourage', 'encouraged', 'end', 'ends', 'english', 'enjoy', 'enlightenment', 'enough', 'ensure', 'enter', 'entering', 'entertainment', 'entrance', 'entrances', 'entry', 'entryway', 'epicsup', 'eras', 'erawan', 'escape', 'esperanto', 'estate', 'eureka', 'euros', 'even', 'evening', 'event', 'events', 'every', 'everyone', 'evict', 'exact', 'examine', 'example', 'exceptionally', 'excursion', 'executive', 'exercise', 'exhibit', 'exhibitions', 'exit', 'expect', 'experience', 'experienced', 'explain', 'explore', 'expressway', 'eye', 'facebook', 'facilities', 'fair', 'fairhaven', 'fall', 'falls', 'falmouth', 'fame', 'families', 'family', 'far', 'farm', 'farmstead', 'farnams', 'favorite', 'fayetteville', 'features', 'featuring', 'february', 'fee', 'fees', 'feet', 'female', 'fen', 'fence', 'fenced', 'fenceline', 'fences', 'fencing', 'ferguson', 'ferry', 'feta', 'fidélité', 'field', 'fields', 'figueira', 'figueres', 'filled', 'film', 'final', 'find', 'finding', 'fine', 'firehat', 'first', 'fisgard', 'fish', 'fit', 'five', 'flaçà', 'flight', 'flixbus', 'floor', 'floors', 'fly', 'fm1764', 'foggy', 'follow', 'following', 'foot', 'footpath', 'formation', 'formations', 'formerly', 'fortress', 'fortresses', 'found', 'fountain', 'france', 'francois', 'free', 'fremont', 'friday', 'fridays', 'friendly', 'front', 'frozen', 'fulfilled', 'fulfilling', 'fully', 'functioning', 'future', 'förstadsgatan', 'gain', 'galeties', 'gallery', 'galway', 'game', 'gamla', 'garages', 'garden', 'gardens', 'gate', 'gates', 'gather', 'gaviota', 'general', 'gentle', 'george', 'get', 'gets', 'getting', 'ghastly', 'gift', 'girl', 'girls', 'girona', 'give', 'gives', 'gladly', 'gladys', 'glasgow', 'glasses', 'glen', 'glenn', 'glimpse', 'globe', 'globes', 'glyphs', 'gmx', 'god', 'going', 'golf', 'gondola', 'gone', 'gong', 'good', 'google', 'gopher', 'gordon', 'gorgeous', 'gospic', 'gotanda', 'gothic', 'government', 'governmental', 'gps', 'grand', 'grande', 'grate', 'grave', 'gravel', 'graveyard', 'great', 'greek', 'green', 'greenhouse', 'grevin10', 'grill', 'grimness', 'ground', 'grounds', 'group', 'groups', 'guardians', 'guests', 'guide', 'guided', 'guides', 'guoliang', 'guoliangcun', 'habsburg', 'haena', 'haggle', 'hail', 'half', 'halfway', 'hall', 'halloween', 'hamburgmuseum', 'hampshire', 'hanakoa', 'handle', 'hanging', 'hanky', 'hanychov', 'happen', 'happening', 'hard', 'harriet', 'harris', 'harrison', 'hart', 'hartbauer', 'hawai', 'hawaiʻi', 'head', 'heading', 'heard', 'heart', 'height', 'helicopter', 'helios', 'help', 'helped', 'herald', 'hermine', 'hexagonal', 'hidden', 'high', 'highly', 'highway', 'hike', 'hikers', 'hiking', 'hilarious', 'hill', 'hills', 'himmelstorp', 'hire', 'hired', 'hishi', 'historical', 'history', 'hobart', 'hogan', 'hole', 'holiday', 'holidays', 'hollow', 'home', 'homes', 'horses', 'hostel', 'hosts', 'hot', 'hotel', 'hour', 'hours', 'house', 'houston', 'however', 'hubert', 'huge', 'huixian', 'hundred', 'hunt', 'hutchinson', 'huxian', 'hwy', 'höganäs', 'ice', 'idea', 'ikebukuro', 'ikegami', 'illegal', 'illinois', 'illustrating', 'images', 'immediately', 'immersive', 'impasse', 'imperial', 'import', 'imposed', 'inclement', 'include', 'included', 'includes', 'including', 'indian', 'indicate', 'info', 'inform', 'information', 'infrastructure', 'initially', 'inside', 'installation', 'instead', 'instructed', 'intellectualism', 'interested', 'interesting', 'interior', 'international', 'interns', 'intersection', 'intersects', 'interstate', 'intimidating', 'invalides', 'involves', 'island', 'isolated', 'issues', 'jack', 'jacobs', 'jaffrey', 'jamaica', 'james', 'japanese', 'jeanne', 'jin', 'joan', 'job', 'john', 'jonquera', 'jump', 'june', 'kalalau', 'kayak', 'kayakers', 'keep', 'kentucky', 'kept', 'kew', 'key', 'kid', 'kidderminster', 'kids', 'kilns', 'kilometer', 'kilometers', 'kind', 'king', 'knowledge', 'knowledgeable', 'known', 'koa', 'königswinter', 'lab', 'lack', 'lad', 'ladd', 'ladder', 'lady', 'lafayette', 'lake', 'lakeview', 'lamp', 'lancaster', 'land', 'landing', 'landmark', 'landscape', 'lane', 'languages', 'large', 'larger', 'largest', 'lark', 'las', 'last', 'lat', 'later', 'latour', 'laurel', 'lead', 'leads', 'least', 'leave', 'leaves', 'led', 'left', 'leg', 'leisure', 'leland', 'leonard', 'less', 'lesser', 'lets', 'levee', 'level', 'levels', 'lexington', 'library', 'liceu', 'lies', 'life', 'lighthouse', 'like', 'lily', 'limit', 'limited', 'limits', 'line', 'lines', 'link', 'linkeroever', 'lipscani', 'liquors', 'listed', 'listen', 'listing', 'lit', 'little', 'live', 'lives', 'llanallgo', 'local', 'locals', 'locate', 'located', 'location', 'locations', 'lockable', 'locked', 'locker', 'lodge', 'london', 'long', 'longer', 'look', 'looking', 'looks', 'loop', 'lose', 'lost', 'lot', 'lots', 'lou', 'low', 'lower', 'lowry', 'ltd', 'lucent', 'lyon', 'made', 'madison', 'madrid', 'magazine', 'main', 'major', 'make', 'makes', 'making', 'mall', 'malmö', 'man', 'manitou', 'mansion', 'many', 'map', 'maps', 'march', 'mariahilfer', 'maritime', 'mark', 'marked', 'marker', 'markers', 'marks', 'marquette', 'mason', 'mass', 'massive', 'mast', 'masterpiece', 'masts', 'material', 'mathematics', 'matter', 'matthew', 'maubourg', 'may', 'maybe', 'maybeck', 'mayo', 'maze', 'meal', 'meander', 'meaning', 'measures', 'medical', 'medicine', 'meeting', 'meets', 'member', 'members', 'memorial', 'memory', 'mentioned', 'menu', 'mess', 'meta', 'metal', 'meters', 'metler', 'metro', 'mexico', 'michigan', 'mid', 'midway', 'might', 'mighty', 'mile', 'miles', 'mill', 'million', 'millstreet', 'min', 'mindful', 'minions', 'minute', 'minutes', 'miss', 'missing', 'moat', 'mobility', 'mochi', 'mochiya', 'models', 'modern', 'moher', 'momias', 'monday', 'mondays', 'montego', 'months', 'montmartre', 'montmartre75009', 'monument', 'monumental', 'moon', 'moonraker', 'moose', 'morning', 'mornings', 'mortimer', 'mosaics', 'motor', 'motorway', 'mount', 'mountain', 'mounted', 'mouth', 'movie', 'mrt', 'msp', 'much', 'mud', 'muddy', 'mural', 'murals', 'museum', 'museumsquartier', 'mushera', 'musherabeg', 'music', 'musical', 'must', 'musée', 'mystery', 'n4150', 'nacional', 'nails', 'name', 'named', 'names', 'nanping', 'narrow', 'nas', 'nasa', 'nashville', 'national', 'native', 'natural', 'nature', 'nazca', 'near', 'nearby', 'nearest', 'nearly', 'necessary', 'need', 'neighborhood', 'neighboring', 'neil', 'nest', 'netherlands', 'never', 'new', 'newcastle', 'next', 'niagara', 'nice', 'night', 'nimis', 'nine', 'nisshodo', 'non', 'nonetheless', 'noon', 'norfolk', 'normally', 'north', 'northeast', 'northumberland', 'northumberlandia', 'northwest', 'not', 'note', 'noting', 'nottingham', 'november', 'nowata', 'numbers', 'nys', 'objects', 'obtain', 'occasion', 'occasionally', 'occupants', 'ocho', 'oconto', 'october', 'offer', 'offered', 'offers', 'office', 'officially', 'often', 'ohio', 'okinawa', 'oklahoma', 'old', 'one', 'oneida', 'online', 'onto', 'open', 'opening', 'opens', 'operate', 'operation', 'operational', 'opportunity', 'opposite', 'opt', 'option', 'options', 'opéra', 'order', 'org', 'organ', 'original', 'osmond', 'ottoman', 'outer', 'outhouse', 'outside', 'outskirts', 'overnight', 'overshadowed', 'package', 'page', 'paid', 'painted', 'paintings', 'pair', 'palace', 'palamós', 'palm', 'palo', 'pamphlets', 'pandora', 'papaya', 'parade', 'paradise', 'parallel', 'parents', 'parfait', 'parish', 'parisnote', 'park', 'parking', 'parkway', 'parlavà', 'part', 'partially', 'particular', 'parts', 'pass', 'passage', 'passenger', 'passengers', 'passersby', 'passing', 'past', 'patagonian', 'path', 'paths', 'patisserie', 'patrol', 'patrolled', 'pauli', 'pauls', 'paved', 'pay', 'paz', 'pearl', 'pecos', 'pedestrian', 'peek', 'pelham', 'penn', 'pennsylvania', 'people', 'per', 'pera', 'pere', 'perfect', 'perfectly', 'performances', 'permission', 'permit', 'permits', 'permitted', 'permitting', 'perpignan', 'person', 'personal', 'pertaining', 'peshtigo', 'petersham', 'petroglyphs', 'petting', 'phase', 'phoenix', 'phone', 'phones', 'photo', 'photograph', 'photographer', 'photographic', 'photographs', 'photography', 'photos', 'phrao', 'physics', 'piazza', 'pick', 'picnics', 'pictographs', 'picture', 'pie', 'pierce', 'pilgrim', 'pinturas', 'pipe', 'pittsburgh', 'place', 'placed', 'places', 'plain', 'plan', 'plane', 'planes', 'plantation', 'plaque', 'plaques', 'plays', 'plaza', 'please', 'plentiful', 'plenty', 'plimoth', 'plum', 'plus', 'pocono', 'point', 'police', 'pond', 'pool', 'pop', 'popular', 'port', 'porta', 'portbou', 'portion', 'possible', 'posted', 'posts', 'potential', 'potties', 'pouch', 'pow', 'powder', 'powered', 'praça', 'pre', 'precarious', 'prefer', 'preorders', 'prepared', 'present', 'presentation', 'preservation', 'preserve', 'price', 'princess', 'princeville', 'prints', 'prior', 'priory', 'privacy', 'private', 'probably', 'problems', 'products', 'programming', 'project', 'prominent', 'promotion', 'property', 'prophecy', 'prophet', 'protecting', 'protection', 'proves', 'provide', 'provides', 'providing', 'provincial', 'pub', 'public', 'publicly', 'puebla', 'pueblo', 'pull', 'purchase', 'puts', 'púbol', 'qew', 'quaker', 'quantities', 'quarries', 'quarry', 'quarter', 'quarterly', 'questions', 'quick', 'quite', 'rabbits', 'radio', 'raeford', 'rail', 'railing', 'railings', 'railroad', 'rain', 'rancho', 'ranges', 'rapid', 'rapids', 'raspberry', 'ravine', 'reach', 'reached', 'reads', 'real', 'really', 'rear', 'reason', 'recently', 'recognized', 'recommend', 'recommended', 'record', 'recorded', 'recreation', 'red', 'reduced', 'reenactment', 'regent', 'regional', 'register', 'regular', 'relics', 'remain', 'remains', 'renfe', 'rent', 'rentals', 'reopen', 'represent', 'representing', 'reproduction', 'require', 'required', 'requires', 'res', 'research', 'resembled', 'reservations', 'reserve', 'reserving', 'reside', 'residence', 'residential', 'resort', 'respect', 'respectful', 'restaurant', 'resting', 'restoration', 'restored', 'restrooms', 'result', 'retreat', 'reward', 'rex', 'richmond', 'ride', 'ridge', 'right', 'rights', 'ring', 'rinkai', 'rios', 'rips', 'rise', 'risk', 'river', 'riverpark', 'riverside', 'rmb', 'road', 'roads', 'roadside', 'roam', 'rock', 'rocks', 'rocky', 'rodoviaria', 'roman', 'roodebeek', 'room', 'rooms', 'rose', 'rossio', 'rotunda', 'rouen', 'rough', 'roughly', 'rouken', 'round', 'roundabout', 'route', 'routes', 'royal', 'rte', 'rub', 'rue', 'run', 'running', 'runs', 'runways', 'rusty', 'ruta', 'rutland', 'sad', 'safe', 'saint', 'salford', 'sanctuary', 'sandusky', 'sandy', 'santo', 'sarfa', 'sarrià', 'sat', 'saturday', 'saturdays', 'savota', 'savoy', 'saw', 'saydel', 'says', 'scale', 'scavenger', 'scenic', 'schedule', 'scheduled', 'scheldt', 'school', 'sconondoa', 'scrap', 'screening', 'sculptors', 'sculpture', 'searching', 'season', 'seasonal', 'seasons', 'seaton', 'seattle', 'second', 'section', 'sections', 'securing', 'security', 'see', 'seeing', 'seems', 'seen', 'seibu', 'sek', 'sell', 'senate', 'sending', 'seniors', 'september', 'served', 'serves', 'service', 'services', 'session', 'set', 'sets', 'seven', 'several', 'sexes', 'shaped', 'shared', 'sheep', 'shelter', 'shine', 'shinjuku', 'shiny', 'shipment', 'shoes', 'shoot', 'shop', 'shopping', 'shore', 'shoreline', 'short', 'shorter', 'shortest', 'shot', 'show', 'shows', 'shuttle', 'side', 'sides', 'sidewalk', 'siegburg', 'sign', 'signage', 'signed', 'signposted', 'signposts', 'signs', 'silent', 'simonetti', 'since', 'single', 'sinks', 'sint', 'sip', 'site', 'sites', 'six', 'size', 'ski', 'skinny', 'sky', 'slaves', 'slippery', 'slippy', 'slope', 'slopes', 'slow', 'slussen', 'small', 'smaller', 'smart', 'smiljan', 'snakes', 'soccer', 'society', 'soi', 'somebody', 'someone', 'sometimes', 'soto', 'sound', 'south', 'southbound', 'southeast', 'southern', 'southwest', 'souvenir', 'space', 'spaces', 'spare', 'sparingly', 'special', 'specified', 'speed', 'spire', 'spiritual', 'split', 'spokane', 'sports', 'spot', 'spots', 'spotted', 'spring', 'springs', 'square', 'staff', 'staffer', 'stags', 'staircase', 'staircases', 'stairs', 'stan', 'stands', 'start', 'starts', 'state', 'states', 'station', 'stationery', 'statue', 'statues', 'stavropoleos', 'stay', 'staying', 'stays', 'steep', 'step', 'steps', 'steve', 'stick', 'stiftgasse', 'still', 'stillwell', 'stockholm', 'stoddart', 'stone', 'stoneyhill', 'stop', 'stopping', 'stops', 'storage', 'store', 'straight', 'strasbourg', 'strasse', 'street', 'streets', 'stretcher', 'strictly', 'striking', 'strong', 'stroudsburg', 'stroudsmoor', 'structure', 'students', 'style', 'styx', 'subject', 'suburbs', 'subway', 'subways', 'suggested', 'suitable', 'suites', 'sullivan', 'summer', 'summery', 'summit', 'sumner', 'sun', 'sunday', 'sundays', 'sunrise', 'sunset', 'sup', 'sure', 'surrounded', 'surrounding', 'surrounds', 'survey', 'sweet', 'swimming', 'syracuse', 'södra', 'tabard', 'tags', 'takanawa', 'take', 'taken', 'takes', 'taking', 'talking', 'tall', 'taos', 'tasting', 'taxi', 'taylors', 'techno', 'teens', 'tell', 'temperatures', 'temporarily', 'ten', 'tend', 'tennessee', 'term', 'terminal', 'terrace', 'terrain', 'texas', 'text', 'thames', 'thank', 'thanking', 'theatrical', 'thing', 'though', 'thought', 'three', 'throughout', 'throughs', 'throws', 'thruway', 'thurs', 'thursdays', 'ticket', 'tickets', 'tide', 'tilburg', 'time', 'times', 'timing', 'toast', 'today', 'toe', 'toed', 'toilets', 'tokorozawa', 'tokyu', 'toll', 'took', 'top', 'torrington', 'tour',

In [83]:
for v in Stem_dict.values():
    term_id['term_id'].append(v)

In [84]:
term_id

{'term_id': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157,
  158,
  159,
  160,
  161,
  162,
  163,
  164,
  165,
  166,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  174,
  175,
  176,
  177,
  178,
  179,
  180,
  181,
  182,
  183,
  184,
  185,
  186,
  187,
  188,
  189,
  190,
  191,
  192,
  193,
  194,
  195,
  196,
  197,
  198,
  199,
  200,
  201,
  202,
  203,
  204,
  205,
  206,
  207,
  208,
  209,
  210,
  211,
  212,
  213,
  214,
  215,
  216,
  217,
  218,
  219,
  220,
  221,
  222,
  223,
  224,
  225,
  226,
  227,
  228,
  229,
  230,
  231,
  232,
  233,
  234,
  235,
  236,
  237,
  238,
  239,
  240,
  241,
  242,
  243,
  244,
  245,
  246,
  247,
  248,
  249,
  250,
  251,
  252,
  253,
  254,
  255,
  256,
  257,
  258,
  259,
  260,
  261,
  262,
  263,
  264,
  265,
  266,
  267,
  268,
  269,
  270,
  271,
  272,
  273,
  274,
  275,
  276,
  277,
  278,
  279,
  280,
  281,
  282,
  283,
  284,
  285,
  286,
  287,
  288,
  289,
  290,
  291,
  292,
  293,
  294,
  295,
  296,
  297,
  298,
  299,
  300,
  301,
  302,
  303,
  304,
  305,
  306,
  307,
  308,
  309,
  310,
  311,
  312,
  313,
  314,
  315,
  316,
  317,
  318,
  319,
  320,
  321,
  322,
  323,
  324,
  325,
  326,
  327,
  328,
  329,
  330,
  331,
  332,
  333,
  334,
  335,
  336,
  337,
  338,
  339,
  340,
  341,
  342,
  343,
  344,
  345,
  346,
  347,
  348,
  349,
  350,
  351,
  352,
  353,
  354,
  355,
  356,
  357,
  358,
  359,
  360,
  361,
  362,
  363,
  364,
  365,
  366,
  367,
  368,
  369,
  370,
  371,
  372,
  373,
  374,
  375,
  376,
  377,
  378,
  379,
  380,
  381,
  382,
  383,
  384,
  385,
  386,
  387,
  388,
  389,
  390,
  391,
  392,
  393,
  394,
  395,
  396,
  397,
  398,
  399,
  400,
  401,
  402,
  403,
  404,
  405,
  406,
  407,
  408,
  409,
  410,
  411,
  412,
  413,
  414,
  415,
  416,
  417,
  418,
  419,
  420,
  421,
  422,
  423,
  424,
  425,
  426,
  427,
  428,
  429,
  430,
  431,
  432,
  433,
  434,
  435,
  436,
  437,
  438,
  439,
  440,
  441,
  442,
  443,
  444,
  445,
  446,
  447,
  448,
  449,
  450,
  451,
  452,
  453,
  454,
  455,
  456,
  457,
  458,
  459,
  460,
  461,
  462,
  463,
  464,
  465,
  466,
  467,
  468,
  469,
  470,
  471,
  472,
  473,
  474,
  475,
  476,
  477,
  478,
  479,
  480,
  481,
  482,
  483,
  484,
  485,
  486,
  487,
  488,
  489,
  490,
  491,
  492,
  493,
  494,
  495,
  496,
  497,
  498,
  499,
  500,
  501,
  502,
  503,
  504,
  505,
  506,
  507,
  508,
  509,
  510,
  511,
  512,
  513,
  514,
  515,
  516,
  517,
  518,
  519,
  520,
  521,
  522,
  523,
  524,
  525,
  526,
  527,
  528,
  529,
  530,
  531,
  532,
  533,
  534,
  535,
  536,
  537,
  538,
  539,
  540,
  541,
  542,
  543,
  544,
  545,
  546,
  547,
  548,
  549,
  550,
  551,
  552,
  553,
  554,
  555,
  556,
  557,
  558,
  559,
  560,
  561,
  562,
  563,
  564,
  565,
  566,
  567,
  568,
  569,
  570,
  571,
  572,
  573,
  574,
  575,
  576,
  577,
  578,
  579,
  580,
  581,
  582,
  583,
  584,
  585,
  586,
  587,
  588,
  589,
  590,
  591,
  592,
  593,
  594,
  595,
  596,
  597,
  598,
  599,
  600,
  601,
  602,
  603,
  604,
  605,
  606,
  607,
  608,
  609,
  610,
  611,
  612,
  613,
  614,
  615,
  616,
  617,
  618,
  619,
  620,
  621,
  622,
  623,
  624,
  625,
  626,
  627,
  628,
  629,
  630,
  631,
  632,
  633,
  634,
  635,
  636,
  637,
  638,
  639,
  640,
  641,
  642,
  643,
  644,
  645,
  646,
  647,
  648,
  649,
  650,
  651,
  652,
  653,
  654,
  655,
  656,
  657,
  658,
  659,
  660,
  661,
  662,
  663,
  664,
  665,
  666,
  667,
  668,
  669,
  670,
  671,
  672,
  673,
  674,
  675,
  676,
  677,
  678,
  679,
  680,
  681,
  682,
  683,
  684,
  685,
  686,
  687,
  688,
  689,
  690,
  691,
  692,
  693,
  694,
  695,
  696,
  697,
  698,
  699,
  700,
  701,
  702,
  703,
  704,
  705,
  706,
  707,
  708,
  709,
  710,
  711,
  712,
  713,
  714,
  715,
  716,
  717,
  718,
  719,
  720,
  721,
  722,
  723,
  724,
  725,
  726,
  727,
  728,
  729,
  730,
  731,
  732,
  733,
  734,
  735,
  736,
  737,
  738,
  739,
  740,
  741,
  742,
  743,
  744,
  745,
  746,
  747,
  748,
  749,
  750,
  751,
  752,
  753,
  754,
  755,
  756,
  757,
  758,
  759,
  760,
  761,
  762,
  763,
  764,
  765,
  766,
  767,
  768,
  769,
  770,
  771,
  772,
  773,
  774,
  775,
  776,
  777,
  778,
  779,
  780,
  781,
  782,
  783,
  784,
  785,
  786,
  787,
  788,
  789,
  790,
  791,
  792,
  793,
  794,
  795,
  796,
  797,
  798,
  799,
  800,
  801,
  802,
  803,
  804,
  805,
  806,
  807,
  808,
  809,
  810,
  811,
  812,
  813,
  814,
  815,
  816,
  817,
  818,
  819,
  820,
  821,
  822,
  823,
  824,
  825,
  826,
  827,
  828,
  829,
  830,
  831,
  832,
  833,
  834,
  835,
  836,
  837,
  838,
  839,
  840,
  841,
  842,
  843,
  844,
  845,
  846,
  847,
  848,
  849,
  850,
  851,
  852,
  853,
  854,
  855,
  856,
  857,
  858,
  859,
  860,
  861,
  862,
  863,
  864,
  865,
  866,
  867,
  868,
  869,
  870,
  871,
  872,
  873,
  874,
  875,
  876,
  877,
  878,
  879,
  880,
  881,
  882,
  883,
  884,
  885,
  886,
  887,
  888,
  889,
  890,
  891,
  892,
  893,
  894,
  895,
  896,
  897,
  898,
  899,
  900,
  901,
  902,
  903,
  904,
  905,
  906,
  907,
  908,
  909,
  910,
  911,
  912,
  913,
  914,
  915,
  916,
  917,
  918,
  919,
  920,
  921,
  922,
  923,
  924,
  925,
  926,
  927,
  928,
  929,
  930,
  931,
  932,
  933,
  934,
  935,
  936,
  937,
  938,
  939,
  940,
  941,
  942,
  943,
  944,
  945,
  946,
  947,
  948,
  949,
  950,
  951,
  952,
  953,
  954,
  955,
  956,
  957,
  958,
  959,
  960,
  961,
  962,
  963,
  964,
  965,
  966,
  967,
  968,
  969,
  970,
  971,
  972,
  973,
  974,
  975,
  976,
  977,
  978,
  979,
  980,
  981,
  982,
  983,
  984,
  985,
  986,
  987,
  988,
  989,
  990,
  991,
  992,
  993,
  994,
  995,
  996,
  997,
  998,
  999,
  1000,
  ...]}

In [ ]:
word = {'word'}

In [34]:
# create an Empty DataFrame object
word_df = pd.DataFrame(word, columns = ['word'])
print(word_df)

           word
0          0091
1           100
2           101
3          10am
4           112
...         ...
2129     zagreb
2130  zhengzhou
2131     zocalo
2132        zoo
2133      ōsaki

[2134 rows x 1 columns]

In [35]:
term_df = pd.DataFrame(term_id, columns = ['term_id'])
print(term_df)

      term_id
0           1
1           2
2           3
3           4
4           5
...       ...
2129     2130
2130     2131
2131     2132
2132     2133
2133     2134

[2134 rows x 1 columns]

In [85]:
vocabulary = pd.concat([word_df,term_df ], axis=1)

In [86]:
vocabulary

           word  term_id
0          0091        1
1           100        2
2           101        3
3          10am        4
4           112        5
...         ...      ...
2129     zagreb     2130
2130  zhengzhou     2131
2131     zocalo     2132
2132        zoo     2133
2133      ōsaki     2134

[2134 rows x 2 columns]

In [87]:
#create a list of documents based on the placeDesc column
doc_list = df[' placeDesc '].values.tolist() 
doc_list

[['along',
  'highway',
  '41',
  'oconto',
  'peshtigo',
  'wisconsin',
  'look',
  'historical',
  'sign',
  'marker',
  'might',
  'miss'],
 ['respect',
  'local',
  'privacy',
  'go',
  'daily',
  'life',
  'places',
  'okinawa',
  'best',
  'accessed',
  'car'],
 ['live',
  'concerts',
  'every',
  'sunday',
  '3',
  'p',
  'may',
  'september',
  'featuring',
  'blend',
  'popular',
  'music',
  'classic',
  'works',
  'typical',
  'carillon',
  'music',
  'check',
  'website',
  'changes',
  'schedule',
  'special',
  'holiday',
  'performances',
  'automated',
  'music',
  'plays',
  'daily',
  'noon',
  '6',
  'p'],
 ['check',
  'parade',
  'website',
  'information',
  'year',
  'date',
  'register',
  'since',
  'streets',
  'closed',
  'parade',
  'best',
  'take',
  'public',
  'transportation',
  'take',
  'q',
  'n',
  'f',
  'train',
  'stillwell',
  'avenue'],
 ['city',
  'chambers',
  'functioning',
  'governmental',
  'building',
  'inform',
  'security',
  'information',
  'desk',
  'interested',
  'viewing',
  'staircases',
  'two',
  'sets',
  'staircase',
  'either',
  'side',
  'access',
  'though',
  'free',
  'limited',
  'able',
  'roam',
  'around',
  'leisure',
  'take',
  'photos',
  'examine',
  'display',
  'cases',
  'containing',
  'various',
  'objects',
  'pertaining',
  'building',
  'history',
  'gain',
  'entry',
  'upper',
  'levels',
  'suggested',
  'take',
  'one',
  'tours',
  'offered',
  'free',
  '45',
  'minute',
  'tour',
  'twice',
  'day',
  '10',
  '30',
  '2',
  '30',
  'p',
  'monday',
  'friday',
  'tours',
  'filled',
  'first',
  'come',
  'first',
  'served',
  'basis',
  'fit',
  'groups',
  '25',
  'people',
  'tours',
  'located',
  'main',
  'entrance',
  'located',
  'george',
  'square',
  'side',
  'building',
  'free',
  'pamphlets',
  'available',
  'give',
  'history',
  'building'],
 ['visit',
  'exit',
  '101',
  'de',
  'soto',
  'ave',
  'go',
  'north',
  'el',
  'rancho',
  'drive',
  'turn',
  'right',
  'old',
  'trapper',
  'lodge',
  'statues',
  'left',
  'past',
  'horses',
  'red',
  'barn',
  'parking',
  'lot',
  '8',
  'note',
  'pierce',
  'college',
  'whose',
  'land',
  'statues',
  'reside',
  'trying',
  'evict',
  'statues',
  'historical',
  'landmark',
  'campus',
  'result',
  'statues',
  'fenced',
  'able',
  'visited',
  'although',
  'one',
  'peek',
  'rips',
  'fencing',
  'material',
  'get',
  'small',
  'glimpse'],
 ['raeford', 'fayetteville', 'nc', 'hwy', '401'],
 ['cahuachi',
  'ceremonial',
  'center',
  'nazca',
  'river',
  'valley',
  '28',
  'km',
  'town',
  'name',
  'many',
  'tours',
  'available',
  'various',
  'tour',
  'companies'],
 ['actually',
  'nice',
  'places',
  'discover',
  'linkeroever',
  'side',
  'scheldt',
  'keep',
  'river',
  'right',
  'follow',
  'trail',
  'half',
  'mile',
  'toward',
  'small',
  'beach',
  'called',
  'sint',
  'annastrand',
  'might',
  'even',
  'lose',
  'grimness',
  'summery',
  'days',
  'also',
  'hilarious',
  '6d',
  'cinema'],
 ['located', 'old', 'quarter', 'st', 'augustine'],
 ['models',
  'located',
  'entryway',
  'mathematics',
  'building',
  'university',
  'arizona',
  'campus'],
 ['lamp',
  'burns',
  'day',
  'night',
  'striking',
  'effect',
  'visit',
  'dark',
  'pop',
  'nearby',
  'savoy',
  'hotel',
  'check',
  'little',
  'museum',
  'features',
  'photos',
  'old',
  'liquors',
  '1969',
  'thank',
  'note',
  'neil',
  'armstrong',
  'nasa',
  'stationery',
  'thanking',
  'staff',
  'sending',
  'champagne',
  'cocktail',
  'glasses',
  'toast',
  'moon',
  'landing'],
 ['tours',
  'church',
  'currently',
  'available',
  '2nd',
  '4th',
  'fridays',
  '12',
  '2',
  'p',
  'worship',
  'services',
  'person',
  'online',
  'via',
  'church',
  'facebook',
  'page',
  'sunday',
  '11',
  'accessibility',
  'questions',
  'prior',
  'visit',
  'please',
  'contact',
  'church',
  'office',
  '615',
  '254',
  '7584',
  'email',
  'info',
  'dpchurch',
  'com'],
 ['abandoned',
  'village',
  'open',
  'public',
  'bridge',
  'entrance',
  'chained',
  'location',
  'longer',
  'open',
  'public',
  'may',
  'reopen',
  'future',
  'check',
  'heading'],
 ['publicly',
  'visible',
  'bit',
  'old',
  'treasury',
  'shelter',
  'tunnel',
  'opening',
  'dry',
  'moat',
  'catch',
  'glimpse',
  'fence',
  'line',
  'pennsylvania',
  'avenue',
  'lat',
  'long',
  'marks',
  'spot'],
 ['want',
  'purchase',
  'frozen',
  'pie',
  'volunteer',
  'sell',
  'one',
  'parish',
  'house',
  'drop',
  'weekday',
  'business',
  'hours',
  'mass',
  '8',
  '30',
  '10',
  '30',
  'sundays'],
 ['midway',
  'currently',
  'artists',
  'compound',
  'rooms',
  'rent',
  'overnight',
  'long',
  'term',
  'stays',
  'expect',
  'show',
  'see',
  'murals',
  'completely',
  'closed',
  'public',
  'week',
  'one',
  'text',
  'hotel',
  'directly',
  '310',
  '827',
  '1748',
  'weekend',
  'stays',
  'gets',
  'fully',
  'booked',
  'october',
  'plan',
  'going',
  'around',
  'halloween',
  'perfect',
  'time',
  'visit',
  'place',
  'plan',
  'ahead',
  'book',
  'room',
  'advance',
  'every',
  'halloween',
  'midway',
  'throws',
  'massive',
  'halloween',
  'event',
  'open',
  'public',
  'called',
  'draculacon',
  'ball'],
 ['easily',
  'walked',
  'central',
  'shopping',
  'district',
  'located',
  'praça',
  'da',
  'figueira',
  'square',
  'easily',
  'accessed',
  'busses',
  '12e',
  '15e',
  '208',
  '714',
  '736',
  '737',
  '760',
  'short',
  'walk',
  'metro',
  'rossio'],
 ['lark',
  'hill',
  'place',
  'accessed',
  'salford',
  'museum',
  'free',
  'enter',
  'museum',
  'occasionally',
  'changes',
  'street',
  'temporarily',
  'represent',
  'eras',
  'history'],
 ['located',
  'lexington',
  'ice',
  'center',
  'sports',
  'complex',
  'take',
  '75',
  'lexington',
  'turn',
  'right',
  'man',
  'war',
  'right',
  'beaver',
  'creek',
  'right',
  'eureka',
  'springs',
  'drive'],
 ['seasonal',
  'museum',
  'open',
  'weekends',
  'april',
  'november',
  'seven',
  'days',
  'week',
  'may',
  'october',
  'want',
  'visit',
  'outside',
  'seasonal',
  'hours',
  'give',
  'call',
  'make',
  'special',
  'arrangements'],
 ['admission',
  'park',
  'free',
  'wary',
  'many',
  'steep',
  'cliffs',
  'visiting',
  'small',
  'children'],
 ['spot',
  'east',
  '15',
  'head',
  'north',
  'butte',
  'see',
  'lady',
  'time',
  'distance',
  'big',
  'bring',
  'binoculars',
  'plan',
  'see',
  'roadside',
  'plus',
  'lit',
  'night',
  'well',
  'worth',
  'wait',
  'june',
  'october',
  'scheduled',
  'tours',
  'directly',
  'site',
  'including',
  'lady',
  'chapel',
  'wall',
  'women',
  'monument',
  'get',
  'close',
  'private',
  'vehicles',
  'permitted',
  'taking',
  'tour',
  'bus',
  'traveling',
  'gift',
  'shop',
  'butte',
  'plaza',
  'mall',
  '3100',
  'harrison',
  'ave',
  'round',
  'trip',
  'takes',
  'two',
  'half',
  'hours',
  'weather',
  'permitting',
  'make',
  'reservations',
  'call',
  '406',
  '782',
  '1221',
  'check',
  'website',
  'admission',
  'fees',
  'details'],
 ['currently',
  'open',
  'public',
  'however',
  'congressional',
  'staffer',
  'including',
  'interns',
  'take',
  'guests',
  'staff',
  'heard',
  'bathtubs',
  'uncertain',
  'location',
  'prepared',
  'crazy',
  'looks',
  'ask',
  'take',
  'senate',
  'bathtubs'],
 ['ampelparchen',
  'seen',
  'pedestrian',
  'crossings',
  'throughout',
  'vienna',
  'city',
  'center'],
 ['check',
  'hours',
  'visiting',
  'bring',
  'camera',
  'visit',
  'gallery',
  'purchase',
  'tickets',
  'museum'],
 ['saw',
  'mill',
  'river',
  'parkway',
  'north',
  'take',
  'exit',
  '9',
  'executive',
  'boulevard',
  'make',
  'left',
  'turn',
  'onto',
  'broadway',
  'grounds',
  'left'],
 ['admission',
  'esperanto',
  'museum',
  'also',
  'includes',
  'admission',
  'globe',
  'museum',
  'world',
  'largest',
  'collection',
  'globes',
  'upper',
  'level',
  'building'],
 ['town',
  'paradise',
  'follow',
  'n',
  'whitefish',
  'point',
  'rd',
  'north',
  '11',
  'miles',
  'go'],
 ['free',
  'museum',
  'open',
  '10',
  '4',
  'p',
  'tuesday',
  'friday',
  '9',
  '3',
  'p',
  'saturdays',
  'architect',
  'james',
  'dakin',
  'designed',
  'prominent',
  'gothic',
  'style',
  'building',
  'reason',
  'must',
  'visit',
  'see',
  'gorgeous',
  'dome',
  'charge',
  'tour',
  'building',
  'use',
  'audio',
  'guide',
  'even',
  'children',
  'room',
  'minions',
  'spare',
  '3',
  'per',
  'person',
  'worth',
  'see',
  '4d',
  'immersive',
  'theatrical',
  'presentation'],
 ['located',
  'east',
  'side',
  'laurel',
  'canyon',
  'blvd',
  'south',
  'chandler',
  'look',
  'plain',
  'white',
  'office',
  'car',
  'rear',
  'end',
  'window',
  'open',
  'monday',
  'friday',
  '8',
  '30',
  '6',
  '00',
  'pm',
  'free',
  'admission'],
 ['closest',
  'metro',
  'drassanes',
  'l3',
  'also',
  'include',
  'wine',
  'tasting',
  'visit',
  'column'],
 ['farm',
  'offers',
  'tours',
  'restaurant',
  'plenty',
  'delicious',
  'options',
  'including',
  'raspberry',
  'cream',
  'parfait',
  'made',
  'moose',
  'feta',
  'cheese'],
 ['best',
  'places',
  'view',
  'caves',
  'city',
  'caves',
  'attraction',
  'broadmarsh',
  'centre',
  'brewhouse',
  'yard',
  'tours',
  'mortimer',
  'hole',
  'conducted',
  'throughout',
  'year',
  'virtual',
  'cave',
  'fly',
  'throughs',
  'available',
  'nottingham',
  'caves',
  'survey',
  'website'],
 ['island',
  'near',
  'hi',
  'hostel',
  'riverside',
  'drive',
  'bridge',
  'walkway',
  'island',
  'must',
  'use',
  'non',
  'powered',
  'watercraft',
  'get',
  'swimming',
  'lake',
  'illegal',
  'many',
  'kayak',
  'sup',
  'canoe',
  'rentals',
  'lady',
  'bird',
  'lake',
  'writing',
  'closest',
  'epicsup',
  'rentals'],
 ['signs',
  'california',
  'highway',
  '99',
  'earlimart',
  'direct',
  'park',
  '15',
  'minutes',
  'earlimart'],
 ['sculpture', 'storage', 'right', 'restored', 'original', 'artist'],
 ['metro',
  'latour',
  'maubourg',
  'varenne',
  'invalides',
  'st',
  'francois',
  'xavier'],
 ['right', 'stavropoleos', 'lipscani', 'streets'],
 ['good',
  'place',
  'start',
  'explore',
  'styx',
  'valley',
  'mt',
  'field',
  'national',
  'park',
  'office',
  'one',
  'hour',
  'drive',
  'hobart',
  'via',
  'new',
  'norfolk'],
 ['check',
  'website',
  'open',
  'hours',
  'make',
  'appointment',
  'vr',
  'kid',
  'friendly'],
 ['fair',
  'vermont',
  'border',
  'new',
  'york',
  '15',
  'miles',
  'west',
  'rutland',
  '65',
  'miles',
  'south',
  'burlington',
  'allen',
  'house',
  'directly',
  'across',
  'center',
  'village',
  'green',
  '12',
  'w',
  'park',
  'place',
  'adams',
  'house',
  'southern',
  'end',
  'corner',
  'park',
  'place',
  'adams',
  'street'],
 ['257', 'stroudsmoor', 'rd', 'stroudsburg', 'pa', '18360'],
 ['accessible', 'car', 'madrid'],
 ['according',
  'vermont',
  'quarries',
  'corporation',
  'tours',
  'danby',
  'quarry',
  'available',
  'public',
  'tours',
  'might',
  'available',
  'special',
  'circumstances',
  'case',
  'try',
  'contacting',
  'website'],
 ['site',
  'part',
  'alcatel',
  'lucent',
  'research',
  'lab',
  'specified',
  'address',
  'antenna',
  'top',
  'hill',
  'accessible',
  'road',
  'going',
  'hill',
  'typically',
  'open',
  'general',
  'work',
  'hours'],
 ['site',
  'open',
  'year',
  'round',
  'access',
  'inside',
  'buildings',
  'winter',
  'trail',
  '1',
  '2',
  'mile',
  'easy',
  'walking',
  'starts',
  '7',
  'miles',
  'north',
  'grand',
  'lake',
  'entrance',
  'rocky',
  'mountain',
  'national',
  'park'],
 ['visitors',
  'museum',
  'worth',
  'noting',
  '2nd',
  '3rd',
  'floors',
  'wheelchair',
  'accessible',
  'admission',
  '5',
  'per',
  'person',
  '15',
  'families',
  'six',
  'members',
  'open',
  'mid',
  'april',
  'october',
  'hours',
  'thurs',
  '10am',
  '4pm',
  'friday',
  '10am',
  '4pm',
  'sat',
  '10am',
  '5',
  'pm',
  'sun',
  '10am',
  '5',
  'pm',
  'september',
  'museum',
  'hosts',
  'pow',
  'wow',
  'proves',
  'great',
  'place',
  'family',
  'picnics'],
 ['guided',
  'tours',
  'better',
  'access',
  'available',
  'two',
  'boat',
  'services'],
 ['2',
  '5',
  '3',
  'hour',
  'train',
  'ride',
  'berlin',
  'easy',
  'take',
  'ice',
  'regional',
  'trains',
  'get',
  'also',
  'option',
  'taking',
  'bus',
  'ex',
  'flixbus'],
 ['located', '¼', 'mile', 'south', 'warm', 'springs', 'highway', '85'],
 ['head',
  'main',
  'doors',
  'near',
  'neighboring',
  'basilica',
  'staircase',
  'right',
  'take',
  'museum',
  'charge',
  'five',
  'euros'],
 ['houston',
  'memorial',
  'park',
  'easily',
  'reached',
  'taking',
  'interstate',
  '45',
  'south',
  'fm',
  '1764',
  'fm1764',
  'lowry',
  'expressway',
  'main',
  'road',
  'texas',
  'city',
  'park',
  'reached',
  'making',
  'left',
  '29th',
  'street',
  'bayview',
  'may',
  'reach',
  'park',
  'directly',
  'taking',
  '146',
  'southbound',
  '197',
  'loop',
  '25th',
  'avenue',
  'memorial',
  'park',
  'closes',
  '7pm'],
 ['mid',
  'way',
  'along',
  'glen',
  'osmond',
  'road',
  '15',
  'minutes',
  'drive',
  'adelaide',
  'hills',
  'city'],
 ['near',
  'bar',
  'wooden',
  'staircase',
  'leads',
  'second',
  'floor',
  'dining',
  'room',
  'prefer',
  'get',
  'meal'],
 ['walk',
  'bicycle',
  'north',
  'bike',
  'path',
  'mile',
  'burlington',
  'boathouse',
  'foot',
  'main',
  'street',
  'come',
  'lakeview',
  'cemetery',
  'right',
  'see',
  'steep',
  'footpath',
  'following',
  'edge',
  'ravine',
  'right',
  'follow',
  'footpath',
  'top',
  'bluff',
  'continue',
  'another',
  '100',
  'yards',
  'past',
  'open',
  'field',
  'left'],
 ['located',
  'falmouth',
  'jamaica',
  'north',
  'shore',
  'island',
  'a1',
  '20',
  'minutes',
  'east',
  'montego',
  'bay',
  '45',
  'minutes',
  'west',
  'ocho',
  'rios'],
 ['enter',
  'bronx',
  'community',
  'college',
  'gates',
  'hall',
  'fame',
  'terrace',
  'college',
  'offers',
  'free',
  'tours',
  'sure',
  'call'],
 ['best',
  'time',
  'visit',
  'summer',
  'fall',
  'warned',
  'town',
  'may',
  'resembled',
  'muddy',
  'mess',
  'wet',
  'seasons'],
 ['north',
  '34th',
  'street',
  '250',
  'feet',
  'east',
  'intersection',
  'fremont',
  'avenue',
  'north',
  'fremont',
  'section',
  'seattle'],
 ['site',
  'located',
  'slopes',
  'mushera',
  'musherabeg',
  'mountain',
  'outside',
  'millstreet',
  'country',
  'park',
  'eleven',
  'kilometers',
  'millstreet',
  'county',
  'cork',
  'follow',
  'signs',
  'millstreet',
  'toward',
  'millstreet',
  'country',
  'park',
  'go',
  'past',
  'park',
  'entrance',
  'turn',
  'right',
  '300',
  'meters',
  'road',
  'entrance',
  'site',
  'left'],
 ['ali',
  'buried',
  'section',
  'u',
  'cemetery',
  'follow',
  'green',
  'path',
  'directly',
  'grave'],
 ['take',
  'city',
  'bus',
  'marked',
  'las',
  'momias',
  'ask',
  'bus',
  'driver',
  'point',
  'street',
  'leads',
  'museum',
  'walk',
  'uphill',
  'see',
  'big',
  'stone',
  'wall',
  'without',
  'windows',
  'go',
  'straight',
  'museum',
  'turn',
  'right',
  'follow',
  'wall',
  'end',
  'see',
  'lot',
  'souvenir',
  'stands',
  'turn',
  'left',
  'walk',
  'find',
  'ticket',
  'window',
  'want',
  'visit',
  'cemetery',
  'first',
  'turn',
  'big',
  'stone',
  'wall',
  'instead',
  'walk',
  'uphill',
  'little',
  'see',
  'entrance',
  'right',
  'graveyard',
  'worth',
  'look',
  'like',
  'kind',
  'thing',
  'cannot',
  'get',
  'museum',
  'cemetery',
  'must',
  'walk',
  'around',
  'side',
  'museum',
  'actually',
  'underneath',
  'graveyard',
  'take',
  'short',
  'tour',
  'trip',
  'part',
  'general',
  'tour',
  'city',
  'enough',
  'time',
  'appreciate',
  'ghastly',
  'cadavers',
  'instead',
  'make',
  'sure',
  'least',
  'hour',
  'two',
  'walk',
  'around'],
 ['cave',
  'open',
  'april',
  'september',
  'weekends',
  'bank',
  'holidays',
  'tours',
  'must',
  'booked',
  'online'],
 ['admission',
  'free',
  'exhibit',
  'open',
  '9',
  '00',
  '5',
  '00',
  'p',
  'please',
  'call',
  'ahead',
  '731',
  '855',
  '2013',
  'large',
  'groups'],
 ['outhouse',
  'located',
  'town',
  '575',
  'south',
  '46',
  'north',
  'pere',
  'marquette',
  'rail',
  'trail'],
 ['located',
  'approximately',
  '0',
  '21',
  'miles',
  'south',
  'entrance',
  'belgrade',
  'crow',
  'visible',
  'left',
  'side',
  'highway',
  '71',
  '45',
  '4442',
  '95',
  '0091'],
 ['members',
  'annual',
  'dues',
  'give',
  'access',
  'programming',
  'anyone',
  'free',
  'visit',
  'library',
  'paid',
  'parking',
  'available',
  'nearby',
  'parking',
  'garages',
  'street'],
 ['attend',
  'silent',
  'film',
  'screening',
  'authentic',
  'classic',
  'movie',
  'experience',
  'mighty',
  'wurlitzer',
  'pipe',
  'organ',
  'providing',
  'musical',
  'accompaniment'],
 ['walk',
  'statue',
  'time',
  'though',
  'aware',
  'crowds',
  'tend',
  'gather',
  'around',
  'shiny',
  'toe',
  'advised',
  'rub',
  'statue',
  'causes',
  'damage',
  'wear',
  'sure',
  'take',
  'peek',
  'behind',
  'statue',
  'get',
  'glimpse',
  'sandy',
  'stoddart',
  'depiction',
  'greek',
  'god',
  'helios',
  'illustrating',
  'concept',
  'enlightenment',
  'head',
  'surrounded',
  'nest',
  'snakes',
  'representing',
  'anti',
  'intellectualism'],
 ['view',
  'reproduction',
  'paintings',
  'listen',
  'pre',
  'recorded',
  'tour',
  'need',
  'pay',
  'front',
  'desk',
  'staff',
  '3',
  'per',
  'person',
  'depending',
  'timing',
  'could',
  'wait',
  'conference',
  'room',
  'could',
  'use',
  'consider',
  'calling',
  'ahead',
  'pull',
  'curtain'],
 ['free',
  'live',
  'entertainment',
  'weekends',
  'kids',
  'get',
  'free',
  'firehat'],
 ['us',
  '90',
  'nys',
  'thruway',
  'exit',
  '55',
  'route',
  '219',
  'route',
  '219',
  'south',
  'end',
  'approx',
  '24',
  '5',
  'miles',
  'left',
  '0',
  '2',
  'miles',
  'right',
  'onto',
  'continuation',
  '219',
  'south',
  'approx',
  '8',
  'miles',
  '219',
  'ashford',
  'hollow',
  'speed',
  'limit',
  '45',
  'right',
  'onto',
  'ahrens',
  'road',
  'carsons',
  'ashford',
  'house',
  'park',
  'sign',
  'corner',
  'stay',
  'straight',
  'approx',
  '2',
  '7',
  'miles',
  'county',
  'road',
  '75',
  'mill',
  'valley',
  'rd',
  'turn',
  'left',
  'go',
  '1',
  '5',
  'miles',
  'park',
  'entrance',
  'left',
  'two',
  'distinct',
  'sections',
  'park',
  'directions',
  'main',
  'site',
  'plaques',
  'information',
  'admission',
  'fees',
  'trail',
  'maps',
  'site',
  'mill',
  'valley',
  'rd',
  'closer',
  'ashton',
  'hollow',
  'smaller',
  'parking',
  'lot',
  'bathrooms',
  'port',
  'potties',
  'take',
  'photos',
  'trail',
  'maps',
  'consult',
  'trail',
  'website',
  'set',
  'trail',
  'maps',
  'posted',
  'sparingly',
  'names',
  'many',
  'sculptors',
  'also',
  'shared',
  'sparingly',
  'bring',
  'water',
  'long',
  'climbs',
  'hot',
  'days',
  'closes',
  'year',
  '31st',
  'october'],
 ['gps',
  'coordinates',
  'lead',
  'train',
  'station',
  'upon',
  'arriving',
  'fairhaven',
  'may',
  'park',
  'near',
  'amtrak',
  'station',
  'walk',
  'main',
  'part',
  'town',
  'along',
  'harris',
  'avenue',
  'may',
  'park',
  '12th',
  'harris',
  'walk',
  'toward',
  'amtrak',
  'station',
  'markers',
  'ground',
  'sure',
  'keep',
  'eye'],
 ['short',
  'walk',
  'ōsaki',
  'station',
  'yamanote',
  'rinkai',
  'lines',
  'less',
  'mile',
  'gotanda',
  'station',
  'asakusa',
  'yamanote',
  'tokyu',
  'ikegami',
  'lines',
  'less',
  'mile',
  'takanawa',
  'dai',
  'station',
  'asakusa',
  'line',
  'locate',

In [90]:
# instantiate the vectorizer object
countvectorizer = CountVectorizer(analyzer= 'word', stop_words='english')
tfidfvectorizer = TfidfVectorizer(analyzer='word',stop_words= 'english')

In [101]:
for i in range(len(doc_list)):
    count_wm = countvectorizer.fit_transform(doc_list[i])
    tfidf_wm = tfidfvectorizer.fit_transform(doc_list[i])
    count_tokens = countvectorizer.get_feature_names_out()
    tfidf_tokens = tfidfvectorizer.get_feature_names_out()

In [102]:
df_countvect = pd.DataFrame(data = count_wm.toarray(),columns = count_tokens)
df_tfidfvect = pd.DataFrame(data = tfidf_wm.toarray(),columns = tfidf_tokens)
print("Count Vectorizer\n")
print(df_countvect)
print("\nTD-IDF Vectorizer\n")
print(df_tfidfvect)

Count Vectorizer

    24  advance  appointment  collection  com  contact  email  hours  make  \
0    0        0            0           1    0        0      0      0     0
1    0        0            0           0    0        0      0      1     0
2    0        0            0           0    0        0      0      0     0
3    0        0            0           0    0        0      0      0     0
4    0        0            0           0    0        0      0      0     0
5    0        0            0           0    0        0      0      0     0
6    0        0            0           0    0        0      0      0     0
7    0        0            0           0    0        0      0      0     0
8    0        0            1           0    0        0      0      0     0
9    0        0            0           0    0        0      0      0     1
10   0        0            1           0    0        0      0      0     0
11   0        0            0           0    0        1      0      0     0
12   0        0            0           0    0        0      0      0     0
13   0        0            0           0    0        0      0      0     0
14   1        0            0           0    0        0      0      0     0
15   0        0            0           0    0        0      0      1     0
16   0        1            0           0    0        0      0      0     0
17   0        0            0           0    0        0      1      0     0
18   0        0            0           0    0        0      0      0     0
19   0        0            0           0    0        0      0      0     0
20   0        0            0           0    0        0      0      0     0
21   0        0            0           0    1        0      0      0     0

    nc  rr  simonetti  thursdays  tuesdays  vince  vsimonetti
0    0   0          0          0         0      0           0
1    0   0          0          0         0      0           0
2    0   0          0          0         1      0           0
3    0   0          0          1         0      0           0
4    0   0          0          0         0      0           0
5    0   0          0          0         0      0           0
6    0   0          0          0         0      0           0
7    0   0          0          0         0      0           0
8    0   0          0          0         0      0           0
9    0   0          0          0         0      0           0
10   0   0          0          0         0      0           0
11   0   0          0          0         0      0           0
12   0   0          0          0         0      1           0
13   0   0          1          0         0      0           0
14   0   0          0          0         0      0           0
15   0   0          0          0         0      0           0
16   0   0          0          0         0      0           0
17   0   0          0          0         0      0           0
18   0   0          0          0         0      0           1
19   1   0          0          0         0      0           0
20   0   1          0          0         0      0           0
21   0   0          0          0         0      0           0

TD-IDF Vectorizer

     24  advance  appointment  collection  com  contact  email  hours  make  \
0   0.0      0.0          0.0         1.0  0.0      0.0    0.0    0.0   0.0
1   0.0      0.0          0.0         0.0  0.0      0.0    0.0    1.0   0.0
2   0.0      0.0          0.0         0.0  0.0      0.0    0.0    0.0   0.0
3   0.0      0.0          0.0         0.0  0.0      0.0    0.0    0.0   0.0
4   0.0      0.0          0.0         0.0  0.0      0.0    0.0    0.0   0.0
5   0.0      0.0          0.0         0.0  0.0      0.0    0.0    0.0   0.0
6   0.0      0.0          0.0         0.0  0.0      0.0    0.0    0.0   0.0
7   0.0      0.0          0.0         0.0  0.0      0.0    0.0    0.0   0.0
8   0.0      0.0          1.0         0.0  0.0      0.0    0.0    0.0   0.0
9   0.0      0.0          0.0         0.0  0.0      0.0    0.0    0.0   1.0
10  0.0      0.0          1.0         0.0  0.0      0.0    0.0    0.0   0.0
11  0.0      0.0          0.0         0.0  0.0      1.0    0.0    0.0   0.0
12  0.0      0.0          0.0         0.0  0.0      0.0    0.0    0.0   0.0
13  0.0      0.0          0.0         0.0  0.0      0.0    0.0    0.0   0.0
14  1.0      0.0          0.0         0.0  0.0      0.0    0.0    0.0   0.0
15  0.0      0.0          0.0         0.0  0.0      0.0    0.0    1.0   0.0
16  0.0      1.0          0.0         0.0  0.0      0.0    0.0    0.0   0.0
17  0.0      0.0          0.0         0.0  0.0      0.0    1.0    0.0   0.0
18  0.0      0.0          0.0         0.0  0.0      0.0    0.0    0.0   0.0
19  0.0      0.0          0.0         0.0  0.0      0.0    0.0    0.0   0.0
20  0.0      0.0          0.0         0.0  0.0      0.0    0.0    0.0   0.0
21  0.0      0.0          0.0         0.0  1.0      0.0    0.0    0.0   0.0

     nc   rr  simonetti  thursdays  tuesdays  vince  vsimonetti
0   0.0  0.0        0.0        0.0       0.0    0.0         0.0
1   0.0  0.0        0.0        0.0       0.0    0.0         0.0
2   0.0  0.0        0.0        0.0       1.0    0.0         0.0
3   0.0  0.0        0.0        1.0       0.0    0.0         0.0
4   0.0  0.0        0.0        0.0       0.0    0.0         0.0
5   0.0  0.0        0.0        0.0       0.0    0.0         0.0
6   0.0  0.0        0.0        0.0       0.0    0.0         0.0
7   0.0  0.0        0.0        0.0       0.0    0.0         0.0
8   0.0  0.0        0.0        0.0       0.0    0.0         0.0
9   0.0  0.0        0.0        0.0       0.0    0.0         0.0
10  0.0  0.0        0.0        0.0       0.0    0.0         0.0
11  0.0  0.0        0.0        0.0       0.0    0.0         0.0
12  0.0  0.0        0.0        0.0       0.0    1.0         0.0
13  0.0  0.0        1.0        0.0       0.0    0.0         0.0
14  0.0  0.0        0.0        0.0       0.0    0.0         0.0
15  0.0  0.0        0.0        0.0       0.0    0.0         0.0
16  0.0  0.0        0.0        0.0       0.0    0.0         0.0
17  0.0  0.0        0.0        0.0       0.0    0.0         0.0
18  0.0  0.0        0.0        0.0       0.0    0.0         1.0
19  1.0  0.0        0.0        0.0       0.0    0.0         0.0
20  0.0  1.0        0.0        0.0       0.0    0.0         0.0
21  0.0  0.0        0.0        0.0       0.0    0.0         0.0