In [58]:
import pandas as pd
import polars as pl

### Series

Pandas

In [59]:
"""find more information about command"""
print(help(pd.Series.loc))

Help on property:

    Access a group of rows and columns by label(s) or a boolean array.

    ``.loc[]`` is primarily label based, but may also be used with a
    boolean array.

    Allowed inputs are:

    - A single label, e.g. ``5`` or ``'a'``, (note that ``5`` is
      interpreted as a *label* of the index, and **never** as an
      integer position along the index).
    - A list or array of labels, e.g. ``['a', 'b', 'c']``.
    - A slice object with labels, e.g. ``'a':'f'``.

      .. warning:: Note that contrary to usual python slices, **both** the
          start and the stop are included

    - A boolean array of the same length as the axis being sliced,
      e.g. ``[True, False, True]``.
    - An alignable boolean Series. The index of the key will be aligned before
      masking.
    - An alignable Index. The Index of the returned selection will be the input.
    - A ``callable`` function with one argument (the calling Series or
      DataFrame) and that returns valid output for indexing (one of the above)

    See more at :ref:`Selection by Label <indexing.label>`.

    Raises
    ------
    KeyError
        If any items are not found.
    IndexingError
        If an indexed key is passed and its index is unalignable to the frame index.

    See Also
    --------
    DataFrame.at : Access a single value for a row/column label pair.
    DataFrame.iloc : Access group of rows and columns by integer position(s).
    DataFrame.xs : Returns a cross-section (row(s) or column(s)) from the
                   Series/DataFrame.
    Series.loc : Access group of values using labels.

    Examples
    --------
    **Getting values**

    >>> df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
    ...                   index=['cobra', 'viper', 'sidewinder'],
    ...                   columns=['max_speed', 'shield'])
    >>> df
                max_speed  shield
    cobra               1       2
    viper               4       5
    sidewinder          7       8

    Single label. Note this returns the row as a Series.

    >>> df.loc['viper']
    max_speed    4
    shield       5
    Name: viper, dtype: int64

    List of labels. Note using ``[[]]`` returns a DataFrame.

    >>> df.loc[['viper', 'sidewinder']]
                max_speed  shield
    viper               4       5
    sidewinder          7       8

    Single label for row and column

    >>> df.loc['cobra', 'shield']
    2

    Slice with labels for row and single label for column. As mentioned
    above, note that both the start and stop of the slice are included.

    >>> df.loc['cobra':'viper', 'max_speed']
    cobra    1
    viper    4
    Name: max_speed, dtype: int64

    Boolean list with the same length as the row axis

    >>> df.loc[[False, False, True]]
                max_speed  shield
    sidewinder          7       8

    Alignable boolean Series:

    >>> df.loc[pd.Series([False, True, False],
    ...                  index=['viper', 'sidewinder', 'cobra'])]
                         max_speed  shield
    sidewinder          7       8

    Index (same behavior as ``df.reindex``)

    >>> df.loc[pd.Index(["cobra", "viper"], name="foo")]
           max_speed  shield
    foo
    cobra          1       2
    viper          4       5

    Conditional that returns a boolean Series

    >>> df.loc[df['shield'] > 6]
                max_speed  shield
    sidewinder          7       8

    Conditional that returns a boolean Series with column labels specified

    >>> df.loc[df['shield'] > 6, ['max_speed']]
                max_speed
    sidewinder          7

    Multiple conditional using ``&`` that returns a boolean Series

    >>> df.loc[(df['max_speed'] > 1) & (df['shield'] < 8)]
                max_speed  shield
    viper          4       5

    Multiple conditional using ``|`` that returns a boolean Series

    >>> df.loc[(df['max_speed'] > 4) | (df['shield'] < 5)]
                max_speed  shield
    cobra               1       2
    sidewinder          7       8

    Please ensure that each condition is wrapped in parentheses ``()``.
    See the :ref:`user guide<indexing.boolean>`
    for more details and explanations of Boolean indexing.

    .. note::
        If you find yourself using 3 or more conditionals in ``.loc[]``,
        consider using :ref:`advanced indexing<advanced.advanced_hierarchical>`.

        See below for using ``.loc[]`` on MultiIndex DataFrames.

    Callable that returns a boolean Series

    >>> df.loc[lambda df: df['shield'] == 8]
                max_speed  shield
    sidewinder          7       8

    **Setting values**

    Set value for all items matching the list of labels

    >>> df.loc[['viper', 'sidewinder'], ['shield']] = 50
    >>> df
                max_speed  shield
    cobra               1       2
    viper               4      50
    sidewinder          7      50

    Set value for an entire row

    >>> df.loc['cobra'] = 10
    >>> df
                max_speed  shield
    cobra              10      10
    viper               4      50
    sidewinder          7      50

    Set value for an entire column

    >>> df.loc[:, 'max_speed'] = 30
    >>> df
                max_speed  shield
    cobra              30      10
    viper              30      50
    sidewinder         30      50

    Set value for rows matching callable condition

    >>> df.loc[df['shield'] > 35] = 0
    >>> df
                max_speed  shield
    cobra              30      10
    viper               0       0
    sidewinder          0       0

    Add value matching location

    >>> df.loc["viper", "shield"] += 5
    >>> df
                max_speed  shield
    cobra              30      10
    viper               0       5
    sidewinder          0       0

    Setting using a ``Series`` or a ``DataFrame`` sets the values matching the
    index labels, not the index positions.

    >>> shuffled_df = df.loc[["viper", "cobra", "sidewinder"]]
    >>> df.loc[:] += shuffled_df
    >>> df
                max_speed  shield
    cobra              60      20
    viper               0      10
    sidewinder          0       0

    **Getting values on a DataFrame with an index that has integer labels**

    Another example using integers for the index

    >>> df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
    ...                   index=[7, 8, 9], columns=['max_speed', 'shield'])
    >>> df
       max_speed  shield
    7          1       2
    8          4       5
    9          7       8

    Slice with integer labels for rows. As mentioned above, note that both
    the start and stop of the slice are included.

    >>> df.loc[7:9]
       max_speed  shield
    7          1       2
    8          4       5
    9          7       8

    **Getting values with a MultiIndex**

    A number of examples using a DataFrame with a MultiIndex

    >>> tuples = [
    ...     ('cobra', 'mark i'), ('cobra', 'mark ii'),
    ...     ('sidewinder', 'mark i'), ('sidewinder', 'mark ii'),
    ...     ('viper', 'mark ii'), ('viper', 'mark iii')
    ... ]
    >>> index = pd.MultiIndex.from_tuples(tuples)
    >>> values = [[12, 2], [0, 4], [10, 20],
    ...           [1, 4], [7, 1], [16, 36]]
    >>> df = pd.DataFrame(values, columns=['max_speed', 'shield'], index=index)
    >>> df
                         max_speed  shield
    cobra      mark i           12       2
               mark ii           0       4
    sidewinder mark i           10      20
               mark ii           1       4
    viper      mark ii           7       1
               mark iii         16      36

    Single label. Note this returns a DataFrame with a single index.

    >>> df.loc['cobra']
             max_speed  shield
    mark i          12       2
    mark ii          0       4

    Single index tuple. Note this returns a Series.

    >>> df.loc[('cobra', 'mark ii')]
    max_speed    0
    shield       4
    Name: (cobra, mark ii), dtype: int64

    Single label for row and column. Similar to passing in a tuple, this
    returns a Series.

    >>> df.loc['cobra', 'mark i']
    max_speed    12
    shield        2
    Name: (cobra, mark i), dtype: int64

    Single tuple. Note using ``[[]]`` returns a DataFrame.

    >>> df.loc[[('cobra', 'mark ii')]]
                   max_speed  shield
    cobra mark ii          0       4

    Single tuple for the index with a single label for the column

    >>> df.loc[('cobra', 'mark i'), 'shield']
    2

    Slice from index tuple to single label

    >>> df.loc[('cobra', 'mark i'):'viper']
                         max_speed  shield
    cobra      mark i           12       2
               mark ii           0       4
    sidewinder mark i           10      20
               mark ii           1       4
    viper      mark ii           7       1
               mark iii         16      36

    Slice from index tuple to index tuple

    >>> df.loc[('cobra', 'mark i'):('viper', 'mark ii')]
                        max_speed  shield
    cobra      mark i          12       2
               mark ii          0       4
    sidewinder mark i          10      20
               mark ii          1       4
    viper      mark ii          7       1

    Please see the :ref:`user guide<advanced.advanced_hierarchical>`
    for more details and explanations of advanced indexing.

None

In [60]:
"""Series"""
s_pd = pd.Series([3, -5, 7, 4],  index=['a',  'b',  'c',  'd'])
s_pd2 = pd.Series([7, -2, 3],  index=['a',  'c',  'd'])
print(s_pd['b'])
print(s_pd[(s_pd < -1) | (s_pd > 2)])
s_pdo = s_pd.drop(['a',  'c'])
print(s_pdo)

-5
a    3
b   -5
c    7
d    4
dtype: int64
b   -5
d    4
dtype: int64

In [61]:
print(s_pd + s_pd2)                    #only show shared columns
print(s_pd.add(s_pd2, fill_value=0))
print(s_pd.sub(s_pd2, fill_value=2))
print(s_pd.div(s_pd2, fill_value=4))
print(s_pd.mul(s_pd2, fill_value=3))

a    10.0
b     NaN
c     5.0
d     7.0
dtype: float64
a    10.0
b    -5.0
c     5.0
d     7.0
dtype: float64
a   -4.0
b   -7.0
c    9.0
d    1.0
dtype: float64
a    0.428571
b   -1.250000
c   -3.500000
d    1.333333
dtype: float64
a    21.0
b   -15.0
c   -14.0
d    12.0
dtype: float64

## Dataframe

In [62]:
def get_body_data():
  data = {'weight': [   70,   77,   77,   77,   80,   70, None, 65, 55, 43, 86, 91, 82],
          'height': [ 2100,  185,  190,  170,  155,  None,  170, 175, 160, 153, 179, 183, 190]}
  return data

def bmi_calculator(weight, height):

  bmi = weight / ((height/100)**2)
  bmi = round(bmi, 1)

  return bmi

def bmi_status(bmi):

  if bmi < 18.5:                        # bmi น้อยกว่า 18.5        : ต่ำกว่าเกณฑ์
    status = 'ต่ำกว่าเกณฑ์'
  elif bmi >= 18.5 and bmi <= 22.9:     # bmi ระหว่าง 18.5 - 22.9  : สมส่วน
    status = 'สมส่วน'
  elif bmi >= 23 and bmi <= 24.9:       # bmi ระหว่าง 23.0 - 24.9  : เกินมาตรฐาน
    status = 'เกินมาตรฐาน'
  elif bmi >= 25 and bmi <= 29.9:       # bmi ระหว่าง 25.0 - 29.9  : โรคอ้วน
    status = 'โรคอ้วน'
  else:                                 # bmi มากกว่า 30.0         : รคอ้วนอันตราย
    status = 'โรคอ้วนอันตราย'

  return status

In [63]:
# Pandas
df_pd = pd.DataFrame(get_body_data())
df_pd.head()

   weight  height
0    70.0  2100.0
1    77.0   185.0
2    77.0   190.0
3    77.0   170.0
4    80.0   155.0

In [64]:
# Polars
df_pl = pl.DataFrame(get_body_data())
df_pl.head()

shape: (5, 2)
┌────────┬────────┐
│ weight ┆ height │
│ ---    ┆ ---    │
│ i64    ┆ i64    │
╞════════╪════════╡
│ 70     ┆ 2100   │
│ 77     ┆ 185    │
│ 77     ┆ 190    │
│ 77     ┆ 170    │
│ 80     ┆ 155    │
└────────┴────────┘

series vs dataframe

Pandas

In [65]:
# series
df_pd['weight']

0     70.0
1     77.0
2     77.0
3     77.0
4     80.0
5     70.0
6      NaN
7     65.0
8     55.0
9     43.0
10    86.0
11    91.0
12    82.0
Name: weight, dtype: float64

In [66]:
# dataframe
df_pd[['height']]

    height
0   2100.0
1    185.0
2    190.0
3    170.0
4    155.0
5      NaN
6    170.0
7    175.0
8    160.0
9    153.0
10   179.0
11   183.0
12   190.0

Polars

In [67]:
# series
df_pl['height']

shape: (13,)
Series: 'height' [i64]
[
	2100
	185
	190
	170
	155
	…
	160
	153
	179
	183
	190
]

In [68]:
# dataframe
df_pl[['height']]

shape: (13, 1)
┌────────┐
│ height │
│ ---    │
│ i64    │
╞════════╡
│ 2100   │
│ 185    │
│ 190    │
│ 170    │
│ 155    │
│ …      │
│ 160    │
│ 153    │
│ 179    │
│ 183    │
│ 190    │
└────────┘

### Data Profiling

#### Basic Function

Pandas

In [69]:
df_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   weight  12 non-null     float64
 1   height  12 non-null     float64
dtypes: float64(2)
memory usage: 336.0 bytes

In [70]:
df_pd.describe()

          weight       height
count  12.000000    12.000000
mean   72.750000   334.166667
std    13.403697   556.237822
min    43.000000   153.000000
25%    68.750000   167.500000
50%    77.000000   177.000000
75%    80.500000   186.250000
max    91.000000  2100.000000

In [71]:
print(df_pd.index)
print(df_pd.columns)
print(df_pd.count())

RangeIndex(start=0, stop=13, step=1)
Index(['weight', 'height'], dtype='object')
weight    12
height    12
dtype: int64

In [72]:
print(df_pd.head(5))
print(df_pd.tail(5))
print(df_pd.shape)

   weight  height
0    70.0  2100.0
1    77.0   185.0
2    77.0   190.0
3    77.0   170.0
4    80.0   155.0
    weight  height
8     55.0   160.0
9     43.0   153.0
10    86.0   179.0
11    91.0   183.0
12    82.0   190.0
(13, 2)

In [73]:
print(df_pd.sort_index())
print(df_pd.sort_values(by='height') )
print(df_pd.rank())

    weight  height
0     70.0  2100.0
1     77.0   185.0
2     77.0   190.0
3     77.0   170.0
4     80.0   155.0
5     70.0     NaN
6      NaN   170.0
7     65.0   175.0
8     55.0   160.0
9     43.0   153.0
10    86.0   179.0
11    91.0   183.0
12    82.0   190.0
    weight  height
9     43.0   153.0
4     80.0   155.0
8     55.0   160.0
3     77.0   170.0
6      NaN   170.0
7     65.0   175.0
10    86.0   179.0
11    91.0   183.0
1     77.0   185.0
2     77.0   190.0
12    82.0   190.0
0     70.0  2100.0
5     70.0     NaN
    weight  height
0      4.5    12.0
1      7.0     9.0
2      7.0    10.5
3      7.0     4.5
4      9.0     2.0
5      4.5     NaN
6      NaN     4.5
7      3.0     6.0
8      2.0     3.0
9      1.0     1.0
10    11.0     7.0
11    12.0     8.0
12    10.0    10.5

Polars

In [74]:
print(df_pl.head(n=5))
print(df_pl.tail(n=5))
print(df_pl.shape)

shape: (5, 2)
┌────────┬────────┐
│ weight ┆ height │
│ ---    ┆ ---    │
│ i64    ┆ i64    │
╞════════╪════════╡
│ 70     ┆ 2100   │
│ 77     ┆ 185    │
│ 77     ┆ 190    │
│ 77     ┆ 170    │
│ 80     ┆ 155    │
└────────┴────────┘
shape: (5, 2)
┌────────┬────────┐
│ weight ┆ height │
│ ---    ┆ ---    │
│ i64    ┆ i64    │
╞════════╪════════╡
│ 55     ┆ 160    │
│ 43     ┆ 153    │
│ 86     ┆ 179    │
│ 91     ┆ 183    │
│ 82     ┆ 190    │
└────────┴────────┘
(13, 2)

In [75]:
df_pl.unique()

shape: (13, 2)
┌────────┬────────┐
│ weight ┆ height │
│ ---    ┆ ---    │
│ i64    ┆ i64    │
╞════════╪════════╡
│ 80     ┆ 155    │
│ 70     ┆ 2100   │
│ 43     ┆ 153    │
│ 77     ┆ 190    │
│ 86     ┆ 179    │
│ …      ┆ …      │
│ 55     ┆ 160    │
│ 70     ┆ null   │
│ 77     ┆ 170    │
│ 65     ┆ 175    │
│ 91     ┆ 183    │
└────────┴────────┘

In [76]:
print(df_pl.sort('weight'))
print(df_pl.with_row_index())

shape: (13, 2)
┌────────┬────────┐
│ weight ┆ height │
│ ---    ┆ ---    │
│ i64    ┆ i64    │
╞════════╪════════╡
│ null   ┆ 170    │
│ 43     ┆ 153    │
│ 55     ┆ 160    │
│ 65     ┆ 175    │
│ 70     ┆ 2100   │
│ …      ┆ …      │
│ 77     ┆ 170    │
│ 80     ┆ 155    │
│ 82     ┆ 190    │
│ 86     ┆ 179    │
│ 91     ┆ 183    │
└────────┴────────┘
shape: (13, 3)
┌───────┬────────┬────────┐
│ index ┆ weight ┆ height │
│ ---   ┆ ---    ┆ ---    │
│ u32   ┆ i64    ┆ i64    │
╞═══════╪════════╪════════╡
│ 0     ┆ 70     ┆ 2100   │
│ 1     ┆ 77     ┆ 185    │
│ 2     ┆ 77     ┆ 190    │
│ 3     ┆ 77     ┆ 170    │
│ 4     ┆ 80     ┆ 155    │
│ …     ┆ …      ┆ …      │
│ 8     ┆ 55     ┆ 160    │
│ 9     ┆ 43     ┆ 153    │
│ 10    ┆ 86     ┆ 179    │
│ 11    ┆ 91     ┆ 183    │
│ 12    ┆ 82     ┆ 190    │
└───────┴────────┴────────┘

#### Index Slicing

In [77]:
def get_df_countries():
  data = {'Country': ['Belgium',  'India',  'Brazil', 'Ghana', 'Canada'],
        'Capital': ['Brussels',  'New Delhi',  'Brasilia', 'Accra', 'Ottawa'],
        'Continent': ['Europe',  'Asia',  'South America', 'Africa', 'North America'],
        'Population': [11190846, 1303171035, 207847528, 5062000, 155555555],
        'Area': [15595488, 545484631, 548494777, 77411222, 789634848]}
  return data

Pandas

In [78]:
pd_countries = pd.DataFrame(get_df_countries())
print(pd_countries[1:])
print(pd_countries.loc[(pd_countries.Capital == 'Brussels') & (pd_countries.Continent == 'Europe')])
print(pd_countries.loc[1:3])
print(pd_countries.iloc[0, 2])
print(pd_countries.iloc[[0, 2]])
print(pd_countries.at[1,  'Country'])

  Country    Capital      Continent  Population       Area
1   India  New Delhi           Asia  1303171035  545484631
2  Brazil   Brasilia  South America   207847528  548494777
3   Ghana      Accra         Africa     5062000   77411222
4  Canada     Ottawa  North America   155555555  789634848
   Country   Capital Continent  Population      Area
0  Belgium  Brussels    Europe    11190846  15595488
  Country    Capital      Continent  Population       Area
1   India  New Delhi           Asia  1303171035  545484631
2  Brazil   Brasilia  South America   207847528  548494777
3   Ghana      Accra         Africa     5062000   77411222
Europe
   Country   Capital      Continent  Population       Area
0  Belgium  Brussels         Europe    11190846   15595488
2   Brazil  Brasilia  South America   207847528  548494777
India

Polars

In [79]:
pl_countries = pl.DataFrame(get_df_countries())
print(pl_countries.sample())
print(pl_countries[1:])
print(pl_countries[1:, :2])

shape: (1, 5)
┌─────────┬───────────┬───────────┬────────────┬───────────┐
│ Country ┆ Capital   ┆ Continent ┆ Population ┆ Area      │
│ ---     ┆ ---       ┆ ---       ┆ ---        ┆ ---       │
│ str     ┆ str       ┆ str       ┆ i64        ┆ i64       │
╞═════════╪═══════════╪═══════════╪════════════╪═══════════╡
│ India   ┆ New Delhi ┆ Asia      ┆ 1303171035 ┆ 545484631 │
└─────────┴───────────┴───────────┴────────────┴───────────┘
shape: (4, 5)
┌─────────┬───────────┬───────────────┬────────────┬───────────┐
│ Country ┆ Capital   ┆ Continent     ┆ Population ┆ Area      │
│ ---     ┆ ---       ┆ ---           ┆ ---        ┆ ---       │
│ str     ┆ str       ┆ str           ┆ i64        ┆ i64       │
╞═════════╪═══════════╪═══════════════╪════════════╪═══════════╡
│ India   ┆ New Delhi ┆ Asia          ┆ 1303171035 ┆ 545484631 │
│ Brazil  ┆ Brasilia  ┆ South America ┆ 207847528  ┆ 548494777 │
│ Ghana   ┆ Accra     ┆ Africa        ┆ 5062000    ┆ 77411222  │
│ Canada  ┆ Ottawa    ┆ North America ┆ 155555555  ┆ 789634848 │
└─────────┴───────────┴───────────────┴────────────┴───────────┘
shape: (4, 2)
┌─────────┬───────────┐
│ Country ┆ Capital   │
│ ---     ┆ ---       │
│ str     ┆ str       │
╞═════════╪═══════════╡
│ India   ┆ New Delhi │
│ Brazil  ┆ Brasilia  │
│ Ghana   ┆ Accra     │
│ Canada  ┆ Ottawa    │
└─────────┴───────────┘

### DataFrame Function

#### Aggregation function

Pandas

In [80]:
print(df_pd['weight'].value_counts())
print(df_pd.groupby('weight').count() )

weight
77.0    3
70.0    2
80.0    1
65.0    1
55.0    1
43.0    1
86.0    1
91.0    1
82.0    1
Name: count, dtype: int64
        height
weight
43.0         1
55.0         1
65.0         1
70.0         1
77.0         3
80.0         1
82.0         1
86.0         1
91.0         1

In [81]:
print(df_pd['weight'].mean() )
print(df_pd.groupby('weight').mean() )
print(df_pd.groupby(by=['weight'])['height'].mean())

72.75
             height
weight
43.0     153.000000
55.0     160.000000
65.0     175.000000
70.0    2100.000000
77.0     181.666667
80.0     155.000000
82.0     190.000000
86.0     179.000000
91.0     183.000000
weight
43.0     153.000000
55.0     160.000000
65.0     175.000000
70.0    2100.000000
77.0     181.666667
80.0     155.000000
82.0     190.000000
86.0     179.000000
91.0     183.000000
Name: height, dtype: float64

In [82]:
print(df_pd['weight'].sum(skipna=True))
print(df_pd['height'].cumsum(axis=0))
print(df_pd['height'].min()/df_pd['height'].max())

873.0
0     2100.0
1     2285.0
2     2475.0
3     2645.0
4     2800.0
5        NaN
6     2970.0
7     3145.0
8     3305.0
9     3458.0
10    3637.0
11    3820.0
12    4010.0
Name: height, dtype: float64
0.07285714285714286

Polars

In [83]:
print(df_pl['weight'].mean())
print(df_pl.group_by(by='weight').agg( [ pl.mean('height').alias("Height_mean")] ))

72.75
shape: (10, 2)
┌──────┬─────────────┐
│ by   ┆ Height_mean │
│ ---  ┆ ---         │
│ i64  ┆ f64         │
╞══════╪═════════════╡
│ 77   ┆ 181.666667  │
│ 86   ┆ 179.0       │
│ 91   ┆ 183.0       │
│ 70   ┆ 2100.0      │
│ 43   ┆ 153.0       │
│ 82   ┆ 190.0       │
│ 65   ┆ 175.0       │
│ 55   ┆ 160.0       │
│ null ┆ 170.0       │
│ 80   ┆ 155.0       │
└──────┴─────────────┘

In [84]:
print(df_pl.sum())
print(df_pl.select( [  pl.sum("weight").alias("sum_weight"), ]) )
print(df_pl['height'].min()/df_pl['height'].max())

shape: (1, 2)
┌────────┬────────┐
│ weight ┆ height │
│ ---    ┆ ---    │
│ i64    ┆ i64    │
╞════════╪════════╡
│ 873    ┆ 4010   │
└────────┴────────┘
shape: (1, 1)
┌────────────┐
│ sum_weight │
│ ---        │
│ i64        │
╞════════════╡
│ 873        │
└────────────┘
0.07285714285714286

#### Filtering

Pandas

In [85]:
filter1 = df_pd['weight']  < 75
filter2 = df_pd['height'] > 175
print(df_pd[filter1] )
print(df_pd[filter1 & filter2])
print(df_pd[filter1 | filter2])

   weight  height
0    70.0  2100.0
5    70.0     NaN
7    65.0   175.0
8    55.0   160.0
9    43.0   153.0
   weight  height
0    70.0  2100.0
    weight  height
0     70.0  2100.0
1     77.0   185.0
2     77.0   190.0
5     70.0     NaN
7     65.0   175.0
8     55.0   160.0
9     43.0   153.0
10    86.0   179.0
11    91.0   183.0
12    82.0   190.0

In [86]:
df_pd.query('height > 200 or weight < 77')

   weight  height
0    70.0  2100.0
5    70.0     NaN
7    65.0   175.0
8    55.0   160.0
9    43.0   153.0

Polars

In [87]:
filter1 = pl.col("height") > 200
filter2 = pl.col("weight") <= 77

print(df_pl.filter((filter1 ) & (filter2)))
print(df_pl.filter((filter1 ) | (filter2)))
print(df_pl.select(pl.col(pl.selectors.INTEGER_DTYPES).exclude('weight')))

shape: (1, 2)
┌────────┬────────┐
│ weight ┆ height │
│ ---    ┆ ---    │
│ i64    ┆ i64    │
╞════════╪════════╡
│ 70     ┆ 2100   │
└────────┴────────┘
shape: (8, 2)
┌────────┬────────┐
│ weight ┆ height │
│ ---    ┆ ---    │
│ i64    ┆ i64    │
╞════════╪════════╡
│ 70     ┆ 2100   │
│ 77     ┆ 185    │
│ 77     ┆ 190    │
│ 77     ┆ 170    │
│ 70     ┆ null   │
│ 65     ┆ 175    │
│ 55     ┆ 160    │
│ 43     ┆ 153    │
└────────┴────────┘
shape: (13, 1)
┌────────┐
│ height │
│ ---    │
│ i64    │
╞════════╡
│ 2100   │
│ 185    │
│ 190    │
│ 170    │
│ 155    │
│ …      │
│ 160    │
│ 153    │
│ 179    │
│ 183    │
│ 190    │
└────────┘

#### DataFrame Manipulation

Pandas

In [88]:
# change datatype
df_pd_c = df_pd.copy()
df_pd_c.dropna(inplace=True)
df_pd_c[["weight"]] = df_pd_c[["weight"]].astype(int)
df_pd_c.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 0 to 12
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   weight  11 non-null     int64
 1   height  11 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 264.0 bytes

In [89]:
# drop renamed column
df_pd_c = df_pd.copy()
df_pd_c.rename(columns={"weight":"weights"}, inplace=True)
df_pd_c = df_pd_c.drop('weights', axis=1)
df_pd_c

    height
0   2100.0
1    185.0
2    190.0
3    170.0
4    155.0
5      NaN
6    170.0
7    175.0
8    160.0
9    153.0
10   179.0
11   183.0
12   190.0

In [90]:
# concat tables and pivot it
df_pd_c = df_pd.copy()
df_pd_c2 = df_pd.copy()

df_pdc = pd.concat([df_pd_c, df_pd_c2])
df_pdc['mult'] = df_pdc['weight'] * df_pdc['height']

df_pdc = pd.pivot_table(df_pdc, values='mult', index=['height'], columns=['weight'], aggfunc="sum", fill_value=0)
df_pdc

weight,43.0,55.0,65.0,70.0,77.0,80.0,82.0,86.0,91.0
height,,,,,,,,,
153.0,13158.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
155.0,0.0,0.0,0.0,0.0,0.0,24800.0,0.0,0.0,0.0
160.0,0.0,17600.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
170.0,0.0,0.0,0.0,0.0,26180.0,0.0,0.0,0.0,0.0
175.0,0.0,0.0,22750.0,0.0,0.0,0.0,0.0,0.0,0.0
179.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30788.0,0.0
183.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33306.0
185.0,0.0,0.0,0.0,0.0,28490.0,0.0,0.0,0.0,0.0
190.0,0.0,0.0,0.0,0.0,29260.0,0.0,31160.0,0.0,0.0
2100.0,0.0,0.0,0.0,294000.0,0.0,0.0,0.0,0.0,0.0

Polars

In [91]:
# change datatype
df_pl_c = df_pl.clone()
df_pl_c[["weight"]] = df_pl_c.select(pl.col("weight").cast(pl.Float32))
df_pl_c

shape: (13, 2)
┌────────┬────────┐
│ weight ┆ height │
│ ---    ┆ ---    │
│ f32    ┆ i64    │
╞════════╪════════╡
│ 70.0   ┆ 2100   │
│ 77.0   ┆ 185    │
│ 77.0   ┆ 190    │
│ 77.0   ┆ 170    │
│ 80.0   ┆ 155    │
│ …      ┆ …      │
│ 55.0   ┆ 160    │
│ 43.0   ┆ 153    │
│ 86.0   ┆ 179    │
│ 91.0   ┆ 183    │
│ 82.0   ┆ 190    │
└────────┴────────┘

In [92]:
# drop renamed columns
df_pl_c = df_pl.clone()
df_pl_c = df_pl_c.rename({"weight":"weights"})
df_pl_c = df_pl_c.drop('weights')
df_pl_c

shape: (13, 1)
┌────────┐
│ height │
│ ---    │
│ i64    │
╞════════╡
│ 2100   │
│ 185    │
│ 190    │
│ 170    │
│ 155    │
│ …      │
│ 160    │
│ 153    │
│ 179    │
│ 183    │
│ 190    │
└────────┘

In [93]:
# concat tables and pivot it
df_pl_c = df_pl.clone()
df_pl_c2 = df_pl.clone()

df_plc = pl.concat([df_pl_c, df_pl_c2])
df_plc = df_plc.with_columns([(pl.col('weight') * pl.col('height')).alias('mult')])
df_plc = df_plc.pivot( "weight", index="height", values="mult", aggregate_function="sum",)

df_plc

shape: (11, 11)
┌────────┬────────┬───────┬───────┬───┬───────┬───────┬───────┬───────┐
│ height ┆ 70     ┆ 77    ┆ 80    ┆ … ┆ 43    ┆ 86    ┆ 91    ┆ 82    │
│ ---    ┆ ---    ┆ ---   ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ i64    ┆ i64    ┆ i64   ┆ i64   ┆   ┆ i64   ┆ i64   ┆ i64   ┆ i64   │
╞════════╪════════╪═══════╪═══════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ 2100   ┆ 294000 ┆ null  ┆ null  ┆ … ┆ null  ┆ null  ┆ null  ┆ null  │
│ 185    ┆ null   ┆ 28490 ┆ null  ┆ … ┆ null  ┆ null  ┆ null  ┆ null  │
│ 190    ┆ null   ┆ 29260 ┆ null  ┆ … ┆ null  ┆ null  ┆ null  ┆ 31160 │
│ 170    ┆ null   ┆ 26180 ┆ null  ┆ … ┆ null  ┆ null  ┆ null  ┆ null  │
│ 155    ┆ null   ┆ null  ┆ 24800 ┆ … ┆ null  ┆ null  ┆ null  ┆ null  │
│ …      ┆ …      ┆ …     ┆ …     ┆ … ┆ …     ┆ …     ┆ …     ┆ …     │
│ 175    ┆ null   ┆ null  ┆ null  ┆ … ┆ null  ┆ null  ┆ null  ┆ null  │
│ 160    ┆ null   ┆ null  ┆ null  ┆ … ┆ null  ┆ null  ┆ null  ┆ null  │
│ 153    ┆ null   ┆ null  ┆ null  ┆ … ┆ 13158 ┆ null  ┆ null  ┆ null  │
│ 179    ┆ null   ┆ null  ┆ null  ┆ … ┆ null  ┆ 30788 ┆ null  ┆ null  │
│ 183    ┆ null   ┆ null  ┆ null  ┆ … ┆ null  ┆ null  ┆ 33306 ┆ null  │
└────────┴────────┴───────┴───────┴───┴───────┴───────┴───────┴───────┘

### Data Transformation

#### Data Cleansing

drop duplicates

pandas

In [94]:
df_pd.drop_duplicates()

    weight  height
0     70.0  2100.0
1     77.0   185.0
2     77.0   190.0
3     77.0   170.0
4     80.0   155.0
5     70.0     NaN
6      NaN   170.0
7     65.0   175.0
8     55.0   160.0
9     43.0   153.0
10    86.0   179.0
11    91.0   183.0
12    82.0   190.0

polars

In [95]:
df_pl.unique()

shape: (13, 2)
┌────────┬────────┐
│ weight ┆ height │
│ ---    ┆ ---    │
│ i64    ┆ i64    │
╞════════╪════════╡
│ 77     ┆ 170    │
│ 82     ┆ 190    │
│ 55     ┆ 160    │
│ 70     ┆ null   │
│ null   ┆ 170    │
│ …      ┆ …      │
│ 65     ┆ 175    │
│ 80     ┆ 155    │
│ 86     ┆ 179    │
│ 77     ┆ 185    │
│ 43     ┆ 153    │
└────────┴────────┘

missing values

In [96]:
df_pd_c = df_pd.copy()
df_pd_c.dropna(inplace=True)

#fillna(value={"col1":0, "col2":2}, axis=1)
df_pd_c['weight'].fillna(df_pd_c['weight'].mean())
df_pd_c['height'].fillna(df_pd_c['height'].mean())

0     2100.0
1      185.0
2      190.0
3      170.0
4      155.0
7      175.0
8      160.0
9      153.0
10     179.0
11     183.0
12     190.0
Name: height, dtype: float64

clear outliers

In [97]:
df_pd_c = df_pd.copy()

Q1 = df_pd_c['height'].quantile(.25)    # การหาควอไทล์ที่ 25 (.25)
Q3 = df_pd_c['height'].quantile(.75)    # การหาควอไทล์ที่ 75 (.75)

IQR = Q3 - Q1                       # ควอไทล์ที่อยู่ระหว่าง 25 - 75

upper_bound = Q3 + 1.5 * IQR        # ขอบเขตบน
lower_bound = Q1 - 1.5 * IQR        # ขอบเขตล่าง

outliers = df_pd_c[(df_pd_c['height'] < lower_bound) | (df_pd_c['height'] > upper_bound)]  # การหาข้อมูลผิดปกติ (Outlier) ที่อยู่นอกช่วง ขอบเขตบน - ล่าง
print( lower_bound, upper_bound )           # (141.875, 216.875)

print(outliers)                            # แสดงข้อมูลผิดปกติ (Outlier)

df_pd_c = df_pd_c[~df_pd_c.index.isin(outliers.index)].copy()  # กรองข้อมูลผิดปกติออกด้วย tilde (~) operator
df_pd_c.dropna(inplace=True)                                     # กำจัดค่าว่าง (NaN) โดยแทนค่าเข้าไปที่เดิม (inplace=True)

print(df_pd_c  )                           # DataFrame ที่ผ่านการทำความสะอาดข้อมูลแล้ว

139.375 214.375
   weight  height
0    70.0  2100.0
    weight  height
1     77.0   185.0
2     77.0   190.0
3     77.0   170.0
4     80.0   155.0
7     65.0   175.0
8     55.0   160.0
9     43.0   153.0
10    86.0   179.0
11    91.0   183.0
12    82.0   190.0

#### apply functions

pandas

In [98]:
df_pd_c['BMI']  = df_pd_c.apply(lambda row: bmi_calculator(row['weight'], row['height']), axis=1)

In [99]:
df_pd_c['BMI'].apply(bmi_status)

1             สมส่วน
2             สมส่วน
3            โรคอ้วน
4     โรคอ้วนอันตราย
7             สมส่วน
8             สมส่วน
9       ต่ำกว่าเกณฑ์
10           โรคอ้วน
11           โรคอ้วน
12            สมส่วน
Name: BMI, dtype: object

In [100]:
df_pd_c.apply(lambda row: bmi_status(row['BMI']), axis=1)

1             สมส่วน
2             สมส่วน
3            โรคอ้วน
4     โรคอ้วนอันตราย
7             สมส่วน
8             สมส่วน
9       ต่ำกว่าเกณฑ์
10           โรคอ้วน
11           โรคอ้วน
12            สมส่วน
dtype: object

polars

In [101]:
df_pl_c = pl.from_pandas(df_pd_c)

In [107]:
pl_results = df_pl_c.select(
    pl.struct(["weight", "height"])
    .map_elements(lambda row: bmi_calculator(row['weight'], row['height']))
    .alias("BMI"),
    (pl.col("weight") + pl.col("height")).alias("normal_plus"))

sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.

In [108]:
pl_results

shape: (10, 2)
┌──────┬─────────────┐
│ BMI  ┆ normal_plus │
│ ---  ┆ ---         │
│ f64  ┆ f64         │
╞══════╪═════════════╡
│ 22.5 ┆ 262.0       │
│ 21.3 ┆ 267.0       │
│ 26.6 ┆ 247.0       │
│ 33.3 ┆ 235.0       │
│ 21.2 ┆ 240.0       │
│ 21.5 ┆ 215.0       │
│ 18.4 ┆ 196.0       │
│ 26.8 ┆ 265.0       │
│ 27.2 ┆ 274.0       │
│ 22.7 ┆ 272.0       │
└──────┴─────────────┘

#### apply min max scaler

In [109]:
from sklearn.preprocessing import MinMaxScaler  # แปลงตัวเลขให้อยู่ระหว่าง 0-1

weight_scaler = MinMaxScaler() # จะทำการแปลงน้ำหนัก (weight)  ให้ตัวเลขอยู่ระหว่าง 0-1 -> MinMaxScaler()
height_scaler = MinMaxScaler() # จะทำการแปลงส่วนสูง (height) ให้ตัวเลขอยู่ระหว่าง 0-1  -> MinMaxScaler()

df_pd_c['weight_scaled'] = weight_scaler.fit_transform(df_pd_c[['weight']])     # สร้างคอลัมน์ใหม่ของน้ำหนัก (weight) เพื่อเก็บผลการแปลง
df_pd_c['height_scaled'] = height_scaler.fit_transform(df_pd_c[['height']])     # สร้างคอลัมน์ใหม่ของส่วนสูง (height) เพื่อเก็บผลการแปลง

df_pd_c

    weight  height   BMI  weight_scaled  height_scaled
1     77.0   185.0  22.5       0.708333       0.864865
2     77.0   190.0  21.3       0.708333       1.000000
3     77.0   170.0  26.6       0.708333       0.459459
4     80.0   155.0  33.3       0.770833       0.054054
7     65.0   175.0  21.2       0.458333       0.594595
8     55.0   160.0  21.5       0.250000       0.189189
9     43.0   153.0  18.4       0.000000       0.000000
10    86.0   179.0  26.8       0.895833       0.702703
11    91.0   183.0  27.2       1.000000       0.810811
12    82.0   190.0  22.7       0.812500       1.000000

### Export & Import

CSV

Pandas

In [110]:
df_pd_c.to_csv('clean_bmi.csv', index=False)
pd.read_csv('clean_bmi.csv')

   weight  height   BMI  weight_scaled  height_scaled
0    77.0   185.0  22.5       0.708333       0.864865
1    77.0   190.0  21.3       0.708333       1.000000
2    77.0   170.0  26.6       0.708333       0.459459
3    80.0   155.0  33.3       0.770833       0.054054
4    65.0   175.0  21.2       0.458333       0.594595
5    55.0   160.0  21.5       0.250000       0.189189
6    43.0   153.0  18.4       0.000000       0.000000
7    86.0   179.0  26.8       0.895833       0.702703
8    91.0   183.0  27.2       1.000000       0.810811
9    82.0   190.0  22.7       0.812500       1.000000

Polars

In [111]:
df_pl_c = pl.from_pandas(df_pd_c)

df_pl_c.write_csv(f"clean_bmi_pl.csv")
pl.read_csv(f"clean_bmi_pl.csv", has_header=True)

shape: (10, 5)
┌────────┬────────┬──────┬───────────────┬───────────────┐
│ weight ┆ height ┆ BMI  ┆ weight_scaled ┆ height_scaled │
│ ---    ┆ ---    ┆ ---  ┆ ---           ┆ ---           │
│ f64    ┆ f64    ┆ f64  ┆ f64           ┆ f64           │
╞════════╪════════╪══════╪═══════════════╪═══════════════╡
│ 77.0   ┆ 185.0  ┆ 22.5 ┆ 0.708333      ┆ 0.864865      │
│ 77.0   ┆ 190.0  ┆ 21.3 ┆ 0.708333      ┆ 1.0           │
│ 77.0   ┆ 170.0  ┆ 26.6 ┆ 0.708333      ┆ 0.459459      │
│ 80.0   ┆ 155.0  ┆ 33.3 ┆ 0.770833      ┆ 0.054054      │
│ 65.0   ┆ 175.0  ┆ 21.2 ┆ 0.458333      ┆ 0.594595      │
│ 55.0   ┆ 160.0  ┆ 21.5 ┆ 0.25          ┆ 0.189189      │
│ 43.0   ┆ 153.0  ┆ 18.4 ┆ 0.0           ┆ 0.0           │
│ 86.0   ┆ 179.0  ┆ 26.8 ┆ 0.895833      ┆ 0.702703      │
│ 91.0   ┆ 183.0  ┆ 27.2 ┆ 1.0           ┆ 0.810811      │
│ 82.0   ┆ 190.0  ┆ 22.7 ┆ 0.8125        ┆ 1.0           │
└────────┴────────┴──────┴───────────────┴───────────────┘

Parquet

Pandas

In [112]:
df_pd_c.to_parquet(f"clean_bmi.parquet")
pd.read_parquet(f"clean_bmi.parquet")

    weight  height   BMI  weight_scaled  height_scaled
1     77.0   185.0  22.5       0.708333       0.864865
2     77.0   190.0  21.3       0.708333       1.000000
3     77.0   170.0  26.6       0.708333       0.459459
4     80.0   155.0  33.3       0.770833       0.054054
7     65.0   175.0  21.2       0.458333       0.594595
8     55.0   160.0  21.5       0.250000       0.189189
9     43.0   153.0  18.4       0.000000       0.000000
10    86.0   179.0  26.8       0.895833       0.702703
11    91.0   183.0  27.2       1.000000       0.810811
12    82.0   190.0  22.7       0.812500       1.000000

Polars

In [113]:
df_pl_c.write_parquet(f"clean_bmi_pl.parquet")
pl.read_parquet(f"clean_bmi_pl.parquet")

shape: (10, 5)
┌────────┬────────┬──────┬───────────────┬───────────────┐
│ weight ┆ height ┆ BMI  ┆ weight_scaled ┆ height_scaled │
│ ---    ┆ ---    ┆ ---  ┆ ---           ┆ ---           │
│ f64    ┆ f64    ┆ f64  ┆ f64           ┆ f64           │
╞════════╪════════╪══════╪═══════════════╪═══════════════╡
│ 77.0   ┆ 185.0  ┆ 22.5 ┆ 0.708333      ┆ 0.864865      │
│ 77.0   ┆ 190.0  ┆ 21.3 ┆ 0.708333      ┆ 1.0           │
│ 77.0   ┆ 170.0  ┆ 26.6 ┆ 0.708333      ┆ 0.459459      │
│ 80.0   ┆ 155.0  ┆ 33.3 ┆ 0.770833      ┆ 0.054054      │
│ 65.0   ┆ 175.0  ┆ 21.2 ┆ 0.458333      ┆ 0.594595      │
│ 55.0   ┆ 160.0  ┆ 21.5 ┆ 0.25          ┆ 0.189189      │
│ 43.0   ┆ 153.0  ┆ 18.4 ┆ 0.0           ┆ 0.0           │
│ 86.0   ┆ 179.0  ┆ 26.8 ┆ 0.895833      ┆ 0.702703      │
│ 91.0   ┆ 183.0  ┆ 27.2 ┆ 1.0           ┆ 0.810811      │
│ 82.0   ┆ 190.0  ┆ 22.7 ┆ 0.8125        ┆ 1.0           │
└────────┴────────┴──────┴───────────────┴───────────────┘

### other ways to create dataframe

In [114]:
def get_data_countries2():
  data = {
        '1': {'Country': 'China', 'Capital':'Shanghai', 'Continent': 'Asia', 'Population': 34342334543, 'Area': 55554518},
        '2': {'Country': 'Australia', 'Capital': 'Canberra', 'Continent': 'Oceania', 'Population': 151648349, 'Area': 978745325 }
          }
  return data

# Deal with datetime

In [115]:
d_date = {'date': {0: '28-01-2022  5:25:00',
  1: '27-02-2022  6:25:00',
  2: '30-03-2022  7:25:00',
  3: '29-04-2022  8:25:00',
  4: '31-05-2022  9:25:00'},
 'date_short': {0: 'Jan-2022', 1: 'Feb-2022', 2: 'Mar-2022', 3: 'Apr-2022', 4: 'May-2022'},
 'unixtime': {0 : 1643365500, 1: 1645961100, 2: 1648643100, 3: 1651238700, 4: 1654007100 }}

In [116]:
#pandas
df_pd = pd.DataFrame(d_date)
df_pd['date'] = pd.to_datetime(df_pd['date'], format='%d-%m-%Y %H:%M:%S')
df_pd['date_new_type'] = df_pd['date'].astype('datetime64[ns]')
df_pd['unixtime'] = pd.to_datetime(df_pd['unixtime'], unit="s")
df_pd

                 date date_short            unixtime       date_new_type
0 2022-01-28 05:25:00   Jan-2022 2022-01-28 10:25:00 2022-01-28 05:25:00
1 2022-02-27 06:25:00   Feb-2022 2022-02-27 11:25:00 2022-02-27 06:25:00
2 2022-03-30 07:25:00   Mar-2022 2022-03-30 12:25:00 2022-03-30 07:25:00
3 2022-04-29 08:25:00   Apr-2022 2022-04-29 13:25:00 2022-04-29 08:25:00
4 2022-05-31 09:25:00   May-2022 2022-05-31 14:25:00 2022-05-31 09:25:00

In [117]:
#polars
d_date_converted = {key: list(val.values()) for key, val in d_date.items()}
df_pl = pl.DataFrame(d_date_converted)
df_pl = df_pl.with_columns( pl.col("date").str.to_datetime(format="%d-%m-%Y %H:%M:%S") )
df_pl = df_pl.with_columns( pl.from_epoch(pl.col('unixtime')) )
df_pl

shape: (5, 3)
┌─────────────────────┬────────────┬─────────────────────┐
│ date                ┆ date_short ┆ unixtime            │
│ ---                 ┆ ---        ┆ ---                 │
│ datetime[μs]        ┆ str        ┆ datetime[μs]        │
╞═════════════════════╪════════════╪═════════════════════╡
│ 2022-01-28 05:25:00 ┆ Jan-2022   ┆ 2022-01-28 10:25:00 │
│ 2022-02-27 06:25:00 ┆ Feb-2022   ┆ 2022-02-27 11:25:00 │
│ 2022-03-30 07:25:00 ┆ Mar-2022   ┆ 2022-03-30 12:25:00 │
│ 2022-04-29 08:25:00 ┆ Apr-2022   ┆ 2022-04-29 13:25:00 │
│ 2022-05-31 09:25:00 ┆ May-2022   ┆ 2022-05-31 14:25:00 │
└─────────────────────┴────────────┴─────────────────────┘

# Deal with API

In [118]:
import requests

#list of dicts
url_currency = "https://r2de3-currency-api-vmftiryt6q-as.a.run.app/gbp_thb"

# convert http request to json
result_conversion_rate = requests.get(url_currency).json()

Pandas

In [119]:
conversion_rate = pd.DataFrame(result_conversion_rate)
conversion_rate = conversion_rate.drop(columns=['id'])
conversion_rate['date'] = pd.to_datetime(conversion_rate['date'])

In [120]:
conversion_rate

          date  gbp_thb
0   2023-05-01   42.761
1   2023-05-02   42.477
2   2023-05-03   42.630
3   2023-05-04   42.456
4   2023-05-05   42.794
..         ...      ...
384 2024-05-19   45.957
385 2024-05-20   45.859
386 2024-05-21   46.246
387 2024-05-22   46.382
388 2024-05-23   46.504

[389 rows x 2 columns]

Polars

In [121]:
conversion_rate_pl = pl.DataFrame(result_conversion_rate)
conversion_rate_pl = conversion_rate_pl.drop('id')
conversion_rate_pl = conversion_rate_pl.with_columns( pl.col("date").str.to_datetime(format="%Y-%m-%d") )

In [122]:
conversion_rate_pl

shape: (389, 2)
┌─────────────────────┬─────────┐
│ date                ┆ gbp_thb │
│ ---                 ┆ ---     │
│ datetime[μs]        ┆ f64     │
╞═════════════════════╪═════════╡
│ 2023-05-01 00:00:00 ┆ 42.761  │
│ 2023-05-02 00:00:00 ┆ 42.477  │
│ 2023-05-03 00:00:00 ┆ 42.63   │
│ 2023-05-04 00:00:00 ┆ 42.456  │
│ 2023-05-05 00:00:00 ┆ 42.794  │
│ …                   ┆ …       │
│ 2024-05-19 00:00:00 ┆ 45.957  │
│ 2024-05-20 00:00:00 ┆ 45.859  │
│ 2024-05-21 00:00:00 ┆ 46.246  │
│ 2024-05-22 00:00:00 ┆ 46.382  │
│ 2024-05-23 00:00:00 ┆ 46.504  │
└─────────────────────┴─────────┘