# PyCaret com features selecionadas pelo metodo da Matriz de Correlação

In [ ]:
!pip install pycaret
from pycaret.classification import *
import pandas as pd
from imblearn.over_sampling import SMOTE

In [2]:
# abrir o dataset
dataset = pd.read_csv('/content/hypothyroid.csv')
#transformando os dados em dados categoricos
for index in dataset.columns.values:
        dataset[index]= dataset[index].astype("category").cat.codes.values

#Processo de limpeza do dataset(removendo linhas com dados faltantes)
for i in dataset.columns.values:
    dataset.drop(dataset[dataset[i] == '?'].index, inplace=True)
dataset = dataset.drop('TBG', axis=1)

## Features selecionadas

In [3]:
dataset = dataset[['T4U', 'T4U measured', 'FTI', 'FTI measured', 'T3', 'T3 measured', 'TT4', 'TT4 measured', 'TSH', 'TSH measured', 'binaryClass']]
dataset.head()

,T4U,T4U measured,FTI,FTI measured,T3,T3 measured,TT4,TT4 measured,TSH,TSH measured,binaryClass
0,72,1,10,1,27,1,28,1,110,1,1
1,146,0,234,0,22,1,3,1,195,1,1
2,48,1,22,1,69,0,10,1,103,1,1
3,146,0,234,0,20,1,83,1,21,1,1
4,44,1,199,1,12,1,201,1,77,1,1

In [4]:
#balancear os dados
sm = SMOTE(random_state=42, k_neighbors=5)
dataset_balanced, output_classe = sm.fit_resample(dataset[['T4U', 'T4U measured', 'FTI', 'FTI measured', 'T3', 'T3 measured', 'TT4', 'TT4 measured', 'TSH', 'TSH measured']], dataset['binaryClass'])

dataset_b= pd.DataFrame(dataset_balanced)
classes = pd.DataFrame(output_classe)

final_dataset = pd.concat([dataset_b, classes], axis=1)

final_dataset.head()

,T4U,T4U measured,FTI,FTI measured,T3,T3 measured,TT4,TT4 measured,TSH,TSH measured,binaryClass
0,72,1,10,1,27,1,28,1,110,1,1
1,146,0,234,0,22,1,3,1,195,1,1
2,48,1,22,1,69,0,10,1,103,1,1
3,146,0,234,0,20,1,83,1,21,1,1
4,44,1,199,1,12,1,201,1,77,1,1

In [5]:
train_size = 0.8
session = setup(data=final_dataset, target='binaryClass', train_size=train_size, data_split_shuffle=True, normalize = True)

In [8]:
best_model = compare_models()

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

In [9]:
print(best_model)

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=-1, num_parallel_tree=None,
              objective='binary:logistic', predictor=None, ...)

## Resultado:
### 5 melhores classificadores:
- Extreme Gradient Boosting
- Random Forest Classifier
- Light Gradient Boosting Machine
- Extra Trees Classifier
- Gradient Boosting Classifier