In [ ]:
%pip install pandas fsspec "huggingface_hub[fsspec]"

Importing the dataset from hugging face into a pandas dataframe

In [55]:
import pandas as pd

df = pd.read_csv("hf://datasets/Aiman1234/Interview-questions/information.csv")

Analyzing the dataset using basic EDA techniques

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 496 entries, 0 to 495
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Number      496 non-null    int64
 1   language    496 non-null    object
 2    level      496 non-null    object
 3   Questions   496 non-null    object
 4   Answers     490 non-null    object
 5   Unnamed: 5  2 non-null      object
dtypes: int64(1), object(5)
memory usage: 23.4+ KB

In [74]:
df.describe()

           Number
count  496.000000
mean   248.500000
std    143.327132
min      1.000000
25%    124.750000
50%    248.500000
75%    372.250000
max    496.000000

Perform basic data cleaning using pandas

In [57]:
print(df[df["Unnamed: 5"].notnull()])

     Number language  level   \
228     229     Java    Easy
430     431     Java  Medium

                                             Questions  \
228  What is the difference between a 'NumberFormat...
430  You are working on a Java project that require...

                                               Answers  \
228                                                NaN
430  In the Java project that requires concurrent a...

                                            Unnamed: 5
228  The 'enum' keyword in Java is used to define a...
430  You can sort an array of Triplets in Java base...

In [58]:
print(df[df["Answers"].isnull()])

     Number language  level   \
228     229     Java    Easy
248     249     Java    Easy
405     406     Java  Medium
408     409     Java  Medium
488     489     Java  Medium
495     496     Java  Medium

                                             Questions Answers  \
228  What is the difference between a 'NumberFormat...     NaN
248  What is the purpose of the 'Iterator' interfac...     NaN
405  What is the purpose of the 'final' keyword in ...     NaN
408  Explain the concept of inheritance in Java. Ho...     NaN
488  What are access modifiers in Java, and what ar...     NaN
495  You are working on a project that requires imp...     NaN

                                            Unnamed: 5
228  The 'enum' keyword in Java is used to define a...
248                                                NaN
405                                                NaN
408                                                NaN
488                                                NaN
495                                                NaN

In [59]:
df1 = df[df["Answers"].notnull()]

In [60]:
df1.drop(columns=["Unnamed: 5"], inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_90232\74219402.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(columns=["Unnamed: 5"], inplace=True)

In [61]:
df1.describe()
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 490 entries, 0 to 494
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Number     490 non-null    int64
 1   language   490 non-null    object
 2    level     490 non-null    object
 3   Questions  490 non-null    object
 4   Answers    490 non-null    object
dtypes: int64(1), object(4)
memory usage: 23.0+ KB

Importing the second dataset using pandas

In [62]:
with open("Dataset\\Software Questions.csv", encoding='cp1252') as f:
    for _ in range(5):
        print(f.readline())

Question Number,Question,Answer,Category,Difficulty

1,What is the difference between compilation and interpretation?,Compilation translates source code into machine code creating an executable file. Interpretation translates and executes code line by line without an executable.,General Programming,Medium

2,Explain the concept of polymorphism.,"Polymorphism allows objects of different classes to be treated as objects of a common superclass, enabling method overriding.",General Programming,Medium

3,Define encapsulation and give an example.,"Encapsulation bundles data and methods in a class, restricting direct data access. Example: class with private data and public methods.",General Programming,Hard

4,"What is an abstract class, and how is it different from an interface?",An abstract class can't be instantiated and can have abstract and concrete methods. An interface only has method signatures without implementations.,General Programming,Medium

In [63]:
df2 = pd.read_csv("Dataset\\Software Questions.csv", encoding='ISO-8859-1')
df2.head(5)

,Question Number,Question,Answer,Category,Difficulty
0,1,What is the difference between compilation and...,Compilation translates source code into machin...,General Programming,Medium
1,2,Explain the concept of polymorphism.,Polymorphism allows objects of different class...,General Programming,Medium
2,3,Define encapsulation and give an example.,Encapsulation bundles data and methods in a cl...,General Programming,Hard
3,4,"What is an abstract class, and how is it diffe...",An abstract class can't be instantiated and ca...,General Programming,Medium
4,5,Describe the principles of Object-Oriented Pro...,"OOP principles include encapsulation, inherita...",General Programming,Medium

In [64]:
df1.head(5)

,Number,language,level,Questions,Answers
0,1,Java,Easy,What is Java?,"Java is a high-level, class-based, object-orie..."
1,2,Java,Easy,What is the difference between JDK and JRE?,JDK (Java Development Kit) is for development ...
2,3,Java,Easy,Explain the main features of Java.,Some main features of Java include platform in...
3,4,Java,Easy,What is the difference between == and equals()...,"== is used to compare references, while equals..."
4,5,Java,Easy,What is the purpose of the 'static' keyword in...,The 'static' keyword is used to create class-l...

In [65]:
df2.describe()
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Question Number  200 non-null    int64
 1   Question         200 non-null    object
 2   Answer           200 non-null    object
 3   Category         200 non-null    object
 4   Difficulty       200 non-null    object
dtypes: int64(1), object(4)
memory usage: 7.9+ KB

In [66]:
print(list(df1.columns))

['Number', 'language', ' level ', 'Questions', 'Answers']

In [67]:
print(list(df2.columns))

['Question Number', 'Question', 'Answer', 'Category', 'Difficulty']

Matching the column names in both datasets to combine the data

In [68]:
df1_renamed = df1.rename(columns={
    "Number": "Question Number",
    "Questions": "Question",
    "Answers": "Answer",
    "language": "Category",
    " level ": "Difficulty"  
})

In [69]:
df1_reordered = df1_renamed[["Question Number", "Question", "Answer", "Category", "Difficulty"]]

In [70]:
df1_reordered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 490 entries, 0 to 494
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Question Number  490 non-null    int64
 1   Question         490 non-null    object
 2   Answer           490 non-null    object
 3   Category         490 non-null    object
 4   Difficulty       490 non-null    object
dtypes: int64(1), object(4)
memory usage: 23.0+ KB

Creating a combined dataset

In [71]:
combined_df = pd.concat([df2, df1_reordered], ignore_index=True)

In [72]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Question Number  690 non-null    int64
 1   Question         690 non-null    object
 2   Answer           690 non-null    object
 3   Category         690 non-null    object
 4   Difficulty       690 non-null    object
dtypes: int64(1), object(4)
memory usage: 27.1+ KB

In [73]:
print(combined_df.head())
print(combined_df.shape)

   Question Number                                           Question  \
0                1  What is the difference between compilation and...
1                2               Explain the concept of polymorphism.
2                3          Define encapsulation and give an example.
3                4  What is an abstract class, and how is it diffe...
4                5  Describe the principles of Object-Oriented Pro...

                                              Answer             Category  \
0  Compilation translates source code into machin...  General Programming
1  Polymorphism allows objects of different class...  General Programming
2  Encapsulation bundles data and methods in a cl...  General Programming
3  An abstract class can't be instantiated and ca...  General Programming
4  OOP principles include encapsulation, inherita...  General Programming

  Difficulty
0     Medium
1     Medium
2       Hard
3     Medium
4     Medium
(690, 5)