import numpy as numps

Extract Data from Google Play .Initially the the data type is dictionary

In [5]:
import pandas as pd
import numpy as np

# Generating sample Google Play Store data
data = {
    'App': [f'App_{i}' for i in range(1, 31)],
    'Category': np.random.choice(['Game', 'Productivity', 'Health', 'Education'], 30),
    'Rating': np.random.uniform(1.0, 5.0, 30).round(1),
    'Reviews': np.random.randint(1, 10000, 30),
    'Size': np.random.choice(['Varies with device', '10M', '20M', '30M'], 30),
    'Installs': np.random.choice(['1,000+', '10,000+', '50,000+', '100,000+'], 30),
    'Type': np.random.choice(['Free', 'Paid'], 30),
    'Price': np.random.choice(['0', '0.99', '1.99', '2.99', '4.99', '5.99', '9.99'], 30),
    'Content Rating': np.random.choice(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+'], 30)
}

Check Data Type

In [7]:
type(data)

dict

Call Pandas Data Frame

In [47]:
df=pd.DataFrame(data)

Call DataFrame with df

In [13]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,App_1,Game,2.7,7370,10M,"1,000+",Paid,2.99,Teen
1,App_2,Education,2.0,6922,30M,"10,000+",Free,5.99,Teen
2,App_3,Education,4.8,5857,30M,"50,000+",Paid,0,Everyone 10+
3,App_4,Game,4.8,9659,20M,"10,000+",Paid,9.99,Mature 17+
4,App_5,Game,2.2,3293,Varies with device,"1,000+",Paid,5.99,Everyone
5,App_6,Education,3.5,8836,Varies with device,"100,000+",Free,1.99,Teen
6,App_7,Game,2.6,717,Varies with device,"50,000+",Paid,1.99,Mature 17+
7,App_8,Education,1.5,9860,Varies with device,"100,000+",Free,5.99,Everyone
8,App_9,Education,4.1,6219,30M,"50,000+",Paid,0.99,Everyone 10+
9,App_10,Health,3.0,3054,10M,"100,000+",Paid,9.99,Mature 17+
10,App_11,Health,2.3,1370,30M,"50,000+",Free,0,Everyone
11,App_12,Game,3.0,5769,30M,"1,000+",Paid,2.99,Teen
12,App_13,Game,3.2,7003,10M,"1,000+",Free,0.99,Everyone 10+
13,App_14,Productivity,4.8,6409,30M,"10,000+",Paid,1.99,Teen
14,App_15,Productivity,4.5,222,30M,"10,000+",Free,9.99,Everyone 10+
15,App_16,Productivity,2.9,4144,10M,"1,000+",Paid,2.99,Teen
16,App_17,Game,4.3,7599,20M,"10,000+",Paid,0.99,Teen
17,App_18,Health,3.8,9394,10M,"50,000+",Paid,2.99,Everyone
18,App_19,Education,3.8,4072,Varies with device,"100,000+",Paid,1.99,Everyone
19,App_20,Education,2.5,2139,10M,"100,000+",Free,1.99,Everyone 10+
20,App_21,Health,3.9,4211,10M,"10,000+",Paid,9.99,Mature 17+
21,App_22,Education,4.3,5421,20M,"50,000+",Paid,5.99,Everyone
22,App_23,Productivity,4.4,226,20M,"10,000+",Free,0,Mature 17+
23,App_24,Productivity,3.5,2843,30M,"10,000+",Paid,0.99,Everyone
24,App_25,Health,1.3,3952,30M,"10,000+",Free,4.99,Everyone
25,App_26,Education,3.3,5224,Varies with device,"50,000+",Free,1.99,Everyone
26,App_27,Education,1.4,5843,10M,"100,000+",Free,1.99,Everyone
27,App_28,Game,2.0,9234,10M,"1,000+",Paid,0.99,Everyone 10+
28,App_29,Education,1.1,6387,30M,"10,000+",Free,1.99,Everyone 10+
29,App_30,Health,2.0,1354,20M,"10,000+",Free,5.99,Everyone 10+

Check the starting 5 entries

In [11]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,App_1,Health,1.1,4114,20M,"50,000+",Free,9.99,Everyone 10+
1,App_2,Game,1.7,6605,10M,"10,000+",Paid,5.99,Everyone 10+
2,App_3,Productivity,2.2,2327,20M,"10,000+",Paid,4.99,Mature 17+
3,App_4,Game,1.8,2961,10M,"50,000+",Paid,1.99,Everyone 10+
4,App_5,Education,4.8,1803,30M,"100,000+",Free,0.99,Teen

Check the last 5 Entries

In [17]:
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
25,App_26,Education,3.3,5224,Varies with device,"50,000+",Free,1.99,Everyone
26,App_27,Education,1.4,5843,10M,"100,000+",Free,1.99,Everyone
27,App_28,Game,2.0,9234,10M,"1,000+",Paid,0.99,Everyone 10+
28,App_29,Education,1.1,6387,30M,"10,000+",Free,1.99,Everyone 10+
29,App_30,Health,2.0,1354,20M,"10,000+",Free,5.99,Everyone 10+

Check the dimensions of data frame

In [17]:
df.shape

(30, 9)

Check the information data

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             30 non-null     object
 1   Category        30 non-null     object
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32
 4   Size            30 non-null     object
 5   Installs        30 non-null     object
 6   Type            30 non-null     object
 7   Price           30 non-null     object
 8   Content Rating  30 non-null     object
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ KB

In [21]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,App_1,Health,1.1,4114,20M,"50,000+",Free,9.99,Everyone 10+
1,App_2,Game,1.7,6605,10M,"10,000+",Paid,5.99,Everyone 10+
2,App_3,Productivity,2.2,2327,20M,"10,000+",Paid,4.99,Mature 17+
3,App_4,Game,1.8,2961,10M,"50,000+",Paid,1.99,Everyone 10+
4,App_5,Education,4.8,1803,30M,"100,000+",Free,0.99,Teen

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             30 non-null     object
 1   Category        30 non-null     object
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32
 4   Size            30 non-null     object
 5   Installs        30 non-null     object
 6   Type            30 non-null     object
 7   Price           30 non-null     object
 8   Content Rating  30 non-null     object
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ KB

Check any three rows

In [27]:
df[["App","Price","Reviews"]]

       App Price  Reviews
0    App_1  9.99     4114
1    App_2  5.99     6605
2    App_3  4.99     2327
3    App_4  1.99     2961
4    App_5  0.99     1803
5    App_6  1.99     6571
6    App_7  1.99     7409
7    App_8     0     3020
8    App_9  2.99     5479
9   App_10     0      465
10  App_11  1.99      533
11  App_12  0.99     4101
12  App_13  0.99      962
13  App_14  1.99     1576
14  App_15     0     3078
15  App_16  4.99     7284
16  App_17  0.99     7285
17  App_18  2.99     2535
18  App_19  0.99     4566
19  App_20  1.99        4
20  App_21  2.99     5161
21  App_22     0     9591
22  App_23  2.99     4366
23  App_24  9.99     9282
24  App_25  5.99     4224
25  App_26  4.99     2222
26  App_27  1.99     2712
27  App_28  0.99     9774
28  App_29  9.99     2731
29  App_30     0     9101

Describe is used to show the Numeric values .Note it will not display string

In [29]:
df.describe()

          Rating      Reviews
count  30.000000    30.000000
mean    2.770000  4394.733333
std     1.282817  2871.873303
min     1.100000     4.000000
25%     1.700000  2379.000000
50%     2.500000  4107.500000
75%     3.975000  6596.500000
max     4.900000  9774.000000

It is used to check the dimensions

In [31]:
df.shape

(30, 9)

Check the unique values( Unique values function is used for see the undesired values like M,+,varies with device).We remove this type of values .This is called cleansing

In [69]:
df["Size"].unique()

array(['20M', '10M', '30M', 'Varies with device'], dtype=object)

This is used to display null values (the reply in Boolean)

In [72]:
df.isnull()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False

The see the null values sum

In [37]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
dtype: int64

To see unique values in Price

In [74]:
df["Price"].unique()

array(['9.99', '5.99', '4.99', '1.99', '0.99', '0', '2.99'], dtype=object)

In the column of Price replace Free with 0.However it is temporary do this.df["Price"].replace("Free","0")
For permanent you have to write this code    df["Price"].df["Price"].replace("Free","0")

In [49]:
df["Price"].replace("Free","0")

0     2.99
1     5.99
2        0
3     9.99
4     5.99
5     1.99
6     1.99
7     5.99
8     0.99
9     9.99
10       0
11    2.99
12    0.99
13    1.99
14    9.99
15    2.99
16    0.99
17    2.99
18    1.99
19    1.99
20    9.99
21    5.99
22       0
23    0.99
24    4.99
25    1.99
26    1.99
27    0.99
28    1.99
29    5.99
Name: Price, dtype: object

Code for Permanent replacement

In [55]:
df["Price"]=df["Price"].replace("Free","0")

In [41]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,App_1,Health,1.1,4114,20M,"50,000+",Free,9.99,Everyone 10+
1,App_2,Game,1.7,6605,10M,"10,000+",Paid,5.99,Everyone 10+
2,App_3,Productivity,2.2,2327,20M,"10,000+",Paid,4.99,Mature 17+
3,App_4,Game,1.8,2961,10M,"50,000+",Paid,1.99,Everyone 10+
4,App_5,Education,4.8,1803,30M,"100,000+",Free,0.99,Teen
5,App_6,Education,1.7,6571,30M,"50,000+",Paid,1.99,Everyone
6,App_7,Health,4.2,7409,10M,"100,000+",Free,1.99,Mature 17+
7,App_8,Education,4.7,3020,30M,"1,000+",Paid,0,Everyone
8,App_9,Education,2.5,5479,10M,"10,000+",Free,2.99,Everyone 10+
9,App_10,Productivity,4.4,465,20M,"1,000+",Paid,0,Mature 17+
10,App_11,Education,1.2,533,20M,"10,000+",Paid,1.99,Mature 17+
11,App_12,Productivity,1.6,4101,20M,"10,000+",Paid,0.99,Everyone 10+
12,App_13,Health,1.2,962,10M,"50,000+",Paid,0.99,Mature 17+
13,App_14,Education,2.5,1576,Varies with device,"1,000+",Free,1.99,Everyone
14,App_15,Health,2.4,3078,20M,"10,000+",Free,0,Teen
15,App_16,Education,3.6,7284,Varies with device,"100,000+",Paid,4.99,Teen
16,App_17,Game,1.3,7285,20M,"1,000+",Paid,0.99,Teen
17,App_18,Education,3.3,2535,20M,"1,000+",Free,2.99,Everyone 10+
18,App_19,Productivity,2.7,4566,30M,"10,000+",Free,0.99,Mature 17+
19,App_20,Education,2.8,4,20M,"1,000+",Free,1.99,Everyone
20,App_21,Education,2.3,5161,Varies with device,"100,000+",Paid,2.99,Everyone
21,App_22,Productivity,4.1,9591,10M,"1,000+",Paid,0,Teen
22,App_23,Game,4.9,4366,10M,"1,000+",Free,2.99,Teen
23,App_24,Productivity,1.8,9282,10M,"1,000+",Free,9.99,Teen
24,App_25,Game,1.1,4224,20M,"10,000+",Paid,5.99,Teen
25,App_26,Health,4.7,2222,30M,"1,000+",Free,4.99,Mature 17+
26,App_27,Health,2.9,2712,Varies with device,"10,000+",Free,1.99,Everyone 10+
27,App_28,Health,4.6,9774,Varies with device,"100,000+",Free,0.99,Teen
28,App_29,Game,3.4,2731,10M,"50,000+",Free,9.99,Everyone 10+
29,App_30,Game,1.6,9101,Varies with device,"50,000+",Free,0,Everyone 10+