## CLEANSING CSV

In [1]:
#importing
import pandas as pd
import numpy as np
import re

In [2]:
# calling csv
df = pd.read_csv("../project2/data/games.csv", encoding= "unicode_escape")

In [3]:
# changing values to be able to see all the columns
pd.set_option('display.max_columns', None)

In [4]:
#cheking all the null values
df.isna().sum()

id                0
rated             0
created_at        0
last_move_at      0
turns             0
victory_status    0
winner            0
increment_code    0
white_id          0
white_rating      0
black_id          0
black_rating      0
moves             0
opening_eco       0
opening_name      0
opening_ply       0
dtype: int64

In [5]:
#looking for leftover columns
df.sample()

,id,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply
15116,KfhyI0Bq,True,1.502142e+12,1.502143e+12,55,resign,white,8+1,mrmandelbrot,1167,worstplayerever123,1176,e4 e5 d4 d5 dxe5 d4 Bb5+ Bd7 c4 Bxb5 cxb5 Bb4+...,C21,King's Pawn Game: Beyer Gambit,4

In [6]:
castle_list = []
for i in df["moves"]:
    word = i.split()
    if "O-O" in word:
        castle_list.append("Yes")
    else:
        castle_list.append("No")

castle_list

['No',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 ...]

In [7]:
df["kings_castle"] = castle_list

In [9]:
#Delete all colums that we will not use
df = df.drop(["id","rated","created_at","last_move_at","increment_code","white_id","black_id","moves",], axis = 1)
#shape check 
df.shape

(20058, 9)

In [10]:
df

,turns,victory_status,winner,white_rating,black_rating,opening_eco,opening_name,opening_ply,kings_castle
0,13,outoftime,white,1500,1191,D10,Slav Defense: Exchange Variation,5,No
1,16,resign,black,1322,1261,B00,Nimzowitsch Defense: Kennedy Variation,4,No
2,61,mate,white,1496,1500,C20,King's Pawn Game: Leonardis Variation,3,No
3,61,mate,white,1439,1454,D02,Queen's Pawn Game: Zukertort Variation,3,Yes
4,95,mate,white,1523,1469,C41,Philidor Defense,5,Yes
...,...,...,...,...,...,...,...,...,...
20053,24,resign,white,1691,1220,A80,Dutch Defense,2,Yes
20054,82,mate,black,1233,1196,A41,Queen's Pawn,2,Yes
20055,35,mate,white,1219,1286,D00,Queen's Pawn Game: Mason Attack,3,Yes
20056,109,resign,white,1360,1227,B07,Pirc Defense,4,No
20057,78,mate,black,1235,1339,D00,Queen's Pawn Game: Mason Attack,3,Yes

In [11]:
#mean of average movements
df["turns"].mean()

60.46599860404826

In [12]:
#checking values
df["victory_status"].value_counts()

resign       11147
mate          6325
outoftime     1680
draw           906
Name: victory_status, dtype: int64

In [13]:
#looking for the average elo of both players 
df["white_rating"].mean()

1596.6318675840064

In [14]:
#opening eco values list
df["opening_eco"].value_counts()

A00    1007
C00     844
D00     739
B01     716
C41     691
       ...
A33       1
D22       1
E44       1
B58       1
D19       1
Name: opening_eco, Length: 365, dtype: int64

In [15]:

df["opening_ply"].value_counts()

3     3490
4     3308
2     2935
5     2730
6     2020
7     1344
8     1116
1     1097
9      687
10     432
11     425
12     142
13     127
14      57
15      43
17      37
16      31
18      12
19      11
20       8
28       4
22       1
24       1
Name: opening_ply, dtype: int64

In [16]:
#looking for all the values in opening
df["opening_name"].value_counts()

Van't Kruijs Opening                                              368
Sicilian Defense                                                  358
Sicilian Defense: Bowdler Attack                                  296
Scotch Game                                                       271
French Defense: Knight Variation                                  271
                                                                 ...
Sicilian Defense: Kupreichik Variation                              1
Modern Defense: Lizard Defense |  Mittenberger Gambit               1
French Defense: Rubinstein Variation |  Kasparov Attack             1
French Defense: Tarrasch Variation |  Open System |  Main Line      1
Sicilian Defense: Najdorf Variation |  Polugaevsky Variation        1
Name: opening_name, Length: 1477, dtype: int64

In [17]:
# Delete everythings its after the dots and dots included to make it simple
df["opening_name"] = df["opening_name"].str.replace("|",":")
df["opening_name"] = df["opening_name"].str.replace("#",":")
df["opening_name"] = df["opening_name"]+":"
df['opening'] = df['opening_name'].str.extract('^(.+?):')

/var/folders/b0/dq4wb7ld55l9pqp5_v7jcgmc0000gn/T/ipykernel_34999/1692786508.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df["opening_name"] = df["opening_name"].str.replace("|",":")

In [18]:
df

,turns,victory_status,winner,white_rating,black_rating,opening_eco,opening_name,opening_ply,kings_castle,opening
0,13,outoftime,white,1500,1191,D10,Slav Defense: Exchange Variation:,5,No,Slav Defense
1,16,resign,black,1322,1261,B00,Nimzowitsch Defense: Kennedy Variation:,4,No,Nimzowitsch Defense
2,61,mate,white,1496,1500,C20,King's Pawn Game: Leonardis Variation:,3,No,King's Pawn Game
3,61,mate,white,1439,1454,D02,Queen's Pawn Game: Zukertort Variation:,3,Yes,Queen's Pawn Game
4,95,mate,white,1523,1469,C41,Philidor Defense:,5,Yes,Philidor Defense
...,...,...,...,...,...,...,...,...,...,...
20053,24,resign,white,1691,1220,A80,Dutch Defense:,2,Yes,Dutch Defense
20054,82,mate,black,1233,1196,A41,Queen's Pawn:,2,Yes,Queen's Pawn
20055,35,mate,white,1219,1286,D00,Queen's Pawn Game: Mason Attack:,3,Yes,Queen's Pawn Game
20056,109,resign,white,1360,1227,B07,Pirc Defense:,4,No,Pirc Defense
20057,78,mate,black,1235,1339,D00,Queen's Pawn Game: Mason Attack:,3,Yes,Queen's Pawn Game

In [19]:
#checking cleansing results
df["opening"].value_counts()

Sicilian Defense       2573
French Defense         1306
Queen's Pawn Game      1059
Italian Game            981
King's Pawn Game        917
                       ...
Global Opening            1
Australian Defense        1
Doery Defense             1
Pterodactyl Defense       1
Valencia Opening          1
Name: opening, Length: 169, dtype: int64

In [20]:
#removing old column
df = df.drop(["opening_name"], axis = 1)

In [21]:
df

,turns,victory_status,winner,white_rating,black_rating,opening_eco,opening_ply,kings_castle,opening
0,13,outoftime,white,1500,1191,D10,5,No,Slav Defense
1,16,resign,black,1322,1261,B00,4,No,Nimzowitsch Defense
2,61,mate,white,1496,1500,C20,3,No,King's Pawn Game
3,61,mate,white,1439,1454,D02,3,Yes,Queen's Pawn Game
4,95,mate,white,1523,1469,C41,5,Yes,Philidor Defense
...,...,...,...,...,...,...,...,...,...
20053,24,resign,white,1691,1220,A80,2,Yes,Dutch Defense
20054,82,mate,black,1233,1196,A41,2,Yes,Queen's Pawn
20055,35,mate,white,1219,1286,D00,3,Yes,Queen's Pawn Game
20056,109,resign,white,1360,1227,B07,4,No,Pirc Defense
20057,78,mate,black,1235,1339,D00,3,Yes,Queen's Pawn Game

In [22]:
#making new colum elo difference between players
df['rating_diff'] = df['white_rating'] - df['black_rating']
df

,turns,victory_status,winner,white_rating,black_rating,opening_eco,opening_ply,kings_castle,opening,rating_diff
0,13,outoftime,white,1500,1191,D10,5,No,Slav Defense,309
1,16,resign,black,1322,1261,B00,4,No,Nimzowitsch Defense,61
2,61,mate,white,1496,1500,C20,3,No,King's Pawn Game,-4
3,61,mate,white,1439,1454,D02,3,Yes,Queen's Pawn Game,-15
4,95,mate,white,1523,1469,C41,5,Yes,Philidor Defense,54
...,...,...,...,...,...,...,...,...,...,...
20053,24,resign,white,1691,1220,A80,2,Yes,Dutch Defense,471
20054,82,mate,black,1233,1196,A41,2,Yes,Queen's Pawn,37
20055,35,mate,white,1219,1286,D00,3,Yes,Queen's Pawn Game,-67
20056,109,resign,white,1360,1227,B07,4,No,Pirc Defense,133
20057,78,mate,black,1235,1339,D00,3,Yes,Queen's Pawn Game,-104

In [23]:
#Making new column base on expected winner using rate difference
df['expected_winner'] = ['white' if x >= 0 else 'black' for x in df['rating_diff']]
df

,turns,victory_status,winner,white_rating,black_rating,opening_eco,opening_ply,kings_castle,opening,rating_diff,expected_winner
0,13,outoftime,white,1500,1191,D10,5,No,Slav Defense,309,white
1,16,resign,black,1322,1261,B00,4,No,Nimzowitsch Defense,61,white
2,61,mate,white,1496,1500,C20,3,No,King's Pawn Game,-4,black
3,61,mate,white,1439,1454,D02,3,Yes,Queen's Pawn Game,-15,black
4,95,mate,white,1523,1469,C41,5,Yes,Philidor Defense,54,white
...,...,...,...,...,...,...,...,...,...,...,...
20053,24,resign,white,1691,1220,A80,2,Yes,Dutch Defense,471,white
20054,82,mate,black,1233,1196,A41,2,Yes,Queen's Pawn,37,white
20055,35,mate,white,1219,1286,D00,3,Yes,Queen's Pawn Game,-67,black
20056,109,resign,white,1360,1227,B07,4,No,Pirc Defense,133,white
20057,78,mate,black,1235,1339,D00,3,Yes,Queen's Pawn Game,-104,black

In [25]:
df["kings_castle"].value_counts()

Yes    15181
No      4877
Name: kings_castle, dtype: int64

In [26]:
#exporting clean csv 
df.to_csv("data/games_clean.csv", index = False, encoding='unicode_escape')