## Data Encoding
### 1.Nominal/OHE Encoding
### 2.Label and Ordinal Encoding
### 3.Target Guided Ordinal Encoding

### Nominal/OHE Encoding
### One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using one hot encoding as follows:

### 1.Red: [1, 0, 0]
### 2.Green: [0, 1, 0]
### 3.Blue: [0, 0, 1]

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
## Create a simple dataframe 
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [5]:
## create an instance of onehotencoder
encoder=OneHotEncoder()

In [8]:
## Perform fit and transform
encoded=encoder.fit_transform(df[['color']]).toarray()

In [9]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [10]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [12]:
## for new data
encoder.transform([['blue']]).toarray()

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [13]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

## Label

In [14]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [15]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [16]:
label_encoder.fit_transform(df[['color']])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [17]:
label_encoder.transform([['red']])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [18]:
label_encoder.transform([['blue']])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [19]:
label_encoder.transform([['green']])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

##  Ordinal Encoding
#### It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order. For example, if we have a categorical variable "education level" with four possible values (high school, college, graduate, post-graduate), we can represent it using ordinal encoding as follows:

#### High school: 1
#### College: 2
#### Graduate: 3
#### Post-graduate: 4

In [20]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
# create a sample dataframe with an ordinal variable
df = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [22]:
df.head()

     size
0   small
1  medium
2   large
3  medium
4   small

In [23]:
## create an insatce of ordinal encoder and peform fit_transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [25]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

## Target Guided Ordinal Encoding
#### It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

#### In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [27]:
# create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [28]:
df.head()

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180

In [31]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [32]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [33]:
df['city_encoded'] = df['city'].map(mean_price)

In [35]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0