In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import StackingClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression

In [ ]:
df=pd.read_csv('Iris.csv')

In [ ]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
x=df.drop('Species',axis=1)
df.drop('Id',axis=1)
y=df['Species']

In [ ]:
x.drop('Id',axis=1)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [ ]:
le=LabelEncoder()
y_e=le.fit_transform(y)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42,stratify=y_e)

In [ ]:
m=[
    ('Lr',LogisticRegression(max_iter=1000)),
    ('Dc',DecisionTreeClassifier(random_state=42)),
    ('svc',SVC(probability=True,kernel='rbf',random_state=42))
]

In [ ]:
meta_learner=LogisticRegression()

In [ ]:
stack_clf=StackingClassifier(
    estimators=m,
    final_estimator=meta_learner,
    cv=5
)

In [ ]:
stack_clf.fit(X_train,y_train)

StackingClassifier(cv=5,
                   estimators=[('Lr', LogisticRegression(max_iter=1000)),
                               ('Dc', DecisionTreeClassifier(random_state=42)),
                               ('svc', SVC(probability=True, random_state=42))],
                   final_estimator=LogisticRegression())

In [ ]:
y_pre=stack_clf.predict(X_test)

In [ ]:
acc=accuracy_score(y_test,y_pre)

In [ ]:
acc

1.0

In [ ]:
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier

In [ ]:
from xgboost import XGBClassifier

In [ ]:
ad=AdaBoostClassifier(n_estimators=100,random_state=42)

In [ ]:
ad.fit(X_train,y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [ ]:
y_pre=ad.predict(X_test)

In [ ]:
accuracy_score(y_test,y_pre)

1.0

In [ ]:
gb=GradientBoostingClassifier(n_estimators=100,learning_rate=0.1,random_state=42)

In [ ]:
gb.fit(X_train,y_train)

GradientBoostingClassifier(random_state=42)

In [ ]:
y_pregb=gb.predict(X_test)

In [ ]:
accuracy_score(y_test,y_pregb)

1.0

In [ ]:
xgb=XGBClassifier(n_estimators=100,learning_rate=0.1,max_depth=3,use_label_encoder=False,eval_metric='mlogloss',random_state=42)

In [ ]:
y_train_encoded = le.transform(y_train)
xgb.fit(X_train, y_train_encoded)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [17:42:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [ ]:
y_prexgb=xgb.predict(X_test)

In [ ]:
accuracy_score(y_test,y_prexgb)

0.0