In [1]:
import os
csv_dir = "/Users/jehadabed/Desktop/Coding/OCx25-dashboard/v4/Data/"
print(os.listdir(csv_dir))

['current_data_co2.json', 'ExpDataDump_250923.numbers', '.DS_Store', 'XRD', 'DashboardData.csv', 'DashboardData-241125.csv', 'XRFDataDump-241125.csv', 'ExpDataDump_250923.csv', 'XRFDataDump-250923.numbers', 'current_data_her.json', 'DashboardData-250923.csv', 'XRFDataDump-250923.csv', 'cleaning_DashboardData.ipynb', 'ExpDataDump_241125.csv']

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

main_df = pd.read_csv(f"ExpDataDump_250923.csv")
main_df = main_df.sort_values(by='voltage', ascending=True).reset_index(drop=True)
# Remove rows where 'rep' column contains 'avg' or 'std' (case-insensitive)
if "rep" in main_df.columns:
    main_df = main_df[~main_df["rep"].astype(str).str.lower().str.contains("avg|std", na=False)].reset_index(drop=True)

# Rename "composition" to "target composition" in main_df if it exists
if "composition" in main_df.columns:
    main_df = main_df.rename(columns={"composition": "target composition"})


# Sort by 'source', then 'batch number', then 'batch date' (all ascending), then by 'sample id'
sort_cols = []
if "source" in main_df.columns:
    sort_cols.append("source")
if "batch number" in main_df.columns:
    sort_cols.append("batch number")
if "batch date" in main_df.columns:
    sort_cols.append("batch date")
if "sample id" in main_df.columns:
    sort_cols.append("sample id")
if sort_cols:
    main_df = main_df.sort_values(by=sort_cols, ascending=True).reset_index(drop=True)


main_df.head(10)

,sample id,source,batch number,batch date,target composition,rep,reaction,current density,voltage,fe_h2,fe_co,fe_ch4,fe_c2h4,fe_gas_total,fe_liquid
0,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,1,HER,50,2.33,NaN,NaN,NaN,NaN,NaN,NaN
1,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,1,CO2R,50,2.74,48.145389,38.634578,0.008807,0.000000,86.788774,13.211226
2,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,1,CO2R,100,3.05,34.726401,53.641945,0.012109,0.000000,88.382927,11.617073
3,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,1,CO2R,150,3.16,30.517902,59.287819,0.013210,0.000000,89.821238,10.178762
4,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,1,CO2R,200,3.31,23.047563,60.066306,0.015687,0.001686,83.133714,16.866286
5,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,1,CO2R,300,3.55,61.609157,20.260314,0.021283,0.012925,81.906151,18.093849
6,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep2,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,2,HER,50,2.51,NaN,NaN,NaN,NaN,NaN,NaN
7,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep2,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,2,CO2R,50,2.91,44.366277,41.920432,0.007706,0.000000,86.294415,13.705585
8,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep2,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,2,CO2R,100,3.19,30.468936,54.150295,0.011009,0.000000,84.632217,15.367783
9,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep2,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,2,CO2R,150,3.37,30.088096,60.142436,0.009541,0.001405,90.243455,9.756545

In [3]:
# Load the new XRF data
xrf_df = pd.read_csv(f"{csv_dir}XRFDataDump-250923.csv")
# Sort by 'source', then 'batch number', then 'batch date' (all ascending), then by 'sample id'
sort_cols = []
if "source" in xrf_df.columns:
    sort_cols.append("source")
if "batch number" in xrf_df.columns:
    sort_cols.append("batch number")
if "batch date" in xrf_df.columns:
    sort_cols.append("batch date")
if "sample id" in xrf_df.columns:
    sort_cols.append("sample id")
if sort_cols:
    xrf_df = xrf_df.sort_values(by=sort_cols, ascending=True).reset_index(drop=True)

xrf_df.head(10)

,sample id,source,batch number,batch date,xrf-wafer_formula,xrf-wafer_stdev,xrf-gde_formula,xrf-gde_stdev,libs-wafer_formula,libs-wafer_stdev,...,xrf-wafter-afteranneal_Sn_stdev,xrf-wafter-afteranneal_stdev,xrf-gde_Pd_mean,xrf-gde_Pd_stdev,xrf-gde_Sn_mean,xrf-gde_Sn_stdev,xrf-gde_Zn_mean,xrf-gde_Zn_stdev,xrf-gde_Ga_mean,xrf-gde_Ga_stdev
0,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.129-Cu-0.083-Pd-0.788,"[0.0104403065089105, 0.0015176736583776, 0.009...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,uoft4_240405_Ag-0.2-Pd-0.8_pp0_rep1,uoft,4,240405,Ag-0.205-Pd-0.795,"[0.0178978583448783, 0.0062449979983983]",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,uoft4_240405_Ag-0.222-Cu-0.333-Pd-0.444_pp0_rep1,uoft,4,240405,Ag-0.335-Cu-0.308-Pd-0.357,"[0.0124899959967967, 0.0023094010767585, 0.008...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,uoft4_240405_Ag-0.25-Au-0.25-Pd-0.5_pp0_rep1,uoft,4,240405,Ag-0.243-Au-0.387-Pd-0.37,"[0.0161967074843417, 0.0153948043183406, 0.008...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,uoft4_240405_Ag-0.333-Pd-0.667_pp0_rep1,uoft,4,240405,Ag-0.384-Pd-0.616,"[0.0037859388972001, 0.0117189305541646]",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,uoft4_240405_Ag-0.4-Pd-0.6_pp0_rep1,uoft,4,240405,Ag-0.407-Pd-0.593,"[0.0045092497528228, 0.0104403065089105]",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,uoft4_240405_Ag-0.429-Pd-0.571_pp0_rep1,uoft,4,240405,Ag-0.566-Pd-0.434,"[0.0017320508075688, 0.0049328828623162]",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,uoft4_240405_Ag-0.444-Pd-0.556_pp0_rep1,uoft,4,240405,Ag-0.485-Pd-0.515,"[0.0062449979983983, 0.003]",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,uoft4_240405_Ag-0.5-Au-0.5_pp0_rep1,uoft,4,240405,Ag-0.339-Au-0.661,"[0.0215019378971602, 0.0665507325278993]",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,uoft4_240405_Ag-0.5-Cu-0.25-Pd-0.25_pp0_rep1,uoft,4,240405,Ag-0.588-Cu-0.17-Pd-0.242,"[0.0051316014394468, 0.0061101009266077, 0.000...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# For "uoft" samples, ensure all sample ids with the same prefix up to (but not including) "_rep" share the same xrf composition
import re

def get_xrf_composition(row):
    sid = row["sample id"]
    source = row.get("source", None)
    if source == "uoft":
        # Extract the prefix up to (but not including) "_rep"
        match_prefix = re.match(r"(.+_rep)\d+$", sid)
        if match_prefix:
            prefix = match_prefix.group(1)
            # Find all sample ids in xrf_df that start with this prefix
            matches = xrf_df[xrf_df["sample id"].str.startswith(prefix)]
            # Use the first valid xrf-gde_formula or fallback to xrf-wafer_formula
            for _, mrow in matches.iterrows():
                val = mrow.get("xrf-gde_formula", None)
                if pd.notna(val) and str(val).strip() != "":
                    return val
                val2 = mrow.get("xrf-wafer_formula", None)
                if pd.notna(val2) and str(val2).strip() != "":
                    return val2
            return None
    # Default behavior for non-uoft or if no prefix match
    match = xrf_df[xrf_df["sample id"] == sid]
    if not match.empty:
        val = match.iloc[0].get("xrf-gde_formula", None)
        if pd.notna(val) and str(val).strip() != "":
            return val
        val2 = match.iloc[0].get("xrf-wafer_formula", None)
        if pd.notna(val2) and str(val2).strip() != "":
            return val2
    return None

# Insert "xrf composition" column after "target composition"
cols = list(main_df.columns)
if "target composition" in cols:
    insert_at = cols.index("target composition") + 1
else:
    # If not present, add at the end
    insert_at = len(cols)

# First, compute the xrf composition as before
xrf_comps = main_df.apply(get_xrf_composition, axis=1)

# For samples where "xrf composition" is empty, use "target composition" value
def fill_xrf_with_target(xrf_val, target_val):
    if pd.isna(xrf_val) or str(xrf_val).strip() == "":
        return target_val
    return xrf_val

if "target composition" in main_df.columns:
    target_comps = main_df["target composition"]
else:
    target_comps = [None] * len(main_df)

xrf_comps_filled = [
    fill_xrf_with_target(xrf_val, target_val)
    for xrf_val, target_val in zip(xrf_comps, target_comps)
]

main_df.insert(insert_at, "xrf composition", xrf_comps_filled)
main_df.head(10)

,sample id,source,batch number,batch date,target composition,xrf composition,rep,reaction,current density,voltage,fe_h2,fe_co,fe_ch4,fe_c2h4,fe_gas_total,fe_liquid
0,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,1,HER,50,2.33,NaN,NaN,NaN,NaN,NaN,NaN
1,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,1,CO2R,50,2.74,48.145389,38.634578,0.008807,0.000000,86.788774,13.211226
2,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,1,CO2R,100,3.05,34.726401,53.641945,0.012109,0.000000,88.382927,11.617073
3,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,1,CO2R,150,3.16,30.517902,59.287819,0.013210,0.000000,89.821238,10.178762
4,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,1,CO2R,200,3.31,23.047563,60.066306,0.015687,0.001686,83.133714,16.866286
5,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,1,CO2R,300,3.55,61.609157,20.260314,0.021283,0.012925,81.906151,18.093849
6,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep2,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,2,HER,50,2.51,NaN,NaN,NaN,NaN,NaN,NaN
7,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep2,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,2,CO2R,50,2.91,44.366277,41.920432,0.007706,0.000000,86.294415,13.705585
8,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep2,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,2,CO2R,100,3.19,30.468936,54.150295,0.011009,0.000000,84.632217,15.367783
9,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep2,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,2,CO2R,150,3.37,30.088096,60.142436,0.009541,0.001405,90.243455,9.756545

In [5]:
# Decompose "xrf composition" into separate columns for each element

import numpy as np

def parse_xrf_composition(comp):
    """
    Parse a string like 'Ag-0.129-Cu-0.083-Pd-0.788' into a dict: {'Ag': 0.129, 'Cu': 0.083, 'Pd': 0.788}
    """
    if not isinstance(comp, str) or comp.strip() == "":
        return {}
    parts = comp.split('-')
    # Expect alternating element, value, element, value, ...
    out = {}
    i = 0
    while i < len(parts) - 1:
        el = parts[i]
        try:
            val = float(parts[i+1])
        except Exception:
            val = 0.0
        out[el] = val
        i += 2
    return out

# Apply parsing to all rows and collect all unique elements
xrf_dicts = main_df["xrf composition"].apply(parse_xrf_composition)
all_elements = set()
for d in xrf_dicts:
    all_elements.update(d.keys())

# For each element, create a new column, fill missing with 0, and sort columns alphabetically
element_columns = []
for el in sorted(all_elements):
    main_df[el] = xrf_dicts.apply(lambda d: d.get(el, 0.0))
    element_columns.append(el)

# Move the element columns to be together and in alphabetical order (if not already)
# Find the first element column's index
first_el_idx = min([main_df.columns.get_loc(el) for el in element_columns])
# Remove element columns from their current positions
cols = [col for col in main_df.columns if col not in element_columns]
# Insert element columns in sorted order at the correct position
for i, el in enumerate(sorted(element_columns)):
    cols.insert(first_el_idx + i, el)
main_df = main_df[cols]

main_df

,sample id,source,batch number,batch date,target composition,xrf composition,rep,reaction,current density,voltage,...,Mo,Nb,Ni,Pd,Pt,Rh,Sn,Tl,W,Zn
0,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,1,HER,50,2.330000,...,0.000,0.0,0.0,0.788,0.0,0.0,0.0,0.0,0.000,0.0
1,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,1,CO2R,50,2.740000,...,0.000,0.0,0.0,0.788,0.0,0.0,0.0,0.0,0.000,0.0
2,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,1,CO2R,100,3.050000,...,0.000,0.0,0.0,0.788,0.0,0.0,0.0,0.0,0.000,0.0
3,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,1,CO2R,150,3.160000,...,0.000,0.0,0.0,0.788,0.0,0.0,0.0,0.0,0.000,0.0
4,uoft4_240405_Ag-0.125-Cu-0.125-Pd-0.75_pp0_rep1,uoft,4,240405,Ag-0.125-Cu-0.125-Pd-0.75,Ag-0.129-Cu-0.083-Pd-0.788,1,CO2R,200,3.310000,...,0.000,0.0,0.0,0.788,0.0,0.0,0.0,0.0,0.000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3318,vsp33_250214_Mo-0.23-W-0.77_pp0_rep1,vsp,33,250214,Mo-0.23-W-0.77,Mo-0.506-W-0.494,1,HER,50,2.770520,...,0.506,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.494,0.0
3319,vsp33_250214_Mo-0.23-W-0.77_pp0_rep2,vsp,33,250214,Mo-0.23-W-0.77,Mo-0.339-W-0.661,2,HER,50,2.743500,...,0.339,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.661,0.0
3320,vsp33_250214_Mo-0.25-W-0.75_pp0_rep1,vsp,33,250214,Mo-0.25-W-0.75,Mo-0.368-W-0.632,1,HER,50,2.706196,...,0.368,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.632,0.0
3321,vsp33_250214_Mo-0.27-W-0.73_pp0_rep1,vsp,33,250214,Mo-0.27-W-0.73,Mo-0.54-W-0.46,1,HER,50,2.684062,...,0.540,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.460,0.0
3322,vsp33_250214_Mo-0.27-W-0.73_pp0_rep2,vsp,33,250214,Mo-0.27-W-0.73,Mo-0.37-W-0.63,2,HER,50,2.737513,...,0.370,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.630,0.0

In [6]:
# Fill any column after "current density" with 0 if nan
if "current density" in main_df.columns:
    idx = main_df.columns.get_loc("current density")
    cols_after_cd = main_df.columns[(idx+1):]
    main_df[cols_after_cd] = main_df[cols_after_cd].fillna(0)

In [7]:
# Export main_df as a CSV file
main_df.to_csv("DashboardData-250923.csv", index=False)