# Column trasnformer

In [127]:
import numpy as np
import pandas as pd

In [128]:
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [129]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [130]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']) ,df['has_covid'], test_size=0.2)


X_train

    age  gender  fever   cough       city
25   23    Male    NaN    Mild     Mumbai
1    27    Male  100.0    Mild      Delhi
42   27    Male  100.0    Mild      Delhi
70   68  Female  101.0  Strong      Delhi
90   59  Female   99.0  Strong      Delhi
..  ...     ...    ...     ...        ...
93   27    Male  100.0    Mild    Kolkata
57   49  Female   99.0  Strong  Bangalore
81   65    Male   99.0    Mild      Delhi
56   71    Male    NaN  Strong    Kolkata
38   49  Female  101.0    Mild      Delhi

[80 rows x 5 columns]

In [131]:
X_train['city'].value_counts(), X_train["cough"].value_counts()

(city
 Kolkata      28
 Delhi        21
 Bangalore    20
 Mumbai       11
 Name: count, dtype: int64,
 cough
 Mild      44
 Strong    36
 Name: count, dtype: int64)

# 1. Aam Zindagi (Without column transformer)

In [132]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [133]:
# adding simple imputer to fever col (handling missing value)
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [134]:
X_train_fever

array([[100.625],
       [100.   ],
       [100.   ],
       [101.   ],
       [ 99.   ],
       [104.   ],
       [104.   ],
       [101.   ],
       [104.   ],
       [ 98.   ],
       [ 98.   ],
       [103.   ],
       [100.   ],
       [103.   ],
       [ 98.   ],
       [101.   ],
       [100.625],
       [102.   ],
       [104.   ],
       [100.   ],
       [100.   ],
       [ 98.   ],
       [102.   ],
       [100.625],
       [104.   ],
       [101.   ],
       [101.   ],
       [ 98.   ],
       [101.   ],
       [104.   ],
       [ 98.   ],
       [103.   ],
       [100.   ],
       [102.   ],
       [ 99.   ],
       [100.625],
       [102.   ],
       [102.   ],
       [ 98.   ],
       [ 98.   ],
       [102.   ],
       [103.   ],
       [104.   ],
       [101.   ],
       [101.   ],
       [101.   ],
       [ 99.   ],
       [101.   ],
       [103.   ],
       [102.   ],
       [ 98.   ],
       [ 98.   ],
       [100.625],
       [100.625],
       [ 98.   ],
       [100.   ],
       [101.   ],
       [ 99.   ],
       [103.   ],
       [ 98.   ],
       [ 98.   ],
       [ 99.   ],
       [ 98.   ],
       [104.   ],
       [ 98.   ],
       [101.   ],
       [103.   ],
       [ 98.   ],
       [100.   ],
       [100.   ],
       [102.   ],
       [104.   ],
       [ 98.   ],
       [100.625],
       [100.   ],
       [100.   ],
       [ 99.   ],
       [ 99.   ],
       [100.625],
       [101.   ]])

In [135]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [136]:
X_train_cough

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.]])

In [137]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [138]:
X_train_gender_city

array([[1., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.]])

In [139]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [140]:
X_train_age

array([[23],
       [27],
       [27],
       [68],
       [59],
       [44],
       [54],
       [51],
       [ 6],
       [71],
       [24],
       [48],
       [19],
       [60],
       [69],
       [ 8],
       [84],
       [ 5],
       [12],
       [11],
       [80],
       [31],
       [20],
       [34],
       [56],
       [64],
       [19],
       [40],
       [42],
       [34],
       [64],
       [73],
       [19],
       [24],
       [66],
       [79],
       [82],
       [82],
       [26],
       [81],
       [64],
       [69],
       [75],
       [47],
       [14],
       [20],
       [72],
       [34],
       [83],
       [49],
       [23],
       [12],
       [38],
       [75],
       [10],
       [55],
       [65],
       [25],
       [70],
       [65],
       [ 5],
       [14],
       [34],
       [16],
       [80],
       [19],
       [46],
       [73],
       [47],
       [ 5],
       [33],
       [25],
       [83],
       [82],
       [13],
       [27],
       [49],
       [65],
       [71],
       [49]])

In [141]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

In [142]:
X_train_transformed

array([[ 23.   , 100.625,   1.   ,   0.   ,   0.   ,   1.   ,   0.   ],
       [ 27.   , 100.   ,   1.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 27.   , 100.   ,   1.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 68.   , 101.   ,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ],
       [ 59.   ,  99.   ,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ],
       [ 44.   , 104.   ,   1.   ,   0.   ,   0.   ,   1.   ,   0.   ],
       [ 54.   , 104.   ,   0.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [ 51.   , 101.   ,   0.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [  6.   , 104.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 71.   ,  98.   ,   0.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [ 24.   ,  98.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 48.   , 103.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 19.   , 100.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ],
       [ 60.   , 103.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 69.   ,  98.   ,   0.   ,   0.   ,   0.   ,   1.   ,   1.   ],
       [  8.   , 101.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 84.   , 100.625,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [  5.   , 102.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 12.   , 104.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 11.   , 100.   ,   0.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [ 80.   , 100.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 31.   ,  98.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 20.   , 102.   ,   1.   ,   1.   ,   0.   ,   0.   ,   1.   ],
       [ 34.   , 100.625,   0.   ,   0.   ,   0.   ,   1.   ,   1.   ],
       [ 56.   , 104.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ],
       [ 64.   , 101.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 19.   , 101.   ,   1.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 40.   ,  98.   ,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ],
       [ 42.   , 101.   ,   1.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 34.   , 104.   ,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ],
       [ 64.   ,  98.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 73.   , 103.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 19.   , 100.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 24.   , 102.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ],
       [ 66.   ,  99.   ,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ],
       [ 79.   , 100.625,   1.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [ 82.   , 102.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ],
       [ 82.   , 102.   ,   0.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [ 26.   ,  98.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 81.   ,  98.   ,   0.   ,   0.   ,   0.   ,   1.   ,   1.   ],
       [ 64.   , 102.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 69.   , 103.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 75.   , 104.   ,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ],
       [ 47.   , 101.   ,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ],
       [ 14.   , 101.   ,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ],
       [ 20.   , 101.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 72.   ,  99.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 34.   , 101.   ,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ],
       [ 83.   , 103.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 49.   , 102.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 23.   ,  98.   ,   1.   ,   0.   ,   0.   ,   1.   ,   1.   ],
       [ 12.   ,  98.   ,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ],
       [ 38.   , 100.625,   1.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 75.   , 100.625,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 10.   ,  98.   ,   0.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [ 55.   , 100.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 65.   , 101.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ],
       [ 25.   ,  99.   ,   0.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [ 70.   , 103.   ,   1.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [ 65.   ,  98.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ],
       [  5.   ,  98.   ,   0.   ,   0.   ,   0.   ,   1.   ,   1.   ],
       [ 14.   ,  99.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ],
       [ 34.   ,  98.   ,   1.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [ 16.   , 104.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 80.   ,  98.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 19.   , 101.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ],
       [ 46.   , 103.   ,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ],
       [ 73.   ,  98.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 47.   , 100.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ],
       [  5.   , 100.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 33.   , 102.   ,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ],
       [ 25.   , 104.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ],
       [ 83.   ,  98.   ,   1.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 82.   , 100.625,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 13.   , 100.   ,   0.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [ 27.   , 100.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ],
       [ 49.   ,  99.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ],
       [ 65.   ,  99.   ,   1.   ,   1.   ,   0.   ,   0.   ,   0.   ],
       [ 71.   , 100.625,   1.   ,   0.   ,   1.   ,   0.   ,   1.   ],
       [ 49.   , 101.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ]])

# 2. Mentos Zindagi (Using column transformer)

In [143]:
from sklearn.compose import ColumnTransformer

In [144]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [145]:
X_train

    age  gender  fever   cough       city
25   23    Male    NaN    Mild     Mumbai
1    27    Male  100.0    Mild      Delhi
42   27    Male  100.0    Mild      Delhi
70   68  Female  101.0  Strong      Delhi
90   59  Female   99.0  Strong      Delhi
..  ...     ...    ...     ...        ...
93   27    Male  100.0    Mild    Kolkata
57   49  Female   99.0  Strong  Bangalore
81   65    Male   99.0    Mild      Delhi
56   71    Male    NaN  Strong    Kolkata
38   49  Female  101.0    Mild      Delhi

[80 rows x 5 columns]

In [146]:
X_train_transformed = transformer.fit_transform(X_train)
X_train_transformed.shape

(80, 7)

In [147]:
X_test_transformed = transformer.transform(X_test)
X_test_transformed.shape

(20, 7)

In [148]:
X_test_transformed

array([[100.625,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  42.   ],
       [101.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ,  81.   ],
       [103.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  16.   ],
       [102.   ,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ,  74.   ],
       [104.   ,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ,  42.   ],
       [101.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  38.   ],
       [100.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  11.   ],
       [104.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,  17.   ],
       [100.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  10.   ],
       [ 99.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ,  60.   ],
       [101.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,  83.   ],
       [101.   ,   0.   ,   1.   ,   1.   ,   0.   ,   0.   ,  15.   ],
       [102.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  69.   ],
       [ 99.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  22.   ],
       [104.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  51.   ],
       [104.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  18.   ],
       [104.   ,   0.   ,   1.   ,   0.   ,   1.   ,   0.   ,  51.   ],
       [100.625,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ,  20.   ],
       [103.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,  50.   ],
       [ 99.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  65.   ]])