In [4]:
import pandas as pd
import os
from yaml import safe_load
from IPython.display import display


def present_results(path: str, val_method: str = "lopo") -> None:
    experiments = [f for f in os.listdir(path) if os.path.isdir(os.path.join(path, f))]
    results = []
    for exp in experiments:
        exp_path = os.path.join(path, exp)
        reports_path = os.path.join(exp_path, "reports.csv")
        if not os.path.exists(reports_path):
            print(f"Skipping {exp_path} as reports.csv does not exist.")
            continue
        report = pd.read_csv(reports_path, index_col=0)
        conf = safe_load(open(os.path.join(exp_path, ".hydra/config.yaml")))
        if conf['validation_method']['_target_'].split(".")[-1].lower() != val_method:
            continue
        model_name: str = conf["model"]["model"]["_target_"].split(".")[-1]
        features_name = (
            conf["feature_extractor"]["_target_"].split(".")[-1]
            if "model_name" not in conf["feature_extractor"]
            else conf["feature_extractor"]["model_name"]
        )
        validation_method = conf["validation_method"]["_target_"].split(".")[-1]
        if "aggregator" not in conf:
            aggregator = "MeanTimeAggregator"
        else:
            aggregator = conf["aggregator"]["_target_"].split(".")[-1] if "_target_" in conf["aggregator"] else None
        acc = report["accuracy"].mean()
        sem_acc = report["accuracy"].sem()
        # Collect results in a list of dicts
        results.append(
            {
                "Model": model_name,
                "Features": features_name,
                "Aggregator": aggregator,
                "Validation": validation_method,
                "Accuracy (%)": f"{acc*100:.0f}",
                "SEM (%)": f"{sem_acc*100:.0f}",
            }
        )

    # After the loop, display as a table
    display(pd.DataFrame(results).sort_values(by=["Model", "Features", "Aggregator"]))

# USILaughs

## Left-side data

### LOPO

In [13]:
import pandas as pd

present_results("../outputs/multirun_2025-06-17_17-42-08")

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
6,DummyClassifier,AutonLab/MOMENT-1-large,CatAggregator,LOPO,56,0
11,DummyClassifier,AutonLab/MOMENT-1-large,MeanChanAggregator,LOPO,56,0
23,DummyClassifier,AutonLab/MOMENT-1-large,MeanTimeAggregator,LOPO,56,0
20,DummyClassifier,AutonLab/MOMENT-1-large,None,LOPO,56,0
16,DummyClassifier,amazon/chronos-t5-large,CatAggregator,LOPO,56,0
1,DummyClassifier,amazon/chronos-t5-large,MeanChanAggregator,LOPO,56,0
13,DummyClassifier,amazon/chronos-t5-large,MeanTimeAggregator,LOPO,56,0
18,DummyClassifier,amazon/chronos-t5-large,None,LOPO,56,0
8,DummyClassifier,amazon/chronos-t5-small,CatAggregator,LOPO,56,0
0,DummyClassifier,amazon/chronos-t5-small,MeanChanAggregator,LOPO,56,0
14,DummyClassifier,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,56,0
22,DummyClassifier,amazon/chronos-t5-small,None,LOPO,56,0
15,LogisticRegression,AutonLab/MOMENT-1-large,CatAggregator,LOPO,53,1
5,LogisticRegression,AutonLab/MOMENT-1-large,MeanChanAggregator,LOPO,54,1
10,LogisticRegression,AutonLab/MOMENT-1-large,MeanTimeAggregator,LOPO,53,1
9,LogisticRegression,AutonLab/MOMENT-1-large,None,LOPO,52,1
17,LogisticRegression,amazon/chronos-t5-large,CatAggregator,LOPO,70,3
7,LogisticRegression,amazon/chronos-t5-large,MeanChanAggregator,LOPO,72,3
2,LogisticRegression,amazon/chronos-t5-large,MeanTimeAggregator,LOPO,69,3
3,LogisticRegression,amazon/chronos-t5-large,None,LOPO,56,0
21,LogisticRegression,amazon/chronos-t5-small,CatAggregator,LOPO,67,4
12,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,LOPO,69,3
4,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,68,4
19,LogisticRegression,amazon/chronos-t5-small,None,LOPO,56,0

,Model,Features,Validation,Accuracy (%),SEM (%)
0,LogisticRegression,HandcraftedFeatureExtractor,LOPO,64,4
1,XGBClassifier,amazon/chronos-t5-small,LOPO,69,4
2,XGBClassifier,HandcraftedFeatureExtractor,LOPO,64,4
3,LogisticRegression,amazon/chronos-t5-small,LOPO,68,4
4,XGBClassifier,amazon/chronos-t5-large,LOPO,69,4
5,DummyClassifier,amazon/chronos-t5-small,LOPO,56,0
6,DummyClassifier,HandcraftedFeatureExtractor,LOPO,56,0
7,LogisticRegression,amazon/chronos-t5-large,LOPO,69,3
8,DummyClassifier,amazon/chronos-t5-large,LOPO,56,0

### TACV

## Right-side data

#### LOPO

In [2]:
present_results("../outputs/multirun_2025-06-18_08-58-59")

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
30,DummyClassifier,AutonLab/MOMENT-1-large,CatAggregator,LOPO,56,0
15,DummyClassifier,AutonLab/MOMENT-1-large,MeanChanAggregator,LOPO,56,0
19,DummyClassifier,AutonLab/MOMENT-1-large,MeanTimeAggregator,LOPO,56,0
1,DummyClassifier,AutonLab/MOMENT-1-large,None,LOPO,56,0
0,DummyClassifier,HandcraftedFeatureExtractor,CatAggregator,LOPO,56,0
20,DummyClassifier,HandcraftedFeatureExtractor,MeanChanAggregator,LOPO,56,0
10,DummyClassifier,HandcraftedFeatureExtractor,MeanTimeAggregator,LOPO,56,0
8,DummyClassifier,HandcraftedFeatureExtractor,None,LOPO,56,0
17,DummyClassifier,amazon/chronos-t5-large,CatAggregator,LOPO,56,0
31,DummyClassifier,amazon/chronos-t5-large,MeanChanAggregator,LOPO,56,0
7,DummyClassifier,amazon/chronos-t5-large,MeanTimeAggregator,LOPO,56,0
11,DummyClassifier,amazon/chronos-t5-large,None,LOPO,56,0
21,DummyClassifier,amazon/chronos-t5-small,CatAggregator,LOPO,56,0
2,DummyClassifier,amazon/chronos-t5-small,MeanChanAggregator,LOPO,56,0
18,DummyClassifier,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,56,0
14,DummyClassifier,amazon/chronos-t5-small,None,LOPO,56,0
9,LogisticRegression,AutonLab/MOMENT-1-large,CatAggregator,LOPO,56,2
13,LogisticRegression,AutonLab/MOMENT-1-large,MeanChanAggregator,LOPO,55,2
29,LogisticRegression,AutonLab/MOMENT-1-large,MeanTimeAggregator,LOPO,56,2
26,LogisticRegression,AutonLab/MOMENT-1-large,None,LOPO,53,2
22,LogisticRegression,HandcraftedFeatureExtractor,CatAggregator,LOPO,72,5
16,LogisticRegression,HandcraftedFeatureExtractor,MeanChanAggregator,LOPO,72,5
25,LogisticRegression,HandcraftedFeatureExtractor,MeanTimeAggregator,LOPO,72,5
4,LogisticRegression,HandcraftedFeatureExtractor,None,LOPO,72,5
28,LogisticRegression,amazon/chronos-t5-large,CatAggregator,LOPO,73,4
3,LogisticRegression,amazon/chronos-t5-large,MeanChanAggregator,LOPO,73,4
27,LogisticRegression,amazon/chronos-t5-large,MeanTimeAggregator,LOPO,76,4
12,LogisticRegression,amazon/chronos-t5-large,None,LOPO,56,0
6,LogisticRegression,amazon/chronos-t5-small,CatAggregator,LOPO,75,4
5,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,LOPO,74,4
23,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,73,5
24,LogisticRegression,amazon/chronos-t5-small,None,LOPO,56,0

In [2]:
present_results("../outputs/multirun_2025-06-23_11-03-31", val_method="lopo")

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
4,XGBClassifier,AutonLab/MOMENT-1-large,CatAggregator,LOPO,55,2
6,XGBClassifier,AutonLab/MOMENT-1-large,MeanChanAggregator,LOPO,41,8
15,XGBClassifier,AutonLab/MOMENT-1-large,MeanTimeAggregator,LOPO,42,6
12,XGBClassifier,AutonLab/MOMENT-1-large,None,LOPO,54,2
8,XGBClassifier,HandcraftedFeatureExtractor,CatAggregator,LOPO,75,4
7,XGBClassifier,HandcraftedFeatureExtractor,MeanChanAggregator,LOPO,42,5
11,XGBClassifier,HandcraftedFeatureExtractor,MeanTimeAggregator,LOPO,63,7
1,XGBClassifier,HandcraftedFeatureExtractor,None,LOPO,75,4
14,XGBClassifier,amazon/chronos-t5-large,CatAggregator,LOPO,73,4
0,XGBClassifier,amazon/chronos-t5-large,MeanChanAggregator,LOPO,51,7
13,XGBClassifier,amazon/chronos-t5-large,MeanTimeAggregator,LOPO,35,6
5,XGBClassifier,amazon/chronos-t5-large,None,LOPO,56,0
3,XGBClassifier,amazon/chronos-t5-small,CatAggregator,LOPO,73,4
2,XGBClassifier,amazon/chronos-t5-small,MeanChanAggregator,LOPO,31,5
9,XGBClassifier,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,46,11
10,XGBClassifier,amazon/chronos-t5-small,None,LOPO,56,0

### TACV

In [3]:
present_results("../outputs/multirun_2025-06-18_13-56-30")

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
30,DummyClassifier,AutonLab/MOMENT-1-large,CatAggregator,TACV,56,0
15,DummyClassifier,AutonLab/MOMENT-1-large,MeanChanAggregator,TACV,56,0
19,DummyClassifier,AutonLab/MOMENT-1-large,MeanTimeAggregator,TACV,56,0
1,DummyClassifier,AutonLab/MOMENT-1-large,None,TACV,56,0
0,DummyClassifier,HandcraftedFeatureExtractor,CatAggregator,TACV,56,0
20,DummyClassifier,HandcraftedFeatureExtractor,MeanChanAggregator,TACV,56,0
10,DummyClassifier,HandcraftedFeatureExtractor,MeanTimeAggregator,TACV,56,0
8,DummyClassifier,HandcraftedFeatureExtractor,None,TACV,56,0
17,DummyClassifier,amazon/chronos-t5-large,CatAggregator,TACV,56,0
31,DummyClassifier,amazon/chronos-t5-large,MeanChanAggregator,TACV,56,0
7,DummyClassifier,amazon/chronos-t5-large,MeanTimeAggregator,TACV,56,0
11,DummyClassifier,amazon/chronos-t5-large,None,TACV,56,0
21,DummyClassifier,amazon/chronos-t5-small,CatAggregator,TACV,56,0
2,DummyClassifier,amazon/chronos-t5-small,MeanChanAggregator,TACV,56,0
18,DummyClassifier,amazon/chronos-t5-small,MeanTimeAggregator,TACV,56,0
14,DummyClassifier,amazon/chronos-t5-small,None,TACV,56,0
9,LogisticRegression,AutonLab/MOMENT-1-large,CatAggregator,TACV,57,3
13,LogisticRegression,AutonLab/MOMENT-1-large,MeanChanAggregator,TACV,58,3
29,LogisticRegression,AutonLab/MOMENT-1-large,MeanTimeAggregator,TACV,57,3
26,LogisticRegression,AutonLab/MOMENT-1-large,None,TACV,54,4
22,LogisticRegression,HandcraftedFeatureExtractor,CatAggregator,TACV,74,4
16,LogisticRegression,HandcraftedFeatureExtractor,MeanChanAggregator,TACV,74,4
25,LogisticRegression,HandcraftedFeatureExtractor,MeanTimeAggregator,TACV,74,4
4,LogisticRegression,HandcraftedFeatureExtractor,None,TACV,74,4
28,LogisticRegression,amazon/chronos-t5-large,CatAggregator,TACV,76,4
3,LogisticRegression,amazon/chronos-t5-large,MeanChanAggregator,TACV,78,5
27,LogisticRegression,amazon/chronos-t5-large,MeanTimeAggregator,TACV,81,4
12,LogisticRegression,amazon/chronos-t5-large,None,TACV,56,0
6,LogisticRegression,amazon/chronos-t5-small,CatAggregator,TACV,80,2
5,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,TACV,77,3
23,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,TACV,77,4
24,LogisticRegression,amazon/chronos-t5-small,None,TACV,56,0

In [3]:
present_results("../outputs/multirun_2025-06-20_10-46-02")

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
4,XGBClassifier,AutonLab/MOMENT-1-large,CatAggregator,TACV,56,2
6,XGBClassifier,AutonLab/MOMENT-1-large,MeanChanAggregator,TACV,57,4
15,XGBClassifier,AutonLab/MOMENT-1-large,MeanTimeAggregator,TACV,56,2
12,XGBClassifier,AutonLab/MOMENT-1-large,None,TACV,56,3
8,XGBClassifier,HandcraftedFeatureExtractor,CatAggregator,TACV,81,3
7,XGBClassifier,HandcraftedFeatureExtractor,MeanChanAggregator,TACV,81,3
11,XGBClassifier,HandcraftedFeatureExtractor,MeanTimeAggregator,TACV,81,3
1,XGBClassifier,HandcraftedFeatureExtractor,None,TACV,81,3
14,XGBClassifier,amazon/chronos-t5-large,CatAggregator,TACV,74,3
0,XGBClassifier,amazon/chronos-t5-large,MeanChanAggregator,TACV,79,3
13,XGBClassifier,amazon/chronos-t5-large,MeanTimeAggregator,TACV,74,3
5,XGBClassifier,amazon/chronos-t5-large,None,TACV,56,0
3,XGBClassifier,amazon/chronos-t5-small,CatAggregator,TACV,76,2
2,XGBClassifier,amazon/chronos-t5-small,MeanChanAggregator,TACV,79,3
9,XGBClassifier,amazon/chronos-t5-small,MeanTimeAggregator,TACV,76,3
10,XGBClassifier,amazon/chronos-t5-small,None,TACV,56,0

# APSYNC (4sec) - engagement (> 4 high, <= 4 low)

## LOPO

In [15]:
present_results("../outputs/multirun_2025-06-24_13-08-52", val_method="lopo")

Skipping ../outputs/multirun_2025-06-24_13-08-52/45 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/28 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/21 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/44 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/36 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/53 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/37 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/52 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/4 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/12 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/13 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/5 as reports.csv does not exist.

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
20,DummyClassifier,HandcraftedFeatureExtractor,CatAggregator,LOPO,47,5
18,DummyClassifier,HandcraftedFeatureExtractor,MeanChanAggregator,LOPO,47,5
2,DummyClassifier,HandcraftedFeatureExtractor,MeanTimeAggregator,LOPO,47,5
1,DummyClassifier,HandcraftedFeatureExtractor,None,LOPO,47,5
8,DummyClassifier,amazon/chronos-t5-large,CatAggregator,LOPO,47,5
0,DummyClassifier,amazon/chronos-t5-large,MeanChanAggregator,LOPO,47,5
3,DummyClassifier,amazon/chronos-t5-large,MeanTimeAggregator,LOPO,47,5
4,DummyClassifier,amazon/chronos-t5-large,None,LOPO,47,5
17,DummyClassifier,amazon/chronos-t5-small,CatAggregator,LOPO,47,5
15,DummyClassifier,amazon/chronos-t5-small,MeanChanAggregator,LOPO,47,5
14,DummyClassifier,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,47,5
13,DummyClassifier,amazon/chronos-t5-small,None,LOPO,47,5
12,LogisticRegression,HandcraftedFeatureExtractor,CatAggregator,LOPO,61,6
7,LogisticRegression,HandcraftedFeatureExtractor,MeanChanAggregator,LOPO,61,6
19,LogisticRegression,HandcraftedFeatureExtractor,MeanTimeAggregator,LOPO,61,6
6,LogisticRegression,HandcraftedFeatureExtractor,None,LOPO,61,6
10,LogisticRegression,amazon/chronos-t5-large,CatAggregator,LOPO,48,5
5,LogisticRegression,amazon/chronos-t5-large,MeanChanAggregator,LOPO,49,8
11,LogisticRegression,amazon/chronos-t5-large,MeanTimeAggregator,LOPO,49,8
21,LogisticRegression,amazon/chronos-t5-large,None,LOPO,49,8
22,LogisticRegression,amazon/chronos-t5-small,CatAggregator,LOPO,46,4
23,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,LOPO,52,7
16,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,49,8
9,LogisticRegression,amazon/chronos-t5-small,None,LOPO,49,8

In [16]:
present_results("../outputs/multirun_2025-06-24_13-40-40", val_method="lopo")

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
0,DummyClassifier,AutonLab/MOMENT-1-large,CatAggregator,LOPO,47,5
10,DummyClassifier,AutonLab/MOMENT-1-large,MeanChanAggregator,LOPO,47,5
5,DummyClassifier,AutonLab/MOMENT-1-large,MeanTimeAggregator,LOPO,47,5
3,DummyClassifier,AutonLab/MOMENT-1-large,None,LOPO,47,5
15,DummyClassifier,amazon/chronos-t5-small,CatAggregator,LOPO,47,5
7,DummyClassifier,amazon/chronos-t5-small,MeanChanAggregator,LOPO,47,5
9,DummyClassifier,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,47,5
1,DummyClassifier,amazon/chronos-t5-small,None,LOPO,47,5
11,LogisticRegression,AutonLab/MOMENT-1-large,CatAggregator,LOPO,45,4
8,LogisticRegression,AutonLab/MOMENT-1-large,MeanChanAggregator,LOPO,49,7
12,LogisticRegression,AutonLab/MOMENT-1-large,MeanTimeAggregator,LOPO,45,4
2,LogisticRegression,AutonLab/MOMENT-1-large,None,LOPO,48,6
4,LogisticRegression,amazon/chronos-t5-small,CatAggregator,LOPO,46,4
6,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,LOPO,52,7
14,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,49,8
13,LogisticRegression,amazon/chronos-t5-small,None,LOPO,49,8

## TACV

In [17]:
present_results("../outputs/multirun_2025-06-24_13-08-52", val_method="tacv")
present_results("../outputs/multirun_2025-06-24_13-40-40", val_method="tacv")

Skipping ../outputs/multirun_2025-06-24_13-08-52/45 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/28 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/21 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/44 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/36 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/53 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/37 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/52 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/4 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/12 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/13 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-24_13-08-52/5 as reports.csv does not exist.

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
17,DummyClassifier,HandcraftedFeatureExtractor,CatAggregator,TACV,53,5
21,DummyClassifier,HandcraftedFeatureExtractor,MeanChanAggregator,TACV,53,5
1,DummyClassifier,HandcraftedFeatureExtractor,MeanTimeAggregator,TACV,53,5
4,DummyClassifier,HandcraftedFeatureExtractor,None,TACV,53,5
12,DummyClassifier,amazon/chronos-t5-large,CatAggregator,TACV,53,5
3,DummyClassifier,amazon/chronos-t5-large,MeanChanAggregator,TACV,53,5
0,DummyClassifier,amazon/chronos-t5-large,MeanTimeAggregator,TACV,53,5
2,DummyClassifier,amazon/chronos-t5-large,None,TACV,53,5
22,DummyClassifier,amazon/chronos-t5-small,CatAggregator,TACV,53,5
15,DummyClassifier,amazon/chronos-t5-small,MeanChanAggregator,TACV,53,5
16,DummyClassifier,amazon/chronos-t5-small,MeanTimeAggregator,TACV,53,5
14,DummyClassifier,amazon/chronos-t5-small,None,TACV,53,5
6,LogisticRegression,HandcraftedFeatureExtractor,CatAggregator,TACV,59,6
9,LogisticRegression,HandcraftedFeatureExtractor,MeanChanAggregator,TACV,59,6
23,LogisticRegression,HandcraftedFeatureExtractor,MeanTimeAggregator,TACV,59,6
10,LogisticRegression,HandcraftedFeatureExtractor,None,TACV,59,6
7,LogisticRegression,amazon/chronos-t5-large,CatAggregator,TACV,53,3
11,LogisticRegression,amazon/chronos-t5-large,MeanChanAggregator,TACV,53,5
5,LogisticRegression,amazon/chronos-t5-large,MeanTimeAggregator,TACV,53,5
20,LogisticRegression,amazon/chronos-t5-large,None,TACV,53,5
19,LogisticRegression,amazon/chronos-t5-small,CatAggregator,TACV,51,2
18,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,TACV,54,4
13,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,TACV,53,5
8,LogisticRegression,amazon/chronos-t5-small,None,TACV,53,5

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
8,DummyClassifier,AutonLab/MOMENT-1-large,CatAggregator,TACV,53,5
15,DummyClassifier,AutonLab/MOMENT-1-large,MeanChanAggregator,TACV,53,5
4,DummyClassifier,AutonLab/MOMENT-1-large,MeanTimeAggregator,TACV,53,5
5,DummyClassifier,AutonLab/MOMENT-1-large,None,TACV,53,5
10,DummyClassifier,amazon/chronos-t5-small,CatAggregator,TACV,53,5
0,DummyClassifier,amazon/chronos-t5-small,MeanChanAggregator,TACV,53,5
9,DummyClassifier,amazon/chronos-t5-small,MeanTimeAggregator,TACV,53,5
7,DummyClassifier,amazon/chronos-t5-small,None,TACV,53,5
14,LogisticRegression,AutonLab/MOMENT-1-large,CatAggregator,TACV,50,2
1,LogisticRegression,AutonLab/MOMENT-1-large,MeanChanAggregator,TACV,54,5
13,LogisticRegression,AutonLab/MOMENT-1-large,MeanTimeAggregator,TACV,50,2
6,LogisticRegression,AutonLab/MOMENT-1-large,None,TACV,54,5
3,LogisticRegression,amazon/chronos-t5-small,CatAggregator,TACV,51,2
2,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,TACV,54,4
11,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,TACV,53,5
12,LogisticRegression,amazon/chronos-t5-small,None,TACV,53,5

# APSYNC (4sec) - enjoyment (> 4 high, <= 4 low)

## LOPO

In [18]:
present_results("../outputs/multirun_2025-06-24_14-40-15", val_method="lopo")

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
16,DummyClassifier,AutonLab/MOMENT-1-large,CatAggregator,LOPO,58,10
22,DummyClassifier,AutonLab/MOMENT-1-large,MeanChanAggregator,LOPO,58,10
4,DummyClassifier,AutonLab/MOMENT-1-large,MeanTimeAggregator,LOPO,58,10
18,DummyClassifier,AutonLab/MOMENT-1-large,None,LOPO,58,10
28,DummyClassifier,HandcraftedFeatureExtractor,CatAggregator,LOPO,58,10
24,DummyClassifier,HandcraftedFeatureExtractor,MeanChanAggregator,LOPO,58,10
2,DummyClassifier,HandcraftedFeatureExtractor,MeanTimeAggregator,LOPO,58,10
1,DummyClassifier,HandcraftedFeatureExtractor,None,LOPO,58,10
10,DummyClassifier,amazon/chronos-t5-large,CatAggregator,LOPO,58,10
0,DummyClassifier,amazon/chronos-t5-large,MeanChanAggregator,LOPO,58,10
3,DummyClassifier,amazon/chronos-t5-large,MeanTimeAggregator,LOPO,58,10
5,DummyClassifier,amazon/chronos-t5-large,None,LOPO,58,10
23,DummyClassifier,amazon/chronos-t5-small,CatAggregator,LOPO,58,10
20,DummyClassifier,amazon/chronos-t5-small,MeanChanAggregator,LOPO,58,10
19,DummyClassifier,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,58,10
17,DummyClassifier,amazon/chronos-t5-small,None,LOPO,58,10
27,LogisticRegression,AutonLab/MOMENT-1-large,CatAggregator,LOPO,55,10
6,LogisticRegression,AutonLab/MOMENT-1-large,MeanChanAggregator,LOPO,57,10
12,LogisticRegression,AutonLab/MOMENT-1-large,MeanTimeAggregator,LOPO,55,10
26,LogisticRegression,AutonLab/MOMENT-1-large,None,LOPO,57,10
15,LogisticRegression,HandcraftedFeatureExtractor,CatAggregator,LOPO,47,7
9,LogisticRegression,HandcraftedFeatureExtractor,MeanChanAggregator,LOPO,47,7
25,LogisticRegression,HandcraftedFeatureExtractor,MeanTimeAggregator,LOPO,47,7
8,LogisticRegression,HandcraftedFeatureExtractor,None,LOPO,47,7
13,LogisticRegression,amazon/chronos-t5-large,CatAggregator,LOPO,54,10
7,LogisticRegression,amazon/chronos-t5-large,MeanChanAggregator,LOPO,58,10
14,LogisticRegression,amazon/chronos-t5-large,MeanTimeAggregator,LOPO,57,10
29,LogisticRegression,amazon/chronos-t5-large,None,LOPO,58,10
30,LogisticRegression,amazon/chronos-t5-small,CatAggregator,LOPO,56,10
31,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,LOPO,58,10
21,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,58,10
11,LogisticRegression,amazon/chronos-t5-small,None,LOPO,58,10

## TACV

In [19]:
present_results("../outputs/multirun_2025-06-24_14-40-15", val_method="tacv")

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
11,DummyClassifier,AutonLab/MOMENT-1-large,CatAggregator,TACV,60,7
18,DummyClassifier,AutonLab/MOMENT-1-large,MeanChanAggregator,TACV,60,7
0,DummyClassifier,AutonLab/MOMENT-1-large,MeanTimeAggregator,TACV,60,7
19,DummyClassifier,AutonLab/MOMENT-1-large,None,TACV,60,7
23,DummyClassifier,HandcraftedFeatureExtractor,CatAggregator,TACV,60,7
27,DummyClassifier,HandcraftedFeatureExtractor,MeanChanAggregator,TACV,60,7
2,DummyClassifier,HandcraftedFeatureExtractor,MeanTimeAggregator,TACV,60,7
5,DummyClassifier,HandcraftedFeatureExtractor,None,TACV,60,7
16,DummyClassifier,amazon/chronos-t5-large,CatAggregator,TACV,60,7
4,DummyClassifier,amazon/chronos-t5-large,MeanChanAggregator,TACV,60,7
1,DummyClassifier,amazon/chronos-t5-large,MeanTimeAggregator,TACV,60,7
3,DummyClassifier,amazon/chronos-t5-large,None,TACV,60,7
28,DummyClassifier,amazon/chronos-t5-small,CatAggregator,TACV,60,7
21,DummyClassifier,amazon/chronos-t5-small,MeanChanAggregator,TACV,60,7
22,DummyClassifier,amazon/chronos-t5-small,MeanTimeAggregator,TACV,60,7
20,DummyClassifier,amazon/chronos-t5-small,None,TACV,60,7
29,LogisticRegression,AutonLab/MOMENT-1-large,CatAggregator,TACV,57,7
15,LogisticRegression,AutonLab/MOMENT-1-large,MeanChanAggregator,TACV,60,7
10,LogisticRegression,AutonLab/MOMENT-1-large,MeanTimeAggregator,TACV,57,7
30,LogisticRegression,AutonLab/MOMENT-1-large,None,TACV,60,7
7,LogisticRegression,HandcraftedFeatureExtractor,CatAggregator,TACV,47,7
12,LogisticRegression,HandcraftedFeatureExtractor,MeanChanAggregator,TACV,47,7
31,LogisticRegression,HandcraftedFeatureExtractor,MeanTimeAggregator,TACV,47,7
13,LogisticRegression,HandcraftedFeatureExtractor,None,TACV,47,7
8,LogisticRegression,amazon/chronos-t5-large,CatAggregator,TACV,60,7
14,LogisticRegression,amazon/chronos-t5-large,MeanChanAggregator,TACV,60,7
6,LogisticRegression,amazon/chronos-t5-large,MeanTimeAggregator,TACV,60,6
26,LogisticRegression,amazon/chronos-t5-large,None,TACV,60,7
25,LogisticRegression,amazon/chronos-t5-small,CatAggregator,TACV,60,7
24,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,TACV,60,7
17,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,TACV,60,7
9,LogisticRegression,amazon/chronos-t5-small,None,TACV,60,7

# APSYNC (10 seconds) - engagement (> 4 high, <= 4 low)

## LOPO

In [13]:
present_results("../outputs/multirun_2025-06-27_18-11-06", val_method="lopo")

Skipping ../outputs/multirun_2025-06-27_18-11-06/20 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/18 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/27 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/9 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/0 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/11 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/7 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/16 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/6 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/17 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/1 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/10 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/19 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/26 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/8 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/21 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/24 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/23 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/4 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/15 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/3 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/12 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/2 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/13 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/5 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/14 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/22 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_18-11-06/25 as reports.csv does not exist.

KeyError: 'Model'

## TACV

In [8]:
present_results("../outputs/multirun_2025-06-27_16-23-32", val_method="tacv")

Skipping ../outputs/multirun_2025-06-27_16-23-32/20 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_16-23-32/18 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_16-23-32/27 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_16-23-32/19 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_16-23-32/26 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_16-23-32/21 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_16-23-32/24 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_16-23-32/23 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_16-23-32/22 as reports.csv does not exist.
Skipping ../outputs/multirun_2025-06-27_16-23-32/25 as reports.csv does not exist.

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
3,DummyClassifier,HandcraftedFeatureExtractor,None,TACV,55,4
2,LogisticRegression,HandcraftedFeatureExtractor,None,TACV,64,7
1,LogisticRegression,amazon/chronos-t5-large,CatAggregator,TACV,49,3
0,LogisticRegression,amazon/chronos-t5-large,None,TACV,53,5

# APSYNC (60 seconds) - engagement (> 4 high, <= 4 low)

## LOPO

In [22]:
present_results("../outputs/multirun_2025-06-24_17-02-26", val_method="lopo")

Skipping ../outputs/multirun_2025-06-24_17-02-26/44 as reports.csv does not exist.

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
13,DummyClassifier,AutonLab/MOMENT-1-large,None,LOPO,33,5
18,DummyClassifier,HandcraftedFeatureExtractor,CatAggregator,LOPO,33,5
0,DummyClassifier,HandcraftedFeatureExtractor,None,LOPO,33,5
6,DummyClassifier,amazon/chronos-t5-large,CatAggregator,LOPO,33,5
1,DummyClassifier,amazon/chronos-t5-large,None,LOPO,33,5
12,DummyClassifier,amazon/chronos-t5-small,None,LOPO,33,5
17,LogisticRegression,AutonLab/MOMENT-1-large,CatAggregator,LOPO,56,10
2,LogisticRegression,AutonLab/MOMENT-1-large,MeanChanAggregator,LOPO,37,7
8,LogisticRegression,AutonLab/MOMENT-1-large,MeanTimeAggregator,LOPO,56,10
16,LogisticRegression,AutonLab/MOMENT-1-large,None,LOPO,39,6
11,LogisticRegression,HandcraftedFeatureExtractor,CatAggregator,LOPO,59,9
5,LogisticRegression,HandcraftedFeatureExtractor,MeanChanAggregator,LOPO,59,9
15,LogisticRegression,HandcraftedFeatureExtractor,MeanTimeAggregator,LOPO,59,9
4,LogisticRegression,HandcraftedFeatureExtractor,None,LOPO,59,9
9,LogisticRegression,amazon/chronos-t5-large,CatAggregator,LOPO,35,6
3,LogisticRegression,amazon/chronos-t5-large,MeanChanAggregator,LOPO,37,4
10,LogisticRegression,amazon/chronos-t5-large,MeanTimeAggregator,LOPO,35,4
19,LogisticRegression,amazon/chronos-t5-large,None,LOPO,35,4
20,LogisticRegression,amazon/chronos-t5-small,CatAggregator,LOPO,54,9
21,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,LOPO,39,3
14,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,39,6
7,LogisticRegression,amazon/chronos-t5-small,None,LOPO,35,4

## TACV

In [23]:
present_results("../outputs/multirun_2025-06-24_17-02-26", val_method="tacv")

Skipping ../outputs/multirun_2025-06-24_17-02-26/44 as reports.csv does not exist.

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
13,DummyClassifier,AutonLab/MOMENT-1-large,None,TACV,43,7
15,DummyClassifier,HandcraftedFeatureExtractor,CatAggregator,TACV,43,7
1,DummyClassifier,HandcraftedFeatureExtractor,None,TACV,43,7
11,DummyClassifier,amazon/chronos-t5-large,CatAggregator,TACV,43,7
0,DummyClassifier,amazon/chronos-t5-large,None,TACV,43,7
14,DummyClassifier,amazon/chronos-t5-small,None,TACV,43,7
19,LogisticRegression,AutonLab/MOMENT-1-large,CatAggregator,TACV,50,17
10,LogisticRegression,AutonLab/MOMENT-1-large,MeanChanAggregator,TACV,40,17
6,LogisticRegression,AutonLab/MOMENT-1-large,MeanTimeAggregator,TACV,50,17
20,LogisticRegression,AutonLab/MOMENT-1-large,None,TACV,40,17
3,LogisticRegression,HandcraftedFeatureExtractor,CatAggregator,TACV,60,12
7,LogisticRegression,HandcraftedFeatureExtractor,MeanChanAggregator,TACV,60,12
21,LogisticRegression,HandcraftedFeatureExtractor,MeanTimeAggregator,TACV,60,12
8,LogisticRegression,HandcraftedFeatureExtractor,None,TACV,60,12
4,LogisticRegression,amazon/chronos-t5-large,CatAggregator,TACV,72,13
9,LogisticRegression,amazon/chronos-t5-large,MeanChanAggregator,TACV,46,14
2,LogisticRegression,amazon/chronos-t5-large,MeanTimeAggregator,TACV,36,4
18,LogisticRegression,amazon/chronos-t5-large,None,TACV,36,4
17,LogisticRegression,amazon/chronos-t5-small,CatAggregator,TACV,65,18
16,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,TACV,72,20
12,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,TACV,49,18
5,LogisticRegression,amazon/chronos-t5-small,None,TACV,36,4

# APSYNC (10sec) - enjoyment (> 4 high, <= 4 low)

## LOPO

In [5]:
present_results("../outputs/multirun_2025-06-25_09-57-48", val_method="lopo")

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
0,DummyClassifier,AutonLab/MOMENT-1-large,CatAggregator,LOPO,58,10
3,DummyClassifier,AutonLab/MOMENT-1-large,MeanChanAggregator,LOPO,58,10
2,DummyClassifier,AutonLab/MOMENT-1-large,MeanTimeAggregator,LOPO,58,10
18,DummyClassifier,AutonLab/MOMENT-1-large,None,LOPO,58,10
14,DummyClassifier,HandcraftedFeatureExtractor,None,LOPO,58,10
11,DummyClassifier,amazon/chronos-t5-large,CatAggregator,LOPO,58,10
9,DummyClassifier,amazon/chronos-t5-large,MeanChanAggregator,LOPO,58,10
19,DummyClassifier,amazon/chronos-t5-large,MeanTimeAggregator,LOPO,58,10
4,DummyClassifier,amazon/chronos-t5-large,None,LOPO,58,10
17,DummyClassifier,amazon/chronos-t5-small,CatAggregator,LOPO,58,10
20,DummyClassifier,amazon/chronos-t5-small,MeanChanAggregator,LOPO,58,10
16,DummyClassifier,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,58,10
1,DummyClassifier,amazon/chronos-t5-small,None,LOPO,58,10
10,LogisticRegression,AutonLab/MOMENT-1-large,CatAggregator,LOPO,55,10
8,LogisticRegression,AutonLab/MOMENT-1-large,MeanChanAggregator,LOPO,58,10
15,LogisticRegression,AutonLab/MOMENT-1-large,MeanTimeAggregator,LOPO,55,10
25,LogisticRegression,AutonLab/MOMENT-1-large,None,LOPO,58,10
6,LogisticRegression,HandcraftedFeatureExtractor,None,LOPO,43,6
24,LogisticRegression,amazon/chronos-t5-large,CatAggregator,LOPO,54,10
22,LogisticRegression,amazon/chronos-t5-large,MeanChanAggregator,LOPO,58,10
21,LogisticRegression,amazon/chronos-t5-large,MeanTimeAggregator,LOPO,54,10
12,LogisticRegression,amazon/chronos-t5-large,None,LOPO,58,10
13,LogisticRegression,amazon/chronos-t5-small,CatAggregator,LOPO,53,9
7,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,LOPO,58,10
23,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,58,10
5,LogisticRegression,amazon/chronos-t5-small,None,LOPO,58,10

## TACV

In [6]:
present_results("../outputs/multirun_2025-06-25_09-57-48", val_method="tacv")

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
6,DummyClassifier,AutonLab/MOMENT-1-large,CatAggregator,TACV,60,7
13,DummyClassifier,AutonLab/MOMENT-1-large,MeanChanAggregator,TACV,60,7
21,DummyClassifier,AutonLab/MOMENT-1-large,MeanTimeAggregator,TACV,60,7
10,DummyClassifier,AutonLab/MOMENT-1-large,None,TACV,60,7
12,DummyClassifier,HandcraftedFeatureExtractor,None,TACV,60,7
14,DummyClassifier,amazon/chronos-t5-large,CatAggregator,TACV,60,7
5,DummyClassifier,amazon/chronos-t5-large,MeanChanAggregator,TACV,60,7
11,DummyClassifier,amazon/chronos-t5-large,MeanTimeAggregator,TACV,60,7
20,DummyClassifier,amazon/chronos-t5-large,None,TACV,60,7
19,DummyClassifier,amazon/chronos-t5-small,CatAggregator,TACV,60,7
0,DummyClassifier,amazon/chronos-t5-small,MeanChanAggregator,TACV,60,7
1,DummyClassifier,amazon/chronos-t5-small,MeanTimeAggregator,TACV,60,7
15,DummyClassifier,amazon/chronos-t5-small,None,TACV,60,7
8,LogisticRegression,AutonLab/MOMENT-1-large,CatAggregator,TACV,63,5
2,LogisticRegression,AutonLab/MOMENT-1-large,MeanChanAggregator,TACV,60,7
9,LogisticRegression,AutonLab/MOMENT-1-large,MeanTimeAggregator,TACV,63,5
3,LogisticRegression,AutonLab/MOMENT-1-large,None,TACV,60,7
22,LogisticRegression,HandcraftedFeatureExtractor,None,TACV,45,9
18,LogisticRegression,amazon/chronos-t5-large,CatAggregator,TACV,57,7
4,LogisticRegression,amazon/chronos-t5-large,MeanChanAggregator,TACV,60,7
7,LogisticRegression,amazon/chronos-t5-large,MeanTimeAggregator,TACV,56,8
23,LogisticRegression,amazon/chronos-t5-large,None,TACV,60,7
17,LogisticRegression,amazon/chronos-t5-small,CatAggregator,TACV,56,7
16,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,TACV,60,7
25,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,TACV,60,7
24,LogisticRegression,amazon/chronos-t5-small,None,TACV,60,7

# APSYNC (10 seconds) - immersion (> 4 high, <= 4 low)

## LOPO

In [2]:
present_results("../outputs/multirun_2025-06-26_10-15-52", val_method="lopo")

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
1,DummyClassifier,HandcraftedFeatureExtractor,None,LOPO,22,8
3,LogisticRegression,AutonLab/MOMENT-1-large,CatAggregator,LOPO,24,8
7,LogisticRegression,AutonLab/MOMENT-1-large,MeanChanAggregator,LOPO,22,7
0,LogisticRegression,AutonLab/MOMENT-1-large,MeanTimeAggregator,LOPO,24,8
4,LogisticRegression,AutonLab/MOMENT-1-large,None,LOPO,23,8
5,LogisticRegression,HandcraftedFeatureExtractor,None,LOPO,27,7
9,LogisticRegression,amazon/chronos-t5-large,CatAggregator,LOPO,27,9
8,LogisticRegression,amazon/chronos-t5-large,MeanChanAggregator,LOPO,25,9
13,LogisticRegression,amazon/chronos-t5-large,MeanTimeAggregator,LOPO,24,7
11,LogisticRegression,amazon/chronos-t5-large,None,LOPO,20,7
2,LogisticRegression,amazon/chronos-t5-small,CatAggregator,LOPO,33,6
10,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,LOPO,25,8
12,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,LOPO,20,7
6,LogisticRegression,amazon/chronos-t5-small,None,LOPO,20,7

## TACV

In [3]:
present_results("../outputs/multirun_2025-06-26_10-15-52", val_method="tacv")

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
11,DummyClassifier,HandcraftedFeatureExtractor,None,TACV,51,4
7,LogisticRegression,AutonLab/MOMENT-1-large,CatAggregator,TACV,41,9
12,LogisticRegression,AutonLab/MOMENT-1-large,MeanChanAggregator,TACV,52,10
9,LogisticRegression,AutonLab/MOMENT-1-large,MeanTimeAggregator,TACV,41,9
0,LogisticRegression,AutonLab/MOMENT-1-large,None,TACV,48,10
10,LogisticRegression,HandcraftedFeatureExtractor,None,TACV,30,7
4,LogisticRegression,amazon/chronos-t5-large,CatAggregator,TACV,47,9
1,LogisticRegression,amazon/chronos-t5-large,MeanChanAggregator,TACV,50,10
5,LogisticRegression,amazon/chronos-t5-large,MeanTimeAggregator,TACV,50,10
3,LogisticRegression,amazon/chronos-t5-large,None,TACV,54,10
13,LogisticRegression,amazon/chronos-t5-small,CatAggregator,TACV,43,5
6,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,TACV,45,9
2,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,TACV,54,10
8,LogisticRegression,amazon/chronos-t5-small,None,TACV,54,10

# SEED (10 seconds, median)

## LOPO

In [2]:
present_results("../outputs/multirun_2025-06-27_16-33-37", val_method="lopo")

Skipping ../outputs/multirun_2025-06-27_16-33-37/3 as reports.csv does not exist.

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
0,DummyClassifier,HandcraftedFeatureExtractor,None,LOPO,84,6
1,LogisticRegression,HandcraftedFeatureExtractor,None,LOPO,84,6
2,LogisticRegression,amazon/chronos-t5-large,None,LOPO,84,6

## TACV

In [3]:
present_results("../outputs/multirun_2025-06-26_10-15-52", val_method="tacv")

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
11,DummyClassifier,HandcraftedFeatureExtractor,None,TACV,51,4
7,LogisticRegression,AutonLab/MOMENT-1-large,CatAggregator,TACV,41,9
12,LogisticRegression,AutonLab/MOMENT-1-large,MeanChanAggregator,TACV,52,10
9,LogisticRegression,AutonLab/MOMENT-1-large,MeanTimeAggregator,TACV,41,9
0,LogisticRegression,AutonLab/MOMENT-1-large,None,TACV,48,10
10,LogisticRegression,HandcraftedFeatureExtractor,None,TACV,30,7
4,LogisticRegression,amazon/chronos-t5-large,CatAggregator,TACV,47,9
1,LogisticRegression,amazon/chronos-t5-large,MeanChanAggregator,TACV,50,10
5,LogisticRegression,amazon/chronos-t5-large,MeanTimeAggregator,TACV,50,10
3,LogisticRegression,amazon/chronos-t5-large,None,TACV,54,10
13,LogisticRegression,amazon/chronos-t5-small,CatAggregator,TACV,43,5
6,LogisticRegression,amazon/chronos-t5-small,MeanChanAggregator,TACV,45,9
2,LogisticRegression,amazon/chronos-t5-small,MeanTimeAggregator,TACV,54,10
8,LogisticRegression,amazon/chronos-t5-small,None,TACV,54,10

# BiHearts (10min)

In [12]:
present_results("../outputs_usilaughs_right/multirun_2025-06-30_11-53-58", val_method="lopo")

Skipping ../outputs_usilaughs_right/multirun_2025-06-30_11-53-58/3 as reports.csv does not exist.

,Model,Features,Aggregator,Validation,Accuracy (%),SEM (%)
0,DummyClassifier,HandcraftedFeatureExtractor,None,LOPO,56,0
1,LogisticRegression,HandcraftedFeatureExtractor,None,LOPO,73,5
2,LogisticRegression,amazon/chronos-t5-large,None,LOPO,56,0