In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('tweets_dataframe.csv',sep='\t')

In [81]:
df.head()

,id,text,user.favourites_count,user.id,lang,user.followers_count,user.verified,truncated
0,593891099434983425,RT @KirkKus: Indirect cost of the UK being in ...,31150,107794703,en,804,False,False
1,593891099548094465,VIDEO: Sturgeon on post-election deals http://...,0,557422508,en,184,False,False
2,593891099388846080,RT @LabourEoin: The economy was growing 3 time...,7565,3006692193,en,182,False,False
3,593891100429045760,RT @GregLauder: the UKIP east lothian candidat...,2130,455154030,en,1073,False,False
4,593891100768784384,RT @thesundaypeople: UKIP's housing spokesman ...,131,187547338,en,87,False,False

In [82]:
df['text'][0]

'RT @KirkKus: Indirect cost of the UK being in the EU is estimated to be costing Britain \xc2\xa3170 billion per year! #BetterOffOut #UKIP'

In [3]:
from nltk.corpus import stopwords

In [4]:
stopwords = set(stopwords.words('english'))

In [5]:
import os

In [6]:
os.getcwd()

'/home/mradul/2projectdaddy/data_project/project/twitter-files'

In [7]:
stopwords_path = os.getcwd() + '/stopwords'

In [8]:
import re
for each in os.listdir(stopwords_path):
    each = stopwords_path + '/' + each
    with open(each,'r') as f:
        for line in f:
            for word in re.findall(r'\w+', line):
                stopwords.add(word) #We want all stopwords, in the set we made earlier.

In [9]:
len(stopwords) #This is interesting. The /stopwords directory has 38517 unique stopwords(focused at twitter). 
#The nltk.corpus stopwords had only 5 words which weren't there in the directory.

38522

In [90]:
df.drop('id',axis=1).head()  #axis=1 refers to the vertical columns.

,text,user.favourites_count,user.id,lang,user.followers_count,user.verified,truncated
0,RT @KirkKus: Indirect cost of the UK being in ...,31150,107794703,en,804,False,False
1,VIDEO: Sturgeon on post-election deals http://...,0,557422508,en,184,False,False
2,RT @LabourEoin: The economy was growing 3 time...,7565,3006692193,en,182,False,False
3,RT @GregLauder: the UKIP east lothian candidat...,2130,455154030,en,1073,False,False
4,RT @thesundaypeople: UKIP's housing spokesman ...,131,187547338,en,87,False,False

In [91]:
df.head() #Not in-plcae i.e original df no affected by drop().

,id,text,user.favourites_count,user.id,lang,user.followers_count,user.verified,truncated
0,593891099434983425,RT @KirkKus: Indirect cost of the UK being in ...,31150,107794703,en,804,False,False
1,593891099548094465,VIDEO: Sturgeon on post-election deals http://...,0,557422508,en,184,False,False
2,593891099388846080,RT @LabourEoin: The economy was growing 3 time...,7565,3006692193,en,182,False,False
3,593891100429045760,RT @GregLauder: the UKIP east lothian candidat...,2130,455154030,en,1073,False,False
4,593891100768784384,RT @thesundaypeople: UKIP's housing spokesman ...,131,187547338,en,87,False,False

In [92]:
df.drop('id',axis=1,inplace=True)

In [93]:
df.head() #Original Dataframe changed.

,text,user.favourites_count,user.id,lang,user.followers_count,user.verified,truncated
0,RT @KirkKus: Indirect cost of the UK being in ...,31150,107794703,en,804,False,False
1,VIDEO: Sturgeon on post-election deals http://...,0,557422508,en,184,False,False
2,RT @LabourEoin: The economy was growing 3 time...,7565,3006692193,en,182,False,False
3,RT @GregLauder: the UKIP east lothian candidat...,2130,455154030,en,1073,False,False
4,RT @thesundaypeople: UKIP's housing spokesman ...,131,187547338,en,87,False,False

In [94]:
df.loc[0]

text                     RT @KirkKus: Indirect cost of the UK being in ...
user.favourites_count                                                31150
user.id                                                          107794703
lang                                                                    en
user.followers_count                                                   804
user.verified                                                        False
truncated                                                            False
Name: 0, dtype: object

In [95]:
import numpy as np
df['links'] = np.nan   #Adding new column for urls present in the tweets.

In [96]:
for i in xrange(2000):
    tweet = df.loc[i]['text']
    tweet = tweet.split()
    write_tweet = ""
    #urls present in the tweet.
    urls = []
    for each in tweet:
        if each not in stopwords:
            write_tweet += ' ' + each
    #url for the tweet saved in the corresponding column.
    urls = re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', write_tweet)
    for url in urls:
        #print url
        df.loc[i,('links')] = url

In [97]:
df.head()

,text,user.favourites_count,user.id,lang,user.followers_count,user.verified,truncated,links
0,RT @KirkKus: Indirect cost of the UK being in ...,31150,107794703,en,804,False,False,NaN
1,VIDEO: Sturgeon on post-election deals http://...,0,557422508,en,184,False,False,http://t.co/BTJwrpbmOY
2,RT @LabourEoin: The economy was growing 3 time...,7565,3006692193,en,182,False,False,http://t.co
3,RT @GregLauder: the UKIP east lothian candidat...,2130,455154030,en,1073,False,False,http://t.co/7eIU0c5Fm1
4,RT @thesundaypeople: UKIP's housing spokesman ...,131,187547338,en,87,False,False,http://t.co/c1AZxcLh

In [98]:
from collections import Counter

In [99]:
Counter(" ".join(df["text"]).split()).most_common(100)

[('RT', 13500),
 ('the', 10444),
 ('to', 7472),
 ('a', 5778),
 ('of', 5525),
 ('in', 5042),
 ('Miliband', 4609),
 ('is', 4323),
 ('with', 3581),
 ('Tories', 3403),
 ('and', 3338),
 ('on', 3215),
 ('SNP', 2864),
 ('for', 2584),
 ('Ed', 2538),
 ('I', 2291),
 ('that', 2137),
 ('Labour', 2086),
 ('Cameron', 2028),
 ('#bbcqt', 2025),
 ('will', 1977),
 ('-', 1968),
 ('it', 1939),
 ('than', 1918),
 ('you', 1883),
 ('The', 1849),
 ('not', 1700),
 ('David', 1661),
 ('out', 1621),
 ('he', 1608),
 ('have', 1522),
 ('rather', 1519),
 ('be', 1416),
 ('Farage', 1370),
 ('are', 1362),
 ('Tory', 1339),
 ('UKIP', 1252),
 ('would', 1226),
 ('was', 1183),
 ('if', 1171),
 ('who', 1160),
 ('let', 1127),
 ('as', 1122),
 ('#AskNigelFarage', 1104),
 ('we', 1080),
 ('deal', 1055),
 ('&amp;', 1055),
 ('If', 1054),
 ('has', 1045),
 ('vote', 1030),
 ('work', 1013),
 ('do', 1007),
 ('by', 999),
 ('just', 989),
 ('they', 949),
 ('but', 927),
 ('his', 917),
 ('support', 914),
 ('all', 913),
 ('from', 879),
 ('about', 867),
 ('#UKIP', 866),
 ('Nigel', 864),
 ('going', 792),
 ('Clegg', 784),
 ('no', 772),
 ('claiming', 772),
 ('says', 767),
 ('\xe2\x80\xa6', 760),
 ('come', 750),
 ('man', 745),
 ('people', 738),
 ('an', 716),
 ('http:/\xe2\x80\xa6', 702),
 ('more', 681),
 ('this', 666),
 ('need', 665),
 ('SNP,', 663),
 ('leader', 663),
 ('w/', 653),
 ('MPs', 646),
 ('at', 637),
 ('wrote', 636),
 ('like', 635),
 ('"preoccupied', 634),
 ('so', 623),
 ('inequality".', 622),
 ('@Tommy_Colc:', 622),
 ('up', 620),
 ("I'm", 614),
 ('want', 613),
 ('#GE2015', 611),
 ('over', 605),
 ('what', 604),
 ('get', 601),
 ('or', 588),
 ('Scotland', 583),
 ('can', 578),
 ('#SNP', 549),
 ('Times', 509)]

In [100]:
#Adding new stopwords after analyzing the 100 most frequently used words/punctuations used in the dataset.
for each in ['rt','lolz','.',';',"'",'"',"i've",'the','to','a','of','in','on','is','and','i','-','it']:
    stopwords.add(each)

In [15]:
#Convert whole text to lower case run the Stopwrods removal again. Should have done it earlier. I added it later.
for i in xrange(2000):
    tweet = df.loc[i]['text'].lower()
    #Write the lowercase text into the dataframe.
    df.replace(df.loc[i]['text'],tweet,inplace=True)

In [15]:
#First I did this step without regex i.e. just plain split(), then I used regex, then both, look below.
for i in xrange(2000):
    tweet = df.loc[i]['text']
    tweet = tweet.split()
    write_tweet = ""
    for each in tweet:
        words = re.findall(r'\w+',each)
        for word in words:
            if word not in stopwords:
                write_tweet += ' ' + each #I use each instead of word to preserve '$170','#betterofout' etc.
                #They would become '170','betterofout' otherwise.
                
    #Write the stopword-free text into the dataframe.
    df.replace(df.loc[i]['text'],write_tweet,inplace=True)
    #print ' '.join(tweet),write_tweet

indirect eu costing britain £170 year! #betteroffout #ukip  indirect eu costing britain £170 #betteroffout #ukip
video: sturgeon post-election deals  sturgeon post-election deals
growing david minister today.. #bbcqt …  growing david minister #bbcqt
ukip lothian 16 msn addy  ukip lothian 16 msn addy
ukip's spokesman rakes £800k benefit migrants. http://t.co/gvwb9rcb4w …  ukip's spokesman rakes £800k benefit migrants. http://t.co/gvwb9rcb4w
#asknigelfarage bbc 22:50! #ukip  #asknigelfarage bbc 22:50! 22:50! #ukip
milliband embarrassment. representing uk?! #bbcqt @conservatives  milliband embarrassment. representing #bbcqt
ft backing tories. unrelated note, here's ft leader jonathan ford (next boris) …  ft backing tories. unrelated ft leader jonathan ford boris)
“@george_osborne: miliband proved he's job” tbf you've salivating do…  “@george_osborne: miliband proved tbf salivating
trickle wealth. it's trickling wallets. greed $$$ greedy.  trickle trickling wallets. greed
snp leader faces  snp leader faces
"ed milliband hanging russell brand. joke. election. people' http:/…  milliband hanging russell election.
miliband: labour overspend http://t.co/w9rj2ash6o  miliband: labour overspend http://t.co/w9rj2ash6o
miliband refusing snp, government?  miliband refusing snp,
it. labour tory snp.  labour tory snp.
contest election poll: london (reuters) minister david the…  contest election poll: london minister david
@dunleavy138 @crillybobc @thesnp @uklabour snp, @ed_miliband clear. w…  @dunleavy138 @crillybobc @thesnp @uklabour snp, @ed_miliband
@edmiliband_mp socialists chose lp snp! #snp last,  @edmiliband_mp socialists chose lp snp! #snp
watch: miliband trips stage  miliband trips stage
ft backing tories. unrelated ft leader jonathan ford boris)  ft backing tories. unrelated ft leader jonathan ford boris)
@b0mbskare anti-scottish largely tory scaremongering. won't toss!  @b0mbskare anti-scottish largely tory scaremongering.
miliband stumbles, dodges  miliband stumbles, dodges
miliband i'd scots nationalists: london (reuters) british labour party…  miliband scots nationalists: london british labour
govt's david he's tories  govt's david tories
dropped snp badge kilmarnock it. …  dropped snp badge kilmarnock
sun’s worm appears miliband #bbcqt  sun’s worm appears miliband #bbcqt
@scottishpleb @ahairybiker snp toxic england. labour them?  @scottishpleb @ahairybiker snp toxic england. labour
i'm #snpbecause entire adult labour &amp; tories misery, war, victimisation t…  #snpbecause entire adult labour &amp; tories misery, victimisation
jeremy vine doesn't snp scottish takeover merits  jeremy vine snp scottish takeover merits
"ukip bastard parties. apologies bastards." @petertatchell university …  "ukip bastard parties. apologies bastards." @petertatchell university
“@suttonnick: friday's page: miliband savaged ‘lies’ #tomorrowspaperstoday #bbcpapers ”  “@suttonnick: miliband savaged #tomorrowspaperstoday #bbcpapers
scenes celebration glasgow #snp #conservative victory. fun. it? :-) …  scenes celebration glasgow #snp victory.
@kthopkins snp thickos power, bringing fair, decent fascists detest!  @kthopkins snp thickos bringing fair, decent fascists detest!
humongous david cameron. clamped avoidance. uncollected risen #bbcqt http:/…  humongous david clamped avoidance. uncollected risen #bbcqt
tory dad: "if ukip chance i'd them." *5 later* "you blinkered!!! minded!!" sure?  tory ukip chance blinkered!!!
tonight's polling average: con 33.7%, lab 33%, ukip 13%, lib 8% 5.7%.  polling con 33.7%, lab 33%, ukip lib
.@mik61scot it's nicola sturgeon's policy... literacy deprive helicop…  .@mik61scot nicola sturgeon's literacy deprive helicop…
guardian page, 2015: miliband hardens line: snp  guardian 2015: miliband hardens snp
@scotlandtonight wont deal. #snp forgiven labour go…  @scotlandtonight wont #snp forgiven labour
clear: coalition deals snp. #bbcqt  coalition deals snp. #bbcqt
tory david cameron's #bbcqt http://t.co/yihdlg5nvo …  tory david #bbcqt http://t.co/yihdlg5nvo
@nigel_farage ed's rejection lab/snp undermine cameron's plea ukippers 'come home' basis proposal?  @nigel_farage rejection lab/snp lab/snp undermine plea ukippers basis proposal?
coalition deals snp. #bbcqt  coalition deals snp. #bbcqt
union, promising scotland's voice heard, refusing deal…  union, promising scotland's voice refusing
penny? time? long!  penny?
@jimforscotland statements confirms decision labour snp.tim…  @jimforscotland statements confirms decision labour snp.tim… snp.tim…
great, reduced deficit, poor. job. bragging torie…  reduced bragging torie…
clegg: coalition 'red line' itv  coalition itv
ns 8. #prettyplease  ns #prettyplease
biased #bbc allowing @nigel_farage #leadersdebate program own... #nigelfarage #ukip #ge2015  biased #bbc allowing @nigel_farage #leadersdebate program #nigelfarage #ukip #ge2015
'i'm cave snp trident deficit'. left-wing nuclear weapons maintaing  cave snp trident nuclear weapons maintaing
miliband then, "ah, recruitment? you're dick." i'd him. d…  miliband recruitment?
oh, tories. wiz zis spoiling uz.  tories. wiz zis spoiling uz.
miliband time: won't labour snp #ge2015  miliband labour snp #ge2015
sturgeon post-election deals  sturgeon post-election deals
miliband trips stage  miliband trips stage
scottish sturgeon "nicola". qt "mr cameron", "mr miliband" &amp; "mr clegg". …  scottish sturgeon "nicola". qt miliband" &amp;
@scotlandtonight miliband tories in, 59 snp mps scotland @thesnp #votesnp  @scotlandtonight miliband tories 59 snp mps scotland @thesnp #votesnp
milliband's pronouncements........ dear.... scots.... #votesnp  milliband's pronouncements........ scots.... #votesnp
#newsnight farage cr*p hour. call; farage w/audience questions..  #newsnight farage cr*p farage
like/support
labour supporters/country @ed_miliband tories refusing coalition with…  labour supporters/country @ed_miliband tories refusing coalition
guardian 2015: miliband hardens snp  guardian 2015: miliband hardens snp
couldn't q&amp;as scholarship dinner, argued labour doesn't snp  q&amp;as scholarship argued labour snp
scots lab tories miliband snp, stewart hosie  scots lab tories miliband snp, stewart hosie
miliband trusting eu. him? …  miliband trusting eu.
ukip's spokesman rakes £800k benefit migrants. http://t.co/gvwb9rcb4w  ukip's spokesman rakes £800k benefit migrants. http://t.co/gvwb9rcb4w
snp leader faces  snp leader faces
gov poll lab 35% (+1) con 34% (-1) ukip 12% (-) ldem 8% (-1) grn 5% (+1)  gov poll lab 35% con 34% ukip ldem grn
miliband trusting eu.  miliband trusting eu.
labour snp bluff. snp clear: labour &amp;…  labour snp snp labour &amp;…
"making cards here, he's tory"  cards tory"
member: million's foodbanks? david cameron: here's letter there's  member: foodbanks? david letter
david hugs husky storms #david #hugahusky #davidcamerontweet #greatstorm 2013 #stjude  david hugs husky storms #david #hugahusky #davidcamerontweet #greatstorm 2013 #stjude
#bbcqt tories introduced pfi nhs labour. here's ken clarke boasting it.  #bbcqt tories introduced pfi nhs labour. ken clarke boasting
it's labour minority govt tories. miliband snp's bluff, n…  labour minority govt tories. miliband snp's
fair point......  fair
learnt david wouldn't tonight: tories benefit #b…  learnt david tories benefit
miliband trips stage  miliband trips stage
#sunnation exclusive: slipping stage... http://t.co/wz7bitsezb …  #sunnation slipping stage... http://t.co/wz7bitsezb
miliband stage... country?!?!?!????  miliband stage...
#bbcbias party/leader @bbcnews lab con lib snp ukip 0  #bbcbias party/leader @bbcnews lab con lib snp ukip 0
@rogerv52 @ukip 100% nigel  @rogerv52 @ukip 100% nigel
@daniel__brookes @sarahduk121 @nigel_farage @ukip that's tad semantic? election  @daniel__brookes @sarahduk121 @nigel_farage @ukip tad semantic? election
yougov poll (29 30 apr): lab 35% (+1) con 34% (-1) ukip 12% (-) ldem 8% (-1) grn 5% (+1)  yougov poll (29 30 lab 35% con 34% ukip ldem grn
historic labour snp | @telegraph  historic labour snp @telegraph
miliband's denial squandering money. don't  miliband's denial squandering
murphy scotland intelligence. milliband london demeans scots. scots down…  murphy scotland milliband london demeans scots. scots
#ukip #farageforever  #ukip #farageforever
mk assembly commitment wage. tory opponent.  mk assembly commitment wage. tory opponent.
icm 6% #bbcqt viewers mind. sample but: 32% switchers, cam 25% 20% http:/…  icm #bbcqt viewers sample 32% switchers, cam 25%
miliband trips stage  miliband trips stage
russell heads streets. miliband to…  russell heads miliband
so, bbc time's election leaders, miliband relented the...  bbc election miliband relented
bbc scotlands entire 'nicola sturgeon won't rule she's ruled out'  bbc scotlands entire 'nicola sturgeon rule ruled
leaked #tories feared "inevitable "election defeat flags, muddying wate…  leaked #tories feared "inevitable "election defeat flags, muddying wate…
labour snp mistake! scotland rule uk!  labour snp mistake! scotland rule
libdem leader said, decision 5yrs ago, britain becm greece; impact  libdem leader decision 5yrs britain becm impact
lucy powell miliband's trip: "ed david cameron's sweat." #ge2015 #bbcqt  lucy powell miliband's david #ge2015 #bbcqt
slags miliband meeting russell brand, mind?  slags miliband meeting russell
david benefit "key" http://t.co/jsd8jb1lya #bbcqt  david benefit http://t.co/jsd8jb1lya #bbcqt
tory david #bbcqt http://t.co/yihdlg5nvo  tory david #bbcqt http://t.co/yihdlg5nvo
@bbcnickrobinson tories. lame. predictable lame. #bbcqt  @bbcnickrobinson tories. predictable #bbcqt
@danielmancip i'm nationalist ... don't snp, won't snp unionist nationalist  @danielmancip nationalist snp, snp unionist nationalist
david liam byrne pocket tomorrow. 'everywhere' #bb…  david liam byrne pocket
bbc emphasis milliband's session who…  bbc emphasis milliband's session
@johnmcternan @lenathehyena @uklabour @ed_miliband queen gov fewer mps tories place.  @johnmcternan @lenathehyena @uklabour @ed_miliband queen gov fewer mps tories
#snpbecause #snp #votesnp @ianiwrussell @ianbarr67 @eileen43eileen @zen432 @shellxdoherty84 @katiekhaleesi …  #snpbecause #snp #votesnp @ianiwrussell @ianbarr67 @eileen43eileen @zen432 @shellxdoherty84 @katiekhaleesi
guardian 2015: miliband hardens snp  guardian 2015: miliband hardens snp
david backing £15 museum &amp; library dedicated maggie thatcher. £15 million. off.  david backing £15 museum &amp; library dedicated maggie thatcher. £15
tory chums don't following. wow! commanding tonight. #v…  tory chums commanding
@simonk133 @roadto326 tories front.  @simonk133 @roadto326 tories
miliband trips stage  miliband trips stage
.@ed_miliband 'nodded' keeping austerity, formula. i, too, surprised didn't expand.  .@ed_miliband 'nodded' keeping formula. surprised
miliband stage...  miliband stage...
@rogerv52 @ukip 100% nigel  @rogerv52 @ukip 100% nigel
yougov poll (29 30 lab 35% con 34% ukip ldem grn  yougov poll (29 30 lab 35% con 34% ukip ldem grn
fair  fair
relaxed demeanour he'll deputy *someone* 8th.  relaxed demeanour deputy 8th.
murphy scotland milliband london demeans scots. scots  murphy scotland milliband london demeans scots. scots
lucy powell miliband's david #ge2015 #bbcqt  lucy powell miliband's david #ge2015 #bbcqt
slags miliband meeting russell  slags miliband meeting russell
@danielmancip nationalist snp, snp unionist nationalist  @danielmancip nationalist snp, snp unionist nationalist
david liam byrne pocket  david liam byrne pocket
@johnmcternan @lenathehyena @uklabour @ed_miliband queen gov fewer mps tories  @johnmcternan @lenathehyena @uklabour @ed_miliband queen gov fewer mps tories
unexpectedly, ukip coat arms passport.  ukip coat arms passport.
#snpbecause #snp #votesnp @ianiwrussell @ianbarr67 @eileen43eileen @zen432 @shellxdoherty84 @katiekhaleesi  #snpbecause #snp #votesnp @ianiwrussell @ianbarr67 @eileen43eileen @zen432 @shellxdoherty84 @katiekhaleesi
tim farron "miliband ruled reality"  tim farron "miliband ruled reality"
@mrjamesmack conceivable situation snp labour (bar trident) compromising "locking tories out"?  @mrjamesmack conceivable situation snp labour trident) compromising "locking tories
edm’s he’s snp. british ht…  edm’s snp. british ht…
#ukip “@perform: ”  #ukip
@johnhemming4mp forgot @jessphillips one. ops. fair chance rebuttal. figs clear: @libdem :)  @johnhemming4mp forgot @jessphillips fair chance rebuttal. figs @libdem
daft ukip password tonight. licking type!  daft ukip password licking
havens #bbcqt pourquoi? cameron’s father offshore assets jersey http:…  havens #bbcqt pourquoi? father offshore assets jersey
endeth union! @the45storm @jimforscotland @ed_miliband  endeth union! @the45storm @jimforscotland @ed_miliband
#alexsalmond's #referendum #snp #alexsalmond  #alexsalmond's #referendum #snp #alexsalmond
tonight's cameron, milliband &amp; ideal games bullshit bingo.  milliband &amp; ideal games bullshit bingo.
coalition deals snp. #bbcqt  coalition deals snp. #bbcqt
parties snp spite, they're disenfranchising scottish indy up.  parties snp disenfranchising scottish indy
party's entire "threat" snp bringing tory gov, brin…  entire "threat" snp bringing tory gov, brin…
@andrewcoleman1 @bbcjamescook @nicolasturgeon milliband he'd tory govt snp backing #redtories?  @andrewcoleman1 @bbcjamescook @nicolasturgeon milliband tory govt snp backing #redtories?
occasion? ham actors "b" movie.  occasion? ham actors
#miliband "tough" immigration. @uklabour printing "how benefits" 174 diffe…  #miliband @uklabour printing benefits" 174 diffe…
grimly, labour round, please, ruling snp deals.  labour ruling snp deals.
@cigar117 farage carswell likely, others. showing lib dems. gonner.  @cigar117 farage carswell showing lib gonner.
david cameron's father assets offshore  david father assets offshore
miliband trusting eu.  miliband trusting eu.
miliband trusting eu.  miliband trusting eu.
@yetigcreature @royhendo ukip cosy tories labour snp this.  @yetigcreature @royhendo ukip cosy tories labour snp
kezia doll pure clown hen !!! #snp  kezia doll pure clown hen #snp
labour tories power, wales them. #ge2015  labour tories wales #ge2015
david  david
miliband sacrificed @scottishlabour he'd tories #snp #mili…  miliband sacrificed @scottishlabour tories #snp #mili…
@thimbleofgrace ukip with?  @thimbleofgrace ukip
won't miliband household budget? #bbcqt  miliband household #bbcqt
miliband 'reverse vow'. effective 'no deal' 'tory threat'. @bbcscotl…  miliband effective 'tory threat'. @bbcscotl…
@ed_miliband coalition disaster snp.you'll realistic .if agree-what's problem?  @ed_miliband coalition disaster snp.you'll realistic
#bbcqt miliband:"we coalition snp" bollocks fav "i'm be…  #bbcqt miliband:"we coalition snp" bollocks fav
aw miliband, scottish #bbcqt  aw miliband, scottish #bbcqt
acting salmond leader snp? sturgeon  acting salmond leader snp? sturgeon
miliband : wasn't &amp; nurses britain crashed economy. 'bout sa…  miliband &amp; nurses britain crashed 'bout
appalling miliband, pocket, #questiontime audience. answers @uklabour…  appalling miliband, pocket, #questiontime answers @uklabour…
lib tory 'slash' benefit £8bn cuts http://t.co/kcki2c5e9t …  lib tory benefit £8bn cuts http://t.co/kcki2c5e9t
milliband sun's worm. won't paper tomorrow. …  milliband sun's worm. paper
ft backing tories. unrelated ft leader jonathan ford boris)  ft backing tories. unrelated ft leader jonathan ford boris)
@graceymurph snp tories won't in, tories loads ukip scared snp  @graceymurph snp tories tories loads ukip scared snp
@naebd y'know, tories bills. time.  @naebd tories bills.
@debatingfools @ruptroop wearing boris johnson claiming ukip apparently? …  @debatingfools @ruptroop wearing boris johnson claiming ukip
@garrynewman audience's irritating. heckled questions.  @garrynewman irritating. heckled
@vauseswans mum... , d.... i'm ukip  @vauseswans ukip
ukip's nhs. …  ukip's nhs.
miliband minority snp?  miliband minority snp?
i'm #snpbecause els tory #asknicola #bbcqt #votesnp  #snpbecause els tory #asknicola #bbcqt #votesnp
clegg. lib coalition tories ! listening, …  lib coalition tories
lab mantra 'get tories out' 'but don't cent…  lab mantra tories cent…
miliband's 'if don't labour scotland letting tories in'.  miliband's labour scotland letting tories
yougov poll (29 30 lab 35% con 34% ukip ldem grn  yougov poll (29 30 lab 35% con 34% ukip ldem grn
@james_askwith @themockneyrebel @scottieh419 #ukip ppcs silent asked, stands  @james_askwith @themockneyrebel @scottieh419 #ukip ppcs silent stands
pundits #bbcqt ludicrous. bbc's tories &amp; libdens  pundits #bbcqt bbc's tories &amp; libdens
figures tonight's yougov/sun poll : con 34%, lab 35%, 8%, ukip 12%, grn 5%  figures yougov/sun yougov/sun poll con 34%, lab 35%, ukip grn
@shauntberry @telegraph wasn't fair. non-dorm? clegg? stacked.  @shauntberry @telegraph fair. non-dorm? stacked.
@blowmonkey1 @thesnp deals, coalition clear. tories #scottishlabour way.  @blowmonkey1 @thesnp deals, coalition tories #scottishlabour
one-word verdicts @jameskirkup. cameron: miliband: stumbling clegg: sidelined audience: …  verdicts @jameskirkup. miliband: stumbling sidelined
labour facts, banking tories …  labour banking tories
miliband's  miliband's
ft backing tories. unrelated ft leader jonathan ford boris)  ft backing tories. unrelated ft leader jonathan ford boris)
alt coldplay:look seats! you, do, yeah, yellow. @chemcnicol #…  alt coldplay:look seats! @chemcnicol
we've 5yrs. don't edm &amp; snp one. let's #securetherecovery https:…  5yrs. edm &amp; snp #securetherecovery
@jimforscotland it's jim, lab tories snp gov, wi…  @jimforscotland jim, lab tories snp gov,
“@chrisdyork: here's far... miliband face-planting #bbcqt …  “@chrisdyork: miliband face-planting #bbcqt
#election2015 risks losing seat election  #election2015 risks losing seat election
milliband's pronouncements........ scots.... #votesnp  milliband's pronouncements........ scots.... #votesnp
disgusted @ed_miliband tories @thesnp prog…  disgusted @ed_miliband tories @thesnp prog…
labour tory snp.  labour tory snp.
ft backing tories. unrelated ft leader jonathan ford boris)  ft backing tories. unrelated ft leader jonathan ford boris)
tory mp john a. birthday,  tory mp john
miliband handing ge tories  miliband handing ge tories
cameron's detail...
miliband stumbles, dodges  miliband stumbles, dodges
coalition deals snp. #bbcqt  coalition deals snp. #bbcqt
miliband trusting eu.  miliband trusting eu.
#milistumble here's #rudemanslapdown  #milistumble #rudemanslapdown
leaders, miliband answering #bbcqt  miliband answering #bbcqt
sun edition "ed miliband trips stage" sun scottish edition "ed miliband's tripping"  sun edition miliband trips stage" sun scottish edition miliband's tripping"
havens #bbcqt pourquoi? father offshore assets jersey  havens #bbcqt pourquoi? father offshore assets jersey
david benefits he'll cut. growing frustrated…  david benefits growing frustrated…
@chunkymark @owenjones84 lab torys downing snp. can't snp folks yous out😂  @chunkymark @owenjones84 lab torys downing snp. snp folks yous
@thelastleg russell forces miliband "hapax mogolgnon" #milibrand  @thelastleg russell forces miliband "hapax mogolgnon" #milibrand
#suzanne evans gem. talking, intelligent fierce ukip warrior. get. honesty.  #suzanne evans gem. intelligent fierce ukip warrior.
misinformed.if ukip, free.  misinformed.if ukip,
.@ed_miliband's distancing @thesnp tories &amp; labour sc…  .@ed_miliband's distancing @thesnp tories &amp; labour sc…
labour overspending &amp; tories major overspent too? #bbcqt  labour overspending &amp; tories major overspent #bbcqt
train. aisle tory proclaiming "because it…  aisle tory proclaiming
miliband "we're snp, coalition snp" #bbcqt …  miliband snp, coalition snp" #bbcqt
"cosying russell miliband isn't minister."  "cosying russell miliband minister."
tory lanez 📶  tory lanez

In [16]:
df.head()

,text,user.favourites_count,user.id,lang,user.followers_count,user.verified,truncated,links
0,indirect eu costing britain £170 #betteroffou...,31150.0,107794703,en,804,False,False,NaN
1,sturgeon post-election deals,0.0,557422508,en,184,False,False,http://t.co/BTJwrpbmOY
2,growing david minister #bbcqt,7565.0,3006692193,en,182,False,False,http://t.co
3,ukip lothian 16 msn addy,2130.0,455154030,en,1073,False,False,http://t.co/7eIU0c5Fm1
4,ukip's spokesman rakes £800k benefit migrants...,131.0,187547338,en,87,False,False,http://t.co/c1AZxcLh

In [17]:
df.to_csv('tweets_dataframe.csv', sep='\t',index_label=False)#index_label=False to avoid Unnamed columns.

In [18]:
data = pd.read_csv('tweets_dataframe.csv', sep='\t')

In [24]:
data.head()

,text,user.favourites_count,user.id,lang,user.followers_count,user.verified,truncated,links
0,indirect eu costing britain £170 #betteroffou...,31150.0,107794703,en,804,False,False,NaN
1,sturgeon post-election deals,0.0,557422508,en,184,False,False,http://t.co/BTJwrpbmOY
2,growing david minister #bbcqt,7565.0,3006692193,en,182,False,False,http://t.co
3,ukip lothian 16 msn addy,2130.0,455154030,en,1073,False,False,http://t.co/7eIU0c5Fm1
4,ukip's spokesman rakes £800k benefit migrants...,131.0,187547338,en,87,False,False,http://t.co/c1AZxcLh

In [25]:
data['text'] = data['text'].replace(to_replace=r'\b'+data['links']+r'\b', value='',regex=True)

In [28]:
data.head()

,text,user.favourites_count,user.id,lang,user.followers_count,user.verified,truncated,links
0,indirect eu costing britain £170 #betteroffou...,31150.0,107794703,en,804,False,False,NaN
1,sturgeon post-election deals,0.0,557422508,en,184,False,False,http://t.co/BTJwrpbmOY
2,growing david minister #bbcqt,7565.0,3006692193,en,182,False,False,http://t.co
3,ukip lothian 16 msn addy,2130.0,455154030,en,1073,False,False,http://t.co/7eIU0c5Fm1
4,ukip's spokesman rakes £800k benefit migrants...,131.0,187547338,en,87,False,False,http://t.co/c1AZxcLh

In [29]:
data.to_csv('tweets_dataframe.csv', sep='\t',index_label=False) #Remove links present in tweet texts.