<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

# Working with a real world data-set using SQL and Python

Estimated time needed: **30** minutes

## Objectives

After completing this lab you will be able to:

*   Understand the dataset for Chicago Public School level performance
*   Store the dataset in SQLite database.
*   Retrieve metadata about tables and columns and query data from mixed case columns
*   Solve example problems to practice your SQL skills including using built-in database functions

## Chicago Public Schools - Progress Report Cards (2011-2012)

The city of Chicago released a dataset showing all school level performance data used to create School Report Cards for the 2011-2012 school year. The dataset is available from the Chicago Data Portal: [https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t](https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

This dataset includes a large number of metrics. Start by familiarizing yourself with the types of metrics in the database: [https://data.cityofchicago.org/api/assets/AAD41A13-BE8A-4E67-B1F5-86E711E09D5F?download=true](https://data.cityofchicago.org/api/assets/AAD41A13-BE8A-4E67-B1F5-86E711E09D5F?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&download=true&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

**NOTE**:

Do not download the dataset directly from City of Chicago portal. Instead download a static copy which is a more database friendly version from this <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">link</a>.

Now review some of its contents.

### Connect to the database

Let us now load the ipython-sql  extension and establish a connection with the database

##### The syntax for connecting to magic sql using sqllite is

  **%sql sqlite://DatabaseName**   
  
where DatabaseName will be your **.db** file

In [1]:
import csv, sqlite3

con = sqlite3.connect("RealWorldData.db")
cur = con.cursor()

In [2]:
!pip install pandas
!pip install ipython-sql prettytable

import prettytable
prettytable.DEFAULT = 'DEFAULT'

Collecting pandas
  Downloading pandas-2.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 122.4 MB/s eta 0:00:00
Downloading numpy-2.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 183.5 MB/s eta 0:00:00
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.3.3 pandas-2.3.2 tzdata-2025.2
Collecting ipython-sql
  Downloading ipython_sql-0.5.0-py3-none-any.whl.metadata (17 kB)
Collecting prettytable
  Downloading prettytable-3.16.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: ipython in /opt/conda/lib/python3.12/site-packages (from ipython-sql) (8.31.0)
Requirement already satisfied: sqlalchemy>=2.0 in /opt/conda/lib/python3.12/site-packages (from ipython-sql) (2.0.37)
Collecting sqlparse (from ipython-sql)
  Downloading sqlparse-0.5.3-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: six in /opt/conda/lib/python3.12/site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.12/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.12/site-packages (from prettytable) (0.2.13)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.12/site-packages (from sqlalchemy>=2.0->ipython-sql) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/conda/lib/python3.12/site-packages (from sqlalchemy>=2.0->ipython-sql) (4.12.2)
Requirement already satisfied: decorator in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (3.0.50)
Requirement already satisfied: pygments>=2.4.0 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (2.19.1)
Requirement already satisfied: stack_data in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/conda/lib/python3.12/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.12/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /opt/conda/lib/python3.12/site-packages (from stack_data->ipython->ipython-sql) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in /opt/conda/lib/python3.12/site-packages (from stack_data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure_eval in /opt/conda/lib/python3.12/site-packages (from stack_data->ipython->ipython-sql) (0.2.3)
Downloading ipython_sql-0.5.0-py3-none-any.whl (20 kB)
Downloading prettytable-3.16.0-py3-none-any.whl (33 kB)
Downloading sqlparse-0.5.3-py3-none-any.whl (44 kB)
Installing collected packages: sqlparse, prettytable, ipython-sql
Successfully installed ipython-sql-0.5.0 prettytable-3.16.0 sqlparse-0.5.3

In [3]:
!pip install ipython-sql
%load_ext sql

Requirement already satisfied: ipython-sql in /opt/conda/lib/python3.12/site-packages (0.5.0)
Requirement already satisfied: prettytable in /opt/conda/lib/python3.12/site-packages (from ipython-sql) (3.16.0)
Requirement already satisfied: ipython in /opt/conda/lib/python3.12/site-packages (from ipython-sql) (8.31.0)
Requirement already satisfied: sqlalchemy>=2.0 in /opt/conda/lib/python3.12/site-packages (from ipython-sql) (2.0.37)
Requirement already satisfied: sqlparse in /opt/conda/lib/python3.12/site-packages (from ipython-sql) (0.5.3)
Requirement already satisfied: six in /opt/conda/lib/python3.12/site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.12/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.12/site-packages (from sqlalchemy>=2.0->ipython-sql) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/conda/lib/python3.12/site-packages (from sqlalchemy>=2.0->ipython-sql) (4.12.2)
Requirement already satisfied: decorator in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (3.0.50)
Requirement already satisfied: pygments>=2.4.0 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (2.19.1)
Requirement already satisfied: stack_data in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /opt/conda/lib/python3.12/site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.12/site-packages (from prettytable->ipython-sql) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/conda/lib/python3.12/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.12/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /opt/conda/lib/python3.12/site-packages (from stack_data->ipython->ipython-sql) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in /opt/conda/lib/python3.12/site-packages (from stack_data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure_eval in /opt/conda/lib/python3.12/site-packages (from stack_data->ipython->ipython-sql) (0.2.3)

In [4]:
%sql sqlite:///RealWorldData.db

### Store the dataset in a Table

##### In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet.  
##### To analyze the data using SQL, it first needs to be stored in the database.

##### We will first read the csv files  from the given url  into pandas dataframes

##### Next we will be using the  df.to_sql() function to convert each csv file  to a table in sqlite  with the csv data loaded in it.

In [7]:
import pandas
df=pandas.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv')
df.to_sql('Chicago_Public_Schools_Data',con)

566

Double-click **here** for the solution.
<!--

import pandas

df = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv")
df.to_sql("CHICAGO_PUBLIC_SCHOOLS_DATA", con, if_exists='replace', index=False, method="multi")

-->

### Query the database system catalog to retrieve table metadata

##### You can verify that the table creation was successful by retrieving the list of all tables in your schema and checking whether the SCHOOLS table was created

In [8]:
# type in your query to retrieve list of all tables in the database
%sql Select name from sqlite_master where type='table'

 * sqlite:///RealWorldData.db
Done.

[('Chicago_Public_Schools_Data',)]

Double-click **here** for a hint

<!--
In sqlite the system catalog table called sqlite_master contains the table metadata
-->

Double-click **here** for the solution.

<!-- Solution using SQLite:

%sql SELECT name FROM sqlite_master WHERE type='table'

-->

### Query the database system catalog to retrieve column metadata

##### The SCHOOLS table contains a large number of columns. How many columns does this table have?

In [13]:
# type in your query to retrieve the number of columns in the SCHOOLS table
%sql Select count(name) from PRAGMA_TABLE_INFO('Chicago_Public_Schools_Data');

 * sqlite:///RealWorldData.db
Done.

[(79,)]

Double-click **here** for the solution.

<!-- Solution SQLite:
%sql SELECT count(name) FROM PRAGMA_TABLE_INFO('CHICAGO_PUBLIC_SCHOOLS_DATA');

-->

Now retrieve the the list of columns in SCHOOLS table and their column type (datatype) and length.

In [15]:
# type in your query to retrieve all column names in the SCHOOLS table along with their datatypes and length
%sql SELECT name,type,length(type) FROM PRAGMA_TABLE_INFO('CHICAGO_PUBLIC_SCHOOLS_DATA');

 * sqlite:///RealWorldData.db
Done.

[('index', 'INTEGER', 7),
 ('School_ID', 'INTEGER', 7),
 ('NAME_OF_SCHOOL', 'TEXT', 4),
 ('Elementary, Middle, or High School', 'TEXT', 4),
 ('Street_Address', 'TEXT', 4),
 ('City', 'TEXT', 4),
 ('State', 'TEXT', 4),
 ('ZIP_Code', 'INTEGER', 7),
 ('Phone_Number', 'TEXT', 4),
 ('Link', 'TEXT', 4),
 ('Network_Manager', 'TEXT', 4),
 ('Collaborative_Name', 'TEXT', 4),
 ('Adequate_Yearly_Progress_Made_', 'TEXT', 4),
 ('Track_Schedule', 'TEXT', 4),
 ('CPS_Performance_Policy_Status', 'TEXT', 4),
 ('CPS_Performance_Policy_Level', 'TEXT', 4),
 ('HEALTHY_SCHOOL_CERTIFIED', 'TEXT', 4),
 ('Safety_Icon', 'TEXT', 4),
 ('SAFETY_SCORE', 'REAL', 4),
 ('Family_Involvement_Icon', 'TEXT', 4),
 ('Family_Involvement_Score', 'TEXT', 4),
 ('Environment_Icon', 'TEXT', 4),
 ('Environment_Score', 'REAL', 4),
 ('Instruction_Icon', 'TEXT', 4),
 ('Instruction_Score', 'REAL', 4),
 ('Leaders_Icon', 'TEXT', 4),
 ('Leaders_Score', 'TEXT', 4),
 ('Teachers_Icon', 'TEXT', 4),
 ('Teachers_Score', 'TEXT', 4),
 ('Parent_Engagement_Icon', 'TEXT', 4),
 ('Parent_Engagement_Score', 'TEXT', 4),
 ('Parent_Environment_Icon', 'TEXT', 4),
 ('Parent_Environment_Score', 'TEXT', 4),
 ('AVERAGE_STUDENT_ATTENDANCE', 'TEXT', 4),
 ('Rate_of_Misconducts__per_100_students_', 'REAL', 4),
 ('Average_Teacher_Attendance', 'TEXT', 4),
 ('Individualized_Education_Program_Compliance_Rate', 'TEXT', 4),
 ('Pk_2_Literacy__', 'TEXT', 4),
 ('Pk_2_Math__', 'TEXT', 4),
 ('Gr3_5_Grade_Level_Math__', 'TEXT', 4),
 ('Gr3_5_Grade_Level_Read__', 'TEXT', 4),
 ('Gr3_5_Keep_Pace_Read__', 'TEXT', 4),
 ('Gr3_5_Keep_Pace_Math__', 'TEXT', 4),
 ('Gr6_8_Grade_Level_Math__', 'TEXT', 4),
 ('Gr6_8_Grade_Level_Read__', 'TEXT', 4),
 ('Gr6_8_Keep_Pace_Math_', 'TEXT', 4),
 ('Gr6_8_Keep_Pace_Read__', 'TEXT', 4),
 ('Gr_8_Explore_Math__', 'TEXT', 4),
 ('Gr_8_Explore_Read__', 'TEXT', 4),
 ('ISAT_Exceeding_Math__', 'REAL', 4),
 ('ISAT_Exceeding_Reading__', 'REAL', 4),
 ('ISAT_Value_Add_Math', 'REAL', 4),
 ('ISAT_Value_Add_Read', 'REAL', 4),
 ('ISAT_Value_Add_Color_Math', 'TEXT', 4),
 ('ISAT_Value_Add_Color_Read', 'TEXT', 4),
 ('Students_Taking__Algebra__', 'TEXT', 4),
 ('Students_Passing__Algebra__', 'TEXT', 4),
 ('9th Grade EXPLORE (2009)', 'TEXT', 4),
 ('9th Grade EXPLORE (2010)', 'TEXT', 4),
 ('10th Grade PLAN (2009)', 'TEXT', 4),
 ('10th Grade PLAN (2010)', 'TEXT', 4),
 ('Net_Change_EXPLORE_and_PLAN', 'TEXT', 4),
 ('11th Grade Average ACT (2011)', 'TEXT', 4),
 ('Net_Change_PLAN_and_ACT', 'TEXT', 4),
 ('College_Eligibility__', 'TEXT', 4),
 ('Graduation_Rate__', 'TEXT', 4),
 ('College_Enrollment_Rate__', 'TEXT', 4),
 ('COLLEGE_ENROLLMENT', 'INTEGER', 7),
 ('General_Services_Route', 'INTEGER', 7),
 ('Freshman_on_Track_Rate__', 'TEXT', 4),
 ('X_COORDINATE', 'REAL', 4),
 ('Y_COORDINATE', 'REAL', 4),
 ('Latitude', 'REAL', 4),
 ('Longitude', 'REAL', 4),
 ('COMMUNITY_AREA_NUMBER', 'INTEGER', 7),
 ('COMMUNITY_AREA_NAME', 'TEXT', 4),
 ('Ward', 'INTEGER', 7),
 ('Police_District', 'INTEGER', 7),
 ('Location', 'TEXT', 4)]

Double-click **here** for the solution.

<!-- Solution 

%sql SELECT name,type,length(type) FROM PRAGMA_TABLE_INFO('CHICAGO_PUBLIC_SCHOOLS_DATA');

-->

### Questions

1.  Is the column name for the "SCHOOL ID" attribute in upper or mixed case?
2.  What is the name of "Community Area Name" column in your table? Does it have spaces?
3.  Are there any columns in whose names the spaces and paranthesis (round brackets) have been replaced by the underscore character "\_"?

## Problems

### Problem 1

##### How many Elementary Schools are in the dataset?

In [16]:
%sql Select count(*) from Chicago_Public_Schools_Data where `Elementary, Middle, or High School`='ES'

 * sqlite:///RealWorldData.db
Done.

[(462,)]

Double-click **here** for a hint

<!--
Which column specifies the school type e.g. 'ES', 'MS', 'HS'? ("Elementary School, Middle School, High School")
-->

Double-click **here** for another hint

<!--
Does the column name have mixed case, spaces or other special characters?
If so, ensure you use double quotes around the "Name of the Column"
-->

Double-click **here** for the solution.

<!-- Solution:

%sql select count(*) from CHICAGO_PUBLIC_SCHOOLS_DATA where "Elementary, Middle, or High School"='ES'

Correct answer: 462

-->

### Problem 2

##### What is the highest Safety Score?

In [18]:
%sql Select max(SAFETY_SCORE) from Chicago_Public_Schools_Data;

 * sqlite:///RealWorldData.db
Done.

[(99.0,)]

Double-click **here** for a hint

<!--
Use the MAX() function
-->

Double-click **here** for the solution.

<!-- Hint:

%sql select MAX(Safety_Score) AS MAX_SAFETY_SCORE from CHICAGO_PUBLIC_SCHOOLS_DATA

Correct answer: 99
-->

### Problem 3

##### Which schools have highest Safety Score?

In [21]:
%%sql
Select NAME_OF_SCHOOL,SAFETY_SCORE from Chicago_Public_Schools_Data
where SAFETY_SCORE=(Select max(SAFETY_SCORE) from Chicago_Public_Schools_Data);

 * sqlite:///RealWorldData.db
Done.

[('Abraham Lincoln Elementary School', 99.0),
 ('Alexander Graham Bell Elementary School', 99.0),
 ('Annie Keller Elementary Gifted Magnet School', 99.0),
 ('Augustus H Burley Elementary School', 99.0),
 ('Edgar Allan Poe Elementary Classical School', 99.0),
 ('Edgebrook Elementary School', 99.0),
 ('Ellen Mitchell Elementary School', 99.0),
 ('James E McDade Elementary Classical School', 99.0),
 ('James G Blaine Elementary School', 99.0),
 ('LaSalle Elementary Language Academy', 99.0),
 ('Mary E Courtenay Elementary Language Arts Center', 99.0),
 ('Northside College Preparatory High School', 99.0),
 ('Northside Learning Center High School', 99.0),
 ('Norwood Park Elementary School', 99.0),
 ('Oriole Park Elementary School', 99.0),
 ('Sauganash Elementary School', 99.0),
 ('Stephen Decatur Classical Elementary School', 99.0),
 ('Talman Elementary School', 99.0),
 ('Wildwood Elementary School', 99.0)]

Double-click **here** for the solution.

<!-- Solution:
In the previous problem we found out that the highest Safety Score is 99, so we can use that as an input in the where clause:

%sql select Name_of_School, Safety_Score from CHICAGO_PUBLIC_SCHOOLS_DATA where Safety_Score = 99

or, a better way:

%sql select Name_of_School, Safety_Score from CHICAGO_PUBLIC_SCHOOLS_DATA where \
  Safety_Score= (select MAX(Safety_Score) from CHICAGO_PUBLIC_SCHOOLS_DATA)


Correct answer: several schools with with Safety Score of 99.
-->

### Problem 4

##### What are the top 10 schools with the highest "Average Student Attendance"?

In [24]:
%%sql 
Select Name_of_School, Average_Student_Attendance from CHICAGO_PUBLIC_SCHOOLS_DATA
    order by Average_Student_Attendance desc limit 10

 * sqlite:///RealWorldData.db
Done.

[('John Charles Haines Elementary School', '98.40%'),
 ('James Ward Elementary School', '97.80%'),
 ('Edgar Allan Poe Elementary Classical School', '97.60%'),
 ('Orozco Fine Arts & Sciences Elementary School', '97.60%'),
 ('Rachel Carson Elementary School', '97.60%'),
 ('Annie Keller Elementary Gifted Magnet School', '97.50%'),
 ('Andrew Jackson Elementary Language Academy', '97.40%'),
 ('Lenart Elementary Regional Gifted Center', '97.40%'),
 ('Disney II Magnet School', '97.30%'),
 ('John H Vanderpoel Elementary Magnet School', '97.20%')]

Double-click **here** for the solution.

<!-- Solution:

%sql select Name_of_School, Average_Student_Attendance from CHICAGO_PUBLIC_SCHOOLS_DATA \
    order by Average_Student_Attendance desc nulls last limit 10 

-->

### Problem 5

##### Retrieve the list of 5 Schools with the lowest Average Student Attendance sorted in ascending order based on attendance

In [26]:
%%sql 
Select Name_of_School, Average_Student_Attendance from CHICAGO_PUBLIC_SCHOOLS_DATA
    order by Average_Student_Attendance limit 5

 * sqlite:///RealWorldData.db
Done.

[('Velma F Thomas Early Childhood Center', None),
 ('Richard T Crane Technical Preparatory High School', '57.90%'),
 ('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Dyett High School', '62.50%'),
 ('Wendell Phillips Academy High School', '63.00%')]

Double-click **here** for the solution.

<!-- Solution:

%sql SELECT Name_of_School, Average_Student_Attendance  \
     from CHICAGO_PUBLIC_SCHOOLS_DATA \
     order by Average_Student_Attendance \
     LIMIT 5

-->

### Problem 6

##### Now remove the '%' sign from the above result set for Average Student Attendance column

In [27]:
%%sql 
SELECT Name_of_School, REPLACE(Average_Student_Attendance, '%', '')
     from CHICAGO_PUBLIC_SCHOOLS_DATA
     order by Average_Student_Attendance
     LIMIT 5

 * sqlite:///RealWorldData.db
Done.

[('Velma F Thomas Early Childhood Center', None),
 ('Richard T Crane Technical Preparatory High School', '57.90'),
 ('Barbara Vick Early Childhood & Family Center', '60.90'),
 ('Dyett High School', '62.50'),
 ('Wendell Phillips Academy High School', '63.00')]

Double-click **here** for a hint

<!--
Use the REPLACE() function to replace '%' with ''

-->

Double-click **here** for the solution.

<!-- Hint:

%sql SELECT Name_of_School, REPLACE(Average_Student_Attendance, '%', '') \
     from CHICAGO_PUBLIC_SCHOOLS_DATA \
     order by Average_Student_Attendance \
     LIMIT 5

-->

### Problem 7

##### Which Schools have Average Student Attendance lower than 70%?

In [32]:
%%sql 
SELECT Name_of_School, Average_Student_Attendance
     from CHICAGO_PUBLIC_SCHOOLS_DATA
     where CAST ( REPLACE(Average_Student_Attendance, '%', '') AS DOUBLE ) < 70
     order by Average_Student_Attendance

 * sqlite:///RealWorldData.db
Done.

[('Richard T Crane Technical Preparatory High School', '57.90%'),
 ('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Dyett High School', '62.50%'),
 ('Wendell Phillips Academy High School', '63.00%'),
 ('Orr Academy High School', '66.30%'),
 ('Manley Career Academy High School', '66.80%'),
 ('Chicago Vocational Career Academy High School', '68.80%'),
 ('Roberto Clemente Community Academy High School', '69.60%')]

Double-click **here** for a hint

<!--
The datatype of the "Average_Student_Attendance" column is varchar.
So you cannot use it as is in the where clause for a numeric comparison.
First use the CAST() function to cast it as a DECIMAL or DOUBLE
e.g. CAST("Column_Name" as DOUBLE)

-->

Double-click **here** for another hint

<!--
Don't forget the '%' age sign needs to be removed before casting
-->

Double-click **here** for the solution.

<!-- Solution:

%sql SELECT Name_of_School, Average_Student_Attendance  \
     from CHICAGO_PUBLIC_SCHOOLS_DATA \
     where CAST ( REPLACE(Average_Student_Attendance, '%', '') AS DOUBLE ) < 70 \
     order by Average_Student_Attendance
     

-->

### Problem 8

##### Get the total College Enrollment for each Community Area

In [34]:
%%sql 
Select Community_Area_Name, sum(College_Enrollment) AS TOTAL_ENROLLMENT
   from CHICAGO_PUBLIC_SCHOOLS_DATA
   group by Community_Area_Name

 * sqlite:///RealWorldData.db
Done.

[('ALBANY PARK', 6864),
 ('ARCHER HEIGHTS', 4823),
 ('ARMOUR SQUARE', 1458),
 ('ASHBURN', 6483),
 ('AUBURN GRESHAM', 4175),
 ('AUSTIN', 10933),
 ('AVALON PARK', 1522),
 ('AVONDALE', 3640),
 ('BELMONT CRAGIN', 14386),
 ('BEVERLY', 1636),
 ('BRIDGEPORT', 3167),
 ('BRIGHTON PARK', 9647),
 ('BURNSIDE', 549),
 ('CALUMET HEIGHTS', 1568),
 ('CHATHAM', 5042),
 ('CHICAGO LAWN', 7086),
 ('CLEARING', 2085),
 ('DOUGLAS', 4670),
 ('DUNNING', 4568),
 ('EAST GARFIELD PARK', 5337),
 ('EAST SIDE', 5305),
 ('EDGEWATER', 4600),
 ('EDISON PARK', 910),
 ('ENGLEWOOD', 6832),
 ('FOREST GLEN', 1431),
 ('FULLER PARK', 531),
 ('GAGE PARK', 9915),
 ('GARFIELD RIDGE', 4552),
 ('GRAND BOULEVARD', 2809),
 ('GREATER GRAND CROSSING', 4051),
 ('HEGEWISCH', 963),
 ('HERMOSA', 3975),
 ('HUMBOLDT PARK', 8620),
 ('HYDE PARK', 1930),
 ('IRVING PARK', 7764),
 ('JEFFERSON PARK', 1755),
 ('KENWOOD', 4287),
 ('LAKE VIEW', 7055),
 ('LINCOLN PARK', 5615),
 ('LINCOLN SQUARE', 4132),
 ('LOGAN SQUARE', 7351),
 ('LOOP', 871),
 ('LOWER WEST SIDE', 7257),
 ('MCKINLEY PARK', 1552),
 ('MONTCLARE', 1317),
 ('MORGAN PARK', 3271),
 ('MOUNT GREENWOOD', 2091),
 ('NEAR NORTH SIDE', 3362),
 ('NEAR SOUTH SIDE', 1378),
 ('NEAR WEST SIDE', 7975),
 ('NEW CITY', 7922),
 ('NORTH CENTER', 7541),
 ('NORTH LAWNDALE', 5146),
 ('NORTH PARK', 4210),
 ('NORWOOD PARK', 6469),
 ('OAKLAND', 140),
 ('OHARE', 786),
 ('PORTAGE PARK', 6954),
 ('PULLMAN', 1620),
 ('RIVERDALE', 1547),
 ('ROGERS PARK', 4068),
 ('ROSELAND', 7020),
 ('SOUTH CHICAGO', 4043),
 ('SOUTH DEERING', 1859),
 ('SOUTH LAWNDALE', 14793),
 ('SOUTH SHORE', 4543),
 ('UPTOWN', 4388),
 ('WASHINGTON HEIGHTS', 4006),
 ('WASHINGTON PARK', 2648),
 ('WEST ELSDON', 3700),
 ('WEST ENGLEWOOD', 5946),
 ('WEST GARFIELD PARK', 2622),
 ('WEST LAWN', 4207),
 ('WEST PULLMAN', 3240),
 ('WEST RIDGE', 8197),
 ('WEST TOWN', 9429),
 ('WOODLAWN', 4206)]

Double-click **here** for a hint

<!--
Verify the exact name of the Enrollment column in the database
Use the SUM() function to add up the Enrollments for each Community Area
-->

Double-click **here** for another hint

<!--
Don't forget to group by the Community Area
-->

Double-click **here** for the solution.

<!-- Solution:

%sql select Community_Area_Name, sum(College_Enrollment) AS TOTAL_ENROLLMENT \
   from CHICAGO_PUBLIC_SCHOOLS_DATA \
   group by Community_Area_Name 

-->

### Problem 9

##### Get the 5 Community Areas with the least total College Enrollment  sorted in ascending order

In [35]:
%%sql
Select Community_Area_Name, sum(College_Enrollment) AS TOTAL_ENROLLMENT
   from CHICAGO_PUBLIC_SCHOOLS_DATA
   group by Community_Area_Name
   order by TOTAL_ENROLLMENT asc
   LIMIT 5

 * sqlite:///RealWorldData.db
Done.

[('OAKLAND', 140),
 ('FULLER PARK', 531),
 ('BURNSIDE', 549),
 ('OHARE', 786),
 ('LOOP', 871)]

Double-click **here** for a hint

<!--
Order the previous query and limit the number of rows you fetch
-->

Double-click **here** for the solution.

<!-- Solution:

%sql select Community_Area_Name, sum(College_Enrollment) AS TOTAL_ENROLLMENT \
   from CHICAGO_PUBLIC_SCHOOLS_DATA \
   group by Community_Area_Name \
   order by TOTAL_ENROLLMENT asc \
   LIMIT 5 

-->

### Problem 10

##### List 5 schools with lowest safety score.

In [37]:
%%sql
Select NAME_OF_SCHOOL,Safety_Score FROM Chicago_Public_Schools_Data
where Safety_Score!='None'
order by Safety_Score limit 5;

 * sqlite:///RealWorldData.db
Done.

[('Edmond Burke Elementary School', 1.0),
 ("Luke O'Toole Elementary School", 5.0),
 ('George W Tilton Elementary School', 6.0),
 ('Foster Park Elementary School', 11.0),
 ('Emil G Hirsch Metropolitan High School', 13.0)]

Double-click **here** for the solution.

<!-- Solution SQLite:

%sql SELECT name_of_school, safety_score \
FROM CHICAGO_PUBLIC_SCHOOLS_DATA  where safety_score !='None' \
ORDER BY safety_score \
LIMIT 5

-->

### Problem 11

##### Get the hardship index for the community area of the school which has College Enrollment of 4368

In [38]:
df1 = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv")
df1.to_sql("CENSUS_DATA", con, if_exists='replace', index=False,method="multi")

78

In [39]:
%%sql 
select hardship_index from CENSUS_DATA CD, CHICAGO_PUBLIC_SCHOOLS_DATA CPS 
where CD.community_area_number = CPS.community_area_number 
and college_enrollment = 4368

 * sqlite:///RealWorldData.db
Done.

[(6.0,)]

Double-click **here** for the solution.

<!-- Solution:
NOTE: For this solution to work the CHICAGO_SOCIOECONOMIC_DATA table 
      as created in the last lab of Week 3 should already exist. If the CHICAGO_SOCIOECONOMIC_DATA table does not exists, please execute the following code beforehand.

df = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv")
df.to_sql("CENSUS_DATA", con, if_exists='replace', index=False,method="multi")


%%sql 
select hardship_index from CENSUS_DATA CD, CHICAGO_PUBLIC_SCHOOLS_DATA CPS 
where CD.community_area_number = CPS.community_area_number 
and college_enrollment = 4368


-->

### Problem 12

##### Get the hardship index for the community area which has the highest value for College Enrollment

In [41]:
%%sql 
Select community_area_number, community_area_name, hardship_index from CENSUS_DATA
   where community_area_number in 
   ( select community_area_number from CHICAGO_PUBLIC_SCHOOLS_DATA order by college_enrollment desc limit 1 )

 * sqlite:///RealWorldData.db
Done.

[(5.0, 'North Center', 6.0)]

Double-click **here** for the solution.

<!-- Solution:
NOTE: For this solution to work the CHICAGO_SOCIOECONOMIC_DATA table 
      as created in the last lab of Week 3 should already exist. If the CHICAGO_SOCIOECONOMIC_DATA table does not exists, please execute the following code beforehand.

df = pandas.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv")
df.to_sql("CENSUS_DATA", con, if_exists='replace', index=False,method="multi")

%sql select community_area_number, community_area_name, hardship_index from CENSUS_DATA \
   where community_area_number in \
   ( select community_area_number from CHICAGO_PUBLIC_SCHOOLS_DATA order by college_enrollment desc limit 1 )
-->

## Summary

##### In this lab you learned how to work with a real word dataset using SQL and Python. You learned how to query columns with spaces or special characters in their names and with mixed case names. You also used built in database functions and practiced how to sort, limit, and order result sets, as well as used sub-queries and worked with multiple tables.

## Author

<a href="https://www.linkedin.com/in/ravahuja/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01" target="_blank">Rav Ahuja</a>
<!--
## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                        |
| ----------------- | ------- | ----------------- | ----------------------------------------- |
| 2022-03-04        | 2.2     | Lakshmi Holla     | Made changes in markdown cells |
| 2020-11-27        | 2.1     | Sannareddy Ramesh | Modified data sets and added new problems |
| 2020-08-28        | 2.0     | Lavanya           | Moved lab to course repo in GitLab        |
-->
<hr>

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>

In [2]:
import pandas as pd
df=pd.read_csv(r'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv')
df

,ID,CASE_NUMBER,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION,ARREST,DOMESTIC,...,DISTRICT,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,LATITUDE,LONGITUDE,LOCATION
0,3512276,HK587712,2004-08-28,047XX S KEDZIE AVE,890,THEFT,FROM BUILDING,SMALL RETAIL STORE,False,False,...,9,14.0,58.0,6,1155838.0,1873050.0,2004,41.807440,-87.703956,"(41.8074405, -87.703955849)"
1,3406613,HK456306,2004-06-26,009XX N CENTRAL PARK AVE,820,THEFT,$500 AND UNDER,OTHER,False,False,...,11,27.0,23.0,6,1152206.0,1906127.0,2004,41.898280,-87.716406,"(41.898279962, -87.716405505)"
2,8002131,HT233595,2011-04-04,043XX S WABASH AVE,820,THEFT,$500 AND UNDER,NURSING HOME/RETIREMENT HOME,False,False,...,2,3.0,38.0,6,1177436.0,1876313.0,2011,41.815933,-87.624642,"(41.815933131, -87.624642127)"
3,7903289,HT133522,2010-12-30,083XX S KINGSTON AVE,840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,4,7.0,46.0,6,1194622.0,1850125.0,2010,41.743665,-87.562463,"(41.743665322, -87.562462756)"
4,10402076,HZ138551,2016-02-02,033XX W 66TH ST,820,THEFT,$500 AND UNDER,ALLEY,False,False,...,8,15.0,66.0,6,1155240.0,1860661.0,2016,41.773455,-87.706480,"(41.773455295, -87.706480471)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,10453948,HZ192829,2016-03-01,028XX E 79TH ST,1055,HUMAN TRAFFICKING,INVOLUNTARY SERVITUDE,APARTMENT,False,False,...,4,7.0,46.0,26,1196679.0,1853139.0,2016,41.751885,-87.554826,"(41.751885152, -87.554825997)"
529,10397129,HZ133234,2016-01-29,006XX W HARRISON ST,5114,NON - CRIMINAL,FOID - REVOCATION,STREET,False,False,...,1,2.0,28.0,26,1172257.0,1897564.0,2016,41.874363,-87.643013,"(41.874363279, -87.643013039)"
530,3269495,HJ747227,2003-11-08,012XX W 81ST ST,510,RITUALISM,AGG RIT MUT: HANDS/FIST/FEET SERIOUS INJURY,OTHER,False,False,...,6,21.0,71.0,04B,1169648.0,1851076.0,2003,41.746852,-87.653941,"(41.746852486, -87.653941385)"
531,10840565,JA143710,2017-02-06,009XX N KARLOV AVE,5073,NON-CRIMINAL (SUBJECT SPECIFIED),NOTIFICATION OF CIVIL NO CONTACT ORDER,RESIDENCE,False,True,...,11,37.0,23.0,26,1148881.0,1905963.0,2017,41.897895,-87.728622,"(41.89789489, -87.728622316)"
532,1326195,G021609,2001-01-11,087XX S ESCANABA AV,9901,DOMESTIC VIOLENCE,DOMESTIC VIOLENCE,APARTMENT,True,True,...,4,NaN,NaN,08B,1196869.0,1847416.0,2001,41.736176,-87.554320,"(41.73617608, -87.554319607)"

In [1]:
!pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.2.0-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.2.0-cp313-cp313-win_amd64.whl (69 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.2.0

In [7]:
file_name='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/laptop_pricing_dataset_base.csv'

In [8]:
import pandas as pd
import numpy as np
df=pd.read_csv(file_name)
df.head(5)

   Acer  4  IPS Panel  2  1  5   35.56  1.6  8  256 1.6.1   978
0  Dell  3    Full HD  1  1  3  39.624  2.0  4  256   2.2   634
1  Dell  3    Full HD  1  1  7  39.624  2.7  8  256   2.2   946
2  Dell  4  IPS Panel  2  1  5  33.782  1.6  8  128  1.22  1244
3    HP  4    Full HD  2  1  7  39.624  1.8  8  256  1.91   837
4  Dell  3    Full HD  1  1  5  39.624  1.6  8  256   2.2  1016

In [10]:
df.replace('?',np.nan)

        Acer  4  IPS Panel  2  1  5   35.56  1.6  8  256 1.6.1   978
0       Dell  3    Full HD  1  1  3  39.624  2.0  4  256   2.2   634
1       Dell  3    Full HD  1  1  7  39.624  2.7  8  256   2.2   946
2       Dell  4  IPS Panel  2  1  5  33.782  1.6  8  128  1.22  1244
3         HP  4    Full HD  2  1  7  39.624  1.8  8  256  1.91   837
4       Dell  3    Full HD  1  1  5  39.624  1.6  8  256   2.2  1016
..       ... ..        ... .. .. ..     ...  ... ..  ...   ...   ...
232   Lenovo  4  IPS Panel  2  1  7   35.56  2.6  8  256   1.7  1891
233  Toshiba  3    Full HD  2  1  5  33.782  2.4  8  256   1.2  1950
234   Lenovo  4  IPS Panel  2  1  5   30.48  2.6  8  256  1.36  2236
235   Lenovo  3    Full HD  3  1  5  39.624  2.5  6  256   2.4   883
236  Toshiba  3    Full HD  2  1  5   35.56  2.3  8  256  1.95  1499

[237 rows x 12 columns]

In [11]:
# Write your code below and press Shift+Enter to execute.
headers=["Manufacturer", "Category", "Screen", "GPU", "OS", "CPU_core", "Screen_Size_inch", "CPU_frequency", "RAM_GB", "Storage_GB_SSD", "Weight_kg","Price"]
df.columns=headers

In [14]:
df

,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.2,634
1,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.2,946
2,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
3,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837
4,Dell,3,Full HD,1,1,5,39.624,1.6,8,256,2.2,1016
...,...,...,...,...,...,...,...,...,...,...,...,...
232,Lenovo,4,IPS Panel,2,1,7,35.56,2.6,8,256,1.7,1891
233,Toshiba,3,Full HD,2,1,5,33.782,2.4,8,256,1.2,1950
234,Lenovo,4,IPS Panel,2,1,5,30.48,2.6,8,256,1.36,2236
235,Lenovo,3,Full HD,3,1,5,39.624,2.5,6,256,2.4,883
236,Toshiba,3,Full HD,2,1,5,35.56,2.3,8,256,1.95,1499

In [15]:
df1=df.replace('?',np.nan)
df1

,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.2,634
1,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.2,946
2,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
3,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837
4,Dell,3,Full HD,1,1,5,39.624,1.6,8,256,2.2,1016
...,...,...,...,...,...,...,...,...,...,...,...,...
232,Lenovo,4,IPS Panel,2,1,7,35.56,2.6,8,256,1.7,1891
233,Toshiba,3,Full HD,2,1,5,33.782,2.4,8,256,1.2,1950
234,Lenovo,4,IPS Panel,2,1,5,30.48,2.6,8,256,1.36,2236
235,Lenovo,3,Full HD,3,1,5,39.624,2.5,6,256,2.4,883
236,Toshiba,3,Full HD,2,1,5,35.56,2.3,8,256,1.95,1499

In [31]:
import pyodbc
# The engine is needed for pandas to interact with the database

# Your successful connection details (replace with your actual server name)
connection_string = (      
    'DRIVER={ODBC Driver 17 for SQL Server};'      
    'SERVER=LENOVO\\SQLEXPRESS;'  
    'DATABASE=Laptop_Pricing;'      
    'Trusted_Connection=yes;'      
)

# Establish the pyodbc connection
pyodbc_connection = pyodbc.connect(connection_string)

In [32]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from sqlalchemy) (4.15.0)

In [33]:
import pyodbc
import pandas as pd
from sqlalchemy import create_engine
import urllib # Needed for properly formatting the URL string

# --- Connection Parameters ---
SERVER = 'LENOVO\\SQLEXPRESS' 
DATABASE = 'Laptop_Pricing'
DRIVER = 'ODBC Driver 17 for SQL Server' # Use 17 or 18, based on your install

# 1. Properly format the connection string components for a SQLAlchemy URL
# This encodes the driver name (e.g., replaces spaces with '+')
params = urllib.parse.quote_plus(
    f"DRIVER={DRIVER};"
    f"SERVER={SERVER};"
    f"DATABASE={DATABASE};"
    f"Trusted_Connection=yes;"
)

# 2. Create the SQLAlchemy Engine URL
# Syntax: mssql+pyodbc:///?odbc_connect=<encoded_pyodbc_string>
# This tells SQLAlchemy to use the MSSQL dialect via the pyodbc connector.
sqlalchemy_url = f"mssql+pyodbc:///?odbc_connect={params}"

# 3. Create the SQLAlchemy Engine
engine = create_engine(sqlalchemy_url)

# --- Load Data to SQL Server using the Engine ---
try:
    # Use the new SQLAlchemy engine object for the 'con' argument
    df1.to_sql(
        name="Laptops_Data", 
        con=engine,  # <--- Now passing the SQLAlchemy Engine!
        if_exists='replace',    
        index=False             
    )
    print("Data successfully loaded to SQL Server using SQLAlchemy Engine.")

except Exception as e:
    print(f"An error occurred during data loading: {e}")

finally:
    # 4. Close the engine connection pool
    if 'engine' in locals():
        engine.dispose()
        print("SQLAlchemy Engine disposed.")

Data successfully loaded to SQL Server using SQLAlchemy Engine.
SQLAlchemy Engine disposed.

In [34]:
cursor_object=pyodbc_connection.cursor()

In [40]:
# Install the 'ipython-sql' and 'prettytable' libraries using pip
!pip install ipython-sql prettytable

# Import the 'prettytable' library, which is used to display data in a formatted table
import prettytable

# Set the default display format for prettytable to 'DEFAULT' (i.e., a simple table format)
prettytable.DEFAULT = 'DEFAULT'

Requirement already satisfied: ipython-sql in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (0.5.0)
Requirement already satisfied: prettytable in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (3.16.0)
Requirement already satisfied: ipython in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython-sql) (9.1.0)
Requirement already satisfied: sqlalchemy>=2.0 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython-sql) (2.0.43)
Requirement already satisfied: sqlparse in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython-sql) (0.5.3)
Requirement already satisfied: six in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from prettytable) (0.2.13)
Requirement already satisfied: greenlet>=1 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: colorama in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: decorator in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (2.19.1)
Requirement already satisfied: stack_data in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: executing>=1.2.0 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from stack_data->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from stack_data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure_eval in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from stack_data->ipython->ipython-sql) (0.2.3)

In [44]:
querry=cursor_object.execute('SELECT TOP 5 * FROM Laptops_Data;')
result=cursor_object.fetchall()

In [45]:
for row in result:
    print(row)

('Dell', 3, 'Full HD', 1, 1, 3, '39.624', 2.0, 4, 256, '2.2', 634)
('Dell', 3, 'Full HD', 1, 1, 7, '39.624', 2.7, 8, 256, '2.2', 946)
('Dell', 4, 'IPS Panel', 2, 1, 5, '33.782', 1.6, 8, 128, '1.22', 1244)
('HP', 4, 'Full HD', 2, 1, 7, '39.624', 1.8, 8, 256, '1.91', 837)
('Dell', 3, 'Full HD', 1, 1, 5, '39.624', 1.6, 8, 256, '2.2', 1016)

In [46]:
!pip install ipython-sql sqlalchemy pyodbc

Requirement already satisfied: ipython-sql in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (0.5.0)
Requirement already satisfied: sqlalchemy in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (2.0.43)
Requirement already satisfied: pyodbc in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (5.2.0)
Requirement already satisfied: prettytable in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython-sql) (3.16.0)
Requirement already satisfied: ipython in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython-sql) (9.1.0)
Requirement already satisfied: sqlparse in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython-sql) (0.5.3)
Requirement already satisfied: six in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet>=1 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: colorama in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: decorator in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (2.19.1)
Requirement already satisfied: stack_data in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: wcwidth in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: executing>=1.2.0 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from stack_data->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from stack_data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure_eval in c:\users\muhammadrehanriaz\anaconda3\envs\rp_env\lib\site-packages (from stack_data->ipython->ipython-sql) (0.2.3)

In [47]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [48]:
# Replace YOUR_ACTUAL_SERVER_NAME_HERE with your Server\Instance name (e.g., 'LAPTOP-ABCD\SQLEXPRESS')

# 1. URL-encode your driver name (replaces spaces with '+')
DRIVER = 'ODBC+Driver+17+for+SQL+Server' 

# 2. Build the full URL
connection_url = (
    f"mssql+pyodbc://LENOVO\\SQLEXPRESS/Laptop_Pricing?"
    f"driver={DRIVER}&trusted_connection=yes"
)

In [50]:
# Use the magic command to connect
%sql {connection_url}

In [53]:
%%sql
Select Top 5 * from Laptops_Data;

 * mssql+pyodbc://LENOVO\SQLEXPRESS/Laptop_Pricing?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes
Done.

[('Dell', 3, 'Full HD', 1, 1, 3, '39.624', 2.0, 4, 256, '2.2', 634),
 ('Dell', 3, 'Full HD', 1, 1, 7, '39.624', 2.7, 8, 256, '2.2', 946),
 ('Dell', 4, 'IPS Panel', 2, 1, 5, '33.782', 1.6, 8, 128, '1.22', 1244),
 ('HP', 4, 'Full HD', 2, 1, 7, '39.624', 1.8, 8, 256, '1.91', 837),
 ('Dell', 3, 'Full HD', 1, 1, 5, '39.624', 1.6, 8, 256, '2.2', 1016)]