# Week3

In [5]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\prash\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\prash\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prash\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\prash\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\prash\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\prash\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [11]:
import warnings
warnings.filterwarnings('ignore')  # ignore all warnings

Loading the Dataset

a) Manual Loading

In [12]:
# Manual function to read CSV
def load_manual(filename):
    with open(filename, 'r') as file:
        data = file.readlines()
    # Split lines and handle header
    header = data[0].strip().split(',')
    rows = [line.strip().split(',') for line in data[1:]]
    return header, rows

header, rows = load_manual('data.csv')
print("Header:", header)
print("Rows:", rows)

Header: ['Name', 'Age', 'Salary']
Rows: [['John', '28', '50000'], ['Alice', '30', '60000'], ['Bob', '', '55000'], ['Eve', '25', '']]

b) Using numpy.loadtxt

In [13]:
import numpy as np

# Assuming numeric data only (Age, Salary)
data = np.loadtxt('data1.csv', delimiter=',', skiprows=1, usecols=(1,2))
print(data)

[[2.8e+01 5.0e+04]
 [3.0e+01 6.0e+04]
 [5.6e+01 5.5e+04]
 [2.5e+01 6.0e+04]]

c) Using numpy.genfromtxt

In [14]:
import numpy as np

data = np.genfromtxt('data.csv', delimiter=',', skip_header=1, usecols=(1,2), filling_values=np.nan)
print(data)

[[2.8e+01 5.0e+04]
 [3.0e+01 6.0e+04]
 [    nan 5.5e+04]
 [2.5e+01     nan]]

d) Using pandas.read_csv

In [15]:
import pandas as pd

df = pd.read_csv('data.csv')
print(df)

    Name   Age   Salary
0   John  28.0  50000.0
1  Alice  30.0  60000.0
2    Bob   NaN  55000.0
3    Eve  25.0      NaN

Dealing with Missing Data

a) Identify missing data

In [16]:
print(df.isnull())          # True for missing values
print(df.isnull().sum())    # Count missing per column

    Name    Age  Salary
0  False  False   False
1  False  False   False
2  False   True   False
3  False  False    True
Name      0
Age       1
Salary    1
dtype: int64

b) Remove missing data

In [18]:
# Drop rows with any missing values
df_drop = df.dropna()
print(df_drop)

    Name   Age   Salary
0   John  28.0  50000.0
1  Alice  30.0  60000.0

c) Fill missing data

In [19]:
# Fill numeric columns with mean
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Salary'].fillna(df['Salary'].mean(), inplace=True)
print(df)

    Name        Age   Salary
0   John  28.000000  50000.0
1  Alice  30.000000  60000.0
2    Bob  27.666667  55000.0
3    Eve  25.000000  55000.0

d) Fill with a constant value

In [20]:
df['Salary'].fillna(50000, inplace=True)

In [21]:
df

    Name        Age   Salary
0   John  28.000000  50000.0
1  Alice  30.000000  60000.0
2    Bob  27.666667  55000.0
3    Eve  25.000000  55000.0

e) Forward/Backward Fill

In [22]:
df.fillna(method='ffill', inplace=True)  # forward fill
df.fillna(method='bfill', inplace=True)  # backward fill

In [23]:
df

    Name        Age   Salary
0   John  28.000000  50000.0
1  Alice  30.000000  60000.0
2    Bob  27.666667  55000.0
3    Eve  25.000000  55000.0