<a href="https://colab.research.google.com/github/Roshni-seth/Machine-Learning/blob/main/Working_with_dates_and_time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q kaggle
from google.colab import files
files.upload()

Saving kaggle (3).json to kaggle (3).json

{'kaggle (3).json': b'{"username":"rosh05032001","key":"0684e1839ccedea0779e4cec79194e29"}'}

In [2]:
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/

In [4]:
! kaggle datasets download onidzelskyi/chat-messages

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /root/.kaggle/kaggle.json'
Dataset URL: https://www.kaggle.com/datasets/onidzelskyi/chat-messages
License(s): CC0-1.0
Downloading chat-messages.zip to /content
 47% 12.0M/25.6M [00:00<00:00, 41.6MB/s]
100% 25.6M/25.6M [00:00<00:00, 71.1MB/s]

In [25]:
import pandas as pd
import numpy as np

In [10]:
time=pd.read_csv('/content/chat-messages.zip')
time.head()

                  date                                                msg
0  2012-01-02 00:21:00                            нужен парень 0965188229
1  2012-01-02 00:24:00                       Всем привет! Как настроение?
2  2012-01-02 00:27:00  ИЩЮ ВТОРУЮ ПОЛОВИНКУ МНЕ 23 ЗОВУТ ВАНЯ ПИШИТЕ ...
3  2012-01-02 00:27:00     Эля  встречала в шумной компании! Все отлично!
4  2012-01-02 00:27:00  Парень катается по городу. Нужна девушка. 0992...

In [7]:
! kaggle datasets download jyesawtellrickson/ecommerce-bookings-data

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /root/.kaggle/kaggle.json'
Dataset URL: https://www.kaggle.com/datasets/jyesawtellrickson/ecommerce-bookings-data
License(s): unknown
Downloading ecommerce-bookings-data.zip to /content
  0% 0.00/1.78M [00:00<?, ?B/s]
100% 1.78M/1.78M [00:00<00:00, 132MB/s]

In [9]:
date=pd.read_csv('/content/ecommerce-bookings-data.zip')
date.head()

         date  product_id  city_id  orders
0  2019-12-16        1897       26       2
1  2019-12-16        4850       26       4
2  2019-12-16        2466       26       1
3  2019-12-16         637       26       1
4  2019-12-16        3497       26     184

In [11]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 523684 entries, 0 to 523683
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        523684 non-null  object
 1   product_id  523684 non-null  int64
 2   city_id     523684 non-null  int64
 3   orders      523684 non-null  int64
dtypes: int64(3), object(1)
memory usage: 16.0+ MB

In [12]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1147100 entries, 0 to 1147099
Data columns (total 2 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   date    1147100 non-null  object
 1   msg     1147100 non-null  object
dtypes: object(2)
memory usage: 17.5+ MB

**Working with Dates**

In [13]:
# converting to datetime datatype
date['date']=pd.to_datetime(date['date'])

In [14]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 523684 entries, 0 to 523683
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        523684 non-null  datetime64[ns]
 1   product_id  523684 non-null  int64
 2   city_id     523684 non-null  int64
 3   orders      523684 non-null  int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 16.0 MB

**1. Extract year**

In [17]:
date['date_year']=date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-16        1897       26       2       2019
1 2019-12-16        4850       26       4       2019
2 2019-12-16        2466       26       1       2019
3 2019-12-16         637       26       1       2019
4 2019-12-16        3497       26     184       2019

**2. Extract Month**

In [18]:
date['date_month_no']=date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-16        1897       26       2       2019             12
1 2019-12-16        4850       26       4       2019             12
2 2019-12-16        2466       26       1       2019             12
3 2019-12-16         637       26       1       2019             12
4 2019-12-16        3497       26     184       2019             12

In [19]:
date['date_month_name']=date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-16,1897,26,2,2019,12,December
1,2019-12-16,4850,26,4,2019,12,December
2,2019-12-16,2466,26,1,2019,12,December
3,2019-12-16,637,26,1,2019,12,December
4,2019-12-16,3497,26,184,2019,12,December

**Extract Days**

In [20]:
date['date_day']=date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-16,1897,26,2,2019,12,December,16
1,2019-12-16,4850,26,4,2019,12,December,16
2,2019-12-16,2466,26,1,2019,12,December,16
3,2019-12-16,637,26,1,2019,12,December,16
4,2019-12-16,3497,26,184,2019,12,December,16

In [22]:
# day of week
date['date_dow']=date['date'].dt.dayofweek
date.sample()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
65245,2019-05-17,4846,1,7,2019,5,May,17,4

In [23]:
# day of week name
date['date_dow_name']=date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-16,2019,12,December,16,0,Monday
1,2019-12-16,2019,12,December,16,0,Monday
2,2019-12-16,2019,12,December,16,0,Monday
3,2019-12-16,2019,12,December,16,0,Monday
4,2019-12-16,2019,12,December,16,0,Monday

In [26]:
# is weekend?

date['date_is_weekend']=np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-16,2019,12,December,16,0,Monday,0
1,2019-12-16,2019,12,December,16,0,Monday,0
2,2019-12-16,2019,12,December,16,0,Monday,0
3,2019-12-16,2019,12,December,16,0,Monday,0
4,2019-12-16,2019,12,December,16,0,Monday,0

**Extract week of the year**

In [28]:
date['date_week']=date['date'].dt.isocalendar().week
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-16,2019,12,December,16,0,Monday,0,51
1,2019-12-16,2019,12,December,16,0,Monday,0,51
2,2019-12-16,2019,12,December,16,0,Monday,0,51
3,2019-12-16,2019,12,December,16,0,Monday,0,51
4,2019-12-16,2019,12,December,16,0,Monday,0,51

**Extract Quarter**

In [29]:
date['quarter']=date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-16,2019,12,December,16,0,Monday,0,51,4
1,2019-12-16,2019,12,December,16,0,Monday,0,51,4
2,2019-12-16,2019,12,December,16,0,Monday,0,51,4
3,2019-12-16,2019,12,December,16,0,Monday,0,51,4
4,2019-12-16,2019,12,December,16,0,Monday,0,51,4

**Extract Semester**

In [30]:
date['semester']=np.where(date['quarter'].isin([1,2]),1,2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-16,2019,12,December,16,0,Monday,0,51,4,2
1,2019-12-16,2019,12,December,16,0,Monday,0,51,4,2
2,2019-12-16,2019,12,December,16,0,Monday,0,51,4,2
3,2019-12-16,2019,12,December,16,0,Monday,0,51,4,2
4,2019-12-16,2019,12,December,16,0,Monday,0,51,4,2

**Extract Time elapsed between date**

In [31]:
import datetime
today=datetime.datetime.today()
today

datetime.datetime(2024, 11, 16, 17, 38, 53, 502400)

In [33]:
today-date['date']

0        1797 days 17:38:53.502400
1        1797 days 17:38:53.502400
2        1797 days 17:38:53.502400
3        1797 days 17:38:53.502400
4        1797 days 17:38:53.502400
                    ...
523679   2145 days 17:38:53.502400
523680   2143 days 17:38:53.502400
523681   2139 days 17:38:53.502400
523682   2138 days 17:38:53.502400
523683   2137 days 17:38:53.502400
Name: date, Length: 523684, dtype: timedelta64[ns]

In [34]:
(today-date['date']).dt.days

0         1797
1         1797
2         1797
3         1797
4         1797
          ...
523679    2145
523680    2143
523681    2139
523682    2138
523683    2137
Name: date, Length: 523684, dtype: int64

In [38]:
# Month Passes

# Month Passes

# Calculate the difference in days
day_diff = (today - date['date']).dt.days

# Divide by the average number of days in a month (30.4375)
month_diff = np.round(day_diff / 30.4375, 0)

month_diff

0         59.0
1         59.0
2         59.0
3         59.0
4         59.0
          ...
523679    70.0
523680    70.0
523681    70.0
523682    70.0
523683    70.0
Name: date, Length: 523684, dtype: float64

**time**

In [39]:
# converting to datetime datatype
time['date']=pd.to_datetime(time['date'])

In [40]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1147100 entries, 0 to 1147099
Data columns (total 2 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   date    1147100 non-null  datetime64[ns]
 1   msg     1147100 non-null  object
dtypes: datetime64[ns](1), object(1)
memory usage: 17.5+ MB

In [41]:
time['hour']=time['date'].dt.hour
time['min']=time['date'].dt.minute
time['sec']=time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2012-01-02 00:21:00,нужен парень 0965188229,0,21,0
1,2012-01-02 00:24:00,Всем привет! Как настроение?,0,24,0
2,2012-01-02 00:27:00,ИЩЮ ВТОРУЮ ПОЛОВИНКУ МНЕ 23 ЗОВУТ ВАНЯ ПИШИТЕ ...,0,27,0
3,2012-01-02 00:27:00,Эля встречала в шумной компании! Все отлично!,0,27,0
4,2012-01-02 00:27:00,Парень катается по городу. Нужна девушка. 0992...,0,27,0

**Extract Time part**

In [42]:
time['time']=time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2012-01-02 00:21:00,нужен парень 0965188229,0,21,0,00:21:00
1,2012-01-02 00:24:00,Всем привет! Как настроение?,0,24,0,00:24:00
2,2012-01-02 00:27:00,ИЩЮ ВТОРУЮ ПОЛОВИНКУ МНЕ 23 ЗОВУТ ВАНЯ ПИШИТЕ ...,0,27,0,00:27:00
3,2012-01-02 00:27:00,Эля встречала в шумной компании! Все отлично!,0,27,0,00:27:00
4,2012-01-02 00:27:00,Парень катается по городу. Нужна девушка. 0992...,0,27,0,00:27:00

**Time differetnce**

In [43]:
today-time['date']

0         4702 days 17:17:53.502400
1         4702 days 17:14:53.502400
2         4702 days 17:11:53.502400
3         4702 days 17:11:53.502400
4         4702 days 17:11:53.502400
                     ...
1147095   2845 days 17:16:53.502400
1147096   2845 days 17:16:53.502400
1147097   2845 days 17:16:53.502400
1147098   2845 days 17:14:53.502400
1147099   2845 days 17:12:53.502400
Name: date, Length: 1147100, dtype: timedelta64[ns]

**in seconds**

In [45]:
(today-time['date'])/np.timedelta64(1,'s')

0          4.063151e+08
1          4.063149e+08
2          4.063147e+08
3          4.063147e+08
4          4.063147e+08
               ...
1147095    2.458702e+08
1147096    2.458702e+08
1147097    2.458702e+08
1147098    2.458701e+08
1147099    2.458700e+08
Name: date, Length: 1147100, dtype: float64

In [46]:
#in minutes
(today-time['date'])/np.timedelta64(1,'m')

0          6.771918e+06
1          6.771915e+06
2          6.771912e+06
3          6.771912e+06
4          6.771912e+06
               ...
1147095    4.097837e+06
1147096    4.097837e+06
1147097    4.097837e+06
1147098    4.097835e+06
1147099    4.097833e+06
Name: date, Length: 1147100, dtype: float64