In [69]:
with open("weather_data.csv") as f:
    datas=f.readlines()
    print(datas)
    for data in datas:
        #print(data)
        pass

['day,temp,condition\n', 'Monday,12,Sunny\n', 'Tuesday,14,Rain\n', 'Wednesday,15,Rain\n', 'Thursday,14,Cloudy\n', 'Friday,21,Sunny\n', 'Saturday,22,Sunny\n', 'Sunday,24,Sunny']

In [70]:
import csv

with open("weather_data.csv") as f:
    datas=csv.reader(f)
    temp=[]
    #print(type(datas))
    for row in datas:
        if row[1]!="temp":
            #print(row)
            temp.append(int(row[1]))

    print(temp)

[12, 14, 15, 14, 21, 22, 24]

In [71]:
import pandas

data=pandas.read_csv("weather_data.csv")
print(data["day"])

0       Monday
1      Tuesday
2    Wednesday
3     Thursday
4       Friday
5     Saturday
6       Sunday
Name: day, dtype: object

In [72]:
data_dict=data.to_dict()
print(data_dict)

{'day': {0: 'Monday', 1: 'Tuesday', 2: 'Wednesday', 3: 'Thursday', 4: 'Friday', 5: 'Saturday', 6: 'Sunday'}, 'temp': {0: 12, 1: 14, 2: 15, 3: 14, 4: 21, 5: 22, 6: 24}, 'condition': {0: 'Sunny', 1: 'Rain', 2: 'Rain', 3: 'Cloudy', 4: 'Sunny', 5: 'Sunny', 6: 'Sunny'}}

In [73]:
temp_list=data["temp"].to_list()
print(temp_list)
print(sum(temp_list)/len(temp_list))

[12, 14, 15, 14, 21, 22, 24]
17.428571428571427

In [74]:
data["temp"].mean()

np.float64(17.428571428571427)

In [75]:
data["temp"].max()

np.int64(24)

In [76]:
data[data.day=="Monday"]

      day  temp condition
0  Monday    12     Sunny

Extracting the row with the max temp

In [77]:
data[data.temp==data.temp.max()]

      day  temp condition
6  Sunday    24     Sunny

In [78]:
monday=data[data.day=="Monday"]
print(monday)
print(monday.temp[0]*1.8+32)

      day  temp condition
0  Monday    12     Sunny
53.6

In [79]:
new_dict={
    "yo":[1,2,3,4,5,6,88],
    "yolo":[1,2,3,4,5,6,67]
}
data=pandas.DataFrame(new_dict)
data.to_csv("new_one.csv")