## Nominal/ OHE encoding

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({
    "color": ["red", "blue", "green", "red", "blue"]
})

df

   color
0    red
1   blue
2  green
3    red
4   blue

In [6]:
## Create an instance of one hot encoder

encoder = OneHotEncoder()

encoder.fit_transform(df[["color"]]).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [9]:
encoded = encoder.fit_transform(df[["color"]])

encoded_df = pd.DataFrame(encoded.toarray(), columns=encoder.get_feature_names_out())
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [10]:
pd.concat([df, encoded_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0
4   blue         1.0          0.0        0.0