In [1]:
import sys

import pandas as pd
import numpy as np

sys.path.append(r'C:\Users\user\Desktop\github\sotrans_analytics_department')
from source.core.de.serving.datamart import Datamart

# ETL

## Extract

In [2]:
datamart: Datamart = Datamart(
    period=8,
    agg_cat_cols=(
        'wh_name',
        'ca_name',
        'ca_type',
        'ca_status',
        'brand_name_1c',
        'sku_id_1c',
    ),
    agg_dgt_cols=(
        'cnt',
    ),
    agg_dt_cols=(
        'year',
        'week'
    )
)

2025-05-20 09:46:11.410 | DEBUG    | source.core.de.serving.datamart.datamart:calc_start_date:301 - Конечная дата анализируемого периода не задана, используется значение из Datamart: 2025-05-19
2025-05-20 09:46:11.410 | SUCCESS  | source.core.de.serving.datamart.datamart:calc_start_date:322 - Начальная дата анализируемого периода успешно рассчитана: 2024-10-01

In [3]:
# Конечный остаток;
datamart.IEnd.add_final()

2025-05-20 09:46:11.424 | DEBUG    | source.core.de.serving.datamart.datamart:__get_interface:255 - Создание интерфейса: IEnd
2025-05-20 09:46:11.425 | SUCCESS  | source.core.de.serving.datamart.datamart:__get_interface:257 - Интерфейс IEnd успешно создан
2025-05-20 09:46:11.426 | SUCCESS  | source.core.de.serving.datamart.modules.utils._validate_data:is_cols_available:87 - Кортеж доступных числовых столбцов: ('cnt',)
2025-05-20 09:46:11.426 | SUCCESS  | source.core.de.serving.datamart.modules.sql.sql_end:get_sql_query_final:49 - SQL-запрос успешно сформирован
2025-05-20 09:46:12.219 | SUCCESS  | source.core.de.serving.datamart.modules.utils._sql_executor:execute_sql_query:52 - SQL-запрос успешно выполнен. DataFrame сформирован: (73167, 7)
2025-05-20 09:46:12.348 | SUCCESS  | source.core.de.serving.datamart.datamart:df:155 - Витрина данных обновлена: (73167, 7)

In [4]:
# Перемещения между филиалами;
datamart.ITransfer.add_transfer()

2025-05-20 09:46:12.354 | DEBUG    | source.core.de.serving.datamart.datamart:__get_interface:255 - Создание интерфейса: ITransfer
2025-05-20 09:46:12.354 | SUCCESS  | source.core.de.serving.datamart.datamart:__get_interface:257 - Интерфейс ITransfer успешно создан
2025-05-20 09:46:12.355 | SUCCESS  | source.core.de.serving.datamart.modules.utils._validate_data:is_cols_available:87 - Кортеж доступных числовых столбцов: ('cnt',)
2025-05-20 09:46:12.356 | SUCCESS  | source.core.de.serving.datamart.modules.sql.sql_transfer:get_sql_query_transfer:49 - SQL-запрос успешно сформирован
2025-05-20 09:46:12.394 | SUCCESS  | source.core.de.serving.datamart.modules.utils._sql_executor:execute_sql_query:52 - SQL-запрос успешно выполнен. DataFrame сформирован: (2449, 7)
2025-05-20 09:46:12.633 | SUCCESS  | source.core.de.serving.datamart.datamart:df:155 - Витрина данных обновлена: (74655, 8)

In [5]:
# Данные по приёмке товаров;
datamart.IArrival.add_arrival()

2025-05-20 09:46:12.640 | DEBUG    | source.core.de.serving.datamart.datamart:__get_interface:255 - Создание интерфейса: IArrival
2025-05-20 09:46:12.641 | SUCCESS  | source.core.de.serving.datamart.datamart:__get_interface:257 - Интерфейс IArrival успешно создан
2025-05-20 09:46:12.642 | SUCCESS  | source.core.de.serving.datamart.modules.utils._validate_data:is_cols_available:87 - Кортеж доступных числовых столбцов: ('cnt',)
2025-05-20 09:46:12.642 | SUCCESS  | source.core.de.serving.datamart.modules.sql.sql_arrival:get_sql_query_arrival:49 - SQL-запрос успешно сформирован
2025-05-20 09:46:12.665 | SUCCESS  | source.core.de.serving.datamart.modules.utils._sql_executor:execute_sql_query:52 - SQL-запрос успешно выполнен. DataFrame сформирован: (17, 7)
2025-05-20 09:46:12.869 | SUCCESS  | source.core.de.serving.datamart.datamart:df:155 - Витрина данных обновлена: (74671, 9)

In [6]:
# Данные по продажам;
datamart.IExpend.add_sale()

2025-05-20 09:46:12.876 | DEBUG    | source.core.de.serving.datamart.datamart:__get_interface:255 - Создание интерфейса: IExpend
2025-05-20 09:46:12.877 | SUCCESS  | source.core.de.serving.datamart.datamart:__get_interface:257 - Интерфейс IExpend успешно создан
2025-05-20 09:46:12.877 | SUCCESS  | source.core.de.serving.datamart.modules.utils._validate_data:is_cols_available:87 - Кортеж доступных числовых столбцов: ('cnt',)
2025-05-20 09:46:12.877 | SUCCESS  | source.core.de.serving.datamart.modules.sql.sql_expend:get_sql_query_sale:254 - SQL-запрос успешно сформирован
2025-05-20 09:46:13.688 | SUCCESS  | source.core.de.serving.datamart.modules.utils._sql_executor:execute_sql_query:52 - SQL-запрос успешно выполнен. DataFrame сформирован: (66007, 7)
2025-05-20 09:46:14.079 | SUCCESS  | source.core.de.serving.datamart.datamart:df:155 - Витрина данных обновлена: (125635, 10)

## Transform

### Pre-Processing

In [11]:
# Замена пропусков в категориальных столбцах;
for col in (
        'wh_name',
        'ca_name',
        'ca_type',
        'ca_status',
        'brand_name_1c',
        'sku_id_1c'
):
    datamart.df[col] = datamart.df[col].fillna(value='_нет данных')

In [12]:
# Замена пропусков в количественных столбцах;
for col in (
        'en_final_cnt_fd',
        'tr_transfer_cnt_fd',
        'ar_arrival_cnt_fd',
        'ex_sale_cnt_sum_8_week',
):
    datamart.df[col] = datamart.df[col].fillna(value=0)

In [13]:
# Классификация дилер/перекуп;
condition = (
    datamart.df['ca_type']
    .isin(values=['дилерский контракт', 'плановые закупки в рф'])
)

datamart.df['ca_type'] = (
    np.where(
        condition,
        'дилерский',
        'перекуп'
    )
)

In [14]:
# Предварительная фильтрация;
datamart.df = datamart.df.query(
    expr="ca_type == 'дилерский'"
    " and wh_name != '_не используется'"
)

2025-05-20 09:48:20.699 | SUCCESS  | source.core.de.serving.datamart.datamart:df:155 - Витрина данных обновлена: (55503, 10)

In [16]:
datamart.df = (
    datamart.df
    .groupby(
        by=[
            'wh_name',
            'brand_name_1c',
            'sku_id_1c'
        ]
    )
    .aggregate(
        {
            'en_final_cnt_fd': 'sum',
            'tr_transfer_cnt_fd': 'sum',
            'ar_arrival_cnt_fd': 'sum',
            'ex_sale_cnt_sum_8_week': 'sum'
        }
    )
    .reset_index()
)

2025-05-20 09:48:27.953 | SUCCESS  | source.core.de.serving.datamart.datamart:df:155 - Витрина данных обновлена: (51635, 7)

In [20]:
# Расчёт количества недель с наличием;
datamart.IHaving.add_stock(
    agg_cat_cols=(
        'wh_name',
        'brand_name_1c',
        'sku_id_1c'
    )
)

2025-05-20 09:48:55.312 | DEBUG    | source.core.de.serving.datamart.datamart:__get_interface:255 - Создание интерфейса: IHaving
2025-05-20 09:48:55.313 | SUCCESS  | source.core.de.serving.datamart.datamart:__get_interface:257 - Интерфейс IHaving успешно создан
2025-05-20 09:48:55.313 | SUCCESS  | source.core.de.serving.datamart.modules.utils._validate_data:is_cols_available:87 - Кортеж доступных числовых столбцов: ('cnt',)
2025-05-20 09:48:55.313 | SUCCESS  | source.core.de.serving.datamart.modules.sql.sql_having:get_sql_query_stock:46 - SQL-запрос успешно сформирован
2025-05-20 10:13:19.545 | SUCCESS  | source.core.de.serving.datamart.modules.utils._sql_executor:execute_sql_query:52 - SQL-запрос успешно выполнен. DataFrame сформирован: (104114, 4)
2025-05-20 10:13:19.773 | SUCCESS  | source.core.de.serving.datamart.datamart:df:155 - Витрина данных обновлена: (104592, 8)

In [18]:
# Предварительная фильтрация;
datamart.df = datamart.df.query(
    expr="wh_name != '_не используется'"
)

2025-05-20 09:48:43.682 | SUCCESS  | source.core.de.serving.datamart.datamart:df:155 - Витрина данных обновлена: (51635, 7)

In [22]:
(
    datamart.df
    .query(expr='sku_id_1c == "цб293430"')
)

,wh_name,brand_name_1c,sku_id_1c,en_final_cnt_fd,tr_transfer_cnt_fd,ar_arrival_cnt_fd,ex_sale_cnt_sum_8_week,hv_stock_8_week
12041,_не используется,техавтосвет,цб293430,NaN,NaN,NaN,NaN,15.0
19164,_склад новосибирск,техавтосвет,цб293430,15.0,0.0,0.0,0.0,31.0
34387,_склад санкт-петербург (красный бор),техавтосвет,цб293430,NaN,NaN,NaN,NaN,17.0
37841,магазин архангельск,техавтосвет,цб293430,1.0,0.0,0.0,8.0,31.0
41794,магазин великий новгород,техавтосвет,цб293430,NaN,NaN,NaN,NaN,18.0
50342,магазин екатеринбург 1,техавтосвет,цб293430,5.0,0.0,0.0,1.0,31.0
54071,магазин екатеринбург 2,техавтосвет,цб293430,4.0,0.0,0.0,2.0,31.0
60648,магазин красноярск,техавтосвет,цб293430,2.0,0.0,0.0,0.0,31.0
63054,магазин москва (ельня),техавтосвет,цб293430,8.0,0.0,0.0,0.0,31.0
71706,магазин нижний новгород 1,техавтосвет,цб293430,5.0,0.0,0.0,0.0,31.0
80920,магазин петрозаводск,техавтосвет,цб293430,2.0,0.0,0.0,2.0,31.0
86786,магазин ростов-на-дону,техавтосвет,цб293430,4.0,0.0,0.0,0.0,31.0
93055,магазин санкт-петербург (шушары 2),техавтосвет,цб293430,9.0,0.0,0.0,0.0,31.0
97857,магазин тольятти 1,техавтосвет,цб293430,10.0,0.0,0.0,0.0,31.0
101579,магазин уфа,техавтосвет,цб293430,10.0,0.0,0.0,0.0,30.0
104563,магазин челябинск,техавтосвет,цб293430,14.0,0.0,0.0,0.0,31.0

### Feature Engineering

In [23]:
# Расчёт фактического остатка с учётом перемещений и приёмки товаров;
datamart.df['fact_cnt'] = (
    datamart.df['en_final_cnt_fd']
    + datamart.df['tr_transfer_cnt_fd']
    + datamart.df['ar_arrival_cnt_fd']
)

In [24]:
(
    datamart.df
    .query(expr='sku_id_1c == "цб293430"')
)

,wh_name,brand_name_1c,sku_id_1c,en_final_cnt_fd,tr_transfer_cnt_fd,ar_arrival_cnt_fd,ex_sale_cnt_sum_8_week,hv_stock_8_week,fact_cnt
12041,_не используется,техавтосвет,цб293430,NaN,NaN,NaN,NaN,15.0,NaN
19164,_склад новосибирск,техавтосвет,цб293430,15.0,0.0,0.0,0.0,31.0,15.0
34387,_склад санкт-петербург (красный бор),техавтосвет,цб293430,NaN,NaN,NaN,NaN,17.0,NaN
37841,магазин архангельск,техавтосвет,цб293430,1.0,0.0,0.0,8.0,31.0,1.0
41794,магазин великий новгород,техавтосвет,цб293430,NaN,NaN,NaN,NaN,18.0,NaN
50342,магазин екатеринбург 1,техавтосвет,цб293430,5.0,0.0,0.0,1.0,31.0,5.0
54071,магазин екатеринбург 2,техавтосвет,цб293430,4.0,0.0,0.0,2.0,31.0,4.0
60648,магазин красноярск,техавтосвет,цб293430,2.0,0.0,0.0,0.0,31.0,2.0
63054,магазин москва (ельня),техавтосвет,цб293430,8.0,0.0,0.0,0.0,31.0,8.0
71706,магазин нижний новгород 1,техавтосвет,цб293430,5.0,0.0,0.0,0.0,31.0,5.0
80920,магазин петрозаводск,техавтосвет,цб293430,2.0,0.0,0.0,2.0,31.0,2.0
86786,магазин ростов-на-дону,техавтосвет,цб293430,4.0,0.0,0.0,0.0,31.0,4.0
93055,магазин санкт-петербург (шушары 2),техавтосвет,цб293430,9.0,0.0,0.0,0.0,31.0,9.0
97857,магазин тольятти 1,техавтосвет,цб293430,10.0,0.0,0.0,0.0,31.0,10.0
101579,магазин уфа,техавтосвет,цб293430,10.0,0.0,0.0,0.0,30.0,10.0
104563,магазин челябинск,техавтосвет,цб293430,14.0,0.0,0.0,0.0,31.0,14.0

In [25]:
datamart.df['mean_month_sales'] = [
    sales / stock * 4.5 
    if stock > 0
    else sales / 25 * 4.5
    for stock, sales in zip(
        datamart.df['hv_stock_8_week'],
        datamart.df['ex_sale_cnt_sum_8_week']
    )
]

In [26]:
(
    datamart.df
    .query(expr='sku_id_1c == "цб293430"')
)

,wh_name,brand_name_1c,sku_id_1c,en_final_cnt_fd,tr_transfer_cnt_fd,ar_arrival_cnt_fd,ex_sale_cnt_sum_8_week,hv_stock_8_week,fact_cnt,mean_month_sales
12041,_не используется,техавтосвет,цб293430,NaN,NaN,NaN,NaN,15.0,NaN,NaN
19164,_склад новосибирск,техавтосвет,цб293430,15.0,0.0,0.0,0.0,31.0,15.0,0.000000
34387,_склад санкт-петербург (красный бор),техавтосвет,цб293430,NaN,NaN,NaN,NaN,17.0,NaN,NaN
37841,магазин архангельск,техавтосвет,цб293430,1.0,0.0,0.0,8.0,31.0,1.0,1.161290
41794,магазин великий новгород,техавтосвет,цб293430,NaN,NaN,NaN,NaN,18.0,NaN,NaN
50342,магазин екатеринбург 1,техавтосвет,цб293430,5.0,0.0,0.0,1.0,31.0,5.0,0.145161
54071,магазин екатеринбург 2,техавтосвет,цб293430,4.0,0.0,0.0,2.0,31.0,4.0,0.290323
60648,магазин красноярск,техавтосвет,цб293430,2.0,0.0,0.0,0.0,31.0,2.0,0.000000
63054,магазин москва (ельня),техавтосвет,цб293430,8.0,0.0,0.0,0.0,31.0,8.0,0.000000
71706,магазин нижний новгород 1,техавтосвет,цб293430,5.0,0.0,0.0,0.0,31.0,5.0,0.000000
80920,магазин петрозаводск,техавтосвет,цб293430,2.0,0.0,0.0,2.0,31.0,2.0,0.290323
86786,магазин ростов-на-дону,техавтосвет,цб293430,4.0,0.0,0.0,0.0,31.0,4.0,0.000000
93055,магазин санкт-петербург (шушары 2),техавтосвет,цб293430,9.0,0.0,0.0,0.0,31.0,9.0,0.000000
97857,магазин тольятти 1,техавтосвет,цб293430,10.0,0.0,0.0,0.0,31.0,10.0,0.000000
101579,магазин уфа,техавтосвет,цб293430,10.0,0.0,0.0,0.0,30.0,10.0,0.000000
104563,магазин челябинск,техавтосвет,цб293430,14.0,0.0,0.0,0.0,31.0,14.0,0.000000

In [27]:
datamart.df['move_to_spb'] = [
    stock - mean_sales
    if stock > mean_sales
    else 0
    for stock, mean_sales in zip(
        datamart.df['fact_cnt'],
        datamart.df['mean_month_sales']
    )
]

In [28]:
(
    datamart.df
    .query(expr='sku_id_1c == "цб293430"')
)

,wh_name,brand_name_1c,sku_id_1c,en_final_cnt_fd,tr_transfer_cnt_fd,ar_arrival_cnt_fd,ex_sale_cnt_sum_8_week,hv_stock_8_week,fact_cnt,mean_month_sales,move_to_spb
12041,_не используется,техавтосвет,цб293430,NaN,NaN,NaN,NaN,15.0,NaN,NaN,0.000000
19164,_склад новосибирск,техавтосвет,цб293430,15.0,0.0,0.0,0.0,31.0,15.0,0.000000,15.000000
34387,_склад санкт-петербург (красный бор),техавтосвет,цб293430,NaN,NaN,NaN,NaN,17.0,NaN,NaN,0.000000
37841,магазин архангельск,техавтосвет,цб293430,1.0,0.0,0.0,8.0,31.0,1.0,1.161290,0.000000
41794,магазин великий новгород,техавтосвет,цб293430,NaN,NaN,NaN,NaN,18.0,NaN,NaN,0.000000
50342,магазин екатеринбург 1,техавтосвет,цб293430,5.0,0.0,0.0,1.0,31.0,5.0,0.145161,4.854839
54071,магазин екатеринбург 2,техавтосвет,цб293430,4.0,0.0,0.0,2.0,31.0,4.0,0.290323,3.709677
60648,магазин красноярск,техавтосвет,цб293430,2.0,0.0,0.0,0.0,31.0,2.0,0.000000,2.000000
63054,магазин москва (ельня),техавтосвет,цб293430,8.0,0.0,0.0,0.0,31.0,8.0,0.000000,8.000000
71706,магазин нижний новгород 1,техавтосвет,цб293430,5.0,0.0,0.0,0.0,31.0,5.0,0.000000,5.000000
80920,магазин петрозаводск,техавтосвет,цб293430,2.0,0.0,0.0,2.0,31.0,2.0,0.290323,1.709677
86786,магазин ростов-на-дону,техавтосвет,цб293430,4.0,0.0,0.0,0.0,31.0,4.0,0.000000,4.000000
93055,магазин санкт-петербург (шушары 2),техавтосвет,цб293430,9.0,0.0,0.0,0.0,31.0,9.0,0.000000,9.000000
97857,магазин тольятти 1,техавтосвет,цб293430,10.0,0.0,0.0,0.0,31.0,10.0,0.000000,10.000000
101579,магазин уфа,техавтосвет,цб293430,10.0,0.0,0.0,0.0,30.0,10.0,0.000000,10.000000
104563,магазин челябинск,техавтосвет,цб293430,14.0,0.0,0.0,0.0,31.0,14.0,0.000000,14.000000

### Separating

In [31]:
# Вспомогательный DataFrame; только Центральный Склад;
df_wh_spb: pd.DataFrame = datamart.df.query(
    expr="wh_name == '_склад санкт-петербург (красный бор)'"
)

In [32]:
(
    df_wh_spb
    .query(expr='sku_id_1c == "цб293430"')
)

,wh_name,brand_name_1c,sku_id_1c,en_final_cnt_fd,tr_transfer_cnt_fd,ar_arrival_cnt_fd,ex_sale_cnt_sum_8_week,hv_stock_8_week,fact_cnt,mean_month_sales,move_to_spb
34387,_склад санкт-петербург (красный бор),техавтосвет,цб293430,NaN,NaN,NaN,NaN,17.0,NaN,NaN,0.0

In [33]:
# Вспомогательный DataFrame; только Центральный Склад;
df_shops: pd.DataFrame = datamart.df.query(
    expr="wh_name != '_склад санкт-петербург (красный бор)' "
    "and wh_name != '_не используется'"
)

### Group by

In [34]:
pt_wh_spb: pd.DataFrame = (
    df_wh_spb
    .groupby(by=['brand_name_1c', 'sku_id_1c'])
    .aggregate(
        {
            'en_final_cnt_fd': 'sum',
            'tr_transfer_cnt_fd': 'sum',
            'ar_arrival_cnt_fd': 'sum',
            'ex_sale_cnt_sum_8_week': 'sum',
            'hv_stock_8_week': 'mean',
            'fact_cnt': 'sum',
            'mean_month_sales': 'sum'
        }
    )
    .rename(
        columns={
            'ex_sale_cnt_sum_8_week': 'spb_ex_sale_cnt_sum_8_week',
            'mean_month_sales': 'spb_mean_month_sales',
            'hv_stock_8_week': 'spb_hv_stock_8_week',
            'fact_cnt': 'spb_fact_cnt',
        }
    )
    .reset_index()
)

In [36]:
(
    pt_wh_spb
    .query(expr='sku_id_1c == "цб293430"')
)

,brand_name_1c,sku_id_1c,en_final_cnt_fd,tr_transfer_cnt_fd,ar_arrival_cnt_fd,spb_ex_sale_cnt_sum_8_week,spb_hv_stock_8_week,spb_fact_cnt,spb_mean_month_sales
15192,техавтосвет,цб293430,0.0,0.0,0.0,0.0,17.0,0.0,0.0

In [37]:
pt_shops: pd.DataFrame = (
    df_shops
    .groupby(by=['wh_name', 'brand_name_1c', 'sku_id_1c'])
    .aggregate(
        {
            'ex_sale_cnt_sum_8_week': 'sum',
            'hv_stock_8_week': 'mean',
            'fact_cnt': 'sum',
            'mean_month_sales': 'sum',
            'move_to_spb': 'sum'
        }
    )
    .rename(
        columns={
            'ex_sale_cnt_sum_8_week': 'shop_ex_sale_cnt_sum_8_week',
            'mean_month_sales': 'shop_mean_month_sales',
            'hv_stock_8_week': 'shop_hv_stock_8_week',
            'fact_cnt': 'shop_fact_cnt',
        }
    )
    .reset_index()
)

In [43]:
result_table: pd.DataFrame = pd.merge(
    left=pt_wh_spb,
    right=pt_shops,
    how='outer',
    on=['brand_name_1c', 'sku_id_1c']
)

In [44]:
(
    result_table
    .query(expr='sku_id_1c == "цб323186"')
)

,brand_name_1c,sku_id_1c,en_final_cnt_fd,tr_transfer_cnt_fd,ar_arrival_cnt_fd,spb_ex_sale_cnt_sum_8_week,spb_hv_stock_8_week,spb_fact_cnt,spb_mean_month_sales,wh_name,shop_ex_sale_cnt_sum_8_week,shop_hv_stock_8_week,shop_fact_cnt,shop_mean_month_sales,move_to_spb
73534,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин архангельск,1.0,4.0,0.0,1.125000,0.0
73535,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин великий новгород,0.0,31.0,1.0,0.000000,1.0
73536,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин воронеж,0.0,31.0,1.0,0.000000,1.0
73537,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин екатеринбург 2,0.0,31.0,1.0,0.000000,1.0
73538,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин красноярск,0.0,31.0,2.0,0.000000,2.0
73539,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин москва (ельня),0.0,31.0,1.0,0.000000,1.0
73540,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин москва (ленинградка),1.0,6.0,0.0,0.750000,0.0
73541,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин мурманск,0.0,31.0,2.0,0.000000,2.0
73542,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин нижний новгород 1,1.0,5.0,0.0,0.900000,0.0
73543,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин нижний новгород 2,2.0,19.0,0.0,0.473684,0.0
73544,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин петрозаводск,5.0,19.0,0.0,1.184211,0.0
73545,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин псков,0.0,17.0,0.0,0.000000,0.0
73546,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин ростов-на-дону,0.0,17.0,0.0,0.000000,0.0
73547,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин санкт-петербург (парнас),0.0,17.0,0.0,0.000000,0.0
73548,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин санкт-петербург (шушары 2),1.0,17.0,0.0,0.264706,0.0
73549,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин тольятти 1,0.0,31.0,2.0,0.000000,2.0
73550,truck part,цб323186,0.0,0.0,0.0,0.0,1.0,0.0,0.0,магазин челябинск,0.0,31.0,1.0,0.000000,1.0

In [45]:
result_table

,brand_name_1c,sku_id_1c,en_final_cnt_fd,tr_transfer_cnt_fd,ar_arrival_cnt_fd,spb_ex_sale_cnt_sum_8_week,spb_hv_stock_8_week,spb_fact_cnt,spb_mean_month_sales,wh_name,shop_ex_sale_cnt_sum_8_week,shop_hv_stock_8_week,shop_fact_cnt,shop_mean_month_sales,move_to_spb
0,1 new,цб336538,NaN,NaN,NaN,NaN,NaN,NaN,NaN,магазин москва (ельня),0.0,31.0,1.0,0.00,1.0
1,1 new,цб336539,NaN,NaN,NaN,NaN,NaN,NaN,NaN,магазин красноярск,0.0,31.0,5.0,0.00,5.0
2,1 new,цб336539,NaN,NaN,NaN,NaN,NaN,NaN,NaN,магазин санкт-петербург (шушары 2),0.0,31.0,3.0,0.00,3.0
3,1 new,цб336540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,магазин красноярск,7.0,30.0,0.0,1.05,0.0
4,1 new,цб336540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,магазин санкт-петербург (парнас),0.0,31.0,2.0,0.00,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84357,ямз,цб428107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,_склад новосибирск,0.0,2.0,0.0,0.00,0.0
84358,ямз,цб439077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,магазин мурманск,0.0,7.0,0.0,0.00,0.0
84359,япония,цб329173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,магазин красноярск,0.0,24.0,0.0,0.00,0.0
84360,ярти,цб431068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,магазин архангельск,1.0,10.0,0.0,0.45,0.0
84361,ярти,цб437479,NaN,NaN,NaN,NaN,NaN,NaN,NaN,магазин мурманск,0.0,14.0,0.0,0.00,0.0

## Load

In [46]:
result_table.to_json(path_or_buf='move_to_wh_spb.json', orient='table', index=False)