In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
product_df = pd.read_csv('clean_skincare_product_1_1.csv')
product_df.head(5)

,subcategory,brand,product_name,variant,price,description,link,image_url
0,Mask Sheet,A Bonne,Berry-Me-Baby Sheetmask,NaN,Rp. 10.000,sheetmask seri a bloom varian blueberry untuk ...,https://reviews.femaledaily.com/products/mask/...,https://image.femaledaily.com/dyn/210/images/p...
1,Wash-Off,A by BOM,Huppies,Milk Face Mask,Rp. 10.000,"menyembuhkan kulit kusam, efek anti-aging, men...",https://reviews.femaledaily.com/products/mask/...,https://image.femaledaily.com/dyn/210/images/p...
2,Wash-Off,A by BOM,Huppies Beet Root Face Mask,NaN,Rp. 6.000,masker organik yang memiliki claim :\r\n1. mem...,https://reviews.femaledaily.com/products/mask/...,https://image.femaledaily.com/dyn/210/images/p...
3,Wash-Off,A by BOM,Huppies Peel Off Mask,NaN,Rp. 8.000,Peel Off Mask 4 Varian :\r\n- Black Collagen\r...,https://reviews.femaledaily.com/products/mask/...,https://image.femaledaily.com/dyn/210/images/p...
4,Serum & Essence,A'kin,Certified Organic Rosehip Oil,NaN,Rp. 532.134,A'kin Certified Organic Rosehip Oil merupakan ...,https://reviews.femaledaily.com/products/treat...,https://image.femaledaily.com/dyn/210/images/p...

In [3]:
# hapus kolom yang tidak diperlukan
product_df.drop(['link'], axis=1, inplace=True)

In [4]:
product_df.head(5)

,subcategory,brand,product_name,variant,price,description,image_url
0,Mask Sheet,A Bonne,Berry-Me-Baby Sheetmask,NaN,Rp. 10.000,sheetmask seri a bloom varian blueberry untuk ...,https://image.femaledaily.com/dyn/210/images/p...
1,Wash-Off,A by BOM,Huppies,Milk Face Mask,Rp. 10.000,"menyembuhkan kulit kusam, efek anti-aging, men...",https://image.femaledaily.com/dyn/210/images/p...
2,Wash-Off,A by BOM,Huppies Beet Root Face Mask,NaN,Rp. 6.000,masker organik yang memiliki claim :\r\n1. mem...,https://image.femaledaily.com/dyn/210/images/p...
3,Wash-Off,A by BOM,Huppies Peel Off Mask,NaN,Rp. 8.000,Peel Off Mask 4 Varian :\r\n- Black Collagen\r...,https://image.femaledaily.com/dyn/210/images/p...
4,Serum & Essence,A'kin,Certified Organic Rosehip Oil,NaN,Rp. 532.134,A'kin Certified Organic Rosehip Oil merupakan ...,https://image.femaledaily.com/dyn/210/images/p...

In [5]:
product_df.shape

(11194, 7)

In [6]:
product_df.duplicated().sum()

2

In [7]:
product_df[product_df.duplicated(keep = False)]

,subcategory,brand,product_name,variant,price,description,image_url
2407,Face,Crystallure,Supreme Double Action Micellar Gel,NaN,Rp. 120.000,Micellar Gel dengan teknologi Double Action un...,https://image.femaledaily.com/dyn/210/images/p...
2410,Face,Crystallure,Supreme Double Action Micellar Gel,NaN,Rp. 120.000,Micellar Gel dengan teknologi Double Action un...,https://image.femaledaily.com/dyn/210/images/p...
7444,Facial Wash,Nu Skin,Epoch Cleansing Bar,NaN,Rp. 326.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...
7460,Facial Wash,Nu Skin,Epoch Cleansing Bar,NaN,Rp. 326.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...

In [8]:
product_df.drop_duplicates(inplace=True, keep='first')
product_df.duplicated().sum()

0

In [9]:
product_df.isnull().sum()

subcategory        0
brand              0
product_name       0
variant         9294
price              0
description        1
image_url          0
dtype: int64

In [10]:
product_df.shape

(11192, 7)

### menangani data variant

In [11]:
product_df[product_df.product_name.str.lower().str.contains('skin bae')].head(5)

,subcategory,brand,product_name,variant,price,description,image_url
154,Serum & Essence,AVOSKIN,Your Skin Bae Serum,Alpha Arbutin 3% + Grapeseed,Rp. 139.000,Avoskin Your Skin Bae Ultimate Alpha Arbutin 3...,https://image.femaledaily.com/dyn/210/images/p...
158,Serum & Essence,AVOSKIN,Your Skin Bae Serum,Niacinamide 12% + Centella,Rp. 157.900,Avoskin Your Skin Bae Serum Niacinamide 12% + ...,https://image.femaledaily.com/dyn/210/images/p...
159,Serum & Essence,AVOSKIN,Your Skin Bae Serum,Marine Collagen 10% + Gingseng Root,Rp. 139.000,Reformulation in August 2022\r\n\r\nAvoskin Yo...,https://image.femaledaily.com/dyn/210/images/p...
160,Serum & Essence,AVOSKIN,Your Skin Bae Serum,Ultimate Hyaluron HYACROSS 3% + Green Tea,Rp. 139.000,Avoskin Your Skin Bae Ultimate Hyaluron HYACRO...,https://image.femaledaily.com/dyn/210/images/p...
163,Serum & Essence,AVOSKIN,Your Skin Bae Serum,Salicylic Acid 2% + Zinc,Rp. 152.900,Avoskin Your Skin Bae Serum Salicylic Acid 2% ...,https://image.femaledaily.com/dyn/210/images/p...

### concat product_name dan variant

In [12]:
product_df.product_name.duplicated().sum()

1357

In [13]:
product_df[['brand', 'product_name']].duplicated().sum()

649

In [14]:
product_df[product_df.duplicated(['brand', 'product_name'], keep=False)]

,subcategory,brand,product_name,variant,price,description,image_url
66,Mask Sheet,AHC,Natural Essential Mask Aqua,Nourishing,Rp. 38.900,AHC Natural Essential Mask Aqua merupakan mild...,https://image.femaledaily.com/dyn/210/images/p...
75,Mask Sheet,AHC,Natural Essential Mask Aqua,Brightening,Rp. 36.000,Mild Essence yang Berasal dari Bahan Alami – e...,https://image.femaledaily.com/dyn/210/images/p...
116,Mask Sheet,APIEU,Icing Sweet Bar Sheet Mask,Watermelon,Rp. 12.000,"Hydrates and moisturizes. Thin, lightweight te...",https://image.femaledaily.com/dyn/210/images/p...
119,Mask Sheet,APIEU,Icing Sweet Bar Sheet Mask,Melon,Rp. 12.900,"Mengandung ekstrak buah yang menutrisi, menena...",https://image.femaledaily.com/dyn/210/images/p...
121,Mask Sheet,APIEU,Icing Sweet Bar Sheet Mask,Pineapple,Rp. 12.000,"- Smooths and hydrates\r\n- Thin, lightweight ...",https://image.femaledaily.com/dyn/210/images/p...
...,...,...,...,...,...,...,...
11162,Mask Sheet,3W CLINIC,Fresh Mask Sheet,Pomegranate,Rp. 20.000,This is a sheet-type mask containing a variety...,https://image.femaledaily.com/dyn/210/images/p...
11165,Mask Sheet,3W CLINIC,Fresh Mask Sheet,Red Gingseng,Rp. 20.000,"A sheet-type, hypoallergenic facial mask. Form...",https://image.femaledaily.com/dyn/210/images/p...
11167,Mask Sheet,3W CLINIC,Fresh Mask Sheet,Collagen,Rp. 20.000,This is a sheet-type mask containing a variety...,https://image.femaledaily.com/dyn/210/images/p...
11168,Mask Sheet,3W CLINIC,Fresh Mask Sheet,White,Rp. 20.000,This is a sheet-type mask containing a variety...,https://image.femaledaily.com/dyn/210/images/p...
11169,Mask Sheet,3W CLINIC,Fresh Mask Sheet,Snail,Rp. 20.000,This is a sheet-type mask containing a variety...,https://image.femaledaily.com/dyn/210/images/p...

pada dataset brand dan product name duplikat namun dibedakan oleh variant sehingga disini digabungkan product_name dan variant

In [15]:
product_df['product_name_variant_concat'] = product_df.apply(lambda x: '_'.join([x.product_name, x.variant]) 
                                                   if pd.notnull(x.variant) else x.product_name, axis=1)

In [16]:
product_df.head(5)

,subcategory,brand,product_name,variant,price,description,image_url,product_name_variant_concat
0,Mask Sheet,A Bonne,Berry-Me-Baby Sheetmask,NaN,Rp. 10.000,sheetmask seri a bloom varian blueberry untuk ...,https://image.femaledaily.com/dyn/210/images/p...,Berry-Me-Baby Sheetmask
1,Wash-Off,A by BOM,Huppies,Milk Face Mask,Rp. 10.000,"menyembuhkan kulit kusam, efek anti-aging, men...",https://image.femaledaily.com/dyn/210/images/p...,Huppies_Milk Face Mask
2,Wash-Off,A by BOM,Huppies Beet Root Face Mask,NaN,Rp. 6.000,masker organik yang memiliki claim :\r\n1. mem...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Beet Root Face Mask
3,Wash-Off,A by BOM,Huppies Peel Off Mask,NaN,Rp. 8.000,Peel Off Mask 4 Varian :\r\n- Black Collagen\r...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Peel Off Mask
4,Serum & Essence,A'kin,Certified Organic Rosehip Oil,NaN,Rp. 532.134,A'kin Certified Organic Rosehip Oil merupakan ...,https://image.femaledaily.com/dyn/210/images/p...,Certified Organic Rosehip Oil

In [17]:
product_df[['brand', 'product_name_variant_concat']].duplicated().sum()

9

In [18]:
product_df[product_df.duplicated(['brand', 'product_name_variant_concat'], keep=False)]

,subcategory,brand,product_name,variant,price,description,image_url,product_name_variant_concat
271,Sleeping Mask,Acure,The Magical Wonderfluff,NaN,Rp. 265.647.11,Acure The Magical Wonderfluff merupakan sleepi...,https://image.femaledaily.com/dyn/210/images/p...,The Magical Wonderfluff
275,Lotion & Emulsion,Acure,The Magical Wonderfluff,NaN,Rp. 265.627.12,Acure The Magical Wonderfluff merupakan moistu...,https://image.femaledaily.com/dyn/210/images/p...,The Magical Wonderfluff
614,Face Oil,Apotium,Phytonutrients Revitalizing Serum-Oil,NaN,Rp. 199.000,Lightweight serum-oil nourishes skin and maint...,https://image.femaledaily.com/dyn/210/images/p...,Phytonutrients Revitalizing Serum-Oil
616,Serum & Essence,Apotium,Phytonutrients Revitalizing Serum-Oil,NaN,Rp. 199.000,Lightweight serum-oil nourishes skin and maint...,https://image.femaledaily.com/dyn/210/images/p...,Phytonutrients Revitalizing Serum-Oil
2251,Eye & Lip,Clio,Micro-Fessional Lip & Eye Remover,NaN,Rp. 249.000,CLIO Micro-Fessional Lip & Eye Remover cleanse...,https://image.femaledaily.com/dyn/210/images/p...,Micro-Fessional Lip & Eye Remover
2252,Eye & Lip,Clio,Micro-Fessional Lip & Eye Remover,NaN,Rp. 249.000,Kualitas produknya sama dengan maybelline make...,https://image.femaledaily.com/dyn/210/images/p...,Micro-Fessional Lip & Eye Remover
3454,Facial Wash,Esther Cosmetic,Brightening Soap,NaN,Rp. 100.000,Sabun wajah yang membantu mencerahkan dan memb...,https://image.femaledaily.com/dyn/210/images/p...,Brightening Soap
3459,Facial Wash,Esther Cosmetic,Brightening Soap,NaN,Rp. 100.000,Sabun Wajah untuk Pencerahan by Esther House o...,https://image.femaledaily.com/dyn/210/images/p...,Brightening Soap
3497,Toner,Eucerin,Eucerin,Pro Acne Solution,Rp. 170.000,FACIAL TONER FOR BLEMISH-PRONE SKIN\r\n\r\nCLI...,https://image.femaledaily.com/dyn/210/images/p...,Eucerin_Pro Acne Solution
3506,Facial Wash,Eucerin,Eucerin,Pro Acne Solution,Rp. 160.000,"Soap- and fragrance-free, Eucerin ProACNE Solu...",https://image.femaledaily.com/dyn/210/images/p...,Eucerin_Pro Acne Solution
5036,Toner,Isntree,Isntree Hyaluronic Acid Toner Plus,NaN,Rp. 280.000,Contains 5 different types of hyaluronic acid,https://image.femaledaily.com/dyn/210/images/p...,Isntree Hyaluronic Acid Toner Plus
5041,Lotion & Emulsion,Isntree,Isntree Hyaluronic Acid Toner Plus,NaN,Rp. 250.000,Five types of Hyaluronic Acid\r\ncontains 5 di...,https://image.femaledaily.com/dyn/210/images/p...,Isntree Hyaluronic Acid Toner Plus
6824,Cream,Moreskin,Clean & Glow,NaN,Rp. 130.000,Moreskin Clean & Glow adalah Produk kecantikan...,https://image.femaledaily.com/dyn/210/images/p...,Clean & Glow
6832,Lotion & Emulsion,Moreskin,Clean & Glow,NaN,Rp. 155.000,Moreskin clean & glow adalah krim booster untu...,https://image.femaledaily.com/dyn/210/images/p...,Clean & Glow
7527,Face Oil,Nuxe,Huile Prodigieuse Multi-Usage Dry Oil,NaN,Rp. 325.000,Produk NUXE Huile Prodigieuse® / Multi-Usage D...,https://image.femaledaily.com/dyn/210/images/p...,Huile Prodigieuse Multi-Usage Dry Oil
7530,Oil,Nuxe,Huile Prodigieuse Multi-Usage Dry Oil,NaN,Rp. 448.000,NUXE Huile Prodigieuse Multi-Usage Dry Oil ada...,https://image.femaledaily.com/dyn/210/images/p...,Huile Prodigieuse Multi-Usage Dry Oil
10612,Cream,Vitacreme B12,Regenerative Cream,NaN,Rp. 249.000,Vitacreme B12 Regenerative Cream merupakan kri...,https://image.femaledaily.com/dyn/210/images/p...,Regenerative Cream
10616,Lotion & Emulsion,Vitacreme B12,Regenerative Cream,NaN,Rp. 249.900,Vitacreme B12 Regenerative Cream adalah item t...,https://image.femaledaily.com/dyn/210/images/p...,Regenerative Cream

setelah product_name dan variant digabungkan ternyata masih terdapat data duplikat yang dimana dibedakan oleh subcategory sehingga disini digabungkan juga dengan subcategory

In [19]:
product_df['product_name_concat'] = product_df.apply(lambda x: '_'.join([x.product_name, x.variant, x.subcategory]) 
                                                             if pd.notna(x.variant) 
                                                             else '_'.join([x.product_name, x.subcategory]),
                                                             axis=1)

In [20]:
product_df

,subcategory,brand,product_name,variant,price,description,image_url,product_name_variant_concat,product_name_concat
0,Mask Sheet,A Bonne,Berry-Me-Baby Sheetmask,NaN,Rp. 10.000,sheetmask seri a bloom varian blueberry untuk ...,https://image.femaledaily.com/dyn/210/images/p...,Berry-Me-Baby Sheetmask,Berry-Me-Baby Sheetmask_Mask Sheet
1,Wash-Off,A by BOM,Huppies,Milk Face Mask,Rp. 10.000,"menyembuhkan kulit kusam, efek anti-aging, men...",https://image.femaledaily.com/dyn/210/images/p...,Huppies_Milk Face Mask,Huppies_Milk Face Mask_Wash-Off
2,Wash-Off,A by BOM,Huppies Beet Root Face Mask,NaN,Rp. 6.000,masker organik yang memiliki claim :\r\n1. mem...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Beet Root Face Mask,Huppies Beet Root Face Mask_Wash-Off
3,Wash-Off,A by BOM,Huppies Peel Off Mask,NaN,Rp. 8.000,Peel Off Mask 4 Varian :\r\n- Black Collagen\r...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Peel Off Mask,Huppies Peel Off Mask_Wash-Off
4,Serum & Essence,A'kin,Certified Organic Rosehip Oil,NaN,Rp. 532.134,A'kin Certified Organic Rosehip Oil merupakan ...,https://image.femaledaily.com/dyn/210/images/p...,Certified Organic Rosehip Oil,Certified Organic Rosehip Oil_Serum & Essence
...,...,...,...,...,...,...,...,...,...
11189,Serum & Essence,9wishes,Collagen Ampule Essence,NaN,Rp. 3.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Collagen Ampule Essence,Collagen Ampule Essence_Serum & Essence
11190,Serum & Essence,9wishes,Amazing Pine Ampule Serum,NaN,Rp. 300.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Amazing Pine Ampule Serum,Amazing Pine Ampule Serum_Serum & Essence
11191,Serum & Essence,9wishes,Extreme Oxygen Ampule Serum,NaN,Rp. 300.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Extreme Oxygen Ampule Serum,Extreme Oxygen Ampule Serum_Serum & Essence
11192,Mask Sheet,9wishes,Rice Water Sheet Mask,NaN,Rp. 45.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Rice Water Sheet Mask,Rice Water Sheet Mask_Mask Sheet
11193,Cream,9wishes,Rice Radiance Cream,NaN,Rp. 3.600,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Rice Radiance Cream,Rice Radiance Cream_Cream

In [21]:
product_df[['brand', 'product_name_concat']].duplicated().sum()

2

In [22]:
product_df[product_df.duplicated(['brand', 'product_name_concat'], keep=False)]

,subcategory,brand,product_name,variant,price,description,image_url,product_name_variant_concat,product_name_concat
2251,Eye & Lip,Clio,Micro-Fessional Lip & Eye Remover,NaN,Rp. 249.000,CLIO Micro-Fessional Lip & Eye Remover cleanse...,https://image.femaledaily.com/dyn/210/images/p...,Micro-Fessional Lip & Eye Remover,Micro-Fessional Lip & Eye Remover_Eye & Lip
2252,Eye & Lip,Clio,Micro-Fessional Lip & Eye Remover,NaN,Rp. 249.000,Kualitas produknya sama dengan maybelline make...,https://image.femaledaily.com/dyn/210/images/p...,Micro-Fessional Lip & Eye Remover,Micro-Fessional Lip & Eye Remover_Eye & Lip
3454,Facial Wash,Esther Cosmetic,Brightening Soap,NaN,Rp. 100.000,Sabun wajah yang membantu mencerahkan dan memb...,https://image.femaledaily.com/dyn/210/images/p...,Brightening Soap,Brightening Soap_Facial Wash
3459,Facial Wash,Esther Cosmetic,Brightening Soap,NaN,Rp. 100.000,Sabun Wajah untuk Pencerahan by Esther House o...,https://image.femaledaily.com/dyn/210/images/p...,Brightening Soap,Brightening Soap_Facial Wash

setelah dilihat pada website untuk description menggunakan baris pertama dan tidak ada description pada baris kedua sehingga data duplikat dihapus tetapi tetapi mempertahankan baris pertama

In [23]:
product_df = product_df.drop_duplicates(['brand', 'product_name_variant_concat'], keep='first')
product_df

,subcategory,brand,product_name,variant,price,description,image_url,product_name_variant_concat,product_name_concat
0,Mask Sheet,A Bonne,Berry-Me-Baby Sheetmask,NaN,Rp. 10.000,sheetmask seri a bloom varian blueberry untuk ...,https://image.femaledaily.com/dyn/210/images/p...,Berry-Me-Baby Sheetmask,Berry-Me-Baby Sheetmask_Mask Sheet
1,Wash-Off,A by BOM,Huppies,Milk Face Mask,Rp. 10.000,"menyembuhkan kulit kusam, efek anti-aging, men...",https://image.femaledaily.com/dyn/210/images/p...,Huppies_Milk Face Mask,Huppies_Milk Face Mask_Wash-Off
2,Wash-Off,A by BOM,Huppies Beet Root Face Mask,NaN,Rp. 6.000,masker organik yang memiliki claim :\r\n1. mem...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Beet Root Face Mask,Huppies Beet Root Face Mask_Wash-Off
3,Wash-Off,A by BOM,Huppies Peel Off Mask,NaN,Rp. 8.000,Peel Off Mask 4 Varian :\r\n- Black Collagen\r...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Peel Off Mask,Huppies Peel Off Mask_Wash-Off
4,Serum & Essence,A'kin,Certified Organic Rosehip Oil,NaN,Rp. 532.134,A'kin Certified Organic Rosehip Oil merupakan ...,https://image.femaledaily.com/dyn/210/images/p...,Certified Organic Rosehip Oil,Certified Organic Rosehip Oil_Serum & Essence
...,...,...,...,...,...,...,...,...,...
11189,Serum & Essence,9wishes,Collagen Ampule Essence,NaN,Rp. 3.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Collagen Ampule Essence,Collagen Ampule Essence_Serum & Essence
11190,Serum & Essence,9wishes,Amazing Pine Ampule Serum,NaN,Rp. 300.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Amazing Pine Ampule Serum,Amazing Pine Ampule Serum_Serum & Essence
11191,Serum & Essence,9wishes,Extreme Oxygen Ampule Serum,NaN,Rp. 300.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Extreme Oxygen Ampule Serum,Extreme Oxygen Ampule Serum_Serum & Essence
11192,Mask Sheet,9wishes,Rice Water Sheet Mask,NaN,Rp. 45.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Rice Water Sheet Mask,Rice Water Sheet Mask_Mask Sheet
11193,Cream,9wishes,Rice Radiance Cream,NaN,Rp. 3.600,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Rice Radiance Cream,Rice Radiance Cream_Cream

In [24]:
product_df[['brand', 'product_name_concat']].duplicated().sum()

0

In [25]:
# menghapus kolom yang tidak diperlukan
product_df.drop(['product_name_variant_concat'], axis=1, inplace=True)

C:\Users\Owner\AppData\Local\Temp\ipykernel_11764\4126305895.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_df.drop(['product_name_variant_concat'], axis=1, inplace=True)

In [26]:
product_df

,subcategory,brand,product_name,variant,price,description,image_url,product_name_concat
0,Mask Sheet,A Bonne,Berry-Me-Baby Sheetmask,NaN,Rp. 10.000,sheetmask seri a bloom varian blueberry untuk ...,https://image.femaledaily.com/dyn/210/images/p...,Berry-Me-Baby Sheetmask_Mask Sheet
1,Wash-Off,A by BOM,Huppies,Milk Face Mask,Rp. 10.000,"menyembuhkan kulit kusam, efek anti-aging, men...",https://image.femaledaily.com/dyn/210/images/p...,Huppies_Milk Face Mask_Wash-Off
2,Wash-Off,A by BOM,Huppies Beet Root Face Mask,NaN,Rp. 6.000,masker organik yang memiliki claim :\r\n1. mem...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Beet Root Face Mask_Wash-Off
3,Wash-Off,A by BOM,Huppies Peel Off Mask,NaN,Rp. 8.000,Peel Off Mask 4 Varian :\r\n- Black Collagen\r...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Peel Off Mask_Wash-Off
4,Serum & Essence,A'kin,Certified Organic Rosehip Oil,NaN,Rp. 532.134,A'kin Certified Organic Rosehip Oil merupakan ...,https://image.femaledaily.com/dyn/210/images/p...,Certified Organic Rosehip Oil_Serum & Essence
...,...,...,...,...,...,...,...,...
11189,Serum & Essence,9wishes,Collagen Ampule Essence,NaN,Rp. 3.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Collagen Ampule Essence_Serum & Essence
11190,Serum & Essence,9wishes,Amazing Pine Ampule Serum,NaN,Rp. 300.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Amazing Pine Ampule Serum_Serum & Essence
11191,Serum & Essence,9wishes,Extreme Oxygen Ampule Serum,NaN,Rp. 300.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Extreme Oxygen Ampule Serum_Serum & Essence
11192,Mask Sheet,9wishes,Rice Water Sheet Mask,NaN,Rp. 45.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Rice Water Sheet Mask_Mask Sheet
11193,Cream,9wishes,Rice Radiance Cream,NaN,Rp. 3.600,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Rice Radiance Cream_Cream

### menangani data null pada description

In [27]:
# mengecek data kosong pada dataframe
product_df.isnull().sum()

subcategory               0
brand                     0
product_name              0
variant                9286
price                     0
description               1
image_url                 0
product_name_concat       0
dtype: int64

kolom variant akan dihapus karena sudah ada di kolom product_name_concat

In [28]:
# menghapus kolom yang tidak diperlukan
product_df.drop(['variant'], axis=1, inplace=True)

C:\Users\Owner\AppData\Local\Temp\ipykernel_11764\2326271020.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_df.drop(['variant'], axis=1, inplace=True)

In [29]:
product_df[product_df['description'].isna()]

,subcategory,brand,product_name,price,description,image_url,product_name_concat
1974,Skin Soothing Treatment,Cathy Doll,99% Snail and Gold Soothing Gel,Rp. 25.000,NaN,https://image.femaledaily.com/dyn/210/images/p...,99% Snail and Gold Soothing Gel_Skin Soothing ...

In [30]:
# hapus baris yang memiliki deskripsi kosong
product_df.dropna(subset=['description'], inplace=True)
product_df

C:\Users\Owner\AppData\Local\Temp\ipykernel_11764\2240214214.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_df.dropna(subset=['description'], inplace=True)

,subcategory,brand,product_name,price,description,image_url,product_name_concat
0,Mask Sheet,A Bonne,Berry-Me-Baby Sheetmask,Rp. 10.000,sheetmask seri a bloom varian blueberry untuk ...,https://image.femaledaily.com/dyn/210/images/p...,Berry-Me-Baby Sheetmask_Mask Sheet
1,Wash-Off,A by BOM,Huppies,Rp. 10.000,"menyembuhkan kulit kusam, efek anti-aging, men...",https://image.femaledaily.com/dyn/210/images/p...,Huppies_Milk Face Mask_Wash-Off
2,Wash-Off,A by BOM,Huppies Beet Root Face Mask,Rp. 6.000,masker organik yang memiliki claim :\r\n1. mem...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Beet Root Face Mask_Wash-Off
3,Wash-Off,A by BOM,Huppies Peel Off Mask,Rp. 8.000,Peel Off Mask 4 Varian :\r\n- Black Collagen\r...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Peel Off Mask_Wash-Off
4,Serum & Essence,A'kin,Certified Organic Rosehip Oil,Rp. 532.134,A'kin Certified Organic Rosehip Oil merupakan ...,https://image.femaledaily.com/dyn/210/images/p...,Certified Organic Rosehip Oil_Serum & Essence
...,...,...,...,...,...,...,...
11189,Serum & Essence,9wishes,Collagen Ampule Essence,Rp. 3.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Collagen Ampule Essence_Serum & Essence
11190,Serum & Essence,9wishes,Amazing Pine Ampule Serum,Rp. 300.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Amazing Pine Ampule Serum_Serum & Essence
11191,Serum & Essence,9wishes,Extreme Oxygen Ampule Serum,Rp. 300.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Extreme Oxygen Ampule Serum_Serum & Essence
11192,Mask Sheet,9wishes,Rice Water Sheet Mask,Rp. 45.000,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Rice Water Sheet Mask_Mask Sheet
11193,Cream,9wishes,Rice Radiance Cream,Rp. 3.600,There's no description for this product.,https://image.femaledaily.com/dyn/210/images/p...,Rice Radiance Cream_Cream

In [31]:
# hapus baris data yang mengandung kalimat There's no description for this product.
product_df = product_df[~product_df['description'].str.contains("There's no description for this product.")]
product_df

,subcategory,brand,product_name,price,description,image_url,product_name_concat
0,Mask Sheet,A Bonne,Berry-Me-Baby Sheetmask,Rp. 10.000,sheetmask seri a bloom varian blueberry untuk ...,https://image.femaledaily.com/dyn/210/images/p...,Berry-Me-Baby Sheetmask_Mask Sheet
1,Wash-Off,A by BOM,Huppies,Rp. 10.000,"menyembuhkan kulit kusam, efek anti-aging, men...",https://image.femaledaily.com/dyn/210/images/p...,Huppies_Milk Face Mask_Wash-Off
2,Wash-Off,A by BOM,Huppies Beet Root Face Mask,Rp. 6.000,masker organik yang memiliki claim :\r\n1. mem...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Beet Root Face Mask_Wash-Off
3,Wash-Off,A by BOM,Huppies Peel Off Mask,Rp. 8.000,Peel Off Mask 4 Varian :\r\n- Black Collagen\r...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Peel Off Mask_Wash-Off
4,Serum & Essence,A'kin,Certified Organic Rosehip Oil,Rp. 532.134,A'kin Certified Organic Rosehip Oil merupakan ...,https://image.femaledaily.com/dyn/210/images/p...,Certified Organic Rosehip Oil_Serum & Essence
...,...,...,...,...,...,...,...
11172,Serum & Essence,7am' Daisy,Intelligent Restoring Skin Booster,Rp. 114.000,7am Daisy Intelligent Restoring Skin Booster m...,https://image.femaledaily.com/dyn/210/images/p...,Intelligent Restoring Skin Booster_Serum & Ess...
11173,Serum & Essence,7am' Daisy,Rapid Brightening Skin Booster,Rp. 114.000,7am Daisy Rapid Brightening Skin Booster merup...,https://image.femaledaily.com/dyn/210/images/p...,Rapid Brightening Skin Booster_Serum & Essence
11174,Serum & Essence,7am' Daisy,Moisture Replenishing Skin Booster,Rp. 114.000,7am Daisy Moisture Replenishing Skin Booster m...,https://image.femaledaily.com/dyn/210/images/p...,Moisture Replenishing Skin Booster_Serum & Ess...
11175,Serum & Essence,7am' Daisy,Youthful Renewing Skin Booster,Rp. 114.000,7am Daisy Youthful Renewing Skin Booster merup...,https://image.femaledaily.com/dyn/210/images/p...,Youthful Renewing Skin Booster_Serum & Essence
11178,Face Mist,9wishes,Hydra Ampoule Toner,Rp. 300.000,This Hydra Ampule Toner instantly provides hyd...,https://image.femaledaily.com/dyn/210/images/p...,Hydra Ampoule Toner_Face Mist

In [32]:
product_df.isnull().sum()

subcategory            0
brand                  0
product_name           0
price                  0
description            0
image_url              0
product_name_concat    0
dtype: int64

In [33]:
product_df

,subcategory,brand,product_name,price,description,image_url,product_name_concat
0,Mask Sheet,A Bonne,Berry-Me-Baby Sheetmask,Rp. 10.000,sheetmask seri a bloom varian blueberry untuk ...,https://image.femaledaily.com/dyn/210/images/p...,Berry-Me-Baby Sheetmask_Mask Sheet
1,Wash-Off,A by BOM,Huppies,Rp. 10.000,"menyembuhkan kulit kusam, efek anti-aging, men...",https://image.femaledaily.com/dyn/210/images/p...,Huppies_Milk Face Mask_Wash-Off
2,Wash-Off,A by BOM,Huppies Beet Root Face Mask,Rp. 6.000,masker organik yang memiliki claim :\r\n1. mem...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Beet Root Face Mask_Wash-Off
3,Wash-Off,A by BOM,Huppies Peel Off Mask,Rp. 8.000,Peel Off Mask 4 Varian :\r\n- Black Collagen\r...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Peel Off Mask_Wash-Off
4,Serum & Essence,A'kin,Certified Organic Rosehip Oil,Rp. 532.134,A'kin Certified Organic Rosehip Oil merupakan ...,https://image.femaledaily.com/dyn/210/images/p...,Certified Organic Rosehip Oil_Serum & Essence
...,...,...,...,...,...,...,...
11172,Serum & Essence,7am' Daisy,Intelligent Restoring Skin Booster,Rp. 114.000,7am Daisy Intelligent Restoring Skin Booster m...,https://image.femaledaily.com/dyn/210/images/p...,Intelligent Restoring Skin Booster_Serum & Ess...
11173,Serum & Essence,7am' Daisy,Rapid Brightening Skin Booster,Rp. 114.000,7am Daisy Rapid Brightening Skin Booster merup...,https://image.femaledaily.com/dyn/210/images/p...,Rapid Brightening Skin Booster_Serum & Essence
11174,Serum & Essence,7am' Daisy,Moisture Replenishing Skin Booster,Rp. 114.000,7am Daisy Moisture Replenishing Skin Booster m...,https://image.femaledaily.com/dyn/210/images/p...,Moisture Replenishing Skin Booster_Serum & Ess...
11175,Serum & Essence,7am' Daisy,Youthful Renewing Skin Booster,Rp. 114.000,7am Daisy Youthful Renewing Skin Booster merup...,https://image.femaledaily.com/dyn/210/images/p...,Youthful Renewing Skin Booster_Serum & Essence
11178,Face Mist,9wishes,Hydra Ampoule Toner,Rp. 300.000,This Hydra Ampule Toner instantly provides hyd...,https://image.femaledaily.com/dyn/210/images/p...,Hydra Ampoule Toner_Face Mist

In [34]:
# simpan data yang telah dilakukan cleaning
product_df.to_csv('clean_skincare_product_2_1.csv', index=False)

In [38]:
product_df.shape

(9721, 7)

## Batasssss

### mapping nama product ke id numerik

In [35]:
# baca dataset product
data = pd.read_csv('clean_skincare_product_2_1.csv')
data

,subcategory,brand,product_name,price,description,image_url,product_name_concat
0,Mask Sheet,A Bonne,Berry-Me-Baby Sheetmask,Rp. 10.000,sheetmask seri a bloom varian blueberry untuk ...,https://image.femaledaily.com/dyn/210/images/p...,Berry-Me-Baby Sheetmask_Mask Sheet
1,Wash-Off,A by BOM,Huppies,Rp. 10.000,"menyembuhkan kulit kusam, efek anti-aging, men...",https://image.femaledaily.com/dyn/210/images/p...,Huppies_Milk Face Mask_Wash-Off
2,Wash-Off,A by BOM,Huppies Beet Root Face Mask,Rp. 6.000,masker organik yang memiliki claim :\r\n1. mem...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Beet Root Face Mask_Wash-Off
3,Wash-Off,A by BOM,Huppies Peel Off Mask,Rp. 8.000,Peel Off Mask 4 Varian :\r\n- Black Collagen\r...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Peel Off Mask_Wash-Off
4,Serum & Essence,A'kin,Certified Organic Rosehip Oil,Rp. 532.134,A'kin Certified Organic Rosehip Oil merupakan ...,https://image.femaledaily.com/dyn/210/images/p...,Certified Organic Rosehip Oil_Serum & Essence
...,...,...,...,...,...,...,...
9716,Serum & Essence,7am' Daisy,Intelligent Restoring Skin Booster,Rp. 114.000,7am Daisy Intelligent Restoring Skin Booster m...,https://image.femaledaily.com/dyn/210/images/p...,Intelligent Restoring Skin Booster_Serum & Ess...
9717,Serum & Essence,7am' Daisy,Rapid Brightening Skin Booster,Rp. 114.000,7am Daisy Rapid Brightening Skin Booster merup...,https://image.femaledaily.com/dyn/210/images/p...,Rapid Brightening Skin Booster_Serum & Essence
9718,Serum & Essence,7am' Daisy,Moisture Replenishing Skin Booster,Rp. 114.000,7am Daisy Moisture Replenishing Skin Booster m...,https://image.femaledaily.com/dyn/210/images/p...,Moisture Replenishing Skin Booster_Serum & Ess...
9719,Serum & Essence,7am' Daisy,Youthful Renewing Skin Booster,Rp. 114.000,7am Daisy Youthful Renewing Skin Booster merup...,https://image.femaledaily.com/dyn/210/images/p...,Youthful Renewing Skin Booster_Serum & Essence
9720,Face Mist,9wishes,Hydra Ampoule Toner,Rp. 300.000,This Hydra Ampule Toner instantly provides hyd...,https://image.femaledaily.com/dyn/210/images/p...,Hydra Ampoule Toner_Face Mist

In [36]:
# Impor library pandas
import pandas as pd

# Buat peta pemetaan (mapping) dari product_name ke ID numerik
unique_product_names = data['product_name_concat'].unique()
product_id_mapping = {product_name: id for id, product_name in enumerate(unique_product_names)}

# Tambahkan kolom 'product_id' ke DataFrame dengan ID numerik
data['product_id'] = data['product_name_concat'].map(product_id_mapping)
data

,subcategory,brand,product_name,price,description,image_url,product_name_concat,product_id
0,Mask Sheet,A Bonne,Berry-Me-Baby Sheetmask,Rp. 10.000,sheetmask seri a bloom varian blueberry untuk ...,https://image.femaledaily.com/dyn/210/images/p...,Berry-Me-Baby Sheetmask_Mask Sheet,0
1,Wash-Off,A by BOM,Huppies,Rp. 10.000,"menyembuhkan kulit kusam, efek anti-aging, men...",https://image.femaledaily.com/dyn/210/images/p...,Huppies_Milk Face Mask_Wash-Off,1
2,Wash-Off,A by BOM,Huppies Beet Root Face Mask,Rp. 6.000,masker organik yang memiliki claim :\r\n1. mem...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Beet Root Face Mask_Wash-Off,2
3,Wash-Off,A by BOM,Huppies Peel Off Mask,Rp. 8.000,Peel Off Mask 4 Varian :\r\n- Black Collagen\r...,https://image.femaledaily.com/dyn/210/images/p...,Huppies Peel Off Mask_Wash-Off,3
4,Serum & Essence,A'kin,Certified Organic Rosehip Oil,Rp. 532.134,A'kin Certified Organic Rosehip Oil merupakan ...,https://image.femaledaily.com/dyn/210/images/p...,Certified Organic Rosehip Oil_Serum & Essence,4
...,...,...,...,...,...,...,...,...
9716,Serum & Essence,7am' Daisy,Intelligent Restoring Skin Booster,Rp. 114.000,7am Daisy Intelligent Restoring Skin Booster m...,https://image.femaledaily.com/dyn/210/images/p...,Intelligent Restoring Skin Booster_Serum & Ess...,9276
9717,Serum & Essence,7am' Daisy,Rapid Brightening Skin Booster,Rp. 114.000,7am Daisy Rapid Brightening Skin Booster merup...,https://image.femaledaily.com/dyn/210/images/p...,Rapid Brightening Skin Booster_Serum & Essence,9277
9718,Serum & Essence,7am' Daisy,Moisture Replenishing Skin Booster,Rp. 114.000,7am Daisy Moisture Replenishing Skin Booster m...,https://image.femaledaily.com/dyn/210/images/p...,Moisture Replenishing Skin Booster_Serum & Ess...,9278
9719,Serum & Essence,7am' Daisy,Youthful Renewing Skin Booster,Rp. 114.000,7am Daisy Youthful Renewing Skin Booster merup...,https://image.femaledaily.com/dyn/210/images/p...,Youthful Renewing Skin Booster_Serum & Essence,9279
9720,Face Mist,9wishes,Hydra Ampoule Toner,Rp. 300.000,This Hydra Ampule Toner instantly provides hyd...,https://image.femaledaily.com/dyn/210/images/p...,Hydra Ampoule Toner_Face Mist,9280

In [37]:
# simpan dalam file csv
data.to_csv('clean_skincare_product_2_2.csv', index=False)