In [1]:
import pandas as pd

In [41]:
steam_data = pd.read_csv('filtered_games.csv')

In [36]:
steam_data

,AppID,Name,Estimated owners,Peak CCU,Required age,Price,About the game,Supported languages,Full audio languages,Windows,...,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Release date cleaned
0,20200,Galactic Bowling,0 - 20000,0,0,19.99,Galactic Bowling is an exaggerated and stylize...,['English'],[],True,...,0,0,0,0,Perpetual FX Creative,Perpetual FX Creative,"Single-player,Multi-player,Steam Achievements,...","Casual,Indie,Sports","Indie,Casual,Sports,Bowling",2008-10-21
1,655370,Train Bandit,0 - 20000,0,0,0.99,THE LAW!! Looks to be a showdown atop a train....,"['English', 'French', 'Italian', 'German', 'Sp...",[],True,...,0,0,0,0,Rusty Moyher,Wild Rooster,"Single-player,Steam Achievements,Full controll...","Action,Indie","Indie,Action,Pixel Graphics,2D,Retro,Arcade,Sc...",2017-10-12
2,1732930,Jolt Project,0 - 20000,0,0,4.99,Jolt Project: The army now has a new robotics ...,"['English', 'Portuguese - Brazil']",[],True,...,0,0,0,0,Campião Games,Campião Games,Single-player,"Action,Adventure,Indie,Strategy",NaN,2021-11-17
3,1355720,Henosis™,0 - 20000,0,0,5.99,HENOSIS™ is a mysterious 2D Platform Puzzler w...,"['English', 'French', 'Italian', 'German', 'Sp...",[],True,...,0,0,0,0,Odd Critter Games,Odd Critter Games,"Single-player,Full controller support","Adventure,Casual,Indie","2D Platformer,Atmospheric,Surreal,Mystery,Puzz...",2020-07-23
4,1659180,TD Worlds,0 - 20000,3,0,10.99,"TD Worlds is a dynamic, highly strategical gam...","['English', 'Russian', 'Danish']",[],True,...,0,0,0,0,MAKSIM VOLKAU,MAKSIM VOLKAU,"Single-player,Steam Achievements,Steam Cloud","Indie,Strategy","Tower Defense,Rogue-lite,RTS,Replay Value,Perm...",2022-01-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58846,2341640,Our Summer Festival,0 - 0,0,0,6.99,This summer fair is bursting with activities! ...,"['English', 'Japanese']",[],True,...,0,0,0,0,SAT-BOX,SAT-BOX,"Single-player,Multi-player,PvP,Shared/Split Sc...","Action,Casual,Indie,Sports",NaN,2023-04-02
58847,2125160,Prison Life 2,0 - 20000,6,0,10.79,Core Features Real players only! All Guards an...,"['English', 'French', 'Italian', 'German', 'Sp...",[],True,...,0,0,0,0,AO Games,AO Games,"Single-player,Multi-player,PvP,Online PvP,Co-o...","Casual,Indie,RPG,Simulation,Strategy","First-Person,Detective,Social Deduction,Multip...",2023-03-30
58848,2318860,Architecture Zeitgeist,0 - 20000,0,0,5.99,Architecture Zeitgeist is a game created with ...,"['English', 'Japanese', 'Portuguese - Brazil',...",[],True,...,0,0,0,0,Matheus Rudo,Rudo Studios,Single-player,"Casual,Simulation,Early Access","Casual,Simulation,Puzzle,Exploration,Immersive...",2023-03-27
58849,2180330,Girl's Way to Survive 2: Bloody Museum,0 - 0,0,0,2.39,"Development progress: prologue map (finished),...",['Simplified Chinese'],[],True,...,0,0,0,0,绅士游戏工坊,绅士游戏工坊,Single-player,"Action,Casual,Indie,RPG,Early Access",NaN,2023-04-02
58850,2352890,Hentai Ariel,0 - 20000,1,0,0.74,'Hentai Ariel' is a unique puzzle in which the...,"['English', 'French', 'Italian', 'German', 'Sp...",[],True,...,0,0,0,0,Cyber Keks,Cyber Keks,"Single-player,Steam Achievements","Casual,Indie",NaN,2023-03-30

In [9]:
# 데이터 타입 확인
steam_data.dtypes

AppID                           int64
Name                           object
Estimated owners               object
Peak CCU                        int64
Required age                    int64
Price                         float64
About the game                 object
Supported languages            object
Full audio languages           object
Windows                          bool
Mac                              bool
Linux                            bool
Metacritic score                int64
Metacritic url                 object
User score                      int64
Positive                        int64
Negative                        int64
Score rank                    float64
Recommendations                 int64
Notes                          object
Average playtime forever        int64
Average playtime two weeks      int64
Median playtime forever         int64
Median playtime two weeks       int64
Developers                     object
Publishers                     object
Categories                     object
Genres                         object
Tags                           object
Release date cleaned           object
dtype: object

In [42]:
# Estimated owners 열의 스트링 타입 데이터 'k - n'을 [int(k),int(n)] 으로 형식 전환

for i in range(0,len(steam_data)):
    val = steam_data['Estimated owners'][i].split('-')
    try:
        steam_data['Estimated owners'][i] = [int(val[0]), int(val[1])]
    except:
        print(i, ':',val)
    
steam_data

<ipython-input-42-a519f4ff3997>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steam_data['Estimated owners'][i] = [int(val[0]), int(val[1])]

,AppID,Name,Estimated owners,Peak CCU,Required age,Price,About the game,Supported languages,Full audio languages,Windows,...,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Release date cleaned
0,20200,Galactic Bowling,"[0, 20000]",0,0,19.99,Galactic Bowling is an exaggerated and stylize...,['English'],[],True,...,0,0,0,0,Perpetual FX Creative,Perpetual FX Creative,"Single-player,Multi-player,Steam Achievements,...","Casual,Indie,Sports","Indie,Casual,Sports,Bowling",2008-10-21
1,655370,Train Bandit,"[0, 20000]",0,0,0.99,THE LAW!! Looks to be a showdown atop a train....,"['English', 'French', 'Italian', 'German', 'Sp...",[],True,...,0,0,0,0,Rusty Moyher,Wild Rooster,"Single-player,Steam Achievements,Full controll...","Action,Indie","Indie,Action,Pixel Graphics,2D,Retro,Arcade,Sc...",2017-10-12
2,1732930,Jolt Project,"[0, 20000]",0,0,4.99,Jolt Project: The army now has a new robotics ...,"['English', 'Portuguese - Brazil']",[],True,...,0,0,0,0,Campião Games,Campião Games,Single-player,"Action,Adventure,Indie,Strategy",NaN,2021-11-17
3,1355720,Henosis™,"[0, 20000]",0,0,5.99,HENOSIS™ is a mysterious 2D Platform Puzzler w...,"['English', 'French', 'Italian', 'German', 'Sp...",[],True,...,0,0,0,0,Odd Critter Games,Odd Critter Games,"Single-player,Full controller support","Adventure,Casual,Indie","2D Platformer,Atmospheric,Surreal,Mystery,Puzz...",2020-07-23
4,1659180,TD Worlds,"[0, 20000]",3,0,10.99,"TD Worlds is a dynamic, highly strategical gam...","['English', 'Russian', 'Danish']",[],True,...,0,0,0,0,MAKSIM VOLKAU,MAKSIM VOLKAU,"Single-player,Steam Achievements,Steam Cloud","Indie,Strategy","Tower Defense,Rogue-lite,RTS,Replay Value,Perm...",2022-01-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58846,2341640,Our Summer Festival,"[0, 0]",0,0,6.99,This summer fair is bursting with activities! ...,"['English', 'Japanese']",[],True,...,0,0,0,0,SAT-BOX,SAT-BOX,"Single-player,Multi-player,PvP,Shared/Split Sc...","Action,Casual,Indie,Sports",NaN,2023-04-02
58847,2125160,Prison Life 2,"[0, 20000]",6,0,10.79,Core Features Real players only! All Guards an...,"['English', 'French', 'Italian', 'German', 'Sp...",[],True,...,0,0,0,0,AO Games,AO Games,"Single-player,Multi-player,PvP,Online PvP,Co-o...","Casual,Indie,RPG,Simulation,Strategy","First-Person,Detective,Social Deduction,Multip...",2023-03-30
58848,2318860,Architecture Zeitgeist,"[0, 20000]",0,0,5.99,Architecture Zeitgeist is a game created with ...,"['English', 'Japanese', 'Portuguese - Brazil',...",[],True,...,0,0,0,0,Matheus Rudo,Rudo Studios,Single-player,"Casual,Simulation,Early Access","Casual,Simulation,Puzzle,Exploration,Immersive...",2023-03-27
58849,2180330,Girl's Way to Survive 2: Bloody Museum,"[0, 0]",0,0,2.39,"Development progress: prologue map (finished),...",['Simplified Chinese'],[],True,...,0,0,0,0,绅士游戏工坊,绅士游戏工坊,Single-player,"Action,Casual,Indie,RPG,Early Access",NaN,2023-04-02
58850,2352890,Hentai Ariel,"[0, 20000]",1,0,0.74,'Hentai Ariel' is a unique puzzle in which the...,"['English', 'French', 'Italian', 'German', 'Sp...",[],True,...,0,0,0,0,Cyber Keks,Cyber Keks,"Single-player,Steam Achievements","Casual,Indie",NaN,2023-03-30

In [44]:
# 형식 바뀐 것 확인
steam_data.dtypes

AppID                           int64
Name                           object
Estimated owners               object
Peak CCU                        int64
Required age                    int64
Price                         float64
About the game                 object
Supported languages            object
Full audio languages           object
Windows                          bool
Mac                              bool
Linux                            bool
Metacritic score                int64
Metacritic url                 object
User score                      int64
Positive                        int64
Negative                        int64
Score rank                    float64
Recommendations                 int64
Notes                          object
Average playtime forever        int64
Average playtime two weeks      int64
Median playtime forever         int64
Median playtime two weeks       int64
Developers                     object
Publishers                     object
Categories                     object
Genres                         object
Tags                           object
Release date cleaned           object
dtype: object

In [48]:
# 저장
steam_data.to_csv('./kaggle_after_defining.csv')

In [49]:
# 확인
after_define = pd.read_csv('kaggle_after_defining.csv')
after_define.head()

,Unnamed: 0,AppID,Name,Estimated owners,Peak CCU,Required age,Price,About the game,Supported languages,Full audio languages,...,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Release date cleaned
0,0,20200,Galactic Bowling,"[0, 20000]",0,0,19.99,Galactic Bowling is an exaggerated and stylize...,['English'],[],...,0,0,0,0,Perpetual FX Creative,Perpetual FX Creative,"Single-player,Multi-player,Steam Achievements,...","Casual,Indie,Sports","Indie,Casual,Sports,Bowling",2008-10-21
1,1,655370,Train Bandit,"[0, 20000]",0,0,0.99,THE LAW!! Looks to be a showdown atop a train....,"['English', 'French', 'Italian', 'German', 'Sp...",[],...,0,0,0,0,Rusty Moyher,Wild Rooster,"Single-player,Steam Achievements,Full controll...","Action,Indie","Indie,Action,Pixel Graphics,2D,Retro,Arcade,Sc...",2017-10-12
2,2,1732930,Jolt Project,"[0, 20000]",0,0,4.99,Jolt Project: The army now has a new robotics ...,"['English', 'Portuguese - Brazil']",[],...,0,0,0,0,Campião Games,Campião Games,Single-player,"Action,Adventure,Indie,Strategy",NaN,2021-11-17
3,3,1355720,Henosis™,"[0, 20000]",0,0,5.99,HENOSIS™ is a mysterious 2D Platform Puzzler w...,"['English', 'French', 'Italian', 'German', 'Sp...",[],...,0,0,0,0,Odd Critter Games,Odd Critter Games,"Single-player,Full controller support","Adventure,Casual,Indie","2D Platformer,Atmospheric,Surreal,Mystery,Puzz...",2020-07-23
4,4,1659180,TD Worlds,"[0, 20000]",3,0,10.99,"TD Worlds is a dynamic, highly strategical gam...","['English', 'Russian', 'Danish']",[],...,0,0,0,0,MAKSIM VOLKAU,MAKSIM VOLKAU,"Single-player,Steam Achievements,Steam Cloud","Indie,Strategy","Tower Defense,Rogue-lite,RTS,Replay Value,Perm...",2022-01-09