#  Montagem do Google Drive e importação do Pandas

In [27]:
import pandas

#  Visualização dos dados

In [28]:
df = pandas.read_csv("data-aulapandas/sport-activity3.csv")

df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

#  Visualização dos dados inválidos

In [30]:
df[df['Calories'].isna()]

     Duration  Pulse  Maxpulse  Calories
17         45     90       112       NaN
27         60    103       132       NaN
91         45    107       137       NaN
118        60    105       125       NaN
141        60     97       127       NaN

#  Limpeza dos dados

In [31]:
df.dropna(inplace=True)
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[164 rows x 4 columns]

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 164 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  164 non-null    int64
 1   Pulse     164 non-null    int64
 2   Maxpulse  164 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 6.4 KB

#  Correlação dos dados

Um ótimo método do Pandas é o **corr()** que calcula a correlação entre cada coluna do dataset. O retorno da função **corr()** retorna uma tabela com valores entre 1 e -1. O valor 1 representa 100% de correlação entre os valores. No caso do valor -1 (negativo), significa que há 100% de correlação inversamente proporcional.

In [33]:
print(df.corr())

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.160661  0.005679  0.922717
Pulse    -0.160661  1.000000  0.784631  0.025121
Maxpulse  0.005679  0.784631  1.000000  0.203813
Calories  0.922717  0.025121  0.203813  1.000000