In [1]:
import numpy as np
import pandas as pd

In [6]:
df_train = pd.read_csv("Train_Data.csv")
df_train

,duration,protocoltype,service,flag,srcbytes,dstbytes,land,wrongfragment,urgent,hot,...,dsthostsamesrvrate,dsthostdiffsrvrate,dsthostsamesrcportrate,dsthostsrvdiffhostrate,dsthostserrorrate,dsthostsrvserrorrate,dsthostrerrorrate,dsthostsrvrerrorrate,lastflag,attack
0,0,tcp,netbios_dgm,REJ,0,0,0,0,0,0,...,0.06,0.06,0.00,0.00,0.00,0.00,1.00,1.00,21,1
1,0,tcp,smtp,SF,1239,400,0,0,0,0,...,0.45,0.04,0.00,0.00,0.11,0.00,0.02,0.00,18,0
2,0,tcp,http,SF,222,945,0,0,0,0,...,1.00,0.00,0.02,0.03,0.00,0.00,0.00,0.00,21,0
3,0,tcp,http,SF,235,1380,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,21,0
4,0,tcp,uucp_path,REJ,0,0,0,0,0,0,...,0.01,0.08,0.00,0.00,0.00,0.00,1.00,1.00,19,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86840,0,tcp,http,SF,216,674,0,0,0,0,...,1.00,0.00,0.01,0.03,0.01,0.01,0.00,0.00,21,0
86841,0,tcp,http,SF,368,1725,0,0,0,0,...,1.00,0.00,0.03,0.05,0.00,0.00,0.13,0.06,20,0
86842,28,tcp,ftp,SF,1483,4152,0,0,0,30,...,0.28,0.04,0.01,0.00,0.00,0.00,0.00,0.00,20,0
86843,0,tcp,smtp,SF,1679,385,0,0,0,0,...,0.16,0.08,0.00,0.00,0.69,0.00,0.01,0.00,18,0
86844,11343,tcp,telnet,SF,3396,16694,0,0,0,0,...,0.18,0.02,0.00,0.00,0.23,0.33,0.00,0.00,18,0

In [7]:
df_test = pd.read_csv("Test_Data.csv")
df_test

,duration,protocoltype,service,flag,srcbytes,dstbytes,land,wrongfragment,urgent,hot,...,dsthostsrvcount,dsthostsamesrvrate,dsthostdiffsrvrate,dsthostsamesrcportrate,dsthostsrvdiffhostrate,dsthostserrorrate,dsthostsrvserrorrate,dsthostrerrorrate,dsthostsrvrerrorrate,lastflag
0,0,tcp,mtp,REJ,0,0,0,0,0,0,...,7,0.03,0.08,0.00,0.00,0.0,0.0,1.0,1.0,20
1,0,tcp,http,SF,199,1721,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,21
2,0,tcp,discard,S0,0,0,0,0,0,0,...,14,0.05,0.09,0.00,0.00,1.0,1.0,0.0,0.0,18
3,0,tcp,telnet,S0,0,0,0,0,0,0,...,2,0.01,0.09,0.00,0.00,1.0,1.0,0.0,0.0,18
4,0,tcp,exec,S0,0,0,0,0,0,0,...,16,0.06,0.06,0.00,0.00,1.0,1.0,0.0,0.0,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21707,0,tcp,http,SF,273,4367,0,0,0,0,...,255,1.00,0.00,0.03,0.01,0.0,0.0,0.0,0.0,21
21708,0,udp,domain_u,SF,45,45,0,0,0,0,...,255,1.00,0.00,0.01,0.00,0.0,0.0,0.0,0.0,18
21709,0,tcp,imap4,S0,0,0,0,0,0,0,...,10,0.04,0.08,0.00,0.00,1.0,1.0,0.0,0.0,20
21710,0,tcp,ftp_data,SF,29,0,0,0,0,0,...,45,0.47,0.07,0.47,0.04,0.0,0.0,0.0,0.0,21
21711,0,tcp,private,S0,0,0,0,0,0,0,...,2,0.01,0.08,0.00,0.00,1.0,1.0,0.0,0.0,21

In [8]:
df_train.isna().sum()

duration                  0
protocoltype              0
service                   0
flag                      0
srcbytes                  0
dstbytes                  0
land                      0
wrongfragment             0
urgent                    0
hot                       0
numfailedlogins           0
loggedin                  0
numcompromised            0
rootshell                 0
suattempted               0
numroot                   0
numfilecreations          0
numshells                 0
numaccessfiles            0
numoutboundcmds           0
ishostlogin               0
isguestlogin              0
count                     0
srvcount                  0
serrorrate                0
srvserrorrate             0
rerrorrate                0
srvrerrorrate             0
samesrvrate               0
diffsrvrate               0
srvdiffhostrate           0
dsthostcount              0
dsthostsrvcount           0
dsthostsamesrvrate        0
dsthostdiffsrvrate        0
dsthostsamesrcportrate    0
dsthostsrvdiffhostrate    0
dsthostserrorrate         0
dsthostsrvserrorrate      0
dsthostrerrorrate         0
dsthostsrvrerrorrate      0
lastflag                  0
attack                    0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train = df_train.drop(['attack'], axis='columns')
y_train = df_train['attack']

In [11]:
y_train

0        1
1        0
2        0
3        0
4        1
        ..
86840    0
86841    0
86842    0
86843    0
86844    0
Name: attack, Length: 86845, dtype: int64

In [12]:
x_test = df_test
x_test

,duration,protocoltype,service,flag,srcbytes,dstbytes,land,wrongfragment,urgent,hot,...,dsthostsrvcount,dsthostsamesrvrate,dsthostdiffsrvrate,dsthostsamesrcportrate,dsthostsrvdiffhostrate,dsthostserrorrate,dsthostsrvserrorrate,dsthostrerrorrate,dsthostsrvrerrorrate,lastflag
0,0,tcp,mtp,REJ,0,0,0,0,0,0,...,7,0.03,0.08,0.00,0.00,0.0,0.0,1.0,1.0,20
1,0,tcp,http,SF,199,1721,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,21
2,0,tcp,discard,S0,0,0,0,0,0,0,...,14,0.05,0.09,0.00,0.00,1.0,1.0,0.0,0.0,18
3,0,tcp,telnet,S0,0,0,0,0,0,0,...,2,0.01,0.09,0.00,0.00,1.0,1.0,0.0,0.0,18
4,0,tcp,exec,S0,0,0,0,0,0,0,...,16,0.06,0.06,0.00,0.00,1.0,1.0,0.0,0.0,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21707,0,tcp,http,SF,273,4367,0,0,0,0,...,255,1.00,0.00,0.03,0.01,0.0,0.0,0.0,0.0,21
21708,0,udp,domain_u,SF,45,45,0,0,0,0,...,255,1.00,0.00,0.01,0.00,0.0,0.0,0.0,0.0,18
21709,0,tcp,imap4,S0,0,0,0,0,0,0,...,10,0.04,0.08,0.00,0.00,1.0,1.0,0.0,0.0,20
21710,0,tcp,ftp_data,SF,29,0,0,0,0,0,...,45,0.47,0.07,0.47,0.04,0.0,0.0,0.0,0.0,21
21711,0,tcp,private,S0,0,0,0,0,0,0,...,2,0.01,0.08,0.00,0.00,1.0,1.0,0.0,0.0,21

In [13]:
# Encoding categorical features
categorical_features = ['protocoltype', 'service', 'flag']
numerical_features = x_train.columns.difference(categorical_features)

In [14]:
numerical_features

Index(['count', 'diffsrvrate', 'dstbytes', 'dsthostcount',
       'dsthostdiffsrvrate', 'dsthostrerrorrate', 'dsthostsamesrcportrate',
       'dsthostsamesrvrate', 'dsthostserrorrate', 'dsthostsrvcount',
       'dsthostsrvdiffhostrate', 'dsthostsrvrerrorrate',
       'dsthostsrvserrorrate', 'duration', 'hot', 'isguestlogin',
       'ishostlogin', 'land', 'lastflag', 'loggedin', 'numaccessfiles',
       'numcompromised', 'numfailedlogins', 'numfilecreations',
       'numoutboundcmds', 'numroot', 'numshells', 'rerrorrate', 'rootshell',
       'samesrvrate', 'serrorrate', 'srcbytes', 'srvcount', 'srvdiffhostrate',
       'srvrerrorrate', 'srvserrorrate', 'suattempted', 'urgent',
       'wrongfragment'],
      dtype='object')

In [15]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

In [16]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),  # Apply StandardScaler to numerical features
        ('cat', OneHotEncoder(), categorical_features)  # Apply OneHotEncoder to categorical features
    ])

In [17]:
# Create pipeline
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier())
])

In [18]:
# Split data for validation
x_train_split, x_val_split, y_train_split, y_val_split = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

In [17]:
pipeline.fit(x_train_split, y_train_split)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['count', 'diffsrvrate', 'dstbytes', 'dsthostcount',
       'dsthostdiffsrvrate', 'dsthostrerrorrate', 'dsthostsamesrcportrate',
       'dsthostsamesrvrate', 'dsthostserrorrate', 'dsthostsrvcount',
       'dsthostsrvdiffhostrate', 'dsthostsrvrerrorrate',
       'dsthostsrvserrorrate', 'duration',...
       'numcompromised', 'numfailedlogins', 'numfilecreations',
       'numoutboundcmds', 'numroot', 'numshells', 'rerrorrate', 'rootshell',
       'samesrvrate', 'serrorrate', 'srcbytes', 'srvcount', 'srvdiffhostrate',
       'srvrerrorrate', 'srvserrorrate', 'suattempted', 'urgent',
       'wrongfragment'],
      dtype='object')),
                                                 ('cat', OneHotEncoder(),
                                                  ['protocoltype', 'service',
                                                   'flag'])])),
                ('classifier', RandomForestClassifier())])

In [20]:
# Validate model
y_val_pred = pipeline.predict(x_val_split)
y_val_pred

array(['neptune', 'normal', 'neptune', ..., 'neptune', 'neptune',
       'neptune'], dtype=object)

In [21]:
from sklearn.metrics import classification_report, accuracy_score

In [22]:
print(classification_report(y_val_split, y_val_pred))
print("Validation Accuracy: ", accuracy_score(y_val_split, y_val_pred))

              precision    recall  f1-score   support

     neptune       1.00      1.00      1.00      6607
      normal       1.00      1.00      1.00     10762

    accuracy                           1.00     17369
   macro avg       1.00      1.00      1.00     17369
weighted avg       1.00      1.00      1.00     17369

Validation Accuracy:  1.0

In [19]:
# Train on full training data
pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['count', 'diffsrvrate', 'dstbytes', 'dsthostcount',
       'dsthostdiffsrvrate', 'dsthostrerrorrate', 'dsthostsamesrcportrate',
       'dsthostsamesrvrate', 'dsthostserrorrate', 'dsthostsrvcount',
       'dsthostsrvdiffhostrate', 'dsthostsrvrerrorrate',
       'dsthostsrvserrorrate', 'duration',...
       'numcompromised', 'numfailedlogins', 'numfilecreations',
       'numoutboundcmds', 'numroot', 'numshells', 'rerrorrate', 'rootshell',
       'samesrvrate', 'serrorrate', 'srcbytes', 'srvcount', 'srvdiffhostrate',
       'srvrerrorrate', 'srvserrorrate', 'suattempted', 'urgent',
       'wrongfragment'],
      dtype='object')),
                                                 ('cat', OneHotEncoder(),
                                                  ['protocoltype', 'service',
                                                   'flag'])])),
                ('classifier', RandomForestClassifier())])

In [22]:
# Predicting on test data
predictions = pipeline.predict(x_test)
result=predictions
result

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

In [28]:
from sklearn.metrics import f1_score, recall_score, precision_score

In [24]:
# converting the result array into a dataframe
results = pd.DataFrame(result, columns=['Result'])

In [25]:
results

       Result
0           1
1           0
2           1
3           1
4           1
...       ...
21707       0
21708       0
21709       1
21710       0
21711       1

[21712 rows x 1 columns]

In [26]:
results.to_csv('my_actual_submission.csv', index=False)