In [1]:
"""
if you are familiar with requests , BeautifulSoup and some pandas
you will be fine following with my process of web scraping 
I have scraped (goodreads.com) this website  
"""
import requests as rq
from bs4 import BeautifulSoup

In [21]:
url = 'https://www.goodreads.com/list/show/544.Best_Non_Fiction_About_Music'
response = rq.get(url)

In [92]:
# using headers i am trying to imitate a real browser.
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    'Accept-Language': 'en-US,en;q=0.9',
}

url = 'https://www.goodreads.com/list/show/544.Best_Non_Fiction_About_Music'
response = rq.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Try finding regular <tr> tags

rows = soup.find_all('tr' , itemtype="http://schema.org/Book")

In [61]:
headings_list = []
authors_list = []
ratings_list = []
scores_list = []
for row in rows:
    heading = row.find('span' , itemprop="name").get_text()
    headings_list.append(heading)
    author = row.find("div" , class_ = 'authorName__container').find(
    'span' , 
        itemprop="name"
    ).get_text()
    authors_list.append(author)
    ratings = row.find('span' , class_ = "minirating").get_text()
    ratings_list.append(ratings)
    score = row.find('span' , class_ = "smallText uitext").find('a').get_text()
    scores_list.append(score)

In [ ]:
# now time for joining two codes that is where the fun aprt is

import requests as rq
from bs4 import BeautifulSoup

categories = [
    "romance", "fiction", "young-adult", "fantasy", "science-fiction",
    "non-fiction", "children", "history", "mystery", "covers", "horror",
    "historical-fiction", "gay", "titles", "best", "middle-grade", "paranormal",
    "queer", "nonfiction", "historical-romance", "love", "lgbt", "contemporary",
    "thriller", "lgbtq", "women", "biography", "title-challenge", "classics", "series"
    ]
headings_list = []
authors_list = []
ratings_list = []
scores_list = []
category = []

for category in categories :

    url = f'https://www.goodreads.com/list/tag/{category}'
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        'Accept-Language': 'en-US,en;q=0.9',
    }
    Response = rq.get(url , headers = headers)
    soup = BeautifulSoup(Response.text , 'html.parser')
    lists = soup.find_all('div' , class_ = "row")
    for lis in lists :
        url = lis.find('a' , class_="listTitle")
        urls = url['href']
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
            'Accept-Language': 'en-US,en;q=0.9',
        }
        response = rq.get(url_list, headers=headers)
        # the one is lower case letter r

        soup = BeautifulSoup(response.text, 'html.parser')

        rows = soup.find_all('tr' , itemtype="http://schema.org/Book")

        for row in rows:
            heading = row.find('span' , itemprop="name").get_text()
            headings_list.append(heading)
            author = row.find("div" , class_ = 'authorName__container').find(
            'span' , 
                itemprop="name"
            ).get_text()
            authors_list.append(author)
            ratings = row.find('span' , class_ = "minirating").get_text()
            ratings_list.append(ratings)
            score = row.find('span' , class_ = "smallText uitext").find('a').get_text()
            scores_list.append(score)

import pandas as pd
df = pd.DataFrame({'headings':headings_list , 'authorname':authors_list, 'rating':ratings_list, "scores":scores_list})

In [96]:
"""
i am going to have to see my data frame just to confirm its conf
"""
df

,headings,authorname,rating,scores
0,A Walk in the Woods: Rediscovering America on ...,Bill Bryson,"4.07 avg rating — 430,514 ratings","score: 5,552"
1,"Angela’s Ashes (Frank McCourt, #1)",Frank McCourt,"4.15 avg rating — 647,435 ratings","score: 3,339"
2,Becoming,Michelle Obama,"4.44 avg rating — 1,144,600 ratings","score: 3,143"
3,The Diary of a Young Girl,Anne Frank,"4.20 avg rating — 4,018,019 ratings","score: 3,062"
4,The Light We Carry: Overcoming in Uncertain Times,Michelle Obama,"4.27 avg rating — 92,969 ratings","score: 2,939"
...,...,...,...,...
1495,'Tis,Frank McCourt,"3.73 avg rating — 65,004 ratings",score: 561
1496,The Story of My Life,Helen Keller,"4.08 avg rating — 149,677 ratings",score: 522
1497,"With Love, The Argentina Family: Memories of T...",Mirta Ines Trupp,3.92 avg rating — 89 ratings,score: 500
1498,Steve Jobs: The Unauthorized Autobiography,J.T. Owens,"3.73 avg rating — 1,038 ratings",score: 500
1499,Signs of Life: To the Ends of the Earth with a...,Stephen Fabes,4.16 avg rating — 525 ratings,score: 500

In [98]:
# Now i should save it to csv so that later 
# I can do data cleaning using this data
df.to_csv('')

,headings,authorname,rating,scores
0,A Walk in the Woods: Rediscovering America on ...,Bill Bryson,"4.07 avg rating — 430,514 ratings","score: 5,552"
1,"Angela’s Ashes (Frank McCourt, #1)",Frank McCourt,"4.15 avg rating — 647,435 ratings","score: 3,339"
2,Becoming,Michelle Obama,"4.44 avg rating — 1,144,600 ratings","score: 3,143"
3,The Diary of a Young Girl,Anne Frank,"4.20 avg rating — 4,018,019 ratings","score: 3,062"
4,The Light We Carry: Overcoming in Uncertain Times,Michelle Obama,"4.27 avg rating — 92,969 ratings","score: 2,939"
...,...,...,...,...
1495,'Tis,Frank McCourt,"3.73 avg rating — 65,004 ratings",score: 561
1496,The Story of My Life,Helen Keller,"4.08 avg rating — 149,677 ratings",score: 522
1497,"With Love, The Argentina Family: Memories of T...",Mirta Ines Trupp,3.92 avg rating — 89 ratings,score: 500
1498,Steve Jobs: The Unauthorized Autobiography,J.T. Owens,"3.73 avg rating — 1,038 ratings",score: 500
1499,Signs of Life: To the Ends of the Earth with a...,Stephen Fabes,4.16 avg rating — 525 ratings,score: 500